### ISSUE TITLE
Deprecation warnings logged to console

### ISSUE THREAD

**Issue by alburdette619** [redux-saga/redux-saga#1000]
On updating to 1.5.3, I now receive the following error multiple times in my console:

`[...effects] has been deprecated in favor of all([...effects]), please update your code `

Stacktrace:

![screen shot 2017-05-24 at 11 14 28 am](https://cloud.githubusercontent.com/assets/22638838/26410810/4c6ad0fa-4072-11e7-9850-f4772892513a.png)

**Comment by jimbol** [comment]
This is due to the switch to the new [parallel effect combinator, `all`](https://redux-saga.js.org/docs/api/#alleffects---parallel-effects)

In the places where you are doing this
```es6
yield [
  call(effectA),
  call(effectB),
]
```
you have to do this instead
yield all([
  call(effectA),
  call(effectB),
])
```

**Comment by alburdette619** [comment]
@jimbol Thx!  I don't see anything about that in the release notes except maybe this item:

```
all effect - explicit effect for parallel effects, which is exactly what we had been supporting by accepting yielded arrays, so the latter is become deprecated now in favor of this explicitness which nicely maps to the Promise.all API. Please use this from now on
```

But that doesn't explicitly say it.  Either way thx again.

**Comment by Andarist** [comment]
Sorry for not being more explicit @alburdette619 . How would u improve the changelog regarding this?

**Comment by crazy4groovy** [comment]
releated to: https://github.com/redux-saga/redux-saga/issues/960

FWIW I can't find anywhere in my code that might be triggering this deprecation warning (ie. yielding an array of sagas); I've already fixed this part:

```
export default function* rootSaga() {
  yield effects.all(sagasArray);
}
```

**Comment by chrisnojima** [comment]
Ok so I think I found one root cause of this issue for us. 

If you do
```
function * myGenerator(params) {
  yield []
}

yield call(myGenerator, myParams)
```

The docs say

> If the result is not an Iterator object nor a Promise, the middleware will immediately return that value back to the saga, so that it can resume its execution synchronously.


So there's some ambiguity here. I intended this to be a value but it gets interpreted as an array of generators (i assume).

Instead, if you actually do

```
yield Promise.resolve([])
```

Then it does work fine.

**Comment by Andarist** [comment]
Thats one of the reason the API was made more explicit here, to avoid such ambiguity:)

**Comment by alburdette619** [comment]
@Andarist sorry, that is pretty explicit. I knew less of what I was talking about then.

**Comment by Andarist** [comment]
Could u elaborate? Im not sure if I understood what do u mean

**Comment by alburdette619** [comment]
Your changelog was plenty extensive, you can close this issue. Thanks!

**Comment by danstepanov** [comment]
@Andarist Based on the above, I'm not sure where the issue is occurring in my code. Perhaps `yield allSagas`?
<img width="985" alt="screen shot 2017-07-16 at 8 52 15 pm" src="https://user-images.githubusercontent.com/5482800/28255188-d45cce76-6a68-11e7-95e2-89246eefb2b7.png">

**Comment by Andarist** [comment]
@danstepanov yeah, its the culprit here, just change this to:
```js
yield effects.all(allSagas.map(saga => effects.fork(saga)))
```

**Comment by joaolavoier-luizalabs** [comment]
I've fixed all my code. But I still receiving the same log. 

```
YellowBox.js:80 [...effects] has been deprecated in favor of all([...effects]), 
please update your code
``` 

Before it was

``` js
function* fetchExampleOne() {
  yield call(api.fetchExampleOne());
}

function* fetchExampleTwo() {
  yield call(api.fetchExampleTwo());
}

const  mySagas = [
    takeLatest(actions.FETCH_EXAMPLE_ONE, fetchExampleOne);
    takeLatest(actions.FETCH_EXAMPLE_TWO, fetchExampleTwo);
 ];

export default function* rootSaga() {
  yield all([
    ...mySagas,
  ]);
}
```

To

``` js
function* fetchExampleOne() {
  yield call(api.fetchExampleOne());
}

function* mySagaOne() {
  yield takeLatest(actions.FETCH_EXAMPLE_ONE, fetchExampleOne);
}

function* fetchExampleTwo() {
  yield call(api.fetchExampleTwo());
}

function* mySagaTwo() {
  yield takeLatest(actions.FETCH_EXAMPLE_TWO, fetchExampleTwo);
}

export default function* rootSaga() {
  yield all([
    fork(mySagaOne),
    fork(mySagaTwo),
  ]);
}
```

**Comment by Andarist** [comment]
There are for sure some other places in ur app which yield arrays
