### ISSUE TITLE
Broken link in External Resources

### ISSUE THREAD

**Issue by nalekberov** [redux-saga/redux-saga#1001]
There is a link in the page, which is broken:

**The Definitive Guide to the JavaScript Generators by Gajus Kuizinas**

I could find another source to the content, it could be helpful to insert a link from Web Archive.

**Comment by Andarist** [comment]
@gajus is the article available somewhere on the web? :)

**Comment by erikvold** [comment]
https://github.com/gajus/gajus.com-blog/blob/master/posts/the-definitive-guide-to-the-javascript-generators/index.md ?

**Comment by gajus** [comment]
> https://github.com/gajus/gajus.com-blog/blob/master/posts/the-definitive-guide-to-the-javascript-generators/index.md ?

Thats correct. Sorry, didn't see the original notifications.

**Comment by Andarist** [comment]
Fixed, thank you guys :)

**Comment by nalekberov** [comment]
Thanks everyone for your time and effort!
