### ISSUE TITLE
How to get current state in my action creator?

### ISSUE THREAD

**Issue by ghoshnirmalya** [redux-saga/redux-saga#1002]
I've the following action creator 

```
export const addNewMedia = (media) => ({
  type: ADD_NEW_MEDIA,
  media,
});
```

This accepts a new `media` and appends it to the current state. This is how I'm handling it in the `reducer`:

```
case ADD_NEW_MEDIA:
  updatedState = state.get('medias').get('data');
  updatedState.push(action.media);
  
  return state
    .setIn(['medias', 'data'], updatedState)
    .set('hasNewMedia', false);
```

Now, I don't want this logic in my `reducer` and want to put this in my action creator. To do so, I'll need the current state of my app inside my `addNewMedia` action creator. 

How can I get my current state in the action creator?

**Comment by doortts** [comment]
@ghoshnirmalya I think you are confusing the core concept of Redux. Action creator should know payload and required state which is needed to change state. So, you must create a payload with the necessary state to create an action.

**Comment by ghoshnirmalya** [comment]
Yes. That's true. But, in redux-thunk, I can do something like:

```
export function getBlogs() {
  return (dispatch, getState) => {
    const project = getState().project.get('project'); // this would get the project state

    // ....
  };
}
```

Is this possible to do in redux-saga?

**Comment by doortts** [comment]
I think you should have written this way.

```
export function getBlogs(project) {
  return (dispatch) => {
    ...
    // ....
  };
}
```
Is there any reason to pass getState and get project in the action creator file?

**Comment by Andarist** [comment]
Its possible by splittin action in to 2. U listen for 1 in the saga (with take), use select effect, prepare ur second action and put (dispatch) it. Its an overkill though. U should be able to create the neccessary payload brfore dispatching in the first place

Also as thunk is rly lightweight u can mix both - thunk and saga

**Comment by ghoshnirmalya** [comment]
@doortts @Andarist thank you for your reply. I just didn't want to pass the `project` object as an argument to the `getBlogs` function as I wondered if there was any easy way (not an overkill process) of getting the state inside the `getBlogs` function.

If I've to pass it like @doortts suggested, then this issue can be closed.

**Comment by doortts** [comment]
@ghoshnirmalya : ) well, then, how about pass state itself with payload? In fact, I have never tried but technically it will (maybe) work

**Comment by ghoshnirmalya** [comment]
Just to mention before closing that what @doortts specified in https://github.com/redux-saga/redux-saga/issues/1002#issuecomment-304441705, works fine!

**Comment by maala** [comment]
export const ActionCreator = () => async (dispatch , state) => {
          console.log(state()) ;
} ;
simply pass second parameter to the actionCreator and you will access store state
