### ISSUE TITLE
How to handle when an action causes a saga side effect at scale

### ISSUE THREAD

**Issue by neurosnap** [redux-saga/redux-saga#1003]
As our application has grown, it has become less clear what actions end up triggering a saga, what actions end up in a reducer, and what actions do both.

The problem we are running into is when, for example, we dispatch `ADD_TODO` and we expect it to *just* hit the reducer, but in fact a saga is also listening to it, causing side effects we did not intend.

So I'm being confronted with a few questions:

* How do we properly label our actions to make it clear that when using it, it can cause side effects?
* How do we `ADD_TODO` without it hitting a saga for some cases, but in other cases it should hit a saga?

Currently we create a sister action that we list in our reducer, `ONLY_ADD_TODO` that our sagas don't listen to, but this feels like a quick fix.

Thoughts?

**Comment by jimbol** [comment]
Perhaps action creators could add a `role` of some sort, then saga middleware could check for that role.

```es6
createSagaMiddleware({
  emitter: emit => action => {
    if (!action.meta.role) return emit(action);
    
    if (action.meta.role === SAGA) {
      emit(action);
      return;
    }
  }
});
```
Then a higher order reducer could do a similar intercept on the reducer side

```es6
function todoReducer (state, action) {
  // ... normal reducer stuff
}

function createRoleReducer(reducer) {
  return function(state, action) {
    if (!action.meta.role) return reducer(state, action);
    if (action.meta.role === REDUCER) {
      return reducer(state, action);
    }
  }
}

createRoleReducer(todoReducer);
```

Which leaves us with the ability to do this
```es6
// only hits the saga
dispatch({
  type: ADD_TODO,
  meta: {
    role: SAGA,
  }
})

// only hits the reducer
dispatch({
  type: ADD_TODO,
  meta: {
    role: REDUCER,
  }
})

// hits the reducer and the saga
dispatch({
  type: ADD_TODO,
})
```

Is there an easier way of supporting "roles" like this?

**Comment by Andarist** [comment]
@jimbol what u have presented is already fairly easy and quite direct in the approach, abstraction would kill a clarity for this case here I think

the whole problem depends heavily on the application in place, i.e. i havent yet struggled with any problems with that - treating saga as completely external service which may listen on actions and cause side effects is working for me great so far

would rly need to know more about why 1 action needs sometimes trigger a saga and sometimes not, maybe they should be always split into 2 as they represent other state transitions?

**Comment by ms88privat** [comment]
@neurosnap https://medium.com/@marcelschulze/using-react-native-with-redux-and-redux-saga-a-new-proposal-ba71f151546f
Thats the way I did it so far. It's working great but a little bit of boilerplate.

**Comment by erikvold** [comment]
I think this is really left up to the developer using `redux-saga` and it's best not to offer a one solution fits all approach.  This is almost a coding style issue, it could be handled with abstractions, or action type namespacing, adding data to the redux state, and mixture of these, and more options.  

Like @Andarist pointed out the best solution likely depends on the application.

**Comment by erikvold** [comment]
@Andarist can we close this?
