### ISSUE TITLE
A flow-typed definition for v0.15.3

### ISSUE THREAD

**Issue by NameFILIP** [redux-saga/redux-saga#1006]
Looks like there is no flow-typed definition for the latest version. The last one I see is for https://github.com/flowtype/flow-typed/tree/master/definitions/npm/redux-saga_v0.13.x

**Comment by Andarist** [comment]
I would greatly appreciate the PR for this as Im not familiar with flow that much

**Comment by dvakatsiienko** [comment]
+1 on this. We started the migration to Flow two weeks ago. Would be awesome to have 0.15.3 support since 0.15.3 contains some new features that are missing in 0.13.*

**Comment by dvakatsiienko** [comment]
We actually would like to help on this, but we don't really have a lot of experience writing libdefs since we started to get in touch with Flow not so long ago. We are researching actively there is not so much rich information on the Internets at the moment of being. Please share if you have any materials about writing libdefs.

**Comment by neighborhood999** [comment]
I just find v0.14.x libdefs: [here](https://github.com/tai2/redux-saga-take-latest-typing-example/blob/master/flow-typed/npm/redux-saga_v0.14.x.js)

**Comment by dvakatsiienko** [comment]
@neighborhood999 Thank you!

**Comment by TomiS** [comment]
I create a gist of [**0.15.x** types](https://gist.github.com/TomiS/feabd0da885c4cf61065c258ef144ed8). I did it by modifying 0.13 types against my own project repository because I wasn't able to make flow-typed tests run correctly in reasonable time, so that's why it's not tested properly and might be incomplete.

**Comment by philipchmalts** [comment]
@TomiS just imported this into my own flow typings and I'm getting `identifier `Saga0` Could not resolve name` as error, looks like it is used in takeEvery and takeLatest

**Comment by TomiS** [comment]
@philipchmalts Hmm, could it be because `Saga0` is now defined in root module and takeLatest/Every is defined in effects module... Weird it doesn't error in my repo.

**Comment by TomiS** [comment]
@philipchmalts I think I managed to improve it a bit. See https://gist.github.com/TomiS/feabd0da885c4cf61065c258ef144ed8/revisions

**Comment by philipchmalts** [comment]
@TomiS Thanks for taking a look at this and getting back to me, it appears the error I mentioned earlier is now gone but now I am getting `itentifier FsmIterator cannot not resolve name`. I think its a similar issue of scoping redux-saga/effects.

**Comment by cef62** [comment]
@philipchmalts I don't know if you already resolved the issue but for me it worked simply moving `FsmIterator` outside the `redux-saga` module declaration.

**Comment by Andarist** [comment]
Thanks to the great work by @Alxandr, `flow-typed` has now updated [`redux-saga` typings](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/redux-saga_v0.16.x/flow_v0.56.0-/redux-saga_v0.16.x.js). Closing the issue now, if there are any problems with new typings, please report them here by creating a new issue or fix them in `flow-typed` repository.

If you have any suggestions on what is the best way to incorporate typings directly into `redux-saga` repository - please let me know. From what I understand the biggest problem is that typings are targeting specified range of flow versions and having them directly in the repository kinda locks them down to that range and might cause problems for people using versions from outside the range.
