### ISSUE TITLE
Bump version to 1.x.x

### ISSUE THREAD

**Issue by NameFILIP** [redux-saga/redux-saga#1007]
Have you guys considered bumping the major version to 1?
"If a project is going to be shared with others, it should start at 1.0.0, though some projects on npm don't follow this rule." - https://docs.npmjs.com/getting-started/semantic-versioning

P.S. Npm has different behavior for `^0.x.x` vs `^1.x.x`.

**Comment by Andarist** [comment]
Yes, we are going to bump to v1 once i finish work on multicast channel (already in PRs)
