### ISSUE TITLE
Is the push model redundant?

### ISSUE THREAD

**Issue by bryankang** [redux-saga/redux-saga#1008]
From my limited experience using this nifty library, I'm able to do just about everything with the pull model using an infinite while loop. 

What are some good guidelines or examples of when to use one over the other?

**Comment by Andarist** [comment]
Aint sure if i understand correctly, but saga in general is pull-only. Do u have any particular pattern in mind?

**Comment by bryankang** [comment]
Disregard - looks like it was my misunderstanding of saga helpers. Thanks for the clarification!
