### ISSUE TITLE
Share data between sagas

### ISSUE THREAD

**Issue by Nosherwan** [redux-saga/redux-saga#1013]
I need to share the history object required by react-router with the sagas.
We have different apps each having a different type of history (browser, hash etc), and we are injecting history into a function that returns the root sagas which is in a separate project.
The rootSagas module keeps a shared history object inside.
Now we have decided to separate out the sagas from within the rootSagas module hence the challenge how to share the history object with different saga modules.
 
Some options are:
1. Pass the history via action payload, which will be repetitive from each event handler in the components.
2. Some how bind the history to each generator, not very straight forward.

I was wondering if there is a generic way of sharing some data or object among different sagas:

Current method:

```javascript

//rootSagas.js
const getRootSaga = history => {
	_history = history;
	return function* rootSaga() {
		yield [
			loginFlow(),
			watchAndLog(),
			registrationSaga(),
			fetchPortfolioSaga(),
			searchCompanySaga(),
			addCompanySaga(),
			removeCompanySaga(),
			switchPortfolioSaga()
		];
	};
};

export default getRootSaga;

//in configureStore.js

export default function configureStore(initialState) {
	//... create store code

//passing history
	sagaMiddleware.run(getRootSaga(history));
	
	return store;
}

```

**Comment by aikoven** [comment]
The Context feature might solve your problem, see https://github.com/redux-saga/redux-saga/pull/735

**Comment by Nosherwan** [comment]
Thanks @aikoven  that is exactly what I needed :)
