### ISSUE TITLE
Low-level takeEvery blocks other sagas

### ISSUE THREAD

**Issue by IceOnFire** [redux-saga/redux-saga#1016]
Hi,

While implementing CRUD operations I noticed that this code works perfectly:

```js
function* rootSaga() {
  yield takeEvery(INSERT_DATA, insertDataSaga)
  yield takeEvery(FETCH_DATA, fetchDataSaga)
  yield takeEvery(UPDATE_DATA, updateDataSaga)
  yield takeEvery(REMOVE_DATA, removeDataSaga)
}
```

but when I try to replace the second `takeEvery` effect with my own implementation, taken from the [docs](https://redux-saga.js.org/docs/advanced/Concurrency.html):

```js
function* myOwnTakeEvery(pattern, saga, ...args) {
  const task = yield fork(function*() {
    while (true) {
      const action = yield take(pattern)
      yield fork(saga, ...args.concat(action))
    }
  })
  return task
}

function* rootSaga() {
  yield takeEvery(INSERT_DATA, insertDataSaga)
  yield myOwnTakeEvery(FETCH_DATA, fetchDataSaga)
  yield takeEvery(UPDATE_DATA, updateDataSaga)
  yield takeEvery(REMOVE_DATA, removeDataSaga)
}
```

then the first two sagas are called as always but the second two aren't anymore.

Am I wrongly using the low level example? I'm using redux-saga@0.15.3.

Antony

**Comment by Andarist** [comment]
Actually `takeEvery` implementation is closer to:
```js
const takeEvery = (pattern, saga, ...args) => fork(function*() {
	while (true) {
		const action = yield take(pattern)
		yield fork(saga, ...args.concat(action))
	}
})
```

**Comment by IceOnFire** [comment]
You're absolutely right, this works as expected! Maybe we should update the docs accordingly, would you like me to do it?

**Comment by Andarist** [comment]
Sure, please do, would be greatly appreciated. Please check also if there are such low-level examples of `throttle` and `takeLatest` and update them too if neccessary :)

**Comment by IceOnFire** [comment]
Incoming PR ;)

**Comment by IceOnFire** [comment]
@Andarist Fixes to the docs should be pushed in the `gh-pages` branch to be effectively pubilshed, is there a best practice we should follow?

**Comment by Andarist** [comment]
I just rely on myself to publish them manually because not everything which gets to the master needs to be published asap, sometimes i merge new features etc and cannot publish updated docs for such cases. Feel free to suggest better workflow - would be great to have this automated reliably

**Comment by IceOnFire** [comment]
By having a look in the `package.json` I found a `docs:publish` script. If that's the way you use to publish docs then I have no better suggestions :)

**Comment by Andarist** [comment]
Yeah, task is in place, just need to be ran manually. Gonna do this later tomorrow

**Comment by ericwooley** [comment]
For those of you who came here because you didn't realize take every *wasn't* blocking, here is my quick and dirty implementation of a blocking one. 

```
// this is hard to type, so were just stealing take every types
const blockingTakeEvery: typeof takeEvery = (
  patternOrChannel: any,
  saga: any,
  ...args: any[]
) =>
  call(function* () {
    while (true) {
      const action = yield take(patternOrChannel)
      yield fork(saga, ...args.concat(action))
    }
  }) as any
```

It would be really convenient to have an official equivalent.

**Comment by Andarist** [comment]
It doesnt seem to make much sense to have a blocking takeEvery - it wont ever unblock, so what's the point? If you don't want to execute any lines following `takeEvery` then just make it the last effect within your saga

**Comment by ericwooley** [comment]
@Andarist 

I'll write you a simplified example for how I am using it. In my case, I am using peerjs and channels. 

```ts
function *peerComSaga(myPeerId: string) {
   // peer will manage multiple connections from multiple peers.
   const peer = new Peer(myPeerId)
   // emits connections whenever there is an incoming connection.
   const connectionChannel = call(createConnectionChannel, peer)

  // ... a few other forks and channels with peer
  try {
    // it's nice that this blocks so that when this saga is cancelled, the cleanup happens. Otherwise we need to do a while true loop
    // with a take and fork. 
    yield blockingTakeEvery(connectionChannel, peerDataConnectionSaga)
  } finally {
    peer.destroy()
  }
}
```
