### ISSUE TITLE
Uncaught at saga

### ISSUE THREAD

**Issue by matthiasprieth** [redux-saga/redux-saga#1018]
Hey I get this error and don't know how to better debug or what the problem is. I tried different redux-saga versions but the problem still persists. 
I'm pretty sure I did not have this problem more than 1-2 weeks ago. I also tried to check out older git commits, but the problem still exists. 
It's also interesting that i can login so loginSuccess/loginFail actions get dispatched. So the app is working ayway, I just get those strange errors. 

![screenshot_20170606-174157](https://user-images.githubusercontent.com/4509289/26868351-08059ef2-4b69-11e7-82f8-524e63fd07f9.png)
I don't even know what I've changed from the first error to the second, but i think just another redux-saga version.
![screenshot_20170606-175825](https://user-images.githubusercontent.com/4509289/26868357-0d2c93e0-4b69-11e7-9e51-f741262ace1e.png)

Strange is also that in reactotron the Saga/Effect(s) is `undefined`
![image](https://user-images.githubusercontent.com/4509289/26868784-6f9948f6-4b6a-11e7-9eb0-d27316de73fb.png)

**Comment by matthiasprieth** [comment]
Maybe it's also related to this issue: https://github.com/redux-saga/redux-saga/issues/1004

**Comment by Andarist** [comment]
could u share a repo with reproduced issue? its really hard to help with such bare description

**Comment by matthiasprieth** [comment]
Unfortunately I dont have a public repo, but I uploaded an old version where I have the same problem.
https://github.com/matthiasprieth/redux-saga-uncaught-problem

Would be awesome if you could check it out. Cause I'm still having the same problem since hours. To test it 'click' on the 'STOREBOX APP'-button then on 'LoginScreen' and then on Sign In. Normaly you should see the message `NORMAL LOGIN FAILED wrong user data etc.` but instead I get the Uncaught error as described above.

**Comment by Andarist** [comment]
Cannot quite run the app, have no react-native experience, had installed it to play with long time ago but didnt have really time to use it. Could u specify how should i run the project? What non `node_modules` stuff I need to have installed?

**Comment by matthiasprieth** [comment]
I guess the first thing you need is:
- the latest JDK, Android SDK and setting ANDROID_HOME environment variable (https://facebook.github.io/react-native/releases/0.23/docs/android-setup.html)
- install react-native: npm install -g react-native-cli
- build and run app: react-native run-android

**Comment by Andarist** [comment]
That a lot of setup for me for now, wont be able to check this too soon. However you should be able to debug this quite easily by setting up a breakpoint [here](https://github.com/redux-saga/redux-saga/blob/7929507cbc26c3c227d26402ff68145ac8a3c0bb/src/internal/utils.js#L150) and investigating the state of whats getting logged exactly. 

By inspecting the code I guess there might be some problem with `AsyncStorage`, `api` or `reducers`. You can investigate this with `console.log` like this:
```js
// attempts to login
export function * login (api, action) {
  const { username, password } = action
  let response
  
  try {
    response = yield call(api.login, username, password)
  } catch (err) {
    console.log('1', err)
  }  

  if(response.ok){
    //set headers
    const userData = response.data
    const token = userData.token

    try {
      yield AsyncStorage.setItem('@AppLocalStorage:token', token)
    } catch (err) {
      console.log('2', err)
    }

    try {
      yield call(api.setHeader, 'Authorization', `Bearer ${token}`)
    } catch (err) {
      console.log('3', err)
    }
    
    try {
      // dispatch successful logins
      yield put(LoginActions.loginSuccess(userData))
    } catch (err) {
      console.log('4', err)
    }    
  } else {
    try {
      // dispatch failure
      yield put(LoginActions.loginFailure('NORMAL LOGIN FAILED wrong user data etc.'))
    } catch (err) {
      console.log('5', err)
    }
  }
}
```

**Comment by skellock** [comment]
I think this might be a Reactotron bug that [we recently fixed](https://github.com/infinitered/reactotron/issues/430).

We're monkeypatching (lulz) `AsyncStorage` so we can track it.  When we swizzled we forgot to return the promise.  So up above (where you work with AsyncStorage), you're yielding undefined. 😱 

Can you update your `reactotron-redux-saga` and try again?  

Sorry about that!  Programming is hard.

**Comment by matthiasprieth** [comment]
My `reactotron-redux-saga` is at `v1.11.1` so latest. hm.. maybe I understand something wrong, but when I `yield call(AsyncStorage.setItem('@AppLocalStorage:token', token))` i get `Error: call: argument [object Object] is not a function` so the `AsyncStorage` was always fine for me before. I had no problem with that.

**Comment by Andarist** [comment]
aint sure exactly if thats the problem but u probably should use for this AsyncStorage call such form:
```js
yield call([AsyncStorage, 'setItem'], '@AppLocalStorage:token', token)
```

**Comment by Andarist** [comment]
If you still encounter the issue, please respond back. Closing at the issue got stale and you have not followed up to the last comment.

**Comment by incorvia** [comment]
For future reference for anyone that finds this helpful.. for me, I just forgot to import "call" ...
