### ISSUE TITLE
take from eventChannel and actions at the same time

### ISSUE THREAD

**Issue by nico1510** [redux-saga/redux-saga#1020]
Is there a way to simultaneously take whichever event comes fist in an eventChannel or from a plain action ?
I'm trying to do something like this:

```javascript
let lastTask;
   while (true) {
      const { user, error, cancel } = yield take([eventChannel, CANCEL_ACTION]);
      if (cancel) {
          yield cancel(lastTask);
       } else {
          lastTask = yield fork(handleUserSync, user, error);
       }
 }
```

The eventChannel emits `{user}` or `{error}` while the `CANCEL_ACTION` has `{cancel: true}` payload. Mixing event channel actions and regular actions doesn't seem to work though... Is this supported or can it be achieved in a different way maybe ?

**Comment by jimbol** [comment]
Perhaps `race` is what you're looking for. [Heres the official guide](https://redux-saga.js.org/docs/advanced/RacingEffects.html).

**Comment by nico1510** [comment]
yes something like `race` but for **receiving** actions instead of calling effects...

**Comment by jimbol** [comment]
Perhaps I'm missing some nuance of event channels but this should be possible
```es6
const { actionA, actionB } = yield race({
  actionA: take(ACTION_A),
  actionB: take(ACTION_B)
});

if (actionA) {
  console.log('A won');
} else if (actionB) {
  console.log('B won');
}
```

**Comment by nico1510** [comment]
aahh that's how it can be done :) Thank you very much ;)
