### ISSUE TITLE
IE8 redux-saga blank page

### ISSUE THREAD

**Issue by Thomas080304** [redux-saga/redux-saga#1022]
when i test page in IE8,it got a blank page. i location the error in source code like below:
(redux-saga\src\internal\channel.js)
return { take: take, put: put, flush: flush, close: close,
    get __takers__() {
       return takers;
    },
    get __closed__(){
      return closed;
   }
};
IE told me need “:” below get!
is it babel error? how to fix it.thanks

**Comment by Andarist** [comment]
Getters and setters are part of ES5, which is not supported in ie8.

We do not plan to support such outdated browser, most modern tooling is dropping support for those, including React. If you need this to work under IE8 u probably need to setup babel transform for redux-saga which will transform to ES3 + provide a global Promise polyfill (as its used too under the hood - for a `delay` helper, which is superb useful so you probably want to use it).

**Comment by Thomas080304** [comment]
@Andarist, thanks for your help. i add "es3ify","babel-polyfill","es5-shim","es5-shim/es5-sham",still not work.
what is suggestion for babel transform for redux-saga?

**Comment by Andarist** [comment]
U would have to share ur bundler config so i could suggest something. Have u added this transform for redux-saga which is in node_modules? Its usually ignored to speed up dev experience
