### ISSUE TITLE
Typescript support requires "es2015.iterable" lib

### ISSUE THREAD

**Issue by letharion** [redux-saga/redux-saga#1029]
If you end up here from google needing help, check out the [`--lib`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) setting and make sure you have `es2015.iterable` enabled.

I'm guessing that `es2015.iterable` is included in the default configuration, and this is a somewhat rare issue.

In my case however, it was not a part of the included libs, and so compilation failed for me as follows:

```
error TS2345: Argument of type '() => IterableIterator<ForkEffect>' is not assignable to parameter of type 'Saga0'.
  Type 'IterableIterator<ForkEffect>' is not assignable to type 'Iterator<any>'.
    Property 'next' is missing in type 'IterableIterator<ForkEffect>'
```

I struggled for a while with digging through the `d.ts` but not getting anywhere. Turns out there was a simple solution, so I wanted to post it here.

**Comment by letharion** [comment]
Leaving the issue open so a maintainer can decide if anything needs to be done, but as far as I'm concerned, it can be closed as is. :)

**Comment by Andarist** [comment]
@aikoven should it get documented or closed?

**Comment by aikoven** [comment]
I think it can be closed now because typings work fine with default TS config. We could consider adding docs if there's a demand.

**Comment by letharion** [comment]
@aikoven Looking at the documention again it says

> The default library injected is: 
> ► For --target ES5: DOM,ES5,ScriptHost
> ► For --target ES6: DOM,ES6,DOM.Iterable,ScriptHost

So if you're targetting ES6, it's on by default, but if you're targetting ES5, then it's not.

**Comment by Andarist** [comment]
I would prefer to just close it now, people should be able to find this issue to solve their issues in the future

@letharion ofc I would gladly accept a PR with an explanation if you can provide one :)

**Comment by rplotkin** [comment]
This is NOT easy to find. Can it not at least be mentioned in the typings file?

**Comment by Andarist** [comment]
info about it is here https://github.com/redux-saga/redux-saga#typescript
