### ISSUE TITLE
Testing sagas with Jest

### ISSUE THREAD

**Issue by PhilipTheVictor** [redux-saga/redux-saga#1034]
How will I test the saga given below:
function *mySaga({ payload })   {
try {
const { data } = yield call(api.someApi, payload);
yield put(mySagaSuccess({
data,
})
);
}
catch(error){
yield put(mySagaFailure(error));
}
}

**Comment by ssynix** [comment]
I found [`redux-saga-test-plan`](https://github.com/jfairbank/redux-saga-test-plan/) super useful in testing sagas.

Unlike `redux-saga` docs, it focuses on testing what goes into and out of your sagas, instead of a specific chain of effects.
