### ISSUE TITLE
redux saga run other middleware before get into sagaMiddleware

### ISSUE THREAD

**Issue by stefensuhat** [redux-saga/redux-saga#1037]
First things first. Sorry for posted it here, I already stuck for 2 days to make this things works.

I have this codes:

    // jwtmiddleware.js //

    function createJwtMiddleware() {
	    return ({ dispatch, getState }) => (next) => (action) => {
	        const auth = getState().auth;
	        if (typeof action === 'function') {
	            if (auth && auth.token) {
	                const exp = jwtDecode(auth.token).exp;

	                const tokenExpiration = moment.unix(exp);
	                if (tokenExpiration && (
	                        tokenExpiration.diff(moment(), 'm') <= 8
	                    )) {
	                    return authPromise(dispatch).then(() => setTimeout(next(action), 250));
	                }
	            }
	        }

	        return next(action);
	    };

	}

And put it into store.js:

    const middlewares = [
	    jwt,
	    thunk,
	    routerMiddleware(history),
	    sagaMiddleware,
	];
    const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__;

	const store = createStore(reducer, composeEnhancers(applyMiddleware(...middlewares)));
    export default store;

my saga:

	export function menuRequest() {
	    return { type: FETCH_MENU_REQUEST };
	}

	function fetchMenu() {
	    return new Promise((resolve, reject) => {
	        request.get('/menus')
	            .then((response) => resolve(response))
	            .catch((error) => reject(error))
	    })
	}

	export function* handleFetchMenu() {
	    try {
	        const payload = yield call(fetchMenu);

	        yield put({ type: FETCH_MENU_SUCCESS, payload });
	    } catch (e) {
	        yield put({ type: FETCH_MENU_FAILED, e });
	    }
	}

	export function* watchMenu() {
	    yield takeEvery(FETCH_MENU_REQUEST, handleFetchMenu);
	}

Rootsaga.js:

    

	export default function* Root() {
	    yield all([
	        fork(watchLoginRequest),
	        fork(watchMenu),
	    ])
	}

the problem is it never enter to jwtmiddleware for any saga call. If I use redux thunk it runs properly. 

The flow of this code is: before saga attempt to `fetchAnyCall` it will check for current jwt token if its need to be refresh (will update the token) or already expired (will redirect to login page).

is there any possible solution to make this code works? or any other flow for checking token for every call with redux saga?

**Comment by Andarist** [comment]
its because u are running ur `fetch` via `call`, which only executes it, personally I would make a request saga which would include ur jwt token logic, instead of having it in ur middleware chain, but ofc u can integrate those quite easily

the problem with ur code is that u do not dispatch (from the saga) ur request functions, so they do not reach obviously ur middleware, you should try `yield put.resolve(fetchMenu)`

**Comment by stefensuhat** [comment]
@Andarist `yield put.resolve(fetchMenu)` solve my problems perfectly!.

> personally I would make a request saga which would include ur jwt token logic

can you lights me up more about this?

Thanks man!

**Comment by Andarist** [comment]
Well, it kinda depends how do u want to structure ur sagas and how do handle ur actions, how much are they event-induced or how much they are like commands?

If they are commands you could have a single `REQUEST` type which would describe in its payload what request should be made and then you could make something like this:
```js
function* makeRequest({ payload }) {
    const { auth } = yield select()
    
    // handle here ur auth.token
    // im not really sure right now from the provided snippet whats ur logic

    try {
        const constructedRequest = // ... construct a request from ur payload
        const result = yield call(constructedRequest);

        yield put({ type: REQUEST_SUCCESS, payload: result });
    } catch (e) {
        yield put({ type: REQUEST_FAILED, e });
    }
}

yield takeEvery(REQUEST, makeRequest)
```

Or if you have it more signal based you can do it like this
```js
const withToken = (saga, ...args) => {
    return function* (action) {
        const { auth } = yield select()
        // handle ur token generic logic however u want
        yield call(saga, ...args, token, action)
    }
}

yield takeEvery(FETCH_MENU_REQUEST, withToken(handleFetchMenu))
```

**Comment by stefensuhat** [comment]
@Andarist thanks for the help!. I'm gonna try this out. will close this.
