### ISSUE TITLE
How to check if page is loading from the component?

### ISSUE THREAD

**Issue by ivanakimov** [redux-saga/redux-saga#1040]
Right now I have this strategy implemented:

1. Component loads + dispatches an action to call an API
2. The sagas handling the request will save API progress in a state, something like this:

```json
requests: {
  "/v1/page/get?param1=value1": {
    "loading": true,
    "loaded": false,
    "error": null
  }
}
```

3. When the page is loaded, the data is saved + the request state is updated. All of that is working good so far.

The problem is I'm not sure how to write `isPageLoading()` function... How can I call an asynchronous saga from my component? The reason I can't just check the state directly from the component is because my API URLs are "assembled" inside the saga, like that:

```javascript
function*() {
  const site = yield select(getSelectedSite);
  return {
    method: 'GET',
    route: `/v1/site/${site}`
  };
}
```
...and it's baked into the `request` which is inside other sagas. So is there any way to call an asynchronous function from the component? Or how are these functions usually written?

**Comment by Andarist** [comment]
So you dispatch an action like `SELECT_SITE` in smth like `componentDidMount` of the component and the data might be available right away (from the state) or asynchronously (needs to be fetched with saga)? And you are unsure how to write a selector for `isPageLoading`?

Im not quite sure if Ive grasped the issue you are facing, but cant you just raise a flag on your resource in the state to indicate that its loading or not? some `REQUEST_SUCCESS` would just put in the store `loading: false` then and you would be able to query such flag synchronously in every situation I think.

**Comment by ivanakimov** [comment]
@Andarist thank you for responding.

Yeah, sorry I made it sound all complicating. To answer your questions: yes, you're basically right.

The issue is: this component has multiple ways it can load a page (there's many UI parameters -- black shoes, blue shoes, small shoes, large shoes, etc). So my state looks something like this:

```json
requests: {
  "/v1/page/get?color=blue": {
    "loading": true,
    "loaded": false,
    "error": null
  },
  "/v1/page/get?color=black": {
    "loading": false,
    "loaded": true,
    "error": null
  },
  "/v1/page/get?color=blue&size=large": {
    "loading": false,
    "loaded": true,
    "error": null
  }
}
```

The way I made it work was to call a function like this: `dispatch(loadPage({ color: "black", size: "large" }))`, so *the component is not aware of the **key** in the state (eg: `/v1/page/get?color=black&size=large`)* because the saga is the one composing that key, not the component.

Therefore, the component can't really check the state directly. I could theoretically just "re-create" the loading/not-loading flags in the component itself, but then I'll have two places where these flags are kept.

Do I have the wrong strategy for this?

**Comment by Andarist** [comment]
I would try to think how to reorganize ur state better to normalize it, aint sure atm though whats the best approach.

However even with such shape - if if component doesnt know the key it did dispatch the fetching action based on which the saga was able to construct this key - so this could be extracted and the component could query ur state with those params and not the key itself (key would be created from the parama under the hood)

**Comment by ivanakimov** [comment]
Ok. Yeah, that's true, the key composition code could be extracted. The problem is that code is in asynchronous sagas (it uses `select` for a few parameters), so I'm not sure yet how to extract it properly so that it could be in synchronous functions that component calls.

Alright, I'll keep thinking. Thanks for your feedback.

**Comment by Andarist** [comment]
Could u share relevant parts of the key composition code? Would be easier to advise further.

**Comment by ivanakimov** [comment]
@Andarist ok, thanks for following up. Let me try to show the basics in a simple way:

In component:

```javascript
import { loadItems } from '../../redux/actions';
...
componentDidMount() {
  ...
  dispatch(loadItems(page, color, size, weight));
}
```

Then it creates an action (which is watched), which then triggers another action.

Now in that saga:

```javascript
function* sagaLoadItems(action) {
  const params = {
    page: action.page,
    color: action.color,
    size: action.size,
    weight: action.weight
  };
  const { response, error } = yield fetch(items.get, params);
}
```

The `items.get` looks something like this:

```javascript
const items = {
  get: function*() {
    const site = yield select(getSelectedSite);
    return {
      method: 'GET',
      route: `/v1/items/${site}/get`
    };
  }
}
```

And the `fetch` is my own generator wrapper that a) forms the proper url from parameters b) does the `call` to the API and c) `put`s the proper values in the `requests` state (`loading`, `loaded`, etc).

Seeing as how `items.get` + the wrapper are the ones "assembling" the URL with params (and they're generator functions), I am not sure how I can write a regular `isLoading()` function that "assembles" a proper URL given params and then checks the state...

**Comment by Andarist** [comment]
Damn! This one is hard. Cannot think right now to restructure it with minimal effort :/ 

However component should be able to query the state in your example and I would think how to refactor ur state key and all to make it happen. Will give you benefits in the long run - simpler and more predictable code.

**Comment by ivanakimov** [comment]
Ok, thank you for looking @Andarist :)
