### ISSUE TITLE
Using saga to wrap API calls and call them (wrappers) directly

### ISSUE THREAD

**Issue by GuyMichael** [redux-saga/redux-saga#1041]
I'm struggling with this concept for a few days now, and I'm not quite sure if what I'm doing is very logical or very awkward.

### First, the 'normal' use:
sagas are very helpful and easy to write, and work naturally with API calls as side effects of 'actions'.
So naturally, many of my API calls are from a saga, which implement the 'loading, loading-error, loaded' approach (dispatch with `put()`). Something like this:

    export default function* initSaga() {
            //call all saga watchers in parallel
        yield all([
                ...
                , takeLatest("FETCH_SHOPS_AROUND_LOCATION", fetchShopsAroundLocation)
        ]);
    }

    function* fetchShopsAroundLocation(action) {
        try {
            yield put({type: "SHOPS_AROUND_LOCATION_LOADING"});
            const response = yield call(API.getShopsAroundLocation, action.location.latitude, action.location.longitude);
            yield put({type: "SHOPS_AROUND_LOCATION_LOADED", response});
        } catch (e) {
            yield put({type: "SHOPS_AROUND_LOCATION_LOADING_ERROR", reason: e.message});
        }
    }

### What do I want to achieve?
Now, say I want to directly call a fetchAPI method from someplace else, like a React Component:
Let's say that in a `render()` method of a Component, depending on some logic, I want to call an API.

The first thing that came to my mind was: "hey, I already have the same implementation of 'loading, loaded, error' logic in a saga! (due to the same call being called as a response to an action), and furthermore, I really like the use of generators, the way saga works&looks, and the fact that sagas are easy to duplicate & maintain, like a big actions.js sheet.  But I can't dispatch an action from within `render()` because it's forbidden(clearly)! So let's wrap that saga with a method and just call it!"
So I did something like this:

    export default function* initSaga(sagaMiddleware) {
        saga = sagaMiddleware;//a global 'let' which is placed inside the sagas.js scope

            //call all saga watchers in parallel
        yield all([
                ...
                , takeLatest("FETCH_SHOPS_AROUND_LOCATION", fetchShopsAroundLocation)
        ]);
    }

    function* fetchShopsAroundLocation(action) {...}//same as before

    //the new fetch method, to be directly called from outside sagas.js
    export function fetchShopsAroundLocation(latitude, longitude) {
            //saga is the sagaMiddleware set in initSaga()
        saga.run(fetchShopsAroundLocation, {location: {latitude, longitude}});
    }

### And my questions are:
1. Is it a good use of sagas? Or is it abusing saga, to be something it shouldn't?
    If so, do you have another solution, instead of copy-paste that fetchShopsAroundLocation saga to a different location?
2. If the idea is good, I'm I doing it right? Is it 'normal' to call the `agaMiddleware's `run()` method every time I want to fetch something?

**Comment by Andarist** [comment]
> Let's say that in a render() method of a Component, depending on some logic, I want to call an API.

That is rather an anti-pattern, `render` should stay pure function of props and state. For such things it is advised to use lifecycle methods.

> Is it a good use of sagas? Or is it abusing saga, to be something it shouldn't?

Rather the latter. The main purpose of saga is to separate ur components from the side effects of your application. Just look at the logo :) Ur state atom communicates with saga and nothing else, saga is acting as a bridge between it and the outside world.

> do you have another solution, instead of copy-paste that fetchShopsAroundLocation saga to a different location?

whats ur use case? Why and where do u want to reuse it?

**Comment by GuyMichael** [comment]
Thx for the detailed reply.
The actual problem I'm trying to solve is that React-Router (v4) doesn't have a prop to 'do something' once that route is used. So when I go into some page/screen/component as a result of routing, I don't have a callback that tells me 'this page/screen/component is starting'. If I had one, I would've dispatched an action to trigger the saga..

To be more detailed, if that is not clear enough:
1. There is some data loading once the app loads (fetched inside my main saga).
    Talking about the example above, it may be 'fetchAllCities' (cities would contain shopes..)
2. I have a page inside the app (a Component, clearly).
    This screen may be entered from two entry points: 
    a. User clicks on a button on the main page
    b. User pasts a URL to the browser, linking/routing directly to this page (React-Route v4).
3. As a result of this page being routed to, I'd want to fetch 'storesAroundLocation' from the example
   above (location could be the city's center for example).

-> So, trying to solve the case of 2a, I could assume (don't want to though) that the
   initial data is already in the store (result of 'fetchAllCities' in our example) and just
   put a fetch call in the componentDidMount callback.
   * However, this will fail on 2b, as the initial data would probably still be loading.
   ** I could delay the whole rendering of that inner page, but I don't want to (product/ux requirements).
      I'd better have the static parts loaded, and the 'cities' shown once fetched.
-> Trying to solve the case of 2b, I would use saga to listen for the initial data 'fetched' action,
    and then load the 'storesAroundLocation', which will trigger a re-render.
    * However, this will ignore case 2a, meaning that this whole data will be loaded, even if the user
      will never click on that button (I want lazy loading, depending on entering this page)

So far, the only 'clean' solution I found was the one described above.
I'm SURE there is a good solution, as I'm SURE 90% of react/redux apps need something like this.
I'm probably just too new to this:)

Thank you! Waiting for some suggestions:)

**Comment by Andarist** [comment]
Sorry for not responding any time sooner, frankly I missed your reply somehow. I guess you have worked around your issue by now, but if you have any more questions or your issue stays unresolved - please just write in this thread and I will for sure get back to you this time.

**Comment by ovaldi** [comment]
Hi @GuyMichael  I have the same question, how do you handle this case?
