### ISSUE TITLE
Handling action correctly

### ISSUE THREAD

**Issue by odarino** [redux-saga/redux-saga#1042]
Hello,
I have one thing to ask about asynchronous, redux-saga.
Basically, I have one simple action: when I selected an item => delete it, if it's success, call api that get all items, again
Like this: ( this is happened inside my saga)

```
export function* delete (action)
   yield call(service.deleteanitem)
   ....
   yield call(service.getall)
   yield put {type: 'getall'}
```
My idea is, I want it's sequential, I mean, when I delete item, a 'getall' action have to 'wait' whenever the previous action done, then its turn.
Any suggestion ?

**Comment by Andarist** [comment]
```js
export function* delete (action) {
	yield call(service.deleteanitem)
	....
	yield call(service.getall)
	yield put({ type: 'getall' })
	yield take('getall_finished')
}


// other saga
const chan = yield actionChannel('delete', buffers.expanding())

while (true) {
	const action = yield take(chan)
	yield call(delete, action)
}
```

**Comment by odarino** [comment]
@Andarist thanks for your response but can you explain this ? because I'm new in React/saga
Specify this: 
```
// other saga
const chan = yield actionChannel('delete', buffers.expanding())

while (true) {
	const action = yield take(chan)
	yield call(delete, action)
}
```

**Comment by Andarist** [comment]
`actionChannel` will gather ur actions in a buffer (simple FIFO) so you can take them later. That means you dont have to react to the actions as soon as they happen - you can wait. 

And later Im consuming those actions from the channel one by one. `call` is a blocking effect so this saga wont resume until `delete` saga is finished.

Therefore no more than 1 `delete` saga should run at the same time. This should cover your use case (I think)

**Comment by GuyMichael** [comment]
Can you please explain how it is different from using saga's `takeEvery()` ? Or direct me to a doc paper?
Thx!

**Comment by Andarist** [comment]
`takeEvery` will trigger sagas *immediately*, so there is possibility to run multiple sagas in parallel with this

Example above is queueing actions in a channel and only 1 saga (`delete` in the example) can run at a given moment.
