### ISSUE TITLE
Effect for class instantiation

### ISSUE THREAD

**Issue by ssynix** [redux-saga/redux-saga#1045]
Is it possible to instantiate a class (`new Class()`) through an effect?

The closest I got to it was:
```typescript
class Foo {
    constructor(public num: number) {}
}

function create<T>(SomeClass: new (...args) => T, ...args) {
    return new SomeClass(...args);
}

function* theSaga() {
    const foo = yield call(create, Foo, 3);
    console.log(foo);
}
```

While I'm not too opposed to the extra `create` helper method, it'd be nice if I could achieve this without it:
```typescript
yield call(Foo, 3); // call overload (my personal preference)
yield create(Foo, 3); // new effect
```

**Comment by Andarist** [comment]
you could also wrap this like this:
```js
export const create = (someClass, ...args) => call(() => new someClass(...args))
```
that way you would be able to use `create` as an effect, although ofc it needs to be imported from the other place than those which are built-in

I prefer not adding this to the core, it doesnt seem useful for everybody and its easily implementable on the user's side. That being said I would like to explore possibilities of being able to register ur own effects in the future, so stay tuned.

**Comment by sushrut-desora** [comment]
@Andarist Would you explain how to use the create wrapper ? I do not understand the purpose of ```call``` for calling arrow function ?
Why not ```export const create = (someClass, ...args) => { return new someClass(...args) }```
