### ISSUE TITLE
Reducer not receiving actions in correct order

### ISSUE THREAD

**Issue by rafatwork** [redux-saga/redux-saga#1049]
I'm using a combination of React, Redux & Redux Saga in my project. Below you can find a part of code belonging to a piece of functionality (stripped down & simplified). It fetches a list of products through an async call and displays the count of that result. While fetching, a "Loading" text is displayed.

I believe this is rather basic code which you can find in many examples online.

~~~
export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_REQUEST_SUCCESS = 'PRODUCTS_REQUEST_SUCCESS';

export function productsRequestAction() {
  return {
    type: types.PRODUCTS_REQUEST,
  };
}

export function productsRequestSuccessAction(products) {
  return {
    type: types.PRODUCTS_REQUEST_SUCCESS,
    products,
  };
}

const initialState = {
  isFetching: false,
  products: null,
};

function productsReducer(state = initialState, action) {
  switch (action.type) {

    case types.PRODUCTS_REQUEST:
      return Object.assign({}, initialState, {
        isFetching: true,
      });

    case types.PRODUCTS_REQUEST_SUCCESS:
      return Object.assign({}, state, {
        isFetching: false,
        products: action.products,
      });

    default:
      return state;
  }
}

export function fetchProducts() {
  return axios.get('http://www.example.com/api/my-products')
    .then(response => ({
      products: response.data
    }))
}

function* watchproductsFetch() {
  yield takeLatest(types.PRODUCTS_REQUEST, productsSaga);
}

function* productsSaga(action) {
  try {
    const result = yield call(fetchproducts);
    yield put(productsRequestSuccessAction(result.products));
  } catch (error) {
    ... 
  }
}

class MyContainer extends React.Component {
   ...
   
  componentDidMount() {
    this.props.dispatch(productsRequestAction());
  }

  render() {
    if (this.props.isFetching) {
      return '<span>Loading...</span>';
    }

    return <span>{this.props.products.length + ' products found'}</span>;
  }
  
  ...
}
~~~

As you can see, a PRODUCTS_REQUEST action is fired once the component is mounted. The saga listens for this event and fires the async call once triggered. Once the async call is finished and the products are received, a PRODUCTS_REQUEST_SUCCESS action is fired.

The problem I'm currently facing is that the reducer sometimes receives the PRODUCTS_REQUEST_SUCCESS action **_before_** the PRODUCTS_REQUEST action. UI-wise this results in the product count showing for a split second before turning into the "Loading" message. I would assume the reducer to receive the actions in the order they were dispatched.

I'm having a hard time reproducing this (never happens on my local environment, but it does frequently on a private server I have running in the cloud). If I put something like
`yield delay(50);`
in the productsSaga right after the call-statement, the issue doesn't occur anymore.

Any insights on what I'm doing wrong or what might be causing this?

**Comment by Andarist** [comment]
Actually it even cannot happen like this. Its the reducer who gets the action first and after the state is updated (or not) the saga gets notified about the action.

Without full working example Im afraid I cannot do much to help you. If you share a working thing on something like https://codesandbox.io/ I will gladly look at ur code.

**Comment by rafatwork** [comment]
Sorry for the late response.

I eventually figured out what the issue was. Code was perfectly fine. My project is using redux-persist (https://github.com/rt2zz/redux-persist) together with redux-action-buffer (https://github.com/rt2zz/redux-action-buffer). Apparently the latter one has an open issue about the order of dispatched actions not (always) being adhered (https://github.com/rt2zz/redux-action-buffer/issues/12).
