### ISSUE TITLE
Take effect works wrong

### ISSUE THREAD

**Issue by budarin** [redux-saga/redux-saga#1051]
```

const navigateTo = url => ({
    type: START_NAVIGATE_TO,
    payload: {
        url
    },
});

....

const mapDispatchToActions = dispatch => ({
    onClick: (url) => {
        return dispatch(navigateTo(url))
    },
});

export default connect(null, mapDispatchToActions)(Link);

....

function* navigate() {
    while (true) {
        const { payload: { url } } = yield take(START_NAVIGATE_TO);

        yield history.pushState(null, '', url);

        yield put({
            type: NAVIGATE_TO,
            payload: getLocationInfo(url),
        });
    }
}
```

after clicking on a Link - onClick calls once but "yield take" in navigate saga calls twice - so saga runs twice!

**Comment by Andarist** [comment]
Please share a reproduced issue on something like https://codesandbox.io/

**Comment by budarin** [comment]
unfortunately it's hard to reproduce as a snippet - there a lot of infrastructure around it - redux, routing & etc
can you help me find a solution with an advice where to find?

**Comment by Andarist** [comment]
I would start by giving each `START_NAVIGATE_TO` action a unique ID and `console.log` this id just after the `take` to get better picture of things, also adding a `debugger` instead of `console.log` could show you what's the exact reason why take got triggered at all.

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
