### ISSUE TITLE
JSForce integration with Redux saga

### ISSUE THREAD

**Issue by Shaikabbu** [redux-saga/redux-saga#1052]
If are facing below issues like
When we integrate Login method from connection, as itselt async callback function, react codebase is not waiting till execution as per behavior. Is it good practise to integrate in React.js or better to move in Node.Js Server side code.
Code template:
UI ---> Action generator (trying to call JSforce method as call back coming out ) --> dispatch method -- Store render

**Comment by Andarist** [comment]
Could u describe your issue more thoroughly?

**Comment by Shaikabbu** [comment]
Hi,
we are using JSforce lib for connecting Salesforce API from React application.
Using Redux-saga as middleware.
here come problem,
when we are calling connect.login(its async method) taking sometime to complete action. below is code snippet


      console.log("signInValidation");
          var conn = new jsforce.Connection({
         oauth2 : {
           loginUrl : salesforceconfig.OAUTH_TOKEN_URL,
           clientId : salesforceconfig.CLIENT_ID,
           clientSecret : salesforceconfig.CLIENT_SECRET,
           redirectUri :salesforceconfig.REDIRECT_URI
        }
       });
       
        Working
     var promise= conn.login(credentials.email,credentials.password);
         promise.then(function()
         {
              	yield put(saveOauth('success')); 
         })
     .catch(error => {
           console.log(error);
           yield put(signUserIn(error));
         })
before completing above codeblock its coming out

**Comment by Andarist** [comment]
u cannot use `yield` outside of the the `redux-saga` context (i.e. in callbacks)

The preferred way of dealing with this is to wrap ur connection into an `eventChannel`, it would look something like this:
```js
var conn = new jsforce.Connection({
    oauth2: {
		loginUrl: salesforceconfig.OAUTH_TOKEN_URL,
		clientId: salesforceconfig.CLIENT_ID,
		clientSecret: salesforceconfig.CLIENT_SECRET,
		redirectUri: salesforceconfig.REDIRECT_URI,
	},
});

const login = (conn, email, password) => eventChannel(emit => {
	const promise = conn.login(credentials.email,credentials.password)
	promise
		.then(() => emit(saveOauth('success')))
		.catch(error => emit(signUserIn(error)))
	return () => {} // this should be some cancellation/unsubscribe function
})

const loginChan = login(conn, credentials.email, credentials.password)
const loginResult = yield take(loginChan)
yield put(loginResult)
loginChan.close() // close this one time channel to free resources
```
