### ISSUE TITLE
Question: How does `yield call(someFunctionReturningAPromise)` returns the desired value?

### ISSUE THREAD

**Issue by marsonmao** [redux-saga/redux-saga#1053]
For example I have these codes:

```
function getCurrentGeoPosition() {
  return new Promise(
    resolve => {
      navigator.geolocation.getCurrentPosition(resolve);
    });
}
	 
function* goGetCurrentGeoLocation() {
  const currentPosition = yield call(getCurrentGeoPosition);
  console.log(currentPosition);
}
```

I understand that when `Promise` resolves, `navigator.geolocation.getCurrentPosition` is calling `resolve` with the signature of `(position) => { /*do something...*/ }`, but I can't understand how `(position)` is finally returned.
Can someone please explain why `yield call` correctly returns `currentPosition`?
Thanks.

**Comment by Andarist** [comment]
So the `redux-saga` is a runner and interpreter of ur effects (things u `yield` back to it). When you yield a call effect the redux-saga is instructed to run the supplied function (`getCurrentGeoPosition ` in ur example) and it inspects its return type - which can be a regular value, a promise or an iterator. Depending on that return type it makes the decision what to do.

So if the return's type is a Promise it simply chains to it with something like `.then(result => saga.next(result))`. And that's the whole magic. Your `goGetCurrentGeoLocation` is ofc the `saga` in this example.

**Comment by marsonmao** [comment]
I see...thanks for the instant reply!

**Comment by marsonmao** [comment]
Wait a minute, I think I have to ask for more detail, what is `result` in `.then(result => saga.next(result))` in my case?

**Comment by Andarist** [comment]
Yeah, its general JS question, but I can answer that. `resolve` is a callback function which u get while constructing a `Promise` instance and you use it to pass a result of ur computation to the promise, so its consumers can get notified with the passed value.

Just look at those examples:
```js
function delay(ms, value) {
  return new Promise(resolve => {
    setTimeout(() => resolve(value), ms)
  })
}

const promise = delay(1000, 'res')
promise.then(result => console.log(result)) // will print string 'res'
```
and
```
function getCurrentGeoPosition() {
  return new Promise(
    resolve => {
      navigator.geolocation.getCurrentPosition(position => resolve(position));
    });
}
```

**Comment by marsonmao** [comment]
Thanks for answering js question as well!
Your new version of `pos => resolve(pos)` is totally easy to understand, I can get it now.
So it seems that `getCurrentPosition(resolve)` is equivalent to `getCurrentPosition(pos => resolve(pos)` but I'm still having some difficulties to understand it. 
If you could explain this final mystery to me then I'll be all good!

**Comment by Andarist** [comment]
In JavaScript functions are first class citizens and they can be passed around just like any variable. So you can pass them as arguments to other functions etc. In the essence those 2:
`setCurrentPosition(pos => resolve(pos))`
and
`setCurrentPosition(resolve)`
are really the same thing, the difference is that the former creates an additional function which is unneccessary here

Take a notice that this `pos => resolve(pos)` is also a function, just like what is contained in `resolve`. The difference is that one is already in a reference (`resolve`) and one is put as kinda literal, just in place.

**Comment by marsonmao** [comment]
Thanks Andarist.

So, when `getCurrenPosition` is completed, it executes something like `successCb(pos)`, and the `sucessCb` directly maps to `resolve` or the anonymous just in place function; then, they result in executing `resolve(pos)` or `(pos) => resolve(pos)` (so the 2nd version has redundancy). Is the above correct?

**Comment by Andarist** [comment]
Exactly  🎉 !

**Comment by marsonmao** [comment]
Yaaaaaay!! I got it!! Thank you Andarist!

**Comment by Andarist** [comment]
No problem. Im glad I could help.
