### ISSUE TITLE
Add multiple event listener with firebase

### ISSUE THREAD

**Issue by tamal-appsbee** [redux-saga/redux-saga#1055]
Hi,

I am using redux-saga following way, the goal is to listen to multiple listeners:

in **saga.js**
```
let subscriptions = {}

// Saga event channel
function fbEventChannel(id) {
  return eventChannel(emit => {
    const listener = (data) => {
      emit({ [id]: data.val() });
    }
    firebaseDb.ref('user').child(id).on('value', listener);
    const unsubscribe = () => {
      firebaseDb.ref('user').child(id).off('value', listener)
    }
    return unsubscribe;
  })
}

// Listen to users
function* listen(action){
  try{
    subscriptions[action.data] = yield call(fbEventChannel, action.data);
    while (true) {
      const listener = yield take(subscriptions[action.data]);
      yield put(actions.listenUsers(listener));
    }
  } catch(e){
    console.log('Error:::', e)
  } finally {
    if (yield cancelled()){
      subscriptions[action.data].close();
    }
  }
}

// Saga user listener
function* subscribeUser(action) {
  while (true) {
    const listenTask = yield fork(listen, action)
    const unsubscribed = yield take(actions.UPDATE_USER_FB)

    console.log(action.data, unsubscribed.data);
    if(action !== unsubscribed.data)
      yield cancel(listenTask);
  }
}

export function* watchFbUserListner() {
  yield takeEvery( actions.INIT_USER_FB, subscribeUser );
}
```

in reducer.js
```
     case LISTEN_USER_FB:
    return { ...state, isFetching: true, errors: {}, data: {...state.data, ...action.data} }; 
```

in component.js

```
    let userIds = this.props.userIds; // Get user ids only On which need to add listners
    if(userIds.length > 0){
      userIds.forEach((e)=> { 
        this.props.initListner(e.key); // trigger INIT_USER_FB action
      });
    }

```

Questions is: 
a. Am I following correct way?
b. How I going to update listner or reducer state if there update in 'userIds' object, if need to remove some user and add new user ?
c. What will be the correct way to clean up saga task and listeners

**Comment by Andarist** [comment]
I dont get quite why `UPDATE_USER_FB` has to unsubscribe the listener, shouldnt it just update the user isntead of removing the old one and inserting a new one (when it gets subscribed to it again)?

**Comment by tamal-appsbee** [comment]
@Andarist  thanks for the reply.

I want to update 'userIds' array. So in saga it should unsubscribe users those are not exist in updated 'userIds' array. Also subscribe the new 'userIds' to fb listeners.

**Comment by Andarist** [comment]
If this solution works for you, its perfectly fine to use. Personally I would think a little if maybe whole firebase can be wrapped in a single channel so probably it would be easier to maintain the logic. 

Also `subscribeUser` and `listen` sagas seem to be overly complicated by the separation of them. You could keep both logics in 1 saga and use something like `race` to steer taking from the channel and unsubscribing it, that would also allow you to get rid of 'global' `subscriptions`, but as with everything - it's only matter of personal flavour.

**Comment by tamal-appsbee** [comment]
ok. 
is it possible to move following section to saga ?
```
 userIds.forEach((e)=> { 
        this.props.initListner(e.key); // trigger INIT_USER_FB action
      });

```

**Comment by Andarist** [comment]
Sure it is, you just need to establish other trigger than component's lifecycle.

**Comment by bradennapier** [comment]
@tamal-appsbee you may find this (alpha) package useful.  We are using it pretty heavily 

https://github.com/Dash-OS/firebase-listener

along with 

https://github.com/Dash-OS/saga-observable

to ilsten to hundreds of firebase paths efficiently.

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
