### ISSUE TITLE
Consider making `redux-saga` a store enhancer.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [redux-saga/redux-saga#1056]
Sagas must be registered with `run`, but that's only exposed through the instance of saga middleware.  While it's pretty trivial if you're registering all of your sagas when you set up the store
```
const sagaMiddleware = createSagaMiddleware();
const store = createStore(reducer, applyMiddleware(sagaMiddleware));
sagaMiddleware.run(mySaga);
sagaMiddleware.run(myOtherSaga);
```
it gets complicated if you want to register them dynamically; you have to either hold onto the instance of middleware
```
// sagaMiddleware.js
export default createSagaMiddleware();

// store.js
import sagaMiddleware from './sagaMiddleware';
const store = createStore(reducer, applyMiddleware(sagaMiddleware));

// somewhereThatHasAccessToStoreAndWillDynamicallyRegisterASaga.js
import sagaMiddleware from './sagaMiddleware';
sagaMiddleware.run(mySaga);
```
or patch `run` into the store.
```
// store.js
const sagaMiddleware = createSagaMiddleware();
const store = createStore(reducer, applyMiddleware(sagaMiddleware));
store.runSaga = sagaMiddleware.run;

// somewhereThatHasAccessToStoreAndWillDynamicallyRegisterASaga.js
store.runSaga(mySaga);
```
The latter option is what boilerplates like `react-boilerplate` [seem to do](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/store.js#L42), so it seems that, to use it dynamically, users have to do a little work to upgrade it to an enhancer.
So, like, how about just making it an enhancer?

**Comment by Andarist** [comment]
Could u propse exact API that you have in mind? Also please read [this discussion](https://github.com/redux-saga/redux-saga/issues/235) to see about different approaches that were implemented previously and had some serious flaws we were trying to get rid off.

**Comment by wtgtybhertgeghgtwtg** [comment]
Something like
```
// store.js
const enhancer = sagaEnhancer();
// enhancer adds `runSaga` property to store.
const store = createStore(reducer, enhancer);

// somewhereThatHasAccessToStoreAndWillDynamicallyRegisterASaga.js
store.runSaga(mySaga);
```
I am not sure how that conversation relates, so I might be missing something.

**Comment by wtgtybhertgeghgtwtg** [comment]
And here's a sample implementation I've been using
```
import {emitter} from 'redux-saga/lib/internal/channel';
import {runSaga} from 'redux-saga/lib/internal/runSaga';
import {ident} from 'redux-saga/lib/internal/utils';

export default function sagaEnhancer({context = {}, ...options} = {}) {
  const {sagaMonitor, logger, onError} = options;
  // Validation removed for brevity.
  return createStore => (reducer, preloadedState, enhancer) => {
    const store = createStore(reducer, preloadedState, enhancer);
    const {dispatch, getState} = store;
    const sagaEmitter = emitter();
    sagaEmitter.emit = (options.emitter || ident)(sagaEmitter.emit);
    const run = runSaga.bind(null, {
      context,
      subscribe: sagaEmitter.subscribe,
      dispatch,
      getState,
      sagaMonitor,
      logger,
      onError,
    });
    const newDispatch = action => {
      const result = dispatch(action);
      sagaEmitter.emit(action);
      return result;
    };
    const setContext = props => {
      Object.assign(context, props);
    };
    return {...store, dispatch: newDispatch, runSaga: run, setContext};
  };
}
```

**Comment by wtgtybhertgeghgtwtg** [comment]
If this looks okay, I can file a PR or something.

**Comment by erikvold** [comment]
This proposal is to mutate the `store` object, and I think we shouldn't do it for that reason, we should try to favor immutability where possible.  Also it would just be extra code to maintain and by implementing this proposal we might implicitly suggest that this is a recommended use case, and I don't think we should do that, especially now that so much documentation is out there explaining the current setup method (which I think is better for the immutability reason stated above).

**Comment by wtgtybhertgeghgtwtg** [comment]
It doesn't mutate the store object, though.  It returns an enhanced store.

**Comment by erikvold** [comment]
> It doesn't mutate the store object, though. It returns an enhanced store.

ah good point, I see that now.

**Comment by erikvold** [comment]
I think this might be a step backwards in http://redux.js.org/docs/advanced/Middleware.html to [attempt 3](http://redux.js.org/docs/advanced/Middleware.html#attempt-3-monkeypatching-dispatch) since dispatch is being money patched, although I guess that is not required for what you are suggesting.

**Comment by erikvold** [comment]
> const store = createStore(reducer, enhancer);

Also I'm not sure how this is intended to work with other middleware.

**Comment by wtgtybhertgeghgtwtg** [comment]
>Also I'm not sure how this is intended to work with other middleware.

Same way you'd do it for any other store enhancer
```
const store = createStore(
  reducer,
  compose(
    applyMiddleware(otherMiddleware),
    sagaEnhancer(),
  ),
);
```

**Comment by Andarist** [comment]
I dont see the real benefit of doing this now, by being more explicit we force users to compose this behaviour on their stores however they want and its only a few lines of code anyway. I would prefer users being more conscious about this and enhance their stores only when really needed (for the ease of usage).

It could also potentially mess with people's TS/flow types.

Also benefit of saga being a middleware is also an ability to put it into whatever position in the middleware chain you like, although it being 'last' is preferable and the easiest to maintain in the long run. 

Im still open for a discussion about this though, maybe others will have something interesting to add, but personally I think its more flexible the way it is now.

**Comment by wtgtybhertgeghgtwtg** [comment]
> by being more explicit we force users to compose this behaviour on their stores however they want and its only a few lines of code anyway

How else would they want to do it?  It's just boilerplate that amounts to the same thing.
> It could also potentially mess with people's TS/flow types.

As long as the store enhancer returns a valid `StoreCreator`, nothing changes.

> it will now not be possible to implement a gate keeper middleware checking users permission levels in a way that the 'blocked' action would be skipped and would not hit the sagas.

Sure it is
```
const store = createStore(
  reducer,
  compose(
    // Wraps dispatch from `sagaEnhancer`.
    applyMiddleware(gatekeeperMiddleware),
    // Wraps original dispatch.
    sagaEnhancer(),
  ),
);
```

**Comment by Andarist** [comment]
> How else would they want to do it? It's just boilerplate that amounts to the same thing.

1 line of code (`store.runSaga = sagaMiddleware.run;`) hardly can be called as boilerplate imho.

*gatekeeper example*
In the simplest scenario its possible and fine, but most of the times people use middlewares to hook into `dispatch` as it was literally their design goal. By spreading this responsibility between middlewares and enhancers we lose ordering flexibility, cause they cannot intermit each other.

**Comment by Andarist** [comment]
After some thinking I havent found enough compelling arguments to change the way how the redux-saga is used at the moment, we might revisit this in the future.
