### ISSUE TITLE
Add test for createMockTask

### ISSUE THREAD

**Issue by erikvold** [redux-saga/redux-saga#1059]
I'm not seeing any tests that `createMockTask` works in the `test` dir, am I missing something?

**Comment by Andarist** [comment]
No you are not, no tests are written for this. It's a test utility and nothing really worthwhile to test there.

However feel free to add extra tests for this. The best one would be really not checking its API but more if it serves its purpose - so I guess injecting this as a result of `fork`/`spawn`

**Comment by restrry** [comment]
what exactly could be tested here?
if we don't run saga, but just make test as in  https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/TaskCancellation.md
```js
const task = createMockTask()
function* saga() {
    yield cancel(task)
}
// the only test that we can do is 
assert.deepEqual(gen.next().value, cancel(task))
// and probably add check that cancel(task) or join(task) don't throw errors
```

**Comment by Andarist** [comment]
i guess example usage could be the test for this
