### ISSUE TITLE
Add more channel tests

### ISSUE THREAD

**Issue by erikvold** [redux-saga/redux-saga#1064]
It's not clear to me how I should test the sagas that I write which use channels, like `actionChannel`.  I don't see any examples, did I miss any?  Could someone please explain how to test examples like those on https://redux-saga.js.org/docs/advanced/Channels.html ?

**Comment by Andarist** [comment]
Unfortunately it's not documented well enough, but you can do something like
```js
let eff = it.next() // actionChannel effect
const mockChannel = channel()
it.next(mockChannel) // inject mockChannel back (it will become left value of the assignment in ur saga)
```
It also depends on what test exactly you would like to write, so more details would be appreciated.

**Comment by erikvold** [comment]
This issue is more about adding examples to the documentation so that people can figure out how to test channels for themselves.

**Comment by erikvold** [comment]
@Andarist how would one test the `throttle` example on https://redux-saga.js.org/docs/api/index.html ?


```javascript
const mySaga = function*() {
  const chan = yield actionChannel(pattern)

  while (true) {
    const action = yield take(chan)
    yield fork(task, ...args, action)
    yield call(delay, ms)
  }
}
```

When I test this I did something like you suggested first, then the next step fails:

```javascript
    let chan = actionChannel(pattern);
    assert.deepEqual(
      gen.next().value,
      chan
    );

    assert.deepEqual(
      gen.next().value,
      {} // bit confused what to test against here
    );
```

And the second test gives me:

Error: take(patternOrChannel): patternOrChannel is undefined
      at check (node_modules/redux-saga/lib/internal/utils.js:45:11)
      at take (node_modules/redux-saga/lib/internal/io.js:59:22)

and it's failing on this line ` const action = yield take(chan)`

**Comment by Andarist** [comment]
This should go like this:
```js
    let chan = actionChannel(pattern);
    assert.deepEqual(
      gen.next().value,
      chan
    );

    const mockChannel = channel()

    assert.deepEqual(
      gen.next(mockChannel).value,
      take(mockChannel)
    );
```

**Comment by erikvold** [comment]
@Andarist where does `channel` get exported from?

**Comment by Andarist** [comment]
@erikvold its exported from the main entry point
```js
import { channel } from 'redux-saga'
```

**Comment by Andarist** [comment]
Do you feel that there is still something lacking from the docs? Please specify, so we can work on it :) Your input in past few days was really great! Appreciate it a lot.

**Comment by andresmijares** [comment]
Yeah, I'm thinking about getting this part better, I would love to have to inputs as well :)

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.

**Comment by aepp** [comment]
I'm still missing examples on how to test the channels. E.g. I'd like to test the channel processes not more than `UPLOAD_TREADS_COUNT` requests at the same time - how would I do it? I can test the Saga itself, but can't figure out how to test that constraint of maximum parallel requests. 

That's my saga:

```
export function* watchChunksBeingAddedForUpload() {
  const uploadChannel = yield call(channel);

  for (let i = 0; i < UPLOAD_TREADS_COUNT; i++) {
    yield fork(uploadChunkSaga, uploadChannel);
  }

  while (true) {
    const action = yield take(PROCESS_CHUNK_UPLOAD);
    yield put(uploadChannel, action.payload);
  }
}
```

**Comment by Andarist** [comment]
I would recommend testing this in a black-box manner - spy on the outside world and assert your expectations, do not test the implementation itself.

**Comment by aepp** [comment]
> I would recommend testing this in a black-box manner - spy on the outside world and assert your expectations, do not test the implementation itself.

@Andarist thank you for the advise!
