### ISSUE TITLE
Setup (travis) ci

### ISSUE THREAD

**Issue by erikvold** [redux-saga/redux-saga#1067]
It would be nice if travis-ci was setup so that tests could be run for every pull request automatically.

**Comment by Andarist** [comment]
This would be great, although Im personally more familiar with CircleCI. Solution ofc doesnt matter, its the continous checks that matter.

Hadnt time to setup this, but for sure will try to do this. I want to release `v1` some in the near (*cough*) future, as we've reached stability long time ago already. This would pair really nicely with that. 

Also incorporating [bundlesize check](https://github.com/siddharthkp/bundlesize) would be cool.

**Comment by camflan** [comment]
I'm open to working on this

**Comment by camflan** [comment]
I have it working on my fork. Can someone else confirm that redux-saga currently has 1 failing test: `TypeScript files compile against definitions`

**Comment by Andarist** [comment]
@camflan yeah, this one is not working, it only indicates that we really need the CI :P 

Thanks for the PR!

**Comment by camflan** [comment]
@Andarist you got it -- I'm trying to debug the `bundlesize` part of this. I have it running locally using the travis-ci docker file, but it fails on travis-ci.org itself. I'll submit another pull once I have this working as well 👍

**Comment by camflan** [comment]
nvm, you got it already :)

**Comment by erikvold** [comment]
@camflan thanks for setting up travis!  /cc @Andarist 

I fixed the tests that were failing in #1079 and I think we should upgrade the version of node used in travis so I created #1078 as well.

**Comment by erikvold** [comment]
after landing #1079 we can close this issue I think!

**Comment by Andarist** [comment]
Thanks you guys for the great work. 👏

**Comment by camflan** [comment]
👍
