### ISSUE TITLE
Access to current non finished sagas

### ISSUE THREAD

**Issue by andresmijares** [redux-saga/redux-saga#1071]
Is there a way to access to the rootSagas array or all the non finishes sagas?

I'm trying to make a graph of my sagas (threads) executing at a given time.

**Comment by bradennapier** [comment]
This would be nice to have -- some sort of analysis capability to check if there are runaway sagas not be handled.  Especially since spawn() can make this situation happen extremely easily since it also detaches from the ROOT saga (something I dont agree with personally - i think spawn should just be a separate context still attached to the root saga so that you can cancel it knowing ALL sagas are cancelled)

**Comment by Andarist** [comment]
I think this should be possible to be built on sagaMonitor.

@bradennapier could u create an issue thread with the description of the problem and proposed solution?

**Comment by yelouafi** [comment]
for an example of use see

https://github.com/redux-saga/redux-saga/blob/master/examples/sagaMonitor/index.js
https://github.com/redux-saga/redux-saga-devtools/blob/master/src/store/createSagaMonitor.js

Esp. root Sagas can be recognized with the field `root: true` during the `EFFECT_TRIGGERED` event.

**Comment by bradennapier** [comment]
I actually (kind of) already have a solution built that could possibly be extended upon to provide a graph-like functionality.  I use it for redux-saga-process v2 which is a signifcant upgrade of the entire concept there.

It includes the capability to get a graph-like result of all your running tasks as well as keeping them all organized, logging errors in a much more helpful way, etc etc.

https://github.com/Dash-OS/saga-task-manager

It's definitely not something i would use in production -- it's definitely reliable but may require some code reading to understand the internals.

Also has some nice logging options:

![image](https://user-images.githubusercontent.com/15365418/28110828-62c05d0a-66a8-11e7-8526-ccfeda990f47.png)

![image](https://user-images.githubusercontent.com/15365418/28110945-b889be8e-66a8-11e7-94e5-5c8d96a6fc6f.png)

**Comment by andresmijares** [comment]
@bradennapier awesome! I will take a look! thank you!

**Comment by bradennapier** [comment]
The more I use it, the more I realize how essential it is truthfully.  In terms of handling tons of forks and spawns while making sure it all comes together nicely it is critical.  Today was troubleshooting a few things and it made fixing something that would no doubt take hours extremely simple.  

@Andarist @yelouafi - i wonder if the option to enable a high-quality logging option internally may not be extremely useful?  sagas introduces a concept which can be hard to understand what is really occurring behind the scenes.  I feel it's probably fairly easy to have things accidentally happening in the background that are eating up users performance if they don't understand some of the core details of how it all works.  

Perhaps some way of monitoring things like if there seems to be a high number of running tasks that are not completing (memory leaks), etc?

![image](https://user-images.githubusercontent.com/15365418/28145136-c894e976-6724-11e7-9c73-3c41c4263961.png)

**Comment by Andarist** [comment]
Yeah, monitoring options would be really cool - integrated in some kind of [redux-saga-devtools](https://github.com/redux-saga/redux-saga-devtools). But those are rather plans for the future.
