### ISSUE TITLE
What is the difference between `all()` and using an array of sagas?

### ISSUE THREAD

**Issue by alberth8** [redux-saga/redux-saga#1073]
I noticed in 0.15, the `all` API was introduced. Why use `all` instead of the following?

```
yield [
 call(...),
 call(...),
]
```

**Comment by Andarist** [comment]
Under the hood they are both the same, `yield [...effects]` will result in a deprecation warning though and inform you about `all`.

This was introduced to make parallel behaviour **explicit** and it nicely mirrows [Promise.all](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise/all)
