### ISSUE TITLE
Typescript Typings for result of `call` effect

### ISSUE THREAD

**Issue by Rokt33r** [redux-saga/redux-saga#1075]
To provide typings for result of call effect, I have to do like this.

```ts
  const repository: Repository = yield call<{slug: string, name: string}>(Repository.add as () => Promise<Repository>, {
    slug,
    name
  })
```

If we change the generic a little like:

```ts
// type Func1<T1> = (arg1: T1) => any;
type Func1<RESULT, T1> = (arg1: T1) => RESULT | Promise<RESULT>;

// <T1>(fn: CallEffectFn<Func1<T1>>, arg1: T1): R;
<RESULT, T1>(fn: CallEffectFn<Func1<RESULT, T1>>, arg1: T1): R;
```

Then, we will have much better format.

```ts
  const repository: Repository = yield call<Repository, {slug: string, name: string}>(Repository.add, {
    slug,
    name
  })
```

**Comment by aikoven** [comment]
Why doesn't `Repository.add()` declare a correct return type in the first place?

Also, what's the benefit from this type casting? The types are lost anyway after the `yield`.

**Comment by Rokt33r** [comment]
Yes, types will break after `yield`. But, we know they are not `any` and can be specific typed value because we are using `redux-saga`.

I've seen lots of mistakes like this in my company. That's the reason why I came here.

**Comment by Rokt33r** [comment]
What I expected is: 

```
const {
  someValueOfRepo,
  anotherValueOfRepo
}: Repository = yield call<Repository>(Repository.add, name)
```

1. If `Repository.add` doesn't return an instance of `Repository` anymore, it will blame.
2. If `anotherValueOfRepo` is no removed from `Repository`, It will blame too.

**Comment by aikoven** [comment]
I see, and this makes sense. But you would also have to declare types for all of the arguments. And yes, this is a breaking change. We could check back on this before v1.0

**Comment by grovesNL** [comment]
When is v1.0? This would be useful.

**Comment by Andarist** [comment]
@aikoven I'm preparing (slowly 😉) v1. Could you revisit this matter? Unfortunately I'm not able to make any decision regarding this and I trust you with TS related stuff here :)

**Comment by Rokt33r** [comment]
@Andarist How can I track the changes for v1?

**Comment by Andarist** [comment]
I've created [a milestone](https://github.com/redux-saga/redux-saga/milestone/1) where I gather all issues I would like to have resolved before releasing v1.

Anyway - I do not intend to make any major breaking changes, just some minor tweaks, internal changes and dropping previously deprecated features. 

But v1 is also a commitment to not make any breaking changes in it and ofc it looks nice :P

**Comment by aikoven** [comment]
Fixed in https://github.com/redux-saga/redux-saga/pull/1255
