### ISSUE TITLE
Way to pass arguments to the task in test

### ISSUE THREAD

**Issue by MartinCerny-awin** [redux-saga/redux-saga#1077]
I am trying to test task started by Saga helper takeLatest() and I am not able to figure out how I can pass arguments (locale) to the Saga task.

```
export function* requestReviews({ locale }) {
  const cachedReviews = yield select(selectors.getReviews, locale);
  return cachedReviews;
}

export default function* watchRequestReviews() {
  yield takeLatest(types.REVIEWS_REQUEST, requestReviews);
}
```

This is how my test looks like

```
it('should get reviews', () => {
    const gen = watchRequestReviews();
    expect(gen.next().value).toEqual(takeLatest('REVIEWS_REQUEST', requestReviews()));
});
```
I receive a TypeError: Cannot read property 'locale' of undefined.

**Comment by erikvold** [comment]
This is because your test code is calling `requestReviews()` which causes the error.  I think you want to replace `requestReviews()` with `requestReviews` in your test code.

**Comment by Andarist** [comment]
And when it comes to `requestReviews` - you need to write a separate test for this as in the one you have provided `takeEvery` wont execute any task, its just an information for you that such `takeEvery` has occured when executing `watchRequestReviews`.

**Comment by MartinCerny-awin** [comment]
I have tried this actually before as well, but it doesn't solve how can I pass arguments. I am getting different expected results.
