### ISSUE TITLE
TS context property missing on call function

### ISSUE THREAD

**Issue by nihiluis** [redux-saga/redux-saga#1082]
tryna do this:

```ts
    const { payload, err } = yield call(axios, {
      method: 'GET',
      url: url,
    })
```

yet get error. what is the issue here?

```
[ts]
Argument of type 'AxiosStatic' is not assignable to parameter of type 'CallEffectNamedFn<{ [x: string]: Func1<{ method: string; url: string; }>; }, string>'.
  Type 'AxiosStatic' is not assignable to type '{ context: { [x: string]: Func1<{ method: string; url: string; }>; }; fn: string; }'.
    Property 'context' is missing in type 'AxiosStatic'.
```

**Comment by aikoven** [comment]
This error message has nothing to do with the exact error in the code. Unfortunately, when failing to match with multiple signatures, TypeScript shows an error with the last signature only.

To get the right error message, you may comment out all `call` signatures in typings file except for the one you're using.

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.

**Comment by FourwingsY** [comment]
I met same error with this type error
But it was my fault.
I was trying to use function that wraps and create some saga like this
```
function createSaga() {
  return function*() {...}
}
```
but I did some mistype like this
```
function* createSaga() {
        ^
  return function*() {...}
}
```

I hope some of mistakes could be solved by this.

**Comment by eyerean** [comment]
Had the same error when I forgot to add my `newSaga` in my `rootSaga` where I `yield all([mySagas(), newSaga()]`. Could be of help to somebody out there.
