### ISSUE TITLE
[Question] How to interrupt to cancel the task from a specific action

### ISSUE THREAD

**Issue by minkyu-yi** [redux-saga/redux-saga#1086]
When use with `react-router-redux`, What is the best practice to cancel the task from `LOCATION_CHANGE` action?

```js
function* watcher() {
    yield takeLatest(DO_SOMETHING, worker);
}

function* worker() {
  try {
    // ...
  } catch (e) { 
    // ....
  }
}
```

I want to cancel the worker when the location changes. The first thing I think is the code below, but I 'm not sure if it is clean solution, and I wonder what best practice is.

```js
function* watcher() {
    yield takeLatest([DO_SOMETHING, LOCATION_CHANGE], worker);
}

function* worker(action) {
  if (action.type === LOCATION_CHANGE) {
    return;
  }

  try {
    // ...
  } catch (e) { 
    // ....
  }
}
```

**Comment by Andarist** [comment]
The snippet you have provided wont cancel the worker. It will listen for both actions and return immediately from the invoked worker for the `LOCATION_CHANGE`, but the worker will be still much alive and will keep listenening for your `DO_SOMETHING`.

Try this:
```js
function* watcher() {
    const task = yield takeLatest(DO_SOMETHING, worker);
    yield take(LOCATION_CHANGE);
    yield cancel(task);
}
```

**Comment by minkyu-yi** [comment]
Oh, Thank you! I realized What I was confused about.

In short, I did not want to cancel `takeLatest` task but just the worker in progress.

Could you advise again ?? Thank you.

**Comment by Andarist** [comment]
Hm, I guess then ur solution will work fine. When `LOCATION_CHANGE` happens it will just cancel the worker in progress, but wont proceed with worker's logic and just return.

**Comment by minkyu-yi** [comment]
Thanks again for your comment :)
