### ISSUE TITLE
Synchronized loadings question

### ISSUE THREAD

**Issue by idangozlan** [redux-saga/redux-saga#1087]
Hi,

Is there anyway to wait for action till it getting resolved before rendering component / rerendering it after the actions resolved before saga runnings completed?

My case is that I have 2 components, A and inside of it B. the things is that A is loading user details, and based on that it render or not the B component inside of it. Since the user is still loading, B is not rendered on the first loop, but in the second loop (after saga completed). The problem is that B has to fetch data according to the user details that A component fetched.

Thanks!

**Comment by Andarist** [comment]
I guess you dispatch some kind of `FETCH_DATA` in `componentDidMount` hooks or something. If that's the case it's not possible to make this in fewer steps.

You could restructure your logic though, I guess if B is going to render is determined on some pure logic - which you could extract and use in a saga to load both data for A and data for B (when data for A becomes available) and only then dispatch some `DATA_FETCHED` action to take down the spinner/loading component and render both A and B in one go.

**Comment by idangozlan** [comment]
I can do so, but it's make coupling, think about that, for example, lets assume that I want to show only to logged in users "recent posts" or whatever, but only on 5 specific pages. that mean that I have to make requests for the "recent posts" from all of those specific pages, since the "recent posts" component is not rendered if user info is under loading (then it considered as guests, and the recent posts not loaded for guests).

**Comment by idangozlan** [comment]
Finally I've created a request of user data on the "recent posts" loading generator, then performing the second call of getting the recent posts only if it's a user, and render it according to that.
