### ISSUE TITLE
undefined is not an object evaluating regeneratorRuntime.mark

### ISSUE THREAD

**Issue by NoPPT** [redux-saga/redux-saga#1088]
![simulator screen shot 2017 7 18 18 23 44](https://user-images.githubusercontent.com/9957401/28312885-4d5d7f4e-6be7-11e7-89a3-c8e180055219.png)

React Native 

```
//package.json
{
	"name": "FrankSystemApp",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"immutable": "3.8.1",
		"prop-types": "15.5.10",
		"react": "16.0.0-alpha.12",
		"react-native": "0.46.4",
		"react-navigation": "1.0.0-beta.11",
		"react-redux": "5.0.5",
		"redux": "3.7.2",
		"redux-logger": "3.0.6",
		"redux-saga": "0.14.8"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "2.1.0",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	}
}
```
```
//sagas.js
'use strict';

import { delay } from 'redux-saga';
import { call, put, fork } from 'redux-saga/effects';

function* watchToast() {
    console.log('Hello Sagas!');
}

export default function* rootSaga() {
    yield all([
        fork(watchToast),
    ]);
}
```

```
//store.js
'use strict';

import { createStore, applyMiddleware } from 'redux';
import createSagaMiddleware from 'redux-saga';
import { createLogger } from 'redux-logger';
import rootSaga from '../sagas';
import reducers from '../reducers';

const middlewares = [];
const sagaMiddleware = createSagaMiddleware(rootSaga);
middlewares.push(sagaMiddleware);

if (__DEV__) {
    const loggerMiddleware = createLogger();
    middlewares.push(loggerMiddleware);
}

export const store = createStore(
    reducers,
    applyMiddleware(...middlewares)
);
```
if i remove `import rootSaga from '../sagas';` in store.js,  run success.

**Comment by Andarist** [comment]
u probably need to install `regenerator-runtime` and add `import 'regenerator-runtime/runtime'` at the top of ur entry point

**Comment by NoPPT** [comment]
thanks, I solved this problem by changing the `react-native` version to `0.45.1`, but i don't know why ~

**Comment by Noitidart** [comment]
I am having this same problem but in RN 0.47.1. @NoPPT are you sure a simple upgrade to 0.45.1 fixed this?

**Comment by Noitidart** [comment]
@Andarist  @NoPPT - this is the issue to following along - https://github.com/facebook/react-native/issues/14838#issuecomment-321274943

Upgrading to 0.45.1 could not possibly have been the fix. Must have downgraded babel preset or something.

Or you switched to using `const = ` before the generators.

**Comment by NoPPT** [comment]
@Noitidart i'm so sorry that my reply misled you. I was constantly changing the version and sometimes it worked, so I thought the revision would solve the problem. Later I found that the modified version to `0.45.1` didn't really solve the problem, finally I used `redux-thunk` to replace `redux-saga`.

**Comment by Noitidart** [comment]
No problem sir, thank you for that. I just wanted to add the correction here because when I searched this is the first thing that came up on search engines. To help others.

**Comment by germanattanasio** [comment]
Running
```
npm install regenerator-runtime
```

And adding 
```
import 'regenerator-runtime/runtime';
```
Solved my issue.

**Comment by iMagdy** [comment]
Just go back to a state where the app was working, check `package-lock.json` file, and make sure that `package.json` file match the same versions.
