### ISSUE TITLE
Trying to use yield inside map

### ISSUE THREAD

**Issue by KrishnanAnil** [redux-saga/redux-saga#1090]
Spent few hours trying to figure out how to run sagas inside a map in parallel.

Tried out what I found : yield result.map(item => call(api.endpoint, item))
But nothing seems to happen. 

Here's what I was doing : 

````
export function* syncCanvasesByFolder(<someParams>) {
    yield call(api.syncCanvasForFolder, <someParam>);
}

export default function* syncAllFoldersForSurvey(<someParams>) {

    // Get list of folder for a survey
    const folders = yield call(data.getFolderBySurvey, surveyId);

    //For each folder sync canvases

        yield all(folders.map(folder => {
               call(syncCanvasesByFolder, folder.id, lastSyncedAt, access_token)  
        }));
 
/*Sequential call*/
    // for (const i in folders) {
    //     if (folders.hasOwnProperty(i)) {
    //         yield call(syncCanvasesByFolder, folders[i].id, lastSyncedAt, access_token);
    //       //  yield call(canvasSyncSaga.syncAllCanvasesForFolder, folders[i].id, lastSyncedAt);
    //     }
    // }
}
````

Sequential call when done in a for loop is working. But nothing seems to happen inside the map. Not getting any exception/errors as well.

**Comment by neurosnap** [comment]
Code snippet is hard to read, could you try formatting and distilling it a little bit?

This should work

```js
const urls = ['http://google.com', 'http://bing.com']; 
yield all(urls.map((url) => call(url));
```

**Comment by KrishnanAnil** [comment]
@neurosnap Thanks. I removed try catch and some commented codes. 
What I have is say a list of folders, each has list of canvases. I want to call the api to get me list of updated canvases for each folder. I tried to do that using a map (which is not working). 
When I just have the for loop it works. From what I have read it says that map does it in parallel, hence wanted that to work. :(

**Comment by Andarist** [comment]
This should work, could u share a reproduced issue on something like codesandbox.io?

**Comment by neurosnap** [comment]
You need to add a return statement in your map

```js
yield all(folders.map(folder => {
  return call(syncCanvasesByFolder, folder.id, lastSyncedAt, access_token)  
}));
```

**Comment by Andarist** [comment]
Oh, didnt spotted that there was no implicit return situation there. Good catch @neurosnap !

**Comment by KrishnanAnil** [comment]
@neurosnap @Andarist Thanks guys. That did the trick.

**Comment by Techno-than** [comment]
Hi I am getting runtime error that 'all is undefined', my code is like this - 

const res = yield call(getRootDir, param1);
const FoldersWithDirs = yield **all**(res.map(res => {
      return {
        ...res,
        dirs: call(Api.getSubFolders, res.id, res.param)
      }
  }));

Anything wrong above code?

**Comment by KrishnanAnil** [comment]
You probably forgot to import all.

**Comment by alaPing** [comment]
Could you have a look my code, please?
I want to create function as follows:
1. accept argument files and repeat 2-1 ~ 2-3 process
  2-1. download each file
  2-2. get property each file
  2-3. return object
3. return array of object

```javascript
// fileDownload and getProperty are defined. 
// download a file -> get its property -> return
function* loop(fileId) {
  yield call(fileDownload, fileId);
  const property = yield call(getProperty, fileId);
  return {
    id: fileId,
    ...property,
  };
}

export function* normalizeFileData(files) {
  return yield all(files.map(file => loop(file.id)));
}
```

**Comment by shinima** [comment]
@alaPing It seems to me that your code should work fine. Could you describe what's your expected behavior and what's the actual behavior?

**Comment by neurosnap** [comment]
```js
export function* normalizeFileData(files) {
  return yield all(files.map(file => call(loop(file.id))));
}
```

**Comment by alaPing** [comment]
@neurosnap
Oh... thank you very much!
I have solved this problem.

@shinima
Thank you for your rapid response!
Your questions help me to organize my mind.
