### ISSUE TITLE
How to run same action from two components and perform it once? 

### ISSUE THREAD

**Issue by idangozlan** [redux-saga/redux-saga#1091]
Hi,

I would like to know if there's a way to run same action form 2 different components and performing it only once? example:

App Component
|--- Profile Component

Im fetching user profile on App Component so all the components will have user details.
Profile component is making a fetch all that based on user details, and when it rendering, user call of App Component is still under loading state, so now I have somehow to wait to the user data fetch of App Component to be ended and only then run the Profile Component call.

Is there any way to run only once the user profile call from the App component or to let Profile component be aware when the user call of App component has done?

Thanks!

**Comment by Andarist** [comment]
I would go with the simplest solution - put a `fetching`/`loading` state in your store and just consult that state before making a request, so a duplicate will know to skip it.

**Comment by idangozlan** [comment]
i have `loading` state, but then how I can tell the Profile component fetch to be wait till `loading` is changing to false?

**Comment by Andarist** [comment]
make both those components dispatch some `FETCH_USER` action and in the saga

```js
function* fetchUser({ id }) {
  const isLoading = yield select(state => Boolean(state.users.byIds[id] && state.users.byIds[id].loading))
  if (isLoading) {
    return
  }
  const user = yield call(api.fetchUser, id)
  yield put({ type: USER_FETCHED, user })
}

yield takeEvery(FETCH_USER, fetchUser)
```

**Comment by idangozlan** [comment]
If I understand you right, you mean that in `App` component im dispatching `FETCH_USER`, and in `Profile` component im dispatching `FETCH_USER` and `FETCH_PROFILE` (or whatever second fetch is), but it's still not solving the problem, when `FETCH_PROFILE` is dispatching, the user still not loaded (under loading).

**Comment by kajas90** [comment]
You have few options with redux-saga, you can fork generator with a little delay and cancel ongoing task if action was dispatched second time. You can also use `takeLatest` helper. From my experience, cancel will help you a lot with avoid unnecessary requests :)

**Comment by idangozlan** [comment]
Thanks. there is no way to cancel request across watchers, right?

**Comment by Andarist** [comment]
@idangozlan You can put a cancel action from one saga/watcher and take it from another (to decide about cancellation). So its possible - just there is no some magic way to do it :) Everything stays explicit

**Comment by steezeburger** [comment]
Why don't you dispatch `FETCH_USER_SUCCESS` when you receive your user then do something like

```
// fetches profiles
function* fetchProfile() {
  yield put({ type: FETCH_PROFILE });
}
// in your main sagas
yield takeLatest(FETCH_USER_SUCCESS, fetchProfile);
```

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
