### ISSUE TITLE
Cleanup the cancellable-counter example

### ISSUE THREAD

**Issue by erikvold** [redux-saga/redux-saga#1093]
Not sure what happened but the cancellable-counter example doesn't seem to be complete or was broken, also the tests don't seem to be relevant (maybe I'm wrong) and don't pass.

We should probably clean this up and get it working with tests running again.

**Comment by Andarist** [comment]
You are right, it seems in complete in regards of tests. Example alone is working fine though - or have you experienced any issues with it too?

**Comment by djskinner** [comment]
Are you refering to the cancellation example here: https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/Channels.md#using-the-eventchannel-factory-to-connect-to-external-events?

I'm trying to create an eventEmitter which can be cancelled by an action. I'm struggling to understand how the example works though. If the code is already within the `finally` block then surely the eventEmitter has already finished. So how does cancellation work in this code? Perhaps it's just my lack of understanding!

**Comment by djskinner** [comment]
Ok I've seen the full example here https://github.com/redux-saga/redux-saga/blob/master/examples/cancellable-counter/src/sagas/index.js.

It makes more sense now. Perhaps the docs should include the code for the race.

**Comment by Andarist** [comment]
@djskinner do u still have any unanswered questions? or did the example's code clarified all the things for you?

**Comment by djskinner** [comment]
The example code clarified everything thanks
