### ISSUE TITLE
More typing extensibility for effects

### ISSUE THREAD

**Issue by Rokt33r** [redux-saga/redux-saga#1094]
I'm developing a redux enhancer for dispatch batched actions. 

As you see below, my actions are batched into another single action.

```ts
      yield put(batchAction([
        {
          type: 'SayBye'
        },
        {
          type: 'SayBye'
        },
        {
          type: 'SayBye'
        },
      ]))
```
> https://github.com/Revisolution/typed-redux-kit/blob/batched-actions/src/specs/batchEnhancer.spec.ts

This is not that bad, but I think it would be much nicer if I could `put` actions just as an array like the below example:
```ts
      yield put([
        {
          type: 'SayBye'
        },
        {
          type: 'SayBye'
        },
        {
          type: 'SayBye'
        }
      ])
```
> https://github.com/Revisolution/typed-redux-kit/blob/batched-actions-exp/src/specs/batchEnhancer.spec.ts#L42-L52

To make it possible, I have to extend dispatch and put functions just like redux-thunk does.

Here comes the problem. The typing for `put` of redux-saga is declared as a const.
It means there is no way to overload this function.

So, to make the second example possible, I have to modify the typing.

Original : 
```ts
export const put: {
  <A extends Action>(action: A): PutEffect<A>;
  <T>(channel: Channel<T>, action: T | END): ChannelPutEffect<T | END>;
  ...
};
```

Modified : 
```ts
export interface Put {
  <A extends Action>(action: A): PutEffect<A>;
  <T>(channel: Channel<T>, action: T | END): ChannelPutEffect<T | END>;
  ...
}
export const put: Put
```

Then, I could overload `dispatch` and `put`.
```ts
declare module 'redux' {
  export interface Dispatch<S> {
    <A extends Redux.Action>(asyncAction: A | A[]): A
  }
}

declare module 'redux-saga/effects' {
  export interface Put {
    <A extends Redux.Action>(action: A[]): ReduxSagaEffects.PutEffect<A>
    resolve<A extends Redux.Action>(action: A[]): ReduxSagaEffects.PutEffect<A>
  }
}
```
https://github.com/Revisolution/typed-redux-kit/blob/batched-actions-exp/src/lib/batched-actions.ts#L5-L16

Does it make sense? If so, I'll send a Pull request to fix this.

**Comment by Andarist** [comment]
cc @aikoven

**Comment by aikoven** [comment]
Yeah, that makes a lot of sense. 👍
