### ISSUE TITLE
Missing TypeScript definition for cloneableGenerator

### ISSUE THREAD

**Issue by stevenmusumeche** [redux-saga/redux-saga#1096]
I am importing this method in a TypeScript file like this:

    import { cloneableGenerator } from 'redux-saga/utils';

The actual code works great, however, I'm getting a TypeScript error.

```
file: '..... src/sagas/bootstrap.test.ts'
severity: 'Error'
message: 'Module '.... node_modules/redux-saga/utils"' has no exported member 'cloneableGenerator'.'
at: '7,10'
source: 'ts'
```

**Comment by Andarist** [comment]
@stevenmusumeche included typings are community-driven, so they always need some time to catch up after releasing features etc.

However this one was already merged in some time ago, gonna release new version with it right now. :)

**Comment by stevenmusumeche** [comment]
Thank you! I saw them in the code but couldn't find them in the release :)

**Comment by Andarist** [comment]
should already be released, please check if everything is working fine

**Comment by stevenmusumeche** [comment]
@Andarist I actually get the same error with 0.15.5. I can silence it like this, but it's not ideal.

```
declare module 'redux-saga/utils' {
    var cloneableGenerator: (foo: any) => any;
}
```

**Comment by Andarist** [comment]
@stevenmusumeche could u check why is it happening? does your `./node_modules/redux-saga/utils.d.ts` contain `cloneableGenerator` at the bottom of the file?

**Comment by Rokt33r** [comment]
@andarist I also confirmed, It doesn't exists there.

**Comment by Andarist** [comment]
@Rokt33r could u check why it might be broken? When I install `redux-saga` and inspect `utils.d.ts` contents I can see it has `cloneableGenerator` definition

**Comment by stevenmusumeche** [comment]
Actually, it is there and is working for me now.

**Comment by Rokt33r** [comment]
@Andarist Yea, it exists. I tried to find it with typo. :dizzy_face::dizzy_face:

**Comment by Andarist** [comment]
Closing this then :)
