### ISSUE TITLE
Cannot read property 'mark' of undefined

### ISSUE THREAD

**Issue by flyjennyetn** [redux-saga/redux-saga#1100]
index.js  
import React , { Component } from 'react';
import {Navigator,View,Text,StatusBar, Platform} from 'react-native';
import {createStore,applyMiddleware,compose} from 'redux';
import {Provider } from 'react-redux';
import createSagaMiddleware from 'redux-saga';

import ReducersManager from './js/reducers/';
import SagaManager from './js/sagas/';
import Route from './js/route';

const sagaMiddleware = createSagaMiddleware();
const initialState = window.__INITIAL_STATE__;

const store = createStore(
    ReducersManager,
    initialState,
    applyMiddleware(sagaMiddleware)
);

store.runSaga = sagaMiddleware.run;
//store.close = () => store.dispatch(END);
store.runSaga(SagaManager);

const isDebuggingInBrowser = __DEV__ && !!window.navigator.userAgent;
if (isDebuggingInBrowser) {
    window.store = store;
}

export default class App extends Component {
    render() {
        return (
            <Provider store = {store} >
                <Route />
            </Provider>
        )
    }
}

saga/index

import home from './home'

export default function* rootSaga() {
	yield* home();
}

saga/home

import { fork,call, put,takeLatest } from 'redux-saga/effects'

function* coursesQuery({token}) {
	
}

function* watchCourses() {
	yield takeLatest('courses/query', coursesQuery);
}

export default function*() {
	yield fork(watchCourses);
}

**Comment by Andarist** [comment]
@flyjennyetn 
you need to add a global module of `regenerator-runtime`. Please install this package and add this to ur top entry file
```js
import `regenerator-runtime/runtime`
```

**Comment by flyjennyetn** [comment]
@Andarist    Is still the same problem
package.json
      "react": "16.0.0-alpha.12",
    "react-native": "^0.46.4",
    "react-redux": "^5.0.5",
    "redux": "^3.7.2",
    "redux-actions": "^2.2.1",
    "redux-saga": "^0.15.5",
    "regenerator-runtime": "^0.10.5"

index.js

  import React , { Component } from 'react';
import {Navigator,View,Text,StatusBar, Platform} from 'react-native';
import {createStore,applyMiddleware} from 'redux';
import {Provider } from 'react-redux';
import createSagaMiddleware from 'redux-saga';
import 'regenerator-runtime/runtime';
import ReducersManager from './js/reducers/';
import SagaManager from './js/sagas/';
import Route from './js/route';


saga/home.js

  import 'regenerator-runtime/runtime';
import { fork,takeLatest } from 'redux-saga/effects'

function* coursesQuery() {
	
}

function* watchCourses() {
	yield takeLatest('courses/query', coursesQuery);
}


export default function*() {
	yield fork(watchCourses);
}

**Comment by Andarist** [comment]
Please add the import only in the `index.js`, its providing a global `regeneratorRuntime` object. Do not add this import in each of the saga files.

**Comment by flyjennyetn** [comment]
@Andarist   
![image](https://user-images.githubusercontent.com/12065761/28516478-f91ab8d2-7093-11e7-9b54-91a1ed9b3840.png)

**Comment by Andarist** [comment]
@flyjennyetn that is completely weird, could u share ur setup as a repository i could quickly run and debug this?

**Comment by flyjennyetn** [comment]
@Andarist   https://github.com/flyjennyetn/test/tree/master/jiagou

**Comment by Andarist** [comment]
@flyjennyetn How can I run it properly? when I make
`react-native run-ios`
it runs `index.ios.js` which is only some starter project and I see that what i should ran is in `app/index.js` - however aint sure how to run this properly.

**Comment by flyjennyetn** [comment]
@Andarist   react-native run-android     
it runs index.android.js

**Comment by Andarist** [comment]
For some reason this is whats get generated in your saga modules:
```js
var _marked = [coursesQuery, watchCourses, _callee].map(regeneratorRuntime.mark);

var regeneratorRuntime = require(43                   ); // 43 = regenerator-runtime
```
So by the line `regeneratorRuntime.mark` is called its still not defined. You could apply some hackery on the `babel-preset-react-native`, but its probably not worth it. You should try to report the issue in react-native's repository. For some reason their [custom transform](https://github.com/facebook/react-native/blob/6555f9bee865af03a4db09beb9216b8b61e182b8/babel-preset/transforms/transform-regenerator-runtime-insertion.js) doesnt play nicely with standard `regenerator-transform` (which they include to transform generators syntax).

**Comment by Andarist** [comment]
@flyjennyetn its certainly not a `redux-saga` issue. Aint 100% sure if its react-native's issue, or some combination of packages, but I would start from raising issue on their repository to keep ball rolling.

If you want a **temporary** solution until it gets resolved, you would have to drop `babel-preset-react-native`, use other preset, or just list of the plugins they recommend with the react-native. It seems there is nothing specific for the react-native development [here](https://github.com/facebook/react-native/blob/6555f9bee865af03a4db09beb9216b8b61e182b8/babel-preset/plugins.js). If you decide to go this road - if you want to ensure redux-saga to work:
- include `babel-plugin-transform-regenerator`
- put `import 'regenerator-runtime/runtime'; at the top of your entry file and ONLY there, no need to include it per saga module

**Comment by Jeepeng** [comment]
* downgraded `babel-preset-react-native` form `2.1.0` to `2.0.0`
* `npm run start -- --reset-cache`

**Comment by Andarist** [comment]
Did it help?

**Comment by flyjennyetn** [comment]
@Andarist  yes       @Jeepeng  thank

**Comment by pranit123** [comment]
Facing the same issue. @Andarist's fix did not work

**Comment by mammosu** [comment]
I changed like
```
function* rootSaga() {
  ...
}
export default rootSaga;
```
to
```
const rootSaga = function* rootSaga() {
  ...
}
export default rootSaga;
```
then I resolved .

**Comment by mammosu** [comment]
I changed like
```
function* rootSaga() {
  ...
}
export default rootSaga;
```
to
```
const rootSaga = function* rootSaga() {
  ...
}
export default rootSaga;
```
then I resolved .

**Comment by Andarist** [comment]
@mammosu's solution works, but it fixes the symptoms and not the underlaying issue.

As far as I know this is an issue of `babel-preset-react-native` and it got fixed in one of more recent releases.

**Comment by mammosu** [comment]
@Andarist That makes sense. Thank you!
