### ISSUE TITLE
How to get arguments sent from action in saga and Cancel requests in takeEvery

### ISSUE THREAD

**Issue by vivekdwivedi** [redux-saga/redux-saga#1101]
I have a two fold problem. One is to cancel requests when using takeEvery and another is to access the args is I implement a while loop instead of takeEvery. I hope this is a common scenario and maybe helpful to others as well.

Scenario: I have a report full of charts and I can apply filters on the report level (eg. change date range). For each chart in the report, I am making an API call to get the data with applied filters and based on the data, my chart will be painted. What I want to do is cancel a request for chart data if it is still pending and user changed the filter, or moved to a different report. 

**Current implementation:**

My action creator to fetch chart data
```
export function getChartDataForReport(params) {
  return {
    type: types.CHART_DATA_FOR_REPORT_REQUEST,
    params, // params have info like chart id, filter etc
  };
}

```
creates an action which is watched by the watcher and then the saga is called

```
export function* getChartDataForReportSaga(params) {
  try {
    const result = yield call(Api.getChartDataForReport, params.params.chartid, params.params.date, params.params.dimensionFilters, params.params.compare, params.params.dimension, params.params.extraDimension);
    yield [
      put({ type: types.CHART_DATA_FOR_REPORT_SUCCESS, data: result.data.response.data, chartId: result.data.response.cid }),
    ];
  } catch (error) {
    yield put({ type: types.CHART_DATA_FOR_REPORT_FAILURE, error });
  }
}

// Another attempt using race condition, but can't get params here
function* watchGetChartDataInReport() {

  while (true) {
    yield take(types.CHART_DATA_FOR_REPORT_REQUEST);
    yield race({
      task: call(getChartDataForReportSaga),
      cancel: take[LOCATION_CHANGE, types.APPLY_DATE_FILTER, types.APPLY_DIMENSION_FILTER],
    });
  }
// Below is the implementation that works fine for location change. Since my Sagas are dynamically injected when a route loads, cancelling the watcher at location change works fine

  // const watcher = yield takeEvery(types.CHART_DATA_FOR_REPORT_REQUEST, getChartDataForReportSaga);
  // yield take(LOCATION_CHANGE);
  // yield cancel(watcher);
}
```

saga then makes the API call using Axios where I am cancelling based on CANCEL from redux-saga like this:

```
// apicaller.js -> This guy cancels the call if it gets a CANCEL from redux
import axios, { CancelToken } from 'axios';
import { CANCEL } from 'redux-saga';

export const get = (url, params) => {
  const config = getRequestConfig();
  config.params = params;
  config.method = 'get';
  const source = CancelToken.source();
  config.cancelToken = source.token;
  const request = axios.get(url, config);
  request[CANCEL] = () => source.cancel();
  return request;
};

// api.js -> This is what the saga will call and this will call get method from apicaller.js

export const getChartDataForReport = (chartid, date, filters, compare, dimension, extraDimension) => {
  let reqFilter = filters;
  let compareMode = compare;
  const dimensionChanges = dimension || [];
  const extraDimensionForChart = extraDimension || [];
  if (reqFilter === null) {
    reqFilter = [];
  }
  if (compareMode === undefined) {
    compareMode = false;
  }
  const url = `${API_ENDPOINT}/data/reports/charts/${chartid}?date=${JSON.stringify(date)}&filters=${JSON.stringify(filters)}&compare=${compareMode}&dimension=${JSON.stringify(dimensionChanges)}&extraDimension=${JSON.stringify(extraDimensionForChart)}`;
  return API.get(url);
};
```
I have two more action creators for apply of date filter and dimension filter

```
export function applyDateFilter() {
  return {
    type: types.APPLY_DATE_FILTER,
  };
}

export function applyDimensionFilter() {
  return {
    type: types.APPLY_DIMENSION_FILTER,
  };
}
```

So what I want to achieve is that on either a location change, date filter apply or dimension filter apply, I should call the cancel for task that made the api call and axios will cancel the api call. The issues I am facing are:

1. If I wait for location change (as shown in commented part of watcher), it will cancel the watcher and all calls are getting cancelled fine. But this works only because a new watcher is injected in next report load. This was one of the side effects from using react-boilerplate implementation. How do I cancel in case a filter is applied, and I can't cancel the watcher as it won't be injected again for the same report, so no more api calls will be made.

2. Again in the case of commented code, I am not passing params anywhere, but in my saga, I do get the params from the action created. Since it was working fine, I never questioned where it came from. So where is the param coming from?

3. If I try to mimic takeEvery and implement a while-true loop with a race cancellation, I no longer have access to my params. I know I am not passing it to my saga, but where do I get my params inside the watcher. The action creator did create the action with params. So I should be able to get this with the action. 

If there is any other fundamental mistake I am making, please point out and I will try to fix it.

**Comment by Andarist** [comment]
hey @vivekdwivedi !

You have put quite a lot of text here, I dont have time **right now** to analyze the whole thing. From the really quick scan Ive noticed that u have a problem with accessing action params while reimplementing `takeEvery` as a while loop.

This can be done like this:
```js
export function* getChartDataForReportSaga(params) {
  try {
    const result = yield call(Api.getChartDataForReport, params.params.chartid, params.params.date, params.params.dimensionFilters, params.params.compare, params.params.dimension, params.params.extraDimension);
    yield [
      put({ type: types.CHART_DATA_FOR_REPORT_SUCCESS, data: result.data.response.data, chartId: result.data.response.cid }),
    ];
  } catch (error) {
    yield put({ type: types.CHART_DATA_FOR_REPORT_FAILURE, error });
  }
}

function* watchGetChartDataInReport() {
  while (true) {
    const { params } = yield take(types.CHART_DATA_FOR_REPORT_REQUEST);
    yield race({
      task: call(getChartDataForReportSaga, params),
      // u dont have to put LOCATION_CHANGE here,
      // cancellation will propagate downwards from the injectedSaga
      cancel: take([types.APPLY_DATE_FILTER, types.APPLY_DIMENSION_FILTER]),
    });
  }
}

function* injectedSaga() {
  const watcher = yield fork(watchGetChartDataInReport);
  yield take(LOCATION_CHANGE);
  yield cancel(watcher);  
}
```

If that doesnt help, please report back and Im gonna read through ur problem thoroughly later and help you more.

**Comment by vivekdwivedi** [comment]
Thanks a lot for the quick response. Getting the params was main issue and this fixes my case.

**Comment by linesh-simplicity** [comment]
```js
export function* saveLocation() {
  while (true) {
    const action = yield take(actions.saveLocation)
    const { lat, lng } = action.payload.params 

    yield put({ type: types.LOCATION_SUCCESS, payload: { location: params } })
    try {
      yield call(Api.post, urls.nearBy, { latitude: lat, longitude: lng })
    } catch (e) {
      yield call(utils.log, e)
    }
  } 
}
```

or utilise the `takeEvery` function provided by saga to remove the `while (true)` in your business saga: 

```js
export function* saveLocationSaga(action) {
  const { lat, lng } = action.payload.params 

  yield put({ type: types.LOCATION_SUCCESS, payload: { location: params } })
  try {
    yield call(Api.post, urls.nearBy, { latitude: lat, longitude: lng })
  } catch (e) {
    yield call(utils.log, e)
  }
}

export function* saveLocationSagaTaker() {
  yield takeEvery(actions.saveLocation, saveLocationSaga)
}
```

correct me if I miss something.

**Comment by URvesh109** [comment]
thanks linesh

**Comment by PedroFerr** [comment]
Thanks @linesh... simplicity! That's it!
