### ISSUE TITLE
add favicon to gitbook

### ISSUE THREAD

**Issue by erikvold** [redux-saga/redux-saga#1105]
We need to:

- [ ] create favicon
- [ ] add favicon to gitbook

I'm not sure how redux docs do this, there a plugin that can be used though https://plugins.gitbook.com/plugin/favicon

**Comment by Andarist** [comment]
It seems besides generating favicon it doesnt take much work - https://github.com/reactjs/redux/commit/3c900de44f1410fd2508401536b6e634e013e048

**Comment by r3dcrosse** [comment]
@Andarist I would like to take on this issue please!

**Comment by Andarist** [comment]
@r3dcrosse that would be super nice of you, thanks for the help offering :)

**Comment by r3dcrosse** [comment]
Submitted a pull request with the favicon. I used the logo provided in the redux-saga repo and scaled it down to the appropriate sizes. 

I could not get the favicon to update using the same method in the redux `docs:build` script. However, using the favicon plugin referenced by @erikvold worked effortlessly. 

The favicon looks like this (using chrome here): 
![screen shot 2017-11-21 at 10 29 32 pm](https://user-images.githubusercontent.com/10459856/33114706-e7bddbcc-cf12-11e7-9f2e-6591bc34a5b8.png)

I'm open to any suggestions or changes, please let me know what you think!

**Comment by Andarist** [comment]
Thanks! Great work.
