### ISSUE TITLE
How to know when a generator that ran from a user action has completed ?

### ISSUE THREAD

**Issue by furiousOyster** [redux-saga/redux-saga#1110]
If we dispatch an action that we are using to start a generator, how can we know when this generator has completed ?

In this example, how can we know when, for a given dispatch, the saga that has been triggered has completed ?

```javascript
const action = { type: 'FOO_SAGA' }
store.dispatch( action )
function * rootSaga(){
  yield takeLatest( 'FOO_SAGA', doTheThing)
}
```

We have tried making a sagaMonitor object but are unable to gain access to the triggering action.  I think I am stupid.  Help ?

**Comment by Andarist** [comment]
Could u share ur relevant code on something like codesandbox.io ? Also whats ur use case? Why do u need to know if `doTheThing` has completed? Cant u `yield put({ type: 'DO_THE_THING_COMPLETED' })`?

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
