### ISSUE TITLE
Sequencing Sagas via yield*

### ISSUE THREAD

**Issue by dagen-niger** [redux-saga/redux-saga#1111]
Hello, guys, I just want to clarify docs.

What did you mean here: "A more powerful alternative is to use the more generic middleware composition mechanism." (at https://redux-saga.js.org/docs/advanced/SequencingSagas.html)? Could you give some ewxamples or links?

**Comment by Andarist** [comment]
@dagen-niger it literally just refers to the next section in the docs - https://redux-saga.js.org/docs/advanced/ComposingSagas.html :)

**Comment by eric-burel** [comment]
Hi, 
Since this issue is open, I'll try my luck.
The doc is not explicit about how to sequence _a dynamic array_ of sagas.
```js
yield race({
      cancel: take('FOO'),
      // TODO : should run in sequence ! not in parallel !
      update: all(bars.map(bar => call(asyncFunc, bar)))
    });
```
I can't find a syntax that wait for asyncFunc to end before triggering the next call.

**Comment by Andarist** [comment]
you can implement this easily in the user land with something like this:
```js
const waterfall = (sagas, ...args) => fork(function* () {
	let result
	for (let i = 0; i < sagas.length; i++) {
		result = yield call(sagas[i], ...args, result)
	}
	return result
})
```

**Comment by eric-burel** [comment]
Hi, thanks for your answer, I managed to write this in the end :) I don't like the need to use a for loop though, maybe a `sequence([array])` effect would be cool to provide coherence withe the `all([array])` effect.

**Comment by Andarist** [comment]
It would have to use the same for loop :trollface: you just wouldnt see it in ur code. At the moment I dont think there is real need for more built-in effects, what would be interesting though is to find a way to create ur own effects more integrated with the internal runtime.

**Comment by alanhg** [comment]
I still don’t understand the role of yield* for serializing saga. Can you give a complete example?

Official doc is not explicit.
