### ISSUE TITLE
How to chain multiple redux saga asyn call simultaneously and wait for all the results

### ISSUE THREAD

**Issue by LearningNerdd** [redux-saga/redux-saga#1114]
I have a function called fetchStudentId as below:-

```
export function fetchStudentId(studentJoiningId) {
  return (dispatch, getState) => {

const state = getState()
blah
blah
blah

const student_data = {my required data ..., studentJoiningId}

const options = {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
  },
  body: JSON.stringify(student_data),
  mode: "cors",
}

return fetch("fvfcfgcfcfgc.fcfgcfc/yfcfcgcfg/hffgcfgccg", options)
  .then((json) => {
    dispatch(randomFunction(json))
    dispatch(fetchSudentDetails(json.student_id)
  })
  .catch((error) => {
  })
  }
}
```
below is my fetchSudentDetails function in which i am checking the name present in the response is "NONE" or somethingelse.

I will be calling fetchSudentDetails again and again untill response is not "NONE"

```
export function fetchSudentDetails(student_id) {

  return (dispatch, getState) => { 
const state = getState()
let fetching = state.fetching

if (fetching) {

  return 
  fetch("xdxfxdfx.com/jvhjv/jbjb")
    .then((json) => {
      switch (json.details.name) {
        case "NONE":
          setTimeout(
            () => dispatch(fetchSudentDetails(student_id)),
            FETCH_OFFER_DELAY
          )
          break
        default: // SUCCESS
          dispatch(setstudentdetails(json.details.complete))
      }
    })
    .catch((error) => {
    })
}
  }
}
```
So, everything is working fine as of now if I call this.props.fetchStudentJoiningId("jkjnkjnkjnnjkn") for one student

Now, I want to fetch 10 student's details simultaneously i.e I need to call fetchStudentJoiningId("jbjhb"), fetchStudentJoiningId("khbhjbjh"), ....(similar 10 calls ) and once all the 10 calls are succeeded then only I need to have my logic

So, far What I have tried

```
export function fetchTenStudents(dispatch) {
  return Promise
  .all([dispatch(fetchStudentId("kjhhjbhjb")),
    dispatch(fetchStudentId("vghvg")),
    dispatch(fetchStudentId("kjhhjbgvghvhjb")),
   ...(10 calls)
  ])
  .then(([xx, yy, zz, aa, oo, pp, rr, ss, tt, gvgh]) => {

  })
}
```
But its throwing the following error:- Actions must be plain objects. Use custom middleware for async actions.

While looking into this, I found that recalling the function fetchSudentDetails() is causing this issue

I want to call 10 fetchStudentId() simultaneously. Upon successful completion of all the 10 calls, I need to have my logic.

Successful completion of each request means fetchStudentId will be called and we will get student id and using that studentid I need to call fetchStudentDetails and fetchStudentDetails will be calling itself until name is not "NONE". Once the name is not "NONE", the request is succeeded.

I need to wait for 10 successful completion. I can't change the behaviour of fetchStudentDetails calling again and again.

I am open to make use of redux-saga.

**Comment by Andarist** [comment]
In the redux-saga world it would look something like this
```js
function* fetchStudentId(id) {
	// this is an effect for getState
	const studentData = yield select(state => ...)
	const options = {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json'
		},
		body: JSON.stringify(studentData),
		mode: 'cors'
	}

	const json = yield call(fetch, 'https://url/to/the/student', options)

	// this while loop is for fetchSudentDetails
	// could be extracted to other saga
	while (true) {
		const studentDetails = yield call(fetch, 'https://url/to/the/student/details')
		
		if (studentDetails.details.name !== "NONE") {
			yield call(delay, FETCH_OFFER_DELAY)
			continue
		}

		yield put(setStudentDetails(studentDetails.details.success))
	}

	// return some useful data, probably not whats inside json now
	return json
}

function* watchFetchUsers () {
	// take listens for dispatched action of the given .type
	const action = yield take(FETCH_TEN_STUDENTS) 
	// we map ids to call effects, all effects is similar to the Promise.all
	// calls are blocking so this saga wont resume until those calls are finished
	const results = yield all(action.payload.ids.map(id => call(fetchStudentId, id)))
	// put is an effect for dispatching
	yield put({ type: STUDENTS_FETCHED, payload: { results } })
}
```

**Comment by LearningNerdd** [comment]
Hi @Andarist, 

Thank you so much for sharing the details.

But my usecase is bit different.
I wont be knowing the ids before
`const results = yield all(action.payload.ids.map(id => call(fetchStudentId, id)))`

To get the id, I am making use of the following function `fetchStudentId` which will be taking studentJoiningId as argument

```
export function fetchStudentId(studentJoiningId) {
  return (dispatch, getState) => {

const state = getState()
blah
blah
blah

const student_data = {my required data ..., studentJoiningId}

const options = {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
  },
  body: JSON.stringify(student_data),
  mode: "cors",
}

return fetch("fvfcfgcfcfgc.fcfgcfc/yfcfcgcfg/hffgcfgccg", options)
  .then((json) => {
    dispatch(randomFunction(json))
    dispatch(fetchSudentDetails(json.student_id)
  })
  .catch((error) => {
  })
  }
}
```
Once I get the id from fetchStudentId function, using that id I need to call fetchStudentDetails function
Both of the functions are async. fetchStudentDetails should be called only after fetchStudentId.

fetchStudentDetails should be called only after fetchStudentId ----> this process has to be run simultaneously for 10 student

The information which I have previously is 10 student's joining ids
using joining id, get student id, using student id get student details.

**Comment by Andarist** [comment]
This is literally only an implementation id, you should be able to adjust my code to your needs with ease - ive only created it quickly to show you how this could be achieved in a saga world. Besides supplying other arguments to those generators it meets all of your requirements.

**Comment by LearningNerdd** [comment]
Awesome..
Sorry for the misunderstanding.
I will implement this in my project and will let you know the update.

Just some quick questions:-

1. `yield all(action.payload.ids.map(id => call(fetchStudentId, id)))` will this wait for all the 10 async calls to be completely finised?
2. if one call fails from 10 calls, what kind of status I will be getting from yield all call. As I need to revert the processs if any one f the async calls get failed?

**Comment by Andarist** [comment]
> yield all(action.payload.ids.map(id => call(fetchStudentId, id))) will this wait for all the 10 async calls to be completely finised?

Yes, it should. As mentioned `call` is a blocking effect so nothing will resume in the yielding generator until it finishes.

> if one call fails from 10 calls, what kind of status I will be getting from yield all call. As I need to revert the processs if any one f the async calls get failed?

Well, that part you need to figure out on your own - you need to implement a failing strategy on top of my proposed code, as it depends on ur needs - but its easy to do whatever u want:
- retry failed
- fail whole operation
- just swallow errors

If you implement things correctly you can use regular `try/catch` blocks on any level of the code you want, ie:
```js
try {
  const studentDetails = yield call(fetch, 'https://url/to/the/student/details')
  return studentDetails
} catch (err) {
  // handle err
}

```
So you can decide whats more appropriate for your use case - handle it downstream (directly where the fetch happens) or upstream (where the `all(...calls)` effect happen).

**Comment by LearningNerdd** [comment]
Thank you @Andarist,

I am going to implement this.

**Comment by Andarist** [comment]
No problem, feel free to ask any questions :)
