### ISSUE TITLE
[...effects] has been deprecated in favor of all([...effects]), please update your code

### ISSUE THREAD

**Issue by thinhtrh** [redux-saga/redux-saga#1115]
Hi my friends, I'm using redux saga for my project. Yesterday it worked fine, but today i get a warning and it's not work, "[...effects] has been deprecated in favor of all([...effects]), please update your code". I think my code is good, here is my code:

```
//My root
export default function* root(){
    yield all([
        fork(AddProductSaga),
        fork(GetProductListSaga)
    ])
}

//AddProductSaga
function* AddProduct(action) {
    try {
        const data = yield call(AddProductAPI(action.name, action.id, action.category, action.price))
        yield put({
            type: ADD_PRODUCT_SUCCESS,
            data
        })
    }catch (er){
        yield put({
            type: ADD_PRODUCT_FAIRLURE,
            er
        })
    }

}

function* AddProductSaga() {
    yield takeEvery(ADD_PRODUCT, AddProduct)
}

export default AddProductSaga

//GetProductListSaga
function* getProductList() {
    try {
        const data = yield call(GetProductListAPI())
        yield put({
            type: GET_PRODUCT_LIST_SUCCESS,
            data
        })
    }catch (er){
        yield put({
            type: GET_PRODUCT_LIST_FAIRLURE,
            er
        })
    }
}

function* GetProductListSaga() {
    yield takeEvery(GET_PRODUCT_LIST, getProductList)
}

export default GetProductListSaga
```
Can someone help me?

**Comment by Andarist** [comment]
Have u imported `all` from `redux-saga/effects`?

**Comment by thinhtrh** [comment]
@Andarist i have imported all, i don't know why, i will create new project and recheck. hope to work fine

**Comment by thinhtrh** [comment]
@Andarist Do you see any problem on my code?

**Comment by Andarist** [comment]
@thinhtrh Not with what you have pasted in here in regards of `all`. Are those all of your sagas?

**OFFTOPIC**
`const data = yield call(AddProductAPI(action.name, action.id, action.category, action.price))`
would be better as 
`const data = yield call(AddProductAPI, action.name, action.id, action.category, action.price)`

**Comment by parse** [comment]
I am also struggling to find the origin of this deprecation as well. I have quite a few sagas, is there a way we can get some more info in terms of where the deprecation message is being triggered from?

**Comment by Andarist** [comment]
I'll look into how I could expose origin of the deprecation better, but you should be able quite easily track down the origin by setting up a breakpoint on the warning line and looking into the stack trace.

**Comment by omerdn1** [comment]
Any news on this matter?

**Comment by thinhtrh** [comment]
i created new project and it worked fine with that code :) i don't understand

**Comment by Minishlink** [comment]
Ran into this deprecation notice today with this, and I'm not sure if this is an intended behaviour:
```js
const obj = { a: [] };
yield all(Object.values(obj));
```
Note that it happens only if the value of `obj.a` is an array.

**Comment by Andarist** [comment]
@Minishlink it's quite intended at the moment.

Array is still interpreted as parallel effect (with deprecation warning). Interpreting effects is a little bit 'recursive' process, in theory you can yield nested effect combinators (`race`, `all`). So the runtime tries to run each effect contained in `all` - and you are passing an empty array there as effect to be interpreted, so the runtime recognises it as nested parallel effect.

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
