### ISSUE TITLE
How to understand saga use while(true) ?

### ISSUE THREAD

**Issue by zhangping2014** [redux-saga/redux-saga#1116]
what's different between the following code?
i do not understand  how to use the While.
```
function* watchNavigate() {
  while(true) {
    const {pathname} = yield take(actions.NAVIGATE)
    yield history.push(pathname)
  }
}
```
```
function* watchNavigate() {
   const {pathname} = yield take(actions.NAVIGATE)
   yield history.push(pathname)
}
```

**Comment by seanyu4296** [comment]
Hi,

I just read the documentation just today and haven't used redux-saga yet. From what i understand, the first code snippet you posted behaves like the "takeEvery", but it is not exactly the same. So it will always watch for an action "NAVIGATE", while the second code snippet will only watch for the first actions "NAVIGATE" then end the generator function.
https://redux-saga.js.org/docs/advanced/FutureActions.html

Hope i helped

**Comment by Andarist** [comment]
What @seanyu4296 said :)

Generators are kinda pauseable functions, so putting `while (true)` in them doesnt mean blocking infinite loop (if the body of the `while` contains `yield` ofc), but rather some kind of infinite task - in your case that saga wont ever stop listening for `NAVIGATE` action.

**Comment by zhangping2014** [comment]
thanks @Andarist  @seanyu4296

**Comment by samuelcastro** [comment]
Wound't be better just use `takeEvery` rather than the `while(true)` ?

**Comment by samuelcastro** [comment]
nvm, I found the answer here: https://github.com/redux-saga/redux-saga/issues/684
