### ISSUE TITLE
about turn page in saga

### ISSUE THREAD

**Issue by zhangping2014** [redux-saga/redux-saga#1118]
when i read the documentation of redux-saga, there is a example about login.
but i do not understand how to  turn  anthoer page when i login success.
code like this

```javascript
    // Login Component
    this.props.login(user)
    // saga
    function* authorize(user) {
	try{
            const token = yield call(Api.authorize, user)
	    yield put({ type: 'LOGIN_SUCCESS', user: token })

          //  i want to turn page here 
          // with react-router

	}catch(error) {
		yield put({ type: 'LOGIN_ERROR', error})
	}
    } 
```
Hope some one can help me a example, thanks

**Comment by Andarist** [comment]
It really depends what solution do u use for routing.

**Comment by zhangping2014** [comment]
yes i used react-router @Andarist

**Comment by Andarist** [comment]
The easiest way would probably be to just integrate with `react-router-redux` like shown [here](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux) and to `yield put(push('/route'))`.

**Comment by zhangping2014** [comment]
i know it, but how did u  get the push in ur saga fn ? @Andarist

**Comment by Andarist** [comment]
According to their README its as easy as:
`import { push } from 'react-router-redux'`

**Comment by zhangping2014** [comment]
i did it,  but it don't work.
```javascript
    // saga fn
    import { push } from 'react-router-redux'
     // fn
    ...
    yield put(push('/route'))
    ...

```

**Comment by zhangping2014** [comment]
here is my example [demo](https://github.com/zhangping2014/redux-saga-demo.git)

**Comment by Andarist** [comment]
Please recheck as it ur repo works for me.

I've confirmed that this `yield put(push('/route'))` dispatches such action:
```js
{
  type: "@@router/CALL_HISTORY_METHOD",
  payload: {
    method: "push",
    args: ["/person"]
  }
}
```
and I got redirected to the page with such content:
```
<div>person page</div>
```

**Comment by zhangping2014** [comment]
it redirected to person page  because i maked it. 
in the Login component eg.
i think if u remove the code below, it willn't redirected anymore.

```javascript
componentWillReceiveProps(nextProps) {
		const { user } = nextProps.auth
		const keys = Object.keys(user)

		console.log('user', user)
		if (keys.length != 0) {
			this.context.router.replace('/person')
		}
	}
```
i have add u to the collaborators

**Comment by Andarist** [comment]
Oh, you need to figure out how exactly `react-router-redux` works. On the saga part there is nothing more to be done, dispatching redirecting action (`push`) is working - it just needs to be interpreted correctly (and acted upon) on the router's side. Maybe reach out to the reactiflux community for help and guidance. Unfortunately Ive never used this router and I dont have time at the moment to learn about its APIs more :(

**Comment by vzaramel** [comment]
I guess the tight way to use the react-route-redux API is to use the push method on history. 

```
import { history } from '../store/configureStore'

function* authorize(user) {
	try{
		const token = yield call(Api.authorize, user)

		yield put({ type: 'LOGIN_SUCCESS', user: token })
		yield call(history.push, '/person')
	}catch(error) {
		console.log(error)
		yield put({ type: 'LOGIN_ERROR', error})
	}
}
```

**Comment by Andarist** [comment]
According to their [README](https://github.com/ReactTraining/react-router/blame/d02558f4b323ec8d0351f14288e1916b79060ad7/packages/react-router-redux/README.md#L56) It should be possible to `store.dispatch(push('/foo'))` (at least in v4)

**Comment by vzaramel** [comment]
In his [example](https://github.com/zhangping2014/redux-saga-demo) he is using a old version of react-router and react-router-redux.

I updated both libs everything worked just fine.
[https://github.com/vzaramel/redux-saga-demo](https://github.com/vzaramel/redux-saga-demo)

**Comment by zhangping2014** [comment]
thanks
