### ISSUE TITLE
Saga function is not being called

### ISSUE THREAD

**Issue by wellyal** [redux-saga/redux-saga#1120]
I have two different saga function. The first one I could ensure my saga's setup was working great. But when I tried to add another function, it's not being called (I don't get any errors).

expenses.js (saga)
```js
import { put, call, takeEvery } from 'redux-saga/effects'
import { actionTypes } from 'reducers/expenses'

import userExpensesService from 'services/expenses'

function* getUserExpenses() {
  try {
    const expenses = yield call(userExpensesService.getUserExpenses)
    yield put({ type: actionTypes.SUCCESS, payload: expenses })
  } catch (err) {
    yield put({ type: actionTypes.FAILURE, payload: err })
  }
}

export function* watchGetUserExpenses() {
  yield takeEvery(actionTypes.REQUEST, getUserExpenses)
}
```

index.js (rootSaga)
```js
import { all } from 'redux-saga/effects'

import { watchAuthenticate } from './auth'
import { watchGetUserExpenses } from './expenses'

export default function* rootSaga() {
  yield all([
    watchAuthenticate(),
    watchGetUserExpenses()
  ])
}
```

OBS: My action creator is being called, and it is triggering the correct action type. Since I'm just importing the action types from my reducer, it can't be a problem with typo.

**Comment by Andarist** [comment]
I aint sure which one is not working properly from ur description. Could u be more specific and maybe reproduce the issue on something like codesandbox.io ? This would ensure that I could quickly help you.

Those should be irrelevant for the mentioned code, but I would still advise u to refactor this:
```diff
// expenses.js
-export function* watchGetUserExpenses() {
-  yield takeEvery(actionTypes.REQUEST, getUserExpenses)
-}
+ export const takeEvery(actionTypes.REQUEST, getUserExpenses)

// index.js 
export default function* rootSaga() {
  yield all([
-    watchAuthenticate(),
+    fork(watchAuthenticate)
-    watchGetUserExpenses()
+    watchGetUserExpenses
  ])
}
```

**Comment by wellyal** [comment]
@Andarist I've replaced both function calls from rootSaga with the fork calls. Like this

```js
yield all([
    fork(watchAuthenticate),
    fork(watchGetUserExpenses)
  ])
```

And now it is working fine (really not sure why). I've also tried to refactor the `takeEvey` as you said but it didn't worked. Thanks for your help.

**Comment by Andarist** [comment]
Forgot to specify the identifier for the exported watcher, should be:
```js
export const watchGetUserExpenses = takeEvery(actionTypes.REQUEST, getUserExpenses)
```

Could u share ur code somehow? Cannot do much without debugging ur issue properly.

**Comment by wellyal** [comment]
Here is the [source code](https://github.com/wellyal/planilha-reembolso-app). I realise that when I call the first saga (watchAuthenticate) and right after execute the other, both execute as expected. But when I try to dispatch only `getUserExpenses` it doen't work.

**Comment by Andarist** [comment]
You need to reorder `ReactDOM.render` and `sagaMiddleware.run` calls.

You are dispatching this action `planilha_reembolso/expenses/REQUEST` in `componentWillMount` when sagas were not yet started so listener for ur action type was not yet registered - because of this you miss the first dispatched set of actions.

**Comment by wellyal** [comment]
@Andarist No way. I can't believe it was that simple. Thanks man. I've spent hours trying to figure that out. 

Could you please answer me one more question? Should I put fork on every watcher I am declaring? I saw that `fork` makes saga perform a non blocking call to a specific function. Can you explain me why this refactor its better than my old solution? Or just send some link so I can't understand better. Again thanks, you just saved my like.

**Comment by Andarist** [comment]
> Should I use fork on every watcher I am declaring?

It depends on the requirements and what behaviour do you want to achieve. Read carefully docs about blocking vs non-blocking effects, fork model (all of ur sagas create a tree of tasks, with `spawn` u can create a 'detached' task from that tree) and also understand how cancellation (downwards) and error (upwards) propagate through that tree. That's what you should understand to pick tools for the job correctly - dont be scared though, those topics are really simple.

Also while yielding iterators (and promises) work - yielding wrapping effects (fork, spawn, call) is preferred. 

> Can you explain me why this refactor its better than my old solution?

Not rly much better, but ur solution have created an extra layer of the generator in between with no actual benefit from it. Let me illustrate with an example with regular functions:
```js
var fn = () => console.log('smth')
setTimeout(() => fn(), 1000) // unnecessary function layer
setTimeout(fn, 1000) // slightly 'better' equivalent
```

**Comment by dcz-ii** [comment]
> You need to reorder `ReactDOM.render` and `sagaMiddleware.run` calls.
> 
> You are dispatching this action `planilha_reembolso/expenses/REQUEST` in `componentWillMount` when sagas were not yet started so listener for ur action type was not yet registered - because of this you miss the first dispatched set of actions.

dammnn!! this really helped me. I cant believe I spent more than an hour looking for this.
