### ISSUE TITLE
saga act with unrelated response

### ISSUE THREAD

**Issue by eungchang** [redux-saga/redux-saga#1123]
my backend is spring boot,  
my app has two chunks, first one is login page, second one is webapp page.
webapp page is contributed with react, router, redux, saga.

when user do not anything in ten minutes, spring boot works like belows.
1. session timeout 2.  moving user to login page.

at the same time, user click any button of webapp, and that fire redux action.

and then,  redux saga takes spring boot response ( which are not related!! )
i posted it below what redux logger said .
 ------------------------------------------------
>  action user_home/NOTIFICATION_SUCCESS @ 16:31:06.653
redux-logger.js:1  

prev state Object {side_navigation: Map, user_home: Map, study_main: Map, study: Map, test: Map}
redux-logger.js:1

 action     
Object {type: "user_home/NOTIFICATION_SUCCESS", payload: Object, @@redux-saga/SAGA_ACTION: true}

payload: Object

config: Object

data: "<!DOCTYPE html>↵↵<html>↵<head>↵<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /↵</html>"

responseType: ""
responseURL: "http://localhost:8080/"
responseXML: null
status: 200
statusText: "OK"
timeout: 0

upload: XMLHttpRequestUploadonabort: nullonerror: nullonload: nullonloadend: nullonloadstart: nullonprogress: nullontimeout: null__proto__: XMLHttpRequestUploadwithCredentials: false__proto__: XMLHttpRequeststatus: 200statusText: "OK"__proto__: Object

type: "user_home/NOTIFICATION_SUCCESS"
@@redux-saga/SAGA_ACTION: true__proto__: Object

> 
----------------------------------------------------
how can i handle this problem??  

what i want is,

1. after session timeout
2. then moving to login page

**Comment by Andarist** [comment]
Could u post your saga code?

**Comment by eungchang** [comment]
`import { fork, call, take, put, takeEvery } from 'redux-saga/effects'

import { actionTypes, actions } from '../redux_reducers_ducks/ducks_study.js'
import * as api from '../redux_sagas_services/api_study.js';

//worker saga
function* getBookContent(action) {
	try {
		const response = yield call(api.getBookContent, action.payload);
		//handle api success
		if(response.status === 200) {
			yield put(actions.wordlist_success(response));			
		}
		else if(response.status === 204) {
			//yield put(actions.needtomakeschedule());
		}
		
	}
	catch(error) {
		//handle api fail
		yield put(actions.wordlist_failure(error));
	}	
}

function* updateStudyDay(action) {
	try {
		const response = yield call(api.updateStudyDay, action.payload);
		//handle api success
		if(response.status === 200) {
			yield put(actions.updatestudyday_success(response));			
		}
		
	}
	catch(error) {
		//handle api fail
		console.log('updateStudyDay is Error!!!');
		console.log(error);
		//yield put(actions.updatestudyday_failure(error));
	}	
}

//watcher saga
function* watching_GetBookContent() {
	yield takeEvery(actionTypes.WORDLIST_REQUEST, getBookContent);	  
}

function* watching_UpdateStudyDay() {
	yield takeEvery(actionTypes.UPDATESTUDYDAY_REQUEST, updateStudyDay);	  
}

//root saga 
export default function* rootSaga() {
	yield fork(watching_GetBookContent);
	yield fork(watching_UpdateStudyDay);
}

-----------------------------------------------------

this is my saga code

i guess,  
1. user do not anything  so ,  server decide to logout user
2. user click  any button which dispatch action,  server return response ( redirect to login page )
3.  saga take server's redirect response  as an action's response 
4. so , saved login html page to redux state

this is problem to me.

for your understanding, 
i have two page app. first one is login html page. second one is webapp html page.

**Comment by Andarist** [comment]
What response do u get from the server when redirect happens?

**Comment by eungchang** [comment]
i wrote about that  in the middle of my first comment.
 i make it short cause that is too long to upload here. 
response is whole login html page.
and that whole login html page is saved  at data of action.payload

data: "↵↵↵↵<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /↵"

and whole html page saved as redux state value.

**Comment by Andarist** [comment]
Its basic HTTP - you cannot make such redirect for the user automatically. You should return some error type from this request (instead of html) and do the redirect yourself in javascript.

**Comment by eungchang** [comment]
thanks !  i will try to do that way
