### ISSUE TITLE
Need to put push twice for the page to be re-rendered

### ISSUE THREAD

**Issue by thales-gaddini** [redux-saga/redux-saga#1126]
Good night everyone!

My problem is that I need to call the push action twice in my saga generator before the page is rendered. I have no clue why this is happening. To exemplify:

- If I use this:

```
function* mySaga(action) {
  const result = yield call(api.fetchSomething, action.uid);
  yield put(fetchSomethingSuccess(result));
  yield put(push('/something'));
}
```

The url will change to '/something' but the Something component associated won't be rendered.

- If I use this:

```
function* mySaga(action) {
  const result = yield call(api.fetchSomething, action.uid);
  yield put(fetchSomethingSuccess(result));
  yield put(push('/something'));
  yield put(push());
}
```
The url will change to '/something' and the Something component associated will be rendered.

- If I change the push param of the second push like this:

```
function* mySaga(action) {
  const result = yield call(api.fetchSomething, action.uid);
  yield put(fetchSomethingSuccess(result));
  yield put(push('/something'));
  yield put(push('/somethingelse'));
}
```

The Something component associated will be rendered but the '/somethingelse' url will be shown.

Yielding the empty push is probably wrong. Can someone point out what I should do please?

Thanks in advance!

PS: I'm not sure how to label this as a question.

**Comment by Andarist** [comment]
It sounds like a wrongly configured router / components and is not connected to redux-saga specifically by any means. If you share a reproduced issue on a repository to clone, I might look into it briefly. If not I'll have to close the issue here.

**Comment by thales-gaddini** [comment]
This seems connected to redux-saga because if I just dispatch the push action in the component it works as expected. The second push is only needed when I'm using it inside the saga generator function. What doesn't make sense to me is why would it work after the second push.

Just to be sure, at least this part seems correct to you right?

```
function* mySaga(action) {
  const result = yield call(api.fetchSomething, action.uid);
  yield put(fetchSomethingSuccess(result));
  yield put(push('/something'));
}
```

I'll try to look into it a bit more. Thanks anyway.

**Comment by Andarist** [comment]
Yeah. Nothing strange about this snippet.

Please share a reproduced issue on something like codesandbox.io . I'll try to help then with finding a solution

**Comment by Andarist** [comment]
This issue got a little bit stale, therefore Im closing it. Feel free to respond when you get to it.
