### ISSUE TITLE
Catch individual `call`/`apply` errors within `all`

### ISSUE THREAD

**Issue by JamyGolden** [redux-saga/redux-saga#1128]
I'm doing a dynamic `all` call and for the most part I get the correct data but in an edge case I'm getting a `400` error for one of the calls which is then failing `all()`. 
```
const results = yield all(someArr.map(
    someVal => apply(someService, someService.someMethod, [someVal])
));
```
Is there something I can do in which an `apply` with an error simply leaves out the result in the `results` `const`?.

Edit: I could do a `for` loop and `yield` each apply in there and catch any errors but I'd like to have them called simultaneously with `all` if possible.

**Comment by Andarist** [comment]
Im considering adding `safe` to the `redux-saga`, which would allow you to do:
```js
const results = yield all(someArr.map(
    someVal => safe(apply(someService, someService.someMethod, [someVal]))
));
```
and receive some kind of pair/tuple of result and error to unpack for urself. So in your example results would become an array of such pairs/tuples.

You can use it even today though, by implementing `safe` yourself:
```js
cosnt safeCall = (worker, ...args) => call(function* () {
    try {
        const res = yield call(worker, ...args)
        return { res }
    } catch (err) {
        return { err }
    }
})
```

and use it like this:
```js
const results = yield all(someArr.map(
    someVal => safeCall([someService, someService.someMethod], someVal)
));
```

**Comment by JamyGolden** [comment]
Thanks @Andarist!
