### ISSUE TITLE
yield call(fetch) never return on Android

### ISSUE THREAD

**Issue by pongponglau** [redux-saga/redux-saga#1129]
I am running react-native 0.47.1 with saga 0.15.6.

When i run the following codes in a real Android 6.0 device (and also in simulator), the statement "yield call(fetchData);" is never returned.

function fetchData () {
        return fetch(`${config.base}dashboard_charts.json`).then(response => (
            (response.status === 200) ? response.json() : Promise.reject('logon')
        ));
    }

function* getData (action) {
    try {
        const charts = yield call(fetchData);
        yield put({ type: UPDATE_DASHBOARD_CHART, charts });
    } catch (error) {
        yield put({ type: UPDATE_DASHBOARD_CHART, charts: [] });
        if(error.message === 'logon') {
            yield put({ type: PERMORM_AUTORIZE });
        }
    }
}

export default function * rootSaga () {
    yield [ takeEvery(FETCH_DASHBOARD_CHART, getData) ];
};

However, there is no problem on iOS. 

Do you have any ideas?

Thank you very much

**Comment by Andarist** [comment]
I would start debugging from checking this:
```js
function fetchData () {
  console.log('fetch data')
  return fetch(${config.base}dashboard_charts.json).then(res => {
    console.log('res', res)
    return res
  }).then(response => (
    (response.status === 200) ? response.json() : Promise.reject('logon')
  ));
}
```

**Comment by pongponglau** [comment]
@Andarist 

Only console.log('fetch data') is found. Does it mean there is problem with fetch ob Android?

Thanks a lot

**Comment by Andarist** [comment]
> Only console.log('fetch data') is found. Does it mean there is problem with fetch ob Android?

It seems so. Please file an issue on their repository.

> Thanks a lot

No problem :)

**Comment by pongponglau** [comment]
Very strange. fetch did return, however, it never jumps into then() or catch().
 
let result = fetch(url)

console.log(JSON.stringify(result))

It just prints out integer hash.

DO you have any idea?

Thanks alot

**Comment by Andarist** [comment]
Fetch returns a promise and thats probably what u have seen by console logging it. Problem is that it doesnt seem to resolve (hence no then/catch is called)

**Comment by pongponglau** [comment]
You are right. I try fetch somewhere else in my RN project (outside saga).  The same issue is found. Thus, i believe there is problem with fetch on android with RN 0.47.1 but there is no problem on iOS. I have reported this issue to React Native and hope they have a fix on it soon.

Thank you for your help

**Comment by hiroto78** [comment]
Hi, there!
It had already fixed? If you know anything about this, please let me know. 
Thank you.

**Comment by nicolashardy** [comment]
Same issue. I know this is closed, but if @hiroto78 or @pongponglau have any answers... :D
