### ISSUE TITLE
Make it obvious when you dispatch critical actions after END

### ISSUE THREAD

**Issue by kumar303** [redux-saga/redux-saga#1132]
It would be helpful to log an error (or throw an error?) if an important action is dispatched after [`END`](https://github.com/redux-saga/redux-saga/issues/255) has ended all sagas. By important action I mean one that was passed to `take()` in a previously running saga.

In server side rendering you have to render once to dispatch data loading actions and render a second time after the `END` action has completed all sagas handling the actions. I just spent a long time chasing down a bug where my data loading action (for one component) was dispatching in the *second* rendering phase. This phase is too late because all sagas have ended. However, the loading action was happily dispatched into the ether without any warnings.

I suppose I could roll my own with [`take.maybe()`](https://redux-saga.js.org/docs/api/index.html#takemaybepattern) but it would be nicer if it were built in since I think this is an easy bug to trigger.

**Comment by Andarist** [comment]
How redux-saga should determine if the action is critical or not?

**Comment by kumar303** [comment]
I don't know anything about the implementation but what about this:

- A saga starts up called `categoriesSaga()`
- it registers `takeLatest('FETCH_CATEGORIES', handleCategoryFetch())`
- the application dispatches `END` which causes `categoriesSaga()` to stop running
- the application accidentally dispatches `'FETCH_CATEGORIES'` after that
- redux-saga logs a warning: "`'FETCH_CATEGORIES'` was dispatched but `categoriesSaga()` is no longer running"

If that's not possible hopefully it at least illustrates the idea I had to make these kind of bugs easier to track down.

**Comment by Andarist** [comment]
Im afraid it could potentially lead to memory problems if implemented naively also it still doesn't determine good enough if the `handleCategoryFetch` was important for SSR or not - I think the same applies for any other actions and without any type of hints (with magic annotations or some kind of helper function which you could use to mark sagas as important) is effectively not possible to determine that. And such solutions are rather brittle, hard to maintain and would have to be manually applied to the source code - it doesn't seem compelling enough to implement anything like this, when you can just write tests for your SSR process and catch the potential problems way better.

I categorize this request as not possible to implement (unfortunately, I would certainly like to guard you from potential mistakes) and therefore I'm closing this issue. Feel free to comment back though.
