### ISSUE TITLE
Question: channel is closed immediately if using takeEvery in the try-block

### ISSUE THREAD

**Issue by marsonmao** [redux-saga/redux-saga#1133]
The code is fairly short: 

```
function* manageSocket()
{
  try {
    var wsChannel = yield call(subscribeWebSocket, eventChannel, eventHandlers);
    yield takeEvery(wsChannel, function*(action) {
      yield put(action);
    });
  }
  finally {
    wsChannel.close();
    console.log('wsChannel closed');
  }
}
```

With this setup, the `try` block is finished immediately after `takeEvery`, so the `finally` block is executed as well, then there won't be any action sent from the channel, which is not good.

So I have to use this setup:

```
function* manageSocket()
{
  try {
    var wsChannel = yield call(subscribeWebSocket, eventChannel, eventHandlers);
    while (true) {
      const action = yield take(wsChannel);
      yield put(action);
    }
  }
  finally {
    wsChannel.close();
    console.log('wsChannel closed');
  }
}
```

i.e. to explicitly write the `while` loop so that my `try` block won't finish immediately.

My question is, is this by design? Am I forced to use the `while` loop structure instead of `takeEvery`?

Thanks!

**Comment by Andarist** [comment]
It is derivative of the design and how generators work. `takeEvery` is a non-blocking effect. This means that it will return to  your generator a task descriptor as soon as possible and yielding generator will continue its execution. 

Because its kinda last statement in your generator it reaches its end and executes code in the `finally` block. 

Therefore if you want to keep using `takeEvery` there you need to introduce some blocking effect (thats while inlined `while` loop worked).

The best I can think of is to:
```diff
function* manageSocket()
{
  try {
    var wsChannel = yield call(subscribeWebSocket, eventChannel, eventHandlers);
    var task = yield takeEvery(wsChannel, function*(action) {
      yield put(action);
    });
+   yield join(task)  
  }
  finally {
    wsChannel.close();
    console.log('wsChannel closed');
  }
}
```

**Comment by marsonmao** [comment]
Hey Andarist thanks for the reply (again!)

So that it looks like the whole structure of an event channel watcher is fairly fixed; One has to 1. hand write the infinite `while` loop or provide a block effect like `join` to make `try` block work, then 2. provide the corresponding `finally` block to close the channel.

If the above assumptions are correct, then what do you think about writing a wrapper/creator function that assemble these things together? Like a `setupSocket` function that accepts a created channel, the body inside `try` block and the body inside `finally` block so that people won't bother with hand write the fixed structure, also won't make any mistake? Oh and I mean this wrapper will be written in my project, I don't think this should go into redux-saga.

Or, option 2, any chance the design of channel could get some modification? The goal is to make writing channel codes more easily (or more free), e.g. people could choose to use `while (true)` or `takeEvery` without the burden to make the `try` block blocking. I'm not sure if this is possible, but I think if it's possible and reasonable, this could go into redux-saga.

**Comment by Andarist** [comment]
> f the above assumptions are correct, then what do you think about writing a wrapper/creator function that assemble these things together? Like a setupSocket function that accepts a created channel, the body inside try block and the body inside finally block so that people won't bother with hand write the fixed structure, also won't make any mistake? Oh and I mean this wrapper will be written in my project, I don't think this should go into redux-saga.

If this works for you - go ahead! :) 

> Or, option 2, any chance the design of channel could get some modification? The goal is to make writing channel codes more easily (or more free), e.g. people could choose to use while (true) or takeEvery without the burden to make the try block blocking. I'm not sure if this is possible, but I think if it's possible and reasonable, this could go into redux-saga.

Aint really sure if thats possible. I prefer exposing more primitive/building blocks which you can use to built upon more fine-grained solutions. Including such behaviour in the core library would only limit use cases or we would have to make this configurable which is also a maintenance burden.

Going to close this issue, as it seems solved. Feel free to comment more if you want to. I dont miss any answers in any threads here ;)

**Comment by marsonmao** [comment]
@Andarist The answer is clear and reasonable, thanks! If there are any more ideas popping out of my head I would come back ;) Thanks!
