### ISSUE TITLE
Put statements and awaiting for events triggered from another saga

### ISSUE THREAD

**Issue by qpre** [redux-saga/redux-saga#1134]
Hey !

I'm kind of confused as of how to perform a `put` effect and wait for a few specific events before continuing:

sample case:

```javascript
function* myRequestSaga() {
  const requestChannel = yield actionChannel("REQUEST");

  while (true) {
    const { requestParams } = yield take(requestChannel);
    const { id } = yield call(request, requestParams);

    yield put({ type: "INSERT_REQUESTED", id });

    yield race({
      error: yield take("INSERT_FAILED"),
      success: yield take("INSERT_SUCCEEDED"),
    });

    console.log("it's over moving on to the next one !");
  }
}
```

Here I don't want to perform any other requests in parallel, and want to wait from another saga's events before unlocking.

When doing this I end up being locked up at the `race` statement.
I've tried both: 
- wrapping my `put` statement into a fork
- using actionChannels for both my error and success statements (I expected them to buffer the selected actions from before the `put` statement and then `take` on them in `race` to see which one won)

**Comment by jimbol** [comment]
I think the saga is getting hung up on the `put` because it's not being passed an action. Can you verify?

**Comment by qpre** [comment]
Hey @jimbol sorry, it's a typo in the example, Im editing it.

**Comment by Andarist** [comment]
@qpre 
Try this :)
```diff
    yield race({
-      error: yield take("INSERT_FAILED"),
+      error: take("INSERT_FAILED"),
-      success: yield take("INSERT_SUCCEEDED"),
+      success: take("INSERT_SUCCEEDED"),
    });
```

**Comment by qpre** [comment]
Thanks @Andarist ! solved it for me !
