### ISSUE TITLE
The correct way of fetching data and dispatching a new action

### ISSUE THREAD

**Issue by dantenovski** [redux-saga/redux-saga#1136]
``` javascript
function* fetchIncrement(){
  return fetch('http://www.haha.com/fetch_increment') // It just returns string "1"
  		.then(res=>res.json())
  		.then(data=>{
                   console.log(data); // logs "1" as expected
                   return parseInt(data);
  }).catch(err=>console.log(err))
}

export function* incrementAsync(){
  let fetchResult = yield call(fetchIncrement);
  console.log(fetchResult); // logs Promise object
  yield put({type: 'INCREMENT_COUNT', payload: fetchResult}) // I want payload to be 1
}
```
All I'm trying to do is to dispatch 'INCREMENT_COUNT' with payload: 1. 

I was thinking of dispatching 'INCREMENT_COUNT' from within fetch but it may be an anti pattern?

**Comment by dantenovski** [comment]
Also I wanted to do it this way:

```javascript
function* fetchUser(action) {
   try {
      const user = yield call(Api.fetchUser, action.payload.userId);
      yield put({type: "USER_FETCH_SUCCEEDED", user: user});
   } catch (e) {
      yield put({type: "USER_FETCH_FAILED", message: e.message});
   }
}
```
But I don't know how Api.fetchUser should be constructed

**Comment by sgal** [comment]
@dantenovski Here's how you can do `fetchUser` example (simplified)
```
// userApi.js
export const fetchUser = (userId) => fetch(`http://mywebsite.com/user/${userId}`);

// userSaga.js
... same as your code
```

First example can be fixed by using yield instead of promise's `then()` as well as `try/catch` instead of promise's `catch()`.

```
function* fetchIncrement(){
  try {
    const response = yield call(fetch, 'http://www.haha.com/fetch_increment');
    const data = response.json();
    console.log(data); // prints "1"
    return parseInt(data, 10); // explicitly set radix
  } catch (e) {
    console.log(e);
  }
}

export function* incrementAsync(){
  let fetchResult = yield call(fetchIncrement);
  console.log(fetchResult); // logs 1 (parsed from "1")
  yield put({type: 'INCREMENT_COUNT', payload: fetchResult}) // payload is 1 (number)
}
```

**Comment by dantenovski** [comment]
Thank you! But it prints NaN and upon inspection it turns out to be the Promise object.
```
    const data = response.json();
    console.log(data); // prints "1" <- actually prints Promis object
```

**Comment by dantenovski** [comment]
I got help and the suggested code is like this:

```javascript
function * fetchIncrement () {
  const response = yield call(
    fetch,
    `url`
  );
  const data = yield call([response, response.json])

  const number = parseInt(data)
  console.log(`const number below`);
  console.log(number)
  return number
```
And it works but I don't know if this is the correct way or easiest way. Also I don't fully understand how this one works:
```
const data = yield call([response, response.json])
```
We pass in the returned Promise object and also a function that will convert [[PromiseValue]] into json?

**Comment by sgal** [comment]
@dantenovski Ah, sorry, forgot that `response.json()` also returns promise.

As for your question - it is simply calling a function with specific context. See [here](https://github.com/redux-saga/redux-saga/blob/master/docs/api/README.md#callcontext-fn-args)

So, your example can be explained like this.
```
const json = yield call([response, response.json]); // response is context here

// same as
const json = yield call([response, "json"]);
```

Hope it helps.

**Comment by dantenovski** [comment]
@sgal Thanks a lot! Finally it is clear why we have to use two calls. In the examples I found online there is only one call(fetch, url) and it returns a value, and that's why I've been struggling with it, I couldn't make it work. Now when you said that response.json() also returns a Promise it is clear why we have to make another yield call. Thanks again!

**Comment by Andarist** [comment]
Issue is solved, therefore going to close this thread. If you have any other questions, please just open a new issue or comment in here :)

@sgal thanks for answering

**Comment by dantenovski** [comment]
Thank you guys! Actually the problem was that I made fetchIncrement() a generator function by mistake, it supposed to be a regular function that returns a promise, so in that case there is no need for the second call i.e. call([ ]). Thanks Andarist for spotting it!

**Comment by unionthugface** [comment]
I have been trying to follow this example, but I keep getting an error on the `yield call([resp, resp.json])` part. I get `body stream already read`.  Can anyone assist with this?

**Comment by restrry** [comment]
seems someone in your code already called json on response
in code you can get the same error with
```js
fetch('your url').then(res => res.body().then(() => res.body()))
```

**Comment by aJoohongKim** [comment]
since this is one of top search result from google. I am leaving my solution.
`
function fetchIncrement(){
// return fetch({}).then().catch()
return fetch({
  method: 'get',
  url: 'http://www.haha.com/fetch_increment'
})
  .then(res => res.json())
  .catch(err=> err);
}
`

**Comment by unionthugface** [comment]
Here is a solution using async/await.  These would be considered "saga utilities":

```
import { call, put } from 'redux-saga/effects'

async function fetchJson(url) {
    let resp;
    try {
        let data = await fetch(url);
        resp = { data: await data.json() };
    }
    catch (e) {
        resp = { err: e.message };
    }
    return resp;
}

export function* fetchApi(path, successAction, failureAction) {
    try {
        const { data, err } = yield call(fetchJson, `//${baseApiUrl}${path}`);
        if (!!data)
            yield put({ type: successAction, data });
        else
            yield put({ type: failureAction, ...err.message });
    }
    catch (e) {
        yield put({ type: failureAction, message: e.message });
    }
}
```

And this would be in use:
```

function* fetchPayRates() {
    yield call(fetchApi, 'rate/mpr', PAY_RATES_FETCH_SUCCEEDED, PAY_RATES_FETCH_FAILED);
}
```
