### ISSUE TITLE
how can i test if block in jest like this lines of code 

### ISSUE THREAD

**Issue by kumar155** [redux-saga/redux-saga#1137]
const dataTypeName = mapDataTypes(dataType);
      if (dataTypeName.length === 0) {
        return;
      }
      yield put(sourceActions.onRdsmSourcePlantRequestStarted());
this case how can check the if block

**Comment by Andarist** [comment]
You can check `done` property of the resulting object when `dataTypeName` is empty to check if the iterator has finished.
