### ISSUE TITLE
Yielding fetch json loses reference to the responses `this` and causes an error

### ISSUE THREAD

**Issue by jedrichards** [redux-saga/redux-saga#1141]
The following code throws an error:

```js
const res = yield call(fetch, 'some-url')
const json = yield call(res.json)
// TypeError: Cannot read property 'text' of null
```

I need to bind the json function back to `res` to make it work

```js
const res = yield call(fetch, 'some-url')
const json = yield call(res.json.bind(res))
```

Is this expected? I'm using React Native.

**Comment by Andarist** [comment]
It is expected, its just how javascript works and there is nothing we can do about here, we provide a special way of using `call` for this use case though. You can do this:
```js
const res = yield call(fetch, 'some-url')
const json = yield call([res, 'json']) // or yield call([res, res.json])
```

**Comment by jedrichards** [comment]
Aha thanks! Good to know - I could have just checked the docs more carefully. My b.

**Comment by mahmoudsalahmis** [comment]
Hello,

You can use apply as well.

`const data = yield apply(res, res.json);`
