### ISSUE TITLE
Detecting when a saga is cancelled automatically

### ISSUE THREAD

**Issue by eranimo** [redux-saga/redux-saga#1142]
Inside of a saga I have a `requestAnimationFrame` loop running that needs to be stopped manually when the saga has been cancelled. This is usually done automatically. I tried to use the `yield cancelled()` effect but it doesn't seem to work when the saga is cancelled automatically.

What is the best way to do this?

**Comment by Andarist** [comment]
@eranimo could u post example snippet that u are trying to use?

**Comment by bradennapier** [comment]
@eranimo sounds like the same question that was asked a few questions later.

https://github.com/redux-saga/redux-saga/issues/1169

I answered it there.

**Comment by Andarist** [comment]
I believe this issue is about something else. requestAnimationFrame would be best wrapped in an eventChannel in the saga, from the eventChannel creator u should return an unsubscribe function so it can be called automatically when u call .close on the returned channel (in finally block of ur saga)

**Comment by Andarist** [comment]
This thread got a little bit stale, so Im closing it. Feel free to respond back later or create a new issue.
