### ISSUE TITLE
Allow using `all` with an object

### ISSUE THREAD

**Issue by jimbol** [redux-saga/redux-saga#1150]
The index based approach for `all` is good in many situations.

```es6
const [ a, b ] = yield all([
  call(fetchApi, '/posts/a'),
  call(fetchApi, '/posts/b'),
])
```

but sometimes it could be valuable to have the results stored on an object, much like [race](https://redux-saga.js.org/docs/advanced/RacingEffects.html) does.

```es6
const { a, b } = yield all({
  a: call(fetchApi, '/posts/a'),
  b: call(fetchApi, '/posts/b'),
})
```

If `all` won't support this change, I would suggest the term `parallel` instead.

If there is interest, I can work on this.

**Comment by Andarist** [comment]
It's already working ;) https://github.com/redux-saga/redux-saga/blob/master/test/proc/parallel.js#L125-L130

Also documented in the API docs [here](https://redux-saga.js.org/docs/api/#alleffects)
