### ISSUE TITLE
Using Channels with firebase

### ISSUE THREAD

**Issue by ygorlf** [redux-saga/redux-saga#1151]
I'm having trouble to make my store listen to changes on my firebase database, I think the eventChannel is the right way, but when I refresh the page i get only the first entry of firebase on the channel.

```
const subscribePosts = (socket) => {
  return eventChannel((emit) => {

    const insert = (snap) => {
      emit(addPost(snap.val()));
    };

    postsRef.on('child_added', insert);
   
    return () => {};
  });
};
```

```
function* postsChannel(socket) {
  const channel = yield call(subscribePosts, socket);
  while(true) {
    const action = yield take(channel);
    yield put(action);
  }
};
```

```
export function* mainSaga() {
  yield fork(postsChannel);
};
```

Sorry to post here, maybe stackoverflow was a better place :)

**Comment by Andarist** [comment]
Ur code seems to be fine. Did you check if u receive more than 1 items from the firebase? I would advice u to start from putting a simple `console.log` in the `insert` function

**Comment by ygorlf** [comment]
Yes, All the items are coming from the firebase, but the emit is happening only for the 1st item

**Comment by ygorlf** [comment]
I set up a webpackbin link with the issue, I don't know why but redux-saga is not working properly on webpackbin but when I download the repo and run locally works perfectly, in the console it's printed 4 items but only the 1st is dispatched to redux :(

https://www.webpackbin.com/bins/-KstpbNrGSjKADpQtC4w

**Comment by Andarist** [comment]
Im not entirely sure why this happens - but I have a really strong guess ;)

Ur inserts happen really fast (in the same synchronous call stack). `put` effect while non-blocking it might be a little bit delayed for internal scheduling reasons. So while `put` is for a brief moment blocked and not released yet, next `take` happens after ur emits, so it misses them.

As a workaround for this problem I propose to specify a buffer for ur channel like this:
```js
const subscribePosts = (socket) => {
  return eventChannel((emit) => {

    const insert = (snap) => {
      emit(addPost(snap.val()));
    };

    postsRef.on('child_added', insert);

    return () => { };
  }, buffers.expanding());
};
```

Everything will work as expected then.

**Comment by ygorlf** [comment]
thank's, works perfectly :)
