### ISSUE TITLE
Testing cloneableGenerator with mocha

### ISSUE THREAD

**Issue by klis87** [redux-saga/redux-saga#1154]
In testing example https://redux-saga.js.org/docs/advanced/Testing.html you show how to test sagas with `tape` library. I am interested in this part: 

```javascript
test('doStuffThenChangeColor', assert => {
  const data = {};
  data.gen = cloneableGenerator(doStuffThenChangeColor)();

  assert.test('user choose an even number', a => { // how to do sth like this with mocha/chai?
    data.clone = data.gen.clone();
    a.deepEqual(
      data.gen.next(chooseNumber(2)).value,
      put(changeUI('red')),
      'should change the color to red'
    );

    a.end();
  });

  assert.test('user choose an odd number', a => {
    a.deepEqual(
      data.clone.next(chooseNumber(3)).value,
      put(changeUI('blue')),
      'should change the color to blue'
    );

    a.end();
  });
});
```

What is the best way to test `cloneableGenerator` with `mocha/chai`?

**Comment by Andarist** [comment]
Hey, could u elaborate on ur question? Im not sure what is the part you are asking for. Shouldn't testing with mocha/chai look pretty much the same as with tape?

**Comment by klis87** [comment]
Yes, it looks really similar, the problem is, that I wanted to have something like nested `assert` (assert.test) in `it` block, so I could test generator branches in a readable way within one `it` block. I guess this is not possible and it is just better to test 1 branch per each `it` block. I guess we could close this issue :)

**Comment by klis87** [comment]
Yes, I think this is the best way to go about this. Thanks 👍
