### ISSUE TITLE
Unit testing with redux saga

### ISSUE THREAD

**Issue by Kshirodram** [redux-saga/redux-saga#1163]
I want to do the unit testing for the following watchers and workers using mocha and chai. Can someone help here?

I did write some unit test case but its not working as expected

***example***

    import { expect } from "chai";
    import { take, call } from "redux-saga/effects";

    import * as actions from "client/actions";
    import { watchGetFavorites } from "client/sagas/watchers/favorite-watcher";
    import { fetchFavorites } from "client/sagas/workers/favorite-worker";

    describe("favorite-watcher saga", () => {
      const generator = watchGetFavorites();
      it("it should execute watchGetFavorites", () => {
        expect(generator.next().value).to.deep.equal(take(actions.GET_FAVORITES));
      });
      it("it should execute watchGetFavorites api", () => {
        const data = {
          "loadAction": {
            type: actions.GET_FAVORITES,
            "payload": {
              "userId": "id"
            }
          }
        };
        const apiCall = generator.next(data);
        expect(apiCall).to.deep.equal(call(fetchFavorites, data));
      });
    });

The 1st test case is passing but however the second one is failing and I also want to know how can I test the entire watchers so that it will also cover the worker code.

**RootSaga**

    import {fork} from "redux-saga/effects";
    import * as favoriteWatcher from "./watchers/favorite-watcher";

    export default function *rootSaga() {
      yield [
        fork(favoriteWatcher.watchGetFavorites)
      ];
    }

***Watcher***

    import {take, call, takeEvery} from "redux-saga/effects";
    import * as actions from "../../actions/index";
    import * as workers from "../workers/favorite-worker";

    export function* watchGetFavorites() {
      const loadAction = yield take(actions.GET_FAVORITES);
      yield call(workers.fetchFavorites, loadAction.payload);
    }

    export function* watchDeleteFavorites() {
      yield takeEvery(actions.DELETE_FAVORITE, function*(loadAction) {
        yield call(workers.deleteFavorites, loadAction.payload);
      });
    }

***Worker***

    export function* fetchFavorites(payload) {// eslint-disable-line
      try {
        const response = yield call(fetchForJson, `${config.API.favoritesListURL}/${payload.userId}`); //api call
        yield put({//dispatch
          type: actions.GET_FAVORITES_SUCCESS,
          result: response.result,
          fetching: false
        });
      } catch (error) {
        yield put({
          type: actions.GET_FAVORITES_ERROR,
          result: error,
          fetching: false
        });
      }
    }

    export function* deleteFavorites(payload) {
      try {
        const response = yield call(deleteJson, `${config.API.deleteFavoriteURL}/${payload.userId}`, payload); //api call
        yield put({//dispatch
          type: actions.DELETE_FAVORITE_SUCCESS,
          result: response.result,
          fetching: false
        });
      } catch (error) {
        yield put({
          type: actions.DELETE_FAVORITE_ERROR,
          result: error,
          fetching: false
        });
      }
    }

Any help really appreciated.

**Comment by wisn** [comment]
Check this [one](https://github.com/infinitered/ignite-example-login/blob/master/Tests/Sagas/LoginSagaTest.js).

**Comment by ianhowe76** [comment]
Also from the docs: https://redux-saga.js.org/docs/advanced/Testing.html
