### ISSUE TITLE
How to chain firebase observables using redux-saga?

### ISSUE THREAD

**Issue by maitham1** [redux-saga/redux-saga#1164]
I am trying to chain three firebase requests using redux-sagas. I require one of the API requests in the chain to continuously emit its payload. As I need to retrieve grpID's first from the userProfile, then the grpObject and then attach the latest conversation to the grpObject which will change depending on the latest message in the group. Thus I need to be able to continuously obtain the latest message from firebase.

```
 userProfile
    userID
         groups
              grpID1:true
              grpID2:true 

groups
       grpID1
            grpName
            created
            members
                  member1 
                  member2

conversations 
         grpID
             msgID
          
```

I understand why this doesn't work and I guess I could put a while loop within fetchChatGroups() and continuously monitor if the object has changed, then dispatch the action if it has. But I was wondering what is best practice for this use case?

```
`function* getMemberProfiles(UID) {
  try {
    const memberObject = yield call(get, 'userProfile', UID);
    return memberObject;
  } catch (err) {
    console.log(err);
  }
}

function* getLatestConversation(grpID) {
  try {
    const opts = newOpts();
    const refLatestConvo = firebase
      .database()
      .ref('conversations')
      .child(`${grpID}`)
      .orderByChild('createdAt')
      .limitToLast(1);
    yield call([refLatestConvo, refLatestConvo.on], 'value', opts.handler);
    while (true) {
      const { data } = yield take(opts);
      if (data.val()) {
        return data.val()[data._childKeys[0]];
      }
      return null;
    }
  } catch (err) {
    console.log(err);
  }
}

export function* getChatGroupObject(grpID, tuteeUID) {
  try {
    const groupObject = yield call(get, 'groups', grpID);
    const memberProfiles = yield Object.keys(groupObject.members)
      .filter(mem => mem !== tuteeUID)
      .map(memUID => call(getMemberProfiles, memUID));
    const latestConversation = yield call(getLatestConversation, grpID);
    return { ...groupObject, memberProfiles, key: grpID, latestConversation };
  } catch (err) {
    console.log(err);
  }
}

/**
 *
 * @return {Generator} []
 */
export function* fetchChatGroups() {
  try {
    const opts = newOpts();
    const tuteeUID = yield select(getTuteeUID);
    const refGrpIDs = firebase.database().ref('userProfile').child(`${tuteeUID}/groups`);
    const snapGrpIDs = yield call([refGrpIDs, refGrpIDs.once], 'value', opts.handler);
    if (snapGrpIDs.val()) {
      const groupObject = yield Object.keys(snapGrpIDs.val()).map(grpID =>
        call(getChatGroupObject, grpID, tuteeUID),
      );
      yield put(ChatAction.chatGroupsReceived(groupObject));
    } else {
      ChatAction.chatGroupsReceived([]);
    }
  } catch (error) {
    console.log(error);
  }
}`
```

**Comment by Andarist** [comment]
Could u list ur requirements, Im not entirely sure what the flow - what u only listen for, what kind of requests need to be done, does something need to be queued? I confess I've looked at it only briefly, but had hard time to understand this quickly.

**Comment by maitham1** [comment]
Ah sorry. So I am listening to three different firebase paths in my database. I first collect a list of keys from the database (1st db ref), I then query a different reference to get the actual objects related to those keys(2nd db ref) using a key from within this object I query a different reference to get another object.
Now I need my final query to be continuously listening, and if there is a change within firebase within the innermost query I need the saga to dispatch an action updating the entire object.

Does that make sense?

**Comment by Andarist** [comment]
Hm. So you need to only dispatch results of the third query, but 1st and 2nd causes updates to the next ones (in the end of the chain to the 3rd one). Is that all?

**Comment by maitham1** [comment]
Yes exactly, but I need to do this for an array of keys.

**Comment by maitham1** [comment]
Can anyone help?

**Comment by Andarist** [comment]
You have not described in the latest post whats the trigger for this cascade. Should this cascade be restartable from the inside? From the outside? Both? Or never?

**Comment by maitham1** [comment]
@Andarist sorry, it should be restartable from the inside!

**Comment by Andarist** [comment]
Im still not sure when do u want to restart it, because you mention a desire to use `.once` - and that wont give u any future triggers.

Anyway I would just create a special `RESTART` action and use it like this:
```js
while (true) {
  const task = yield fork(fetchChatGroups)
  yield take(RESTART)
  yield cancel(task)
}
```

So at any moment from the inside (and outside too if thats desirable) you can always `yield put(RESTART)`. Just remember to unsubscribe from the firebase refs in ur `finally` block. You probably want to wrap ur inner most query (the one in `getLatestConversation`) in the `eventChannel` - so it can be nicely consumed with `take`.

**Comment by maitham1** [comment]
@Andarist  I get what you're saying but I have no idea how to implement it using sagas, whats the best practice when it comes to something like this? I would only restart the saga if the event channel getLatestConversation emits a new value.

**Comment by maitham1** [comment]
I guess the main thing I'm struggling with is how do you form an array of channels?

**Comment by maitham1** [comment]
https://github.com/andarist Any way of doing this?

**Comment by maitham1** [comment]
@Andarist 
Hey, I ended up doing this which seems to work quite well only thing is whats the best way of cancelling the subscription?
```

export function* fetchChatGroups() {
  try {
    const grps = yield call(getGroupIDs);
    // while (true) {
    yield grps.map(grpID => put(ChatAction.attachGroupListener(grpID)));
    // yield put({ type: 'CANCEL_LISTENERS' });
    // const action = yield take(() => ChatAction.cancelListeners());

    // if (action.type === 'CANCEL_LISTENERS') {
    //   yield cancel(listen);
    // }
    // }
  } catch (error) {
    console.log(error);
  }
}

export function* attachGroupListener({ grpID }) {
  let groups = {};
  try {
    groups = yield call(groupChannel, grpID);
    while (true) {
      const group = yield take(groups);
      const grpObject = { ...group[grpID], key: grpID };
      const grpObjectWithMembers = yield call(getGroupMembers, grpObject.members, grpObject);
      yield put(ChatAction.attachConvoListener(grpID, grpObjectWithMembers));
    }
  } catch (error) {
    console.log(error);
  } finally {
    if (yield cancelled()) {
      groups.close();
    }
  }
}

export function* attachOneConvoListener({ grpID, grpObject }) {
  let convo = {};
  try {
    convo = yield call(fbEventChannel, grpID);
    while (true) {
      const latestConvoRaw = yield take(convo);
      const key = Object.keys(latestConvoRaw[grpID])[0];
      const latestConversation = { ...latestConvoRaw[grpID][key], _id: key };
      console.log('UPDATE CHAT GROUP', { ...grpObject, latestConversation });
      const tuteeUID = yield select(getTuteeUID);
      yield put(ChatAction.chatGroupsReceived({ ...grpObject, latestConversation, tuteeUID }));
    }
  } catch (error) {
    console.log(error);
  } finally {
    if (yield cancelled()) {
      convo.close();
    }
  }
```

**Comment by bradennapier** [comment]
@maitham1 you may want to look at our "Firebase Listener" package which does lots of firebase-specific stuff

https://github.com/Dash-OS/firebase-listener

**Comment by Andarist** [comment]
@maitham1 hey, sorry for being not so active lately - unfortunately i had other things on my mind

did you resolve ur issue? do u still have any questions? please respond back so I can either close this issue or help u further
