### ISSUE TITLE
Add race([...effects])

### ISSUE THREAD

**Issue by klis87** [redux-saga/redux-saga#1166]
`all` effect allows to pass both array and object. It would be nice if the same was possible with `race`. Sometimes we aren't interested which effect won, sometimes all we care about is that 1 effect won and the rest was automatically cancelled by Saga.

For this use case, this
```
yield race([
  call(someFunction),
  take('ACTION_WHICH_SHOULD_STOP_EXECUTING_SOME_FUNCTION`
]);
```
is much more convenient than
```
yield race({
  someFunctionResult: call(someFunction),
  cancelAction: take('ACTION_WHICH_SHOULD_STOP_EXECUTING_SOME_FUNCTION`
});
```
because we won't use `someFunctionResult` or `cancelAction` keys, setting them here should not be necessary and array syntax is preferable.

**Comment by Andarist** [comment]
It's already supported, keys for the race resolution are [internally obtained with `Object.keys`](https://github.com/redux-saga/redux-saga/blob/f609e805a7a877fa6b8c14934ad207a05df7aad2/src/internal/proc.js#L619-L621) which works with arrays too (as they are objects 😉 ).

**Comment by klis87** [comment]
Ohh great, do you think it would be beneficial to add this to the docs? If yes, I could do it if you don't mind.

**Comment by Andarist** [comment]
Surely I dont min, happy to accept PRs :) those to the docs are the most valuable!

**Comment by klis87** [comment]
Ok great, I am already into it :)

**Comment by Andarist** [comment]
Going to close this issue then and I'll wait for the PR. Thanks for a contribution will! :)

**Comment by Hauuguu** [comment]
Quick question. Before you would do

```
const winner = yield race({
  someFunctionResult: call(someFunction),
  cancelAction: take('ACTION_WHICH_SHOULD_STOP_EXECUTING_SOME_FUNCTION`
});

if (winner.someFunctionResult){
  [...do something here...]
}
```

How would this work in your proposed method @klis87 ?

**Comment by klis87** [comment]
@Hauuguu My initial idea was to use this syntax only when actually I don't need to know the winner:
```javascript
yield race([
  call(someFunction),
  take('ACTION_WHICH_SHOULD_STOP_EXECUTING_SOME_FUNCTION')
]);
```
I could do it for example when I would like `someFunction` task to be cancelled automatically when `ACTION_WHICH_SHOULD_STOP_EXECUTING_SOME_FUNCTION` is the winner. 

And yes, PR was already submitted, but it is waiting for review #1167 

After PR is merged, it will be possible like this:
```javascript
const [someFunction, cancelAction] = yield race([
  call(someFunction),
  take('ACTION_WHICH_SHOULD_STOP_EXECUTING_SOME_FUNCTION')
]);

if (someFunction){
  [...do something here...]
}
```

**Comment by Hauuguu** [comment]
Great, thanks! Looking forward to it :)

**Comment by Andarist** [comment]
@Hauuguu you can use it even today. Sent PR just adds info about this to the docs and adds support for destructuring such race's result:
```js
const [a, b] = yield race([effA, effB])
```
