### ISSUE TITLE
How could we know about finishing of the task (not cancelation)?

### ISSUE THREAD

**Issue by alexeybondarenko** [redux-saga/redux-saga#1169]
I'm looking for the solution to know about the finishing of the task. We can know about the cancellation, but I also want to know about the end of the task.

Do we have a way to do this?

**Comment by bradennapier** [comment]
@alexeybondarenko I do this in [saga-task-manager](https://github.com/Dash-OS/saga-task-manager) and it works very well. 

Take a look here: https://github.com/Dash-OS/saga-task-manager/blob/master/src/main.js#L139-L193

**Comment by alexeybondarenko** [comment]
@bradennapier thank you for the solution. I've found another one way. Task.done is a promise so I can wait for its resolve.

https://github.com/redux-saga/redux-saga/blob/master/examples/real-world/server.js#L59

**Comment by bradennapier** [comment]
Heh, that is exactly what is being done there.  :-) But great, glad you figured it out.  You should probably also validate the task first using the TASK symbol as done in the task-manager example.  That was recommended by the core team.

**Comment by alexeybondarenko** [comment]
@bradennapier ahh, sorry) thank you! 👍
