### ISSUE TITLE
Unable to cancel a particular action

### ISSUE THREAD

**Issue by solodynamo** [redux-saga/redux-saga#1173]
I am supposed to prepare a demo for action cancellation in saga .I made the demo but the action is not getting cancelled even after the console prints **it has been cancelled**. I am trying to listen for **INCREMENT_ASYNC** and cancel it but counter is getting incremented after console prints cancellation.

DEMO: https://codesandbox.io/s/179xo5y4j

**Comment by Andarist** [comment]
You have started 2 independent tasks depending on the `INCREMENT_ASYNC` action. Both `cancelTheAsyncIncrement` and `incrementingAsync` fork `incrementAsync`, but only the former gets cancelled.

If you remove the `incrementingAsync`, everything is gonna work as expected.
