### ISSUE TITLE
'call' objects equallity

### ISSUE THREAD

**Issue by alexxmde** [redux-saga/redux-saga#1182]
I have the following code in my unit test:

`expect(generator.next().value).toEqual(
        call([api.Writters, api.Writters.update], writterId, update))`
When it runs, Jest outputs the message:

> Difference:
    
    Compared values have no visual difference.

If I JSON.stringify booth results and test their equallity, the test passes.
I have other tests where I do this same thing and they don't behave like this one. 
I don't think stringifying the objects is a good thing, so, what am I missing out here?

**Comment by s-kem** [comment]
Do any of the objects you're passing to call contain functions?

If you see `[Function anonymous]` anywhere in the output that's likely where the differences lie (they're not the same instance of a function), so the visual comparison passes, but I think Jest is checking if you pointing to the same anonymous function.

`JSON.stringify()` on an object with functions strips the functions.

**Comment by swannknani** [comment]
You experiencing this issue because jest cannot make the difference between 2 anonymous function.
In order to fix that, you'll need to provide a named function to you mock.
Because jest hoist mock declarations, you'll need to declare your named function **inside** your mock.

```
jest.mock('../selectors', () => {

	function mockedMakeSelectCoverageResult() {}
	return ({
		makeSelectCoverageResult: () => mockedMakeSelectCoverageResult,
	});

});

expect(descriptor).toEqual(select(makeSelectCoverageResult()));
```

**Comment by Andarist** [comment]
Also you could just extract used function to some module, that way `call` effect creator could use each time the same function, therefore 2 `call`s would become comparable with regular `deepEqual`.
