### ISSUE TITLE
Does redux-saga has conflict with another redux-middleware?

### ISSUE THREAD

**Issue by LaiHuanMin** [redux-saga/redux-saga#1187]
Hi! Sorry to post this issue, I'm coding a project about **company manage system**. Just for now, I have finish almost half of project, and **only use redux-thunk to resolve async dispatch**.  
I learned saga middleware recently, I think the saga middleware is better than thunk because of it's strong control without another async control kit (like **async** , **co**,etc).
I wanna know if there's conflict between **redux-saga and another redux-middleware**(such as thunk,redux-promise)?  If it's safe to use, I wanna use redux-saga partly and will convert the thunk code into saga code soon(thunk code and saga code maybe will exist together in a short time ).  
Could you tell me if you know about this situation ?  thanks a lot!

**Comment by neurosnap** [comment]
There shouldn't be any conflicts between using `redux-thunk` in conjunction with `redux-saga`.

**Comment by LaiHuanMin** [comment]
@neurosnap Thanks, I have use redux-thunk and redux-saga together for project
