### ISSUE TITLE
Type error, string not assignable to Channel<{ payload: any; }>

### ISSUE THREAD

**Issue by ebardajiz** [redux-saga/redux-saga#1188]
I'm getting the following TypeScript error with this code:

```jsx
export function* someListener() {
  yield takeEvery("ACTION_TYPE", someSaga)
                // ^^^^^^^^^^^
}
```

Error:

`argument of type 'string' is not assignable to parameter of type 'Channel<{ payload: any; }>'`

Is it me, or is this a TS thing?

**Comment by aikoven** [comment]
Could you please post a bit more code? What's the type of `someSaga`? Do you import `takeEvery` from `redux-saga` or `redux-saga/effects`?

**Comment by ebardajiz** [comment]
The full code looks like this:

```js
import request from 'superagent'
import { call, put, select , takeEvery } from 'redux-saga/effects'

export function* fetchExampleSaga({ payload: ids}) {
  try {
    const data = yield call(request.get, '/api/example')
    yield put(example.success(data))
  } catch (e) {
    yield put(example.error(e))
  }
}

export function* networkListeners() {
  yield takeEvery(EXAMPLE_REQUEST, fetchExampleSaga)
}
```

**Comment by bstro** [comment]
I'm also running into this. I've had to use `take` with `while (true)` loops instead of takeEvery/takeLatest to get around it. This isn't a long-term solution but it gets me moving for now.

**Comment by aikoven** [comment]
Type definition for `takeEvery` has two groups of overloaded signatures: one for taking actions by pattern and another for taking from channels. When TypeScript is unable to match any of these signatures, it shows error regarding the last one it tried.

I'm certain that you have some type error that prevents TS from matching the first group.

You may try this: open `node_modules/redux-saga/effects.d.ts`, find `takeEvery` definition, and comment out all the signatures with `Channel`. You'll get the correct TS error after that.

**Comment by aryzing** [comment]
@aikoven thanks, I think you're on to something :) Indeed, it did make the error message clearer: `Property 'payload' is missing in type 'Action'`.

The thing is, I just changed this file's extension from .js to .ts. I was under the impression I'd be able to adopt TS gradually without any errors... any final thoughts before closing the the issue? Any compiler settings I should look in to?

**Comment by aikoven** [comment]
> The thing is, I just changed this file's extension from .js to .ts.

Hopefully, someday it would be as easy as this.

> Any compiler settings I should look in to?

If you're migrating an existing project, I suggest using defaults. Once you get more confident with TS, use `--strict` option.

> Also, I've noticed that if instead of using object destructuring syntax I simply use fetchExampleSaga(action) the error goes away. Suggestions?

I suggest to always declare the types for arguments of standalone functions (that is, functions that are not inlined callbacks). This way you give TS a starting point for type inference. The return type is almost always optional because it can be inferred from your function returns.

**Comment by Andarist** [comment]
The issue itself seems to be solved, therefore I'm closing this thread. Feel free to discuss further though if you want.

**Comment by djereg** [comment]
It is and old issue, but today I had the same error.
The solution was type hinting, the function arguments, and there is no need for any workaround.

```typescript
export function* fetchExampleSaga({ payload: ids}: AnyAction) {
  // ...
}
```

**Comment by robbyemmert** [comment]
I'm getting the same error also, only when I try to pass additional arguments into my sagas. I.e.

```
export function* authSaga(graphQL: GraphQLApi) {
    yield takeLatest(LoginForm.ActionTypes.SUBMIT, function*(action: StandardAction<Login>, graphQL: GraphQLApi) {

    }, graphQL)
}
```

If I remove the 'graphQL' argument, it works perfectly.

**Comment by charlax** [comment]
Still happening with latest version (1.0.2).

1. I commented the channel-related types in `@redux-saga/core/effects.d.ts`
2. Got the actual error `Property 'payload' is missing in type 'Action<any>' but required in type`
3. I put `AnyAction` in the saga handler.

```
import {AnyAction} from 'redux'

function* uploadSaga({ payload: { file: f, files, folderID } }: AnyAction) {
```

**Comment by Frontmaster** [comment]
I have encountered the same issue.
And a resolution is quite simple. When desctructuring an Action object it's necessary to specify mandatory properties from your interface/type if any.
- Works:
```
type TAction = {
	type: string;
	payload?: any;
	meta?: any;
	error?: boolean;
};

function * saveUserSettings({type, payload}) {
	try {
		const response = yield call(UserService.saveSettings, payload);
		yield put(SaveSuccess(response));
	} catch (e) {
		yield put(SaveFail(e));
	}
}
```
- Also works:
```
function * saveUserSettings(action) {
	try {
		const response = yield call(UserService.saveSettings, action.payload);
		yield put(SaveSuccess(response));
	} catch (e) {
		yield put(SaveFail(e));
	}
}
```
- Doesn't work:
```
ype TAction = {
	type: string;
	payload?: any;
	meta?: any;
	error?: boolean;
};

function * saveUserSettings({payload}) {
	try {
		const response = yield call(UserService.saveSettings, payload);
		yield put(SaveSuccess(response));
	} catch (e) {
		yield put(SaveFail(e));
	}
}
```

**Comment by rufatZZ** [comment]
in my case, that error caused for i didnt put types to my params, then i had to put type definitions for my watcher function params,  then this error fixed,

like, im using typescript-fsa-redux-saga
 before:
`bindAsyncAction(actionCreators.somethingAsync)(`
   ` function* (params): SagaIterator {`
      `return {bar: 'lol'};`
   ` }`
 ` )`

after i added types
`bindAsyncAction(actionCreators.somethingAsync)(`
   `   // here params received types`
    `     function* (params: RQ): SagaIterator {`
      `return {bar: 'lol'};`
   ` }`
 ` )`
