### ISSUE TITLE
Typescript type error: Cannot yield promise

### ISSUE THREAD

**Issue by eivhyl** [redux-saga/redux-saga#1191]
Hello, I'm trying to yield a promise inside a saga (in 0.15.6, ts 2.5.2), but I'm getting the following error when I transpile:
```
Type 'Promise<any>' is not assignable to type 'RootEffect | TakeEffect | ChannelTakeEffect<any> | PutEffect<any> | ChannelPutEffect<any> | AllEf...'.
  Type 'Promise<any>' is not assignable to type 'Effect[]'.
    Property 'includes' is missing in type 'Promise<any>'.
```
Note that the code actually works, it's the type errors that's failing.

See example code below:
```typescript
function* saga (): SagaIterator {
	const response: Response = yield call(fetch, 'http://www.example.com/')
	const body = yield response.json()
}
```

**Comment by aikoven** [comment]
`SagaIterator` is meant to be used for strict type checks where you only `yield` effects. It is completely opt-in, if you don't need such strictness, you may just remove `SagaIterator` annotation.

**Comment by eivhyl** [comment]
Ah okay, my bad. Closing this.
