### ISSUE TITLE
Console.error: "uncaught at *action", _hasBinary@http://localhost...

### ISSUE THREAD

**Issue by ethan520** [redux-saga/redux-saga#1193]
Hi, I'm new to redux-saga, struggling looking for the cause of the below issue. Can someone please kindly help me to clarify what's wrong with it? Would appreciate your help very much. 

This is the error message I got when I was about to update my state via an action that created in redux-saga.

![screen shot 2017-10-02 at 5 49 07 pm](https://user-images.githubusercontent.com/16395613/31072429-80d8f990-a79a-11e7-916f-5d9740bce84a.png)

The below is the codes of the created saga:

export function * submit (data) {
  if (data) {
    //dispatch successful update
    try {
      //put(FormActions.submitData(data))
      yield put(FormActions.submitData(data))
    } catch (error) {
       // dispatch failed update
       yield put(FormActions.updateFailed("Updated failed"))
    }
  } else {
    yield put(FormActions.updateFailed("There are no inputs to update."))
  }
}

Try 1: Without the 'yield' syntax, it managed to update the state without prompting error. But 
           the view was gone haywire somehow after it.
Try 2: Without 'yield' syntax, the above error showed after executing the action.

Am I making some mistakes?

**Comment by neurosnap** [comment]
I don't see anything obviously wrong with the code you pasted, but it doesn't show the entire picture here for us.

Could you show us the actual watch task you are using to activate `submit`?

**Comment by ethan520** [comment]
Thanks for the reply! Let me explain further on the issue I'm facing right now.

I'm using ignite-native-base-boilerplate as my startup template. 

**Below is my actions, reducer & initial state of the PropertyRedux.js**

/* ------------- Types and Action Creators ------------- */
const { Types, Creators } = createActions({
  submitData: ['propertyObject'],
  updatedSuccess: ['data'],
  updateFailure: ['error']
})

export const PropertyDataTypes = Types
export default Creators

/* ------------- Initial State ------------- */

export const INITIAL_STATE = Immutable({
  propertyObject: {
    property_address_1: "F-5-17",
    property_address_2: "IOI Boulevard",
  },
  submitted: false
})

/* ------------- Reducers ------------- */

export const submitData = (state) => state.merge({...state, submitted: true, ...state.propertyObject})

/* ------------- Hookup Reducers To Types ------------- */

export const reducer = createReducer(INITIAL_STATE, {
  [Types.SUBMIT_DATA]: submitData,
  [Types.UPDATED_SUCCESS]: updatedSuccess,
  [Types.UPDATE_FAILURE]: updateFailed,
})

**In Property.js, I'm calling the savePressed() and dispatch it like below:**

submitPressed (data) {
      this.props.savePressed(data)
}

const mapDispatchToProps = (dispatch) => {
  return {
    savePressed: (propertyObject) => dispatch(FormActions.submitData(propertyObject))
  }
}

After I called the function, this error appears. Am I stated it in a more clear way? Let me know if you're still have any doubts. Thanks in advance.

**Comment by Andarist** [comment]
Please format your code with proper indentation - it is unreadable in the current form and it's even harder to help you with your problem.

The error means that you have made some kind of mistake in the code that **handles** ur action. By looking at your code I think it might be here:
```js
export const submitData = (state) => state.merge({...state, submitted: true, ...state.propertyObject})
```
I think what you have wanted is
```js
export const submitData = (state, action) => state.merge({...state, submitted: true, ...action.propertyObject})
```

But ofc it might be some kind of other error. You can always setup breakpoints/debugger statements in your code to get better insight into the matter.

You can also setup a breakpoint inside redux-saga code [here](https://github.com/redux-saga/redux-saga/blob/0820081662936c827e6928bf2b62448686bcb87d/src/internal/proc.js#L474) to inspect caught error which should probably give u better udnerstanding of the problem.

**Comment by ethan520** [comment]
@Andarist , thanks for your time on looking at my question. After i amended according your suggested code, the redux store failed to update. 

But i managed to update the redux store with the below codes:
`export const submitData = (state, action) => {
  const { propertyObject } = action
  return {...state, submitted: true, propertyObject}
}`

But getting this error after i after calling the submitData function.
![screen shot 2017-10-09 at 10 49 27 am](https://user-images.githubusercontent.com/16395613/31323944-171997b2-ace0-11e7-9c16-d82fee494fa6.png)

This is my sagas **submit** function
`
export function * submit ({data}) {
  if (data) {
    // dispatch successful update
    try {
      yield put(FormActions.submitData(data))
    } catch (error) {
       yield put(FormActions.updateFailed("The inputs are not updated yet!"))
    }
  } else {
    // dispatch failed update
    yield put(FormActions.updateFailed("No inputs!"))
  }

}
`

I'm so sorry if troubling you. Appreciate if could get some help from you. =D

**Comment by Andarist** [comment]
Your shared code is just too minimal to help you, the best way for you to get help would be either share the repository with a bug or reproduce it on something like codesandbox.io

**Comment by ethan520** [comment]
After debugging and some trial & error, it seems like if you're implementing reduxsauce + redux saga, they have their own way in structuring the functions. After I changed the param's name of **submit** function in the sagas.js from 'data' (self-defined) to 'propertyObject' (defined in the redux previously), it's working right now. Thanks for the help. Cheers
