### ISSUE TITLE
Module not found Errlr can't resolve react/lib/ReactMount on React 16.0.0

### ISSUE THREAD

**Issue by rkmax** [redux-saga/redux-saga#1194]
I have been using sagas 0.15.6 with React and React DOM 15.6.2, no problem oday I just try 16 and got

    Module not found: Error: Can't resolve 'react/lib/ReactMount' in '/my-project/src/sagas'

on every file inside my sagas (reducers, selectors, sagas) wherever where I use the redux-saga package

**Comment by neurosnap** [comment]
This might be an issue with using multiple versions of react.

Try entering this in terminal:

```bash
npm ls react
```

**Comment by rkmax** [comment]
the result is empty

I think the issue are the another dependencies that requires as peer dependecy react ^15.0.0

I'll close this one because is related to my project dependencies. Thanks @neurosnap for you help

**Comment by vicwang163** [comment]
I have the same issue, after runing 'npm ls react', there is only one react version, but the error occurs again
