### ISSUE TITLE
[DX] Babel plugin

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#1199]
It should be possible to create babel plugin to provide better error stack traces for our sagas in the similar way React and others do it with component stack traces.

**Comment by neurosnap** [comment]
This would be a great addition.  Often times our error stack traces from redux-saga are not helpful.

**Comment by Andarist** [comment]
@neurosnap what information such babel-enhanced error message could possibly have? I thought especially about saga traces - each `call`, `fork`, `spawn` could be tracked and the stack from the root saga could be reported.

**Comment by Andarist** [comment]
This should work very similar to:
https://babeljs.io/docs/plugins/transform-react-jsx-source/
https://babeljs.io/docs/plugins/transform-react-jsx-self/

Handling those things in the redux-saga itself in the development mode is ofc also needed.

**Comment by restrry** [comment]
what's your idea behind that plugin?
what kind of information it has to log?

1. place where effect was created?  that'll work for errors that occurs during calling effect creator, but won't work if error occurs in saga's body 
```js
function* a(){
    yield call(() => unitilisedVariable()); <- can be logged as error when `call` effect was created
}
function* b(){
    unitilisedVariable() <- can't be identified, since occurs not in effect creator. what should be included in error stack in that case?
}


```

2. or place where saga function was created?
```js
function* a(){
     unitilisedVariable() <- now we can add in stack trace info where function a* was declared
}
```

3. both ?

**Comment by Andarist** [comment]
I haven't thought this through yet, but the general idea was to log saga branch - from the root to the failing effect, creating sort of a stack from it, but not exactly the error stack, but the saga stack (similar to what React does for component stacks).

While I know how to manipulate babel's AST to some extent, I have not yet integrated anything with source maps and I guess we are looking for some sort of such integration.

For starters we could annotate each generator (we could detect if it yields an effect, but this could potentially cause some false negatives and annotating every generator shouldn't interfere with anything imho) with source line and inferred name with static properties. In addition we'd have to attach to each yielded value (let's assume everything is an effect) "parent saga" static annotations. That way those helpful infos could flow through the saga's runtime and it could collect it in case of an error to construct a custom error message.

**Comment by restrry** [comment]
I started working on the plugin https://github.com/restrry/babel-plugin-transform-redux-saga-source
but still open for new ideas and need help to integrate it in redux-saga itself

**Comment by russiancow** [comment]
Just to clarify, you don't actually need a babel plugin in order to be able to log the current "saga stack", do you? Since you know which generator is currently running when a task is yielded, redux-saga could keep track of that tree at runtime, and it should be able to grab the current stack at any point. So the only benefit (that I can think of) to a babel plugin is that it could give you line numbers (and potentially other info) on the caller side. Am I wrong about that?

(This is true of React as well—it shows a component stack without the Babel plugin, you just don't get line numbers.)

**Comment by Andarist** [comment]
Yeah, that's true. I'm not sure though if I'd like to include tracking those saga traces in production builds (costs some bytes). But yeah - babel plugin should be responsible for source mapping and nothing else.

**Comment by russiancow** [comment]
React gets around that via a `__DEV__` flag, which I assume uses the `process.env.NODE_ENV !== 'production'` trick that most build tools support. I don't have any experience with Rollup, but I know Webpack, at least, supports inlining of that value, which creates statements like `if (false)` in production, which get removed via dead code elimination—so in production, that code could be stripped out of the build completely. I'm afraid I don't know anything about how to set that up with Rollup, but the React repo might be a good example to use.

**Comment by Andarist** [comment]
There is [rollup-plugin-replace](https://github.com/rollup/rollup-plugin-replace) for exactly the same thing and I plan to use `process.env.NODE_ENV !== 'production'` trick to make it dev only.

I thought React do some of this stuff in prod mode too (i know it often do some stuff in dev mode exclusively), but I might be wrong, havent really checked it.

**Comment by Andarist** [comment]
Closing because the babel plugin has been implemented already.
