### ISSUE TITLE
Basic tutorial fail, mapDispatchToProps() in Connect(FAQ) must return a plain object. Instead received undefined

### ISSUE THREAD

**Issue by stackninigi** [redux-saga/redux-saga#1200]
Hi! I'm trying to use `redux-saga` in my project. I'm starting with simply fetching the data as an array from my API. However, I keep having this warning `mapDispatchToProps() in Connect(FAQ) must return a plain object. Instead received undefined`. Also, as I'm logging in my sagas, when I start the component, in console I see FAQSaga, watchData, actions, true but neither `getdata` nor `error` appear. I wonder why and how to fix it. 

My rootSaga:
```
import { fork } from 'redux-saga/effects';
import FAQSaga from '../sagas/FAQSaga.js';

export default function * rootSaga() {
    yield [
        fork(FAQSaga)
    ];
}
```
FAQSaga.js
```
import * as actions from '../actions/FAQActions';
import axios from 'axios';
import { call, put, take, fork } from 'redux-saga/effects';

export function* getData() {
    try {
        console.log('getdata');
        const response = yield call(axios.get, 'http://localhost:8080/rest/book/all');
        const data = yield response.json();
        yield put(actions.GET_FAQ.SUCCESS(data));
    } catch (e) {
        console.log('erorr');
        console.log(e);
        yield put(actions.GET_FAQ.FAILURE(e));
    }
}

export function* watchData() {
    console.log('watchData');
    while (true) {
        console.log('true');
        yield take(actions.GET_FAQ.REQUEST);
        yield fork(getData);
    }
    // yield takeEvery(actions.GET_FAQ.REQUEST, getData);
}

function * FAQSaga() {
    console.log('FAQSaga');
    yield [
        fork(watchData)
    ];
}

export default FAQSaga;
```

FAQActions.js
```
import {REQUEST, SUCCESS, FAILURE, action} from './helpers';

const GET_FAQ_BASE = 'GET_FAQ_';
export const GET_FAQ = {
    REQUEST: GET_FAQ_BASE + REQUEST,
    SUCCESS: GET_FAQ_BASE + SUCCESS,
    FAILURE: GET_FAQ_BASE + FAILURE
};

const POST_FAQ_BASE = 'POST_FAQ_';
export const POST_FAQ = {
    REQUEST: POST_FAQ_BASE + REQUEST,
    SUCCESS: POST_FAQ_BASE + SUCCESS,
    FAILURE: POST_FAQ_BASE + FAILURE
};

export const getFAQ = {
    request: () => action(GET_FAQ.REQUEST),
    success: response => action(GET_FAQ.SUCCESS, {response}),
    failure: error => action(GET_FAQ.FAILURE, {error})
};

export const postFAQ = {
    request: data => action(POST_FAQ.REQUEST, {data}),
    success: response => action(POST_FAQ.SUCCESS, {response}),
    failure: error => action(POST_FAQ.FAILURE, {error})
};
```

FAQ.js
```import React, {Component} from 'react';
import axios from 'axios';
import PropTypes from 'prop-types';

import { connect } from 'react-redux'
import * as actions from '../../actions/FAQActions';


class FAQ extends Component {

    render() {
        return (
            <div>
                <p>Here some Frequently Asked Questions will be displayed.</p>
                {console.log('FAQ')}
                { this.props.children }
                <button type="button" onClick={this.postLoginData}>
                    post
                </button>
                {/*<button type="button" onClick={this.onClick}>book</button>*/}
            </div>
        )
    }
}

FAQ.propTypes = {};

const mapStateToProps = state => {
    return {
        data: state.FAQReducer.fetchedFAQData
    }
};

const mapDispatchToProps = (dispatch) => ({
    actionOnLoad: () => dispatch(actions.getFAQ.request())
});

export default connect(mapStateToProps, mapDispatchToProps)(FAQ);```

**Comment by Andarist** [comment]
Could u put ur code on smth like codesandbox.io ? Then I would be able to check ur issue quickly once I get home

**Comment by Andarist** [comment]
the codesandbox example is broken and **incomplete**, you do not create store anywhere, nor do u actually render ur FAQ component

**Comment by stackninigi** [comment]
Sorry, I have never before used it. Can I give you access to my bitbucket repo instead?

**Comment by stackninigi** [comment]
@Andarist, fixed it. It should be working now along with the store.

**Comment by Andarist** [comment]
Bitbucket repo is also great, I'm asking for codesandbox, because in most cases people can't share work-related repositories.

I would like to ask you for the future, to test examples you give others for testing - I had to put my time into making it work. From the very beginning there was no mentioned error. I had to tweak ur code to use correct imports and stuff and when I have 'fixed' those issues example is working as expected (at least I guess so). You can check this out here - https://codesandbox.io/s/02rnnwv1l

**Comment by stackninigi** [comment]
I am deeply sorry. Especially for lack of question; when writing it was obvious for me, but after re-reading, it's not. 

**What I would like to have:** I want to call action which will populate my store with some data. So, when calling `actions.getFAQ.request` I'd like to have saga call my API and using `axios` fetch the data and put it into Redux store. In FAQ.js (which is my component) I would like to have access to `fetchData` which is dispatched in `FAQContainer.js`. Also I'd like to have access to props which I mapped in `mapStateToProps` in `FAQContainer.js`

**What I have now:** basically I'm doing `mapStateToProps` and `mapDispatchToProps` and then using `connect` to connect my `FAQContainer.js` with `FAQ.js`. But when I try to access my props they appear to be undefined. Also, redux store is unchanged. 

**What I believe might be an issue:** saga? Not sure if `getData()` in `FAQSaga.js` is called. I tried console logging it and debugging but it seems that it's not called. If not that, maybe there is some kind of issue with reducer since the state is not changed. 

**Additional questions:** after my update, was the codesandbox still not working? I tested it and though that everything should be correct. But once again, sorry for the first time. I'll learn from my mistakes and apologize for your lost time. As for your changes; I believe they didn't really solve my issue. The props are still undefined. But maybe something in the logic itself is incorrect?

**Comment by Andarist** [comment]
Im just about to get sleep, gonna respond in full tomorrow.

As to the codesandbox tweaked by me - u need to click the button to trigger the action which will trigger ur getData saga

**Comment by stackninigi** [comment]
I tried clicking the button but I received `typeError: this.props.fetchData() is not a function`.

**Comment by Andarist** [comment]
Please check my sandbox again, I think I have forgotten to save every file in there (action is triggered with a button click as mentioned before)

**Comment by stackninigi** [comment]
Yes, it works now, thank you. But I'm trying to find the places where I did mistakes and I'm failing. 

I can see the change in `FAQ.js` => ```	postLoginData() {
		console.log(this.props)
		this.props.fetchData()
	}``` and ```				<button type="button" onClick={this.postLoginData.bind(this)}>
					post
				</button>```
Also there are some changes in `FAQsaga.js` ```yield put(actions.getFAQ.success(data))``` and ```yield put(actions.getFAQ.failure())```. Am I missing any other changes? I tried applying these to my code but it didn't help. Still looks as if `mapDispatchToProps` isn't working.

**Comment by Andarist** [comment]
Well, I haven't listed all the changes I've made - you should be able to compare codesandbox provided by you with mine, file by file. Honestly I haven't done much changes (logic-wise), just fixed some bad imports/usage.

Gonna close this issue as it seems to be resolved. Don't be afraid to post more comments with new findings, I'm always do my best and try to reply, even in the closed issues.
