### ISSUE TITLE
Monorepo - extract some modular packages

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#1213]
i.e. `buffers`, `channel`, `is` could be easily extracted and published for better modularity

**Comment by restrry** [comment]
extractable modules:
- `delay` (moved from utils) - depends on `CANCEL symbol from redux-saga `
- `channel` depends on `utils, symbols, scheduler, matchers`
- `is` depends on `TASK & MULTICAST symbols`
could be extracted
- `scheduler`
- `buffers` 
- `matcher`
some modules could depend on symbols. so either we create circular dependency between modules or we extract symbols in a separate package as well

**Comment by shinima** [comment]
Should we extract them into multiple modules like `@redux-saga/delay`, `@redux-saga/channel`, `@redux-saga/is`, or should we just extract them all into one extra module `@redux-saga/utils`?

If we extract them into multiple modules, then putting all symbols in `@redux-saga/symbols` seems good to me.

**Comment by jeffvandyke** [comment]
Was there discussion somewhere I can't find where this was decided to be a good idea? Seeing this issue, I get very nervous about having to add about 5 new dependencies just for a basic usage of redux-saga - JavaScript package dependency lists are quite long enough. Is this direction of extracting separate packages always a good idea? And also, are the effects separate enough from internal implementation where it makes sense to extract them?

**Comment by shinima** [comment]
@jeffvandyke I think this modular packages separation should be internal. Users only need to add redux-saga as the dependency.

By the way, I'm also curious about how we extract modular packages in the end, but at the moment we still have some space to improvement the modularity.

**Comment by shinima** [comment]
@restrry  I think we could make `effectTypes` public. Further more, I'd like to remove `asEffect` and expose the structure of effects(though [it breaks encapsulation](https://github.com/redux-saga/redux-saga/pull/1477#issuecomment-395701484)), which results in much simpler usages like [this](https://github.com/redux-saga/redux-saga-devtools/blob/ec5c9a834171a301e638ac229fd49db2292fc986/src/store/selectors.js#L13-L60). I will make a PR to see if it makes a good difference.

**Comment by Andarist** [comment]
> Should we extract them into multiple modules like @redux-saga/delay, @redux-saga/channel, @redux-saga/is, or should we just extract them all into one extra module @redux-saga/utils?

Former - more packages -> better modularization

> If we extract them into multiple modules, then putting all symbols in @redux-saga/symbols seems good to me.

👍 

> @jeffvandyke I think this modular packages separation should be internal. Users only need to add redux-saga as the dependency.

This.

> also @shinima should we make effectTypes public? to simplify such cases

Might be a good idea too, not necessarily the priority though.

> Further more, I'd like to remove asEffect and expose the structure of effects(though it breaks encapsulation), which results in much simpler usages like this. I will make a PR to see if it makes a good difference.

Good idea about the trial PR 👍 

Back to the topic though - I'm going to extract those packages soon (hopefully) & also tweak the core's build script to be more optimized.

**Comment by restrry** [comment]
merged in https://github.com/redux-saga/redux-saga/pull/1557

**Comment by Andarist** [comment]
Some more packages can be extracted, but it's not blocking the v1 release in any way.
