### ISSUE TITLE
Run sagas with only unique payload

### ISSUE THREAD

**Issue by look-at-this** [redux-saga/redux-saga#1214]
Hey!

I'd like to run saga only if there were no previously executed sagas with the same payload.

What if I make a PR with new effect called `takeUniq`? 
In my case I use a function factory to wrap my sagas, for instance:

```
function uniqPayload(saga) {
    let lastPayload;

    return function* (...args) {
        const { payload } = args[args.length - 1];
        if (payload !== undefined && deepEqual(payload, lastPayload)) {
            // SKIP
            return undefined;
        } else {
            lastPayload = payload;
            yield* saga(...args);
        }
    };
}

...

function* rootSaga() {
        yield all([
            takeEvery('SOME_ACTION', uniqPayload(someSaga), someArg)
        ]);
};
```

**Comment by Andarist** [comment]
The proposed name is quite misleading, because you only compare last payload with the current and by looking at the name itself I thought you want to compare with every past payload.

I dont quite think saga wrapper is needed here, you could simply create a memoized pattern like this:
```js
const skipConsecutiveEqualPayloads = desiredType => {
    let lastPayload
    
    return ({ type, payload }) => {
        if (type !== desiredType) {
            return false
        }

        if (deepEqual(payload, lastPayload)) {
            return false
        }

        lastPayload = payload
        return true
    }
}

function* rootSaga() {
    yield all([
        takeEvery(skipConsecutiveEqualPayloads('SOME_ACTION'), someSaga, someArg)
    ]);
};
```

**Comment by Andarist** [comment]
At the moment I consider such effect to be too specific, I'm not opposed to introducing new helpers, but I feel there are just many more common patterns that should make their way to the core lib before we start adding things like this.

It's the beauty of redux-saga that such helper is really easy to be implemented in the user land and I do not see (at the moment) great value of adding it into the library itself.

**Comment by jacobbuck** [comment]
Shameless plug: I've just published a module which gives you saga helpers for spawning unique sagas. Check it out: https://github.com/jacobbuck/redux-saga-uniq
