### ISSUE TITLE
Effect for getters/setters

### ISSUE THREAD

**Issue by streamich** [redux-saga/redux-saga#1215]
Is there a way to "execute" getters/setters in sagas? Let's say I have a getter `user.name`:

```js
class User {
  get name () {
    // ...
  }
}
```

Then in saga I would do something like this:

```js
yield get(user, 'name');
```

**Comment by Andarist** [comment]
```js
const get = (prop, obj) => call(() => obj[prop]) 
yield get('name', user)
```

**Comment by streamich** [comment]
There is a problem with this approach. Every time it creates a new anonymous function.

So for example when you test your sagas the function in your saga and the one in test are different.

This does not allow to use Jest's `.toEqual` or `.toMatchObject`.

**Comment by Andarist** [comment]
```js
export const get = (prop, obj) => obj[prop]
yield call(get, 'name', user)
```

**Comment by streamich** [comment]
Thanks for the fast response, BTW.
