### ISSUE TITLE
How the saga knows which actions it should be fired on?

### ISSUE THREAD

**Issue by mehrdaad** [redux-saga/redux-saga#1216]
As I have concluded each saga is fired on specific action type.  
So as README suggests the worker Saga: will be fired on ``USER_FETCH_REQUESTED `` actions.  
My question is: how does a saga know on which action type it should be fired?

**Comment by Andarist** [comment]
You pass the action type as argument to the `take` effect creator. `redux-saga`'s runtime is hooked into redux with a middleware and it simply checks action object - when it sees the action of type you have previously `take`n it resumes your saga with the action object

**Comment by Andarist** [comment]
The questions seems to be answered, so I'm closing this.

**Comment by mehrdaad** [comment]
@Andarist thanks for the answer. I've another question does the ``take`` effect only listens for that action only once?  Also Do ``takeLatest`` and ``takeEvery`` effects take all the actions?  
Another question is what is the difference between these 2 code? I see both of them do one thing:  

```
function*(){
  while(true){
     take(action);
     doSomething();
  }
}
```
```
function*(){
  takeEvery(action); //or takeLatest(action)
  doSomething();
}
```

**Comment by Andarist** [comment]
You have right intuition - `take` is setting up a "once" listener.

`takeLatest` and `takeEvery` are just helpers which set up regular `take` under the hood, but when it gets resolved they create a new one instantly. So they act as persistent listeners.

About the snippets - dont forget to put `yield` before effects.

Your first snippet is kinda how `takeEvery` could look like:
```js
function* takeEvery(pattern, saga, ...args) {
  while(true){
     const action = yield take(pattern);
     yield fork(saga, ...args, action)
  }
}
```

The second snippet creates a persistent listener (with `takeEvery`), `doSomething` once and exits - listener being still active ofc.

**Comment by mehrdaad** [comment]
> About the snippets - dont forget to put yield before effects.

yep forget them, sorry :))  

> The second snippet creates a persistent listener (with ```takeEvery``), doSomething once and exits - listener being still active ofc.  
Sorry but I'm confused. Isn't the first snippet persistent? Would you describe what are the exact difference between using a ``while`` in conjunction with ``take`` VS using ``takeEvery``?  
(I've added the forgotten ``yield``s)

**Comment by Andarist** [comment]
> Sorry but I'm confused. Isn't the first snippet persistent? Would you describe what are the exact difference between using a while in conjunction with take VS using takeEvery?
(I've added the forgotten yields)

I didn't mean that second snippet is creating a persistent listener in opposed to the first one. Ive only meant that second one is creating a persistent listener and so does the first snippet.

The difference is that first one will `doSomething` each time it gets notified about `action`, but second one when we write it properly:
```js
function*(){
  yield takeEvery(action, someSaga); //or takeLatest(action, someSaga)
  doSomething();
}
```
will `doSomething` only once after it sets up the `takeEvery` persistent listener AND will `fork` `someSaga` each time it gets notified about the action.

**Comment by mehrdaad** [comment]
Oh, I see now. BTW I really appreciate your time and effort for maintaining this awesome project. thank you
