### ISSUE TITLE
Iterator type is not declared but used in effects.d.ts

### ISSUE THREAD

**Issue by klis87** [redux-saga/redux-saga#1217]
The problematic line is [here](https://github.com/redux-saga/redux-saga/blob/master/effects.d.ts#L432).

**Comment by Andarist** [comment]
cc @aikoven

**Comment by klis87** [comment]
I think not because when I imported your types in my index.d.ts file, typescript complained about it

**Comment by Andarist** [comment]
cc @aikoven

**Comment by aikoven** [comment]
It indeed *is* a built-in type, but it's not included in every library TypeScript provides.
See `"lib"` option in `tsconfig.json`: https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by Andarist** [comment]
Closing as it seems not related to the redux-saga itself, many others use it with TS and that's the first issue about this.

Feel free to comment further if you still have the issue, we'll try to figure out it with you.

**Comment by klis87** [comment]
Thank you, I will check out lib option. Sry for the noise, I just don't use typescript on the daily basis.
