### ISSUE TITLE
Why there is a initial buffer limit of 10 for number of sagas?

### ISSUE THREAD

**Issue by shameemz** [redux-saga/redux-saga#1221]
Any performance issues if I increased the number to 70?
example code:
import { channel, buffers } from "redux-saga";
.....
const intialBuffers = buffers.expanding(70);

**Comment by Andarist** [comment]
There shouldn't be any perf issue, its only matter of allocating the memory. `buffers.expanding` is gonna reallocate new, bigger array under the hood in case of the overflow - so I think you shouldn't be concerned too much about this anyway.

Side note - I'm preparing v1 of redux-saga and it will default channel's buffers to `buffers.expanding(10)` - when at the moment it is `buffers.fixed(10)`.

As the original question got answered Im closing this issue. If you still have any more questions, you can respond here or create a new issue.
