### ISSUE TITLE
Typescript join(...tasks)

### ISSUE THREAD

**Issue by Zaitsev** [redux-saga/redux-saga#1227]
missing  declaration in  redux-saga/effects.d.ts for join(...tasks) call

```typescript
export function join(...tasks: Task[]):  JoinEffect[];
```
IMHO should be like cancel() typings

**Comment by Andarist** [comment]
Would you like to make a PR for this?

**Comment by Zaitsev** [comment]
Pls, [review this](https://github.com/redux-saga/redux-saga/pull/1248)

**Comment by restrry** [comment]
should we solved in the next TS release https://github.com/Microsoft/TypeScript/wiki/Roadmap#30-july-2018
PR https://github.com/Microsoft/TypeScript/pull/24897

**Comment by restrry** [comment]
`join(...task)` and `cancel(...task)` were deprecated in https://github.com/redux-saga/redux-saga/pull/1527/files
