### ISSUE TITLE
File transfer to server in redux-saga

### ISSUE THREAD

**Issue by Lokesh235** [redux-saga/redux-saga#1232]
I am using redux-saga in my react web app. On UI side I am taking email and a file input and want to send the data to my django server. The email value is coming fine on server side but i'm not able to send file. Can anyone please help, how can I transfer the file selected on UI?
Thanks

**Comment by Andarist** [comment]
This is excellent blog post about file uploading with redux-saga https://decembersoft.com/posts/file-upload-progress-with-redux-saga/

**Comment by Andarist** [comment]
The issue seems to be resolved, therefore I'm asking it.
