### ISSUE TITLE
Call without waiting on Promise

### ISSUE THREAD

**Issue by russiancow** [redux-saga/redux-saga#1233]
**Question:** Is there a possible way to use `yield call` on a function that returns a Promise without actually blocking on that promise's resolution? 

**Background:** I'm using [superagent](http://visionmedia.github.io/superagent/) to handle HTTP requests, which returns a "Promise-like" object that also has other properties. One of those properties is a method called `abort()` that does what its name implies. What I'm trying to do is to allow the request to be canceled if the saga gets interrupted, like this:

    // makeApiRequest returns a superagent (Promise-like) request object
    const request = yield call(makeApiRequest, ...args)
    request[CANCEL] = () => request.abort()

But in that example, `call` blocks until the request is finished, and so `request` is actually the response object, which isn't useful. This is what I have been doing as a workaround:

    const request = makeApiRequest(...args) // `request` is a Promise
    request[CANCEL] = () => request.abort()
    const response = yield request // Actually block on the request

but that means I have to mock `makeApiRequest` if I want to test it, which negates one of the biggest benefits of using redux-saga in the first place. 

Is there a better way to do this that doesn't involve calling the API function directly? Thanks!

**Comment by Andarist** [comment]
You can wrap ur superagent request function to create a custom one like this
```js
const makeRequest = (...args) => {
  const request = makeApiRequest(...args)
  request[CANCEL] = () => request.abort()
  return request
}
```

and call that wrapper instead of the original function
```js
const result = yield call(makeRequest, ...args)
```

**Comment by russiancow** [comment]
Aha! I hadn't thought of doing it that way, but that works. Looks like there is no solution for the general case, though? Not a huge deal, as you could create a generic wrapper function similar to this if you had to.

**Comment by Andarist** [comment]
Not sure what do u mean by a general case here, it is pretty general already. The `CANCEL` need to be attached by some kind of wrapper function/generator if you want to benefit from it. We cant recognize external APIs to automate proper cancellation.

**Comment by russiancow** [comment]
Sorry, I wasn't talking about cancellation specifically; I meant a general way to `call` a function that returns a Promise without also blocking on the Promise's resolution.

**Comment by russiancow** [comment]
To clarify even further, if you wanted an arbitrary way to manipulate a returned Promise before blocking on it, you could create a wrapper like this:

    const callWithUpdate = (updater, fn, ...args) => {
      const newFn = (...args) => updater(fn(...args))
      return call(newFn, ...args)
    }

and then use it in your saga like this:

    const update = request => {
      request[CANCEL] = () => request.abort()
      return request
    }
    yield callWithUpdate(update, makeApiRequest, ...args)

That example also may not be the best, because you can't properly test the first argument of `call`. You could make it its own generator and `yield*` it, but you get the idea. Either way, there is no built-in way to achieve the above without creating a wrapper, is that correct? I wonder if it would make sense to create a non-blocking version of `call`, something like `call.nonBlocking`, similar to how `put.resolve` is a different version of `put`? What do you think? I'm sure there are other use cases for manipulating or introspecting a Promise right after it's returned without waiting for it to resolve.

**Comment by Andarist** [comment]
Hm, creating wrappers like this is imho quite fine. If you want to wrap arbitrary promises with arbitrary updaters I guess this is a way to go. If you are willing to ditch any of those 2 requirements, the code would look cleaner though.

As to adding a new effect for non blocking call - Im a little bit in the fence. Doesn't seem that much useful and it is quite easy to achieve this in user land. OTOH adding [custom effects](https://github.com/redux-saga/redux-saga/issues/1238) is something I would be interested in - don't know if Im gonna implement this (ain't sure about API etc), but I will look into it before releasing v1.

**Comment by russiancow** [comment]
Yeah, my own use case is solved by making it cancellable within the wrapper, so I'm not sure if there is a strong use case for having a generic way to call without blocking—I just thought I would bring it up. :) Having said that, I would be in favor of custom effects because I think it would allow for more elegant solutions to things like this, even if it doesn't make it into v1.

I'll close this comment since you answered my original question. :) I will comment on the issue you linked with my thoughts on a custom effects API.
