### ISSUE TITLE
takeLatest parameter error should be more specific

### ISSUE THREAD

**Issue by et** [redux-saga/redux-saga#1241]
When using `takeLatest` without providing a second saga parameter, the error message received isn't very clear.

Example:
```js
yield takeLatest(REQUEST_SIGNOUT);
```

```js
utils.js:258 uncaught at signInPageDataFlow at signInPageDataFlow 
 at signOutFlow 
 at takeLatest 
 TypeError: Cannot read property 'name' of undefined
    at takeLatest (webpack:///./node_modules/redux-saga/es/internal/sagaHelpers/takeLatest.js?:42:125)
```

Is it possible to have this provide an error message such as `takeLatest requires a saga parameter`?

**Comment by Andarist** [comment]
It is possible to add this type of validation in the development environment. Gonna add this in upcoming v1 release
