### ISSUE TITLE
React Native - geolocation and saga

### ISSUE THREAD

**Issue by sr3d** [redux-saga/redux-saga#1243]
I'd like to know how to properly structure the sagas to handle this situation in my React Native app:  I'd need to get the current position of the device first before making the call to the API to grab the local data.  This needs to happen on the start of the app.  

I'm using redux-saga-location for the getCurrentPosition method.

```js
import { watchLocationChannel, getCurrentPosition, watchCurrentPosition} from 'redux-saga-location';

const fetchListings = function* (action) {
    const position = yield call(getCurrentPosition);
    console.log("Saga: position", position);  // null here

    let url = `${BASE_API}/stores/nearby.json`

    const params = { 
      latitude:  position.coords.latitude,
      longitude: position.coords.longitude,
    };

    const response = yield call( Fetch, 'get', params );
    const result   = yield response.json();
    yield put({ type: ListingActions.FETCH_LISTINGS_RESULT, result });    
}
```

Any pointer would be greatly appreciated!

**Comment by Andarist** [comment]
By looking at [`redux-saga-location` source code `getCurrentLocation`](https://github.com/itinance/redux-saga-location/blob/5388172a4b4115f5b3424470b89a188d43e5aab3/saga/location.js#L19) doesn't return the location, but only `put` that data on the channel.

This should work:
```js
import { locationChannel, getCurrentPosition } from 'redux-saga-location';
// ...
yield call(getCurrentPosition);
const { position } = yield take(locationChannel);
```
