### ISSUE TITLE
add an attach api to tie a task's lifetime to a parent saga

### ISSUE THREAD

**Issue by mmerickel** [redux-saga/redux-saga#1244]
There have been a lot of discussions in the tracker about trying to define custom effects and most of them have been resolved by defining a function that returns a `call`. Unfortunately this cannot be done for a custom effect that wants to wrap a `fork` effect and return the task. This is because the `fork` is actually implicitly joined to the iterator and thus the `call` will wait for the fork to complete before returning.

```js
function* handleFork(worker, args) {
  const channel = yield call(channel);
  const task = yield fork(function* () {
    yield setContext({channel});
    yield call(worker, ...args);
  });
  return [task, channel];
}

function myfork(worker, ...args) {
  return call(handleFork, worker, args);
}

function *saga() {
  const [task, channel] = yield myfork(foo); // does not return
}
```

The only way around this right now is to `spawn` instead of `fork` but this means you are responsible for handling the lifetime of the task instead of having it magically tied to the lifetime of a "parent" task. In this case we would want the lifetime to be tied to `saga` and not `handleFork` and there is currently no way to do that. One option might be to define an `attach` effect which unlike `join` is non-blocking and doesn't wait for the task to complete. The only remaining issue is that `handleFork` doesn't have access to its caller to have some handle to attach. For example `const task = spawn(...); const parentTaskId = yield getParentTaskId(); yield attach(task, parentTaskId); return task;` which has created a detached task and then later attached it to a task that it was not created from.

I'm interested in other options but this is currently a limitation in defining custom effects. Note that this is an issue even if you do not use the `call` and instead just `yield handleFork` because a new task is created for any yielded generator and thus any forks are bound to that new task.

**Comment by Andarist** [comment]
Gonna think both about allowing:
- custom effects which could hook directly to the saga runtime - allowing u to create whatever you want, this would have to expose low level state/structures of the [proc.js](https://github.com/redux-saga/redux-saga/blob/1847d7d40b020784525304061f55d92b466135b1/src/internal/proc.js)
- some kind of "non-blocking" `call` which would allow to return `task` descriptor to the caller, I've had similar issue with this in the past and couldn't find a proper way for this in user land

**Comment by Andarist** [comment]
I think some other request from the past seems to be same-ish - https://github.com/redux-saga/redux-saga/issues/559#issuecomment-272587069
