### ISSUE TITLE
Testing nested generator calls

### ISSUE THREAD

**Issue by marutha** [redux-saga/redux-saga#1245]
I have a generator saga that calls set of generators to fetch some initial information after user logs in. The requestResponse* is one which make request to uri provided and gets back the result of the request.

```javascript
export function* requestResponse({ endpoint, payload }) {
  const ref = request();
  const req = prepareRequest({ endpoint, payload, ref });
  yield put(req);
  const response = yield take(ref);
  yield put({ type: BE_ALERT, payload: response.records });
  return response;
}
```

fetchInitialnfo calls this above like below
```javascript
export function* fetchInitialInfo() {
  yield requestResponse(getProfiles());
  yield requestResponse(getSubscribers());
  yield requestResponse(getProjects());
}
```

Now I want to test my fetchInitialInfo like below.
```javascript
it('Expect to have unit tests specified', () => {
    const gen = fetchInitialInfo();
    const takeLatestDescriptor = gen.next(mockTask);
    expect(takeLatestDescriptor.value).toEqual(requestResponse(getProfiles()));
  });
```

On test execution I get something like below
```
Summary of all failing tests
 FAIL  app/containers/App/tests/sagas.test.js
  ● sagas › Expect to have unit tests specified

    expect(received).toEqual(expected)

    Expected value to equal:
      {"_invoke": [Function invoke]}
    Received:
      {"_invoke": [Function invoke]}

    Difference:

    Compared values have no visual difference.
```

I suspect I am doing something wrong here, sorry for the noise, appreciate any guidance as I could not find anything similar on testing.

**Comment by Andarist** [comment]
Value passed to the first `.next()` call (your `mockTask`) is always missed at the moment (that's how javascript works - there is open proposal to the language to add a posibility to access this value with [`function.sent`](https://github.com/allenwb/ESideas/blob/master/Generator%20metaproperty.md))

But even if it gets lost, your code looks quite fine. Are you sure it is all of your code and that what u have pasted in here is what you are using? Jest's report suggests that you compare iterators/generators but in your tests you should have effect object here.

**Comment by marutha** [comment]
Since you said first `.next()` value is ignore I did remove and gave a try.. below the test, and the above implementation remain same. and that is the complete code for the function , `prepareRequest` and `request()` all are functions

```javascript
describe('sagas', () => {
  it('Expect to have unit tests specified', () => {
    // const mockTask = createMockTask();
    const gen = fetchInitialInfo();
    const takeLatestDescriptor = gen.next();
    console.log('takeLatestDescriptor', takeLatestDescriptor);
    console.log('request des', requestResponse(getProfiles()));
    expect(takeLatestDescriptor.value).toEqual(requestResponse(getProfiles()));
    // expect(true).toEqual(false);
  });
});
```


```
 FAIL  app/containers/App/tests/sagas.test.js
  ● Console

    console.warn node_modules/react-native-uuid/uuid.js:48
      [SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()
    console.log app/containers/App/tests/sagas.test.js:35
      takeLatestDescriptor { value: GeneratorFunctionPrototype { _invoke: [Function: invoke] },
        done: false }
    console.log app/containers/App/tests/sagas.test.js:36
      request des GeneratorFunctionPrototype { _invoke: [Function: invoke] }

  ● sagas › Expect to have unit tests specified

    expect(received).toEqual(expected)

    Expected value to equal:
      {"_invoke": [Function invoke]}
    Received:
      {"_invoke": [Function invoke]}

    Difference:

    Compared values have no visual difference.

      at Object.<anonymous> (app/containers/App/tests/sagas.test.js:37:40)
```
let me know if you are looking for any specific info, also is there some open source that implements testing something like this?

**Comment by Andarist** [comment]
What version of `redux-saga` do you use and how do you import `takeLatest`? With newer version of the library it should be done like this:
```js
import { takeLatest } from 'redux-saga/effects'
```

**Comment by marutha** [comment]
`"redux-saga": "0.14.0",` Could this be an issue, I shall try this and let you know my result on this.

Basically there is no import to takeLatest as I am not using it in test case, if you are seeing about `takeLatestDescriptor` this is just a constant that store the descriptor of `gen.next()`, but I agree the naming convention is not followed here which I should correct.

**Comment by Andarist** [comment]
Oh damn, I haven't noticed before the really important thing.

If you want to test against effects equality you cannot `yield requestResponse(getProfiles())` directly because each call to `requestResponse` will end up giving u new instance which has new identity and you wont be able to compare it in tests.

You should change your code to:
```js
export function* fetchInitialInfo() {
  yield call(requestResponse, getProfiles());
  yield call(requestResponse, getSubscribers());
  yield call(requestResponse, getProjects());
}
```

```js
it('Expect to have unit tests specified', () => {
    const gen = fetchInitialInfo();
    const takeLatestDescriptor = gen.next();
    expect(takeLatestDescriptor.value).toEqual(call(requestResponse, getProfiles()));
  });
```

**Comment by lucaspiller** [comment]
I came across this as I have a similar issue. First a bit of background: in our application we have chosen to put all the logic related to building api requests, making the request and parsing responses in sagas. So we dispatch a **LOAD_REQUESTED** action, the saga does all the work, then it dispatches a **LOAD_SUCCESS** action, with a payload that can be simply added to the Redux store without any further munging by the reducer. The works well to keep all the logic in one place, and so far our sagas have been quite testable.

However, in one case we have a saga that works as follows:

```js

function* load() {
  const data = yield call(loadSharedData)

  if (data.condition) {
    yield call(pathA)
  } else {
    yield call(pathB)
  }
}

function* pathA() {
  yield call(loadSomething)
  // munge data
  // maybe load something else
}

function* pathB() {
  yield call(loadSomethingElse)
  // munge data
  // maybe load something else
}
```

`pathA` and `pathB` have been moved to separate functions (they are around 50 lines each) to keep the main function of the saga small, but as they call `yield` they also need to be generator functions.

We can test the `load`, `pathA` and `pathB` functions individually as you describe, but is there a way to make more of an integration test where we can test everything together?

**Comment by Andarist** [comment]
There are various attempts over the issues to make more integration-like tests and I think it is a good direction, because it hides the internal saga implementation.

Personally I would advise you to use [v1.0.0-beta.0](https://github.com/redux-saga/redux-saga/releases/tag/v1.0.0-beta.0) (there was really no big changes!), leverage added `effectMiddlewares` feature to resolve your API-related effects (what you already do in tests) and change the testing approach to more integration-like one. It would require creating **real** redux's store, connecting it to the saga, dispatching some real actions and finally inspecting the state's shape in your assertions.

**Comment by lucaspiller** [comment]
Sorry maybe I wasn't very clear, but what I was looking for is `yield*`. Using that I can write sagas and tests like this:

```js
function* load() {
  const data = yield call(loadSharedData)
  yield* subPath(data)
}

function* subPath() {
  yield call(loadMoreData)
}

it('tests load and subPath', () => {
  const gen = load()
  expect(gen.next()).toEqual(call(loadSharedData)
  expect(gen.next(dataRes)).toEqual(call(loadMoreData)
})
```

Thanks!
