### ISSUE TITLE
Add a `requestIdleCallback` type effect

### ISSUE THREAD

**Issue by ntucker** [redux-saga/redux-saga#1247]
It'd be nice to say yield to another saga in an idle callback so work could be done in the background.

**Comment by Andarist** [comment]
Wouldnt creating this in ur code:
```js
const tick = () => new Promise(resolve => requestIdleCallback(resolve))
```
and using it like this:
```js
yield call(tick)
```
solve it for you?

**Comment by ntucker** [comment]
I don't believe this would make the code following it run in the background, which is of course the purpose of this. The only thing you could do here is run code before the resolve inside the callback that is sent to rIC. However, that code would have no way of interfacing with redux-saga - which is my desire.

**Comment by Andarist** [comment]
Im not sure exactly what is your desire here, could u give a usage example + describe what is happening sync and what after a `requestIdleCallback` is resolved?

**Comment by ntucker** [comment]
I re-read the docs on requestIdleCallback and I realize now it's simply a timing API - it does not do anything like webworkers and run things in the background. Because of this your example should work fine for my purposes. Thanks!
