### ISSUE TITLE
Help: how to cancel a yeld all ?

### ISSUE THREAD

**Issue by realtebo** [redux-saga/redux-saga#1249]
Having 

```
const [users, repos]  = yield all([
  call(fetch, '/users'),
  call(fetch, '/repos')
])

```
from offcial doc page: https://redux-saga.js.org/docs/advanced/RunningTasksInParallel.html

**How can I cancel the parallel execution ?**

**Comment by Andarist** [comment]
It depends where and how do you use `all`.

I.e.
```js
const { parallel, cancelled } = yield race({
	parallel: all([
		call(fetch, '/users'),
		call(fetch, '/repos')
	]),
	cancelled: take('CANCEL_TRIGGER'),
})
```

or 
```js
function* parallelTask() {
	return yield all([
		call(fetch, '/users'),
		call(fetch, '/repos')
	])
}


const task = yield fork(parallelTask)
// ...
yield cancel(task)
```

or 
```js
const tasks = yield all([
	fork(fetch, '/users'),
	fork(fetch, '/repos')
])

yield cancel(...tasks)
```

and possibly some more others way of structuring ur sagas are possible. You need to understand that cancellation happens from the outside of the effect and you need to have access to some task descriptor to call cancel on it + knowing the difference between blocking (`call` here) and nonblocking (`fork` here) is useful.

**Comment by realtebo** [comment]
@Andarist 

I changed my code into the 3rd version:

```
const tasks = yield all([
            yield fork(delay3),
            yield fork(delay5)
        ]);
```

Now I can succesfully cancel using the spread operator.

    yield cancel(...tasks);

thanks !

Also, thanks for the note: 

>You need to understand that cancellation happens from the outside of the effect and you need to have access to some task descriptor to call cancel on it + knowing the difference between blocking (call here) and nonblocking (fork here) is useful.
