### ISSUE TITLE
Link to https://redux-saga.js.org/ gives 404

### ISSUE THREAD

**Issue by sergous** [redux-saga/redux-saga#1251]

**Comment by dviry** [comment]
same here, seems docs' site is down...

**Comment by blakew** [comment]
For now this is the last snapshot from archive.org:

https://web.archive.org/web/20171024040256/https://redux-saga.js.org/

**Comment by Andarist** [comment]
Sorry for that. I was cleaning up some stale branches and I've deleted by accident `gh-pages` which contained the docs. The issue is resolved now.
