### ISSUE TITLE
"application/json POST " send OPTION on yield call(api) instead of POST

### ISSUE THREAD

**Issue by Bonobomagno** [redux-saga/redux-saga#1253]
I searched, but still didn't found a solution.
I'm new on react/redux world, so maybe the problem is elsewhere.

But, i'm using fetch to post an auth request in json

```
export function* loginRequest(action) {
  console.log('loginRequest saga running')
  yield takeLatest(oauthActions.AUTH_LOGIN, function* (action) {
    console.log(action)
      const response = yield call(apiRequest,api.AUTH_LOGIN, action.user)
      try {
      console.log(response)
      yield put({ type: oauthActions.LOGIN_SUCCESS, response: response.data})
      } catch(error) {
        console.log('XXXXXXERROREXXXXX')
      yield put({ type: oauthActions.LOGIN_FAILURE, error: error.message })
      }
  })
}
```

```const myInit = (user) =>{
  let bodydata = JSON.stringify({
          email: user.username,
          password: user.password
      });
  return({
headers: {
  'Accept': 'application/json',
  'Content-Type': 'application/json'
},
method: 'POST',
mode: 'cors',
body: bodydata   })}
const apiRequest =  (api,user) =>
{fetch(api,myInit(user))
.then(res => res.json())
  .then(res => res)
  .catch(error => error);
}```

I  have a jwt auth on backend (php) that is working fine (tested on postman)
I also know that the default handle is sending option before of post for checking the cors on the server (cors are enabled), but how to handle the situation? I just want the post response. Not the option one..

**Comment by Andarist** [comment]
You won't get `OPTIONS` response in your code, unless it is an error I guess (not sure 100% though about the latter). Its the browser which makes the `OPTIONS` request for you and once it gets its response and if it's a correct one it just sends your original request - `POST` and notify you about it when it gets its response.

**Comment by Bonobomagno** [comment]
i got the problem. 
the server need to handle OPTION request giving 200. Cors is not enoght
That was my error, but i think that adding info about it would be a good tip.

I didnt have this problem with angularJs, for example.
Now i'm figuring how to handle this.
adding 
`    RewriteCond %{REQUEST_METHOD} OPTIONS
    RewriteRule ^(.*)$ $1 [R=200,L]`

give me error on apache..

**Comment by Bonobomagno** [comment]
ok.
I found a good answer on the fetch repo
`SetEnvIfNoCase Access-Control-Request-Method "(GET|POST|PUT|DELETE|OPTIONS)" IsPreflight=1
SetEnvIfNoCase Origin ".*" AccessControlAllowOrigin=$0
SetEnvIfNoCase Origin "https://(url1.com|url2.com)$" AccessControlAllowOrigin=$0

Header always set Access-Control-Allow-Origin %{AccessControlAllowOrigin}e env=AccessControlAllowOrigin
Header always set Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" env=IsPreflight
Header always set Access-Control-Allow-Headers "Content-Type, Authorization, Accept, Accept-Language" env=IsPreflight
Header always set Access-Control-Max-Age "7200" env=IsPreflight
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteCond %{ENV:IsPreflight} 1
RewriteRule ^(.*)$ $1 [R=204,L]`
204 is the right response.
Thanks. you can close this :)

**Comment by Andarist** [comment]
> I didnt have this problem with angularJs, for example.

You had to have some different setup. The issue is totally framework independent - it's just how CORS situations need to be handled because of the **browser** specifications.

**Comment by Bonobomagno** [comment]
yep, was a fetch problem. i didnt use fetch before :)
