### ISSUE TITLE
How to test action channel with expanding buffer destructuring

### ISSUE THREAD

**Issue by zacharybergmann** [redux-saga/redux-saga#1257]
I am having issues getting the below saga to pass tests. Am I missing a particular step? I followed issue 727 & 1084 but it seems that 1084 is possibly not working correctly? Appreciate any help!

Saga:

    export function* getElasticStatsFlow() {
      const parseChan = yield actionChannel(PARSE_ES_STATS, yield buffers.expanding(10));

      yield fork(getAllDocumentStats); // get stats for all documents
      yield fork(getMetaDataStats); // get metadata stats

      while (true) {
        const { payload } = yield take(parseChan);
        yield call(handleParseAndPut, payload);
        yield put(finishESStats());
      }
    }

Test:
 
     it('should successfully run and loop', () => {
       const elasticStatsFlowSaga = getElasticStatsFlow();
       const payload = {};
       const chan = actionChannel(PARSE_ES_STATS, buffers.expanding(10));
       const mockChannel = channel();

       expect(elasticStatsFlowSaga.next().value)
         .toEqual(chan);

       expect(elasticStatsFlowSaga.next(mockChannel).value).toEqual(fork(getAllDocumentStats));

       expect(elasticStatsFlowSaga.next().value).toEqual(fork(getMetaDataStats));
 
       expect(elasticStatsFlowSaga.next().value).toEqual(take(mockChannel));

       expect(elasticStatsFlowSaga.next(payload).value).toEqual(call(handleParseAndPut, payload));

       expect(elasticStatsFlowSaga.next().value).toEqual(put(finishESStats()));
     });

**Comment by zacharybergmann** [comment]
This is the output from the test as run now.   

   expect(received).toEqual(expected)

    Expected value to equal:
      {"@@redux-saga/IO": true, "ACTION_CHANNEL": {"buffer": {"flush": [Function flush], "isEmpty": [Function isEmpty], "put": [Function put], "take": [Function take]}, "pattern": "midgard/AdminPage/PARSE_ES_STATS"}}
    Received:
      {"flush": [Function flush], "isEmpty": [Function isEmpty], "put": [Function put], "take": [Function take]}

**Comment by Andarist** [comment]
Something like this:
```js
import { is } from 'redux-saga/utils'

 it('should successfully run and loop', () => {
   const elasticStatsFlowSaga = getElasticStatsFlow();
   const payload = {};
   const mockBuffer = buffers.expanding(10)
   const chan = actionChannel(PARSE_ES_STATS, mockBuffer);
   const mockChannel = channel();

   expect(is.buffer(elasticStatsFlowSaga.next().value)).toBe(true);
   
   expect(elasticStatsFlowSaga.next(mockBuffer).value).toEqual(chan);
   expect(elasticStatsFlowSaga.next(mockChannel).value).toEqual(fork(getAllDocumentStats));

   expect(elasticStatsFlowSaga.next().value).toEqual(fork(getMetaDataStats));

   expect(elasticStatsFlowSaga.next().value).toEqual(take(mockChannel));

   expect(elasticStatsFlowSaga.next(payload).value).toEqual(call(handleParseAndPut, payload));

   expect(elasticStatsFlowSaga.next().value).toEqual(put(finishESStats()));
 });
```

**Comment by zacharybergmann** [comment]
Thanks, got it now! If anyone else comes across this topic, I did the above except:

    const payload = { payload: { thisThing: 'thatThing' } };

and 

    expect(elasticStatsFlowSaga.next(payload).value).toEqual(call(handleParseAndPut, payload.payload));

I thought the value passed on would have just been the payload already destructured but it was the whole object.
