### ISSUE TITLE
redux-saga a saga runs twice but called once

### ISSUE THREAD

**Issue by soma83** [redux-saga/redux-saga#1266]
I have a redux-saga which is called once, but it is executing twice.

This is the action that starts the saga: 

    export function createRequest (data) {
      return {
        type: CREATE_REQUEST,
        payload: {data}
      };
    }

and my sagas.js file looks this way:

    export function* create (x) {
      try {
        const response = yield call(request, URL_TO_API, Object.assign({}, buildBaseHeaders('en'), {
          method: 'post',
          body: JSON.stringify(x.payload.data)
        }));
        yield put(createSuccess(response));
      } catch (error) {
        yield put(createFailure(error));
      }
    }
    
    ... my other sagas
    
    export default function* defaultSaga () {
      yield takeLatest(CREATE_REQUEST, create);
      ... my other calls
    }

`request` handles the `checkStatus` and `parseJSON`. 

If I put a console log in the `createRequest` action it shows just a line in the browser's console, however if I console log the `create` saga it shows twice in the browser's console. 

This gives me back an error, because the first call to the saga successfully creates the element in the database, but the second call returns a

> duplicate key value violates unique constraint

as expected. Therefore my application shows both the insertion success message and the error message captured in the `catch` block saying it was impossible to add the element because it exists already.

`createSuccess` and `createFailure` are actions that only change values in the application state. Also, these actions constants are not related to any saga.

I've been googling and I've been researching how to solve this. The nearest post I found with a possible solution is here https://stackoverflow.com/questions/39565552/redux-saga-is-running-twice-for-a-single-action but the given response doesn't work for me, in fact webpack fails to compile it. The documentation I've found is quite vague around this topic.

So, what am I missing here? How can I deal with this?

**Comment by Andarist** [comment]
How do you load your `defaultSaga` saga? Is it injected somehow during runtime? In example during a route transition?

**Comment by soma83** [comment]
Mr. Andarist, 
I'm using React-Boilerplate and the way I'm injecting the `defaultSaga` is this:

```
const withConnect = connect(mapStateToProps, mapDispatchToProps);
const withReducer = injectReducer({key: 'xxxxxxx', reducer});
const withSaga = injectSaga({key: 'xxxxxxx', saga});

export default compose(withReducer, withSaga, withConnect) MyComponent);
```

**Comment by Andarist** [comment]
I bet that your exported component gets rendered twice and thus the `defaultSaga` gets injected twice and it's run also twice.

You should cancel the injected saga when the component gets unmounted (that's probably your intended use case)

**Comment by Andarist** [comment]
from what I see it should be handled for you already: [here](https://github.com/react-boilerplate/react-boilerplate/blob/e39f8bdca29a35edbd7480968c9fe0b2c9438860/app/utils/injectSaga.js#L35) + [here](https://github.com/react-boilerplate/react-boilerplate/blob/e39f8bdca29a35edbd7480968c9fe0b2c9438860/app/utils/sagaInjectors.js#L68)

Please add `componentWillMount` with a `console.log` to your `MyComponent` to see how many times it tries to get rendered.

**Comment by soma83** [comment]
`componentWillMount() {
  console.log('mounting');
}`

Shows only one `mounting` line... however I did this:
`export default function* defaultSaga () {
  yield takeLatest(CREATE_REQUEST, create);
  console.log('mounting saga');
}`

and it prints "mounting saga" two times. I'm going to see your links right now and then I'll be back.

**Comment by Andarist** [comment]
If you share a repository with the issue reproduced I could help you debug this, without that it's really hard to pinpoint the exact cause.

**Comment by soma83** [comment]
Mr. Andarist,
the codes you gave me are just exactly the same I have. The react `componentWillMount` tells me that the component is going to be mounted just once. The code I have for the sagas is that I gave you, so, I don't know what else could I share in order to give you a more clear idea on this. So, please, tell me what else I can tell you to get this working.

**Comment by soma83** [comment]
Thanks for your time.

**Comment by Andarist** [comment]
Did you solve your problem?

**Comment by soma83** [comment]
Problem solved

**Comment by aelor** [comment]
@soma83 How did you solve the issue ? what you have written seems pretty standard to me. Why and what was the hack required ? Thanks in advace

**Comment by vasantharajan** [comment]
use takeEvery Instead of using the takeLatest
