### ISSUE TITLE
React 16.x compatibility

### ISSUE THREAD

**Issue by jherencia** [redux-saga/redux-saga#1267]
I do not see in the documentation any mention to the dependencies of an specific version of react. But the package.json defines:  "react": "^15.0.0", is that right? Does redux-saga work with React 16.x.

Thank you!

**Comment by Andarist** [comment]
We have react only as dev dependency. `redux-saga` doesn't care about what framework do you use, it's completely agnostic of this. You can integrate it with whatever you want - react, angular, embed, vue, etc.

So to answer your question - it works with any React :)

**Comment by jherencia** [comment]
Thank you!

**Comment by jherencia** [comment]
And what about Redux, is it agnostic too?

I see the new branch of Redux 4.x has been released (https://github.com/reactjs/redux/releases/tag/v4.0.0-beta.1).

**Comment by Andarist** [comment]
Pretty much - yeah, it's just a little bit easier to integrate `redux-saga` with `redux` (it's the "default" integration), but you can integrate any data source with `redux-saga` thanks to `runSaga` API (where "default" integration of `sagaMiddleware` is just a thing wrapper around `runSaga`).

From what I see in the redux's changelog we won't have to adjust our setup in any way - they are not breaking any changes to the `applyMiddleware` stuff and things should just continue to work.

**Comment by jherencia** [comment]
Great! Thank you for the response!
