### ISSUE TITLE
Better errors

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#1269]
Incorporating similar system to this https://zeit.co/blog/err-sh would be super cool, React is doing also similar stuff for prod errors or something.

**Comment by wisn** [comment]
It sounds great. So, should we collecting a common error first?

**Comment by Andarist** [comment]
Could u elaborate? I'm not sure if I understand.

**Comment by wisn** [comment]
I mean common mistakes that user would creates. Like `Error! You're calling takeLatest but there is no Saga in parameter`.

**Comment by Andarist** [comment]
Yeah, most common mistakes should get listed higher on the error page. The main point of this issue is to create an error system which could create links (by ids or something) to error pages - instead of hardcoding the error in the source code. That way helpful error messages can evolve over time without need for publishing new version of the library and without people downloading it.

**Comment by wisn** [comment]
That `without need for publishing new version of the library and without people downloading it` was difficult.

**Comment by Andarist** [comment]
Closing this in favour of our descriptive errors enhanced with babel plugin (coming in stable v1 this month)
