### ISSUE TITLE
[Question] How to catch a fork Api.request error?

### ISSUE THREAD

**Issue by Jancat** [redux-saga/redux-saga#1271]
There has a Api custom middleware to return rejected promise if network error
```js
apiClient.interceptors.response.use(
    response => response,
    error => {
      const { response } = error
      if (!response) {
        return Promise.reject(error)
      }
    }
)
```

fork a logout request and continue clearing sth
```js
export function* logout() {
  while(true){
    yield take('LOGOUT')
    try {
      yield fork(Api.delete, `/tokens/${tokenId}?userId=${userId}`)
    } catch (error) {
      // there will not be catch if request fail
      yield call(Toast.show, error)
    }

   ... // clear sth
  }
}
```

How can I catch fork error? （I don't want to use blocking call method because a bit slowly)
Thanks.

**Comment by Andarist** [comment]
What you are asking for is actually **impossible**. Your `Api.delete` rejects asynchronously, that means if you want to use a non-blocking `fork` to execute it, the execution flow of saga will be already past the `try`/`catch` block when the rejection actually happens therefore it's impossible to catch it reliably in the `logout` saga.

> I don't want to use blocking call method because a bit slowly)

Could you explain your issue? Blocking calls are not any slower, it's only a matter of when the caller saga gets resumed.

I would advise to restructure your control flow somehow to achieve your goal, but to help any further I would actually need to know more business requirements for your logic.

**Comment by Jancat** [comment]
Oh thanks. So this is a wrong flow. I would have to use blocking calls.
> I don't want to use blocking call method because a bit slowly

I mean the delete request has a little delayed. And I don't want to block UI by navigating to login page instantly.

**Comment by huanghaiyang** [comment]
onError
