### ISSUE TITLE
[Question]Wait for the result of the action, then do another fetch operation

### ISSUE THREAD

**Issue by stefli** [redux-saga/redux-saga#1274]
There are two actions:
Action 1.  Retrieve the endpoint to get the result something like orderNo.
Action 2.  Wait for the orderNo, then do another fetch operation. If orderNo is present, then continue the process, otherwise just wait.

I have tried to use selector(yield select(selectors.orderNo)), but it can't get the result due to the Action 2 is executed before Action 1.

Is there any way to get the latest result, then continue the Action process?

Thanks in advance!

**Comment by Andarist** [comment]
It depends on how your sagas are structured. It should be possible to structure your sagas in a way that you ask for the `orderNo` only in the moments you know it's there. If not you could do something like:
```js
export function* waitForState(selector, ...args) {
	do {
		const state = yield select(selector, ...args)
		if (typeof state !== 'undefined') {
			return state
		}
		yield take('*')
	} while (true)
}

// in your saga
const orderNo = yield call(waitForState, selectors.orderNo)
```

**Comment by stefli** [comment]
Thanks, it works.
