### ISSUE TITLE
Getting results from child sagas

### ISSUE THREAD

**Issue by adampetrie** [redux-saga/redux-saga#1275]
I have 3 sagas - 1 that is used for workflow purposes and 2 that are used to make api calls.

The api call sagas both have a very similar format:

```
export function* fetchResourceA(action: FetchResourceA.Request) {
  try {
    const data: Resource.GET = yield call(
      Resource.GET,
      action.payload.resourceId
    );
    
    yield put(FetchResourceA.success(data));
  } catch (error) {
    yield put(
      FetchResourceA.failure("error")
    );
  }
}
```

And were designed to handle the entire async flow of the fetch including dispatching actions on success and error results.

I my workflow saga I would like to be able to make 1 request to each api saga and wait for for them to be successful or fail before completing the workflow. My workflow saga looks like this:

```
export function* loadWorkflowResources(action: LoadWorkflowResources.Request) {
  try {
    yield all([
      call(fetchResourceA, FetchResourceA.request(action.payload.resourceAId)),
      call(fetchResourceB, FetchResourceB.request(action.payload.resourceBId))
    ]);
    yield put(LoadWorkflowResources.success());
  } catch (error) {
    console.log("errror");
  }
}
```
The idea here was to have to api calls encapsulate the async request responses and allow various workflow sagas to request resources as needed. The workflow saga is intended to represent a loading state and so I do not want to render my UI until a `LoadSliceResources.success()` action is dispatched.

For the most part, this seems to work except in the case when fetching a resource from the workflow fails. The API saga dispatches the correct failure action but the workflow saga is none the wiser and proceeds as if the resource fetch was successful. I've tried getting the results from `yield all` but both values are undefined.

Im wondering if I can accomplish what I am after with this setup or perhaps I have more fundamentally misunderstood something. Any clarity that anyone can give is appreciated.

**Comment by Andarist** [comment]
For starters you can rethrow the error in `fetchResourceA`/`fetchResourceB` catch clauses. All the rest kinda depends on your requirements.

**Comment by adampetrie** [comment]
Perfect! I knew I was missing something. Thanks.
