### ISSUE TITLE
autoInc will be larger than Number.MAX_VALUE

### ISSUE THREAD

**Issue by wushuyi** [redux-saga/redux-saga#1281]
in src/internal/utils.js
```javascript 
export function autoInc(seed = 0) {
  return () => ++seed
}

export const uid = autoInc()
```
use in nextEffectId will be error in server side rendering

**Comment by Andarist** [comment]
Why is it going to be an error? It should just overflow the number or something. Anyway that's definitely something that needs to be tuned in the core somehow

**Comment by restrry** [comment]
is it a real problem? even if we assume that you generate 1000 effects/ms:
```js
const msPerYear = 31536000000
const effectsPerMs = 1000
const overflowIn = Number.MAX_SAFE_INTEGER / (msPerYear * effectsPerMs)
console.log(overflowIn) // 285.616 years
```
the number will overflow in 285 years.

plus such a simple approach helps to represent the sequence of effects in human-readable manner

**Comment by Andarist** [comment]
You are right, this is non issue.
