### ISSUE TITLE
Add Contributing Guideline

### ISSUE THREAD

**Issue by wisn** [redux-saga/redux-saga#1287]
That would be nice if we (newcomer) have a guideline how to contributing on the right way. Please add a `CONTRIBUTING.md` guideline.

**Comment by Andarist** [comment]
Sure thing, this would be nice. Do you have any particular contributing guidelines for other projects that you like? What are the most important things that such guideline should alway cover in your opinion?

**Comment by wisn** [comment]
The simplest one is something like [coala/coala](https://github.com/coala/coala/blob/master/CONTRIBUTING.rst). You may see [github/choosealicense.com](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md). The main content is should be the steps to starting contributing and some rules.

**Comment by wisn** [comment]
For addition, [infinitered/ignite](https://github.com/infinitered/ignite/blob/master/.github/CONTRIBUTING.md) contributing guideline was perfect I think.

**Comment by BrandonKlotz** [comment]
@wisn I am a said newcomer looking to help out and contribute somewhere. I just learned React Redux. Let me know if there is something that would be helpful.

**Comment by AbdulKabia** [comment]
Hey, would it be okay if I worked on this?

**Comment by Andarist** [comment]
@AbdulKabia go ahead, would love your contribution for this 👍
