### ISSUE TITLE
how back to orginal flow

### ISSUE THREAD

**Issue by soroushm** [redux-saga/redux-saga#1291]
i Need Some Help

in my application for some flow need login and verification i'm already usin redux - sagas but i dont know how exacly should resolve this situation

user coming to book flow and should be login if is not loged in api get 401 error in case i set a acion 'AUTH_FAILURE' then depend on have accesstoken or not set other flag "LOGIN" OR "REGISTER"
```js
export function* failure() {
  while (true) {
    try {
      yield take(actionTypes.USER.AUTH_FAILURE);
      const accessToken = Storage.token;
      yield accessToken;
      if (accessToken) {
        Storage.removeItem('token')
        yield put({
          type: actionTypes.USER.LOGIN,
        });
      } else {
        yield put({
          type: actionTypes.USER.REGISTER,
        });
      }
    } catch (error) {
      alert('Needs Login')
    }
  }
}
```

sagas for login or register 
```js
export function* login() {
  while (true) {
    try {
      yield take(actionTypes.USER.LOGIN);
      forwardTo('/login')
    } catch (error) {
      console.log('500 internal error');
    }
  }
}
export function* register() {
  while (true) {
    try {
      yield take(actionTypes.USER.REGISTER);
      forwardTo('/register')
    } catch (error) {
      console.log('500 internal error');
    }
  }
}
```

then after submit the form set other action login or register request 
```js
export function* signin() {
  while (true) {
    try {
      const request = yield take(actionTypes.USER.LOGIN_REQUEST);
      const { result, error } = yield call(userApi.user.login, request.query);
      if (result) {
        yield put({
          type: actionTypes.USER.LOGIN_SUCCESS,
          result,
        });
      }
      if (error) {
        yield put({
          type: actionTypes.USER.LOGIN_FAILURE,
          error: error.desc,
        });
      }
    } catch (error) {
      yield put({
        type: actionTypes.USER.LOGIN_FAILURE,
        payload: error,
      });
    }
  }
}
```

how can come back to Book Flow and push history to current URL when dispatch "LOGIN_SUCCESS"

Book Flow -----(api Call)--------- (401 needs Login) ------ (Book)------- (end)
Login Flow (take need Login) ---- (change history "/login") ------ (login sucess)

**Comment by Andarist** [comment]
It depends on how u transition from book flow (which you havent pasted in) to `failure`/`login`

**Comment by soroushm** [comment]
Dear @Andarist
on submit book form there is a api calling then response status is 401 unauthorized
Axios will be dispatch "AUTH_FAILURE" 
then "function* failure" will be take action and depend on user have accessToken or not will be push in login or register route
i wanna on "LOGIN_SUCCESS"  getting back to form and call api again

BR,

**Comment by Andarist** [comment]
your `AUTH_FAILURE` action should contain some useful data which you could use in something similar to `put({ type: REDIRECT_BACK: location: failureAction.redirectBack })` and ofc `take` this `REDIRECT_BACK` action from your submit book saga.
