### ISSUE TITLE
setinterval/delay not working properly (help)

### ISSUE THREAD

**Issue by DavidGonzalezGutierrez** [redux-saga/redux-saga#1293]
From one of my sagas, I make a call to a function or a generator (I have tried both), in which there is a while loop with a delay or a set interval without a loop.
My problem is that although the function is called immediately, the interval set takes about 20 seconds to start running.

What can be the problems?

The help is appreciated.

**Comment by Andarist** [comment]
You'd have to share your code to get the proper help - otherwise we might only guess where the mistake might lie.

**Comment by DavidGonzalezGutierrez** [comment]
**index.saga**
`import {all} from 'redux-saga/effects';
import {logSagas} from "./log.saga";
import {loginSagas} from '../screens/login/login.saga';
import {gpsSagas} from "../components/common/gps/gps.saga";
import {pagoQRSagas} from "../screens/pagoQR/pagoQR.saga";

export default function* rootSaga() {
    yield all([
        ...logSagas,
        ...loginSagas,
        ...gpsSagas,
        ...pagoQRSagas
    ])
}`

There are a total of 20 sagas that load when you start the app.

pagoQRSaga.js
`import {put, select, takeLatest, call, spawn} from "redux-saga/effects";
import {delay} from "redux-saga";
import axios from 'axios';
import {NavigationActions} from "react-navigation";
import {
    PANTALLA_VEHICULOS,
    VEHICULO_SELECCIONADO,
    ACTUALIZAR_ID_OPERACION,
    TICKET_SELECCIONADO
} from "./pagoQR.actionTypes";
import {CAMBIAR_MODO} from "../vehiculos/listaVehiculos/vehiculos.actionTypes";
import Config from "../../config";
import {alertError} from "../alert/alert.actions";

export function* pantallaTickets() {
    let vehiculo = yield select(state => state.pagoQR.vehiculo_seleccionado);
    if (vehiculo.empresa_cliente_id) {
        //respuesta
            yield put({type: ACTUALIZAR_ID_OPERACION, payload: respuesta.data.data.id});
            yield put(NavigationActions.navigate({routeName: 'QR'}));
///THE PROBLEM
            yield call(() => esperaAceptarPagoChannel());
        } catch (e) {
            yield put(alertError(e.message));
        }
    } else {
        //es particular
        yield put({type: CAMBIAR_MODO, payload: "seleccion"});
        yield put(NavigationActions.navigate({routeName: 'TicketsDescuento'}));
    }
}

export function* esperaAceptarPagoChannel() {
    let secs = 10;
    while (secs > 0) {
        yield call(delay, 1000);
        console.log(secs);
        secs--;
    }
}

export const pagoQRSagas = [
    takeLatest(PANTALLA_VEHICULOS, pantallaVehiculos),
    takeLatest(VEHICULO_SELECCIONADO, pantallaTickets),
    takeLatest(TICKET_SELECCIONADO, ticketSeleccionado)
];
`

**Comment by Andarist** [comment]
While this might work, it's suggested to use it like this:
```js
yield call(esperaAceptarPagoChannel);
```
How do you check that your timeout is being called to late? With this `console.log(secs);`? Maybe the placement of this `console.log` confuses you? Please move it above `yield call(delay, 1000);` and you will see that it's called immediately.

**Comment by DavidGonzalezGutierrez** [comment]
Thanks.
I tried like you said: 
yield call(esperaAceptarPagoChannel);
```javascript
export function* esperaAceptarPagoChannel() {
    let secs = 10;
    while (secs > 0) {
        console.log(secs);
        yield call(delay, 1000);
        secs--;
    }
}
```
this was the result: 
![captura](https://user-images.githubusercontent.com/16174918/33985986-7b9aa018-e0bc-11e7-83f6-470ffc0f15b5.PNG)

**Comment by DavidGonzalezGutierrez** [comment]
With setInterval something similar happens.
![captura](https://user-images.githubusercontent.com/16174918/33986975-9da2b68e-e0bf-11e7-95ae-913b4e530913.PNG)

Do not execute it until after 27 seconds.

**Comment by Andarist** [comment]
Sorry but there is no console.log('state after') in the given snippets so once again its hard to track the flow of the whole program. Please also put a console.log in place of THE PROBLEM comment

**Comment by DavidGonzalezGutierrez** [comment]
![captura](https://user-images.githubusercontent.com/16174918/33989494-0d497eb6-e0c8-11e7-9bd5-9427815381ff.PNG)
```javascript
export function* pantallaTickets() {
    let vehiculo = yield select(state => state.pagoQR.vehiculo_seleccionado);
    if (vehiculo.empresa_cliente_id) {
   
        try {
          
            yield put(NavigationActions.navigate({routeName: 'QR'}));
            console.log('Before call esperaAceptar...');
            yield call(esperaAceptarPagoChannel);
            console.log('After call esperaAceptar...');
        } catch (e) {
            yield put(alertError(e.message));
        }
    }
}

export function * esperaAceptarPagoChannel() {
    let secs = 3;
    while (secs > 0) {
        console.log('Before delay');
        yield call(delay, 1000);
        console.log('After delay');
        secs--;
    }
}
```

**Comment by Andarist** [comment]
Could u console.log(setTimeout.toString()) before delay? In what env are you running this? What browser? What system?

**Comment by DavidGonzalezGutierrez** [comment]
Debbuger: Chrome 63 in windows 10
Android: 6.0.1 Galaxy Note 4
"react": "16.0.0-beta.5",
"react-native": "^0.49.5",
"react-redux": "^5.0.6",
"redux": "^3.7.2",
"redux-saga": "^0.16.0"
![captura](https://user-images.githubusercontent.com/16174918/33990616-e4df5618-e0cb-11e7-8453-6ad7df394fe6.PNG)

**Comment by Andarist** [comment]
I think that React Native warning about debugger being in a background tab sums the problem nicely. Chrome is throttling timers such as `setTimeout` when they are fired in the background tab.

**Comment by DavidGonzalezGutierrez** [comment]
![captura](https://user-images.githubusercontent.com/16174918/33992205-fb338b40-e0d1-11e7-910a-32f696600396.PNG)

**Comment by DavidGonzalezGutierrez** [comment]
![captura](https://user-images.githubusercontent.com/16174918/33992291-4e1d2726-e0d2-11e7-8d91-892c3e2ee9bd.PNG)

**Comment by Andarist** [comment]
Unfortunately this is very likely problem with React Native and using the chrome debugger with it. There are bunch of issues about this in RN's github repository.

You can test this out with simpler:
```js
const countdown = (secs = 10) => {
	const next = () => setTimeout(() => {
		if (secs === 0) {
			return
		}
		secs--
		next()
	}, 1000)
	
	next()
}
```

**Comment by DavidGonzalezGutierrez** [comment]
```javascript
export function* ticketSeleccionado() {
    let vehiculo = yield select(state => state.pagoQR.vehiculo_seleccionado);
    let usuario = yield select(state => state.login.usuario);
    let estacion_servicio_id = yield select(state => state.estacionDetectada.estacion.id);
    let ticket_id = yield select(state => state.pagoQR.ticket_descuento_seleccionado.id);
    let token = yield select(state => state.login.token_type + ' ' + state.login.access_token);
    try {
        let respuesta = yield call(() => saveOperacionGasolineraApi(token, vehiculo.id, usuario.empresa_cliente_id, estacion_servicio_id, ticket_id));
        yield put({type: ACTUALIZAR_ID_OPERACION, payload: respuesta.data.data.id});
        yield put(NavigationActions.navigate({routeName: 'QR'}));
        yield call(() => esperaAceptarPagoChannel());
    } catch (e) {
        yield put(alertError(e.message));
    }
}

export function * sleep() {
    let start = new Date().getTime();
    for (let i = 0; i < 1e7; i++) {
        if ((new Date().getTime() - start) > 2000) {
            break;
        }
    }
}

// Función que inicializa el listener de posición del gps
export function * esperaAceptarPagoChannel() {
    let secs = 10;
    while (secs > 0) {
        console.log('a');
        yield call(sleep);
        secs--;
    }
}
```

I have used this internet code. It is not clean but it works. Any of the other functions gives problems.
Now the problem I have is that it is not sent asynchronously. It is waiting for the loop to finish to run.

**Comment by Andarist** [comment]
Blocking the whole (and the only one) thread is not the best idea. You should ask React Native community if there is a way to work around this issue in more proper way.
