### ISSUE TITLE
should CHANNEL_END equal CHANNEL_END_TYPE

### ISSUE THREAD

**Issue by superwf** [redux-saga/redux-saga#1294]
https://github.com/redux-saga/redux-saga/blob/32646061d27fe5e31a99b75ed128a05630af1190/src/internal/symbols.js#L8

when in env that Symbol not exist, CHANNEL_END and CHANNEL_END_TYPE will be same string.
is that a spelling mistake?

**Comment by Andarist** [comment]
The best what I can say for now is commented [here](https://github.com/redux-saga/redux-saga/blob/32646061d27fe5e31a99b75ed128a05630af1190/src/internal/proc.js#L27). They were extracted to the symbols file, but remain conceptually different values - previously were created without using `Symbol`, so nothing has changed. Need to investigate the situation though and I'd like to get rid of at least similar names for them.

**Comment by restrry** [comment]
was removed in https://github.com/redux-saga/redux-saga/pull/1464/files
