### ISSUE TITLE
Proposal: add meta data to delay effects for testing

### ISSUE THREAD

**Issue by D1plo1d** [redux-saga/redux-saga#1295]
With the invent of effectsMiddlewares it would be useful to be able to mock delay effects so that they can be asserted against and so that they don't actually cause a delay.

Problem: the delay effect returns a promise without any property to indicate that it is a delay which makes it impossible to distinguish from a promise returned by any other effect (AFAIK)

Proposal: add metadata to the promise returned by the delay effect to indicate that it is a delay and the length of the delay.

## Example Useage: Mocking delays

```js
  const delayMock = () => {
    const middleware = next => effect => {
      if (effect.type === 'delay') {
        for (resolveFn in middleware.waiting) {
          resolveFn({ next, effect })
        }
        middleware.waiting = []
      } else {
        return next(effect)
      }
    }
    middleware.waiting = []
    middleware.waitForDelay = () => new Promise((resolve, reject) => {
      middleware.waiting.push(resolve)
    })
    return middleware
  }
  
  test('it does something after 200ms', () => {
    const delays = delayMock()
    const sagaTester = new SagaTester({
      initialState,
      options: {
        effectMiddlewares: [delays],
      },
    })

    const delay = await delays.waitForDelay()
    expect(delay.effect.length).toBe(200)
    delay.next()
```

Edit: fixed the example

**Comment by Andarist** [comment]
On the master (not yet released to npm) `delay` is now an effect, check the [implementation](https://github.com/redux-saga/redux-saga/blob/62fecd710576bd3e28aae87aaba551475a31f5c2/src/internal/io.js#L223). I believe it should ease distinguishing it from other effects. If not please comment back.

**Comment by D1plo1d** [comment]
@Andarist yeah that's exactly what I was looking for! Thanks!

I rolled this example up into a little library that works with the latest code on redux-saga#master if anyone else wants to test their delays this way: https://github.com/D1plo1d/redux-saga-delay-mock
