### ISSUE TITLE
Using yielded values in nested generators

### ISSUE THREAD

**Issue by lukasz-zaroda** [redux-saga/redux-saga#1297]
```
function* test(action) {
    const subgenerator = function*() {
        const subgeneratorVariable = yield '1';
        console.log('subgeneratorVariable', subgeneratorVariable);
    };

    for (const generatedValue of subgenerator()) {
        const result = yield generatedValue;
        console.log('result', result);
    }
}
```
`result` variable has output of yield from the subgenerator. `subgeneratorVariable` is undefined. Is there any elegant solution to use yielded values in nested generators? I would like to have the value in the subgeneratorVariable also.

**Comment by Andarist** [comment]
This might not be possible, it's caused by semantics of for/of loop used on the generator. The yielded (and received by the for/of loop) value won't magically get injected back into the subgenerator.
