### ISSUE TITLE
Work with Flutures

### ISSUE THREAD

**Issue by ryanbas21** [redux-saga/redux-saga#1301]
I have been playing around with `Flutures` and since I saw a library `redux-fluture` has no documentation, I went back to use sagas.

The redux-saga middleware can't pick up on the fluture so for example

```
export function coinMarketCapData() {
    return callFuture('https://api.coinmarketcap.com/v1/ticker/?limit=10')
            .promise()
            .then(prop('data'))
}

export function* callRetrieveCoins(action) {
    const coins = yield call(coinMarketCapData)
    yield compose(put, addCoins)(coins)
    yield compose(put, isSearching)();
}
```

works but

```
export function coinMarketCapData() {
    return callFuture('https://api.coinmarketcap.com/v1/ticker/?limit=10')
                .value(prop('data)) // 
}
``
export function* callRetrieveCoins(action) {
    const coins = yield call(coinMarketCapData)
   // error!
    yield compose(put, addCoins)(coins)
    yield compose(put, isSearching)();
}
```

Does not. (expectedly).

It would be nice if the saga middleware would allow working on more than just promises.

Sorry if this has been discussed, some googling didn't pick up on this topic. I was just curious of the stance on this, not sure how large of a change it would be for sagas to support.

**Comment by pokorson** [comment]
Wouldn't `Fluture` separation of methods be a problem here? With Promise it's simple cause you have only `then` to retrieve value but Fluture has `map`, `chain` and `fork` for this purpose and each is slightly different.

So which method would you expect to get called with Fluture here:
`const coins = yield call(coinMarketCapData)`

Or would it require additional API for controlling this?

**Comment by ryanbas21** [comment]
That is a valid point, it could be an issue. I was using `.value` to extract the value out of the fluture.

**Comment by Andarist** [comment]
We'd like to support task libraries but there is no universal protocol for retrieving values and we cannot make it built-in, but we'd like to provide a way to write custom effects - that way you could just extend abilities of our internal effect runner with a custom effect resolved and you could easily create integration effect for Fluture.

**Comment by Andarist** [comment]
There are other issues about custom effects already, this is not an effort we are currently pursuing (because of lacking time resources), therefore I'm going to close this particular issue about it. Would love to see some external contributions for this feature.
