### ISSUE TITLE
Unable to import from redux-saga

### ISSUE THREAD

**Issue by cjpete** [redux-saga/redux-saga#1302]
ESLint in Atom is raising the following error:

```
Error while running ESLint: Cannot find module '/Users/cjpitt/project/node_modules/redux-saga/config/webpack.config.dev.js'
```

My ESLint config contains import resolvers as follows:

```
    "settings": {
        "import/resolver": {
            "webpack": {
                "config": "./config/webpack.config.dev.js"
            }
        }
    },
```

And the 'resolve' webpack config is as follows (this is taken from 'create-react-app' and the differences from the CRA release are that we import from 'src' as if its a node_module, e.g. import { someReduxSelector } from 'reducers', and the modernizr alias.

```
	resolve: {
		// This allows you to set a fallback for where Webpack should look for modules.
		// We placed these paths second because we want `node_modules` to "win"
		// if there are any conflicts. This matches Node resolution mechanism.
		// https://github.com/facebookincubator/create-react-app/issues/253
		modules: ['node_modules', 'src', paths.appNodeModules].concat(
			// It is guaranteed to exist because we tweak it in `env.js`
			process.env.NODE_PATH.split(path.delimiter).filter(Boolean)
		),
		// These are the reasonable defaults supported by the Node ecosystem.
		// We also include JSX as a common component filename extension to support
		// some tools, although we do not recommend using it, see:
		// https://github.com/facebookincubator/create-react-app/issues/290
		// `web` extension prefixes have been added for better support
		// for React Native Web.
		extensions: ['.web.js', '.mjs', '.js', '.json', '.web.jsx', '.jsx'],
		alias: {

			// Support React Native Web
			// https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/
			'react-native': 'react-native-web',
			// https://github.com/peerigon/modernizr-loader
			'modernizr$': path.resolve(__dirname, "../.modernizrrc"),
		},
	},
```

If I remove the import resolver, the import from redux-saga works fine. This obviously isn't an appropriate solution as it breaks our other module imports. However, there must be something different in the way redux-saga exports its contents versus, for example, the main redux package - since the import from node_modules works fine for that.

If you have any advice it would be greatly appreciated.

**Comment by Andarist** [comment]
You'd have to share a repository with the issue reproduced to get help, unfortunately I'm not familiar with `eslint-plugin-import` that much.

**Comment by cjpete** [comment]
@Andarist I've created a repo here - https://github.com/cjpete/redux-saga-import-issue

**Comment by Andarist** [comment]
Thanks for providing a sample repository. I've commented on the plugin's boards already. As this is not an issue with `redux-saga` itself I'm closing this thread. Hopefully we'll be able to fix this issue in the plugin soon.
