### ISSUE TITLE
Promise.all / all() response decoding corrupt data

### ISSUE THREAD

**Issue by vukasin-nikodijevic** [redux-saga/redux-saga#1303]
### Summary:
List of unresolved promises provided to `Promise.all()` or saga's `all()` method aren't properly decoded - in my case always first 6 items of array are cut of.

Here is how it looks in console (array of 12 with 6 objects only - sooo weird)
![image pasted at 2018-1-8 16-28](https://user-images.githubusercontent.com/1715831/34679168-64cc2c8e-f495-11e7-961b-6962ccffcaf2.png)

### What doesn't work:
> This is in saga generator function 

```
    const token = yield getToken();
    const channels = yield all(action.payload.navigationLinks
      .map(navigationLink => (fetchChannelPageVideos({channelId: navigationLink.channelId, pageNum: 1}, token)))
    );
    // Here channels object is NOT properly decoded - missing data received from API
    console.log("channels", channels);
```

### What works: 
> This is executed directly from component componentWillReceiveProps

```
      const token = JSON.parse(localStorage.getItem('oauth2_token')).token;
      Promise.all(
        nextProps.navigationLinks
          .map(navigationLink => (fetchChannelPageVideos({channelId: navigationLink.channelId, pageNum: 1}, token)))
      ).then(channels => {
        // Here channels object is properly decoded - match data received from API
        console.log("channels", channels);
      });
```

### A bit of debugging of fetch() method

```
fetch(BASE_URL + endpoint, options)
    .then(response => {
      return response.text().then(txt => {
        console.log("response txt", txt); // here is all data received from API
        const json = JSON.parse(txt);
        console.log("response json", json); // after decoding data is corrupted and missing first 6 items of array
        return json;
      });
    });
```

**Comment by Andarist** [comment]
Actually console might show you a snapshot of this data from some point in time. If you mutate the object you might see such "weirdo" numbers. I'd advise you to serialize data (with `JSON.stringify` or something) and trust only those logs.

Anyway - as you have also noticed, this "happens" without `redux-saga` being involved at all. Im not sure if we can help you here with non-saga issues like this - there is no fix that we could provide for that.

**Comment by vukasin-nikodijevic** [comment]
@Andarist - I finally solved issue - and everything was pointing that problem is in Saga - I was really wrong.

Issues comes from data mutation and from mostly unexpected place VIEW.

I'm providing connected data from store to my component and I have helper function to subset me videos array to first 3.

Probably IDE auto completed instead of `slice` > `splice` which mutates `videos` object and as it comes by reference it changed everywhere.

This is just one really evil bug - I'll close issue and thanks for reply :)
