### ISSUE TITLE
v1.0.0-beta.0: put.resolve is not a function

### ISSUE THREAD

**Issue by ms88privat** [redux-saga/redux-saga#1304]
Somehow `put.resolve` got lost in the newest version `v1.0.0-beta.0` ? After I downgraded, it did start to work immediately again. 

In the breaking changes I only noticed something about put.sync. So, is this intended?

**Comment by Andarist** [comment]
Please use `putResolve` with `v1.0.0-beta.0`. Forgot to add this to the release note.
