### ISSUE TITLE
update to redux 4

### ISSUE THREAD

**Issue by macrozone** [redux-saga/redux-saga#1306]
redux 4 is coming! https://github.com/reactjs/redux/releases/tag/v4.0.0-beta.1

it seems not to introduce many breaking changes, so it should work with saga as well, but saga has currently a dependency on redux 3.x, so that at least needs to be updated

**Comment by Andarist** [comment]
Actually `redux-saga` has this dependency only for `redux`'s `compose` utility - nothing more. This won't break and for the time being no upgrade has to be done as redux@3 will still be more common in the community for quite some time.

**Comment by macrozone** [comment]
@Andarist true, but it might pull in both redux versions in builds (depending on how the packagers work). Maybe loose the constraint to allow both versions of redux?

**Comment by aikoven** [comment]
Actually, there are breaking changes — in TypeScript typings. Although it should still be compatible with the current redux-saga typings.

Also, I wouldn't include 4.0.0 in the range, since it doesn't yet exist and stuff may change. Maybe there's a way to only include beta versions? Something like `>=0.10 <=4.0.0-beta.1`.

**Comment by Andarist** [comment]
I think that should be possible - we do such things for peer deps on babel integrations, like [here](https://github.com/babel/babel-loader/blob/master/package.json#L18).

**Comment by KeitIG** [comment]
Redux 4 it out btw https://github.com/reactjs/redux/releases/tag/v4.0.0

**Comment by Andarist** [comment]
As discussed - we should update the dependency range to `>=0.10 <5`. Anyone up for creating a PR? :)
