### ISSUE TITLE
Explain root sagas and sagaMiddleware.run better

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#1316]
@lydell has rightfully noticed [here](https://github.com/redux-saga/redux-saga/issues/760#issuecomment-360403490) that those topics might be confusing.

> As of 2018-01-25 the beginner tutorial says:
> 
> export default function* rootSaga() {
>   yield all([
>     helloSaga(),
>     watchIncrementAsync()
>   ])
> }
> As a beginner, I’m going to go with that until I run into problems.
> 
> It would be awesome if there was a section in the docs discussing different ways of implementing the root saga, mentioning pros and cons of each. Also mention what multiple calls to sagaMiddleware.run would mean.

**Comment by smashercosmo** [comment]
Here is my related question on stackoverflow: https://stackoverflow.com/questions/39438005/what-is-the-idiomatic-way-of-starting-rootsaga/47623129

**Comment by zgavin1** [comment]
I'm interested in working on this. I'll find some time in the next day or two.

**Comment by Andarist** [comment]
That would be great!

**Comment by younesmln** [comment]
I'm wondering about the status of this issue because I saw the a related PR has been merged but it still open
I'm interested in helping out if its still an issue

**Comment by zgavin1** [comment]
@Andarist Unless there's more info we want to include, this issue could be closed.
