### ISSUE TITLE
Is this correctly reflected in typings file ?

### ISSUE THREAD

**Issue by gauravsaini** [redux-saga/redux-saga#1320]
https://github.com/redux-saga/redux-saga/blob/2d33852ed9057e104f34a24987a8e410a1069783/src/internal/middleware.js#L30

**Comment by Andarist** [comment]
Sorry - could you be more precise? Which typings? Are you having any problem with this?

**Comment by gauravsaini** [comment]
https://github.com/redux-saga/redux-saga/blob/2d33852ed9057e104f34a24987a8e410a1069783/index.d.ts#L71

**Comment by Andarist** [comment]
@gauravsaini Pasting code lines without any kind of commentary is not really a good way of reporting an issue.

**Comment by spaceemotion** [comment]
I think what he means is that the d.ts files are not up to date (channels are not present). (e.g. PHPStorm tells me that it can't find them)

**Comment by Andarist** [comment]
If there are some typings missing, somebody will have to provide them. Typings are community-driven, I'd happily accept a PR for this.
