### ISSUE TITLE
Add OnlyLatest - this would be similar to Throttle and TakeLatest

### ISSUE THREAD

**Issue by clearwaterstream** [redux-saga/redux-saga#1325]
Hi,

Often times we need to accomplish the following behaviour. Whenever a user inputs a value into a field (let's say address lookup field), we need to hit an API to get some values.

It would be cool if we can do this: create a new helper that instead of cancelling current actions (TakeLatest) would instead queue up the new action so that it can executed once the current action finishes. Only the latest action will be taken from the queue upon completion of current action.

For example, let's say api.lookupaddress.com takes 3 seconds to respond.

With TakeLatest hooked up to a textbox (fires on text change) the moment a user types something in, the current api call would be cancelled and a new one would be made. The story repeats itself until the user finishes typing something in the textbox.

The problem with this approach is that api.lookupaddress.com still takes a hit! So server has to do work, even though the client cancelled the call. In other words, traffic was still sent to the server.

With throttle, I need to play around with timeouts - and that may not be a static value (i.e different delays under different scenarios, etc).

Can we add a new helper, that akin to throttle would allow only 1 execution of a task, and will queue up the rest of tasks. Once the current tasks is finished, it will check the queue and grab the LATEST task, and execute it. If no task exits in the queue - then all's good.

With this approach no extra traffic will be sent to the server, and I do not need to play around with delays.

So essentially the code would be very very similar to throttle helper minus the delay part.

Thanks!!

**Comment by Andarist** [comment]
You are probably looking for something like this:
```js
export const takeX = (ms, pattern, worker, ...args) => {
	return fork(function* () {
		const chan = yield actionChannel(pattern, buffers.sliding(1))

		for (;;) {
			const action = yield take(chan)
			yield call(worker, ...args, action)
		}
	})
}
```

**Comment by clearwaterstream** [comment]
great thank you, let me give it a try ..

**Comment by timm-aym** [comment]
This sound similar to what I though of implementing for a search suggestion box.

In that case I don't want to abort all / the latest pending request, but rather complete the most recent one and show the outdated suggestion (instead of none).

@Andarist I see you code does not make use of the `ms` parameter. Where would that be implemented? Otherwise the above implementation would pull in tasks as soon as the worker finished, right? (Which might be faster or slower than what's desired.)

**Comment by timm-aym** [comment]
I see that this functionality is now provided by the `throttle` helper :)

https://redux-saga.js.org/docs/api/#throttlems-pattern-saga-args
