### ISSUE TITLE
do I bundle firebase calls via async/await to bring this into redux-saga's?

### ISSUE THREAD

**Issue by callagga** [redux-saga/redux-saga#1326]
Any advice re my code below.  I'm noting I'm building out the "reset positions" function as standalone using async/await, but then noting overall (given I'm using redux-saga) should I have not been doing this, but rather build this into the saga/generators approach?   Seems kind of nice to segrate the "firebase only" building blocks separate, and then use redux-saga as the Firebase<=>MyApp/Redux interfacing perhaps (if this makes sense)?

```
function deleteItem(id) {
  const docRef = firebase.firestore().collection('todos').doc(id);
  docRef.delete();
}

async function resetPositionsAsyncAwait() {
  const collRef = firebase.firestore().collection('todos');
  const query = collRef.orderBy('position');
  try {
    const items = await query.get();
    let newCount = 0;
    items.forEach(async (doc) => {
      const docData = doc.data();
      const docRef = collRef.doc(doc.id);
      await docRef.update({ position: newCount });
      newCount += 1;
    });
  } catch (error) {
    console.log('resetPositionsAsyncAwait: error caught. Error=');
    console.log(pf(error));
  }
}

export function* deleteItemSagaR() {
  while (true) {
    const { id } = yield take(ActionTypes.DeleteListItem_UIRequest);
    yield put({ type: ActionTypes.DeleteListItemRequested });
    try {
      yield call(deleteItem, id);
      yield call(resetPositionsAsyncAwait);
      yield put({ type: ActionTypes.DeleteListItemFulfilled });
    } catch (e) {
      yield put({ type: ActionTypes.DeleteListItemRejected });
    }
  }
}
```

**Comment by Andarist** [comment]
If this works for you, then it works for you. Do not complicate things prematurely trying to do them "the right way" (or any other way 😉 ).

**Comment by wbowlin** [comment]
As an aside, this code does not wait for your items options to be processed before returning out of the `resetPositionsAsyncAwait` function due to the use of `async / await` within the `forEach`. That could cause subtle timing bugs since you are dispatching a fulfilled action type possibly before those calls are all done. 

Also, the way you have the saga yielding calls to Firebase is good as it allows you to easily test the saga without having to worry how to mock out Firebase itself.

**Comment by callagga** [comment]
thanks for the feedback - actually there was one suggestion I'd got/implemented since I posted, which hopefully addresses your first comment?  Does this look better?

```
async function resetPositionsAsyncAwait() {
  const db = firebase.firestore();
  const collRef = db.collection('todos');
  const query = collRef.orderBy('position');
  const batch = db.batch();

  // Step 1 - Read document data and prepare batch updates
  try {
    const items = await query.get();
    let newCount = 0;
    items.forEach(async (doc) => {
      const docRef = collRef.doc(doc.id);
      batch.update(docRef, { position: newCount });
      newCount += 1;
    });
  } catch (error) {
    console.log('resetPositionsAsyncAwait (during Step 1): error caught. Error=');
    console.log(pf(error));
  }

  // Step 2 - Run batch update
  try {
    await batch.commit();
  } catch (error) {
    console.log('resetPositionsAsyncAwait (during Step 2): error caught. Error=');
    console.log(pf(error));
  }
}
```
