### ISSUE TITLE
What is the difference between `yield [takelatest]` and `yield takelatest; yield takelatest`

### ISSUE THREAD

**Issue by abc225666** [redux-saga/redux-saga#1329]
By reading documentation and other question, I couldn't understand why these two way is the same.
```
const rootSaga = function * () {
    yield takelatest(A, Asaga);
    yield takelatest(B, Bsaga);
}
```
```
const rootSaga = function * () {
    yield [ takelatest(A, Asaga), takelatest(B, Bsaga) ]
}
```
I think the first way will stuck in A, but in fact, that work for receiving B without receiving A. I am confused how the first way work. Could anyone help me? Thanks

**Comment by Andarist** [comment]
`takeLatest` is built on top of `fork` so it using it won't block your saga.

There is no real difference between those two snippets. Subtle technicality is that first one "asks" redux-saga runtime 2x times to do something (starting a watcher in this case) while the latter asks only once - holding both in a 'batch'. yielding arrays is deprecated though - I'd recommend using explicit effect for this:
```js
const rootSaga = function * () {
    yield all([ takelatest(A, Asaga), takelatest(B, Bsaga) ])
}
```
