### ISSUE TITLE
Filtering actions

### ISSUE THREAD

**Issue by stat92** [redux-saga/redux-saga#1333]
Hi! I have the next issue: 

```
function* update(action) {

    if (action.payload === ...)) {        // I need to process request depending on the payload
      return;
    }

   ... process request
}

function* root() {
    yield takeLatest([ ... ], update)   // additionally I need to take only latest and cancel previous process
}
```

Issue appears in the situation when the first action meets conditions and gets processed, but second new action doesn't meet conditions and cancels previous process.

Is it possible to move that condition into redux-saga and take only actions that meet conditions? I've seen this feature in the `eventChannel` and it would be great to use it in the take effects also. Thanks.

**Comment by Andarist** [comment]
You can use `takeLatest(action => action.type === SOME_ACTION && action.payload.id === id, ...)`, but with the simple `takeLatest` you want be able to `takeLatestBasedOnKey` - you will have to create this on your own. Should be quite simple actually, just cache tasks in the map per id and manage that.

**Comment by stat92** [comment]
Great, thanks!
