### ISSUE TITLE
[Question] Order of execution (saga/reducer) life cycle

### ISSUE THREAD

**Issue by alfonsodev** [redux-saga/redux-saga#1334]
I wonder if it is guaranteed that the reducers will execute right after `put` 
before the next `yield`.
This would be a silly example.
```
// Assuming the initial value of the flag is false, and there is a reducer
// that sets the flag true when SET_A_FLAG is dispatched with enabled: true
function* sillyWorker() {
  yield put({ type: 'SET_A_FLAG', payload: { enabled: true } }) 
  const isFlagEnabled = yield select(state => state.enabled)
}
```
Will the reducer **always** have time to change the value in the store, 
before `yield seelct` is executed ?

**Comment by alfonsodev** [comment]
Sorry for opening this, it is very clearly explain in the docs.
```
It's important to note that when an action is dispatched to the store, the middleware first forwards the action to the reducers and then notifies the Sagas. This means that when you query the Store's State, you get the State after the action has been applied
```

**Comment by Andarist** [comment]
Keep in mind that's true if you do not introduce async middleware AFTER redux-saga's one (there is like noone doing that, but it's worth noting that the described behaviour might not be ALWAYS true).
