### ISSUE TITLE
How to intercept redux-saga depending on api response status?

### ISSUE THREAD

**Issue by HsuWai** [redux-saga/redux-saga#1335]
In my react-native project, I want to handle 204 (no content error) response globally after getting response from api request and navigate to screen. How should I do to intercept in saga?

**Comment by Andarist** [comment]
It somewhat depends on the used request approach/library. If you want to handle this in saga then you should have a single place in saga making those requests and after you get the response you should handle it there or let it communicate to some external handler that this response is got `204` and that should be handled.

**Comment by HsuWai** [comment]
Thans for your answer, Andarist. The request library used is axios. I've tried to handle and dispatch action for 204 response in the response interceptor of axios. That's ok for all actions. But, I don't want this behavior and I just want to intercept at some saga effects, not for all. Is there any way to handle like that?

**Comment by HsuWai** [comment]
I mean I just want to intercept for saga call effects.

**Comment by Andarist** [comment]
I think `effectMiddlewares` described in v1-beta release notes - https://github.com/redux-saga/redux-saga/releases/tag/v1.0.0-beta.0 - could help you.

You'd have to hijack your requests, execute them on your own and inject the return value back yourself.

**Comment by HsuWai** [comment]
Ok. Thanks, Andarist.

**Comment by restrry** [comment]
usually in tests https://github.com/redux-saga/redux-saga/blob/master/packages/core/test/interpreter/effectMiddlewares.js
and docs https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/Testing.md#effectmiddlwares
