### ISSUE TITLE
Typed `yield call`

### ISSUE THREAD

**Issue by zerkms** [redux-saga/redux-saga#1336]
In the following statement

```typescript
const data = yield call(f);
```
`data` would be inferred as `any` (while `f` is a `() => Promise<number>` function).

Is it a fundamental limitation, something that might be improved or is it me doing something wrong?

**Comment by zerkms** [comment]
Somebody else has provided me a link to the typescript issue https://github.com/Microsoft/TypeScript/issues/2983#issuecomment-230404301

So, at the moment it's a typescript limitation.

**Comment by krzkaczor** [comment]
This should be possible with: Typescript 3.6

 https://devblogs.microsoft.com/typescript/announcing-typescript-3-6-beta/

**Comment by marcusegues** [comment]
@krzkaczor can you give an example of how this works?

How would one type the below saga (generator function):
```
interface Data {
  someData: string
}

const apiRequest = async (): Promise<Data> => ({ someData: "data" })

function* genFunc(): Generator<Data, any, Data> {
  try {
    const data = yield apiRequest();
  } catch {
      console.log("error")
  }
}
```

**Comment by krzkaczor** [comment]
@marcusegues i think I was mistaken. After I dived into this feature I realized that it won't solve this problem :(
