### ISSUE TITLE
Question: Re-Authentication flow

### ISSUE THREAD

**Issue by trassmann** [redux-saga/redux-saga#1339]
Hello saga-people,

I am currently implementing a CRUD App with the help of redux-saga. The API will respond with the status code `419` when the authentication token, which is sent on the request header, has expired. My current logic is as follows:

1. There is a central `requestHandlerSaga` that handles sending all API requests via the fetch API.
2. When the `response.status` is `419`, I dispatch an authentication action (the same one that I send when the user clicks Login) with the `refreshToken` on the redux store.
3. I wait for the next authenticate receive action via take: `take([AUTHENTICATE_SUCCESS, AUTHENTICATE_FAIL])`.
4. If it succeeds, I resend the request. This is crucial as this ensure that the saga that was executing still returns with the correct value and I don't have to restart the saga that executes the request handler.
5. If it fails, I logout the user.

The issue with this request is that I create circular dependencies. The generic request handler relies on actions from the authentication sagas and they rely on the request handler. So this design is in itself flawed. Do you have any ideas how I could improve this in a way that it still generically handles every request, but does not rely on linking authentication with it?

Here's the code:

```
const createRequestHandler = method =>
  function* handleRequest(resource, modelId, payload, toHost = false, noRetry = false) {
    try {
      const response = yield call(sendRequest, method, resource, modelId, payload, toHost);
      if (response.ok) {
        if (!response.redirected) {
          return yield response.json();
        }
        return response.text();
      }
      const responseBody = yield response.json();
      if (response.status === 419) {
        // If the retry request also gets a 419, logout
        if (noRetry) {
          const isLoggedIn = yield select(getCurrentAuthState);
          if (isLoggedIn) {
            yield put(logout());
          }
          throw new Error(responseBody);
        }
        const isProcessingReAuth = yield select(getProcessingReAuthState);
        // Dispatch auth with refreshToken if we are not already re-authenticating
        if (!isProcessingReAuth) {
          // On 419, attempt to re-authenticate
          // Select the refresh token from the store
          const refreshToken = yield select(getRefreshToken);
          yield put(login({ refreshToken }));
        }
        // Pause until either auth success or failure triggered
        const { type: reAuthResultActionType } = yield take([AUTHENTICATE_SUCCESS, AUTHENTICATE_FAIL]);
        // If re-auth failed, logout
        if (reAuthResultActionType === AUTHENTICATE_FAIL) {
          return yield put(logout());
        }
        // Re-send the request
        const newRequestHandler = createRequestHandler(method);
        return yield call(newRequestHandler, resource, modelId, payload, toHost, true);
      }
      throw new Error(responseBody);
    } catch (error) {
      throw error;
    }
  };
```

**Comment by Andarist** [comment]
Wouldn't just separating action types from authentication sagas fix your circular dep concerns?

**Comment by trassmann** [comment]
@Andarist Yes, but since I am using ducks that is not really an option. The problem lies not within the circular dependency per se, I just feel that creating circular dependencies is a sign of bad design, and since this is within the very foundation of the app, I want it to be designed solidly. Do you have any ideas how else I could solve this issue?

Thanks for your answer.

**Comment by Andarist** [comment]
**Maybe** you could restructure it so you won't listen for authentication actions but rather just call authentication saga? Not sure if authentication request saga depends on this generic request handler though - maybe it doesn't have to? If it does it's a little bit unclear to me how it works because authentication request could cause authentication waterfalls which would be bad too, right? Or is it supposed to retry authentication process indefinitely?

**Comment by trassmann** [comment]
Yes, authentication also uses the request handler to send its requests. But the API will never respond with a 419 on an authentication request. After thinking about it and talking to you I see two possibilities:

1. Don't implement authentication using the `requestHandler`, instead use `sendRequest` directly.
2. Take the whole re-auth logic out of the `requestHandler` and implement  a generic error handler that all sagas use to handle errors. This error handler would handle `419`. But it would also mean that I'd have to use it in every saga that sends a request, which would mean duplicating code.

Do you have any other ideas? Which of the two options would you go for?

**Comment by Andarist** [comment]
I would probably go with 1, seems OK to me and what I had in mind as one of possibilities when I have commented on the issue earlier.

**Comment by Andarist** [comment]
I think the issue can be closed, if you have any more questions u can ask at any time.
