### ISSUE TITLE
Create Redux Saga App

### ISSUE THREAD

**Issue by kafka-tamura** [redux-saga/redux-saga#1340]
Are there any plans to develop a create redux saga app... on lines of [create-react-app](https://github.com/facebook/create-react-app). I know adding saga to a create-react-app is probably a 20 min task, but still it would be good to have a boilerplate way of managing this.

**Comment by Andarist** [comment]
Not as part of this project, there are existing boilerplates with redux-saga included - ie https://github.com/react-boilerplate/react-boilerplate

**Comment by kafka-tamura** [comment]
Thanks @Andarist.
