### ISSUE TITLE
What if i never call "put()"?

### ISSUE THREAD

**Issue by LKiening** [redux-saga/redux-saga#1341]
Hallo,

first of all let me say thank you for this great lib :)

I have a rather special usecase for the redux world. We are building a site with multiple SPAs on it. Every SPA has its own store. 
But we need a way to communicate between all the apps.
We have build a "Global-Event-Dispatcher" (very few lines of code) with a dispatch method. This dispatch method calls dispatch on every store.

When i want to call globalEventDispatcher.dispatch() in a saga i dont need to call the redux-saga put method to get the action to my store. If i would call put() the application gets the action twice. One action from the globalEventDispatcher and one from the saga.put method.

Whats the effect on redux-saga when some sagas never call the put method?

**Comment by Andarist** [comment]
> Whats the effect on redux-saga when some sagas never call the put method?

There is no effect, `put` is just a wrapper around dispatch and you are not obliged to use any particular effects, you are using whatever you need in particular saga.

As to the problem in general - wouldn't you be able to prevent double dispatches by recognizing action's origin (single store) and prevent from dispatching it again into the source store?

**Comment by LKiening** [comment]
Thank you for the fast answer! Good to know that nothing bad will happen if i dont call the put method.

Your idea would be my fallback option. Since every app is developed by a independet team and every  app runs in a container, its diffucult to make assumptions on the globalEventDispatcher level.

Again thank you for the reply :)

**Comment by Andarist** [comment]
> Your idea would be my fallback option. Since every app is developed by a independet team and every app runs in a container, its diffucult to make assumptions on the globalEventDispatcher level.

Don't you have to register your stores in it? If you do then you have a clear-ish link between a particular store's instance and place where you hook into its actions.

**Comment by LKiening** [comment]
You are absolutly right. But i simple dont know what teamX does in its sagas. They can call
- put
- globalEventDispatcher.dispatch
- or both of them
If the globalEventDispatcher doesnt dispatch actions to its origin store, the teams have to call both methods if they want the action local and globally distibuted. 
I guess its a question of convention and communication what the teams have to do to get the desired effect.
