### ISSUE TITLE
Typescript - Call mock api with call effect

### ISSUE THREAD

**Issue by fdesrosiers** [redux-saga/redux-saga#1343]
Hi,
     It's my first issue ans I didn'T find a way to label it, sorry. I'm trying to call a mock API and i got this error:
error TS2345: Argument of type 'Promise<Program[]>' is not assignable to parameter of type 'CallEffectNamedFn<{ [x: string]: Func0; }, string>'.
  Type 'Promise<Program[]>' is not assignable to type '{ context: { [x: string]: Func0; }; fn: string; }'.
    Property 'context' is missing in type 'Promise<Program[]>'.

The version of redux-saga is: "^0.16.0"

Here the mock API:
```javascript
    getAllMembersAsync() : Promise<Program[]> {
        const promise : Promise<Array<Program>> = new Promise((resolve, reject) => {
                var members : Array<Program>;

                members = ProgramsData.map((currentProgram) => {
                    var program : Program = new Program();

                    program.code = currentProgram.code;
                    program.nom = currentProgram.nom;
                    program.cours = currentProgram.cours;

                    return program;
                });

                resolve(members);
            // });
        });
        return promise;
    }
```

And here my saga:
```javascript
import {call, put, takeLatest} from 'redux-saga/effects';
import { receivedPrograms, FetchPrograms, FETCH_PROGRAMS } from '../actions/programActions';
import { Program } from '../model/program';
import programAPI from '../api/programAPI';

function* fetchPrograms(action: FetchPrograms) {
    let programs: Array<Program>;
    programs = yield call(programAPI.getAllMembersAsync());
    yield put(receivedPrograms(programs));
}
```
Can someone tell my what i'm not doing correctly ? 

thanks alot guys !

**Comment by Andarist** [comment]
I have nearly zero experience with TS, but maybe you could try this:
```js
    programs = yield call(programAPI.getAllMembersAsync);
```

`call` is responsible for actually executing ur function, so invoking it here is probably not what u were looking for.

**Comment by fdesrosiers** [comment]
Thanks a lot @Andarist, my nearly zero experience with TS in nearer of zero than yours.

thanks again !

**Comment by Andarist** [comment]
I guess this can be closed then. Glad it helped :)
