### ISSUE TITLE
takeEvery/takeLatest is executed twice even though action dispatched only once 

### ISSUE THREAD

**Issue by Ayyagaries** [redux-saga/redux-saga#1345]
I have a root saga and login saga like so 
// Login saga
const loginSaga = function * () {
  yield takeEvery(GET_USER_TOKEN, getUserToken)
  yield takeEvery(LOGIN_ERROR, clearConversionError)
}

//Root Saga 
const rootSaga = function * () {
  yield [fork(loginsaga)]
 }
export default rootSaga

//Store
const configureStore = () => {
  const store = createStore(persistReducer, applyMiddleware(...middleware))
  sagaMiddleware.run(rootSaga)
  const persistor = persistStore(store)

  return {store, persistor}
}

export default configureStore

--- My issue is when I run the app the getUserToken is executed Twice --- 

Not sure why this is happening, can anyone help me understand what is happening.

**Comment by Andarist** [comment]
There are 2 possibilities:
- u dispatch `GET_USER_TOKEN` twice
- u fork `loginSaga` twice
