### ISSUE TITLE
Saga function is not being called

### ISSUE THREAD

**Issue by angemile09** [redux-saga/redux-saga#1347]
i have one application with differents saga, en dev all is good, but when i make deploy in production; i use 2 sagas and the third sga that i use is not call.(I don't get any errors). The sga that i need call is REGISTER_USER

index.js

export class RegistrationForm extends React.Component { // eslint-disable-line react/prefer-stateless-function

  constructor() {
    super();
    this.state = {
      email: null,
    };
  }

  register = () => {
    this.props.dispatch(email(this.state.email));
    this.props.dispatch(register(this.state.email));
  }

  render() {
    const props = {
      onChanged: this.onEmailChanged,
      label: 'Email',
      required: true,
    };
    let continueAsAGuest = null;
    if (this.props.invalidEmail) {
      props.errorMessage = <FormattedMessage {...messages.invalideEmail} />;
    }
    if (this.props.userExists) {
      props.errorMessage = <FormattedMessage {...messages.accoutnExists} />;
      continueAsAGuest = (
        <Row>
          <Col>
            <FormattedMessage
              {...messages.continueAsGuest}
              values={{
                link: <Link href="#" onClick={this.goAsAGuest}><FormattedMessage {...messages.clickHere} /></Link>,
              }}
            />
          </Col>
        </Row>
      );
    }
    return (
      <Row>
        <Col className="ms-u-sm12">
          <form className="registration-form">
            <Grid>
              <Row>
                <div className="display-table">
                  <Col className="ms-u-sm8 display-table-cell">
                    <TextField {...props} />
                  </Col>
                  <Col className="ms-u-sm4 display-table-cell align-bottom">
                    <PrimaryButton className="full-width" onClick={this.register}><FormattedMessage {...messages.register} /></PrimaryButton>
                  </Col>
                </div>
              </Row>
              <hr />
              <Row>
                <Col>
                  <FormattedMessage
                    {...messages.login}
                    values={{
                      link: <Link href="#" onClick={this.goToLogin}><FormattedMessage {...messages.signInHere} /></Link>,
                    }}
                  />
                </Col>
              </Row>
              {continueAsAGuest}
            </Grid>
          </form>
        </Col>
      </Row>
    );
  }
}

RegistrationForm.propTypes = {
  dispatch: PropTypes.func.isRequired,
  invalidEmail: PropTypes.bool.isRequired,
  userExists: PropTypes.bool.isRequired,
};

const mapStateToProps = createStructuredSelector({
  invalidEmail: makeInvalidEmail(),
  userExists: makeUserExists(),
});

function mapDispatchToProps(dispatch) {
  return {
    dispatch,
  };
}

export default connect(mapStateToProps, mapDispatchToProps)(RegistrationForm);

action.js

export function register(courriel) {
  return {
    type: REGISTER_USER,
    email: courriel,
  };
}

export function email(courriel) {
  return {
    type: EMAIL,
    email: courriel,
  };
}

reducer.js

function registrationFormReducer(state = initialState, action) {
  switch (action.type) {
    case REGISTER_USER:
      return state
        .set('invalidEmail', false)
        .set('userExists', false);
    case EMAIL:
      return state
        .set('email', action.email);
    default:
      return state;
  }
}

export default registrationFormReducer;

saga.js

export function* register(message) {
  const requestURL = `${__API__}/register`;
  try {
    const response = yield call(request, requestURL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        email: message.email,
      }),
    });
    if (response.status === 'userNonFound') {
      yield put(changedPhase(PHASE_CREATE_USER));
    } else if (response.status === 'userFound') {
      yield put(userFound());
    } else if (response.status === 'invalidEmail') {
      yield put(invalidEmail());
    } else {
      yield put(registrationError());
    }
  } catch (err) {
    yield put(registrationError());
  }
}

//export function* registerSaga() { yield takeLatest(REGISTER_USER, register); }
export const registerSaga = takeEvery(REGISTER_USER, register)

// All sagas to be loaded
export default [
  fork(registerSaga),  
];

**Comment by angemile09** [comment]
@Andarist can you help me with this?

**Comment by Andarist** [comment]
You'd have to share repository with the issue reproduced (or some codesandbox). Also - please paste in formatted code, unfortunately this is completely unreadable right now.

**Comment by restrry** [comment]
I'll close the issue due to inactivity, feel free to reopen. having a reproducible case is highly appreciated
