### ISSUE TITLE
Strange login flow examples in Redux-Saga documentation

### ISSUE THREAD

**Issue by emlmsc** [redux-saga/redux-saga#1349]
For example, if you read [this ](https://redux-saga.js.org/docs/advanced/FutureActions.html) section in redux-saga`s documentation there is an example related to login flow that looks like this.

```
function* loginFlow() {
  while (true) {
    yield take('LOGIN')
    // ... perform the login logic
    yield take('LOGOUT')
    // ... perform the logout logic
  }
} 
```

As there said:

> The loginFlow Saga more clearly conveys the expected action sequence. It knows that the LOGIN action should always be followed by a LOGOUT action, and that LOGOUT is always followed by a LOGIN

Does LOGOUT always follow LOGIN ? I dont think so. For example when user logged in to web site once as usual session will be stored in cookies of web site and when user will visit this web site again how loginFlow saga will catch LOGOUT action?

Or, next example, with login again that described [here](https://redux-saga.js.org/docs/advanced/NonBlockingCalls.html). I wonder how user can click LOGOUT if authorization not completed yet and button that log user out of web site not showed yet? These examples sound strange. I confused a little bit.

Can anyone explain me how these examples fit real world situations of login flow?

Thanks.

**Comment by Andarist** [comment]
> Does LOGOUT always follow LOGIN ? I dont think so. For example when user logged in to web site once as usual session will be stored in cookies of web site and when user will visit this web site again how loginFlow saga will catch LOGOUT action?

It depends how your application is structured. Remember that this is just a simple example and it's goal is to present the idea that saga is not simply responding to actions whenever they happen but that actually it is a state machine - so at certain points it time it can listen to different actions, depending on its state.

**Comment by emlmsc** [comment]
@Andarist 
Next example that described [here](https://redux-saga.js.org/docs/advanced/NonBlockingCalls.html) also for demonstration purposes? Because i didnt see any web site that show to user logout button until he authorized on web site.

**Comment by Andarist** [comment]
If you feel that this example could use some work to reflect better actual use cases, I strongly encourage you to send a PR changing this.

**Comment by emlmsc** [comment]
@Andarist 
In my opinion, even if examples are basic and showed just for demonstration purposes of the system, they must fit real needs. These examples looks like not fit real cases and second example is too complicated while in real case its not even necessary to catch logout action while authorization not complited yet because any website wont show logout button to nonauthorized user. May be its better to show another examples to demonstrate the power of redux-saga that fit actual cases of real world. But its up to you. I just got confused a little bit when reading these examples, because i started to doubt my vision of login/logout flow. So, thanks for replying. I appreciate it.

**Comment by Andarist** [comment]
> In my opinion, even if examples are basic and showed just for demonstration purposes of the system, they must fit real needs.

Sure, that is ideal.

> These examples looks like not fit real cases and second example is too complicated while in real case its not even necessary to catch logout action while authorization not complited yet because any website wont show logout button to nonauthorized user.

Truth to be told `LOGOUT` doesn't have to be triggered by a logout button, source of this action might be entirely else and the real-world saga would have to consider it.

If you have any better example to show in this section, please share it with us for consideration or even better send a PR with a change. Without that I doubt it will get changed any time soon as our resources are very thin.

**Comment by emlmsc** [comment]
@Andarist 
As example it can be tutorial on web site that introduce to user something step by step. Or another example registration of user on web site step by step, when user firstly input its fullname and other info, then in second step upload avatart and further.
