### ISSUE TITLE
Saga does not get cancelled when using variable returned from a call in take pattern

### ISSUE THREAD

**Issue by MJLHThomassen-Eurocom** [redux-saga/redux-saga#1350]
Consider the following minimal example i could come up with (using Typescript):

```javascript
interface Foo
{
    bar: string;
}

function getFoo(): Promise<Foo>
{
    return Promise.resolve({ bar: "baz" });
}

function* getFooSaga(): SagaIterator
{
    try
    {
        while (true)
        {
            // Get some foo
            const foo: Foo = yield call(getFoo);

            // Wait for action.payload to be equal to foo.bar
            yield take(
                (action: Action) =>
                {
                    return action["payload"] === foo.bar; // <-- This breaks stuff!
                });
        }
    }
    finally
    {
        if (yield cancelled())
        {
            console.log("This never gets called.");
        }
    }
}

function* someOtherSaga(): SagaIterator
{
    while (true)
    {
        try
        {
            while (true)
            {
                // Get some foo
                const foo: Foo = yield call(getFoo);

                // Wait for anything
                yield take("*");
            }
        }
        finally
        {
            if (yield cancelled())
            {
                console.log("This does get called.");
            }
        }
    }
}

function* tasksSaga(): SagaIterator
{
    yield all([
        call(getFooSaga),
        call(someOtherSaga)
    ]);
}

export function* mainSaga(): SagaIterator
{
    while(true)
    {
        const tasksTask: Task = yield fork(tasksSaga);

        yield take("SOME_ACTION");

        yield cancel(tasksTask);
    }
}
```

For some reason, referencing `foo.bar` in the pattern for `take` breaks things. After ` yield cancel(tasksTask);`, someOtherSaga gets cancelled, but getFooSaga does not. It also does not throw any errors. This causes 2 getFooSaga's to run when mainSaga() runs for the 2nd time (after SOME_ACTION happened).

I can't figure out whats going wrong here. When replacing `foo.bar` with a constant i.e. "someString", it does work (the saga gets canceled and the log statement prints).

The practical application for this is that after a button press, i start a saga (the "getFooSaga") that grabs an id from a WebApi and i want to wait (take) some action(s) only when the action payload matches that specific id.

**Comment by Andarist** [comment]
Could u prepare a reproduced example on something like codesandbox.io ?

**Comment by MJLHThomassen-Eurocom** [comment]
Hmm, this is strange. I've implemented the example here: https://codesandbox.io/s/wn6yzky9mw

But it seems to work as it should. If i paste the code into my own project it does not... (using the same versions of all the packages of course). Could it have something to do with the typescript transpiler perhaps? I can't configure that in the online tool.

**Comment by Andarist** [comment]
It's rather unlikely that TS compiler would interfere this anyhow. If you share your repository I could try to debug this, but without that it's really hard to tell. You'd have to dive into internal `runCancelEffect` to see what's happening and why the other saga is not getting cancelled.

**Comment by MJLHThomassen-Eurocom** [comment]
Unfortunately i can't share the actual repo since its an internal product for our company. I can however try to setup a project with a similar setup but minimal code and put it on github to share with you. I'll try to look into that today.

I'd debug it myself but i currently have 0 knowledge about redux-saga internals and unfrotunately not the time to dive into it. I apreciate any help!

**Comment by Andarist** [comment]
Not having the issue reproduced forces me to close this for now.

**Comment by MJLHThomassen-Eurocom** [comment]
Sorry for that, our company currently is not actively developing that product anymore so I had no time to properly reproduce the issue. Its been a while and I don't remember how this was solved but I think I was able to work around it somehow.  Closing this is fine.
