### ISSUE TITLE
.done renamed to .toPromise() is missing in typings

### ISSUE THREAD

**Issue by MJLHThomassen-Eurocom** [redux-saga/redux-saga#1353]
#1231 changed Task.done to Task.toPromse(). The typings shipped with 1.0.0-beta.0 still define the following interface:

```
export interface Task {
  isRunning(): boolean;
  isCancelled(): boolean;
  result(): any | undefined;
  result<T>(): T | undefined;
  error(): any | undefined;
  done: Promise<any>;
  cancel(): void;
  setContext<C extends object>(props: Partial<C>): void;
}
```

Which should probably be:

```
export interface Task {
  isRunning(): boolean;
  isCancelled(): boolean;
  result(): any | undefined;
  result<T>(): T | undefined;
  error(): any | undefined;
  toPromise(): Promise<any>;
  cancel(): void;
  setContext<C extends object>(props: Partial<C>): void;
}
```

EDIT:

Just checked the code and it has already been replaced. For some reason this didn't make it into the 1.0.0-beta.0 release (yet). It's not breaking but usefull for HMR. I'll look forward to the next (beta) release!

**Comment by Andarist** [comment]
Hopefully new beta will get shipped this week with some really cool DX feature 😉
