### ISSUE TITLE
END and the consequences on take effects inside races

### ISSUE THREAD

**Issue by chacestew** [redux-saga/redux-saga#1354]
Hi there,

How exactly should `take` effects behave inside a `race` when `END` is dispatched?

I am running into an issue on server rendering. If a saga is blocked on the race below...

```js
yield put(doSomethingAsync()) // this action is taken to trigger a fetch saga

const { success, error, timeout } = yield race({
      success: take(doSomethingAsyncSuccess),
      error: take(doSomethingAsyncFailure),
      timeout: delay(5000)
});
```
... and `END` is dispatched, then putting either `doSomethingAsyncSuccess` or `doSomethingAsyncFailure` does nothing and the saga hangs. Only after 5 seconds will the delay resolve to timeout and the saga can continue. 

Am I correct in thinking the race effect is not terminated but any `take` conditions inside it are? If so there a better way to handle such logic when dispatching `END`?

**Comment by chacestew** [comment]
Reading https://github.com/redux-saga/redux-saga/issues/1117 this does seem to confirm the behaviour that **all** basic takes will terminate when `END` is dispatched via the `stdChannel`, so I'lI scrap that question.

Before closing - is there any intention for this behaviour to change in v1, relating to https://github.com/redux-saga/redux-saga/pull/824 or others? If there is anything already in beta to change or extend how `END` works, I'd be keen to test it in our implementation.

**Comment by Andarist** [comment]
You could try to utilize `effectsMiddleware` feature from v1 to track and resolve other effects based on `END`.

Truth to be told `END` is a hacky solution in itself, if you have any proposal on how it could be improved, I'm all ears. What would you see handled differently?

**Comment by Andarist** [comment]
https://github.com/redux-saga/redux-saga/pull/1493 got merged in, this should "resolve" ur issue by aligning the behaviour with `all` - `END` is going to cancel the saga waiting on `take`
