### ISSUE TITLE
RangeError: Maximum call stack size exceeded in Sagas recursion

### ISSUE THREAD

**Issue by hendywijaya** [redux-saga/redux-saga#1356]
Hi Guys,

related to https://github.com/redux-saga/redux-saga/issues/888

I'm still getting this issue at `0.15.6`

When utilizing a lot of Sagas, in high traffic / concurrency, my app will break:

```
redux-saga error: uncaught at fetchCategoryAPI
RangeError: Maximum call stack size exceeded
    at /node_modules/redux-saga/lib/internal/middleware.js:68:23
    at /node_modules/redux-saga/lib/internal/middleware.js:72:22
```

It doesn't always break at the same Sagas 

Should I increase my OS limit on the stack size ? I doubt that will answer the issue.

it seems to point to this part of the redux-saga code

```
return function (next) {
      return function (action) {
        if (sagaMonitor && sagaMonitor.actionDispatched) {
          sagaMonitor.actionDispatched(action);
        }
        var result = next(action); // hit reducers --> recursion on line 72
        sagaEmitter.emit(action);
        return result;
      };
    };
```
Could this be another issue on the recursion ? @wilsaj  @jhsu Andarist 

Many thanks in advanced for the responses

**Comment by hendywijaya** [comment]
To give more detail these are some sample of my Sagas:

`CategorySagas.js`
```
export function* fetchCategoryAPI (api, data) {
  yield baseFetchNoToken(api.getCategory,
    data,
    CategoryActions.categorySuccess,
    CategoryActions.categoryFailure)
}
```

`BaseSagas.js` - universal style Sagas
```
export function* baseFetchNoToken (api, data, successAction, failureAction) {
  try {
    const res = yield call(api, data)
    if (!res.ok) {
      yield put(failureAction('system error'))
    } else {
      if (!res.data.error) {
        yield put(successAction(res.data.data))
      } else {
        yield put(failureAction(res.data.message))
      }
    }
  } catch (e) {
    yield put(failureAction())
  }
}
```

**Comment by hendywijaya** [comment]
Hi Guys,

Even when enabling just a single store dispatch calling a single Sagas repeatedly, this error still occurs

**Comment by Andarist** [comment]
Could u please create a repository illustrating the issue? I'd like to investigate this.

**Comment by hendywijaya** [comment]
Hi @Andarist 
terribly sorry for late response, here's my sample repo -> https://github.com/hendywijaya/redux-maxcallstack
the issue starts to happen once we do concurrency test (using siege).
In the sample repo, I simulate the api callback section using returning an object.

**Comment by Andarist** [comment]
Thanks for the repro! However it's not working, you forgot to include `./config.js`

**Comment by hendywijaya** [comment]
Hi @Andarist 
Sorry, it was included in .gitignore, I've added the file now 😅

**Comment by hendywijaya** [comment]
Hi @Andarist sorry being slow responding. I'm actually in the middle of tracing similar issue that happens in my other application with smaller load. Will post back my finding here. 
As for the siege, it's actually a simple siege test with 10 concurrent 
https://www.joedog.org/siege-manual/

**Comment by Andarist** [comment]
I just don't have time now to learn this tool, would appreciate clear instructions on how to reproduce ur issue.

**Comment by hendywijaya** [comment]
hi @Andarist 

Sure, I'll try to make it simple.

1. build nextjs by running `npm run build .`
2. start app by running `node start.js`
3. load test the application using `siege -c 50 -i -f urls.txt`

to install `siege` on macosx using homebrew -> `brew install siege`

to install `siege` on windows -> https://github.com/ewwink/siege-windows

to install `siege` on linux, use `apt-get` or `yum` accordingly

during the process of running `siege` the application will be hit multiple times by this load testing tool. 

CMIIW, If we look at the error message, it happens immediately after a max call stack size overflow in recursion part of `sagaMiddleware.run` 

`sagaMiddleware.run` is called in my application sample by next-redux-wrapper part of the code in  [src/Shared/Utils/Misc/ReduxWrapper.js](https://github.com/hendywijaya/redux-maxcallstack/blob/master/src/Shared/Utils/Misc/ReduxWrapper.js)

**Comment by hendywijaya** [comment]
Hi @Andarist 

When I try to debug using a counter in this part
```
var _runSaga = /*#__PURE__*/require('./runSaga');
var stackCount = 0;
...
return function (next) {
      return function (action) {
        if (sagaMonitor && sagaMonitor.actionDispatched) {
          sagaMonitor.actionDispatched(action);
        }
       console.log(stackCount++); /* counter  that never reset back to 1 ? */
        var result = next(action); // hit reducers
        sagaEmitter.emit(action);
        return result;
      };
    };
```

Is it expected that in the server-side execution (using nextjs), this counter will never reset back to 0 ? Also this recursion doesn't seem to happen in browser (I got no console output of the counter in browser)

Thanks!

**Comment by hendywijaya** [comment]
Hi @Andarist 

I've managed to avoid the issue by raising the v8 stack size when running my application. It seems that the default size is too low.

However, I'm still investigating on the recursion max call stack error. Can you please enlighten me on this part of `redux-saga/lib/internal/middleware.js:67`
```
    return function (next) {
      return function (action) {
        if (sagaMonitor && sagaMonitor.actionDispatched) {
          sagaMonitor.actionDispatched(action);
        }
        var result = next(action); // hit reducers
        sagaEmitter.emit(action);
        return result;
      };
    };
```

When will those two recursion expected to end ?

Thanks for your awesomeness!

**Comment by Andarist** [comment]
I couldnt yet found time to debug your repro, so sorry for that.

> When will those two recursion expected to end ?

What do you mean by that? This part just pass action to next middleware (most likely reducer) & emits the action to saga's internals so it can resolve pending `take`s

**Comment by hendywijaya** [comment]
Hi @Andarist no worries, I'm trying to debug and log more information about this.

The error message suggests that a max call stack has been exceed. on these lines of code:
RangeError: Maximum call stack size exceeded
    at /node_modules/redux-saga/lib/internal/middleware.js:68:23
    at /node_modules/redux-saga/lib/internal/middleware.js:72:22

I've managed to avoid / suppress the error by increasing the v8 stack size. Would this be the required setting to safely run a server side rendered redux saga application?

**Comment by JulianKingman** [comment]
I'm getting this error as well. A `takeLatest` in my root saga invokes a saga that yields to a promise, the result of which is `put` to a redux action, and causes the callstack error.

Simplified code:
```javascript
function * root () {
  takeLatest(SyncTypes.SYNC_START, startSync)
}

function * startSync (action) {
  // promise returns object
  const device = yield scanAndConnect()
  console.log('got device', device)
  // callstack error at below
  yield put(SyncActions.deviceConnected(device))
}

const deviceConnected = (state, ({device})) => {
  // using immutable
  return state.merge({device})
}
```

Any ideas?

**Comment by Andarist** [comment]
@JulianKingman posted code is not enough to judge what might be the issue here

**Comment by hendywijaya** [comment]
Hi @JulianKingman 

Can you confirm you have the verbatim error message as:
```
RangeError: Maximum call stack size exceeded
    at /node_modules/redux-saga/lib/internal/middleware.js:68:23
    at /node_modules/redux-saga/lib/internal/middleware.js:72:22
```

Also, please share more information about your application, what other modules are you using primarily, etc.

Can you replicate this issue easily, or is this something that happen intermittently ? And following my dirty solution, does increasing your v8 stack-size prevent such error ?

**Comment by Andarist** [comment]
@hendywijaya I've tried to run `siege` on ur repo but you have not included `urls.txt` in the repository

**Comment by hendywijaya** [comment]
Hi @Andarist 

sorry minor typo, the correct filename is `url.txt`, thus you can run the siege as follows:
`siege -c 50 -i -f url.txt`

Thanks!

**Comment by Andarist** [comment]
You cannot share `middleware` array like [this](https://github.com/hendywijaya/redux-maxcallstack/blob/c02b481abf2744d55339aede6a54a78eb4249b3c/src/Shared/Redux/CreateStore.js#L26) and mutate it later. You are running this on the server and with each created store (once per request I suppose) you just push & push duplicated of your middlewares.

You have to move those into the `createStore` closure. You shouldn't also share `sagaMiddleware` like this, you should move it into the closure too, each store should get its own instance of `sagaMiddleware`.

**Comment by hendywijaya** [comment]
Hi @Andarist 

Thanks for pointing that out! Apparently, yes that exactly is the issue!
Sorry for all the hassle just for a scoping issue!

Solved!

**Comment by Andarist** [comment]
No problem, I'm glad we have figured it out :)
