### ISSUE TITLE
Problem using callbacks

### ISSUE THREAD

**Issue by farzadmf** [redux-saga/redux-saga#1360]
Hi,

I have a situation where I have a function (named `onGetCameras`) that accepts a callback function (e.g., `getCamerasSuccess`); the intention is to call `onGetCameras` (which is an external function), which, does an AJAX call, and upon completion, calls `getCamerasSuccess`, passing the result it received.

What I have is something like this:

```ts
// My 'actionCreators' variable is a reference to create my actions
function* getCamerasSaga(action: action.GetCameras) {
  const { onGetCameras } = action;
  
  const getCamerasSuccess = function*(response: GetCamerasResponse) {
    console.log('SUCCESS', response);
    yield put(actionCreators.getCamerasSuccess(response);
  }
  
  yield put(actionCreators.getCamerasStart());
  
  yield call(onGetCameras, getCamerasSuccss);
}

export function* watchCamera() {
  yield takeEvery(ActionTypes.GetCameras, getCamerasSaga);
}
```

I can't figure out why it's not going into my `getCamerasSuccess` function: I never see my `console.log` message inside of that function

But, if I change my success callback to be a normal function, e.g.:

```ts
const getCamerasSuccess = (response: GetCamerasResponse) => {
  console.log('RESPONSE', response);
}

```

I can see that I'm receiving my response, but, as I mentioned, using the generator function, it seems that it never goes inside of that function.

Can you please help me with this matter?

**Comment by Andarist** [comment]
A generator function is special kind of function - it doesn't "run" immediately when it gets invoked, but rather return an iterator. It's up to the caller to handle this case and iterate over the returned iterator with `.next()`. But anyway your `onGetCameras` won't be able to call `getCamerasSuccess` meaningfully, because effects are just objects that have to be interpreted by `redux-saga` runtime - this means that it's redux-saga which should always be responsible for calling your generators/iterators (it glues all of this together).

Why won't you just do this?
```js
const response = yield call(onGetCameras);
console.log('SUCCESS', response);
yield put(actionCreators.getCamerasSuccess(response);
```

**Comment by farzadmf** [comment]
Thanks for the reply; your suggestion would work if `onGetCameras` is a `Promise`, but when I have to manually specify my two callbacks to it, then I need to define those functions and somehow call them

**Comment by Andarist** [comment]
Could u give an example os the two callbacks situation?

**Comment by farzadmf** [comment]
Thank you for your reply, I asked the question on SO and I got an answer, and it turns out that I can use `cps` to work with callbacks,

[Here's the link to the question](https://stackoverflow.com/questions/49200775/issue-when-using-callbacks-in-redux-saga)
