### ISSUE TITLE
Wait for a task to be finished with success, error or cancelled

### ISSUE THREAD

**Issue by klis87** [redux-saga/redux-saga#1362]
I have a following saga:
```js
function* cancelTaskOnAction(actionType, task) {
  const { abortingAction, taskFinished } = yield race({
    abortingAction: take(actionType),
    taskFinished: join(task), // or task.done,
  });

  if (abortingAction) {
    console.log('lets abort this task and exit');
    yield cancel(task);
  } else {
    console.log('task finished or has been cancelled from somewhere else, so there is no need to wait for actionType anymore, lets exit to free memory');
  }
}
```

The problematic part is `taskFinished: join(task)`, it works when task finished either with ok response or an error, but `taskFinished` will never win this race if task was cancelled, for example by `takeLatest` somewhere. The saga will hang on `take(actionType)`, which is not good for memory.  Is this a bug or this is intentional? Is it possible to add an effect to my race like `taskAborted`?

I am using Redux-Saga v0.16.0

**Comment by Andarist** [comment]
joining a cancelled task cancels a joiner (at least it should), does ur `cancelTaskOnAction` really hangs unresolved when `task` gets cancelled? Could u provide a repro on something like codesandbox.io ?

**Comment by klis87** [comment]
It seems so, as after `task` is cancelled, this saga will hang until `take(actionType)` is fired. I will create a demo soon, I hope I will manage it today.

**Comment by klis87** [comment]
I prepared demo: https://codesandbox.io/s/73qo3w8096

It looks like we have 2 problems, when `join` is used in `race`, when task finishes normally, it will win, but `winner` object won't contain winner's key. 2nd problem, when task is cancelled somewhere else, this saga will still run, demo shows 2 cases:
- 1st case - just click `Start new worker`.
- 2nd case - click `Start new worker` and then within 5s `Stop all workers`

**Comment by Andarist** [comment]
1. the winner has `taskStopped` key, it's value just happens to be `undefined` because `worker` doesn't return anything
2. seems like a problem, gonna look into how it is handled internally and what we can do to fix this. Just to clarify - in your eyes `workerAborter` should get cancelled based on regular cancellation propagation  to joiners rule, right?

**Comment by klis87** [comment]
re 1) My bad :)
re 2) When I raised this issue, when `task` is cancelled, I expected `taskFinished` to be the winner. I thought this is more logical, because as mentioned in docs : 
> Cancellation propagates downward

But after more thinking, when you `yield call(saga)` and `saga` will be cancelled, then caller would be cancelled too.  In the contrary to errors  `yield fork(task)`. And because `join` is like converting `fork` to `call`, I think that joining a task which gets aborted should abort the joiner - and we could always use `try` `finally` and `yield cancelled()` when necessery, so I think this is the best approach. Although maybe wrapping `join` inside `race` should "protect" saga yielding `race`? :) I think it shouldn't, but thats a tough one :)

**Comment by Andarist** [comment]
https://github.com/redux-saga/redux-saga/pull/1493 got merged in, this should "resolve" ur issue by aligning the behaviour with `all` - `END` is going to cancel the saga waiting on `take`
