### ISSUE TITLE
Is there any way to handle error while take effect is pending

### ISSUE THREAD

**Issue by alexeymolchan** [redux-saga/redux-saga#1367]
```js
try {
   const timeout = setTimeout(() => {throw new Error('Error')}, 3000);
   yield take('SOME_ACTION');
   clearTimeout(timeout);
 } catch(e) {
   console.log('error catched')
 }
```

An error thrown after 3 sec if take effect doesn't resolved, but i can't catch an error.

Is it even possible to catch error in my case?

**Comment by GaelS** [comment]
I guess the `race` effect will fit your needs : https://redux-saga.js.org/docs/advanced/RacingEffects.html
