### ISSUE TITLE
Why fsmIterator?

### ISSUE THREAD

**Issue by NeoLegends** [redux-saga/redux-saga#1368]
Hey!

When reading the source code of redux-saga, I stumbled about the fsmIterator approach you're using to implement some of the effects. May I ask why you chose to go that way and implement the state machine yourself instead of using ES6 generators and `yield`?

Thanks!

**Comment by Andarist** [comment]
Hi @NeoLegends! Hope you enjoy reading the source, if you have any questions you can always reach out to me. If you have any thoughts on how it could be improved (both the API/behaviour or the implementation) I would gladly hear you out and ofc you can always make a PR 😉 

Back to the original question - reason is quite simple, with poor-ish es6+ support (many people still need to support IE10) we didn't want to force people to transpile `redux-saga` source to use it. Most people usually ignore `node_modules` in bundlers' rules.

**Comment by NeoLegends** [comment]
I'd like to have something like a combineLatest effect!

It would allow listening to multiple action types and would return an object like the one returned from `race` as soon as its got one action of every type. If it encounters one action multiple times it'll take the latest one.

**Comment by Andarist** [comment]
> It would allow listening to multiple action types and would return an object like the one returned from race as soon as its got one action of every type. If it encounters one action multiple times it'll take the latest one.

This would match rx semantics, right?

> because we cannot return anything custom through yield.

Not sure if I follow could u explain?

The idea seems good, I always wanted to implement more built-in helpers. Do you want to work in this?

**Comment by NeoLegends** [comment]
> This would match rx semantics, right?

Exactly.

> Not sure if I follow could u explain?

As far as I currently understand redux-saga, I cannot have true user-defined effects that return data through the yield like:

```js
// Not possible to return data through yield from the library user perspective today
// because combineLatest is just a library function that uses `fork` and not a real effect
//                         ⇣
const { action1, action2 } = yield combineLatest({
  action1: 'DO_SOMETHING_1',
  action2: 'DO_SOMETHING_2',
});

// use action1, action2
```

Instead, as a user, I must always pass a saga as parameter that is invoked / forked with the data like:

```js
yield combineLatest({
  action1: 'DO_SOMETHING_1',
  action2: 'DO_SOMETHING_2',
  function*({ action1, action2 }) {
    // use action1, action2
  },
});

// cannot use action1, action2 here :/
```

> The idea seems good, I always wanted to implement more built-in helpers. Do you want to work in this?

Sounds good. :) I'll see what I can do.

**Comment by Andarist** [comment]
You can create your custom effects, as long as they are just wrappers around what we offer today.

But as you have observed, for a thing like `combineLatest` you must encapsulate handler in the effect. There is a problem with your first snippet - it assumes that u'd like to handle result of the `combineLatest` at the yield site, but that way we wouldn't be able to implement easily long-running effects (like `combineLatest`). Generators are kinda state machines and by advancing from `yield combineLatest(...)` state to another we wouldn't be able to resolve `combineLatest` again when new action would happen.

**Comment by NeoLegends** [comment]
> it assumes that u'd like to handle result of the combineLatest at the yield site, but that way we wouldn't be able to implement easily long-running effects (like combineLatest). Generators are kinda state machines and by advancing from yield combineLatest(...) state to another we wouldn't be able to resolve combineLatest again when new action would happen.

I don't think I understand what you mean. Why can't the `combineLatest`-effect not resolve when its got all the actions it needs?

Once `combineLatest` resolves there should be no more listening for further actions? It's like "Please give me this set of actions and wait until you've got at least one of every type." It's like a `take` for multiple actions, but with an `AND` behavior instead of the `OR`-behavior`take` works like today.

**Comment by Andarist** [comment]
Oh, I get it. Thought it should be long-lived and resolve each time new action happens after its resolved for the first time.

I think (not sure though) that it should be possible to do what u want, u'd have to use internally `fork` and return `join(forked)` to the yielder.

**Comment by NeoLegends** [comment]
I've already got it as library implementation. It's just that the semantics aren't nice because I have to pass the rest of the saga as parameter to the effect, which introduces problems with cancellation and so on and so forth. :)

> I think (not sure though) that it should be possible to do what u want, u'd have to use internally fork and return join(forked) to the yielder.

Great! I'll see what I can do.

**Comment by restrry** [comment]
seems to be answered
