### ISSUE TITLE
Throttle not functioning consistently in all app states

### ISSUE THREAD

**Issue by garyhogarth** [redux-saga/redux-saga#1370]
Hi,

We are working on a new app and have redux and redux-saga at the core. Our app requires frequent location updates so we have a LOCATION_CHANGED action being dispatched every 500ms. We have API requests that we also want to make triggered by this action so in our saga we have.

`yield throttle(3000, LOCATION_CHANGED, requestReverseGeocodeData);`

This function in turn dispatches an API_REVERSE_GEOCODE_REQUEST action.

Now this works 99% of the time. Every 3 seconds we get 6 LOCATION_CHANGED actions and 1 API_REVERSE_GEOCODE_REQUEST action. However we have found an edge case. On an Android device when the app is placed in the background we continue to get the LOCATION_CHANGED actions from out React Native code however the API_REVERSE_GEOCODE_REQUEST action is never dispatched.

Changing the throttle to takeLatest works perfectly we get 1 API_REVERSE_GEOCODE_REQUEST for every LOCATION_CHANGED action.

Any help or guidance would be appreciated.

**Comment by Andarist** [comment]
Are you sure this happens on a real device and not only on RN simulator? The latter (not sure about real devices) has known issues around timers and `throttle` has to use `setTimeout` under the hood.

**Comment by garyhogarth** [comment]
Yes this is on a real device with the packager running on my local machine.

**Comment by garyhogarth** [comment]
Doing some tests, it could very well be to do with setTimeout/setInterval being called properly with RN on android. 

`setInterval(() => console.log('test'), 1000);` stops firing the second I put the app into the background.

**Comment by Andarist** [comment]
Need to close this as not actionable on our part. I think there are some workarounds for this on RN, but you'd have to search for them on your own as I have no experience with that platform. Feel free to comment if you find the solution for this!
