### ISSUE TITLE
Worker saga not getting called on react native

### ISSUE THREAD

**Issue by TechyTimo** [redux-saga/redux-saga#1375]
I am trying to handle async actions with redux saga on a simple app. It calls an api to fetch some tweets from a local proxy server. 
I can tell that the watcher saga is getting called but the worker saga is not by checking the logs.
I can also tell that the action is being dispatched and the reducers are getting fired using logs as well.

Here is my code - https://github.com/TechyTimo/react-native-tweets

**Comment by Andarist** [comment]
Please use 
```js
yield takeEvery(SEARCH_FOR_TWEETS_REQUESTED, fetchTweets);
```
instead of
```js
yield* takeEvery(SEARCH_FOR_TWEETS_REQUESTED, fetchTweets);
```

**Comment by TechyTimo** [comment]
Turns out I was fetching "takeEvery" from "redux-saga/effects" instead of from "redux-saga".

**Comment by Rohithzr** [comment]
I am having this same issue on react-native
```
//rootSaga.js
import { takeEvery } from "redux-saga/effects";
export function* rootSaga() {
    yield takeEvery(LoginSagaConstants.LOGIN, userLogin)
}

//loginSaga.js
export function* userLogin(action) {
   console.log("userLogin not getting called");
   const response = yield call(LoginAPI.login, action.user);
   console.log(response);
   ...
}

//loginScreen.js
dispatch({
    type: sagaConstants.LOGIN,
    user: {
        username: "username",
        password: "password",
        robottest : "robottest"
    }
});
```

**Comment by oneEyedSunday** [comment]
Having same problem

**Comment by objectivesheep** [comment]
Same here...

**Comment by restrry** [comment]
folks, would you mind adding  runable case to reproduce the problem as the original issue author did?

**Comment by oneEyedSunday** [comment]
Well I was using action creator functions, found out I wasnt calling dispatch

**Comment by Rohithzr** [comment]
My issue was resolved, it was some error on my part (as far as i can remember) if someone needs a working code example, let me know (i am not pasting the codes at the moment as I did not find any real issues with the library itself)

For me this issue can be closed.

**Comment by mostafaebrahimi** [comment]
Same issue...

**Comment by johnnyBira** [comment]
Same issue.

**Comment by mostafaebrahimi** [comment]
@johnnyBira May you show us `watcher registration`  using saga middleware and more?

**Comment by johnnyBira** [comment]
@moatafaebrahimi it was my mistake, now working according to the edit adove.

I’m just curious, if using Redux 4, is it adviced to update to the beta of redux-saga? Both latest and beta seam to be working fine in my case, but I was just thinking sine the latest Redux is using the new context API etc.

**Comment by Andarist** [comment]
Contex api has nothing to do with redux-saga, you can use beta safely.
