### ISSUE TITLE
Organizing sagas into separate files and calling functions across files?

### ISSUE THREAD

**Issue by Slapbox** [redux-saga/redux-saga#1380]
Is there a good way to do this that I'm overlooking? It seems like the only ways to do this are rather hacky, either exporting the function you want to call from the file, in which case the file it resides in needs to reference is with `modules.exports.functionName()` or to use channels and put calls.

This works fine, unless you need to wait for the function to return some value, which put can't do to my knowledge.

Is there some better way I'm overlooking?

**Comment by Andarist** [comment]
Is there any downside of importing sagas to other files? IMHO it's just the same problem of organizing stuff as with "regular" functions.

**Comment by Slapbox** [comment]
Yes I suppose not. It occurred to me later that day that I could put all the generator functions into files and import those into the saga starting files/functions.
