### ISSUE TITLE
Deciding if a fork should be run dynamically?

### ISSUE THREAD

**Issue by Slapbox** [redux-saga/redux-saga#1381]
Is there a way to do this compatible with ES6 imports? For example, wanting to run a fork only if a user is logged in. It works fine to do an `if`statement, but the if is only run at startup. If the user's logged in state changes, the sagas for a logged in user will still be run.

**Comment by Slapbox** [comment]
I should note I have something like 20 conditional effects for this case. The only solution I've seen is to set up an individual watcher for every effect. Surely there's something better?

**Comment by Andarist** [comment]
You'd have to share some example code to get better help. If you need conditional logic you typically branch ur sagas based on dispatched actions (with help of `take`) or based on selected state (with help of `select`). You can also build some customized strategies based on all effects (which tend to be quite low level)

**Comment by Slapbox** [comment]
Thanks for your reply. So I tried something like this:

```
export default function* rootSaga() {
  while (true) {
    const task = yield take();
    const userIsLoggedIn = yield select(getUserStatus);
    if (userIsLoggedIn) {
      yield all([
        fork(syncNotesSaga),
        fork(firebaseFileIndex),
        fork(firebaseUserParams),
        takeLatest(types.NOTE_TEXT_UPDATE, handleUpdateNoteText),
        takeEvery(types.NOTE_ADD, updateNoteFirebase),
      ]);
    }
  }
}
```

Unfortunately this led to repeat runs of sagas and still did not allow for dynamically changing whether or not these should be run. Even when `userIsLoggedIn` was false and it showed it was the case, the sagas referenced under the `yield all` still ran.

I understand I could use take and create a watcher and runner for each task, but in reality there are more like 20 tasks in the yield all, not just the 5 shown here, which seems like it would quickly get very unwieldy. Is there some better option available? Sorry to clutter up the issues section with this. Someone could make good money offering a comprehensive tutorial on `Redux-Saga`

**Comment by Andarist** [comment]
Would something like this work for you?
```js
const loggedInTasks = all([
  fork(syncNotesSaga),
  fork(firebaseFileIndex),
  fork(firebaseUserParams),
  takeLatest(types.NOTE_TEXT_UPDATE, handleUpdateNoteText),
  takeEvery(types.NOTE_ADD, updateNoteFirebase),
])

export default function* rootSaga() {
  while (true) {
    if (!(yield select(getUserStatus))) {
      yield take(types.LOGGED_IN)  
    }
    
    const activeTasks = yield loggedInTasks
    yield take(types.LOGGED_OUT)
    yield cancel(...activeTasks)
  }
}
```

**Comment by Slapbox** [comment]
That is some beautiful code that not only works wonderfully, but has helped me to better understand the fundamentals of flow control with redux-saga.

I know you get a lot of questions and I see you take the time to respond to them all. Thanks very much! I can't tell you how much I appreciate it.
