### ISSUE TITLE
Preventing duplicate code with `Join`, or something else?

### ISSUE THREAD

**Issue by Slapbox** [redux-saga/redux-saga#1382]
I have some effects to process that are applicable to all users, but for certain users levels I need to do some extra processing before sending the results to the same place. I have dozens of these throughout my application and I'm wondering how to structure things in a more sustainable way.

Here's what I have currently (but x20 throughout my application):

```
function* updateObjectStart({ objectToUpdate }) {
  try {
    const shouldDoExtraThings = yield select(getShouldDoExtraThings);
    if (shouldDoExtraThings) {
      yield call(updateObjectExtra, { objectToUpdate });
    } else {
      yield call(updateObject, { objectToUpdate });
    }
  } catch (err) {
    log.error(err);
  }
}

function* updateObjectExtra({ objectToUpdate }) {
  try {
    //  Do some extra processing on the object
    yield put(actions.updateObject({ ...objectToUpdate }));
  } catch (err) {
    log.error(err);
  }
}

function* updateObject({ objectToUpdate }) {
  try {
    yield put(actions.updateObject({ ...objectToUpdate }));
  } catch (err) {
    log.error(err);
  }
}
```

In the end, both paths lead to a call to `updateObject`. I suspect `Join` is the way to handle these, but I can't find any clear examples of how to use it. I think I understand what it does, but as far as actually using it, I'm lost. Is there some higher level way I can handle this without duplicating so much code? I'm sure there is, but right now I'm not sure what it is.

**Comment by Andarist** [comment]
To use `join` effectively u need to sequence ur sagas using `fork`s rather than with message passing (combination of put+take). It's useful if u need to start a task, you need to wait on its result too AND you need to perform some logic in between of those 2. 

I understand that given code is simplistic on purpose at the moment, but such simple case can be modelled with a simple `call`.
```js
function* updateObjectStart({ objectToUpdate }) {
  try {
    const shouldDoExtraThings = yield select(getShouldDoExtraThings);

    if (shouldDoExtraThings) {
      yield call(updateObjectExtra, { objectToUpdate });
    }
    
    yield call(updateObject, { objectToUpdate });
  } catch (err) {
    log.error(err);
  }
}
```

If you have some more complex logic that would need using `join` then this could look more like this
```js
function* updateObjectStart({ objectToUpdate }) {
  try {
    const shouldDoExtraThings = yield select(getShouldDoExtraThings);

    if (shouldDoExtraThings) {
      const task = yield fork(updateObjectExtra, { objectToUpdate });
      // ... more processing
      const result = yield join(task)
      // maybe do smth with `result`?
    }
    
    yield call(updateObject, { objectToUpdate });
  } catch (err) {
    log.error(err);
  }
}
```
