### ISSUE TITLE
Using call effect with function name causes flow type errors

### ISSUE THREAD

**Issue by dmitry-zakablukov** [redux-saga/redux-saga#1384]
Good day!

We are using flow for type checking. And the following code causes type errors:
``yield call([object, 'pop'])``

The only way now for v0.16.0 is using the following code:
``yield call([object, object.pop])``

Can you please add a flow type for the call effect with a function name?

Full error is listed below:

    Cannot call `call` because:
     - Either array literal [1] is incompatible with function type [2] in type argument `Fn`.
     - Or array literal [1] is incompatible with function type [3] in type argument `Fn`.
     - Or array literal [1] is incompatible with function type [4] in type argument `Fn`.
     - Or array literal [1] is incompatible with function type [5] in type argument `Fn`.
     - Or array literal [1] is incompatible with function type [6] in type argument `Fn`.
     - Or array literal [1] is incompatible with function type [7] in type argument `Fn`.
     - Or array literal [1] is incompatible with function type [8] in type argument `Fn`.
     - Or string [9] is incompatible with function type [10] in type argument `Fn`.
     - Or string [9] is incompatible with function type [11] in type argument `Fn`.
     - Or string [9] is incompatible with function type [12] in type argument `Fn`.
     - Or string [9] is incompatible with function type [13] in type argument `Fn`.
     - Or string [9] is incompatible with function type [14] in type argument `Fn`.
     - Or string [9] is incompatible with function type [15] in type argument `Fn`.
     - Or string [9] is incompatible with function type [16] in type argument `Fn`.

       test.js:67:23
        67|                 yield call([object, 'pop']);
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^

    References:
       test.js:67:28
        67|                 yield call([object, 'pop']);
                                       ^^^^^^^^^^^^^^^^^^^^^ [1]
       flow-typed/npm/redux-saga_v0.16.x.js:402:13
       402|     <R, Fn: () => R>(fn: Fn): CallEffect<null, Fn, []>,
                        ^^^^^^^ [2]
       flow-typed/npm/redux-saga_v0.16.x.js:403:17
       403|     <R, T1, Fn: (t1: T1) => R>(fn: Fn, t1: T1): CallEffect<null, Fn, [T1]>,
                            ^^^^^^^^^^^^^ [3]
       flow-typed/npm/redux-saga_v0.16.x.js:404:21
       404|     <R, T1, T2, Fn: (t1: T1, t2: T2) => R>(
                                ^^^^^^^^^^^^^^^^^^^^^ [4]
       flow-typed/npm/redux-saga_v0.16.x.js:409:25
       409|     <R, T1, T2, T3, Fn: (t1: T1, t2: T2, t3: T3) => R>(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [5]
       flow-typed/npm/redux-saga_v0.16.x.js:415:29
       415|     <R, T1, T2, T3, T4, Fn: (t1: T1, t2: T2, t3: T3, t4: T4) => R>(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [6]
       flow-typed/npm/redux-saga_v0.16.x.js:422:33
       422|     <R, T1, T2, T3, T4, T5, Fn: (t1: T1, t2: T2, t3: T3, t4: T4, t5: T5) => R>(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [7]
       flow-typed/npm/redux-saga_v0.16.x.js:438:11
       438|       Fn: (t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6) => R
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [8]
       test.js:67:35
        67|                 yield call([object, 'pop']);
                                              ^^^^^^^^^^^^^ [9]
       flow-typed/npm/redux-saga_v0.16.x.js:450:18
       450|     <Ctx, R, Fn: () => R>(cfn: [Ctx, Fn]): CallEffect<Ctx, Fn, []>,
                             ^^^^^^^ [10]
       flow-typed/npm/redux-saga_v0.16.x.js:451:22
       451|     <Ctx, R, T1, Fn: (t1: T1) => R>(
                                 ^^^^^^^^^^^^^ [11]
       flow-typed/npm/redux-saga_v0.16.x.js:455:26
       455|     <Ctx, R, T1, T2, Fn: (t1: T1, t2: T2) => R>(
                                     ^^^^^^^^^^^^^^^^^^^^^ [12]
       flow-typed/npm/redux-saga_v0.16.x.js:460:30
       460|     <Ctx, R, T1, T2, T3, Fn: (t1: T1, t2: T2, t3: T3) => R>(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [13]
       flow-typed/npm/redux-saga_v0.16.x.js:466:34
       466|     <Ctx, R, T1, T2, T3, T4, Fn: (t1: T1, t2: T2, t3: T3, t4: T4) => R>(
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [14]
       flow-typed/npm/redux-saga_v0.16.x.js:481:11
       481|       Fn: (t1: T1, t2: T2, t3: T3, t4: T4, t5: T5) => R
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [15]
       flow-typed/npm/redux-saga_v0.16.x.js:499:11
       499|       Fn: (t1: T1, t2: T2, t3: T3, t4: T4, t5: T5, t6: T6) => R
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [16]

**Comment by Andarist** [comment]
As you can see this repository has no flow typings, those live in `flow-typed` repo and you should report/fix it there. cc @Alxandr

**Comment by Alxandr** [comment]
I didn't add typings for those cause it would have been really annoying to do so. String-based typing is always tricky. I think it's possible, but I'm not sure how you'd do it.

**Comment by Andarist** [comment]
> As you can see this repository has no flow typings, those live in flow-typed repo and you should report/fix it there
