### ISSUE TITLE
eventChannel doesn't emit outside listeners

### ISSUE THREAD

**Issue by hnordt** [redux-saga/redux-saga#1385]
I'm building a custom routing solution and I needed to write this:

```js
const createBrowserHistoryChannel = () =>
  eventChannel(emit => {
    const unlisten = browserHistory.listen(location => emit(location.pathname))
    emit(browserHistory.location.pathname)
    return unlisten
  })
```

It starts a listener so whenever the user navigates to another page I'll emit the new pathname. Also I'm emitting the current pathname, because `browserHistory.listen` doesn't emit the current pathname.

The code above won't work, but this will work:

```js
const createBrowserHistoryChannel = () =>
  eventChannel(emit => {
    const unlisten = browserHistory.listen(location => emit(location.pathname))
    setTimeout(() => emit(browserHistory.location.pathname), 0)
    return unlisten
  })
```

To make it work I needed to schedule the emit() to be executed in the end of the javascript execution queue.

I've created a JSBin to demonstrate the issue: https://jsbin.com/xowiciyeru/edit?js,console. Please note the line `/!\ BUG: THIS WON'T WORK`.

I'm wondering... Am I missing something or it's a bug?

**Comment by Andarist** [comment]
`eventChannel` is "hot" - if there is no subscriber at given moment emitted msg has to be dropped.

To solve this you can introduce buffering though:
```js
import { buffers } from 'redux-saga'

const createBrowserHistoryChannel = () =>
  eventChannel(emit => {
    const unlisten = browserHistory.listen(location => emit(location.pathname))
    emit(browserHistory.location.pathname)
    return unlisten
  }, buffers.expanding())
```

**Comment by hnordt** [comment]
@Andarist thank you!
