### ISSUE TITLE
Tracking duration associated with an action

### ISSUE THREAD

**Issue by dsanders1234** [redux-saga/redux-saga#1391]
I have an action that has analytics metadata information in its meta block (Flux Standard Action).  I'd like a middleware way of intercepting these actions and timing the duration of the worker(generator function) associated with their pattern(action type string).  I'd like the developer to not have to add anything other than meta information to their Actions.  This timing information would be sent to third party analytics software (like google analytics).  

For instance:

```
MyActions.ts:

export const FETCH_INITIAL_DATA: string = 'FETCH_INITIAL_DATA';
export const fetchInitialDataActionCreator: ActionCreator<ActionWithEventAnalytics> = () => ({
   type: FETCH_INITIAL_DATA,
   meta: {
      analytics: {
         category: "My Category" // Do not localize this!
      }
   }
});


MySagas.ts:

function* fetchInitialDataSaga() {
   yield takeLatest(MyActions.FETCH_INITIAL_DATA, fetchData); // I want to track the duration of fetchData
}

function* fetchData() {
   const response: Summary = yield call(MyAPI.fetchSummary);
   yield put(MyActions.fetchInitialDataSuccessActionCreator(response));
}

export default function* rootSaga() {
   yield all([
      fetchInitialDataSaga(),
      ...
   ]);
}
```

**Comment by Andarist** [comment]
U might be able to achieve this with `effectMiddlewares` feature which is available in v1-beta. Not sure though if it's possible at the moment. I'd go with some higher order saga and wrap sagas that I'd like to track with it.
