### ISSUE TITLE
React Native and Redux Saga issue with ListView component

### ISSUE THREAD

**Issue by Taimoormk** [redux-saga/redux-saga#1392]
I am having bit of wrinkle in my React Native project. I have successfully deployed Redux Saga into the project and got my required data into the reducers. I then used mapStateToProps to bring the data back into my React component. The data has successfully arrived into the component. However, the problem appears when I pass the data(array) into `dataSource.cloneWithRows(launchAppReducer.data)` it doesn't process the data as it should be in order to render it on the UI.

Following is the code I am using and I also have attached my console.log() screenshot if it helps to get down to the problem here.
<img width="867" alt="screen shot 2018-04-10 at 18 51 48" src="https://user-images.githubusercontent.com/27800340/38596671-484580f4-3d6c-11e8-9856-51659d2e1e0a.png">

Following is the code;

```
class Mobile extends Component {

      constructor(props) {
        super(props);
        let { readPostsAction } = this.props;
        readPostsAction();
      }

      render() {
        let { data } = this.props;
        return (
          <Container>
            <ListView
              dataSource={data}
              renderRow={
                (rowData) =>
                  <View>

                  </View>
              }
            />
          </Container>
        );
      }
    }

    const dataSource = new ListView.DataSource({
      rowHasChanged: (r1, r2) => r1 !== r2
    });

    function mapStateToProps({ launchAppReducer }) {
      return {
        isLoading: launchAppReducer.isLoading,
        data: dataSource.cloneWithRows(launchAppReducer.data)
      }
    }

    export default connect(mapStateToProps, { readPostsAction: actions.readPostsAction })(Mobile);
```

I have used the same logic with redux and redux thunk - the code was working fine.

**Comment by Andarist** [comment]
Sorry but this place is about redux-saga issues & your problem looks like a developer mistake, it's usually better to ask such questions on sites like stackoverflow.

Also your screenshot & component sample is not enough to help you here, I'd inspect what's going with `cloneWithRows` more closely on your place.
