### ISSUE TITLE
Call() Silently Kills All Sagas for an Uncaught Promise Rejection

### ISSUE THREAD

**Issue by max-winderbaum** [redux-saga/redux-saga#1395]
When we pass a promise into `call()` that gets rejected asynchronously, then the `onError` function passed into `createSagaMiddleware` does not ever fire and all sagas stop working.

If the `call()` is wrapped in a `try/catch` block then it doesn't kill all the sagas, but we'd still love it if all errors within sagas get passed into the `onError` function!

Repro: https://runkit.com/max-winderbaum/5ace4c686e1db2001293b4b4

Please let me know if there's anything else I can do to help this along! I'm also looking into how to create a PR to fix this, but I'd love some help and/or a point in the right direction.

**Comment by Andarist** [comment]
This is most likely caused by rejecting with `undefined` instead of an actual error. Is there any reason why this happens in your app? It would be good to guard against that in redux-saga though - PRs are welcome.
