### ISSUE TITLE
Errors not throwing to console when using select

### ISSUE THREAD

**Issue by akinnee** [redux-saga/redux-saga#1397]
If I have an error in a selector and I `const something = yield select(getSomething);`, the error does not show up in the console and the effect stops. I'm left wondering what's wrong until I add a try/catch to see what happened.

Is this normal or am I doing something wrong?

Example of a broken selector:
```
function getSomething() {
  const foo = 'not an object';
  return foo.bar;
}
```

**Comment by Andarist** [comment]
Could u replicate the issue? Quick test on codesandbox works fine for me
<img width="885" alt="screen shot 2018-04-14 at 12 36 39" src="https://user-images.githubusercontent.com/9800850/38767397-9d1995f4-3fe0-11e8-8415-00bc26295a73.png">

**Comment by akinnee** [comment]
Sorry for the late reply. It looks like you're using this tool: https://github.com/clarketm/saga-monitor Right?

**Comment by akinnee** [comment]
You mean like this? https://github.com/redux-saga/redux-saga/blob/dfc38612e71f6e1a53c8aeda37dcb3799096408a/examples/sagaMonitor/index.js

Thanks.

**Comment by akinnee** [comment]
We figured out that we were just missing a log. When creating the middleware, an onError function must be provided.

```
createSagaMiddleware({
    onError,
    emitter,
  });
```

Once we added that it was just a simple console log.

```
const onError = (err) => {
    console.error(err);
  };
```
