### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by AnnatarHe** [redux-saga/redux-saga#1405]
I notice that the latest stable version was released on Oct 16, 2017.  It's been half an year.
And recently I really need `takeLeading`(#1332 ), maybe someone else need the operator too.

Should we release a new version?

**Comment by dhanala89** [comment]
Hi this is not released yet. Can you please let us know what the status is?

**Comment by inexplicablysane** [comment]
@Andarist I also would love to have takeLeading.

**Comment by Andarist** [comment]
I've release a new version just now.

**Comment by dhanala89** [comment]
thanks mate but this is still an issue even if i upgrade to your beta1 release. I get 

[flow] Cannot import `takeLeading` because there is no `takeLeading` export in `redux-saga/effects`.

**Comment by Andarist** [comment]
@dhanala89 flow typings are not part of this repository. They are maintained by the community, preferably you should add typing for `takeLeading` in flow-typed repo
