### ISSUE TITLE
how to use redux-saga with async callback function

### ISSUE THREAD

**Issue by OriAmir** [redux-saga/redux-saga#1406]
I want to use redux-saga yield call effect with async function that get the result of this function is call back. ( in this case fingerprintjs but it's general case)

This is the async function I want to exactue :

`new Fingerprint2().get(function(result, components) {
console.log(result);
console.log(components); })`
The issue that I want to execute this function via saga , but it's always stuck on yield call.

I try many ways :

` import Fingerprint2 from 'fingerprintjs2';
   const func = new Fingerprint2().get;
   const res = yield call(func);`

Also try like this:

`import Fingerprint2 from 'fingerprintjs2';
const func = new Fingerprint2().get;
const a = yield call(func, (fingerprint, result) => ({
  fingerprint,
  result
}));
`

And like this:

`import Fingerprint2 from 'fingerprintjs2';
let res = yield call(new Fingerprint2().get(), (fingerprint, result) => ({
  fingerprint,
  result
}));`

Any one know about idea or some way to acheive my goal ?

Thanks!

**Comment by shinima** [comment]
One solution for this is that wrapping this function with Promise, and then yield this promise in saga. Another way may be using `cps` effects, but I'm not sure about it.

**Comment by OriAmir** [comment]
@shinima  I try with cps but it's looks the same.
Can you give me example or something I can use ? no one use thing like that with saga never?

tnx!

**Comment by hoodwink73** [comment]
Hey @OriAmir 

I have a question. Is `new Fingerprint2().get()` synchronous? What does the `get` return?

**Comment by Andarist** [comment]
This should work too
```
const { result, components } = yield call(() => new Fingerprint2().get((result, components) => ({ result, components })))
```

**Comment by Andarist** [comment]
if its callback based it should be possible to do this
```js
const { result, components } = yield cps((err, cb) => new Fingerprint2().get((result, components) => cb({ result, components })))
```

**Comment by Andarist** [comment]
Sorry, I've made a mistake, it should actually be this:
```js
const { result, components } = yield cps((cb) => new Fingerprint2().get((result, components) => cb(null, { result, components })))
```

**Comment by shinima** [comment]
Seem that the issue is resolved. Closing it.

**Comment by DZakh** [comment]
> Sorry, I've made a mistake, it should actually be this:
> 
> ```js
> const { result, components } = yield cps(cb => new Fingerprint2().get((result, components) => cb(null, { result, components })))
> ```

Why not to use just `call` instead of misusing `cps`:
```js
const { result, components } = yield call(new Promise((resolve) => new Fingerprint2().get((result, components) => resolve({ result, components }))))
```
