### ISSUE TITLE
Bug when combining all and race effects

### ISSUE THREAD

**Issue by Havret** [redux-saga/redux-saga#1411]
I have encountered a strange situation when combining all and race effects. 

Here is the problematic code:
```
    const {
      result
    } = yield all({
      leaveSystem: yield call(UserApi.LeaveSystem),
      result: yield race({
        success: take(LEAVE_SYSTEM_REQUEST_SUCCESS),
        failure: take(LEAVE_SYSTEM_REQUEST_FAILURE)
      })
    });
```

I am calling LeaveSystem function to log out the user from the system and wait for a return value which may be Success or Failure. Return value comes through WebSocket. This code works for most of the time, but sometimes it sucks between LeaveSystem and waiting for results. It's strange because Leave system is actually called (I can check this in my back-end logs) and SuccessAction is being actually put by WebSocket Saga. 

If I reorder things a bit, it really goes crazy. :D 

```
    const {
      result
    } = yield all({
      result: yield race({
        success: take(LEAVE_SYSTEM_REQUEST_SUCCESS),
        failure: take(LEAVE_SYSTEM_REQUEST_FAILURE)
      }),
      leaveSystem: yield call(UserApi.LeaveSystem),
    });
```

Now LeaveSystem will not be called at all. 

Am I doing sth wrong or this is a bug? 

I am using the latest stable version which is v0.16.0.

**Comment by Andarist** [comment]
It's because you are not supposed to `yield` within effect combinator, effect combinators (all, race) are supposed to be yielded and be constructed from effect objects - by yielding within effect combinator definition you are effectively yielding "nested" effect instead of yielding the combinator (and ofc later yielding combinator with resolved result instead of effect object).

It should be:
```js
    const {
      result
    } = yield all({
      leaveSystem: call(UserApi.LeaveSystem),
      result: race({
        success: take(LEAVE_SYSTEM_REQUEST_SUCCESS),
        failure: take(LEAVE_SYSTEM_REQUEST_FAILURE)
      })
    });
```

**Comment by Spomsoree** [comment]
I don't quite get this. Why would you use `all` if you do not try to run multiple actions at all?

I'm in a situation where I need to run multiple actions which do an api call in the background.
I'm basically posting to two api's and I need to fire an event/action if both of the actions were successful.

```
const { result1, result2 } = yield all([
        {
            post1:   put(Actions1.postSomething()),
            result1: race({
                    failure1: take(Types1.FAILED),
                    success1: take(Types.1SUCCESS),
                },
            ),
        },
        {
            post2:   put(Actions2.postSomething()),
            result2: race({
                    failure2: take(Types2.FAILED),
                    success2: take(Types2.SUCCESS),
                },
            ),
        },
    ]);
```

Wouldn't this be the use case for the combination of `race` and `all`, or am I completely wrong there?
I'm getting `undefined, undefined`. Am I on a right track there, or did I misunderstood this post?

**Comment by Andarist** [comment]
Note how your destructuring doesnt actually match what you pass to `all`. You are passing an array to `all`, but yet you are trying to destructure `result1` & `result2` properties.

This is not the only problem though, you can't pass plain objects as array items to `all` - `redux-saga` won't dive into those objects and won't execute contained in them effects.

This would be a correct version of your code:
```js
const { result1, result2 } = yield all({
    post1: put(Actions1.postSomething())
    result1: race({
        failure1: take(Types1.FAILED),
        success1: take(Types1.SUCCESS),
    }),

    post2: put(Actions2.postSomething()),
    result2: race({
        failure2: take(Types2.FAILED),
        success2: take(Types2.SUCCESS),
    }),
})
```

But at the same time I believe it would be better if you would wrap a single put+race combination within a separate saga so you could just `call` 2 of them like this:
```js
function* post1Saga() {
    yield put(Actions1.postSomething())
    return yield race({
        failure: take(Types1.FAILED),
        success: take(Types1.SUCCESS),
    })
}

function* post2Saga() {
    yield put(Actions2.postSomething())
    return yield race({
        failure: take(Types2.FAILED),
        success: take(Types2.SUCCESS),
    })
}

// ...
const { result1, result2 } = yield all({
    result1: call(post1Saga),
    result2: call(post2Saga),
})
```

**Comment by Spomsoree** [comment]
Thank you very much. This works as expected.

I thought an array is required to run these in parallel. But of course it doesn't make any sence to expect a result out of it.
