### ISSUE TITLE
Live update Firestore documents w/ Redux Saga

### ISSUE THREAD

**Issue by Compulsor** [redux-saga/redux-saga#1412]
Hi there, 
For my internship I am trying to accomplish the live reloading of Firebase Firestore documents in a list. 
I tried to approach this functionality by making use of the Redux Saga Channel as shown underneath.

```
function* fetchAvailableGoals(action) {
    try {
        const data = yield getAvailableGoals();
        data.onSnapshot(querySnapshot => {
            var availableGoals = [];
            querySnapshot.forEach(doc => {
                availableGoals.push(doc);
            });
            goalChannel.put({
                type: FETCHING_AVAILABLE_GOALS_SUCCESS,
                availableGoals
            });
        });
    } catch (error) {
        console.log('catch error in AG_Saga');
        yield put({ type: FETCHING_AVAILABLE_GOALS_ERROR, error });
    }
}

function* watchGoalChannel() {
    while (true) {
        const action = yield take(goalChannel);
        console.log(action);
        yield put(action);
    }
}

```
The documents that I need are getting pushed into the `availableGoals` array, but unfortunately the array of documents doesn't get passed onto the class where they've got to be displayed. Nor does the console show me any updates when I add a document to the according list in Firebase Firestore.

All help is appreciated, thank you very much in advance.

**Comment by apaatsio** [comment]
I'm sorry I'm not sure where your exact problem is, but are you aware of [redux-saga-firebase](https://github.com/n6g7/redux-saga-firebase)? It makes working with Firebase a bit easier. It also has great documentation.

**Comment by Andarist** [comment]
It's unobvious from your code snippet what `goalChannel` is. Idiomatically it should be an `eventChannel`.

I'm not familiar with the firebase, so it's hard to tell if `querySnapshot.forEach` is sync or not.

**Comment by Andarist** [comment]
Due to lack of followup answer from the original poster we have to close this issue as stale.
