### ISSUE TITLE
Testing cancel effect with realistic Task objects

### ISSUE THREAD

**Issue by CodeJjang** [redux-saga/redux-saga#1415]
According to [Testing generators with fork effect](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/TaskCancellation.md#testing-generators-with-fork-effect), I have to use `createMockTasks` in order to tests that my root / main saga cancels my forked task(s).  
However, I don't see how to check that I indeed cancelled the desired task (and not some other task).

Here's the code from the docs:
```
function* main() {
  while ( yield take(START_BACKGROUND_SYNC) ) {
    // starts the task in the background
    const bgSyncTask = yield fork(bgSync)

    // wait for the user stop action
    yield take(STOP_BACKGROUND_SYNC)
    // user clicked stop. cancel the background task
    // this will cause the forked bgSync task to jump into its finally block
    yield cancel(bgSyncTask)
  }
}
```
And here's how to test it:
```
it('waits for stop action and then cancels the service', () => {
    const mockTask = createMockTask();

    const expectedTakeYield = take(STOP_BACKGROUND_SYNC);
    expect(generator.next(mockTask).value).to.deep.equal(expectedTakeYield);

    const expectedCancelYield = cancel(mockTask);
    expect(generator.next().value).to.deep.equal(expectedCancelYield);
  });
```

Where do I verify that `cancel` indeed cancels `bgSyncTask` and not some other task?  
I would expect to pass the task function to `createMockTask` in some manner so it would present a specific task and not a general task.  

Perhaps am I missing something?

**Comment by Andarist** [comment]
By injecting `mockTask` you "bind" `bgSyncTask` reference to this particular mock's instance, so actually when you later get expected `cancel(mockTask)` **out of** your saga (by iterating with `.next(...)` you have 100% certainty that what you have previously injected into your saga got cancelled later. 

You can test it by creating a second mock task and comparing against `expectedCancelYield = cancel(secondMock)`.
