### ISSUE TITLE
Redux-saga doesn't call - Build Webpack

### ISSUE THREAD

**Issue by angemile09** [redux-saga/redux-saga#1416]
Hi!!
I have one application with react that in localhost It works well with differents saga; but when i do the build with webpack, i have one saga that is never called. Thanks for your help

This is my saga:
[saja.txt](https://github.com/redux-saga/redux-saga/files/1939782/saja.txt)

these are my webpack:
[webpack.base.babel.txt](https://github.com/redux-saga/redux-saga/files/1939800/webpack.base.babel.txt)
[webpack.prod.babel.txt](https://github.com/redux-saga/redux-saga/files/1939801/webpack.prod.babel.txt)

**Comment by angemile09** [comment]
@yelouafi could you help me with this??

**Comment by angemile09** [comment]
@Andarist could you help me with this??

**Comment by Andarist** [comment]
www.stackoverflow.com is much better suited for those kind of questions.

**Comment by angemile09** [comment]
@Fazt hola! sabes mi me puedes ayudar con este tema??
