### ISSUE TITLE
Creating pub sub event channel for Apollo subscriptions

### ISSUE THREAD

**Issue by anthonychung14** [redux-saga/redux-saga#1418]
Based on some Redux state, I want to generate (and be able to cancel) event emitters for React Apollo to subscribe to.

Is it possible to “mock a websocket endpoint”?

**Comment by Andarist** [comment]
> Based on some Redux state, I want to generate (and be able to cancel) event emitters for React Apollo to subscribe to.

It should be possible with `channel` (it's bidirectional).

**Comment by anthonychung14** [comment]
is it possible to mock such a thing if the graphql endpoint expects a `wss` connection?

**Comment by Andarist** [comment]
Assuming we are talking about mocking here - it should be possible. Mocks replace actual implementation and you should be possible to construct it in a way that suits ur needs.

That being said such questions are better suited for sites such as stackoverflow.com than Github issues.
