### ISSUE TITLE
Several sagas waiting for the same rejected promise acts differently

### ISSUE THREAD

**Issue by klimashkin** [redux-saga/redux-saga#1421]
Hi!

Found out that if two saga functions yield the same promise, that gets rejected, then first saga can catch thrown error (if saga wraps yield expression with try-cath), but the second saga can't - it is automatically cancelled.

Is it a correct behavior?

In my case I put fetch request (that returns promise) in a list of pending requests and sagas that try to call fetch with the same parameters just takes existing promise from that list to avoid creating more identical https requests and reuse response from the first one. That means several sagas can yield the same promise. And very strange that only first one can catch error, but others can't.

**Comment by Andarist** [comment]
Seems weird. Could you prepare a repro case on something like codesandbox.io ?

**Comment by klimashkin** [comment]
Oh, that was my fault!
I called the same task twice in `all()` and the second one becomes cancelled before it gets a chance to catch error from promise!

https://codesandbox.io/s/88q39vzzq8
Works normally, but if you uncomment `/*throw error;*/` you get catch block reached only for the first one.
