### ISSUE TITLE
Yield isn't Asynchronous on Linux

### ISSUE THREAD

**Issue by framerate** [redux-saga/redux-saga#1424]
This is a react/redux app running in Electron, for background.

On Windows and macOS, this snippet will delete the data on the server and then fetch the latest as expected.

```javascript    let response = yield call(deleteData, options);
    const data = yield call([response, response.json]);
    if (!data.success) {
        window.alert('You cant do that!');
    }
    yield call(fetchGetDecks);
```

 But when running on Linux (testing on 2 different distros, Solus and Debian based) the fetch will trigger before the deck is deleted properly. Only appears to happen on Linux and happens 100% of the time.

Perhaps this is an antipattern (I'm only a few months into using sagas) or perhaps this is more related to electron.

Any information would be appreciated, and I can supply more info if needed!

**Comment by Andarist** [comment]
`yield` is never asynchronous. The only thing that matters is how the redux-saga runtime interprets what got yielded back to it. 

If your response is about deleting something and later (immediately) you fetch that something and it's still there I would start investigating your backend implementation.

**Comment by framerate** [comment]
Thanks @andarist

The weird thing here is that it only fails on Linux.. using the same back end

I don't have any caching set up on the back end either, just straight calls into the DB

**Comment by Andarist** [comment]
Hard to judge without actually seeing it. Maybe you send response back too soon from the server?

**Comment by framerate** [comment]
Sounds possible, but only on Linux front end?

I guess it could also be possible something on the react side is rendering too fast, but seems odd only on linux again...

The back end us hapi v17, so its all async/await. I'll take another look to be sure but it really feels like sagas functioning different on Linux (I have another bug where v8 or something functions oddly on one OS too so it wouldn't be the first time

**Comment by Andarist** [comment]
Well, assuming u get the response back to ur browser when the items is already deleted and u fetch **afterwards** and you receive some "stale" data there is no way this can be a saga problem.

**Comment by framerate** [comment]
I'm not sure I follow. How would I get stale data if there is no caching? It should always be live. 

And how would this only happens on a linux saga implementation and not on macOS and Windows?

**Comment by framerate** [comment]
@restrry I'll see if I can get one up there!

**Comment by framerate** [comment]
@restrry Sorry I was unable to code up a repro case. The bug is still happening, but I'm working two full time jobs so it's hard to find the time. Hopefully I'll get to it eventually and I'll post it back here (or maybe someone else will have the same bug and find this post!)

Thanks for being responsive! <3
