### ISSUE TITLE
setContext doesn't work 

### ISSUE THREAD

**Issue by MaxToyberman** [redux-saga/redux-saga#1426]
Hi,
I am using setContext but I don't see any change.

in my CreateStore.js file :

```
     const sagaMiddleware = createSagaMiddleware({
        context: {
            api: null
        },
        sagaMonitor
    })
```

then in my saga: 

```
export function * getConfig() {
   
       const api = Api.create('someurl')
        yield setContext({api}})
}
```

when trying to get api:
 ` const api = yield getContext('api')`

I still get null 

Please help

**Comment by Andarist** [comment]
could u share a repro case on something like codesandbox.io ?

**Comment by Andarist** [comment]
Closing because the original author did not respond in over 20 days.
