### ISSUE TITLE
How to write unit test for takeLatest effect which has implemented inner function.

### ISSUE THREAD

**Issue by anujengg** [redux-saga/redux-saga#1427]
I have been implemented `takeLatest` to in order to remove the `while(true)` statements from the implementation. My implementation looks like below and it works perfectly
```
yield takeLatest(constants.SETTINGS.DATE.SAVE, function* save(values) {
    yield all([
      call(saveDate, values),
      call(saveTimezone, values),
    ]);
    yield put(actions.date.update());
});
```
I am able to write unit tests for this by separate out this function to an another generator function, since we have already a lot of functions so I dont want to make a separate function.

Can someone please tell me how I can write an unit test for this kind of implementation.
( either for takeLatest or for takeEvery )

**Comment by Andarist** [comment]
You can read about testing in more details [here](http://blog.scottlogic.com/2018/01/16/evaluating-redux-saga-test-libraries.html).
