### ISSUE TITLE
GitBook docs Beginner Tutorial not in sync with repo

### ISSUE THREAD

**Issue by freddydumont** [redux-saga/redux-saga#1434]
# Description of the bug/issue
The [beginner tutorial docs](https://redux-saga.js.org/docs/introduction/BeginnerTutorial.html) aren't reflecting the docs on the repo.

Notice how the `helloSaga()` function declaration is missing and spacing is off.

<img width="787" alt="docs_missing_function" src="https://user-images.githubusercontent.com/15388588/39848698-c6f25256-544b-11e8-8210-2882eb9828d0.png">

# The expected results
The GitBook should reflect the changes on the [master branch](https://github.com/redux-saga/redux-saga/blob/master/docs/introduction/BeginnerTutorial.md):

> Now we have 2 Sagas, and we need to start them both at once. To do that, we'll add a `rootSaga` that is responsible for starting our other Sagas. In the same file `sagas.js`, refactor the file as follows:
> 
> ```javascript
> import { put, takeEvery, all } from 'redux-saga/effects'
> 
> const delay = (ms) => new Promise(res => setTimeout(res, ms))
> 
> function* helloSaga() {
>   console.log('Hello Sagas!')
> }
> 
> export function* incrementAsync() {
>   yield delay(1000)
>   yield put({ type: 'INCREMENT' })
> }
> 
> export function* watchIncrementAsync() {
>   yield takeEvery('INCREMENT_ASYNC', incrementAsync)
> }
> 
> // notice how we now only export the rootSaga
> // single entry point to start all Sagas at once
> export default function* rootSaga() {
>   yield all([
>     helloSaga(),
>     watchIncrementAsync()
>   ])
> }
> ```

**Comment by Andarist** [comment]
You are right, ideally we should have those in sync - but at the moment we are working on v1 (it's in beta) and we do not want to release docs (some parts of them might refer to v1 features) to avoid confusion.

**Comment by vytautas-pilk** [comment]
@Andarist, library is now v1, and this specific part of a tutorial is still outdated. Not sure about the rest as I just started learning the library.

**Comment by Andarist** [comment]
Could you point me to the exact place that is not in sync?

**Comment by vytautas-pilk** [comment]
Precisely the same as shown in the first post where one should export `incrementAsync` saga to be able to test it later on.
