### ISSUE TITLE
redundant code??

### ISSUE THREAD

**Issue by bochen2014** [redux-saga/redux-saga#1448]
I'm learning saga, and found 2 small issues.

1.  How can we `fork` an iterator?
https://github.com/redux-saga/redux-saga/blob/c61d6f13a33837e92fd36f9b332661a8200782ec/packages/core/src/internal/io.js#L122

will enforce that you can only pass *function* (could be a Function Generator)  into `fork`;  you can **not** pass an `iterator` to `fork`;
*but*, in a different place we have
https://github.com/redux-saga/redux-saga/blob/c61d6f13a33837e92fd36f9b332661a8200782ec/packages/core/src/internal/proc.js#L133

Questions: in what case will above `if` be truthy?

2.  How do we `yield` an iterator? where can I find document for it?
https://github.com/redux-saga/redux-saga/blob/c61d6f13a33837e92fd36f9b332661a8200782ec/packages/core/src/internal/proc.js#L382

I also checked its history, it seems to me that it needs to be cleaned up

**Comment by Andarist** [comment]
1. U might be right, would u like to remove this `if` statement, check if tests pass & send a PR?
2. you can just `yield someGenerator()` (`someGenerator` returns an iterator), but it's not recommended, it's better to `yield call(someGenerator)`

> I also checked its history, it seems to me that it needs to be cleaned up

Not sure what do u mean. Could u elaborate?

**Comment by bochen2014** [comment]
thanks for your reply. 

https://github.com/redux-saga/redux-saga/blob/c61d6f13a33837e92fd36f9b332661a8200782ec/packages/core/src/internal/io.js#L110

so it seems you can't call a generator. you can only call a `fn`;


it seems that `yield someGenerator()` has the same effect as `yield* someGenerator()`, but I can't find the source code for `yield* someGenerator()` . can you point me the direction? thanks

**Comment by Andarist** [comment]
> but I can't find the source code for yield* someGenerator(

There is no source code for this, because it's **language feature**. 

```js
function* someGenerator() {
  yield 2
  yield 4
  return 6
}

const res = yield* someGenerator()
```
is equivalent to 
```js
yield 2
yield 4
const res = 6
```

**Comment by bochen2014** [comment]
i see. 
thank you for your help!
