### ISSUE TITLE
toPromise still referred to as 'done' in the readme

### ISSUE THREAD

**Issue by JSoet** [redux-saga/redux-saga#1452]
#### Description of the bug/issue

This is just a documentation issue which I noticed. I upgraded to the 1.0.0-beta and missed that .done was renamed to .toPromise.. I was looking at the [readme](https://github.com/redux-saga/redux-saga/blob/master/docs/api/README.md#task) and it was still there and I missed it in the release notes so it took me a while to figure it out. I can create a PR to fix it if you want, I just wanted to check that I was looking in the correct place, and that the master branch readme should contain that info (I think so, since takeLeading is also there) or if there's anywhere else that it should be updated.

**Comment by Andarist** [comment]
To sum it up:
- https://redux-saga.js.org/ - contains docs for 0.16
- master branch contains newer version of the docs, we've not yet updated it to be be fully compatible with v1 though

We'd appreciate a PR with a fix! 😉

**Comment by restrry** [comment]
@Andarist should we create an umbrella ticket to collect all cases of incompatibility in the docs?

**Comment by JSoet** [comment]
Done in PR #1456 :)
