### ISSUE TITLE
Cancel request once different request of particular type started.

### ISSUE THREAD

**Issue by quarryman** [redux-saga/redux-saga#1455]
I have saga that listens to 2 events
```
function* (){
      takeLatest(update.type, updateHandlerFunction)
      takeLatest(delete.type, deleteHandlerFunction)
}
```

both _updateHandlerFunction_ and _deleteHandlerFunction_ are generators that yield call() producing API request.

UI can dispatch _update.type_ and _delete.type_ simultaneusly.

What is the best way to achieve one of 2 behaviors
1. Cancel update request once delete.type event has been dispatched (preferable)
2. Make sure _delete_ waits for _update_ to finish, and only then runs _deleteHandlerFunction_.

**Comment by Andarist** [comment]
I must say I don't quite understand your 2 mentioned requirements. How delete.type should both cancel update request and wait for update to finish?

**Comment by quarryman** [comment]
@Andarist I requested for one of 2 requirements. Either 1 or 2 but not both at the same time.
Currently I am more interested in how to achieve second behavior as first can be achieved with 'race'

But its still not clear how Do i make 1 action wait for another to finish ->
Make sure delete waits for update to finish, and only then runs deleteHandlerFunction.

**Comment by Andarist** [comment]
You could i.e. buffer those actions with channels, race takes on them - if u take `update.type` then u should just process update channel until it gets empty and then process delete.

Code for this might get a little bit messy, so probably better to just make a local variable that would act as a "lock". Keep in mind that u can write nested generators, so u can do things like:
```js
function* () {
  let updating = false
  let pendingDelete = null

  yield takeLatest(update.type, function*(ac) {
    updating = true
    yield call(updateHandlerFunction, ac)
    updating = false

    if (pendingDelete) {
      // spawn to detach this task, so it wont get cancelled if new update.type arrives
      yield spawn(function* () {
        // preserve reference + clear the local "state"
        const deleteAc = pendingDelete
        pendingDelete = null
        yield call(deleteHandlerFunction, deleteAc)
      })
      
    }
  })

  yield takeEvery(delete.type, function*(ac) {
    if (updating) {
      pendingDelete = ac
      return
    }
    yield call(deleteHandlerFunction, ac)
  })
}
```

This might not work, not adhere to your exact requirement etc but it should be pretty close to it 😉
