### ISSUE TITLE
How to cancel forked tasks?

### ISSUE THREAD

**Issue by budarin** [redux-saga/redux-saga#1457]
I've been waiting for any help in StackOverflow some days, but no one ((
[my question](https://stackoverflow.com/questions/50488687/redux-saga-how-to-stop-or-cancel-task-chain)

### Description
I have dynamic attaching/detaching sagas for every route.
For an example like this one:

```js
function* incrementAsync() {
    yield call(delay, 3000);
    yield put(counterIncrement());
}

function* incrementAsyncWatcher() {
    yield takeEvery(ASYNC_INCREMENT, incrementAsync);
}

function* incrementCounterSaga() {
    yield fork(incrementAsyncWatcher);
}

const task = sagaMiddleware.run(incrementCounterSaga);
```

then I try to stop this saga

```js
task.cancel();

store.dispathch({ type: ASYNC_INCREMENT });
```

but after 3 seconds see that saga is still working!
How to stop such kind of sagas?

**Comment by restrry** [comment]
how do you see that it's still running? there is an example https://codesandbox.io/s/0p4800k5wv
if you run js file you will see in console that `incrementAsync` is logged only once and `not cancelled` not logged at all

**Comment by budarin** [comment]
Hi!
You are right! It was error in my code
Thanks a lot!
