### ISSUE TITLE
Use takeEvery or takeLatest based on action payload?

### ISSUE THREAD

**Issue by jansomers** [redux-saga/redux-saga#1461]
Based on the payload of the action that is being watched I want to either trigger a takeLatest or takeEvery.

Right currently I have a (half)working solution. The first time the GET_ORDERS_REQUEST with the Open type gets dispatched, the effect is not happening. If that action would be dispatched again, fetchOpenOrders gets called :)

Anything I'm missing?

```
function* ordersRequestSaga() {
 const action = yield take(OrderActions.TypeKey.GET_ORDERS_REQUEST);
 switch (action.payload.requestType) {
 case OrderData.RequestType.Open:
  yield takeLatest(action.type, fetchOpenOrders);
  break;
 default:
  break; 
 }
}
```

**Comment by zgavin1** [comment]
The way to implement what you're trying to do is much simpler than you think. There's no need for the switch statement because Saga helpers like takeLatest and takeEvery only spawn a new saga when the first argument _matches_ with the action your dispatched to the store.

```
function* ordersRequestSaga() {
  yield takeLatest(OrderData.RequestType.Open, fetchOpenOrders);
  yield takeEvery(OrderData.RequestType.OtherRequestType, fetchOtherRequests)
}

**Comment by Andarist** [comment]
You can also pass predicate to `takeLatest`/`takeEvery` instead of action type. Smth like 
```js
function* ordersRequestSaga() {
  yield takeLatest(ac => ac.type === OrderActions.TypeKey.GET_ORDERS_REQUEST && ac.payload.requestType === OrderData.RequestType.Open, fetchOpenOrders);
  yield takeEvery(ac => ac.type === OrderActions.TypeKey.GET_ORDERS_REQUEST && ac.payload.requestType !== OrderData.RequestType.Open, fetchOtherRequests)
}
```
