### ISSUE TITLE
redux-saga: componentDidMount not working on component population for master-detail

### ISSUE THREAD

**Issue by asykes74** [redux-saga/redux-saga#1466]
In reviewing different approaches to populating form components from a database, most of what I found seem to point to doing it from componentDidMount.  For my example, I have a master-detail scenario where I populate a screen with a list of items that can be selected.  After selection, another screen appears allowing the user to edit the selected item.  For my list screen, I am not able to populate the list if I call componentDidMount but I am able to do so if I call componentWillMount and componentWillReceiveProps.  This is the only combination that seems to work. 

Here is the sample code:
    
    methods in component:
    constructor (props) {
        super(props);
        this.state = {
            data: null,
            searchText: null,
            page: 0
        };
    }
    
    
    const mapStateToProps = (state, ownProps) => {
        return {
            data: this.state.data,
            searchText: this.state.searchText,
            page: this.state.page
        };
    }
    
    
    const mapDispatchToProps = (dispatch) => {
        return {
            onFetchResults: (page, searchText) => { dispatch(studentRetrieve(page, searchText)); }    }
    }
    
    export default connect(mapStateToProps, mapDispatchToProps)(ConnectAlert(StudentList));
    
    
    componentWillReceiveProps = (nextProps) => {
        this.setState({data: nextProps.data});
    }
    
    
    action_creator:
    export const studentRetrieve = (page, searchText) => ({
        type: STUDENT_LIST,
        page: page,
        searchText: searchText
    });

    export const studentRetrieveSuccess = (data) => ({
        type: STUDENT_RETRIEVE_SUCCESS,
        data: data
    });
    
    reducer:
    case STUDENT_LIST:
        return {
            ...state,
            searchText: action.searchText,
            page: action.page
        };

    case STUDENT_RETRIEVE_SUCCESS:
        return {
            ...state,
            data: [ ...data ]
        };
    
    
    saga:
    export const fetchStudents = function* (action) {
        try {
            const response = yield call(retrieveStudent, action);
    
            if (response.status >= 200 && response.status < 300) {
                const studentList = yield call([response, 'json']);
    
                yield put(studentSuccess(studentList));
            } else {
                let body = yield call([response, 'json']);
                yield put(errorMessageOccurred(body.errors[0]));
            }
        } catch (err) {
            yield put(errorMessageOccurred(‘Am error message occurred.  Please try again’));
        }
    }
    
    fetch:
    const retrieveStudent = async ({page, searchText}) => {
        let searchString = '';
    
        if (searchText)
            searchString = '/' + searchText;
        else
            searchString = '';
    
        return await fetch(globals.BASE_URL + '/api/studentlist/' + page + searchString, {
            method: 'get',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }, {mode: 'no-cors'});
    }

1) What am I doing wrong in code here, that is making componentDidMount not display a populated component, whereas componentWillMount and componentWillReceiveProps works?

2) Also, I am noticing that in my saga, if an error occurs, the catch exception handling seems to result in an undefined err object.  What could be the issue here?  I am returning the promise from the fetch call.

**Comment by Andarist** [comment]
Issues such as this without a runnable example will be closed. Please follow your issue template instructions.

**Comment by asykes74** [comment]
I am confused, I asked this as a question and not an issue?

**Comment by Andarist** [comment]
> What am I doing wrong in code here, that is making componentDidMount not display a populated component, whereas componentWillMount and componentWillReceiveProps works?

Without a runnable example we cannot know what's causing the issue.

Our question template mentions that "The best way to provide an example is repository or use Code Sandbox".

**Comment by asykes74** [comment]
If I should rephrase the question, that is fine.  Honestly, I saw this question not too much different than this question, https://github.com/redux-saga/redux-saga/issues/697, except my questions is longer.  For the most part I am just trying to understand if my approach is correct since many of the CRUD based suggestions center around using conponentDidMount when reads are necessary.  This is more of seeking understand into how crud scenarios should be properly handled with saga.

**Comment by Andarist** [comment]
You are right about the other question being similar. The problem is that saga got more and more popular and maintaining is more and more of a burden, especially when it comes to answering general questions. I would suggest to ask such questions on sites like stackoverflow.com or join our gitter and start a discussion there. 

I would restraing from using `componentWillMount` & `componentWillReceiveProps` as both are somewhat deprecated nowadays and will be removed in the future. You don't have to dispatch reads from `componentDidMount` (but u can ofc), I assume your component might be rendered conditionally and you might want to start fetching based on the same condition (state change or whatever) and not postpone it until React calls `componentDidMount`. It all depends on your application though and your personal preferences.

**Comment by asykes74** [comment]
Honestly, I am a newbie to react-native and really like what I see in redux-saga.  For my case, if you can point me in this direction.  What might help me the most would be if you could point me in the direction of a example or tutorial using a CRUD, master-detail scenario.  The issue I have run into so far is that most of the crud I have found so far seems to include alot of over the top things that sometimes take away from what should be a basic crud example.  I have been struggling with finding really good examples for these kind of real world examples.
