### ISSUE TITLE
Update GitBooks

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#1469]
I've noticed that redux' docs got a nice lifting, thanks for the new version of GitBook. Would be nice to upgrade too.

Redux commit introducing the change - https://github.com/reduxjs/redux/commit/b307091af4d7e846d9e5f080fb81caf4a8b4aab1

We might want to postpone merging this though, because we don't want to update docs before releasing v1 and from what I understand new Gitbook comes with auto-releases.

**Comment by shinima** [comment]
I'm interested in working on this.

**Comment by divyanshu013** [comment]
I think this would be a good improvement to the docs. I followed the above pr, seems like there are issues with gitbook. Have you explored other options like docnasaurus or gatsby? Perhpas they could work well. Thoughts?

**Comment by Andarist** [comment]
@divyanshu013 they would certainly work well - but they would require quit a bit of work initially to setup, Im afraid that we don't have time resources to do that right now. Would you be willing to work on it? My personal choice out of those 2 would be gatsby

**Comment by divyanshu013** [comment]
@Andarist I also lean towards gatsby. I can surely pick it up but can't promise a timeline (apologies), if you're okay with it.

Any references for docs you have in mind? Gatsby themselves have a good docs site, for reference.

**Comment by Andarist** [comment]
> @Andarist I also lean towards gatsby. I can surely pick it up but can't promise a timeline (apologies), if you're okay with it.

No problem, it's just an enhancement - we are not in a hurry :)

> Any references for docs you have in mind? Gatsby themselves have a good docs site, for reference.

Not really - something rather standard, similar to what we currently have.

**Comment by divyanshu013** [comment]
Awesome, will keep you posted 🙂

**Comment by acdvs** [comment]
It looks like the GitBook CLI isn't supported anymore since the team moved to a paid service. Is there still interest in moving the docs to another platform?

**Comment by Andarist** [comment]
@acdvs yes! would u like to help with the move?

**Comment by acdvs** [comment]
@Andarist Absolutely! I recommend we use Docusaurus for its simplicity and current use in related projects like Redux and React Native but I wouldn't be opposed to something else.

**Comment by Andarist** [comment]
I would be OK with Docusaurus 👍 Ideally we'd preserve current URLs - but if that's too hard then I won't treat this as a blocker.

**Comment by acdvs** [comment]
The only way to have `docs/` at the base of every URL would be to move the docs directory entirely, so we'd either do that or have to settle with URL changes.

**Comment by Andarist** [comment]
What do u mean by moving the docs directory entirely? As to the directory structure in this repository - we have complete freedom for making changes in it.

**Comment by acdvs** [comment]
Ok, I just wasn't sure what the preferable option was there. I guess it would be much better to keep the same URL structure for SEO purposes.

Something in the current site that isn't possible with Docusaurus is having the base readme as the "home" page. The home page would either need to be (1) a real home page (like the [Redux site](https://redux.js.org) has) or (2) an existing doc in the docs directory (e.g., `docs/introduction/BeginnerTutorial.md`).

I think option one with a true homepage is far better in the long run but would require some work to fill it out properly.

**Comment by Andarist** [comment]
A "real" home page sounds good - although I don't have the capacity to work on the design and such. Would you be able to help out with this?

**Comment by Andarist** [comment]
Super, that's going to be awesome 👍
