### ISSUE TITLE
Reducing boilerplate for API calls

### ISSUE THREAD

**Issue by Dharmoslap** [redux-saga/redux-saga#1473]
Found this awesome action factory: https://gist.github.com/jiayihu/811f2dc704d6ce6308d679a987348b20

I think this is worth merging. What are your thoughts?

Let's discuss naming.. something like `createApiActions`or `createRequestActions` can work IMO.

Then we could do:
 
```
import { createRequestActions } from 'redux-saga'

export const addInvoice = createRequestActions('ADD_INVOICE', {
  request: (invoice) => ({ invoice }),
  success: (invoice, result) => ({ invoice, result }),
});

store.dispatch(addInvoice.request({ id: 1 }));
```

**Comment by Dharmoslap** [comment]
@shinima Yes, it would more likely belong into redux repo, but in redux docs they already say that they  recommend to create constants explicitly. 
https://github.com/reduxjs/redux/blob/master/docs/recipes/ReducingBoilerplate.md#generating-action-creators

**Comment by Andarist** [comment]
This is out of scope of redux-saga repository. If you want you might find some place in documentation and create a PR linking from there to this, but other than that I'm closing this as unactionable.
