### ISSUE TITLE
Partially missing docs for call, cps, and fork

### ISSUE THREAD

**Issue by chrissantos1995** [redux-saga/redux-saga#1476]
### Description
My team is using the syntax below to explicitly pass `context` and `fn` to `fork`, `call` and `cps`:

### `fork({context, fn}, ...args)`

It seems that the [API reference](https://redux-saga.js.org/docs/api/) is missing documentation for this style of invocation -- do we know if these are being omitted intentionally?

If it's simply missing from the documentation -- let me know if you need help with the PR for adding these. 

As a followup, it'd be great to have these added to the flow-typed definitions. I can help with that as well if we want to move forward with this change.

**Comment by shinima** [comment]
The code that handles this style of invocation is [here](https://github.com/redux-saga/redux-saga/blob/8555610cbd1f09176546edea7b01383714b8ed48/packages/core/src/internal/io.js#L94-L96). I think the documentation is missing this style of invocation. Welcome to make a PR.

The typescript declaration file already contains [type definitions for this style of invocation](https://github.com/redux-saga/redux-saga/blob/8555610cbd1f09176546edea7b01383714b8ed48/packages/core/effects.d.ts#L150-L155).

**Comment by chrissantos1995** [comment]
Thanks shinima -- I opened a PR [here](https://github.com/redux-saga/redux-saga/pull/1484) for doc additions. I'll pursue the type additions in the flow-typed repo.

**Comment by Andarist** [comment]
closed by #1484
