### ISSUE TITLE
Typescript args issue

### ISSUE THREAD

**Issue by chris-divvito** [redux-saga/redux-saga#1482]
### Steps to reproduce
When `fork()` or `call()` are called with a destructured array as arguments for their worker function (first argument.

#### Description of the bug/issue
typescript reports an error: "TS2557: Expected at least 1 arguments, but got x or more" where x is greater than 1. (which feels like a misnomer: "3 or more" seems to, by definition, satisfy the expectation "at least 1" 

I'm not 100% certain if this is a redux-saga problem or a Typescript problem, but my attempts to figure it out kept leading me back to `CallEffectFn` and `CallEffectFactory`.

#### Example
Here's where I am seeing the issue: 
```
export function* forkUntilLogoutHelper(pattern: Pattern, worker: (action: Action) => any, ...args) {
  while (true) {
    const result = yield take(pattern);
    yield race({
      loginTask: call(worker, result, ...args), // Typescript raises error here
      logout: take(TypeKeys.USER_LOGGED_OUT)
    });
  }
}

export function forkAtLogin(worker: (userLogin: UserLoggedInAction) => any, ...args) {
  return fork(forkUntilLogoutHelper, TypeKeys.USER_LOGGED_IN, worker, ...args); // Typescript raises error here
}

// Several other functions using forkUntilLogoutHelper follow, using the same pattern and with the same issue
```

I may be crazy, but I feel like I wasn't previously seeing this issue, but have opened this file for the first time in a while and seeing this problem.

### Environment information
- redux-saga version: 0.16.0
- babel / typescript setup: babel-core 6.24.1, tsc 2.7.2

A note that there is a workaround... although it is kind of awful:

```
// ...
const [pattern, worker, arg3, arg4, arg5, arg6, ...rest] = [TypeKeys.USER_LOGGED_IN, worker, ...args]
return fork(forkUntilLogoutHelper, pattern, worker, arg3, arg4, arg5, arg6, ...rest);
//...
```

This is part of what led me to believe it was something to do with the setup of `CallEffectFn` and `CallEffectFactory` - that it only seems to work when I change the layout to suit the "6 specific arguments then rest" pattern in there.

**Comment by shinima** [comment]
I think it is because TypeScript has not implemented variadic functions. So typescript raises error on meeting `...rest`. You may find [this issue](https://github.com/Microsoft/TypeScript/issues/5453) helpful. There are lots of similar issue references from other libraries like [immer#129](https://github.com/mweststrate/immer/issues/129).

Sadly I have no idea how to write the right type declaration for this case. Maybe you could cast `call` to `any` before using it:
```javascript
yield race({
  loginTask: call(worker, result, ...args), // no error, but not sound
  logout: take(TypeKeys.USER_LOGGED_OUT)
});
```

**Comment by restrry** [comment]
related https://github.com/Microsoft/TypeScript/pull/24897

**Comment by chris-divvito** [comment]
Awesome, thanks for the info guys. Will look out for the Typescript update. In terms of a workaround I think I'll stay with the one from my original post, it's more verbose, but I think it makes it more clear that it is a temporary hack, and so more likely I'll notice it and fix it when no longer required.

A huge thank you to you guys, btw, for the work you've done with redux-saga, it's a massive boon in development. I was just doing a short stint with another project with an existing, non-redux codebsae for a few weeks and I can't count how many times we had discussions on how to architect various async workflows which ended with me saying "...but you know what would have made this a thousand times easier? Sagas".

**Comment by Andarist** [comment]
As it's not actionable right now on our side, I'm going to close this issue. Feel free to comment further or to create a new one.

**Comment by gausie** [comment]
@Andarist is this solvable now that there is a new version of TS?

**Comment by Andarist** [comment]
no idea - im unfortunately not a TS expert
