### ISSUE TITLE
Can't resolve 'saga-monitor-example'

### ISSUE THREAD

**Issue by pandaCure** [redux-saga/redux-saga#1485]
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'saga-monitor-example' in '/Users/a/demo/redux-saga/examples/shopping-cart/src'
 @ ./src/main.js 11:0-47
 @ multi webpack-hot-middleware/client?reload=true ./src/main
Can't resolve 'saga-monitor-example' in '/Users/a/demo/redux-saga/examples/shopping-cart/src

**Comment by shinima** [comment]
Please describe the steps to reproduce this issue in detail. A repository with an example or use [Code Sandbox](https://codesandbox.io/) would be helpful.

**Comment by pandaCure** [comment]
@shinima 
i just clone the code and npm install and npm run shop

**Comment by shinima** [comment]
@pandaCure This repo use lerna to manage multiple packages. You need to run `npm run bootstrap` instead of `npm install`.

**Comment by pandaCure** [comment]
@shinima Thanks
