### ISSUE TITLE
Returning data from `store` asynchronously

### ISSUE THREAD

**Issue by stefanfrede** [redux-saga/redux-saga#1494]
Hi! I'm currently writing an API to fetch data from a server via `socket.io`. After a bumpy start, I got it working with `redux` and `redux-saga`, but there is one thing which is bothering me. I have to return the fetched data, and I haven't found a good solution for how to do this. This is what I came up with:
```js
  getTags(path: string, locale: string = 'de') {
    const request = JSON.stringify({
      url: path,
      method: 'GET',
      locale,
    });

    const tagList = store.getState().tagList;

    return new Promise(resolve => {
      if (tagList[request]) {
        resolve(tagList[request].tags);
      } else {
        const unsubscribe = store.subscribe(() => {
          const tagList = store.getState().tagList;

          if (!tagList[request].isFetching) {
            unsubscribe();
            resolve(tagList[request].tags);
          }
        });

        store.dispatch({ type: REQUEST_TAGS, request });
      }
    });
  }
```
It is working so far, but I have the feeling that it will cause me some headaches. I searched for quite some time now for other solutions, but nothing came up (or I just searched wrong).

My dream would be what I saw with `redux-thunk`, something in the way of `store.dispatch({ type: REQUEST_TAGS, request }).then( … )`.

If there is a better way to solve this, I would be happy about every push in the right direction.

Thanks in advance!

**Comment by shinima** [comment]
This is an open problem already discussed in #907.  There are some working solutions (but maybe not ideal) in that PR.

**Comment by stefanfrede** [comment]
I got it solved with [redux-wait-for-action](https://github.com/Chion82/redux-wait-for-action).

```
    …
    return new Promise((resolve, reject) => {
      return store
        .dispatch({
          type: REQUEST_ITEMS,
          request,
          [WAIT_FOR_ACTION]: RECEIVE_ITEMS,
          [ERROR_ACTION]: RECEIVE_ITEMS_FAILED,
          [CALLBACK_ARGUMENT]: action => action.items,
        })
        .then(items => resolve(items))
        .catch(error => reject(error));
    });
    …
```
