### ISSUE TITLE
React render errors fall into saga 

### ISSUE THREAD

**Issue by retyui** [redux-saga/redux-saga#1497]
#### Description of the bug/issue
react render errors falls into the saga `try\catch` block

#### Steps to reproduce the bug/issue
1. call put effect
2. after chages state, throw error in render method 

#### Example
There is a [prepared template](https://codesandbox.io/embed/m61l0xyyy) for Code Sandbox
There is a [test repo](https://github.com/retyui/saga-error-demo)

### Actual results
After call put effect in react render throw exeption , which falls into the saga `catch` handler block
### The Expected results
Errors that are thrown downstream will not bubble back into the saga

**Comment by shinima** [comment]
I think the actual results are expected behaviors. If we look at the call stack carefully, we could find that in this example all code are **synchronous**.   `yield put(actionToggleVisibile(true))` is the caller of `Hellow#render()` and ofc the error thrown by callee  should bubble back into the saga.

![image](https://user-images.githubusercontent.com/5550931/41543148-fc23293e-7348-11e8-8d23-b15181b67437.png)

**Comment by retyui** [comment]
@shinima
How can I get rid of the synchronous chain of calls so that the error does not fall into the saga?

**Comment by shinima** [comment]
`render()` method is supposed to be pure of its props&state, so ideally you should not throw any error inside `render()`.   But if the error is inevitable, you could add an [error boundary](https://reactjs.org/docs/error-boundaries.html) above `<Hellow />`.
