### ISSUE TITLE
Counter Vanilla example doesn't work - "effects.delay is not a function"

### ISSUE THREAD

**Issue by lowtolerance** [redux-saga/redux-saga#1500]
### Steps to reproduce
Open examples/counter-vanilla/index.html page in browser and attempt to click "Increment async" button.
#### Description of the bug/issue
Button does not function as expected, and produces an error stating that effects.delay is not a function. Works as expected if incrementAsync function is updated to call delay method of ReduxSaga, or if @beta version of redux-saga is used in place of @latest. I'm guessing this code will work as expected once out of beta, but as it exists, it is currently broken.

**Comment by restrry** [comment]
resolved in https://github.com/redux-saga/redux-saga/pull/1503
