### ISSUE TITLE
Event Channel not emitting

### ISSUE THREAD

**Issue by stefanfrede** [redux-saga/redux-saga#1502]
I try to implement a channel with Redux-Saga to listen to a WebSocket event, and for that, I more or less use the example from the documentation:
```js
const createDeltaChannel = socket =>
  eventChannel(emit => {
    const callback = data => {
      emit(data);
    };

    const eventName = 'changedDelta';

    socket.on(eventName, callback);

    const unsubscribe = () => {
      socket.off(eventName, callback);
    };

    return unsubscribe;
  });

function* watchDeltaChannel() {
  const { url, options } = yield select(socketParams);
  const socket = yield call(connect, url, options);
  const socketChannel = yield call(createDeltaChannel, socket);

  while (true) {
    const payload = yield take(socketChannel);
    yield put({ type: 'INCOMING_DATA', payload });
  }
}

export function* initDeltaChannel() {
  while (true) {
    yield take(START_DELTA_CHANNEL);
    yield race({
      task: call(watchDeltaChannel),
      cancel: take(STOP_DELTA_CHANNEL),
    });
  }
}
```
I use two different browsers to connect to the Socket server, and if I make a request which should trigger a response in one browser I do get my response in the other browser:
```
42/v2,
[
  "changedDelta".
  "{"url":"/~/4/dp/users/dat/value/Bar.Foo/email","body":"foo@bar.baz","method":"PUT"}"
]
```
But event channel wise nothing is happening it is stuck in this line:
`const payload = yield take(socketChannel);`.

Am I missing something?

Since yesterday I try to get this working, but now I ran out of ideas and would appreciate any help!

**Comment by stefanfrede** [comment]
I just verified with a test that the socket-server is working fine and that I get data back if I listen on the `changedDelta`-event.

In other words, this is working:
```js
socket.on('changedDelta', data => {
  console.log(data);
});
```

Either there is something wrong with my code, or something is broken with `eventChannel`.

**Comment by shinima** [comment]
@stefanfrede This seems really strange. `eventChannel` should be widely used in community and your code is totally good for me.

Which version of redux-saga do you use?  Could you provide a minimum reproduction with runnable code to let me investigate this issue?

**Comment by stefanfrede** [comment]
@shinima I just updated `redux-saga` to `v1.0.0-beta.1`, but sadly no changes.

The thing with _minimum_ and _runnable_ code is … difficult, because it is quite specific, but you can have a look [here](https://github.com/stefanfrede/redux-saga-socket/tree/implement-delta-subscription).

You can find the channel specific stuff in [src/sagas/init-channel.js](https://github.com/stefanfrede/redux-saga-socket/blob/implement-delta-subscription/src/sagas/init-channel.js).

I hope this helps a bit.

**Comment by shinima** [comment]
I try to run your redux-saga-socket, but sadly nothing happens in http://localhost:8080 and no error appears.  Without a running example, it is hard for me to solve this issue.

**Comment by stefanfrede** [comment]
Yeah, the problem is that the code is quite specific for the needs of a client of mine. I will think of something to make it testable.

**Comment by stefanfrede** [comment]
@shinima I just build myself a test server with socket.io which emitted a `changedDelta`-event every 2 seconds. Afterwards, I connected to this server and found out that my code is working fine.

So, no clue why it is not working with the socket server of my client, but at least it has nothing to do with redux-saga or my code.

Thank you for trying to help!
