### ISSUE TITLE
saga hangs when updating a redux state

### ISSUE THREAD

**Issue by ngoctuan001** [redux-saga/redux-saga#1507]
I was using redux-saga in my application. And use saga to set the state of my redux. But one thing i am experiencing now is the application will hang if I use saga to update the redux state with a different value from its existing state

Lets say, in my redux there is state name locale. first i set it to en, and create an action CHANGE_LOCALE to change the locale state to zh later.

**reducer.js**

```js
const initialState = fromJS({
  locale: 'en' <- set initial state to en
});

function languageProviderReducer(state = initialState, action) {
  switch (action.type) {
    case CHANGE_LOCALE:
      return state
        .set('locale', action.locale);
    default:
      return state;
  }
}
```
**saga.js**

```js
export function* loadProfile() {
  const profileURL = 'profile';
  const profile = yield axios.get(profileURL)
    // .then((res) => (res.data))
    .then((data) => (data.data));

  yield put({
    type: ACTION1,
    payload: profile,
  });
  console.log('finish action one');

  yield put({
    type: CHANGE_LOCALE,
    locale: 'zh', <- change to zh using saga
  });
  console.log('finish action two');

  yield put({
    type: ACTION3,
    payload: profile,
  });
  console.log('finish action three');
}
export default function* defaultSaga() {
  yield takeLatest(constants.LOAD_PROFILE, loadProfile);
}
```
So when I run the app, the console.log is just showing `finish action one`. Meaning it is hanging after changing the locale state of Redux .

( I use Redux Dev Tool to check and it actually has changed the locale state to'zh', -> it actually finish the action two however , it seems like the saga dont know what to do next )
p/s: The programm will run sucessfully after hanging for 2 or 3 minutes , so its like saga is stuck and then keep retry after a few minutes and succeed 
Any help please ??

**Comment by shinima** [comment]
One possible case is that `loadProfile` is cancelled by its parents. You can log the cancellation status of `loadProfile` and have a try.  The following code may be helpful.

```js
import { cancelled } from 'redux-saga/effects'

export function* loadProfile() {
  try {
    /* your code */
  } finally {
    console.log('loadProfile is cancelled', yield cancelled())
  }
}
```

**Comment by ngoctuan001** [comment]
Hi Shinima, when i run your code , it showing that :` loadProfile is cancelled true`. So is it cancelled by the parents ?, can you help me explain more I quite new in redux - saga. Thanks

**Comment by shinima** [comment]
Could you provide a running environment about your code?  That would make it much easier for me to find out the reason.  There is a template on [sacodesandbox](https://codesandbox.io/s/m79rn28z9y) you can use.

There are many possibilities of `loadProfile` being cancelled.  One possible case is that `put({ type: CHANGE_LOCALE,  locale: 'zh' });` triggers (directly or indirectly) another `LOAD_PROFILE` action, which will be taken by `takeLatest(constants.LOAD_PROFILE, loadProfile);` in `defaultSaga`.  Once `takeLatest` takes a LOAD_PROFILE, it will cancel the running `loadProfile` instance and fork a new instance.

It may also be that `CHANGE_LOCALE` awakes another `take` in another saga (*saga-2*), but code after that `take` throws exception and the exception propagates to the parents/ancestors of *saga-2*. Your `defaultSaga` is one of the children of the those parents/ancestors, so `defaultSaga` get cancelled and `loadProfile` get cancelled too. However in this case, you could see the exception logged into the console or you could catch the exception if you are using try-catch in those parents/ancestors. 

These are just possibilities why `loadProfile` gets cancelled, the actual reason may differ. A running reproduction would be best to let me find out the actual reason.

**Comment by ngoctuan001** [comment]
Hi  because this is a big project so I'm not sure how to reproduce the bug using the codesandbox, i cannot put all the code there. Anyway, there is one way to make it works is to put a yield delay between , something like this

```
 yield put({
    type: ACTION1,
    payload: profile,
  });
  console.log('finish action one');
yield delay (500)
  yield put({
    type: CHANGE_LOCALE,
    locale: 'zh', <- change to zh using saga
  });
  console.log('finish action two');
```

It works perfectly if we delay it by a period, do you have any idea from this . thanks

**Comment by Andarist** [comment]
Are you sure that u do not end up with some kind of infinite loop when dispatching `CHANGE_LOCALE`? Could u check ur action log to confirm/invalidate this guess?

**Comment by shinima** [comment]
Closing this as it is inactive. Feel free to comment or open a new issue.
