### ISSUE TITLE
Flushable throttle that does not fire until there is a pause in incoming events?

### ISSUE THREAD

**Issue by Slapbox** [redux-saga/redux-saga#1511]
I'd like to wait to send some requests until the user is done with input, or at least pauses.  I'm trying something like the below, but the code never gets past a certain point. It works fine if I use `takeEvery` instead of `takeLatest`. What am I overlooking here? Any advice would be greatly appreciated!

(PS, I am of course yielding the `activeTasks` somewhere not shown in this bit of code)
```js
const activeTasks = all([
  throttleUntilLast(5000, 1000, types.UPDATE_A_VALUE, updateValues),
])

function* flushableThrottle({ ms, leadingDelay, pattern, task }, ...args) {
  try {
    yield delay(leadingDelay);
    const throttleChannel = yield actionChannel(pattern, buffers.sliding(1));
    while (true) {
      const action = yield take(throttleChannel); // THIS IS THE LAST LINE EXECUTED
      yield fork(task, ...args, action); // NEVER MAKES IT TO HERE
      yield race({
        flush: take([types.PREPARE_TO_QUIT, types.FORCE_UPDATE]),
        wait: delay(ms)
      });
    }
  } catch (err) {
    log.error(err);
  }
}

function* throttleUntilLast(ms, leadingDelay, pattern, task, ...args) {
  try {
    const params = { ms, leadingDelay, pattern, task };
    yield takeLatest(pattern, flushableThrottle, params, ...args );
  } catch (err) {
    log.error(err);
  }
}

function* updateValues(args) {
  log.warn("Flushing buffer");
}
```

**Comment by Slapbox** [comment]
Mysteriously after stepping away from my code for several minutes, I saw it was then making it to `updateValues()`, but never hitting `log.warn("Flushinjg buffer");`

I have since been unable to reproduce this, which makes it even more baffling to me.

**Comment by Andarist** [comment]
Nesting throttle inside `takeLatest` looks generally like a not good idea - especially without cleaning the inner channel on cancellation. Could u describe ur desired behaviour in more detail? I cant decipher it quickly from given code.

**Comment by Slapbox** [comment]
Yeah sure. Thanks @Andarist.

Basically what I'm trying to have a background sync operation like in the example where you laid out the code for the throttle with a flushable buffer, but I also want to wait until a user has stopped adding input to their local document before syncing it to the cloud for the sake of not overloading the server with a new updates.

For example, if someone types for 30 seconds straight, I'd like to wait until their is a lull in the input to allow the task to proceed. What I tried to do above was to add a leading delay to the task so that it would have a chance to be canceled if newer input occurred.

I'd also like to keep the throttle for flexibility, as there might be times that it makes sense to have both, although in most cases the throttle is not strictly necessary here.

Does that make sense? I feel my explanation could be more clear, but I'm not sure how to make it so.

**Comment by shinima** [comment]
@Slapbox 
```js
//  LINE-1:
const action = yield take(throttleChannel); // THIS IS THE LAST LINE EXECUTED

// LINE-2:
yield takeLatest(pattern, flushableThrottle, params, ...args );
```

I think the problem in your code is that when LINE-1 get executed,  `takeLatest` on LINE-2 can take the same action. `takeLatest` will cancel the existing `flushableThrottle` instance so the iterator jumps out after LINE-1 gets executed.

> Basically what I'm trying to have a background sync operation like in the example where you laid out the code for the throttle with a flushable buffer, but I also want to wait until a user has stopped adding input to their local document before syncing it to the cloud for the sake of not overloading the server with a new updates.

I suspect what you need is  `debounce` rather than `throttle` (though they are very similar).  `debounce` helper is implemented in master branch now, however it is not available in 1.0.0-beta.1, so you need to implement it manually.

The code of `debounce` is as follows, you can edit the code according to your requirements.

```js
export function debounce(ms, channelOrPattern, worker, ...args) {
  return fork(function*() {
    while (true) {
      let action = yield take(channelOrPattern)
      while (true) {
        const { nextAction, timeout } = yield race({
          nextAction: take(channelOrPattern),
          timeout: delay(ms),
        })
        if (timeout) {
          yield fork(worker, ...args, action)
          break
        } else {
          action = nextAction
        }
      }
    }
  })
}
```

**Comment by Andarist** [comment]
I also think that `debounce` is what u are looking for. Going to close this as solved, feel free to open a new issue though.

**Comment by Slapbox** [comment]
Sounds good to me. @shinima and @Andarist thank you both very much for your help. I'm going to play with this.

Not that it's required given the code above, but is there a timeline for a `redux-saga` release with debounce?

Thanks again to you both.

**Comment by Andarist** [comment]
Not sure, we'll try to cut a new release in following weeks.
