### ISSUE TITLE
[refactor] join(...tasks) & cancel(...tasks) should return join/cancel descriptors

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#1515]
At the moment they are internally wrapped in `all` but actually the effect type should get preserved so internal refactor is needed.

At the same time we might consider changing those signatures to:
```js
join([...tasks])
cancel([...tasks])
```
but I'm still on the fence with that, not sure which one is better - variadic arguments or a single array argument? any fresh thoughts on this one @restrry @shinima ?

**Comment by shinima** [comment]
I'm inclining to single array argument.

The problem with variadic arguments I found is that `join(singleTask)` matches both `join(...tasks)` and `join(task)`, and it is unclear that `yield join(singleTask)` will return `taskResult` or `[ taskResult ]`.

**Comment by Andarist** [comment]
You have convinced me to array argument with simplicity of input arg type to output arg type mapping 👍

**Comment by restrry** [comment]
@shinima would you like to work on it?

**Comment by shinima** [comment]
OK. I'll get it done in a few days.

**Comment by shinima** [comment]
Done in #1534
