### ISSUE TITLE
Problem with long running delay

### ISSUE THREAD

**Issue by yfr** [redux-saga/redux-saga#1516]
### Description
I have an OAuth2 refresh saga with uses delay of about an hour (`expires_in` minus 5 minutes) to refresh the `auth_token`. Sadly the delay seems to work correctly here. If I use the same code but with a delay of say 5 minutes, everything works. 

Does anyone have any problems or issues with long-running delays?

**Comment by restrry** [comment]
delay is just a wrapper around setTimeout. https://github.com/redux-saga/redux-saga/blob/5702affdcd681e5aee1371ba68cc061af10078bc/packages/core/src/internal/utils.js#L99-L108
are you sure that there are no page reloads or page [is still in focus](https://stackoverflow.com/questions/6032429/chrome-timeouts-interval-suspended-in-background-tabs) ?

**Comment by yfr** [comment]
Ah did not know about the thing with the background tab. Makes sense now.

Thank you!
