### ISSUE TITLE
How to trigger saga effects from an external function?

### ISSUE THREAD

**Issue by pupudu** [redux-saga/redux-saga#1531]
_Forgive me if this issue makes no sense. First time creating an issue in an open source repo. I will edit/update/comment as requested by anyone who'd like to help._

I made an attempt to trigger the put effect from an external module which is not a saga. Everything works except the action is not being dispatched(as far as I can understand).

Here is an updated version of the counter code-sandbox: https://codesandbox.io/s/zqmwry0lw4

### My approach:
What I am trying to do here is, instead of calling put from the saga, let an external function take care of calling it as many times as it wants. I am happy to provide more details on why I need to do that if anyone wants to know more. 

### About the Codesandbox:
- I've added two new functions. externalFunc and *Putter
  - externalFunc is to trigger the action dispatch externally to the saga.
  - Putter is to call the redux-saga put effect.
- I've disabled console.logs in counter to highlight my usecase
- I've added a console.log to the counter reducer. My target is to make that get called
- I've commented out ` yield put({ type: INCREMENT_ASYNC, value: seconds });` at line 79. That is to bring that responsibility to the externalFunc.
- I've added other code comments to describe what I've done

### The Problem:
- The INCREMENT_ASYNC action is not dispatched as expected.

Is this something technically impossible? If possible, have I missed something here?

Thanks!

**Comment by shinima** [comment]
Your issue is very clear and detailed.

In redux-saga, you can get external input via eventChannel. Or if you are using redux-saga with redux, you can manually call `store.dispatch` to trigger saga effects from an external function.

I've made another sandbox [here](https://codesandbox.io/s/xzvkmv3yyp) illustrating these two methods, have a look 😄

**Comment by pupudu** [comment]
Wow that was awesome. Apparently, eventChannels is the thing I had been looking for. I feel guilty for not reading more about it before I posted the issue. 
Anyways, Thank you, now everything works perfectly!
