### ISSUE TITLE
`delay` is confusing

### ISSUE THREAD

**Issue by shinima** [redux-saga/redux-saga#1533]
In v1.0.0-beta.1, users could import `delay` from `'redux-saga/effects'`. Here `delay` is an effect creator that means users could only use it like `yield delay(2000)`.

But users could still import `delay` from `'redux-saga/utils'`, and here `delay` is a function that returns a Promise. Users could use this `delay` either in `yield delay(2000)` form or in `yield call(delay, 2000)` form.

These two `delay`s are confusing, they have the same name and they both come from redux-saga, but has different meanings and usages.

**Comment by restrry** [comment]
imho we shouldn't export delay from `utils` to avoid confusing and implementing it in user land (if needed) shouldn't be a problem

**Comment by shinima** [comment]
I agree to remove one of them.  But I'm inclining to remove `delay` from `'redux-saga/effects'`.

Because we can use delay-function to create delay-effects, but we can not use delay-effect-creator to create a delay-Promise. In other word, delay function is more general.

And effect-creators from `'redux-saga/effects'` often create effect with corresponding type -- `call()` creates call-effect, `all()` creates all-effects, `fork()` creates fork-effects, etc.. But `delay()` create call-effects, which is not consistent with other effect-creators.

**Comment by restrry** [comment]
helpers create not corresponding effects - takeLatest returns `fork`, for example.
I think the main reason to introduce that change was a bit confusing nature of delay for newcomers. before you have import 2 different functions from saga and use them in right order, you need to understand that `delay` returns promise, that saga can handle promise correctly etc.
```js
import {delay} from 'redux-saga'
import {call} from 'redux-saga/effects'
// then in your code
function* (){
    yield call(delay, 2000)
    ...
}
```

**Comment by Andarist** [comment]
> imho we shouldn't export delay from utils to avoid confusing and implementing it in user land (if needed) shouldn't be a problem

I second that.

> before you have import 2 different functions from saga and use them in right order, you need to understand that delay returns a promise, that saga can handle promise correctly etc.

That was exactly the reason to introduce `delay` as effect. Things like `delay`, `throttle`, `takeEvery` & `takeLatest` are not technically effects, but keeping them separate was quite confusing for many people - so I've decided to just move them to effects for simplicity.

You don't have to worry about it, I'm going to move this `delay` util to separate package (`@redux-saga/delay-promise` or something) or move it out of this repository entirely and just make it a dependency of `redux-saga`.

**Comment by restrry** [comment]
@shinima @Andarist any actions points on this?

**Comment by shinima** [comment]
> You don't have to worry about it, I'm going to move this delay util to separate package (@redux-saga/delay-promise or something) or move it out of this repository entirely and just make it a dependency of redux-saga.

It seems that @Andarist will move one `delay` apart from `redux-saga`. That's good for me.

**Comment by restrry** [comment]
ok, then we need to add it as v1 as a part of breaking changes

**Comment by borrascador** [comment]
https://github.com/redux-saga/redux-saga-beginner-tutorial/issues/41

**Comment by restrry** [comment]
@borrascador what version for you use? v1 should export `delay` from `redux-saga/effects` only

**Comment by borrascador** [comment]
I was using the beta! Good save.

**Comment by magbicaleman** [comment]
If you end up here do to a google search after having your testing break. I ended up with this following, `redux-saga: 1.0.5`

*My Saga*
```
import { call, all, fork, take, cancel, delay } from 'redux-saga/effects';

import { setEmail} from '../dux/subscribe';

export function* handleInput(email) {
  yield delay(500);
  yield call(console.log, email);
}

// More code ...etc
```

```
import { describe } from 'riteway';
import { call, take, delay } from 'redux-saga/effects';

import { actionWatcher, handleInput } from './index';
import { setEmail } from '../dux/subscribe';

describe('Test handleInput saga', async assert => {
    const email = 'email@noop.com';
    const gen = handleInput(email);

    assert({
        given:'an email value',
        should:'it shoudl delay console.log by 500',
        actual: gen.next().value,
        expected: delay(500),
    })
// More code
```

Testing this was particularly confusing at first because in the [beginner tutorial](https://redux-saga.js.org/docs/introduction/BeginnerTutorial.html) they create and export "your" own delay function, and not the `effects` version. 

After reading this and understanding that `delay` this is an effect, then my assumption was that making the changes above would work, similarly how you would test for a type listener, using take which is an effect. 

But I guess what's important, is that if you're using `delay` from lodash or another source, then you'd use the `call` function effect, maybe that's the main illustration from the example.
