### ISSUE TITLE
When will 1.0 be released?

### ISSUE THREAD

**Issue by localjo** [redux-saga/redux-saga#1540]
I'm curious if there is a timeline or estimated date that v1.0 will be released and published on npm? I'm specifically wondering because of https://github.com/redux-saga/redux-saga/issues/614 

(I know I can install the beta tag from GitHub, but just wondering when it will be not be in beta anymore)

**Comment by restrry** [comment]
@localjo there is a list of issues for v1 milestone  https://github.com/redux-saga/redux-saga/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1
I'd say that's doable in ~1-2 months.

btw that logging was removed in [v0.16.0](https://github.com/redux-saga/redux-saga/releases/tag/v0.16.0)

**Comment by restrry** [comment]
I'll close as there are no possible actions points here
