### ISSUE TITLE
How the effect calls another effect and gets the return value?

### ISSUE THREAD

**Issue by yoyo837** [redux-saga/redux-saga#1548]
Forgive me for not finding reliable information on the network.

**Comment by shinima** [comment]
You can get the return-value simply as follows:

```javascript
function* foo() {
  return 'return-value-of-foo'
}

function* bar() {
  const value = yield call(foo)
  console.assert(value === 'return-value-of-foo')
}
```

**Comment by yoyo837** [comment]
@shinima Tks.
Can the `put` method do the same thing?

**Comment by shinima** [comment]
Yielding a `put` effect will returns the return-value of `store.dispatch(action)`. In most situations, `store.dispatch` simply returns the action back and you don't need to care it.

There are some edge cases that you are using redux-saga with other redux middlewares, and the return-value of `store.dispatch` may be changed by other middlewares.

**Comment by yoyo837** [comment]
For some reason, I can only use `put` to call other effects. Is the `Promise` it returns reliable?

**Comment by shinima** [comment]
If some other redux middleware returns a Promise, you can use [`put.resolve`](https://redux-saga.js.org/docs/api/#putresolveaction) to wait for its resolution. 

Say we have a `reduxFecthMiddleware` that returns a Promise for FETCH as follows:

```javascript
const reduxFecthMiddleware = ({ dispatch }) => next => action => {
  if (action.type === "FETCH") {
    return fetch(action.url);
  }
  return next(action);
};

function* gen() {
  try {
    // we can use `put.resolve` to wait for the Promise's resolution
    const response = yield put.resolve({ type: "FETCH", url: "bilibili.com" });
  } catch (error) {
    // handle error
  }
}
```

In my opinion, `put.resolve` is somewhat complicated and we can avoid using it if we change our middleware **from** *returning a Promise* **to** *dispatching another action when some asynchronous task is done*.

**Comment by yoyo837** [comment]
I fully understand what I want to know now, thank you so much.
