### ISSUE TITLE
Understanding binding to generators

### ISSUE THREAD

**Issue by slashburn** [redux-saga/redux-saga#1551]
I've been using `redux-saga `for two days now and I'm trying to wrap my head around the best way to create similar action creators. I've adapted the code I've found in the `examples/real-world` project and ran into a behaviour I don't quite understand.

```
// actions.js
export const categories = {
  request: () => action(VIDEO_CATEGORIES[REQUEST]),
  success: (response) => action(VIDEO_CATEGORIES[SUCCESS], response),
  failure: (response) => action(VIDEO_CATEGORIES[FAILURE], response),
};

export function action(type, payload = {}) {
  return {
    type,
    ...payload,
  };
}
```

I've adapted the `fetchEntity` function in the `real-world` example project to get around too much boilerplate:

```
// sagas.js
/*
* entity must have a success, request and failure method
* request is a function that returns a promise when called
* */
export function* fetchEntity(request, entity) {
  console.log('performing request');
  try {
    const response = yield call(request);
    yield put(entity.success(response));
  } catch (error) {
    yield put(entity.failure(error));
  }
}

// api.buildVideoCategoryRequest is a function that  - when executed - returns a promise
export const fetchVideoCategories = fetchEntity.bind(null, api.buildVideoCategoryRequest, categories);
```

This binding approach works perfectly if the request function (`buildVideoCategoryRequest`) doesn't require any parameters. If the `buildVideoCategoryRequest` were to require a parameter, the following worked for me: 

```
export const fetchVideoCategories = (amount) => {
  const request = api.buildVideoCategoryRequest.bind(null, amount);
  return fetchEntity(request, videoActions.mostPopular);
};
```

This function works perfectly, but I am super confused that the `return` is necessary. The `fetchEntity` function does not contain a return statement, so why do I need to write `return` `fetchEntity(...)` in the code snippet above. If I leave out the `return` statement, nothing happens.

Don't know if this binding approach is good or whether there is an easier solution to accomplish this. Also guys, thank you very much for this library. I've been using `redux-thunk` for a while and I already feel like this library is waaaay better 👍 👍 👍

**Comment by restrry** [comment]
```js
export const fetchVideoCategories = fetchEntity.bind(null, api.buildVideoCategoryRequest, categories);
```
is bound, but it's a generator function, not ordinary function, in your case.

most likely you call it in another saga as
```js
yield call(fetchVideoCategories, amount)
```
you need that `return` because otherwise `call` doesn't receive generator functions and cannot run it.

I'd say that approach make sense and could work in your case, but you need to understand how generators work.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*

**Comment by slashburn** [comment]
Ah, I see 🤔, thank you very much @restrry 👍. The reason is that even though `fetchEntity` does not have a `return` statement, it `yields` the result of a `call` function invocation. `call` returns a plain `JavaScript` object which is then consumed by `redux-saga`.

And I also found out that if I were to use a `generator function` instead of an `arrow function`, I have to `yield` the result instead of using `return`. I guess this approach is more readable and more understandable.

```
export function* watchVideoCategories() {
  yield takeEvery(actions.VIDEO_CATEGORIES[REQUEST], fetchVideoCategories);
  console.log('watchVideoCategories called');
}
export const fetchVideoCategories = function* (amount) {
  // api.buildVideoCategoryRequest is a function that returns a promise once invoked
  const request = api.buildVideoCategoryRequest.bind(null, amount);
  yield fetchEntity(request, videoActions.categories);
};
/*
   entity must be an object that has a request, success and failure function
*/
export function* fetchEntity(request, entity) {
  console.log('performing request');
  try {
    const response = yield call(request);
    yield put(entity.success(response));
  } catch (error) {
    yield put(entity.failure(error));
  }
}
```

**Comment by GaneshSaiKumar** [comment]
@restrry @sahilaug 
how can i unbind the generator after a particular event

**Comment by restrry** [comment]
afaik you cannot unbind a function (for plain js `bind` method). why not use the original function instead of unbinding?

**Comment by restrry** [comment]
in my project I usually restart the whole app on logout to be sure that that are no stale state that could be not relevant anymore.
regarding your question, you can adopt example from https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/TaskCancellation.md
```js
```javascript
function* yourSaga() {
  while (true) {
    yield take('LOGIN')
    const pollingTask = yield fork(pollingSaga);
    yield take('LOGOUT')
    yield cancel(pollingTask);
  }
}
```
```
