### ISSUE TITLE
[docs] enhance `take` effect doc

### ISSUE THREAD

**Issue by ggarek** [redux-saga/redux-saga#1552]
### Docs update suggestions

I think, it would be useful to **add explicit statement about the return value of `take` effects family**.

Same as for, say, `fork` effect is stated `returns a Task object.`

Though, it is not difficult to perceive, that `take` returns an action dispatched. It will make docs more complete if we state it explicitly, imho.

Now, it follows from code example, e.g.:

```
while (true) {
    const action = yield take(patternOrChannel)
    yield fork(saga, ...args.concat(action))
  }
```

but still is kind of implicit.

**Comment by Andarist** [comment]
This is a good suggestion, would you like to prepare a PR for this?

**Comment by ggarek** [comment]
@Andarist created a PR, plz let me know if it is ok
