### ISSUE TITLE
How to use saga to show loader for at least 1 second.

### ISSUE THREAD

**Issue by royipressburger** [redux-saga/redux-saga#1553]
Hi all.

So my question is: How would you recommend using saga to display loader for at least 1 second?
use case:
There are multiply pages in my application where I display a loader (login/ fetching data from server, etc..).
each one of this pages has in the render function:
```
render() {
    return (
         <div>
          { this.props.isLoading && <Loader /> }
          //rest of the component code 
         </div>
    )
}
```

`this.props.isLoading` is coming from redux state,
to be more specific lets take the login example:

```js
function* loginSaga() {
    try {
       yield put(Actions.LoginStarted()) // this will change the value of isLoading in the reducer to true and will show the loader
       // more code here with api call to verify credentials
       yield put(Actions.LoginSuccess()) // this will change the value of isLoading the false
    } catch {
        yield put(Actions.LoginError()) // this will change the value of isLoading the false
    }
}
```

now the easiest solution will be to add before the try `let start = new Date()`
and then before `Actions.LoginSuccess()` or `Actions.LoginError()` to add a delay like so
`yield delay(1000 - (new Date() - start))`

But if I go this way it means that for every time I show the loader I need to do the `start = ...` and the `yield delay...`

can someone think of a more generic/aesthetic solution?

**Comment by shinima** [comment]
I add `delay(1000)` to ensure loader lasts for at least 1 second in the following code. Can this solve your problem?

```javascript
function* loginSaga() {
  try {
    const timeout = delay(1000);
    yield put(Actions.LoginStarted());

    // ensure the next yield-statement spends at least 1 second
    yield all([timeout, call(somVerifyAPI)]);

    yield put(Actions.LoginSuccess());
  } catch {
    yield timeout; // If somVerifyAPI fails within 1 second, we need to wait the remaining time
    yield put(Actions.LoginError());
  }
}
```

**Comment by royipressburger** [comment]
@shinima mmmm yes it solved, but two questions
1. what does `all` returns? I need to return value from `call(someVerifyAPI)`
2. This looks like it is going to work, But you still need to add to every saga those 3 lines `const timeout ... yield all...  yield timeout` I wanted to avoid that.. Like creating a saga that warps another saga and when the wrapper see some action he start counting the delay and when he see the final action he sleeps until timeout?

Is something like this possible? is something like this even worth the work in you opinion?

```js
function* DelaySaga(otherSaga?) {
      // Here when OtherSaga starts to create delay
      const timeout = delay(1000)
      // Wait for the saga to run and somehow catch the put(Actions.LoginSuccess()) of the other saga
      yield timeout
     //release other saga to keep running
  }
}
```

Hope I was clear :)
Im just thinking of a way to avoid writing the 3 lines on every place I need that loader.

**Comment by shinima** [comment]
> Is something like this possible? is something like this even worth the work in your opinion?

Yes, it is possible. I've written a `atLeastOneSecondCall` that encapsulates the logic of waiting at one second.   I suppose that it works but I have not tested it by myself.   And you may change `atLeastOneSecondCall` to a better name.

```javascript
function* atLeastOneSecondCall(fn, ...args) {
  const timeout = delay(1000);
  try {
    const { result } = yield all({
      timeout,
      result: call(fn, ...args)
    });
    return result;
  } catch (e) {
    yield timeout;
    throw e;
  }
}

function* gen() {
  // yield call(someAPI, arg1, arg2);
  // replace your `call` with `atLeastOneSecondCall`
  yield atLeastOneSecondCall(someAPI, arg1, arg2);
}
```

**Comment by royipressburger** [comment]
@shinima Last question :)

How do you suggest to test this?
Im getting this:
```
    Expected value to equal:
      {"_invoke": [Function invoke]}
    Received:
      {"_invoke": [Function invoke]}
```

Here is the full code:
```js 
export function* applyWithDelay(context, fn, ...args) {
  const timeout = delay(defaultDelay);
  try {
    const { response } = yield all({
      timeout,
      response: apply(context, fn, [...args]),
    });

    return response;
  } catch (e) {
    yield timeout;
    throw e;
  }
}

export function* login({ payload }) {
  try {
    yield put(AuthActions.loginStarted());
    const resp = yield applyWithDelay(api, 'post', 'api/1/login', {
      email: payload.email,
      password: payload.password,
      method: payload.method,
    });
    yield put(AuthActions.loginSuccess(resp.token));
  } catch (error) {
    console.error(error);
    yield put(AuthActions.authError(error, parseErrorMsg(error)));
  }
}  

// And in test
  const action = actions.login({ email: 'test@gmail.com', method: 'email', password: '123456' });
  const generator = cloneableGenerator(login)(action);
  expect(generator.next().value).toEqual(put({ type: types.LOGIN_STARTED }));
  expect(generator.next().value).toEqual(applyWithDelay(api, 'post', 'api/1/login', action.payload)); // <-- fails here
```

**Comment by royipressburger** [comment]
Great Thanks Closing this

**Comment by royipressburger** [comment]
@shinima Hi again..

I have encountered a problem with the code we wrote, maybe you can help :)

```
export function* applyWithDelay(context, fn, ...args) {
  const timeout = delay(defaultDelay);
  try {
    const { response } = yield all({
      timeout,
      response: apply(context, fn, [...args]),
    });

    return response;
  } catch (e) {
    yield timeout;
    throw e;
  }
}
```
The problem starts when the `fn` fails (throws exception) before the `delay` is resolved.
In this case the `yield timeout` inside the `catch` is never resolved causing this function never to end.

I tried to do some debugging and figure out that when `fn` fails, if `delay` is not resolved then someone calls `CANCEL` on `delay`.
I put a `console.log` [inside the delay func](https://github.com/redux-saga/redux-saga/blob/master/packages/core/src/internal/utils.js#L105) and saw that someone call the the cancel.

Is that a bug? 
can you see a way to implement the behaviour without the need of saving the start timestamp?
```
const start = new Date();
....
catch {
 yield delay(.... - start)
 throw e
}
```

**Comment by shinima** [comment]
Oh, I see the problem. It is my fault. When `apply(context, fn, [...args])` fails, saga will cancel the pending `timeout` so the `timeout` will never be resolved. We can switch to a `delay` that does not support cancellation. This seems a little weird, but it should work:

```javascript
// delay2 is copied from delay
function delay2(ms, val = true) {
  let timeoutId
  const promise = new Promise(resolve => {
    timeoutId = setTimeout(() => resolve(val), ms)
  })

  // comment this line to disable support for cancellation
  // promise[CANCEL] = () => clearTimeout(timeoutId)

  return promise
}

export function* applyWithDelay(context, fn, ...args) {
  // this timeout will not be cancelled, and will always resolve after `defaultDelay`
  const timeout = delay2(defaultDelay); // <-- using `dealy2` instead of `delay`
  try {
    const { response } = yield all({
      timeout,
      response: apply(context, fn, [...args]),
    });

    return response;
  } catch (e) {
    yield timeout;
    throw e;
  }
}
```

This method seems a little strange, maybe using another method that saves the start time is better, since you only need to save a start time in `applyWithDelay`. Anyway it is up to you. 😄

**Comment by royipressburger** [comment]
@shinima Thanks.. Probably missed it in the documentation :)
