### ISSUE TITLE
Figure out the npm package README situation

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#1556]
`packages/core` is being published as redux-saga, this means that it has to have a README otherwise http://npmjs.com/ will show an empty page - not sure what's the best way to approach this because we want to have kinda the same thing on GitHub & on npm, but both READMEs have to be located at different file paths

**Comment by shinima** [comment]
How about keep a simple/slimmed README on npm that includes a link to the full README on github/redux-saga.js.org. [Babel](https://www.npmjs.com/package/@babel/core) is using the similar readmes on npm.
