### ISSUE TITLE
What is the purpose of using Symbol instead of String in v1.0?

### ISSUE THREAD

**Issue by dangh** [redux-saga/redux-saga#1559]
### Description

Hello,

When I mock a module with Jest, the effects created in this module are not recognized by redux-saga and failed all the tests.

You can checkout the second test in this repo:
https://github.com/dangh/test-jest-saga-repro

I trace down to this line https://github.com/redux-saga/redux-saga/blob/29fbd1b50d7128d3b9e4ff4105ae3b84ed2a2905/packages/core/src/internal/io.js#L217

and figured out that I have to re-require all my modules as well as redux-saga so `runSaga()` can recognize `IO` symbol.

It makes the tests become verbose with lots of redundant requires. Is there's any reason we use Symbol instead of string?

**Comment by Andarist** [comment]
The reason is that they are truly unique, unlike strings. Your tests should share the same symbols as redux-saga's core, so not sure why this happens - we might look into your repo later to check this out.

**Comment by Andarist** [comment]
Interesting, it seems that we might need to revert using those symbols, cc @restrry @shinima

**Comment by shinima** [comment]
Symbols seems to bring some inconvenience and lead to some subtle bugs (I believe that #1562 is caused by symbols). Though symbols are more suitable in theory, it is good and practical to using strings.
