### ISSUE TITLE
Question: proper way to write cancel logic

### ISSUE THREAD

**Issue by landvibe** [redux-saga/redux-saga#1560]
I want to know how to write cancel logic.
Below code has a bug because cancel effect is non-blocking.
```js
function* fetchData(action) {
  const timelineId = action.timeline.id;
  try {
    console.log("fetch-1", action.timeline.likes);
    yield put(actions.setLoading(true));
    yield put(actions.addLike(timelineId, 1));
    yield call(callApiLike);
  } catch (error) {
    console.log("fetch-2", action.timeline.likes);
    yield put(actions.setError(error));
    yield put(actions.addLike(timelineId, -1));
  } finally {
    console.log("fetch-3", action.timeline.likes);
    if (yield cancelled()) {
      console.log("fetch-4", action.timeline.likes);
      yield put(actions.addLike(timelineId, -1));
    }
    console.log("fetch-5", action.timeline.likes);
    yield put(actions.setLoading(false));
  }
}

export default function* watcher() {
  yield all([takeLatest(types.REQUEST_LIKE, fetchData)]);
}
```
When two REQUEST_LIKE actions have been dispatched, the first action is cancelled.
The flow is like below
```
Action-1: fetch-1 
Action-1: fetch-3 
Action-1: fetch-4 
Action-2: fetch-1 
Action-1: fetch-5 ❶
Action-2: fetch-3 
Action-2: fetch-5 
```
❶ The first action's `setLoading(false)` is executed after the second action's `setLoading(true)`.
So the loading state is false in the middle of api call.
How can I fix this code?
codesandbox link: https://codesandbox.io/s/ww0j00ylow

**Comment by shinima** [comment]
The simplest way to handle this is to add `yield delay(0)` at the beginning of `fetchData`. That means executing the body of `fetchData` asynchronously, so the cancellation of previous invocation will always be executed before the next execution of `fetchData`.

```diff
function* fetchData(action) {
+  yield delay(0)
  const timelineId = action.timeline.id;
  // other code...
}
```

I just come up with this simple solution at the moment, but I think there should be some better ways.

**Comment by landvibe** [comment]
@shinima thank you for the solution.
I agree that `there should be some better ways`

**Comment by Andarist** [comment]
Actually the problem lies here in smth different - put effects are somewhat scheduled (within a sync frame). This means that if you should reset ur flag ASAP and only then "revert" ur `addLike` action (if cancelled ofc).

So your code should look like this:
```js
function* fetchData(action) {
  const timelineId = action.timeline.id;
  try {
    console.log("fetch-1", action.timeline.likes);
    yield put(actions.setLoading(true));
    yield put(actions.addLike(timelineId, 1));
    yield call(callApiLike);
  } catch (error) {
    console.log("fetch-2", action.timeline.likes);
    yield put(actions.setError(error));
    yield put(actions.addLike(timelineId, -1));
  } finally {
    console.log("fetch-3", action.timeline.likes);
    yield put(actions.setLoading(false));
    
    if (yield cancelled()) {
      console.log("fetch-4", action.timeline.likes);
      yield put(actions.addLike(timelineId, -1));
    }
  }
}

export default function* watcher() {
  yield all([takeLatest(types.REQUEST_LIKE, fetchData)]);
}
```

Hope that helps.

**Comment by landvibe** [comment]
@Andarist
I think it`s not intuitive and easy to make a bug.

**Comment by Andarist** [comment]
I agree - we can't guard you automatically from this though. Would be good to explain this better in the docs though.
