### ISSUE TITLE
rewrite of redux saga

### ISSUE THREAD

**Issue by velociwabbit** [redux-saga/redux-saga#1561]
After attempting to rewrite most of the code several times so that it is comprehensible to mere mortals (such as yours truly) I have given up the effort. Mind you not because the concept of redux saga is complicated (it isn't ) but instead because of the time it will take to unwind all the gordian (knotlike)  modularization and cross references it performs internally.

My motivation for this rewrite is because I am trying to make code that i wrote maintainable by other mere mortals and redux saga is the weakest (or most convoluted) link. 

The problem is that once you start using redux and redux saga it is all but impossible to remove from one's code base.  This had non trivial consequences when combined with the new version of react router and redux forms.

I have successfully removed redux forms and have rewritten router completely to make it simpler to use, maintain and follow.  (except for the regex matching code which is imported by router anyway) but i do not have time to do the same for saga without some help.

So my question is the following... has there been a rewrite scheduled for this code base?  
And if so who is leading it so that I can offer to help?

**Comment by Andarist** [comment]
Could you rephrase your question? Are you saying the redux-saga's internal code is convoluted & hard to follow and you'd like it to be simpler?

**Comment by shinima** [comment]
Redux-saga itself is somewhat complicated so the code is convoluted too. Things get more complicated that we do not use modern JavaScript (e.g. [createTaskIterator](https://github.com/redux-saga/redux-saga/blob/29fbd1b50d7128d3b9e4ff4105ae3b84ed2a2905/packages/core/src/internal/proc.js#L114-L149)) to make redux-saga run in old browsers.

I've write [little-saga](https://github.com/little-saga/little-saga) that simplifies redux-saga a lot, you can read the source code of little-saga and it should be much easier to understand. Hope this will help you understand the saga internals. There are some differences between little-saga and redux-saga, and I list them in the doc (but sadly, all the documentation is in Chinese 😂).

**Comment by velociwabbit** [comment]
I am trying to be as polite and supportive as possible. I have no idea what
the acceptance rate, bug count or internal reputation of redux saga is at
FB but i have been using it for nearly two years and  it is clear to me
that it, combined with redux implicitly creates a message pump within
javascript.  Anyone who wrote mfc or simple windows c/c++ code has horror
stories about message pumping and trying to debug arcane anomalies. This
puts the burden of clarity on both the end user code and the code that
mandates message pumping.

Here is an example of the problem a reasonably adept programmer could
rewrite most of the 30 or so module of saga into several less modularized
ones that are easier to follow and will be easier to extend.  My guess is
that a good programmer could reduce this 1500 line package to 500 or so
lines of clearly written code that could be understood by simply reading
the code without requiring referencing of external packages or a table of
contents/index to figure out whether obscure terms are functions or
literals or some combination of the two are broken out into separate
modules that require back and forth switching to follow the code.

For example fork and take and takeevery and all the permutations use
literals that look like functions (IO etc) that are created using other
functions (instead of simply hardcoding '@@redux-saga/IO' .  While in
theory such separation is useful in practice, given that the ONLY code that
uses these symbols is redux saga code this is abstraction run amok.

Another good example is the separation of proc.js with runSaga and its
default reference in index.js.  proc is only used with runsaga. Why are
they separated?  why not reduce the total code base by combining these
obviously interdependent modules into one that removes most of the
complexity of formatting and error checking and then calling in to proc
which then performs many of the same tests before calling individual
methods.

This is abstraction and complexity for no useful reason.

Here is another exampe. takevery takelatest etc. all reference the same
modules to build their code. So what is the point of putting each of these
is separate modules. All it does is make the code more complex.  The end
result is that the same modules are imported into ones code base no matter
which options are chosen so why not just consolidate these into a well
formed module with multiple exports?

Here is another one. Abstracting fsmiterator from makeiterator is nothing
short of infuriating. fsmiterator is unnecessary code or is it the
package.json that references another code base that is unnecessary?  or
both?  And wtf is a package.json ' Prepared monorepo structure' ?
Whatever it is it reeks of pompous insecurity.

This is not software. it is a contest by sophomoric imbeciles  to see who
is cleverererer!

**Comment by velociwabbit** [comment]
It is not that redux saga is hard to understand...

Redux saga is a glorified message pump disguised as generator programming.

The problem is that message pumping is really hard to get right. And
removing it requires a deep understanding of both the message pump software
and the end user software that depends upon it.

The solution therefore is to make the message pump as simple as possible to
use (and remove) from a project. In its present form redux saga does
neither.

One reason why linux is so popular is that it is more reliable and easier
to maintain(than mach or gnu)  because linux is not based upon a message
handling micro kernel.   In theory micro kernels are better but in practice
they have to be implemented by mortals which makes them the communists of
operating systems.

**Comment by Andarist** [comment]
> I have no idea what the acceptance rate, bug count or internal reputation of redux saga is at FB 

Not sure why do u mention FB here - this is not FB project, I personally don't know if it's even used anywhere in the FB apps.

> combined with redux implicitly creates a message pump within javascript.

Right, but also - javascript itself is a message pump based (referring to the event loop). Also this message pump is imho quite explicit, this is the whole point of redux - to centralize message receiving point (to a reasonable extent) & make order of actions predictable.

> Here is an example of the problem a reasonably adept programmer could rewrite most of the 30 or so module of saga into several less modularized ones that are easier to follow and will be easier to extend.

I actually believe this is not a valid accusation, because the whole complex logic is actually located in a single file (proc.js), other files are far easier to understand and you shouldn't need to jump through the codebase that much to understand how the whole thing works, because as mentioned the only thing that needs better understanding is proc.js.

> Another good example is the separation of proc.js with runSaga and its default reference in index.js.  proc is only used with runsaga. Why are they separated? 

Because actually proc is also used by proc. So the separation here is IMHO completely valid.

> why not reduce the total code base by combining these obviously interdependent modules into one that removes most of the complexity of formatting and error checking and then calling in to proc which then performs many of the same tests before calling individual methods.

If you feel they those files are duplicating some efforts, please point me to exact lines - I'd love to improve the lib by removing unnecessary code.

> Here is another exampe. takevery takelatest etc. all reference the same modules to build their code. So what is the point of putting each of these is separate modules. All it does is make the code more complex.  The end result is that the same modules are imported into ones code base no matter which options are chosen so why not just consolidate these into a well formed module with multiple exports? 

I guess this is a matter of personal tase, but imho having separate files for those makes perfect sense as they are independent from each other and their source code is often easier to read without the surrounding code.

> Here is another one. Abstracting fsmiterator from makeiterator is nothing
short of infuriating.

They both are different things, while I agree that maybe their names could be improved the abstraction here makes sense, because we need `fsmIterator` and if we would have only this one then code calling `makeIterator` would actually be more convoluted than it is now.

**Comment by velociwabbit** [comment]
My apologies about the FB comment I just assumed that using the term Redux was copyrighted .

As I said I am willing to rewrite the entire repo with a bit of support from anyone.

For example I have distilled my usage 4 key functions of the repo down to these 4  1 or two line module implementation but for some reason I am not able to cause them to behave as saga does.  If it is a small problem I will submit these as substitutions (with appropriate abstractions) as possible simplification and performance optimizations

 Note that i have written them out here in wide form to illuminate what the code is doing.

If anyone can figure out why these do not work (which was the original reason for my post) I would be very appreciative.

(Also to hopefully demonstrate that modularization and abstraction are sometimes overkill. Or be illuminated about what i am missing   )



```
export const fork       =   (fn, ...args    ) =>(          not yet working                     { ['@@redux-saga/IO'] : true , type : 'FORK'      , payload : getFnCallDesc('fork', fn, args)        } )
export const call       =   (fn, ...args    ) =>(                                              { ['@@redux-saga/IO'] : true , type : 'CALL'      , payload : getFnCallDesc('call', fn, args)        } )
export const put        =   (channel, action) =>(  action === null || action === undefined  ?  { ['@@redux-saga/IO'] : true , type : 'PUT'       , payload : { channel : null    , action : channel } } 
                                                                                            :  { ['@@redux-saga/IO'] : true , type : 'PUT'       , payload : { channel : channel , action : action  } } )
export const cancelled  = (   ) =>  (                                                          { ['@@redux-saga/IO'] : true , type : 'CANCELLED' , payload : {   } } )
```

**Comment by Andarist** [comment]
> For example I have distilled my usage of a few key functions down to these one ( or two) line module implementations but for some reason I am not able to cause them to behave as saga does. If it is a small problem I will submit these as substitutions (with appropriate abstractions) as possible simplification and performance optimizations

If you need any help with that please reach out to me. I'm happy to help.

The only "convoluted" part of the codebase you have directly mentioned are effect creators - which I don't really agree on. It's super thin abstraction and in the long run makes a code easier to read (at least for me) because you don't have to focus your eyes on repeated returned nested objects - which would span across multiple lines & would cause extra indentation being added. This part of the code is also super stable (because it's so easy) and we just don't have to come back to it very often.

You are mentioning also this:
> If anyone can figure out why these do not work (which was the original reason for my post) I would be very appreciative.

But I'm not sure what do you refer to, could you be more precise?

**Comment by velociwabbit** [comment]
Thanks for the offer of help.  

I just want to confirm that my understanding of these functions is correct in that 

1 - they ultimately produce a set of messages in the format:
 {
 '@@redux-saga/IO'  : true     
, type :  'FORK'  //  || 'PUT' || 'CALL' ...    
, payload : {  channel  : xxx  , action : xxx } // or whatever is returned from getFnCallDesc
 } 

In other words that  there is no other layer such as passing the message as a function /closure or as an object reference?

Perhaps in the design documents there is a listing of what outputs each of these function calls should produce?  

(as an aside i removed the brackets from the  ['@@redux-saga/IO']  because they were unnecessary.(I believe that either way should work with the new syntax but i am not 100% certain.

if I understand these calls and others they should be able to be translated directly in to message literals without all the extra code and abstraction.  Perhaps there is a good reason to abstract the rest of the code base but it seems to me that put, get, takeevery, takelatest, cancel and fork    combined with a simplified  createMiddleware could be its own really simple stand alone repo?

If so i am at your disposal to assist

**Comment by velociwabbit** [comment]
yes createMiddleware is indeed complex... i was hoping to bite off bits at a time and see if i could make a meaningful subset that mere mortals (such as myself) can follow.

The reason why a separate repo makes sense is that the scope of saga is very broad (or at least broader than my imaginings) and substetting it might reduce the overall complexity by splitting it into two stand alone repos.

My goal is to reduce the difficulty factor in  debugging    redux message stack issues.   This problem is several-fold.

1 - many many messages to trap

2 - the interrupt stack in browsers rarely have user code when these problems occur (they end up mostly in react or redux code   modules)

3 - saga is inherently complex due to the problem it solves

4 - It is hard to figure out what happens betweeen redux, react-readux, react router and redux-saga if you are not intimately familiar with all four.

5 - saga is not even the hardest of these modules to debug... connect in redux  is really, really hard to follow.

I have written many types of software, from control systems,  protocols and compilers to end user full stack apps and when something reaches a level of complexity that it cannot be easily debugged with the available tools it is a warning sign that future maintenance and upgrades will be very hard.

Therefore I am volunteering to (with the help of you and others ) to rewrite a subset so that saga is not the most complex link in the chain.

**Comment by velociwabbit** [comment]
_Have you seen our babel plugin that works with v1-beta? It helps significantly with showing the user code that actually triggered an error._

no I have not... this will help a great deal. I will try it immediately.

re Plan.

I will work on one. 

What i propose to do is to attempt to consolidate all of saga into a single very large file and then subset it into the sections that (in theory) would make a useful subset.   I have attempted this several times before by replacing references with either duplicates of the actual functions or memoized literals where possible.  (It is my process for learning how some repos work)

Once i have this  completed I will share it as a working detailed spec to evaluate.

I realize this is not so much of a plan as a bottoms up decon/reconstruction but it really a great mechanism to ensure  we are all on the same page so to speak.

(It is also kind of fun like putting together a giant puzzle!)

**Comment by velociwabbit** [comment]
This might be one of the most intriguing javascript statements i have ever seen. 
I understand that you are destructuring an  array with [context,fn]  = fn 

but what does the ; do ?  I have tried it without it an no luck

 
```
function getFnCallDesc(meth, fn, args) {  let context = null
           
             if (is.array(fn)) {      ; [context, fn]    = fn  } // what does this   do
        else if (fn.fn) {             ;({context, fn }   = fn) }  
             if (context && is.string(fn) && is.func(context[fn]))   fn = context[fn]
                return { context, fn, args }
}
 
```

**Comment by Andarist** [comment]
it doesnt do anything, in this case. It being there Is partially caused by ASI (Automatic Semicolon Insertion). prettier has put it in the code - preventing bugs caused by ASI. Technically it could check previous line to see if this semicolon is needed, but prettier takes a shortcut and always inserts a semicolon at the beginning of possibly vulnerable line. This happens because we are using `--no-semi` option.

What it prevents? Smth like this:
```js
fn()
[a, b] = c
```
so it wont try to access returned value from fn call, but rather destructure the c variable

**Comment by velociwabbit** [comment]
Thank you for precisely highlighting what is confusing.

```
fn()
[a,b]=c
```

should destructure the c variable  but it doesn't.  I am confounded why there is an implicit access to the returned value from fn() on the next line?

is it that 
"
fn()[a,b] 

"

 could be interpreted as accessing a possible xxx [a,b] = c  which might do something?  (assuming the return value of fn() is xxx) ?  

But any function () with no valid {}   or =>  on the next line should automatically be treated as a stand alone call with the  new line as the  ; equivalent?

**Comment by Andarist** [comment]
Well this exact example is kinda useless, as it will only result in throwing a ReferenceError if you try to run it ("Invalid left-hand side in assignment"), but it's a runtime error and not a parsing error.

Even though I've done some work around babel and I know my fair share about the JS I can't really answer your question in full - reading the language spec is really hard 😉 

In general from what I know the code parsing doesn't like to hold too much state (most approaches can only peek at next token), I guess it's mostly because of perf reasons. EDIT:// after thinking about it a little it's probably not rly keeping track of state, but rather about the fact that we shouldn't "revisit" created nodes, parsing is always left to right (without possibility to correct created nodes), so it's not possible (possibly for perf reasons) to i.e. change a node back when the parser could make a conclusion that it would make more sense for it to be something different considering gained knowledge from next tokens/nodes

So coming back to ASI - when the parser gets to `fn()` and peeks at next symbol which is `[` it has to assume what kind of AST node it might produce in this context, having only es5 (no destructuring) in mind and knowing that JS is always backwards compatible it has to assume that this is property access and thus producing MemberExpression (using babel type).

Not sure if this answers your question completely, I'm kinda tired and maybe this was a bit chaotic. If you still have questions about it, please be more precise and tell me which parts of this are confusing so I can help you understand this better. Cheers!

**Comment by velociwabbit** [comment]
You are a mensch!

It has been a few years since i have written a lookahead compiler but your answer makes sense. 

(And for others that might run into the same issue somewhere else )  the bottom line is that destructuring as a capability of es6 exposes unobvious behavior from js by treating   statement newline  [  ...  

```
f()
[  // other array stuff
```

as one statement instead of two.

On a related note  I have been trying to rewrite some of your code so that my feeble brain can understand it  more easily and i have come across another interesting syntax usage.

This is your code for throttle... (i will show my changes that are similar for throttle below )

```
function throttle(delayLength, pattern, worker, ...args) {
  let action, channel

  const yActionChannel = { done: false, value: actionChannel(pattern, buffers.sliding(1)) }
  const yTake = () => ({ done: false, value: take(channel) })
  const yFork = ac => ({ done: false, value: fork(worker, ...args, ac) })
  const yDelay = { done: false, value: delay(delayLength) }

  const setAction = ac => (action = ac)
  const setChannel = ch => (channel = ch)

  return fsmIterator(
    {
      q1() {
        return { nextState: 'q2', effect: yActionChannel, stateUpdater: setChannel }
      },
      q2() {
        return { nextState: 'q3', effect: yTake(), stateUpdater: setAction }
      },
      q3() {
        return { nextState: 'q4', effect: yFork(action) }
      },
      q4() {
        return { nextState: 'q2', effect: yDelay }
      },
    },
    'q1',
    `throttle(${safeName(pattern)}, ${worker.name})`,
  )
}

```
And here is my interpretation of throttle (using my own layout for clarity of understanding instead of adherence to lint etc.)
```
 const  throttle = (delayLength, pattern, worker, ...args)=> {  let action, channel
        return fsmIterator( 
                {   q1 : ()=>({ nextState: 'q2', effect:   { done: false, value: actionChannel(pattern, buffers.sliding(1)) }  , stateUpdater:  ch => channel = ch      }  )
                ,   q2 : ()=>({ nextState: 'q3', effect:   { done: false, value: take(channel)                              }  , stateUpdater:  ac => action  = ac      }  )
                ,   q3 : ()=>({ nextState: 'q4', effect:   { done: false, value: fork(worker, ...args, ac : action)         }                                           }  )
                ,   q4 : ()=>({ nextState: 'q2', effect:   { done: false, value: delay(delayLength)                         }                                           }  )   
                }
                ,  'q1', 'throttle(' +  safeName(pattern) +' , ' +   worker.name +'  ) '   )

}
```


Other than typo's are these two equivalent or is there something else going on in yours?

**Comment by Andarist** [comment]
If u refer to the object shorthand syntax used for methods there then there is a difference, but one that doesn't affect us anyhow.

Our methods can be bound and yours not (as they are arrow functions). So the `this` and stuff works differently between them. But as I said - that difference doesn't really matter here.

Other than that we also preserve references to helper functions (`stateUpdater`s) by hoisting & closing them over, instead of recreating new functions (and thus "pressuring" GC) whenever `stateUpdater` gets called. Probably doesn't matter either, so kinda whatever - I just got accustomed to preserving references whenever possible.

**Comment by velociwabbit** [comment]
In small space I agree with you but most developers (such as myself) now have 4k screens.  To use the narrow code layout wastes 95% of the available space on screen. I cannot remember the last time i used a small screen for development. And one can put much more useful content on screen by laying it out as i have.

IMHO the people that advocate using 80 characters per line (ish) and therefore only showing on function call  per screen of real estate are just silly and not to be taken seriously

**Comment by velociwabbit** [comment]
as i said punch cards are the natural extension of your argument :)  

120 columns is fine for 1988 or if efficiency of development is low priority 
![image](https://user-images.githubusercontent.com/9357805/45695101-926b1a00-bb15-11e8-972e-1ff3f483b6de.png)

fully used screen   3x info density (mocked up here ONLY to illustrate my point...  ) 

 (Plus zoom in and out to see if necessary. 
![image](https://user-images.githubusercontent.com/9357805/45695195-c34b4f00-bb15-11e8-8a63-aa7149d84698.png)

I am still dumbfounded that this argument still exists. The earth is not flat, evolution exists in nature but not in how programmers take advantage of available screen real estate?

Go figure!

**Comment by Andarist** [comment]
Well, that is still just your personal preference. Ours is just different 😉A good thing about programming is that you can write in various languages and in various styles so everyone can achieve his/her happiness.

**Comment by velociwabbit** [comment]
Yes , indeed!

Gulliver's travels did not have a wide-endian vs-narrow-endian  but should have!

/jpr

**Comment by neurosnap** [comment]
I don't want to derail the conversation, but I recently adapted `redux-saga` to be used without redux: https://github.com/neurosnap/cofx

It's not 1:1 parity (e.g. no forking model) but I think covers quite a few common use-cases, especially for node io.

**Comment by Andarist** [comment]
Cool project, nice to see exploration in this area. Just adding a note - `redux-saga` can be actually used without `redux` too 😉

**Comment by neurosnap** [comment]
Oh nice!  I thought it might be possible. Is there a guide on how to do it
somewhere?

**Comment by Andarist** [comment]
You can check out a working example here - https://codesandbox.io/s/1yq1lx77jq . It's working with current v1-beta.2, to make it work with v0.x you would have to replace `channel` config option with `subscribe` (which works slightly differently, but we have it described in the docs - I think).

All options - `dispatch`, `getState` & `channel` are just to handle `put`, `take` & `select`. It should be usable without any config for use cases not needing those 3.

**Comment by velociwabbit** [comment]
At the risk of exposing my inner bone head. I have been playing around with your new sandbox and it is really cool yet really mysterious as to what it replaces or uniquely provides from a functionality standpoint?
 
```
lelet counter = 0 
const emitter = new EventEmitter()
const channel = stdChannel()
emitter.on("action", channel.put)


runSaga(({ channel,dispatch: out => { emitter.emit("action", out) } , getState: () =>{ "sample"} }),
  function* () {
    const chan = yield call(() => eventChannel(emit => {  
                        const id = setInterval(() =>   emit(counter++) , 1000)
                        return () => clearInterval(id)
                         }))
  while (true) {
    const received =                yield take(chan) 
    yield fork(function* () {       yield delay(1000)
                                    yield put({ type: "RECEIPT" }) 
    })
    const r = yield race({ response: take("*"), timeout: delay(5000) })
    r.response && console.log("  counter = " + counter, r.response)
  }
})
 
```
I have rewritten your code to see how i can break it and the above code works.

As far as i can tell it sets a timer then manages a message stack??? 

I also eliminated as many levels of recursive indirection as possible just to make sure that I understood what the code does.

(I also eliminated the try, finally code because there was a while(true) in between)

Perhaps I should rephrase... I know what it does, I just don't know why?

**Comment by Andarist** [comment]
The code itself on the sandbox is not mine, I just have forked it and made it work with `stdChannel`, so other than that I won't discuss the logic there.

The difference between `eventChannel` and `stdChannel` is that later is unicast (single emit hits a single observer, supports buffering) and the latter is multicast (single emit hits all current observers, doesn't support buffering).

`stdChannel` is used internally to emit redux actions to a saga runtime, but also can be used to connect any other IO (other than redux) with saga (as the integration layer between redux and the saga is actually very thing and the saga is complete independent of the redux) with `{ dispatch, getState, channel }` config object (used with `runSaga` API).
