### ISSUE TITLE
How to use redux-saga with flow type in CommonJS?

### ISSUE THREAD

**Issue by jnwan** [redux-saga/redux-saga#1563]
How can I define the .js.flow file? the current one in flow typed repo is for ES module.
https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/redux-saga_v0.16.x/flow_v0.56.0-/redux-saga_v0.16.x.js

Thanks

**Comment by Andarist** [comment]
This is the typings issue & not the issue of redux-saga itself. As it's not actionable here and we do not have flow typings in the repository itself I have to close this issue. Please make an issue in flow-typed repo.
