### ISSUE TITLE
Question: Test Saga with getFormValues()

### ISSUE THREAD

**Issue by LYC-kosic** [redux-saga/redux-saga#1565]
I have a saga which using redux-form getFormValues() to select form  value from global state. I try to create mock store to pass mock state to saga and successfully to get the form value to do testing. But it stuck on race() and cannot move on to get the success response. Is there anyway to do the testing?

Here is the saga:
```javascript
export function* watchLogin() {
  yield takeEvery(LOGIN, loadLogin);
}

export function* loadLogin(action) {
  var login = yield select(getFormValues('login'));
  const { response, error } = yield doAsync(login, loginRequest) || { }
  if (response) {
    yield put(onLoginSuccess(response))
  } else {
    yield put(onLoginFailure(error ? error : "TIMEOUT")); 
  }
}

function* doAsync(func, ...args) {
    const { funcResponse, timeout } = race({
      funcResponse: call(func, ...args),
      timeout: call(delay, TIMEOUT)
    });

    return funcResponse || { }
} 
```

And is the test code: 
```javascript
describe('When execute process', () => {
      it('Should export ON_LOGIN_SUCCESS response', ()=>{
           const props = {
              form: {
               login: {
               values: {
                 username: "foo",
                 password: "bar"
                       }
                      }
                    }
                  }};
           const sagaMiddleware = createSagaMiddleware();
           const mockStore = configureStore([sagaMiddleware]);
           const store = mockStore(props);
           sagaMiddleware.run(rootsaga);
           store.dispatch(loginAction);
           /...Do Test.../
    });
 });
```

**Comment by Andarist** [comment]
Without working code (or rather not working) we cannot do much to help you. Could u prepare a repro?

**Comment by LYC-kosic** [comment]
Sorry, do you mean the remaining of test code? Due to the running of saga is stuck on doAsync(), so the remaining part of test code still not finish. But I expected saga will put onSuccess response.

**Comment by Andarist** [comment]
I meant the complete working (runnable) code in a separate repository or on smth like codesandbox.io .

**Comment by restrry** [comment]
closed due to inactivity. fell free to reopen with a reproducible case
