### ISSUE TITLE
Are there any plans to update beta to npm, since it is already merged on master?

### ISSUE THREAD

**Issue by Verurteilt** [redux-saga/redux-saga#1567]
I would really like to use effects such as `takeLeading`, but the latest version published on npm is _0.16.0_ and the version that contains such effect is _v1.0.0-beta.1_, also I would like to point out that the last commit on such beta version was on May.

**Comment by restrry** [comment]
there are several leftovers for v1. https://github.com/redux-saga/redux-saga/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1
mean time probably we could release beta-v2. @Andarist ?

**Comment by Andarist** [comment]
> mean time probably we could release beta-v2. @Andarist ?

Yeah, want to do it this weekend 😃

**Comment by Verurteilt** [comment]
Thank you very much guys.

**Comment by Andarist** [comment]
the new beta is out, gonna write down the release note some time soon
