### ISSUE TITLE
create and authenticate automatically with createUserWithEmailAndPassword, is this correct?

### ISSUE THREAD

**Issue by henriqueweiand** [redux-saga/redux-saga#1570]
#### Description of the bug/issue

I'm using the call:

`channelLogin = yield call (reduxSagaFirebase.auth.channel);
`

to check the status of the user session inside a panel, but within it I can register new users to other people, at this moment I noticed that when using:

`createUserWithEmailAndPassword
`

Having already authenticated, the use of this method calls the change in the channel as if the new user was performing a login.

Is this behavior correct?

**Comment by Andarist** [comment]
Sorry, but your issue is not clear to me - you'd have to describe it in more detail to get an answer.

**Comment by restrry** [comment]
closed due to inactivity
