### ISSUE TITLE
Why is `select` not blocking?

### ISSUE THREAD

**Issue by Slapbox** [redux-saga/redux-saga#1574]
I'm a bit confused by this choice. It seems like if you need `select` that you need the value before continuing in most cases.

To be fair, I've used `redux-saga` for half a year without this causing a single issue, but today I'm running into an issue with `select` not returning a value in time.

What's the recommended method to work around this?

**Comment by Andarist** [comment]
`select` is just a wrapped `getState`. It can't be blocking because there is no "releasing trigger". I suspect that by the time ur select got yielded ur state-changing action didnt yet hit the reducers.

**Comment by Slapbox** [comment]
Thanks for your reply @Andarist. I was able to work around this, but I'm still a bit confused.

In this particular case I'm not changing any state. I use re-reselect to cache the response to this particular select statement, and while that's usually no problem, I guess I found a case where the response wasn't fast enough and I got back an array full of pending `select`'s instead of an array of the objects I expected.

Can you elaborate on the concept of a "releasing trigger" a tiny bit? The trigger is not, as I understand it, necessarily tied to state, but to the status of the command itself. For example, `take` blocks until it's fulfilled. Couldn't `select` block a saga until it's fulfilled/wouldn't this be desirable in some circumstances?

**Comment by Andarist** [comment]
> The trigger is not, as I understand it, necessarily tied to state, but to the status of the command itself.

Exactly. And as `select` is just a wrapped `getState` it has no status - or rather it gets to fulfilled state right away automatically & synchronously.

**Comment by Slapbox** [comment]
It's synchronous, but the overall code execution of a saga containing `select` isn't necessarily. What's the right way to handle rare cases where `select` takes long enough that it's not ready in time for the following lines of code that depend on it. For example, when using `reselect` to get some derived state which is computationally intensive?

**Comment by Andarist** [comment]
You will have to walk me through this problem a little more.

> It's synchronous, but the overall code execution of a saga containing select isn't necessarily.

Kinda depends on how you look at this, the saga code around `select` is executed synchronously. When you yield select effect, it is received by a saga runtime, it's executed (getState) and its result is returned to your saga synchronously, so the code line just after you yield select is executed "right away".

> What's the right way to handle rare cases where select takes long enough that it's not ready in time for the following lines of code that depend on it. For example, when using reselect to get some derived state which is computationally intensive?

Even when using reselect you cannot "request" a recomputation and wait for the result asynchronously. reselect performs the recomputation synchronously.

**Comment by Slapbox** [comment]
Wow I was very unclear. Sorry about that.

I should have documented what I was experiencing at the time a bit better to make this easier to discuss. I'm going to close this for now since it's not actively causing me trouble, but if I run into this again I'll come back with a better explanation with code/pictures.

Thanks as always for all your help @Andarist!
