### ISSUE TITLE
takeLatest waits for previous promises to be resolved before resolving last promise.

### ISSUE THREAD

**Issue by reyanshmishra** [redux-saga/redux-saga#1576]
This is more like a question 

I am making api call using takeLatest and everything works perfectly fine as excepted but if I make 10 api calls at the same time it picks up the 10th one as returns the result but before returning the result it waits for all the api calls to be resolved I don't know how to overcome this problem. Am I making any mistake?

I tried it with delay in codesandbox here https://codesandbox.io/s/0x143670v and its seems to be working fine as expected but it with real network call it doesn't here is the youtube link https://youtu.be/gl92JMmN2Sk

I am using this same code as code I have given above except I am making real api call instead of delay.

```
/**
 * Gets the repositories of the user from Github
 */

import { call, put, select, takeLatest, takeEvery } from 'redux-saga/effects'
import { LOAD_REPOS } from 'containers/App/constants'
import { reposLoaded, repoLoadingError } from 'containers/App/actions'

import request from 'utils/request'
import { makeSelectUsername } from 'containers/HomePage/selectors'

/**
 * Github repos request/response handler
 */

export function* getRepos() {
  // Select username from store
  const username = yield select(makeSelectUsername())
  const options = {
    method: 'GET',
    mode: 'cors',
    cache: 'no-cache',
    credentials: 'same-origin',
    headers: { 'PRIVATE-TOKEN': 'z8f89iatcYzSSrg8A-gd' }
  }
  const ul = `api_url`

  try {
    // Call our request helper (see 'utils/request')
    const repos = yield call(request, ul, options)
    console.log('REYANSH', repos)
    //   yield put(reposLoaded(repos, username))
  } catch (err) {
    yield put(repoLoadingError(err))
  }
}

/**
 * Root saga manages watcher lifecycle
 */
export default function* githubData() {
  // Watches for LOAD_REPOS actions and calls getRepos when one comes in.
  // By using `takeLatest` only the result of the latest API call is applied.
  // It returns task descriptor (just like fork) so we can continue execution
  // It will be cancelled automatically on component unmount
  yield takeLatest(LOAD_REPOS, getRepos)
}

```
This is how my saga looks.

**Comment by Andarist** [comment]
Hi, not sure what do u mean - according to the youtube recording all previous requests get cancelled correctly. Maybe your API hangs on cancelled requests for too long? `redux-saga` certainly won't work for cancelled tasks to finish before returning your "10th" result.

**Comment by reyanshmishra** [comment]
@Andarist Ohh got it thanks
