### ISSUE TITLE
Excluded transform-regenerator in babel config

### ISSUE THREAD

**Issue by klis87** [redux-saga/redux-saga#1577]
I noticed excluded `transform-regenerator` in https://github.com/redux-saga/redux-saga/blob/master/packages/core/.babelrc.js#L14

As I understand, it means that generators wont be transformed and generator polyfill won't work in runtime. Following this reasoning, it means that it is not possible to use Redux-Saga in a browser not supporting generators natively.

If I am right, I am even more confused as in readme it is mentioned:
> Important! If the browser you are targeting doesn't support ES2015 generators, you must transpile them (i.e. with babel plugin) and provide a valid runtime, such as the one here. The runtime must be imported before redux-saga.

But this wont help because `redux-saga` vendor generators arent transpiled, so generator polyfill won't be able to do anything to them. 

Am I missing something? :)

**Comment by Andarist** [comment]
This transform was removed because it wasn't actually used. `redux-saga` doesn't use generator syntax in its codebase so the advise from README is still relevant - you have to transpile your generators if you need to be compatible with older environments.

**Comment by klis87** [comment]
@Andarist I see, now it makes sense :) so actually does it make any difference then? I just wonder why it is excluded, for build performance reasons?

Btw, sry a little off-topic but this is why my initial question arised, would u advise to use `babel-runtime` in saga library addons? Recently I got an issue in my addon https://github.com/klis87/redux-saga-requests/issues/157 about `regeneratorRuntime is not defined`

I recommended there to use babel polyfill, but I am not sure whether I shouldnt just use `babel-runtime` there. Because I didnt exlude `transform-regenerator` to support older browsers, but in practice I force to use generator polyfill even for modern browsers due to generator transpilation, which is huge disadvantage of my current solution.

**Comment by Andarist** [comment]
> @Andarist I see, now it makes sense :) so actually does it make any difference then? I just wonder why it is excluded, for build performance reasons?

actually probably it doesnt matter and this exclude can be just removed

> Btw, sry for a little off-topic but this is why my initial question arised, would u advise to use babel-runtime in saga library addons?

You could use `babel-plugin-transform-runtime` with this such options:
```js
['transform-runtime', { helpers: false, polyfill: false, regenerator: true }]
```

Unfortunately when it comes to such things - supporting older browsers but providing also a more modern version there is no good practice worked out in the community, so you kinda either transpile to es5 or you just drop the support for ie11 and such.

**Comment by klis87** [comment]
@Andarist ok, thx, I will probably go with  `transform-runtime`, the lesser evil.

**Comment by Andarist** [comment]
I've 'discovered' why the exclude was in our babel config - it stops the babel from transpiling generators in our tests.

**Comment by klis87** [comment]
@Andarist That makes sense, so mystery solved :)
