### ISSUE TITLE
LocalStorage vs getContext/setContext of redux-saga/effects

### ISSUE THREAD

**Issue by ChiaraSammarco** [redux-saga/redux-saga#1580]
I'm working on an application that uses: react 16.4.2 redux-saga 0.16.0 and redux-actions 2.6.1 ...
Basically, the app gets one configuration parameter by triggering an action on the "ComponentDidMount". 
Some other parameters of the app are then defined on the basis of that parameter. 

I have thought two different solutions to this

1) the fastest one with localStorage

`localStorage.setItem('my_parameter', parameter);`

and then, in the constants definition 

`localStorage.getItem('my_parameter');`

2) the other one with getContext/setContext:
 
`yield setContext({my_parameter: parameter});`

and then in all the interested Sagas I should have to get the parameter by calling 
`function * getMyParameter() {
  return yield getContext('my_parameter');
};
`
and then derive the value of the other parameters ... 

What do you think about these solutions? Could you help me understand which one is the best one and why? If you have any other suggestions, I will be happy to consider them. 

The first solution seems to be the easiest and the fastest one, but I'm not sure it fits the logic of Redux. 

TBN: This value is also in the state, and I could retrieve it also with `yield select (....)`, but in this case, I would like to insert this other parameters' definition in a separated file, somehow independent from the saga.

thanks in advance for your help

**Comment by shinima** [comment]
I think localStorage is for keeping something when the web pages close, and localStorage can only store strings, so IMHO localStorage may not be good solution in this cases.

setContext/getContext is okay, however I suspect that you can pass the parameters from parent saga to children saga and avoid using context. For example: 

```js
function* child(foo, bar) { /* ... */ }

function* parent() {
  // `foo` gets arg1, and `bar` gets arg2
  yield call(child, arg1, arg2)
  // yield fork(child, arg1, arg2)
}
```

**Comment by Andarist** [comment]
As @shinima said - localStorage should be primarily used for **persistent data**, the one that has to survive page reloads.

And context is bringing some magic to the table and is supposed to ease "argument passing" through several layers of saga - for simpler use cases just use function arguments.

If you need a state that has to be accessible (& updateable) in different parts of your app this sounds as a perfect use case for redux's state.

**Comment by ChiaraSammarco** [comment]
Thanks, @shinima, and @Andarist for your replies!
Ok, so localStorage is not what I was looking for since it can change in a future page reload.
So, the use of getContext/setContext fits my case. 
My sagas are not in a relation of parent/children and passing my parameter as a function's argument is either not applicable. 
Thanks a lot for your help ;)
