### ISSUE TITLE
Put effect return/result value

### ISSUE THREAD

**Issue by nico1510** [redux-saga/redux-saga#1581]
Consider the worker threads example from the docs:
```javascript
function* watchRequests() {
  // create a channel to queue incoming requests
  const chan = yield call(channel)

  // create 3 worker 'threads'
  for (var i = 0; i < 3; i++) {
    yield fork(handleRequest, chan)
  }

  while (true) {
    const {payload} = yield take('REQUEST')
    const somethingPromiseLike = yield put(chan, payload)
    const result = yield somethingPromiseLike;
  }
}

function* handleRequest(chan) {
  while (true) {
    const payload = yield take(chan)
    // process the request
  }
```
I adapted it and added the `somethingPromiseLike` variable there because this is the place where I would like to have access to the result. Is there a way to get the result of a PUT effect I sent to a channel ?

**Comment by Andarist** [comment]
There is no such option, channels are primitives for communication and the don't embed any special logic for different item types.

It seems that u might look for a `join` effect, that would require restructuring the given code a little bit though.
