### ISSUE TITLE
Question: Can a buffer's methods be async?

### ISSUE THREAD

**Issue by edwardmsmith** [redux-saga/redux-saga#1587]
I'm just getting started learning about channels, and am interested in creating a persistent channel - that survives across  application runs - specifically in a React Native app.

I'd like to queue up tasks on a channel that would not be lost if the app crashed or was closed.

I was wondering if creating a buffer that read/wrote to AsyncStorage would be the way to achieve this - so I'm wondering if the Buffer's methods (`isEmpty`, `put`, `take`) could be async/promises.

If not, I guess the way to achieve this is to have an effect that first puts an action into AsyncStorage, then into the channel, and when the saga is successful, clears it from AsyncStorage.  Also to have a process that, on app start, reads AsyncStorage and puts into the channel to start actions from a previous run.

The buffer idea seems so much more elegant, tho...

**Comment by Andarist** [comment]
There are no plans to support async in buffers at the moment, truth to be told I don't know how you would like it to work in combination with AsyncStorage.

**Comment by restrry** [comment]
any action point on it?

**Comment by edwardmsmith** [comment]
No, I don't think so.  Since buffers are not async, I just went with my backup plan.

Thank you, though!
