### ISSUE TITLE
Debounce is not in effects typings

### ISSUE THREAD

**Issue by Mamoru1234** [redux-saga/redux-saga#1588]
### Actual results
there is no mention of debounce in typings

### The Expected results
debounce should be typed according to [API](https://github.com/redux-saga/redux-saga/blob/master/docs/api/README.md#debouncems-pattern-saga-args) 

### Environment information

- redux-saga@0.16.0

**Comment by Andarist** [comment]
I've merged ur PR, thanks for it! Keep in mind that debounce is available only in v1-beta
