### ISSUE TITLE
Support passing action creator to put?

### ISSUE THREAD

**Issue by ronen** [redux-saga/redux-saga#1591]
I'm so used to typing

```js
yield call(myApiFunction, {api, args, here})
```

That I naturally do the same thing with `put`:

```js
yield put(myActionCreator, { payload, args, here })  // oops...
```

I can't count how many times I've had to track down a weird error message because I did that!   

But maybe that's not actually such a bad way to do a `put`?  Would it make sense for `put` to support any of:

```
put(action)
put(actionCreator, ...args)
put(channel, action)
put(channel, actionCreator, ...args)
```

I.e., if the first argument (after optional channel) is a function, then `put` would call it with the remaining args and use the result.

If you think this is a good idea, I could do a PR.

**Comment by Andarist** [comment]
IMHO this complicates the API surface (lots of argument overloading) for a little gain. You could maybe create some eslint rule guarding you from this?

**Comment by shinima** [comment]
Currently, we can create a customized effect creator to satisfy such cases:

```javascript
function enhancedPut(channel, creator, ...args) {
  if (is.channel(channel)) {
    return put(channel, creator(...args))
  } else if (is.func(channel)) {
    args = [creator, ...args]
    creator = channel
    return put(creator(...args))
  } else {
    return put(channel)
  }
}

// enhancedPut can be used in one of the following forms:
// enhancedPut(action)
// enhancedPut(actionCreator, ...args)
// enhancedPut(channel, action)
// enhancedPut(channel, actionCreator, ...args)
```

However, it seems really complicated 😓

**Comment by ronen** [comment]
> IMHO this complicates the API surface (lots of argument overloading)

Yep, though it seems not entirely unlike the spirit of various parts of the redux ecosystem which accept either a thing or a function returning the thing.

> You could maybe create some eslint rule guarding you from this?

Maybe, but it might be tricky to distinguish between `put(actionCreator, arg)` vs `put(channel, action)` without being able to check the types of the arguments.  (Thus proving your point of the problem with argument overloading :)

Anyway, not a biggie at all.  If I was in charge I might well decide the same way.  Just thought I'd float the idea.

**Comment by Andarist** [comment]
Thanks for sharing, but because of wanting to keep the API smaller we'd have to decline this request at the moment - especially that this is first time anyone requesting this.

We might reconsider this in the future though.
