### ISSUE TITLE
better way to handle select response

### ISSUE THREAD

**Issue by NormanPerrin** [redux-saga/redux-saga#1593]
### Description
I'm not sure, but i read `select` is non blocking.
So my question would be how to better handle the `select` when the data required is being fetch.
Should I add a `take` with a timeout if the data returned by the `select` is empty?

I leave some examples to better understand the question.
The case 3 explains my problem. If the `staticData` is resolved during the `select`, the `take` would not finish ever, unless it has a timeout.

I don't know how to replicate my scenario either.

![fetch_problem](https://user-images.githubusercontent.com/11911371/45172655-5615f080-b1dc-11e8-8a29-e64218504a07.png)

**Comment by shinima** [comment]
> If the staticData is resolved during the select, the take would not finish ever, unless it has a timeout.

*fetching staticData* is asynchronous, and *execution of `select` effect* is synchronous, so `select` is always executed before staticData is resolved.

**Comment by shinima** [comment]
If I understand correctly, I translate your figures into the following code, and there is just one possible case in your scenario:

```javascript
function* gen() {
  yield fork(fetch, '/staticData')
  yield fork(fetch, 'sections/profile')
  // at this point, /staticData is NOT resolved
  const questionTypes = yield select(staticData.questionTypes)
  // at this point, /staticData is NOT resolved
  yield take(STATIC_DATA_SUCC) // staticData may be resolved during waiting STATIC_DATA_SUCC
  return map(section, questionTypes)
}
```

**Comment by Andarist** [comment]
If u want to fork ur requests, then you should join those tasks and make your select after the join resolves - that way it will run AFTER ur store got updated with fetched data

**Comment by NormanPerrin** [comment]
@shinima ah ok, so it should never happend the 3 case.
I have something like this in the `fetchById`, the `staticData` fetch is called from another action:
```

function* selectStaticData() {
    const staticData = yield select(state => state.staticData);
    if (!isEmpty(staticData)) {
        return staticData;
    }
    return (yield take(STATIC_DATA_SUCCEEDED)).data;
}

const mapSection = (section, staticData) => ...

export function* fetchSectionById({id}) {
    try {
        const sectionJson = yield call(SectionService.fetchById, id);
        const staticData = yield selectStaticData();
        const section = mapSection(sectionJson, staticData);
        yield put(receiveSection(section));
    } catch (err) {
        yield put(handleError(err));
    }
}
```

**Comment by shinima** [comment]
@NormanPerrin this seems good me.
