### ISSUE TITLE
What's the best way to unit test a yield* situation with Jest?

### ISSUE THREAD

**Issue by melkristian** [redux-saga/redux-saga#1595]
### Description
What is the best way to test a saga that has a yield*?

Sample Generator:
```
function* myTestGen() {
  try {
    yield* anotherGenerator();
  } catch(err) {
    yield call(someAction(err));
  }
}
```
Sample Jest Test:
```
it('should yield anotherGenerator', () => {
  const g = myTestGen();
  expect(g.next().value).toEqual(<what's the best value here>);
});
```

When doing a yield*, calling next() goes directly to the first yield statement of the reference generator.

What is the best way to test this?

**Comment by Andarist** [comment]
It depends on what do u want to test, using manual iteration testing (with .next()) u might test the anotherGenerator yielded effect. 

There is no "best way" . Write your tests in a way to get more confidence in your code, but what gives you more confidence is somewhat a personal taste. Personally I would look around for more integration-like testing approaches than using the mentioned manual iteration way.

**Comment by Andarist** [comment]
> When testing, anotherGenerator() should have tests of their own. But when testing the generator above, calling .next() takes me to the first yield of that generator but what I really want to get to test that anotherGenerator() has been ran.

If that's your goal then it's better to use `yield call(anotherGen)`

**Comment by melkristian** [comment]
Great! Thanks a lot, @Andarist !
