### ISSUE TITLE
accessing child tasks forked by takeLatest

### ISSUE THREAD

**Issue by berkankisaoglu** [redux-saga/redux-saga#1603]
I ran into a case where I need to access all the tasks that are forked & running thru the system. 
My use case is something like -- 

- STEP 1: User clicks a button fires a bunch of API calls
- STEP 2: Clicks another button to cancel those API calls
- STEP 3: Then clicks a third button to re-initiate the same API calls

My saga looks like -- 

```javascript
export function* exampleSaga(action) {
  yield takeLatest(EXAMPLE.EXAMPLE_NUMBER_ONE, workerExampleNumberOne)
  yield takeLatest(EXAMPLE.EXAMPLE_NUMBER_TWO, workerExampleNumberTwo)
}
```

and it's registered to middleware by calling -- 
```javascript
var exampleTask = sagaMiddleware.run(exampleSaga)
```

my workers look like -- 

```javascript
function* workerExampleNumberOne(action) {
  yield put(exampleNumberOneInProgress())
  try {
    var request = yield call(api.exampleNumberOne, action.data)
    yield put(exampleOneSuccess())
  } catch (e) {
      console.log(e)
  } finally {
      if (yield cancelled()) {
         console.log("cancelled")
      }
  }
}
```

and my actions are like -- 

```javascript
export function exampleNumberOne(data) {
   return { type: EXAMPLE.EXAMPLE_NUMBER_ONE, data: data }
}

export function exampleNumberTwo(data) {
  return { type: EXAMPLE.EXAMPLE_NUMBER_TWO, data: data }
}
```

and when user clicks button 1 and 3, the following actions are dispatched on both -- 

```javascript
function userClickedButtonOneOrThree() {
   dispatch(exampleNumberOne())
   dispatch(exampleNumberTwo())
}
```

My problem is accessing the child tasks when user clicks button 1 or 3. 
Imagine that each API calls that the workers do takes about 10 sec and user wants to cancel after 2 seconds and re-initiate it. 

If I cancel the task that's returned by `var sagaTask = sagaMiddleware.run(exampleSaga)`, the tasks are cancelled but user can't re-initiate the requests. Any hints to achieve that? 

Thanks

**Comment by Andarist** [comment]
It depends on what u are trying to achieve exactly, but u shouldnt probably cancel `sagaTask` in this case, but rather take some action in ur exampleSaga & cancel created tasks more granularly.

**Comment by berkankisaoglu** [comment]
Any use case where I don't want to execute `yield put(exampleOneSuccess())` for those operation. 
An example use case would be -- 

- User makes a request to fetch some data
- User logs out
-  If I don't cancel the tasks when the response is received it will continue processing the response in the success block and etc... 
    - If I cancel tasks out, it won't process and run finally block
    - If the user logs back in (without hard refresh or anything), I want user to be able to run the same sagas. 

- If I cancel out `sagaTask` that's being returned by `sagaMiddleware.run`, user won't be able to run the same saga without a complete refresh (mentioning complete refresh because it's easy to refresh a web page but it's not that easy if it's a mobile app)  
- If I cancel each tasks that's being returned by `yield takeLatest(EXAMPLE.EXAMPLE_NUMBER_ONE, workerExampleNumberOne)`, same thing happens... User won't be able to run the same saga. 

So I actually need to access child tasks forked. One solution that I come up with is to use my own version of takeLatest, something like

```javascript
export const takeLatestAndCancelAnytime = (patternOrChannel, saga, ...args) => fork(function*() {
 let lastTask
 while (true) {
   const action = yield take(patternOrChannel)
   if (lastTask) {
     yield cancel(lastTask) // cancel is no-op if the task has already terminated
     delete sagaTasks[lastTask.id]
   }
   lastTask = yield fork(saga, ...args.concat(action))
   sagaTasks[lastTask.id] = lastTask
 }
})
```
It stores all child tasks in `sagaTasks` so which makes them cancelable at anytime. Wondering if there's any other proper way of achieving this.

**Comment by Andarist** [comment]
Sorry, I have hard time focusing right now and Im not sure what your requirements are.

I know that you have 2 actions and 2 workers (1 for each of the actions). Could you describe ur dispatch/cancel requirements?

**Comment by restrry** [comment]
closed due to inactivity. feel free to reopen
