### ISSUE TITLE
Could we use saga to synchronizly update the store?

### ISSUE THREAD

**Issue by ansonyao** [redux-saga/redux-saga#1607]
### Description

Say I have a saga like this 

```
function* goToProfile(action) {
    const { id } = action
    try {
        yield put(Creators.setSelectedPerson(id))

        // I want to navigate to another page in react native. this is an imperative call I am afraid. I eed to trigger it using something like this.props.navigation.navigate("nextpage") where this is the class of a page. 
    } catch(e) {
        console.tron.log(e)
    }
}

```
Say Creators.setSelectedPerson(id) will update the selectedPersonId in the redux store. I want to make sure this value is updated before the navigation happens.
Could you guys please suggest me a good way to write this? I am new to saga. I would like to see how to solve this asynchronize store update thing in saga, if it is possible.

**Comment by Andarist** [comment]
Lines after `put` are guaranteed to run only after `put` (so basically `dispatch`) is executed, so you should be able to query the state AFTER the update. Keep in mind that this is guaranteed only if your actions always hit reducers synchronously. If you have some async middleware which delays, batches or whatever before passing them to reducer then we can't guarantee that.

**Comment by zeayal** [comment]
If you are using *reactnavigation* in your react-native project, you can see https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html

The add code like this:
`javascript
// NavigationService.js
import { NavigationActions } from 'react-navigation';

let _navigator;

function setTopLevelNavigator(navigatorRef) {
  _navigator = navigatorRef;
}

function navigate(routeName, params) {
  _navigator.dispatch(
    NavigationActions.navigate({
      routeName,
      params,
    })
  );
}

// add other navigation functions that you need and export them
export default {
  navigate,
  setTopLevelNavigator,
};

// In you saga.js
import NavigationService from '...../NavigationService';
function goToProfilePage() {
   NavigationService.navigate('App')
}
function* goToProfile(action) {
    const { id } = action
    try {
        yield put(Creators.setSelectedPerson(id))
        yield call('goToProfilePage')
        // I want to navigate to another page in react native. this is an imperative call I am afraid. I eed to trigger it using something like this.props.navigation.navigate("nextpage") where this is the class of a page. 
    } catch(e) {
        console.tron.log(e)
    }
}

`

**Comment by ansonyao** [comment]
Thanks for the great suggestions! @Andarist and @zeayal. I will close the issue now.
