### ISSUE TITLE
When try to run the examples getting a compilation error.

### ISSUE THREAD

**Issue by anikakalbrun** [redux-saga/redux-saga#1608]
### Steps to reproduce
I have cloned the project
went to the async directory: cd /examples/async
installed node_modules: npm install
tried to run the project: npm run start

This is the output I am getting:
--------------------------------------------------------------------------------------------------

^CTNS6237L:async a$ npm run start

> async-example@1.0.0-beta.1 start /Users/a/IdeaProjects/redux-saga/examples/async
> webpack-dev-server

ℹ ｢wds｣: Project is running at http://localhost:3000/
ℹ ｢wds｣: webpack output is served from /
[BABEL] Note: The code generator has deoptimised the styling of /Users/a/IdeaProjects/redux-saga/examples/async/node_modules/react-dom/cjs/react-dom.development.js as it exceeds the max of 500KB.
✖ ｢wdm｣: Hash: 4e8714d1ecdbfb4c7dfc
Version: webpack 4.19.1
Time: 5300ms
Built at: 2018-09-19 12:54:43
     Asset       Size  Chunks             Chunk Names
   main.js   1.64 MiB    main  [emitted]  main
index.html  292 bytes          [emitted]  
Entrypoint main = main.js
[./node_modules/@babel/polyfill/lib/index.js] 893 bytes {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 6.84 KiB {main} [built]
[./node_modules/url/url.js] 22.3 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:3000] (webpack)-dev-server/client?http://localhost:3000 7.79 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.65 KiB {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.31 KiB {main} [built]
[0] multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./src/main.js 52 bytes {main} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.13 KiB {main} [built]
[./src/containers/App.js] 3.18 KiB {main} [built]
[./src/main.js] 433 bytes {main} [built]
[./src/sagas/index.js] 4.33 KiB {main} [built]
[./src/store/configureStore.js] 1.11 KiB {main} [built]
    + 355 hidden modules

ERROR in ../sagaMonitor/index.js
Module not found: Error: Can't resolve '@redux-saga/is' in '/Users/a/IdeaProjects/redux-saga/examples/sagaMonitor'
 @ ../sagaMonitor/index.js 2:0-37 78:6-13
 @ ./src/store/configureStore.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./src/main.js

ERROR in ../sagaMonitor/modules/checkers.js
Module not found: Error: Can't resolve '@redux-saga/is' in '/Users/a/IdeaProjects/redux-saga/examples/sagaMonitor/modules'
 @ ../sagaMonitor/modules/checkers.js 1:0-37 4:9-18
 @ ../sagaMonitor/index.js
 @ ./src/store/configureStore.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./src/main.js

ERROR in ../sagaMonitor/modules/logSaga.js
Module not found: Error: Can't resolve '@redux-saga/is' in '/Users/a/IdeaProjects/redux-saga/examples/sagaMonitor/modules'
 @ ../sagaMonitor/modules/logSaga.js 2:0-37 75:13-24 77:13-23 79:13-22
 @ ../sagaMonitor/index.js
 @ ./src/store/configureStore.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./src/main.js

ERROR in ../sagaMonitor/modules/DescriptorFormatter.js
Module not found: Error: Can't resolve '@redux-saga/is' in '/Users/a/IdeaProjects/redux-saga/examples/sagaMonitor/modules'
 @ ../sagaMonitor/modules/DescriptorFormatter.js 3:0-37 55:10-18
 @ ../sagaMonitor/modules/logSaga.js
 @ ../sagaMonitor/index.js
 @ ./src/store/configureStore.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./src/main.js

ERROR in ./src/store/configureStore.js
Module not found: Error: Can't resolve 'redux-saga' in '/Users/a/IdeaProjects/redux-saga/examples/async/src/store'
 @ ./src/store/configureStore.js 7:0-46 10:23-43
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./src/main.js

ERROR in ./src/sagas/index.js
Module not found: Error: Can't resolve 'redux-saga/effects' in '/Users/a/IdeaProjects/redux-saga/examples/async/src/sagas'
 @ ./src/sagas/index.js 17:0-67 37:17-20 41:17-21 46:17-20 68:17-21 74:17-21 99:17-23 104:17-21 108:17-23 113:17-23 124:17-21 144:17-23 149:17-21 164:17-21 168:17-21 172:17-21
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./src/main.js

ERROR in ../sagaMonitor/modules/logSaga.js
Module not found: Error: Can't resolve 'redux-saga/effects' in '/Users/a/IdeaProjects/redux-saga/examples/sagaMonitor/modules'
 @ ../sagaMonitor/modules/logSaga.js 3:0-49 84:17-28 86:24-35 90:24-35 92:24-35 94:24-35 96:24-35 98:24-35 100:24-35 102:24-35 104:24-35 106:24-35 108:24-35 110:24-35 112:24-35 114:24-35
 @ ../sagaMonitor/index.js
 @ ./src/store/configureStore.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./src/main.js

ERROR in ../sagaMonitor/modules/checkers.js
Module not found: Error: Can't resolve 'redux-saga/effects' in '/Users/a/IdeaProjects/redux-saga/examples/sagaMonitor/modules'
 @ ../sagaMonitor/modules/checkers.js 2:0-49 4:40-51
 @ ../sagaMonitor/index.js
 @ ./src/store/configureStore.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 (webpack)/hot/dev-server.js ./src/main.js
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./index.html] 444 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 492 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 552 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.

--------------------------------------------------------------------------------------------------

I am using node v8.10.0. 

When I tried to run the real-word example I got an other error: 
Error: Cannot find module 'lodash/array/zip'

I am wondering how to run the examples? 
Thanks

**Comment by Andarist** [comment]
When cloning the master branch and trying to test those it might not work. This is a lerna-managed monorepo, instead of installing modules in an example directory please run bootstrap script in the project's root. This should install all dependencies in managed directories - so after that you should be able to run the example.

**Comment by jpggvilaca** [comment]
Doesn't work, even with the bootstrap. I think there's dependencies that need to be updated

**Comment by aibolik** [comment]
I faced same problem. You should follow ReadMe from redux-saga.js.org, that states you should run this one too:
`npm test`

If you look at `package.json` you'll notice that in `pretest` step `build` will be ran, that is probably what was missing.

**Comment by andrevenancio** [comment]
Doesnt work. Neither following instructions on redux-saga readme.MD file nor doing npm i && npm start on the example/real-world folder.

**Comment by jiajianrong** [comment]
The same issue met too

**Comment by ranrolls** [comment]
The same issue still persist

**Comment by Ashkanph** [comment]
Same problem here. I tried these two, but didn't solve the problem:

```bash
npm run postinstall
npm run bootstrap
```

**Comment by jpggvilaca** [comment]
Opened a PR for this: https://github.com/redux-saga/redux-saga/pull/1782

So, if you can't wait, just add these 2 missing devDependencies on the redux-saga's `package.json`

**Comment by Andarist** [comment]
I believe that this should be resolved by https://github.com/redux-saga/redux-saga/commit/71d2caa6a558036dfd526d2aac41734da587022b . If not please reopen the issue.
