### ISSUE TITLE
Dispatch every x seconds

### ISSUE THREAD

**Issue by adamwright104** [redux-saga/redux-saga#1610]
I've just about got my head round redux and now i want to do something with real time data, everyone seems to recommend redux-saga so here i am,  for this i'm testing it with a country time api so i know the results from the call will be updated on each request.

The console.log(result) is being hit and its outputting in iterations but not sending the data to the component.

Do i need to add some specific actions for Saga? example START_SAGE and should that have a payload? Then how do i add my own setTimeOut into fetchSaga function?

Any advise or working examples would be great

actions.js

```javascript
export const FETCH = 'FETCH';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';


export function fetch() {
  return {
    type: FETCH
  };
}

export function fetchSuccess(data) {
  return {
    type: FETCH_SUCCESS,
    data
  };
}

export function fetchFail(error) {
  return {
    type: FETCH_FAILURE,
    error
  };
}
```
saga.js

```javascript
export function *fetchSaga() {
    try {
      const result = yield call(axios.get, 'http://api.timezonedb.com/v2.1/list-time-zone?key=EF1GEI5N2IAX&format=json')
      console.log(result)
      yield put(actions.fetch(result));
    }
    catch (err) {
      console.log("err", err)
    }
}
```
Table.js
```javascript
componentDidMount() {
    this.props.fetch()
  }

render() {
    if(!this.props.isfetching) {
      return (
        <div>
          <Table sortable celled fixed>
          <Table.Header>
            <Table.Row>
              <Table.HeaderCell
              >
                countryCode
              </Table.HeaderCell>
              <Table.HeaderCell
              >
                countryName
              </Table.HeaderCell>
              <Table.HeaderCell
              >
                timestamp
              </Table.HeaderCell>
              <Table.HeaderCell
              >
                action
              </Table.HeaderCell>
            </Table.Row>
          </Table.Header>
          <Table.Body>
            {this.props.data.map((item, i) => {
              return (
              <Table.Row key={i}>
                <Table.Cell>{item.countryCode}</Table.Cell>
                <Table.Cell>{item.countryName}</Table.Cell>
                <Table.Cell>{this.CovertTime(item.timestamp)}</Table.Cell>
                <Table.Cell><button onClick={() => {this.onClick(item.countryCode)}}>click me</button></Table.Cell>
              </Table.Row>
              )
            })}
          </Table.Body>
        </Table>
        </div>
      );
    }
    else {
      return (
        <div>{this.props.isfetching}</div>
      )
    }
  }
}

Table.propTypes = {
  fetch: PropTypes.func
};

function mapStateToProps(state) {
  return {
    data: state.data.items,
    isfetching: state.data.isFetching
  };
}

export default connect(mapStateToProps, { fetch })(Table);

```

**Comment by shinima** [comment]
Add a setTimeOut into fetchSaga is quite straightforward:

```javascript
import delay from '@redux-saga/delay-p'

function* fetchSagaPeriodically() {
  while (true) {
    yield call(fetchSaga);
    yield delay(2000);
  }
}
```

--- 

> but not sending the data to the component.

You need to add a payload in you `FETCH` action so you can save the fetch result in your store, and then your `<Table />` can read the result from the store via connect.

```diff
-export function fetch() {
+export function fetch(result) {
  return {
    type: FETCH,
+    result,
  };
}
```
```javascript
// your reducer
function reducer(state, action) {
  if (action.type === 'FETCH') {
    return { ...state, data: action.result } // save the fetch result in your store
  }
  // ... other code
}
```

**Comment by adamwright104** [comment]
@shinima thanks i've got that working now. however i'm not sure its doing the delay. Do you have a best practice example of polling for this? 


```
export function *fetchSaga() {
  while (true) {
    const result = yield call(axios.get, 'http://api.timezonedb.com/v2.1/list-time-zone?key=EF1GEI5N2IAX&format=json');
    yield delay(10000);
    yield put(actions.fetch(result.data.zones));
  }
}
```

 componentDidMount() {
    this.props.fetch()
  }

render() {
    console.log("this.props.data", this.props.data)
    if(this.props.data) {
      return (
        <div>
          <Table sortable celled fixed>
          <Table.Header>
            <Table.Row>
              <Table.HeaderCell
              >
                countryCode
              </Table.HeaderCell>
              <Table.HeaderCell
              >
                countryName
              </Table.HeaderCell>
              <Table.HeaderCell
              >
                timestamp
              </Table.HeaderCell>
              <Table.HeaderCell
              >
                action
              </Table.HeaderCell>
            </Table.Row>
          </Table.Header>
          <Table.Body>
            {this.props.data.map((item, i) => {
              return (
              <Table.Row key={i}>
                <Table.Cell>{item.countryCode}</Table.Cell>
                <Table.Cell>{item.countryName}</Table.Cell>
                <Table.Cell>{this.CovertTime(item.timestamp)}</Table.Cell>
                <Table.Cell><button onClick={() => {this.onClick(item.countryCode)}}>click me</button></Table.Cell>
              </Table.Row>
              )
            })}
          </Table.Body>
        </Table>
        </div>
      );
    }
    else {
      return (
        <div>{this.props.isfetching}</div>
      )
    }
  }
}

export default connect(mapStateToProps, { fetch })(Table);

**Comment by shinima** [comment]
Not sure what you're going to achieve... If you want to skip the delay at the first time, since saga logic could be quite flexible, you could add a local variable `skipAtFirstTime` as follows: 

```javascript
export function* fetchSaga() {
  let skipAtFirstTime = true
  while (true) {
    const result = yield call(axios.get, 'http://api.timezonedb.com/v2.1/list-time-zone?key=EF1GEI5N2IAX&format=json')
    if (!skipAtFirstTime) {
      skipAtFirstTime = false
      yield delay(10000)
    }
    yield put(actions.fetch(result.data.zones))
  }
}
```

**Comment by jebaGem** [comment]
> Not sure what you're going to achieve... If you want to skip the delay at the first time, since saga logic could be quite flexible, you could add a local variable `skipAtFirstTime` as follows:
> 
> ```js
> export function* fetchSaga() {
>   let skipAtFirstTime = true
>   while (true) {
>     const result = yield call(axios.get, 'http://api.timezonedb.com......')
>     if (!skipAtFirstTime) {
>       skipAtFirstTime = false
>       yield delay(10000)
>     }
>     yield put(actions.fetch(result.data.zones))
>   }
> }
> ```

Did you get answer to this issue ? Because I am also facing this in my application now . It will be helpful if you share it . Thanks

**Comment by saadq** [comment]
Assuming I had a saga like this:

```js
function* fetchSagaPeriodically() {
  while (true) {
    yield call(fetchSaga);
    yield delay(2000);
  }
}
```

and I wanted to be able to cancel at some point, should the cancellation be done within the saga itself? Like:

```js
function* fetchSagaPeriodically() {
  while (true) {
    // Is this a bad way of adding `cancel`?
    if (shouldCancel()) {
      yield cancel(fetchSagaPeriodically);
    }
    
    yield call(fetchSaga);
    yield delay(2000);
  }
}
```

**Comment by Andarist** [comment]
This wouldn't work because you have to cancel a task and not a generator. Think about generators here as classes and about tasks as instances of those classes - you can't cancel a class, you want to cancel a particular instance of it.

If you want to cancel a task in which you are currently in you can either use self-cancellation (`yield cancel()`) or just use a simple `return`
