### ISSUE TITLE
yield is not defined

### ISSUE THREAD

**Issue by z937010871** [redux-saga/redux-saga#1617]
function* update(){
       Alert.alert(message, null, [{ text: '确定', onPress:()=> yield put(back('LoginPage'))
}
![image](https://user-images.githubusercontent.com/18677021/46151863-51f06680-c2a2-11e8-9a05-d50149be60df.png)

**Comment by z937010871** [comment]
> ```
> function* update(){
Alert.alert(message, null, [{ text: '确定', onPress:()=> yield put(back('LoginPage'))
}
> ```
> ![图片](https://user-images.githubusercontent.com/18677021/46151863-51f06680-c2a2-11e8-9a05-d50149be60df.png)

**Comment by z937010871** [comment]
有人在么, 求解答 各位大佬们

**Comment by shinima** [comment]
You can only use the `yield` keyword in a generator function. 

When you want to dispatch actions when user clicks some button, you could call the `dispatch` function in your view. However in sagas, where you cannot access the `dispatch` function, you need to create an eventChannel from the click events, and then take from the eventChannel to let the saga get the click event.

yield 只能在生成器函数中才能使用。

看起来你想要实现“用户点击某个按钮的时候 dispatch 特定的 action“，在视图那边的话你可以直接调用 dispatch 函数。不过在 saga 中，你需要从点击事件中创建一个 eventChannel，然后在 saga 中从这个 eventChannel 中 take 得到点击的事件，这样你的 saga 才会知道「按钮被点击了」。

**Comment by z937010871** [comment]
> 您只能`yield`在生成器函数中使用关键字。
> 
> 看来你正在实现的是“当用户点击某个按钮，发送一些动作”时。在您可以访问该`dispatch`功能的视图中，您可以`dispatch`直接调用该功能。但是在sagas中，您无法访问该`dispatch`函数，您需要从click事件创建一个eventChannel，然后从eventChannel获取让saga获得click事件。
> 
> yield只能在生成器函数中才能使用。
> 
> 看起来你想要实现“用户点击某个按钮的时候调度特定的动作”，在视图那边的话你可以直接调用调度函数。不过在saga中，你需要从点击事件中创建一个eventChannel，然后在saga中从这个eventChannel中取得到点击的事件，这样你的saga才会知道「按钮被点击了」。



> 您只能`yield`在生成器函数中使用关键字。
> 
> 看来你正在实现的是“当用户点击某个按钮，发送一些动作”时。在您可以访问该`dispatch`功能的视图中，您可以`dispatch`直接调用该功能。但是在sagas中，您无法访问该`dispatch`函数，您需要从click事件创建一个eventChannel，然后从eventChannel获取让saga获得click事件。
> 
> yield只能在生成器函数中才能使用。
> 
> 看起来你想要实现“用户点击某个按钮的时候调度特定的动作”，在视图那边的话你可以直接调用调度函数。不过在saga中，你需要从点击事件中创建一个eventChannel，然后在saga中从这个eventChannel中取得到点击的事件，这样你的saga才会知道「按钮被点击了」。

可以帮忙写个demo吗,刚学习redux-saga 不是很懂

**Comment by z937010871** [comment]
> You can only use the `yield` keyword in a generator function.
> 
> It seems that what you are implementing is "when user clicks some button, dispatches some actions". In your views, where you could access the `dispatch` function, then you could call the `dispatch` function directly. However in sagas, where you cannot access the `dispatch` function, you need to create an eventChannel from the click events, and then take from the eventChannel to let the saga get the click event.
> 
> yield 只能在生成器函数中才能使用。
> 
> 看起来你想要实现“用户点击某个按钮的时候 dispatch 特定的 action“，在视图那边的话你可以直接调用 dispatch 函数。不过在 saga 中，你需要从点击事件中创建一个 eventChannel，然后在 saga 中从这个 eventChannel 中 take 得到点击的事件，这样你的 saga 才会知道「按钮被点击了」。

可以帮忙写个demo么,刚学redux-saga和es6 不是很懂.

**Comment by shinima** [comment]
Using eventChannel may be a little overwhelming. In this case, let's use the `cps` effect:

```javascript
import { cps } from 'redux-saga/effects'

function* update() {
  const result = yield cps(cb => {
    Alert.alert(message, null, [{ text: '确定', onPress: () => cb('user-press-confirm') }])
  })
  if (result === 'user-click-confirm') {
    yield put(back('LoginPage'))
  } // else ...
}
```

In this case, `yield cps(...)` will be blocked until the `cb` is called. When user presses the confirm button, `cb('user-press-confirm')` is executed, and `'user-press-confirm'` is assigned to `result`.

**Comment by z937010871** [comment]
> Using eventChannel may be a little overwhelming. In this case, let's use the `cps` effect:
> 
> ```js
> import { cps } from 'redux-saga/effects'
> 
> function* update() {
>   const result = yield cps(cb => {
>     Alert.alert(message, null, [{ text: '确定', onPress: () => cb('user-press-confirm') }])
>   })
>   if (result === 'user-click-confirm') {
>     yield put(back('LoginPage'))
>   } // else ...
> }
> ```
> 
> In this case, `yield cps(...)` will be blocked until the `cb` is called. When user presses the confirm button, `cb('user-press-confirm')` is executed, and `'user-press-confirm'` is assigned to `result`.

你好,大神 刚刚试了您的方法, 报错了

<img width="322" alt="wx20180928-140921 2x" src="https://user-images.githubusercontent.com/18677021/46190931-1dbf8900-c328-11e8-8d72-ca77bc2d5ad3.png">

**Comment by shinima** [comment]
不好意思，`cb('user-press-confirm')` 那边我写错了。需要添加一个 null：

```diff
function* update() {
  const result = yield cps(cb => {
-   Alert.alert(message, null, [{ text: '确定', onPress: () => cb('user-press-confirm') }])
+   Alert.alert(message, null, [{ text: '确定', onPress: () => cb(null, 'user-press-confirm') }])
  })
}
```

**Comment by z937010871** [comment]
> 不好意思，`cb('user-press-confirm')` 那边我写错了。需要添加一个 null：
> 
> ```diff
> function* update() {
>   const result = yield cps(cb => {
> -   Alert.alert(message, null, [{ text: '确定', onPress: () => cb('user-press-confirm') }])
> +   Alert.alert(message, null, [{ text: '确定', onPress: () => cb(null, 'user-press-confirm') }])
>   })
> }
> ```



> 不好意思，`cb('user-press-confirm')` 那边我写错了。需要添加一个 null：
> 
> ```diff
> function* update() {
>   const result = yield cps(cb => {
> -   Alert.alert(message, null, [{ text: '确定', onPress: () => cb('user-press-confirm') }])
> +   Alert.alert(message, null, [{ text: '确定', onPress: () => cb(null, 'user-press-confirm') }])
>   })
> }
> ```

嗯嗯,解决了,非常感谢您! 厉害!!!

**Comment by z937010871** [comment]
> 不好意思，`cb('user-press-confirm')` 那边我写错了。需要添加一个 null：
> 
> ```diff
> function* update() {
>   const result = yield cps(cb => {
> -   Alert.alert(message, null, [{ text: '确定', onPress: () => cb('user-press-confirm') }])
> +   Alert.alert(message, null, [{ text: '确定', onPress: () => cb(null, 'user-press-confirm') }])
>   })
> }
> ```

嗯嗯,解决掉了,非常感谢您!
厉害!!!
