### ISSUE TITLE
Get 'Require cycle' Warning 

### ISSUE THREAD

**Issue by lengzuo** [redux-saga/redux-saga#1618]
![simulator screen shot - iphone 6 - 2018-09-28 at 10 16 11](https://user-images.githubusercontent.com/13924824/46184409-27d18f80-c308-11e8-9a97-afc4a07279c4.png)

Im not sure will this warning affect my project in the future.

Any idea to solve this ?

**Comment by restrry** [comment]
@lengzuo still reproducible after update?

**Comment by Andarist** [comment]
Should be also fixed with 0.16.1
