### ISSUE TITLE
Rough estimate of 1.0.0 timeline

### ISSUE THREAD

**Issue by abettadapur** [redux-saga/redux-saga#1620]
Hi,
We love using ReduxSaga in our projects and we want to take advantage of some new features in v1.0.0.
A couple of questions

* Do you have a rough estimate of when v1.0.0 would be complete? Or a list of outstanding tasks to complete before the release (if you need contributors)
* Do you think that beta2 is stable enough to deploy to production? Or are there still some significant rough edges that have be ironed out?

Thanks!

**Comment by Andarist** [comment]
I hope to release v1 this month, but beta2 is generally stable - it's just an evolution of the 0.x line, not a complete rewrite. Just pin your dependency to exact version and you should be fine.

**Comment by restrry** [comment]
actually what's left - update the docs, examples and review them, hope we finish with it soon 😃 there are no  major changes since `beta.2`, so you can start using it. draft of changelog https://github.com/redux-saga/redux-saga/pull/1613

**Comment by saboya** [comment]
Should this be closed?
