### ISSUE TITLE
Suspend before running root

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#1623]
root should be considered a regular task (its just being run from outside instead of being forked inside) and thus normal scheduling should apply for it.

So we should suspend the scheduler before running, I can dig up a test case for this as I had it somewhere

**Comment by shinima** [comment]
I found a simple case that can test whether the root is under scheduling. If root is under scheduling, then `take('*')` can get the action dispatched by `put(action)`, and *test* will win the race. After adding [restrry's code](https://github.com/redux-saga/redux-saga/issues/1592#issuecomment-427393479), this test can pass.

```javascript
test('runSaga scheduling', async () => {
  const action = { type: 'ACTION' }
  let actual

  function* root() {
    const result = yield race({
      // sentinel is used to avoid blocking at take('*')
      sentinel: Promise.resolve(true),
      test: all([put(action), take('*')]),
    })
    actual = result.test
  }

  await runSaga(storeLike(() => null), root).toPromise()

  expect(actual).toEqual([action, action])
})
```

**Comment by Andarist** [comment]
yeah, my test case that I was supposed to find was really similar, ill probably use urs to create a PR for this 👍
