### ISSUE TITLE
`babelHelpers is not defined` in 0.16.1 version

### ISSUE THREAD

**Issue by weekeight** [redux-saga/redux-saga#1632]
### Steps to reproduce

in any react project, with webpack build tools

#### Description of the bug/issue

use redux-saga@0.16.0 in react project is ok, I found you guys released 0.16.1 two days ago, once we upgrade to this version, will get the error in the console: `babelHelpers is not defined`.

I checked the code in redux-saga@0.16.1, in `/dist/redux-saga.js:1707`, there is `babelHelpers.defineEnumerableProperties(_ref9, _mutatorMap), _ref9;`, but we don't have `babelHelpers` defined in the scope, so error occurs. any idea about it?

![image](https://user-images.githubusercontent.com/1918022/46643417-8cb1a300-cbae-11e8-92b5-d989193ccc84.png)

![image](https://user-images.githubusercontent.com/1918022/46643408-7d325a00-cbae-11e8-9b09-32d1a0c4c54d.png)

**Comment by Andarist** [comment]
I've released 0.16.2 with the fix, the only affected versions were UMD ones (in dist directory) - they are generally not supposed to be consumed with webpack. main/module entry points are more optimized for this.
