### ISSUE TITLE
An interface for managing all spawned / detached tasks

### ISSUE THREAD

**Issue by alexsbryan** [redux-saga/redux-saga#1633]
### Description

Is there an interface for accessing all spawned tasks? For the application I'm working on we have tests that spin up modules that run their respective sagas, then after each test we'd like to be able to clean up all executing sagas. Unfortunately just cancelling the rootSagas for each module isn't sufficient since the cancellation won't propagate to spawned processes. We can adapt some things to make this work on our end, but I wanted to check if it'd be reasonable to request a way to access all spawned tasks directly from the library?

### Example

I created a sandbox with the basic problematic case: https://codesandbox.io/s/y360k1l95z. The main idea would just be this little snippet:

```
   const rootTask = sagaMiddleware.run(rootSaga);
   rootTask.cancel();
   // is there anything I could use here to cancel all workers spawned by rootTask?
```

### Proposals

1) Could redux-saga expose a static method on Task to retrieve all spawned tasks?
2) Maybe better could there be a callback to `middleware.run` that could notify an observer when new tasks are spawned so they can chose how to manage them? This solution is nice for us because we could bind a group to the callback and keep track of spawned tasks by group making our cancellation more targeted (in a test, I can load module A & B, then cancel all running sagas started by A and assert that B still works properly).

**Comment by shinima** [comment]
Sorry for the late reply. 

> Is there an interface for accessing all spawned tasks?

Sadly, the answer is NO. redux-saga internally does not track the detached tasks, all that redux-saga does when handling `spawn` effects is calling `proc()` (the function that consumes the iterator) and return a task descriptor back to the iterator.

However in such cases I think a customized `spawn` effect creator can be helpful. In the following code, calling `mySpawn` will yield a `spawn` effect and it save the task descriptor in a global map, so we can get the task object later. We can even save the task with a name, so then we use the name to retrieve the corresponding task object.

```javascript
// a global map for storing all the detached tasks via mySpawn
// this map can be placed in saga context or in redux store as well
const map = new Map()

function* mySpawn(name, fn, ...args) {
  const task = yield spawn(fn, ...args)
  map.set(name, task)
}

function getAllMyTasks() {
  return map
}

function* rootSaga() {
  yield mySpawn('name-1', saga)
  yield mySpawn('name-2', anotherSaga)

  const taskMap = getAllMyTasks()
  yield cancel(Array.from(taskMap.values()))
}
```

**Comment by alexsbryan** [comment]
Sounds reasonable, thanks for the response! That answers my question.
