### ISSUE TITLE
Order (queue) inside all effect

### ISSUE THREAD

**Issue by nuam** [redux-saga/redux-saga#1634]
Hello everyone.
I want the FIRST to always be executed first, and the rest all how usually. How can I do it?
Sorry if it sounds stupid :)

`export default function* myName() {
  yield all([
    fork(FIRST),
    fork(notFirst),
    fork(notFirst),
  ]);
}`

Can it resolve my problem?
`  yield all([
    call(FIRST),
    fork(notFirst),
    fork(notFirst),
  ]);`

I don't understand documentation. In documentation written about parallel execution, but I need to block everything else while the first not finished.

**Comment by Andarist** [comment]
All executes all its effects in parallel - immediately. If u want FIRST to
finish before executing next effects then do this:

yield call(FIRST)
yield all([fork(notFirst), fork(notFirst)])

**Comment by shinima** [comment]
Closing it. If you have further questions, just re-open it.
