### ISSUE TITLE
How to make sure that a saga finishes execution inside another saga?

### ISSUE THREAD

**Issue by etairi** [redux-saga/redux-saga#1635]
I have the following scenario:

```
export function* addCircle(circleApi, { payload }) {
    try {
        const response = yield apply(
            circleApi,
            circleApi.addCircle,
            [payload]
        );

        if (response.error_type) {
           yield put(addCircleFailedAction(response.error));
        } else {
            yield put(addCircleSucceededAction(response));
        }
    } catch (err) {
        console.error(err);
    }
}

export function* addTender(tenderApi, { payload }) {
    try {
       // NOTE: I want this to finish before continuing with making the API call below.
       yield call(addCircleAction(payload.circlePayload));

       // Rest of saga removed for brevity.
    } catch (err) {
        console.error(err);
    }
}
```

So, basically `addCircle` is making an API call, and depending on its success I call the appropriate redux action. Now, inside another saga I call the action responsible for `addCircle` saga, and I want it to finish execution before I continue with the rest of the saga. I tried to use call, but it basically doesn't wait for the `addCircle` saga to finish executing. Is there any way to wait for it? I call `addCircle` from inside my components and I didn't have the need to wait it, but in this specific instance I have to call it inside the saga, so I really need to wait for it to finish execution, change the state of the app, so that I can use the updated state in the rest of `addTender` saga. Any ideas?

**Comment by shinima** [comment]
`call` should be blocking, that means it will wait the inner saga to complete before resuming the outer generator. So basically I think if you refactor your design/code a little, you could use `call` to wait the inner saga to complete.

In your case, I'm not quite sure what's the relationship between `addCircleAction` and `addCircle()` 😕  But I think you could put a `ADD_CIRCLE_COMPLETED` action in the bottom of `addCircle()` and you can take(wait) this action in other sagas where you want to make sure that the `addCircle()` is finished.

```diff
export function* addCircle(circleApi, { payload }) {
// ... other code...
+ yield put({ type: 'ADD_CIRCLE_COMPLETED'})
}

export function* addTender(tenderApi, { payload }) {
    try {
       // NOTE: I want this to finish before continuing with making the API call below.
       yield call(addCircleAction(payload.circlePayload));
+    yield take('ADD_CIRCLE_COMPLETED')
       // Rest of saga removed for brevity.
    } catch (err) {
        console.error(err);
    }
}
```

**Comment by etairi** [comment]
Thanks, this worked!

**Comment by Andarist** [comment]
Closing the issue then. Glad you have figured it out.
