### ISSUE TITLE
Delay type in api.md not equal real function

### ISSUE THREAD

**Issue by retyui** [redux-saga/redux-saga#1638]
### Steps to reproduce

1) Show [delay type](https://github.com/redux-saga/redux-saga/tree/master/docs/api#delayms-val) effect
2) And compare with `delayP` function
https://github.com/redux-saga/redux-saga/blob/a1c465d18780bc69450569b76f43e4e35baac5c7/packages/delay-p/src/index.js#L3-L14
3) It is always return true

#### Description of the bug/issue
Where is the error in the documentation or in the implementation of the function `delayP` ?

#### Example
```js
const test = yield delay(1, "myValue"); // true
```
### Actual results
`test === true`

### The Expected results
```js
test === "myValue" // if the documentation is the source of truth
```

### Environment information
- redux-saga 1.0.0-beta.2
- babel

**Comment by restrry** [comment]
that's a bug. should return passed value

**Comment by Andarist** [comment]
Sideways question - why do you need this feature? Seems quite odd to rely on it.
