### ISSUE TITLE
Understanding how tasks cancellation and cancelled work is difficult 

### ISSUE THREAD

**Issue by alcuadrado** [redux-saga/redux-saga#1643]
Hi,

I'm learning about `redux-sagas` and found it very difficult to understand how this pattern worked:

```js
try {
  yield delay(1000); // Or another blocking effect
} finally {
  if (yield cancelled()) {
    console.log("CANCELLED");
  }
}
```

I tried things like:

```js
try {
  console.log("1");
  yield delay(100000000);
  console.log("2");
} catch (error) {
  console.error("3");
} finally {
  if (yield cancelled()) {
    console.log("CANCELLED");
  }
}
```

and to my surprise only `1` and `CANCELLED` were printed 🤯.

It took me some time until I found [this issue](https://github.com/redux-saga/redux-saga/issues/266) that explains it.

More documentation about this would be super helpful.

**Comment by restrry** [comment]
your use case looks like this?
```js
function* genA(){
  try {
    console.log("1");
    yield delay(500);
    console.log("2");
  } catch (error) {
    console.error("3");
  } finally {
    if (yield cancelled()) {
      console.log("CANCELLED");
    }
  }
}

function* main() {
    const task = yield fork(genA)
    yield delay(100)
    yield cancel(task)
}
```
what we can add to this doc?
https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/TaskCancellation.md

**Comment by alcuadrado** [comment]
There's a brief mention on how it works there: 

> In the above example, cancellation of bgSyncTask will cause the Generator to jump to the finally block. Here you can use yield cancelled() to check if the Generator has been cancelled or not.

but maybe making it more detailed would work, something along the lines of 

> In the above example, cancellation of bgSyncTask will use [Generator.prototype.return](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/return) to make the Generator jump directly to the finally block. Here you can use yield cancelled() to check if the Generator has been cancelled or not.

**Comment by Andarist** [comment]
adjusted the docs, i hope it wont be as confusing now
