### ISSUE TITLE
Saga errors not propagated

### ISSUE THREAD

**Issue by vclav** [redux-saga/redux-saga#1647]
### Steps to reproduce
1. set `window.onerror = errorHandler;`,
or wrap React app `try { ReactDOM.render(...) } catch(err) { errorHandler(err); } }`
or use `componentDidCatch`,
2. then throw an error in saga,

#### Description of the bug/issue
error is not propagated. It is wrote into *console* as `uncaught ...` but I'm not able to handle the error. The `try {} catch () {}` works in saga, but is not propagated outside.

I suspect the polyfill for ES6 generators might be culprit.

As a workaround I catch all errors in saga and then throws them in `setTimeout`, but it is ugly.

### Environment information
- redux-saga@16.2
- babel-core@6.26.0
- babel-generator@6.26.1
ya

**Comment by restrry** [comment]
this is an error in async function, so try/catch cannot help here. but saga provides you a hook `onError` in [createSagaMiddleware](https://redux-saga.js.org/docs/api/#createsagamiddlewareoptions) for errors bubble to the root saga, where you can handle an exception. keep in mind that if error bubbles to the root - the whole saga tree is cancelled

**Comment by restrry** [comment]
closed as no actions points are possible
