### ISSUE TITLE
flow-typed definitions for 0.16.x not working for flow 0.84.0

### ISSUE THREAD

**Issue by sslotsky** [redux-saga/redux-saga#1657]
### Steps to reproduce

1. Start with a React app
2. Install redux-saga 0.16.0 and related dependencies
3. Install and initialize flow
4. Install flow-typed and use it to install types
5. Run flow status

### Expected result

There should be no errors with the redux-saga type definitions

#### Actual result

Errors with the type definitions.

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/redux-saga_v0.16.x.js:7:36

Cannot resolve module redux-saga/effects.

      4│ // @flow
      5│
      6│ declare module "redux-saga" {
      7│   import typeof * as _effects from "redux-saga/effects";
      8│   declare export var effects: _effects;
      9│
     10│   declare export interface Channel {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/redux-saga_v0.16.x.js:470:10

Cannot resolve module redux-saga.

     467│     SpawnEffect,
     468│     TakeEffect,
     469│     Task
     470│   } from "redux-saga";
     471│
     472│   declare export var take: {
     473│     <P: Pattern>(pattern: P): TakeEffect<P, void, void>,
```

**Comment by Andarist** [comment]
Flow typings are not maintained in this repository. They are located here - https://github.com/flow-typed/flow-typed/tree/master/definitions/npm/redux-saga_v0.16.x/flow_v0.56.0- 

The best way to move forward would be to prepare a PR fixing those typings and sending it there.

**Comment by sslotsky** [comment]
Thanks, I was attempting to take the easy option from the following advice:

https://github.com/redux-saga/redux-saga/issues/1006#issuecomment-348142339

> please report them here by creating a new issue or fix them in flow-typed repository.

I realize this is old advice :smile:
