### ISSUE TITLE
Why do you have a semicolon here?

### ISSUE THREAD

**Issue by 951565664** [redux-saga/redux-saga#1661]
![image](https://user-images.githubusercontent.com/22285404/47786523-fc96f180-dd46-11e8-8666-2fe9d127995e.png)

**Comment by 951565664** [comment]
Is it preventing code packaging errors?I know that a semicolon may be added at the beginning of the file.

**Comment by shinima** [comment]
The semicolon is added by prettier. If you remove these semicolons and run prettier again, it will add for you.

**Comment by shinima** [comment]
https://www.zhihu.com/question/20298345   Hope this can help you.

**Comment by restrry** [comment]
closed as no actions points are possible
