### ISSUE TITLE
Calling a saga that forks a long running task is blocking

### ISSUE THREAD

**Issue by abettadapur** [redux-saga/redux-saga#1664]
Hi!
I found a bug in our production code today, and the cause was surprising to me. An example is shown here
```
sagaMiddleware.run(firstSaga);
function* firstSaga(): SagaIterator {
  // This call blocks, even though the secondSaga is forking the long running operation
  yield call(secondSaga);

  // Never Called
  console.log("Done!");
}

function* secondSaga(): SagaIterator {
  yield fork(thirdSaga);
}

function* thirdSaga(): SagaIterator {
  while (true) {
    const thing = yield take("Something");
    console.log(thing);
  }
}
```

In the code above, "Done!" is never printed to the console, which was unexpected to me. I thought that the call effect would complete once `secondSaga` is finished forking the long running task. 

Could you help me explain this?

**Comment by khaliu** [comment]
I think you should check this in the _fork_ API Docs:

> All forked tasks are attached to their parents. When the parent terminates the execution of its own body of instructions, it will wait for all forked tasks to terminate before returning.
> To create detached forks, use spawn instead.

So, you won't leave _secondSaga_ until the third ends as the Third will be attached to it, but first it will resolve all the secondSaga body block.

Try using Spawn instead.

**Comment by abettadapur** [comment]
Thanks for the reply!
