### ISSUE TITLE
Proper usage with FileReader?

### ISSUE THREAD

**Issue by Slapbox** [redux-saga/redux-saga#1665]
Can someone provide an example of what the cleanest workflow for using FileReader, (or [PromiseFileReader](https://www.npmjs.com/package/promise-file-reader)) to read a bunch of files in a saga setting would be?

I can imagine a couple of ways, but none of them are particularly clean and easy to reason about. Would I be right to think that using an `eventChannel` would be the best approach?

**Comment by Slapbox** [comment]
So it turns out this works, but I don't understand why:

```js
  const PromiseFileReader = require('promise-file-reader');
  const readContent = yield PromiseFileReader.readAsText(blobData);
  console.log(readContent);
```

Can anyone explain why? Will I run into some unforeseen issue with this approach?

**Comment by Andarist** [comment]
This works because technically you can yield promises (but its not quite recommended, its better to use `call` effect).

Personally I would do this:
```js
function readAsText(blob) {
  return new Promise(resolve => {
    const reader  = new FileReader();
    reader.onload = () => resolve(reader.result)
    reader.onerror = reject
    reader.readAsText(blob)
  })
}
// ...
const content = yield call(readAsText, blob)
```

**Comment by Slapbox** [comment]
@Andarist thank you so much as always for your generosity in helping people with this amazing library!

Besides being better for testing, are there other benefits to wrapping the promise in a function and using `call` like that?

**Comment by Andarist** [comment]
No, there are no other strong benefits. Redux-saga conceptually deals with effects and promise is not an effect, so generally it's advised to avoid yielding them.

**Comment by Slapbox** [comment]
Thanks again @Andarist!
