### ISSUE TITLE
yield select not working in unit tests

### ISSUE THREAD

**Issue by rybon** [redux-saga/redux-saga#1668]
`yield select` does not work in unit tests with the `runSaga` method. Apparently this is a known issue? Will this be fixed in 1.0? I'd rather not test my sagas as generators.

#### Steps to reproduce the bug/issue
See example code below.

#### Example
```
export function* fetch(): Saga<void> {
  let task
  try {
    const url = '/api'
    const variables = {}
    variables.someField = yield select(someFieldSelector) // undefined in unit test
    task = yield forkWithErrorHandler(
      postRequest,
      { url, data: { variables }, cancellationToken: CANCEL }
    )
    const { error, data } = yield join(task)
    if (error) {
      yield put(failure(error))
    } else {
      yield put(success(data))
    }
  } finally {
    if (yield cancelled()) {
      yield cancel(task)
    }
  }
}
```

```
describe('API saga', () => {
  it('should perform the correct effect on success', async () => {
    expect.assertions(1)

    const dispatched = []
    const stub = sinon.stub(services, 'postRequest').callsFake(() =>
      Promise.resolve({
        data: mockSuccessData
      })
    )

    await runSaga(
      {
        dispatch: action => dispatched.push(action),
        getState: () => ({
          someKey: { someField: 'test' } // cannot be resolved with yield select
        })
      },
      fetch,
      triggerAPI()
    ).done

    expect(dispatched).toEqual([
      success(mockSuccessData)
    ])

    stub.restore()
  })
```

### Actual results
Failing unit tests, because values from `yield select` are `undefined`.

### The Expected results
Passing unit tests.

### Environment information
0.16.2

**Comment by Andarist** [comment]
> yield select does not work in unit tests with the runSaga method. Apparently this is a known issue.

It's not known, I don't see why it wouldn't work. Could you prepare a simple codesandbox showcasing the problem? 

> I'd rather not test my sagas as generators.

I definitely applaud that 👍

**Comment by rybon** [comment]
Sorry, was a mistake in my code. My bad.

**Comment by mincedmit** [comment]
@rybon this may be hard to recall but do you remember what the issue in your code was?  Currently experiencing a similar issue.

**Comment by rybon** [comment]
@mincedmit off the top of my head I think it had to do with improperly structured mock data or a circular import related to Redux stuff, such as selectors and reducers. But can’t remember exactly anymore. The CodeSandbox is working though.
