### ISSUE TITLE
Babel-7-jest deprication

### ISSUE THREAD

**Issue by DalderupMaurice** [redux-saga/redux-saga#1670]
### Description
Just wanted to point out that babel-7-jest is currently depricated as you can see right [here](
https://github.com/Sneezoo/babel-7-jest#deprecated). It would be a step forward to replace this module

References in the code: 
https://github.com/redux-saga/redux-saga/blob/76361728b4149c4f6944cda69d3e97ec49bc5118/packages/core/package.json#L69
https://github.com/redux-saga/redux-saga/blob/2db9b0f8e5c5bda9eb900d92eb91a317c8c45a67/package.json#L55
https://github.com/redux-saga/redux-saga/blob/50efcd293414d6c73db93d09faebaadb47b06387/packages/core/babel-transformer.jest.js#L2

**Comment by Andarist** [comment]
Thanks for pointing this out but we are aware about this issue - we are using that module temporarily because we want to support both babel@6 and babel@7 in our babel plugin. Using that module made it slightly easier for the time being from what I remember.
