### ISSUE TITLE
how can I setup a global error handler?

### ISSUE THREAD

**Issue by kabike** [redux-saga/redux-saga#1672]
I knew that exception in call effect should be catched otherwise it will propagate to parent.But I do not want to wirte the same try/catch code everywhere, so can I setup a global error handler for these kind of things.
```
function* fetchProducts() {
  try {
    const products = yield call(Api.fetch, '/products')
    yield put({ type: 'PRODUCTS_RECEIVED', products })
  }
  catch(error) {
    yield put({ type: 'FAILED', error })
  }
}
```

**Comment by Taym95** [comment]
Do you want to catch all uncaught exceptions?

if yes you can do it like this:

`const rootTask = sagaMiddleware.run(rootSaga);
rootTask.done.catch(function (err) {
    console.log("Error in Sagas", err);
});
`

**Comment by Taym95** [comment]
Do you want to catch all uncaught exceptions? if yes you can do it like this:

```const rootTask = sagaMiddleware.run(rootSaga); 
rootTask.done.catch(function (err) {
    console.log("Error in Sagas", err);
 });```

**Comment by Taym95** [comment]
Do you want to catch all uncaught exceptions? if yes you can do it like this:

`const rootTask = sagaMiddleware.run(rootSaga);
rootTask.done.catch(function (err) { console.log("Error in Sagas", err); });`

**Comment by kabike** [comment]
> Do you want to catch all uncaught exceptions? if yes you can do it like this:
> 
> `const rootTask = sagaMiddleware.run(rootSaga); rootTask.done.catch(function (err) { console.log("Error in Sagas", err); });`

But in this way, the rootTask is done.

**Comment by kabike** [comment]
Or how can I make the following code keep running even though there is an error in Api.fetch
```
export function* getAllProducts() {
  const products = yield call(api.getProducts)
  yield put(actions.receiveProducts(products))
}

export function* watchGetProducts() {
  yield takeEvery(actions.GET_ALL_PRODUCTS, getAllProducts)
}
```

**Comment by shinima** [comment]
@kabike You could use the following code to let your saga automatically restart when it encounters an error:

```javascript
function keepAlive(sagaFn) {
  return function*() {
    while (true) {
      try {
        const result = yield io.call(sagaFn)
        console.log('saga completes with result:', result)
        return result
      } catch (e) {
        console.error('saga aborted due to:', e)
        console.log('restarting the saga...')
      }
    }
  }
}

// And your code becomes like...
yield takeEvery(actions.GET_ALL_PRODUCTS, keepAlive(getAllProducts))
```

You can put `keepAlive` at a higher level (say, the rootSaga) to control the granularity of restarting behaviors.restart

**Comment by restrry** [comment]
restart of saga will reset its internal state.
another alternative is to write your own version of `call`
```js
function* safeCallWithReport (fn, ...args) {
  try {
    const result = yield call(fn, ...args)
    return {result, error: null}
 } catch(e){
   report(e) // or yield call (report, e)
   return {result: null, error: e}
 }
```

**Comment by restrry** [comment]
closed as there are no action points here

**Comment by michael-freidgeim-webjet** [comment]
We used function similar to suggested by @Taym95 
```
    sagaMiddleware.run(rootSagas, store.dispatch).done.catch(e => {
        logger.error({ message: e.message, source: 'sagaError', stacktrace: e.sagaStack });
    });
```
with old version "redux-saga": "^0.15.3",, but after I tried to update to the latest V1.1.1,
I am getting TypeError: Cannot read property 'catch' of undefined.
What is correct syntax now?

**Comment by Andarist** [comment]
```js
sagaMiddleware.run(rootSagas, store.dispatch).toPromise().catch(e => {
        logger.error({ message: e.message, source: 'sagaError', stacktrace: e.sagaStack });
    });
```
