### ISSUE TITLE
Lock the channel method

### ISSUE THREAD

**Issue by meiguanxiHXX** [redux-saga/redux-saga#1673]
Help
It means like this:
takeLatest(REPLACE_ELEMENT_DETAILS, method())
I want to begin the method after last method is is completed.

**Comment by shinima** [comment]
You could use the `actionChannel` effect to buffer the actions and use a while-true loop to consums the actions.

```javascript
function* saga() {
  const chan = yield actionChannel('REPLACE_ELEMENT_DETAILS')
  try {
    while (true) {
      const action = yield take(chan)
      yield call(yourHandler, action)
    }
  } finally {
    chan.close()
  }
}
```

**Comment by meiguanxiHXX** [comment]
Thanks for pointing that out

**Comment by meiguanxiHXX** [comment]
> You could use the `actionChannel` effect to buffer the actions and use a while-true loop to consums the actions.
> 
> ```js
> function* saga() {
>   const chan = yield actionChannel('REPLACE_ELEMENT_DETAILS')
>   try {
>     while (true) {
>       const action = yield take(chan)
>       yield call(yourHandler, action)
>     }
>   } finally {
>     chan.close()
>   }
> }
> ```

Thanks for pointing that out
