### ISSUE TITLE
Production bug captured with Sentry

### ISSUE THREAD

**Issue by TheoneLucas** [redux-saga/redux-saga#1675]
Hi,

I've captured a bug in Sentry that I believe to have been thrown by redux-saga, by file `redux-saga/es/internal/proc.js`, at line 466:53. The version of redux-saga I'm using is 0.16.0. Here is a screenshot of the issue:

![image](https://user-images.githubusercontent.com/5532541/48621914-44935680-e98c-11e8-9580-9a218a8eb091.png)

I've made the issue public, here is a link to it: 

https://sentry.io/share/issue/0230d201a3404b01b6c443623a6ed664/

I will be glad to help you guys with any additional information you need

**Comment by Andarist** [comment]
How many times this has happened to your app? Which useragents have been associated with this?

**Comment by TheoneLucas** [comment]
It has happened 1 time with 1 user. He were using Google Chrome v. 70.0.3538 on Mac OS X
v. 10.13.6

**Comment by Andarist** [comment]
That's really strange - might be some obscure v8 engine bug :s If the source map is correct then it means that most likely it has thrown on "missing" `isEnd` which is statically available, its never redefined and its always a function.

I have a strong suspicion that you are using webpack older than v4 and if you are using webpack@3 then you are not using ModuleConcatenationPlugin in your production build. Could you confirm this guess?

**Comment by TheoneLucas** [comment]
Yes, I'm not using the ModuleConcatenationPlugin, but I'm indeed using WebPack 4 (v. 4.16.2)

**Comment by Andarist** [comment]
Do you disable it somehow? (it should be used by default in production mode in webpack@4)

**Comment by TheoneLucas** [comment]
Oh, I've searched for "ModuleConcatenationPlugin" in my production webpack config file and didn't find anything. But if this is enabled by default, then I'm probably using it. I've uploaded my config file, let me know if it can help you:

https://gist.github.com/TheoneLucas/e24327741064d0408a419fc68691225c

**Comment by TheoneLucas** [comment]
I checked the documentation for `onError` function and I will send a bugfix implementing it on my application now, making it send the error to Sentry and as soon as an error is captured with it I will come back here with all the information it gathered.

**Comment by TheoneLucas** [comment]
I just noted that my application already have an `onError` handler on `createSagaMiddleware` function, and it was on production at the time this bug happened.

**Comment by Andarist** [comment]
was the bug reported to sentry through that onError handler?

**Comment by TheoneLucas** [comment]
I don't think so, as the onError function handler don't appear on the error stack.

**Comment by Andarist** [comment]
I would classify this as impossible then - we won't be able to act on it anyhow as it seems it just can't happen and that sentry might be reporting some false positives on this one.

**Comment by TheoneLucas** [comment]
Ok, if this error happen again I will make sure to get back on here with more details.

**Comment by Andarist** [comment]
Thanks! For now I'm not going to close this issue, but let us know if you find more about it.
