### ISSUE TITLE
onError execution: why is !task.cont condition needed and what does it mean?

### ISSUE THREAD

**Issue by Fs00** [redux-saga/redux-saga#1676]
I've spent almost an entire afternoon trying to figure out why the function I passed to `onError` in `createSagaMiddleware(options)` didn't get called, even though I was throwing Errors in my sagas to trigger it.
Then I found this in Saga code:
https://github.com/redux-saga/redux-saga/blob/ffd57bb559f39f4e205ce96ebd0d67a67e714bcd/src/internal/proc.js#L334
That condition was preventing onError to get called. Why is there and what that means?
To better understand my context, this is my rootSaga:
```js
export default function* rootSaga() {
  yield all([authFlowSaga(), ...commitsSagas]);
}
```
`authFlowSaga` is a generator which waits for actions in an infinite loop, while `commitsSagas` looks like below:
```js
export const commitsSagas = [
  autoListUpdateCheckController(),     // generator which waits for actions
  takeLatest(COMMITS_ACTION_TYPE_KEYS.COMMITS_LIST_PAGE_REQUEST, retrieveCommitsListPage)
];
```
Hope that someone can clarify my doubts and help me to make onError method work.

**Comment by Andarist** [comment]
It's handled like this because errors are bubbled up through the sagas (so you can catch the error in a parent with try/catch) - so that check is basically supposed to mean "call onError when there is no parent that could catch this"

**Comment by Fs00** [comment]
I tried using a try/catch block in rootSaga, but exceptions coming from `retrieveCommitsListPage` are not caught. Is that because takeLatest is called inside an array declaration?
However, I feel like that onError behavior is kinda flawed. In this way, "potentially catchable" errors that are uncaught will never be reported. And furthermore, API reference is not clear at all on this point.

**Comment by Andarist** [comment]
Could u prepare a simple condesandbox.io for us to take look at that would demonstrate your issue?

**Comment by restrry** [comment]
@Fs00 you mean this code doesn't catch an error?
```js
try{
  yield add([...])
} catch(e){
```
>Note that though fork effects are nested in an all effect, they are always connected to the parent task through the underlying forkQueue. Uncaught errors from forked tasks bubble to the parent task and thus abort it (and all its child tasks) - they cannot be caught by the parent task.

https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/RootSaga.md#nesting-fork-effects-in-all-effect

**Comment by Andarist** [comment]
Just adding to what @restrry has said - they should still be received by the onError option and I believe they are right now - so if you are seeing something different it would be great to get a codesandbox showcasing your problem.

**Comment by Fs00** [comment]
@restrry If the code you posted doesn't catch errors, then an exception which is "bubbled up" is not necessarily catchable? I think there's something that I'm missing.
And I suspect I'm currently making some mistakes, because the generator `authFlowSaga` in my code is not forked (and probably it should, since it doesn't return a task descriptor). I'll do some more testing and I'll let you know.

**Comment by Andarist** [comment]
> The only thing I can't get is why in rootSaga I can intercept bubbled errors from forked tasks with a finally block, but not with a catch one.

Not sure what do u mean by that.

The problem with forked sagas is that after forking the forking generator is at unknown (to us) state - we can't inject an exception into it, because it might be already at the point past any catch clause. That's why those errors are not catchable in the parent saga.

**Comment by Andarist** [comment]
Sorry, I still dont quite understand the problem - could u prepare a codesandbox showcasing it? It would ease getting us on the same page.

I think u might mix block and non-blocking effects in your try clause, but Im not sure without looking at the concrete example

**Comment by Fs00** [comment]
I have no problems anymore. It's just that I can't understand the behavior of fork exceptions described in the docs. You say that an exception bubbled from a task is not catchable (and it's true), but then why am I able to intercept it using a `finally` block?

**Comment by Fs00** [comment]
Oh lol, I'm dumb. :joy:  
I forgot that it's the normal behavior of finally. Thus, since in the `try` I have an `all` Effect which includes at least a task that runs a `while(true)` loop, whenever a task fails, `all` Effect aborts and the `finally` block is reached.  
Thanks everyone for helping me to reach the conclusion. And sorry for the time I took you.:smile:
