### ISSUE TITLE
Fire actions from event handlers outside of sagas or react components.

### ISSUE THREAD

**Issue by laur89** [redux-saga/redux-saga#1677]
There's a requirement to fire actions from within 3rd party component's eventHandlers (eg. jwplayer).

Say there's following saga:

    import {initAndConfigurePlayer} from 'src/b';

    function* createPlayer() {
      const config = select(({config}) => config);
    
      const player = yield call(initAndConfifurePlayer, config);
      yield put(actions.playerStarted(player));  // player instance is stored
    }

`initAndConfigurePlayer` would be a function imported from module `B`:

    const initAndConfigurePlayer = config => {
    
      const player = window.jwplayer(config);  // pseudocode
	  player.on('error', error => {
        // ! action would need to be fired from here
      });
    
      return player;
    };

What is the proper way to achieve this? Should an instance of module `B` be created, and redux `store` passed to it (i.e. vanilla redux usage)?

**Comment by Andarist** [comment]
eventChannel
