### ISSUE TITLE
TS typings for v1

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#1683]
Need to do this https://github.com/redux-saga/redux-saga/pull/1655#issuecomment-440672034 , also @aikoven has some other things that he'd like to refactor before stable v1.

**Comment by Andarist** [comment]
@aikoven do u know when you will be able to refactor those typings? (no pressure - just asking)

**Comment by aikoven** [comment]
I’m planning to do this within the next two weeks. Is that ok?

**Comment by Andarist** [comment]
Sure thing :)

**Comment by lukasbash** [comment]
If I may throw in a question, even if its a specific one.
What is the status on infering type definitions over the `yield` keyword?

I could not find the correct issue in the typescript repo directly. Do you have any updates in here if this is "only" a TS thing, or if you have to fix something in the lib as well?

**Comment by restrry** [comment]
ts doesn't support this and seems isn't going to add support. issue in ts repo https://github.com/Microsoft/TypeScript/issues/2983

**Comment by TotooriaHyperion** [comment]
@lukasbash @restrry 
In my view, it's noway to define the type when the value itself doesn't linked to a real runtime type.
Means only if the language treat a type as an object too, or this type inference would be impossible.

A pre-defined type is also unacceptable, as it couples the generator function and the effects. Which makes the generator function not pure, and the effects not reusable.

But on the other hand, I think **_what's really matters_** is that **_an effect description should have close connection with the expect behavior of the effect_**, which means **_including the type that(whenever it needs) to be returned_**.

Thus I got an idea to solve the problem by a convention that a effect description as a object, to carry the result back.

Example:
> got an idea to have yield return type connect with the yield value type:
> 
> ```ts
> interface EffectBase<T> {
>   type: EffectType;
>   ret: T;
> }
> 
> async function* testCall() {
>   // we can define the type of return value of QueryModelEffect
>   // meanwhile define the type of the future return: query.ret
>   // as the type of a effect description should be match with it's yield return value type
>   const query = QueryModelEffect(......);
>   yield query;
>   const { id, name } = (await query.ret)!;
>   console.log(123, { id, name });
> }
> 
> async function exmpleRunner() {
>   const gen = testCall();
>   let done: boolean = false;
>   while (!done) {
>     const res = await gen.next();
>     done = res.done;
>     if (done) {
>       break;
>     }
>     res.value && (res.value.ret = await performEffect(args));
>   }
> }
> ```
> 
> not sure if it's anti-pattern, but works well for my case as all the yield value is a simple object describing the effect.

**Comment by lukasbash** [comment]
@TotooriaHyperion Thanks for your reply!
Interesting pattern I see here:
```typescript
const query = QueryModelEffect(......);
yield query;
```

The thing is, with this pattern, you get the type inference of the effect and not the type of the value it could possibly return or deliver.
Let's make an example of a casual select effect in a saga:
```typescript
// state is now typeof "ReduxSagaEffects.SelectEffect"
const state = select();
yield state;

// here i want to have to use the actual type of my redux state and not just the effect
// this should happen automatically
```

The issue stays the same, as you are describing the return value of the effect with generics the result would be the same as if I would type it manually like:
```typescript
const state: MyState = yield select();
```

Maybe I did not understand the example correctly. Or it might be that I also did not understand the saga typings correctly. But the effect descriptor should in my opinion already know the type of the delivered value. And `yield` should be just a passthrough as it does actually not alter any values, it just describes how to wait or not wait for code execution.
Anything wrong here in my thoughts?

**Comment by TotooriaHyperion** [comment]
@lukasbash 

Manually type it is a good solution, but it split code to parts.

Sometimes we want **_auto_** type inference, especially when using **_third-party library_**.
My case was using with sequelize, and manually write the returntype of an model's querymethods is verbose.

```typescript
import EffectType from "./constants/effectType";
import SequelizeModel from "./interfaces/SequelizeModel";
import EffectBase from "./interfaces/EffectBase";

export type QueryModelArgs<Model, M extends keyof Model> = [
  Model,
  M,
  Model[M] extends AnyFun ? Parameters<Model[M]> : undefined
];

export type QueryModelRet<
  Model,
  M extends keyof Model
> = Model[M] extends AnyFun ? ReturnType<Model[M]> : any;

export interface QueryModelEffect<Model, M extends keyof Model>
  extends EffectBase<QueryModelRet<Model, M>> {
  type: EffectType.QUERT_MODEL;
  args: QueryModelArgs<Model, M>;
}

export default function performQueryModel<
  T,
  M extends keyof SequelizeModel<T>
>([model, method, param]: QueryModelArgs<SequelizeModel<T>, M>): QueryModelRet<
  SequelizeModel<T>,
  M
> {
  return (model[method] as any)(...(param as any));
}

export function queryModel<T, M extends keyof SequelizeModel<T>>(
  args: QueryModelArgs<SequelizeModel<T>, M>,
): QueryModelEffect<SequelizeModel<T>, M> {
  return {
    type: EffectType.QUERT_MODEL,
    args,
    cps: undefined as any,
  };
}

```

In this example, we only need to type once, then we can use it for all model.(super convenient on generic type)
YieldType is connected to YieldReturnType automatically.
Special trick to simplify code written in typescript.

This actually should be done by language using type as a object. But in js, I only find this way to use yield with ts conveniently.
