### ISSUE TITLE
Do you plan to add a takeLatestDeep helper ?

### ISSUE THREAD

**Issue by guillaumewuip** [redux-saga/redux-saga#1686]
### Description
I am looking for a saga helper effect that behave like `takeLatest` but where we can group actions by some payload properties.
My use case is I think quite common : I'm using redux-saga to listen for api request actions and I want to not duplicate http requests to the same entity (defined by an id). 

Code example that is not working : 

```js
function get(id) {
  return fetch(`${URL}/${id}`);
}

function* makeRequest(action) {
  const result = yield call(get, action.payload.id);
  yield put({
    type: REQUEST_SUCCESS,
    payload: {
      request,
    }
  });
}

function* mainSaga() {
  yield takeLatest(REQUEST, makeRequest);
  // this will cancel all ongoing requests
  // not just requests with the same action.payload.id
}
```

I came across this [Stackoverflow question](https://stackoverflow.com/questions/45572331/redux-sagas-fetch-only-once-when-same-id-is-dispatched-multiple-times) that helped me understand what I can do for this.

So, what I need is something like : 

```js
import {
 take,
 fork,
 cancel,
} from 'redux-saga';

const takeLatestDeep = (pattern, identifier, fn, ...args) => fork(function* () {
  const tasks = {};

  while(true) {
    const action = yield take(pattern);
    const id = identifier(action);

    if (tasks[id]) {
      cancel(tasks[id]);
    } 
    
    tasks[id] = yield fork(fn, ...args.concat(action));
  }
}
```

That I can use like this : 

```js
yield takeLatestDeep(
   REQUEST,
   action => action.payload.id,
   makeRequest,
);
```

Is it something that you think can be added to redux-saga helpers ?
If yes, I can make a PR for it :)

**Comment by restrry** [comment]
`take` allows you specify custom matcher, so it should be sufficient https://redux-saga.js.org/docs/api/#takepattern
```js
yield takeLatest((action) => action.type === 'ACTION_NAME' && action.payload === 1)
```

**Comment by guillaumewuip** [comment]
Thanks for your answer @restrry 
I'm not sure the custom matcher can help me in this case. I don't know the id value and I don't want to match only one id value either.
I would like a generic way of grouping actions with `takeLatest`, ie. having a way to tell `takeLatest` to only cancel previous task if the corresponding previous action has the same id as the actual one.

Actually `takeLatestDeep` looks like a bad name for a helper like that. It's probably better named `takeLatestGroup`.

**Comment by Andarist** [comment]
There is currently no plans regarding including this in the core - I believe it's too specific and should be implemented in your app or as npm package if you want to share it with the community. Saga's effects are nicely composable so you can leverage that instead of relaying on us providing it for you. Hope this makes sense for you.

**Comment by guillaumewuip** [comment]
Yep, no problem @Andarist !
Thanks for your time :)
