### ISSUE TITLE
Can we use redux-saga with useReducer?

### ISSUE THREAD

**Issue by hudovisk** [redux-saga/redux-saga#1692]
### Description
I know redux-saga is supposed to be used with redux, but I was wondering if there is a way to use it with the new hooks api of react.
This is my attempt so far but it doesn't seem very performant (as sagaMiddleware.run is called multiple times):
```jsx
function applyMiddleware(...middlewares) {
  middlewares = middlewares.slice();
  middlewares.reverse();

  return (state, dispatch) => {
    const store = {
      getState: () => state,
      dispatch
    };
    
    middlewares.forEach(middleware => (dispatch = middleware(store)(dispatch)));

    return dispatch;
  };
};

const sagaMiddleware = createSagaMiddleware();
const enhanceDispatch = applyMiddleware(logger, sagaMiddleware);

function useBooksReducer() {
  let [state, dispatch] = useReducer(booksReducer, initialState);
  dispatch = enhanceDispatch(state, dispatch);

  sagaMiddleware.run(booksSagas);

  return [state, dispatch];
} 
```

Is there a correct way of using it with the new hooks api?

**Comment by Andarist** [comment]
Early experimentation - https://codesandbox.io/s/82vmz6r198

**Comment by martinkadlec0** [comment]
React hooks are out. Really looking forward to some less experimental saga hooks :)

**Comment by RubenSandwich** [comment]
@Andarist Thank you so much for your example.

I cleaned it up a bit, removed unused code, and here is the cleaned up version: https://codesandbox.io/s/v10vr0pj53.

One problem I can see with this implementation, however, is that I believe it ties the hook to the component lifecycle. (When the component dies so does the sagas.) I wonder if there is any way to prevent that. (My first pass would be creating a global "sagaEnv" and then passing that in when creating the useReducerAndSaga hook, but I have a feeling that if we want long-running sagas then we need global state so we are already better served with Redux. 🤷‍♀️ )

**Comment by Andarist** [comment]
yeah, this hook works only for component-specific sagas, if you want to register long running tasks you have to implement some kind of provider on top of your app which would receive registration requests, u'd have to rethink when such saga should die though.

**Comment by anguyen1817** [comment]
It would be awesome if redux-saga officially supports `useReducerAndSaga` from that early experimentation.

**Comment by rwieruch** [comment]
Why not just using Redux if you have one or more of the following requirements:

* side-effect library (redux-saga, redux-thunk, ...)
* middleware
* global store with combined reducers

Everything else would be reinventing the wheel, wouldn't it?

**Comment by RubenSandwich** [comment]
@rwieruch,

This whole thread is more about experimentation and "what if". In that sense, it's fine to "reinvent the wheel". I don't think anyone in this thread is even completely sure if this code would be "useful", but the experimentation is fun and might provide fertile ground in the future.

**Comment by Federkun** [comment]
This seems a good way to solve problems like

https://github.com/redux-saga/redux-saga/issues/907
https://github.com/redux-saga/redux-saga/issues/1842
and more

In combination with the react's context api, it would give you a lot more options before you even consider adding a redux store in your project. Really looking forward to see how this discussion continue.

**Comment by caasi** [comment]
Inspired by @Andarist and @RubenSandwich, here is another mini `useReducerAndSaga`:

```javascript
function useReducerAndSaga(reducer, initialState, rootSaga) {
  const [state, reactDispatch] = useReducer(reducer, initialState)
  const env = useRef(state)
  env.current = state
  const channel = useMemo(() => stdChannel(), [])
  const dispatch = useCallback((a) => {
    setImmediate(channel.put, a)
    reactDispatch(a)
  }, [])
  const getState = useCallback(() => env.current, [])

  useEffect(() => {
    const task = runSaga({ channel, dispatch, getState }, rootSaga)
    return () => task.cancel()
  }, [])

  return [state, dispatch]
}
```

Unfortunately it's still bind to the current component lifecycle.

**Comment by therealparmesh** [comment]
I published something that is based on the discussion here. Hopefully it helps push this issue along. 😄 

https://github.com/therealparmesh/use-react-saga

```jsx
function* incrementAsync() {
  const previousState = yield select();

  yield call(console.log, "I AM STARTING TO INCREMENT FROM", previousState);
  yield delay(2000);
  yield put({ type: "INCREMENT" });

  const state = yield select();

  yield call(console.log, "I AM FINISHED INCREMENTING TO", state);
}

function* saga() {
  yield takeLatest("INCREMENT_ASYNC", incrementAsync);
}

export const Example = () => {
  const [state, dispatch] = React.useReducer((state, action) => {
    switch (action.type) {
      case "INCREMENT":
        return state + 1;
      default:
        return state;
    }
  }, 0);

  const put = useReactSaga({ state, dispatch, saga });

  return (
    <div>
      <p>Clicked {state} times!</p>
      <button onClick={() => put({ type: "INCREMENT_ASYNC" })}>
        increment async
      </button>
    </div>
  );
};
```

**Comment by therealparmesh** [comment]
Here's a CodeSandbox example: https://codesandbox.io/s/use-react-saga-example-e8rrz

I've updated the library to try to tackle problems around calling select and the number React updates.

**Comment by cesarvargas00** [comment]
> Why not just using Redux instead of useReducer if you have one or more of the following requirements:
> 
> * side-effect library (redux-saga, redux-thunk, ...)
> * middleware
> * global store with combined reducers
> 
> Everything else would be reinventing the wheel, wouldn't it? Asking out of curiosity!

In my case (not sure if of any relevance), I'm not using redux because I do not want to keep a global store with combined reducers.

**Comment by martinkadlec0** [comment]
Also it is generally not recommended to keep UI state in redux, but because we need to update some state from sagas, we have to lift some UI the state to redux anyway.

Personally I would like to keep using redux fro application/data layers of my app, but for components it would be neat to have an interface to work directly with the components state.

The question is, how would the interface look to allow working with both redux & the component in the same saga.

**Comment by neurosnap** [comment]
Greetings!  This issue have been inactive for a few years so I'm going to close for now.  If anyone wants to continue to chat about this issue then I'd be happy to reopen and help.
