### ISSUE TITLE
How can I wait all 'put' actions finished in running parallel?

### ISSUE THREAD

**Issue by tomzaku** [redux-saga/redux-saga#1693]
### Description
```
const data = yield all([
        // @TODO: Should be use action function.
        yield put({
            type: '@@app/PCPNAME/QUERY',
            payload: {},
        }),
        yield put({
            type: '@@app/PCPREGIONNAME/QUERY',
            payload: {},
        }),
        yield put({
            type: '@@app/PCPGROUPNAME/QUERY',
            payload: {},
        }),
        yield put({
            type: '@@app/SERVICETYPE/QUERY',
            payload: {},
        }),
        yield put({
            type: '@@app/PCPPRIMARYSPECIALTY/QUERY',
            payload: {},
        }),
    ])
console.log('DATA >>>', data)
```
When I run this function, the 'DATA >>>' run before actions such as: '@@app/PCPPRIMARYSPECIALTY/QUERY', '@@app/PCPNAME/QUERY'....

How can I wait all the actions finished?

Related: https://stackoverflow.com/questions/53531648/how-can-i-wait-all-put-actions-finished-in-running-parallel

**Comment by GabrielFerrarini** [comment]
If I understand you correctly, then put doesn't "execute" the action. It dispatches it to the redux store and then other sagas will listen and execute the actions independently (depending on how you implemented them). If you want the actual queries/api calls to be executed in parallel and awaited for, you should yield an array of "call" effects, like this: https://redux-saga.js.org/docs/advanced/RunningTasksInParallel.html

**Comment by tomzaku** [comment]
@GabrielFerrarini Thanks. The main reason i don't want to duplicated the code because I wrote 5 query in saga. 
for example:
```
function* queryList(action: ActionResourceType<"QUERY">) {
		const data = yield call(ajax.query(serverConfig), action.payload.params)
		yield put(actionCollection.addManyLocal(data))
}
...
yield takeLatest('@@app/PCPPRIMARYSPECIALTY/QUERY', queryList),
```

Is there anyway to avoid duplicated?
Thanks
