### ISSUE TITLE
Feature Request / Suggestion: Selector Channels

### ISSUE THREAD

**Issue by knpwrs** [redux-saga/redux-saga#1694]
I have run into a situation where I think the following pattern could be useful:

```js
function* exampleSaga(selectorOutput) {
  // use selectorOutput
  // yield effects
  // dispatch actions
}

function* mainSaga() {
  yield takeEvery(selectorChannel(selector), exampleSaga);
}
```

Basically have a saga that runs whenever the output of a selector changes. The motivation for such a feature is to be able to react to derived changes from the redux store (changes that can result from various disparate sagas, making it difficult to use channels to communicate directly from saga to saga). Currently I am modeling the above situation with something like the following:

```js
// Abuse the `createSelector` API to run effects when a given selector changes its output:
const runEffectsOnChange = createSelector(selector, async (selectorOutput) => {
  // use selectorOutput
  // you cannot yield effects
  // but you can dispatch actions
  store.dispatch(actionCreator(args));
});

store.subscribe(() => runEffectsOnChange(store.getState()));
```

One big disadvantage of this approach is the lack of distinction between `takeEvery` and `takeLatest`. There are ways to work around this, but I think it would be more elegant to be able to use the abstractions provided by `redux-saga`.

I don't know if other people would find this to be useful, or how practical it would be to implement. One problem I could potentially see with a pattern like this is that people could get themselves into an infinite loop if they don't write good selectors.

**Comment by Andarist** [comment]
Wouldnt this work for you?
```js
const createSelectorChannel = (selector, buffer) => call(function*() {
	const chan = channel(buffer)
	let previous

	yield spawn(function*() {
		try {
			while (true) {
				yield take('*')
				const result = yield select(selector)
				if (previous !== result) {
					previous = result
					chan.put(result)
				}
			}
		} finally {
			chan.close()
		}
	})

	return chan
})
```

**Comment by knpwrs** [comment]
Ah, `take('*')`. That's very interesting. Would the `select` effect be executed before or after the action makes its way through the store (i.e., would I get the state resulting from that particular action or would I get the state from before that action)?

**Comment by knpwrs** [comment]
Awesome. That only leaves me with two questions:

1. Is that order of execution something that the `redux-saga` maintainers would be willing to commit to? Meaning if it changes that would be considered a breaking change which would constitute a major semver bump?
1. Would you mind if I were to distribute that code snippet as an NPM module under the MIT license?

**Comment by Andarist** [comment]
1. Yes, this wont change.
2. Sure thing, go ahead :)

**Comment by knpwrs** [comment]
Published on npm as [`redux-saga-select-channel`](https://www.npmjs.com/package/redux-saga-selector-channel)!

Source code: https://github.com/knpwrs/redux-saga-selector-channel

Thanks for the help!
