### ISSUE TITLE
Recommended way to handle all saga errors 

### ISSUE THREAD

**Issue by aarosil** [redux-saga/redux-saga#1698]
I've been searching through the issues about how to handle saga errors and wondering if there's any recommended way to catch uncaught saga exceptions *without* having to put try/catch inside every saga. 

My use case is showing a modal whenever the app JS crashes so I don't need to handle errors individually at all, just need to catch uncaught exceptions and issue some `SET_APP_ERROR_STATE` action that will trigger showing the modal.

I see 1.0 release is in beta which will completely rework error handling, so I'm not keen to add a lot of code in the interim before that, given I don't need to address specific errors at all. More like a high level wrapper would be most useful.

Is there any progress w/ `safe` saga effect? Or any relevant issues/gists how to "roll my own"? Any help/input greatly appreciated. Thanks for the nice library 😃

**Comment by Andarist** [comment]
I plan to release release candidate of v1 this week and on your place I would wait for it. I would use `onError` option to `createSagaMiddleware` to listen for all errors and show a modal from there (i.e. by dispatching a redux action there).

`safe` wrapper can be easily implemented in userland:
```js
const safeCall = (saga, ...args) => call(function* () {
    try {
        return { err: false, result: yield call(saga, ...args) }
    } catch (err) {
        return { err: true, result: err }
    }
})
```

**Comment by aarosil** [comment]
Thanks, I'll try this out. 

Is there any issue for tracking the v1.0 release, or any update docs I can view? I'm interested in breaking changes and stuff I can get ready to try the release candidate.

**Comment by Andarist** [comment]
docs are merged into the master branch, as to the breaking changes and stuff the best thing you can follow is our release notes here https://github.com/redux-saga/redux-saga/releases . As you can see there are really not that many of breaking changes, v1 is just a slight evolution, not the revolution

**Comment by aarosil** [comment]
Thanks, it looks great! 

I have one more question regarding your other other suggestion to use `onError` option of `createSagaMiddleware` to dispatch the `SET_ERROR_STATE` action.

How would I access `dispatch` from within the function I give as `onError`? Store is not created yet, so I don't have reference to `dispatch`. 

I'm thinking I may not understand that suggestion fully

**Comment by Andarist** [comment]
Just use the store reference from the outer scope

**Comment by aarosil** [comment]
Sorry, I'm still not following 100%! 
I'm using vanilla store creation similar to the below, from the tutorial:

```js
import { createStore, applyMiddleware } from 'redux'
import createSagaMiddleware from 'redux-saga'

// ...
import { helloSaga } from './sagas'

const sagaMiddleware = createSagaMiddleware({
  onError: () => {
    // how to access dispatch at this point?
  }
})
export default createStore(
  reducer,
  applyMiddleware(sagaMiddleware)
)
```
Could you share a quick gist of accessing store from the outer scope?

**Comment by Andarist** [comment]
```
import { createStore, applyMiddleware } from 'redux'
import createSagaMiddleware from 'redux-saga'

// ...
import { helloSaga } from './sagas'

const sagaMiddleware = createSagaMiddleware({
  onError: () => {
    store.dispatch({ type: 'SET_ERROR_STATE' })
  }
})

const store = createStore(
  reducer,
  applyMiddleware(sagaMiddleware)
)

export default store
```

**Comment by restrry** [comment]
and keep in mind if error bubbles to root saga and you have `onError` called --> the whole saga tree is terminated, so either your `dispatch` is used only for changing redux store or your action handler should be run as `spawn` effect. Usually I consider `onError` as fatal situation and don't use any redux semantic inside

**Comment by Andarist** [comment]
I think dispatching an action here (to trigger some UI change) is fine but yeah - this should be used mostly for logging purposes / terminating the app. You can't recover there, if `onError` gets called your app is already in unpredictable state and it's better to gracefully destroy your resources and fix your bug asap.

**Comment by restrry** [comment]
seems that we should add it in docs, if we don't have such notices yet

**Comment by Andarist** [comment]
Sure, good idea 👍

**Comment by levenleven** [comment]
@restrry So basically there's no "built in" mechanism for global error handling (which won't terminate the whole saga tree)? 

Example use case: if any network call results in `401` - redirect to login page

**Comment by Andarist** [comment]
You can easily built that on top of existing APIs. You just need to think about your system in explicit manner without hiding implementations in some global handlers implicitly.

Just built a generic request saga which you can use whenever you'd like to use fetch (or similar)

**Comment by levenleven** [comment]
@Andarist Sure, that's what we did.. But there're some other cases (reporting, etc.) where it could be useful. Also having global error handler I can be sure that **all** errors will be reported (just for example), in opposite to having a "wrapper" that developer can choose not to use for some reason.

Anyway, thanks for suggestion!

**Comment by restrry** [comment]
All errors cannot be handled just by one error handler, as their context and nature are different.
Say network error could be handled locally, but runtime exception shouldn't.
https://blogs.msdn.microsoft.com/ericlippert/2008/09/10/vexing-exceptions/
Yes, we can add a wrapper that receives all exceptions from code (say, for reporting, not for handling), but this wrapper won't have runtime context information. And anyway, users will have to do them manually, which is not different from the situation we have today. Correct me if I'm wrong.

**Comment by Andarist** [comment]
The problem lies in that only you as app developer can know which errors are expected and which are not. We pass only completely unhandled errors to the current global `onError` and u can log all of them there.

**Comment by levenleven** [comment]
What I was looking for is the option to analyze the error and decide if it should blow up the entire app or not.

**Comment by restrry** [comment]
added some docs https://github.com/redux-saga/redux-saga/pull/1721 
can we add something else?

**Comment by Andarist** [comment]
I think we can close it. If you have any further questions feel free to open new issue.

**Comment by nemrath** [comment]
pff. let the app dev decide when the app should terminate.
