### ISSUE TITLE
Is it possible to catch an error thrown from a call()ed saga?

### ISSUE THREAD

**Issue by edzillion** [redux-saga/redux-saga#1701]
Sorry to bother you fine peeps but I can't find a definitive answer to this anywhere. 

So let's say I have one saga:
```
export function * initSignUp (action) {
  try {
    yield call(signUp, action.signUpDetails)
  } catch (err) {
    console.log('caught in initSignUp', err)
    yield put({ type: 'SIGN_UP_FAIL', err, action })
  }
}
```

which call()s another:
```
export function * signUp (action) {
  try {
    let response = yield Auth.signUp({...})
    yield put(addData({...}))
  } catch (err) {
    console.log('caught in signUp', err)
    throw new Error(err)
  }
}
```

If the inner saga here fails on yield `Auth.signUp()` then the first catch block is hit, but throwing the error results in an uncaught exception. 

Is it possible to catch the error in `signUp` here? I keep seeing people using this pattern instead of throwing the error:
```
try {
  ...
} catch (error) {
  yield put(Actions.loginFailure(error));
}
```

but then each specific action needs a fail and success action to go with it, and that seems a lof of repetition & biolerplate (?)

I have a SO issue here: https://stackoverflow.com/questions/53630496/failing-to-catch-errors-thrown-by-a-redux-saga-calling-another-saga/53631751#53631751

**Comment by edzillion** [comment]
> Yes, errors propagate through the "saga stack". So if you inner doesnt handle it the outer saga has a chance to handle it. This applies to call/apply/cps effects (and other blocking ones, i dont mention here ie select as u generally dont want ur select effects to throw)

Ok, thanks for the clarification.

I wonder why the parent saga isn't catching the error here? The call stack shows:
```
[14:04:16] uncaught at rootSaga, at rootSaga                                                                                               
 at rootSaga                                                                                                                               
 at takeEvery                                                                                                                              
 at signUp                                                                                                                                 
 TypeError: Cannot read property 'username' of undefined                                                                                   
```
so I put a try catch block around the `yield all` that spawns this saga, like so:
```
function * onboardingSaga () {
  try {
    yield all([
      takeEvery(INIT_SIGN_UP, initSignUp),
      ...
    )]
  } catch (err) {
    // still not getting the error here
  }
}
```

But I still can't catch the error. super confused.

**Comment by Andarist** [comment]
`takeEvery` is basically `fork(internalTakeEveryImplementation)`, errors caught in forked tasks cannot be caught like this.

Why? Because of this:
```js
function* foo() {
  console.log(2)
  yield delay(0)
  console.log(4)
  throw new Error('test')
}

function* saga() {
  try {
    console.log(1)
    yield fork(foo)
  } catch (err) {
    // never
  }
  console.log(3)
}
```

When the error in forked task gets thrown your parent saga might be already outside of the try/catch block

**Comment by tichaonax** [comment]
So we had this scenario and realized we needed a "higher order function" approach. The idea is you implement the try catch in the higher function and it will catch all errors that happen inside your saga. In our case we log to redux these errors and is helpful during debugging, but you could easily do what you want with the errors. Notice you do not need the try catch in your sagas it is all in one place. createAction is nothing but a utility function that creates actions to spare you the pain of writing actions manually.

export const createAction = (type, ...argNames) => {
  return (...args) => {
    let action = { type };
    argNames.forEach((arg, index) => {
      action[arg] = args[index];
    });
    return action;
  };
};


(A) Create a file that has both the action and the higher order function
......
import { put } from 'redux-saga/effects';
import { createAction } from '../utilities';
export const SET_SAGA_ERROR = 'SET_SAGA_ERROR';
export const setSagaError = createAction(SET_SAGA_ERROR, 'errors');

export function safeSaga(func) {
  return function* (args) {
    try {
      yield* func(args);
    } catch (error) {
      yield put(setSagaError({ saga: func.name, args, error }));
    }
  };
}

(B) Then your saga will be something like this

import { call, put, takeLatest } from 'redux-saga/effects';

import { updateCart } from '../../services';

import { safeSaga, CART_ITEMS, updateCartItems } from '../../actions';

function* cartUpdate(action) {
  //your saga implementation
  const { data } = yield call(updateCart, action.items);
 yield put(updateCartItems(data));
}

export function* cartUpdateSaga() {
  yield takeLatest(CART_ITEMS, safeSaga(cartUpdate));
}

export default cartUpdateSaga;


**** you can put logging steps in the safeSaga function to see exactly what is happening ****

**Comment by restrry** [comment]
closed as there are no action points here

**Comment by edzillion** [comment]
Fine but I consider this question still unanswered. Probably needs documentation

**Comment by restrry** [comment]
let's clarify what kind of documentation could be useful here. recommended approach to handle async exceptions in saga?
because as I can see the initial question was about handling error for `call` effect, that's blocking operation and using `try/catch` should be sufficient.
for non-blocking operations it's a bit harder, as race there could be a race condition and try/catch is already passed when exceptions rose. therefore `spawned` or `forked` saga should be safe. you can use the approach that  @tichaonax suggested above or implement your own.
actually, we have a lot of questions about error handling, thus it's helpful for us to know what is unclear from the docs

**Comment by mihaisavezi** [comment]
Just had to format @tichaonax answer

```javascript
export const createAction = (type, ...argNames) => {
  return (...args) => {
    let action = { type };
    argNames.forEach((arg, index) => {
      action[arg] = args[index];
    });
    return action;
  };
};
```
(A) Create a file that has both the action and the higher order function

```javascript
  ......
import { put } from 'redux-saga/effects';
import { createAction } from '../utilities';
export const SET_SAGA_ERROR = 'SET_SAGA_ERROR';
export const setSagaError = createAction(SET_SAGA_ERROR, 'errors');

export function safeSaga(func) {
  return function* (args) {
    try {
      yield* func(args);
    } catch (error) {
      yield put(setSagaError({ saga: func.name, args, error }));
    }
  };
}
```

(B) Then your saga will be something like this
```javascript 
import { call, put, takeLatest } from 'redux-saga/effects';

import { updateCart } from '../../services';

import { safeSaga, CART_ITEMS, updateCartItems } from '../../actions';

function* cartUpdate(action) {
  //your saga implementation
  const { data } = yield call(updateCart, action.items);
  yield put(updateCartItems(data));
}

export function* cartUpdateSaga() {
  yield takeLatest(CART_ITEMS, safeSaga(cartUpdate));
}

export default cartUpdateSaga;
```
