### ISSUE TITLE
take effect doesnt return an action anymore in beta

### ISSUE THREAD

**Issue by klis87** [redux-saga/redux-saga#1702]
### Steps to reproduce
For some reason below code doesn't work anymore in latest beta:
```js
const action = yield take(a => isRequestAction(a) && (!a.meta || a.meta.runByWatcher !== false));
```
It doesn't return action object anymore, but `{"@@redux-saga/IO":true,"TAKE":{...}}`, which looks like effect instructions for redux-saga, not the action.

#### Description of the bug/issue
You can see the full context of above snippet here: https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests/src/sagas.js#L239

I read releases of beta and I didn't notice any change for `take`, am I missing something or just beta doesn't work properly yet?

### Environment information
- redux-saga version: `1.0.0-beta.3`

**Comment by restrry** [comment]
are you sure that problem is in this snippet? 
action from `take` test shows it should work as expected https://github.com/redux-saga/redux-saga/blob/master/packages/core/__tests__/interpreter/take.js#L5-L119

**Comment by klis87** [comment]
@restrry I am sure, because I don't do anything fancy at https://github.com/klis87/redux-saga-requests/blob/master/packages/redux-saga-requests/src/sagas.js#L239, just `take` an action, plus everything works in redux-saga 0.16. Unfortunately I cannot do unit tests because I use redux-saga-test-plan which doesnt support redux saga `1.0.0-beta.3` yet. 

If thats not problem for you re debugging, you can add console.log to check returned `action` by `take`, then build everything with `yarn build` in project root, then you can go to examples, like https://github.com/klis87/redux-saga-requests/tree/master/examples/advanced

**Comment by Andarist** [comment]
You have to update `redux-saga` across whole project. At the moment you are using v1 runtime but 0.16 effects.

**Comment by klis87** [comment]
@Andarist what do you mean, effects were moved to a separate package? Do we have any migration guide?

**Comment by Andarist** [comment]
They are still part of the core package, but your `redux-saga-requests` package has dependency on 0.16 and `take` imported from that directory uses this 0.16 package (according to regular resolution algorithm).

**Comment by klis87** [comment]
@Andarist Ahhh sry for this, I updated it locally, I just gave you a reference to it so you could see the whole codebase, officially I support only 0.16. Do you want me to prepare a 1.0 branch so you could clone it to reproduce it locally?

**Comment by restrry** [comment]
if you update package, it should work. the problem right now that saga cannot recognize that you yielded effect and returns object as is. https://github.com/redux-saga/redux-saga/blob/master/packages/core/src/internal/proc.js#L144-L149

**Comment by Andarist** [comment]
Yeah, shape of the effect object has changed **slightly** but it has obviously major implication for our runtime code. You had to import `take` from 0.16. Please try to update to v1 everywhere in that monorepo, if it doesnt help you - then please prepare a branch I can take look at.

**Comment by klis87** [comment]
@restrry @Andarist probably this was my mistake, sry for that. I assumed that I needed to update only dep in my examples, because `redux-saga` is peer dep of `redux-saga-requests`. However, I had `redux-saga` as dev dependency pinned which I didn't think about.

All in all, the only change I need to make is `delay` import, other stuff work! Thanks and apologies again for taking your time
