### ISSUE TITLE
Icons! 

### ISSUE THREAD

**Issue by DoctorHowser** [redux-saga/redux-saga#1705]
Hello!

This is a general question regarding the logo icons. The vs-code material icon library discussed (and added!) redux icons into their set, but were resistant to the redux-saga icon. I think it's due to the rectangular shape, which makes it difficult.

https://github.com/PKief/vscode-material-icon-theme/issues/255#issuecomment-391993647 

Are there any plans for a square icon option? I'm no graphic artist, but it would be really cool to get the icon set to also advertise redux-saga!

**Comment by Andarist** [comment]
Im not graphic designer either, if anyone makes a square version of our logo then I'll merge it in.

**Comment by szb512** [comment]
Here's the square version of our logo.
![68747470733a2f2f72656475782d736167612e6a732e6f72672f6c6f676f2f303830302f52656475782d536167612d4c6f676f2d4c616e6473636170652e706e67](https://user-images.githubusercontent.com/47613831/53291040-0bccff80-377b-11e9-8771-7b59a0f75e39.png)

**Comment by szb512** [comment]
851 x 852 px.
