### ISSUE TITLE
workers pool

### ISSUE THREAD

**Issue by atlanteh** [redux-saga/redux-saga#1709]
### Description
I want to allow my clients to upload 30-40 images at once. However my server doesn't allow it, so I need to make multiple requests, however I don't want all requests issued at once. I want the first 5 photos to upload simultaneously, and once a photo finishes, upload another one, until all photos are uploaded.
Is it possible? How can I do it?

**Comment by Andarist** [comment]
https://redux-saga.js.org/docs/advanced/Channels.html#using-channels-to-communicate-between-sagas

**Comment by atlanteh** [comment]
Thanks for your supper quick response
I'm trying it in a bit different way and it doesn't work for me:
```
function* uploadAdminPhotos(action) {
    try {
        const photos = action.payload.slice();
        const photosChannel = yield call(channel, buffers.expanding());
        const workers = [];
        for (var i = 0; i < 5; i++) {
            const worker = yield fork(uploadSinglePhoto, photosChannel);
            workers.push(worker);
        }

        for (let i = 0; i < photos.length; i++) {
            yield put(photosChannel, photos[i]);
        }
        photosChannel.close();
        yield put({type: 'ALL_PHOTOS_UPLOAD_SUCCESS!!'});
        
}
```
In this case ALL_PHOTOS_UPLOAD_SUCCESS is dispatched before all. How do I wait for channel to finish all given work, close it and only then dispatch 'ALL_PHOTOS_UPLOAD_SUCCESS'?

**Comment by Andarist** [comment]
```js
function* uploadSinglePhoto(photosChannel) {
    while (true) {
        if (photosChannel.isEmpty()) {
            return;
        }
        const photo = yield take(photosChannel);
        yield call(uploadSinglePhoto);
    }
}

function* uploadAdminPhotos(action) {
    const photos = action.payload.slice();
    const buffer = buffers.expanding();
    const photosChannel = channel(buffer);
    photosChannel.isEmpty = buffer.isEmpty;

    for (let i = 0; i < photos.length; i++) {
        yield put(photosChannel, photos[i]);
    }

    const workers = yield all(Array.from({ length: 5 }).map(() => fork(uploadSinglePhoto, photosChannel)));

    yield join(workers)
    photosChannel.close();
    yield put({type: 'ALL_PHOTOS_UPLOAD_SUCCESS!!'});
}
```

**Comment by atlanteh** [comment]
WOW awesome!
Thanks a lot

**Comment by atlanteh** [comment]
Just one small fixup:
`yield join(workers)`
should be:
`yield join(...workers)`

**Comment by Andarist** [comment]
Oh, I've used v1 semantics and it should be `yield join(workers)`, but in v0.16 you are right - `yield join(...workers)`

**Comment by atlanteh** [comment]
I just read the releases notes, and I don't see this change in there. Can you please add it so if anyone upgrades, they will know to update this one as well? (Also, I think you should have an "Upgrade" link from v0.16 to v1 that will summarize all the upgrade processes needed. WDYT?

**Comment by Andarist** [comment]
It's mentioned [here](https://github.com/redux-saga/redux-saga/releases/tag/v1.0.0-beta.2) in Changed section.

> Also, I think you should have an "Upgrade" link from v0.16 to v1 that will summarize all the upgrade processes needed. WDYT?

Sure - I'll prepare a single list before releasing final v1.
