### ISSUE TITLE
Execute parrelel redux actions [help wanted]

### ISSUE THREAD

**Issue by Phenixer** [redux-saga/redux-saga#1711]
Hi everyone, I have a question how to design something and I can't get my head around it.

I have those Redux actions **LOAD_REQUEST** and **LOAD_SUCCESS** / **LOAD_FAILURE**.
A saga generator function is listening to takeEvery(LOAD_REQUEST, generator_func) and loads the requested entity and returns it in the payload of **LOAD_SUCCESS**.

If I want to execute those actions and wait for the result, I wrote:
```
function* load_entity(entity) {
  yield put(LOAD_REQUEST(entity));
  const result_payload = yield take([LOAD_SUCCESS],[LOAD_FAILURE]);
  return result_payload;
}
```

My problem is that if I try to execute this code async i.e
```
const all_results = yield all(
  requested_entities.map(entity => call(load_entity(entity)))
);
```
The first load that finishes and puts the **LOAD_SUCCESS** action will make all those calls finish prematurely. I need a way to only **take** the right requests.

I have ideas how to do this...:
1) Do a while loop and `take` until the related entity payload is returned.
2) Put a `channel` inside the LOAD_REQUEST payload and put a result in that channel.
3) Don't put redux actions and instead call the saga's generator function...

What would be the best way to implement this kind of setup? Is there one? Am I missing something?
Thanks

**Comment by shinima** [comment]
You can use take with a predicate. For example, say the entity has a unique `id` property, you can do ...
```javascript
const result_payload = yield take(action => 
  action.type === 'LOAD_SUCCESS' && action.entity.id === 1000
)
```

... this take effect will be resolved only on LOAD_SUCCESS action with the specified id.

**Comment by restrry** [comment]
seems the comment solves the problem
