### ISSUE TITLE
No need to fork inside all in examples

### ISSUE THREAD

**Issue by ktrungha** [redux-saga/redux-saga#1719]
### Description
In this example https://github.com/redux-saga/redux-saga/blame/master/examples/real-world/sagas/index.js and many examples, I see the use of `fork ` inside `all`.

If I understand things correctly. This is not necessary as using `all` is not blocking on each individual effect already. The example should be `yield all([
    call(watchNavigate),
    call(watchLoadUserPage),
    call(watchLoadRepoPage),
    call(watchLoadMoreStarred),
    call(watchLoadMoreStargazers)
  ])` instead of `yield all([
    fork(watchNavigate),
    fork(watchLoadUserPage),
    fork(watchLoadRepoPage),
    fork(watchLoadMoreStarred),
    fork(watchLoadMoreStargazers)
  ])`

**Comment by Andarist** [comment]
Yes - you are right that forks are probably not technically needed there, but by using forks you are allowing yielding generator to reach its end (because task descriptors will be returned to the yielding generator and it will proceed to next line, while with calls it would block indefinitely - waiting till all watchers end)

**Comment by ktrungha** [comment]
> Yes - you are right that forks are probably not technically needed there, but by using forks you are allowing yielding generator to reach its end (because task descriptors will be returned to the yielding generator and it will proceed to next line, while with calls it would block indefinitely - waiting till all watchers end)

Now this just comes to my mind: Taken into account what you said, it seems there is no need to call `all` we can just call `fork` like `fork(watchNavigate); fork(watchLoadUserPage); fork(watchLoadRepoPage); fork(watchLoadMoreStarred); fork(watchLoadMoreStargazers)`. No need to wrap these with `all` outside

**Comment by ktrungha** [comment]
If you say so I think it's clearer to use an option that is the minimal. It makes understanding the example easier. I have a coworker who is very confused about setting up root saga with many ways of writing it.
