### ISSUE TITLE
Integration testing, how to mock a generator.

### ISSUE THREAD

**Issue by MatteoGioioso** [redux-saga/redux-saga#1720]
I am making integration testing and I have the need to mock a saga generator to return a controlled value.
```
import {workerSaga} from "../somewhere";

workerSaga = jest.fn(); //or any fake implementation
```
However this is not working. Is there a way to achieve this?

Thanks

**Comment by Andarist** [comment]
The issue is not related to redux-saga, ESM imports are static & read-only. I think you just have to use `jest.mock` appropriately.

**Comment by MatteoGioioso** [comment]
Edited my question

**Comment by restrry** [comment]
if you test `sagaA` that calls `sagaB`, approach and links to libraries are described in https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/Testing.md
With this approach, you don't need to mock anything at all.

If you do want to mock something, you can use jest's functionality  `jest.mock('../path/to/module', () => ({ sagaB: .... }))`, if I'm not mistaken.
