### ISSUE TITLE
takeEvery and takeLatest. Why? When to use? Use simultaneously?

### ISSUE THREAD

**Issue by wzup** [redux-saga/redux-saga#1722]
From here
https://redux-saga.js.org/docs/basics/UsingSagaHelpers.html#

Use cases for both? We can read that they exists. We can understand `takeEvery` but why did you introduce `takeLatest`?

**Comment by restrry** [comment]
> Unlike takeEvery, takeLatest allows only one fetchData task to run at any moment. And it will be the latest started task. If a previous task is still running when another fetchData task is started, the previous task will be automatically cancelled.

the difference is described here

**Comment by whitehorse622** [comment]
If you use the "takeEvery", it allows multiple fetchData instances to be started concurrently. At a given moment, we can start a new fetchData task while there are still one or more previous fetchData tasks which have not yet terminated.
but If you use the "takeLatest", it allows only one fetchData task to run at any moment. If a previous task is still running when another fetchData task is started, and the previous task will be automatically cancelled.
