### ISSUE TITLE
Unclear 'runSaga' options and subscribe field documentation

### ISSUE THREAD

**Issue by MatteoGioioso** [redux-saga/redux-saga#1724]
The documentation about `runSaga` `options` is very unclear.

First:
`options: Object` : https://redux-saga.js.org/docs/api/index.html#runsagaoptions-saga-args

the function signature is `runSaga(options, saga, ...args)`
But then where the rest of the fields belong to? `dispatch(output)`, `getState()` ?
Do they still belong to the `options`?

Second: `subscribe` field:
```
subscribe(callback): Function - A function which accepts a callback and returns an unsubscribe function

callback(input): Function - callback(provided by runSaga) used to subscribe to input events. subscribe must support registering multiple subscriptions.
input: any - argument passed by subscribe to callback (see Notes below)
```

I am having a really hard time to understand what this means, I suppose the function should look something like this.

```
subscribe: (callback) => {
    //Subscribe function
    callback(input);

    //Unsubscribe function
    return () => { //some code };
},
```
How can I use it to resolve a `take` effects for example?. 
Would be nice to have some examples also. In the testing section `Testing the full Saga`, there are some nice example, but without using the `subscribe` field

**Comment by Andarist** [comment]
I've updated docs around this API -  https://github.com/redux-saga/redux-saga/commit/466c5a4f8e941fb0f30a6e6dfb40310883876856 . Keep in mind that it was adjusted to v1, which we are going to release soon. 

Is this now clearer or do you feel something still could get improved?

**Comment by MatteoGioioso** [comment]
@Andarist Thank you, it is certainly more clear now.

**Comment by arnaudambro** [comment]
Hi @Andarist, I am trying my best to build a code corresponding to what you say but I struggle quite hard...
Let's take a basic example :

I created a `recordSaga` function, its target is to record what actions have been dispatched during the saga.

```js
export const recordSaga = async (saga, initialAction, state) => {
  const dispatched = [];

  const done = await runSaga(
    {
      dispatch: action => dispatched.push(action),
      getState: () => state,
    },
    saga,
    initialAction,
  ).done;

  return {
    dispatched,
    done,
  };
};

```

so let's say my saga is this one
```js
export function* mySaga() {
  const needToSave = yield select(needToSaveDocument);
  if (needToSave) {
    yield put(saveDocument());
    yield take(SAVE_DOCUMENT_SUCCESS);
  }
  yield put(doSomethingElse())
}
```

I want to write two tests, which I expect to be the following
```js
describe('mySaga', async () => {
  it('test 1: no need to save', async () => {    
    const state = { needToSave: false }
    const { dispatched } = await recordSaga(randomSaga, {}, state);
    expect(dispatched).toEqual([
      doSomethingElse()
    ])
  })
  it('test 2: need to save', async () => {
    const state = { needToSave: true }
    const { dispatched } = await recordSaga(randomSaga, {}, state);
    expect(dispatched).toEqual([
      saveDocument(),
      doSomethingElse()
    ])
  })
})
```

However, for the test 2 where there is a `take` in between, and of course `jest` (or its girlfriend `jasmine`) is yelling at me: `Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`

That's where your solution takes place, but I don't know how to implement it. I tried that:

```js
import { runSaga, stdChannel } from 'redux-saga';
import EventEmitter from  'events';

export const recordSaga = async (saga, initialAction, state) => {
  const dispatched = [];

  const emitter = new EventEmitter()
  const channel = stdChannel()
  emitter.on("action", channel.put)

  const done = await runSaga(
    {
      dispatch: action => {
        emitter.on("action", action)
        dispatched.push(action)
      },
      getState: () => state,
      channel
    },
    saga,
    initialAction,
  ).done;

  return {
    dispatched,
    done,
  };
};
```

but now I have `TypeError: (0 , _reduxSaga.stdChannel) is not a function`, and anyway I feel I am not doing right...
could you help please ?

**Comment by arnaudambro** [comment]
Actually I am thinking: as the `SAVE_DOCUMENT_SUCCESS` action type is triggerd by a click, I also need to mock that click, right ? How can I do this within `runSaga`
