### ISSUE TITLE
'takeLeading' doesn't exist in 'redux-saga/effects'

### ISSUE THREAD

**Issue by SergeyVolynkin** [redux-saga/redux-saga#1725]
### Steps to reproduce
Use "redux-saga": "0.16.2"
#### Description of the bug/issue
'takeLeading' is [in the documentation](https://github.com/redux-saga/redux-saga/tree/master/docs/api#takeleadingpattern-saga-args), but doesn't exist
#### Steps to reproduce the bug/issue

1. import { takeLeading } from "redux-saga/effects";
2. recieve 'takeLeading' is not exported from 'redux-saga/effects' error

### The Expected results
'takeLeading' is working as described in the docs
### Environment information

- redux-saga version: 0.16.2
- create-react-app: latest (v2)

**Comment by Andarist** [comment]
It's available in v1 - which is at RC stage right now.

**Comment by priyankanethi** [comment]
I still face this. Is it already available now?
