### ISSUE TITLE
Redux Saga take(pattern), I get only maximum of 4 parameters.

### ISSUE THREAD

**Issue by FantasticSWT** [redux-saga/redux-saga#1727]
![image](https://user-images.githubusercontent.com/38369131/51122937-f4365900-1855-11e9-9c8a-89bcbf19decf.png)

I managed to get the value for only the first four parameters(from promotionImageRef to Quantity), the fifth parameter onward return me 'undefined'.

I had tested where I rearrange the sequence of the parameter. I managed to get only first four parameters only.

Is this a bug or it's normal behavior?

**Comment by shinima** [comment]
This seems a problem with the dispatched action, check the code that dispatch actions and inspect the action rather than using destruct assignment.

```javascript
const action = yield take(ADD_PROMOTION_REQUESTED)
console.log(action)
```

**Comment by FantasticSWT** [comment]
![image](https://user-images.githubusercontent.com/38369131/51161531-bbd26180-18cd-11e9-9e7b-fa9dadcc23dd.png)

This is the result of console.log(action).

Before that, i got value, but when it triggered by take(pattern), the value become undefined.

**Comment by Andarist** [comment]
The most likely answer is thar you don't pass enough arguments to your `addPromotionRequested`. `redux-saga` doesnt do anything special with your actions - it just resolves `take`s and let you deal with received action.

**Comment by FantasticSWT** [comment]
It seems like dispatched actions have limited number of arguments. As reference to: https://github.com/vuejs/vuex/issues/366

My temporary work around is to lessen the parameters by creating objects.
