### ISSUE TITLE
How to use yield in map in React Native?

### ISSUE THREAD

**Issue by joseph-d-p** [redux-saga/redux-saga#1729]
I've tried the suggestions in #1090, however it doesn't work for my need.
My goal is to execute the forked function inside `map`.

Here's what I've tried:

```
  function* doSomethingWithItem(item) {}

  yield all(items.map(item => {
    // ... some item checking
    return fork(doSomethingWithItem, item);
  }));
```
Tried also using `yield fork()` but got an error "yield is a reserved word..."
`doSomethingWithItem()` isn't called.

Appreciate the help.

**Comment by Andarist** [comment]
This should work - please provide a repro case on codesandbox.io so we can help you.

**Comment by joseph-d-p** [comment]
@Andarist, thanks. works on react but not on react native.

[![Edit React Native](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jn24j7o4y9)

**Comment by joseph-d-p** [comment]
@Andarist, my bad. After adding a `catch`, the error was unrelated. Thanks!
