### ISSUE TITLE
How to get axios error response INTO the redux saga catch method

### ISSUE THREAD

**Issue by peshoicov** [redux-saga/redux-saga#1730]
The code with axios is:

```
export const createBlaBla = (payload) => {
  return axios.post('/some-url', payload)
    .then(response => response)
    .catch(err => err);
}
```

And then I'm using this with redux-saga like this:

```
function* createBlaBlaFlow(action) {
  try {
    const response = yield call(createBlaBla, action.payload);
    if (response) {
      yield put({
        type: CREATE_BLA_BLA_SUCCESS
      });
    }
  } catch (err) {
    // I need the error data here ..
    yield put({
      type: CREATE_BLA_BLA_FAILURE,
      payload: 'failed to create bla-bla'
    });
  }
}
```

In case of some error on the backend - like invalid data send to the backend - it returns a 400 response with some useful data:

```
{
  "code":"ERR-1000",
  "message":"Validation failed because ..."
  "method":"POST",
  "errorDetails":"..."
}
```

But I don't receive this useful data in the catch statement inside the saga. I can console.log() the data in the axios catch statement, also I can get it inside the try statement in the saga, but it never arrives in the catch.

Probably I need to do something else? ... Or the server shouldn't return 400 response in this case?

**Comment by shinima** [comment]
You are catching errors in your `createBlaBla`, so the error does not bubble to the generator. Just replace you `createBlaBla` as follows:

```javascript
export const createBlaBla = (payload) => {
  return axios.post('/some-url', payload)
}
```

**Comment by peshoicov** [comment]
Thanks, that really helped :)

**Comment by rajat-np** [comment]
You can destructure response and error object that will be returned promise and can check if err is not null.
```javascript
const { response, err } = yield call(createBlaBla, action.payload);
```

**Comment by BenNeighbour** [comment]
@rajat-np I am trying that and it isn't working for me? Could I have some clarity on this please?

**Comment by ridwanswattup** [comment]
> @rajat-np I am trying that and it isn't working for me? Could I have some clarity on this please?

Same here, got any resolve @BenNeighbour

**Comment by neurosnap** [comment]
Hi, could you please share some code so we can try to help? Thanks!

**Comment by ridwanswattup** [comment]
@neurosnap It is just like the one above only I still can't get the error

`const postUtil = (url, data, config) => axios.post(url, data, config);`

**Comment by peshoicov** [comment]
A few thoughts that might help or lead to some solution(s):

1. What is the response from the backend? 400?
2. If you add then and catch to the axios call - do you get the error there?

**Comment by ridwanswattup** [comment]
> A few thoughts that might help or lead to some solution(s):
> 
> 1. What is the response from the backend? 400?
> 2. If you add then and catch to the axios call - do you get the error there?

It's a 409 error that return an error object that can be seen on postman or Browser network 
```

**Comment by peshoicov** [comment]
Hm ... I did a quick search and it could be that the axios library has problems with 409 http status code.

So - as some things to try:

1. Can you try the code from this [comment](https://github.com/axios/axios/issues/3490#issuecomment-773747693)? It uses dummy URL that always return 409, which is very handy :)
2. Can you try to use `fetch()` instead of axios?

**Comment by ridwanswattup** [comment]
> Author

Yes, I thought the same and I even found the comment referenced but validateStatus wasn't working. But now that I use fetch and I get the expected error. I visited validateStatus again but this time using properly from an instance I can now get the proper error. This is weird with axios though because by default it is meant for call validateStatus itself with the status code check I have just supplied.  Thanks @peshoicov @neurosnap

**Comment by peshoicov** [comment]
@ridwanswattup - do you mind share a bit of code?
Sorry but I couldn't understand you :)

**Comment by ridwanswattup** [comment]
> @ridwanswattup - do you mind share a bit of code? Sorry but I couldn't understand you :)

proper way to use validateStatus

```
const instance = axios.create({
   validateStatus:  (status) => {

// this is weird because according to my check this ought to be done by axios by default
     return status >= 200 && status < 300;
    }
  });
 instance.post(url, data, config);
 // this works

```
It was used directly in the comment you referred me to which doesn't work when I tried earlier when I also found the comment section
```
axios('http://httpstat.us/409', { validateStatus() { return true } })
  .then(res => console.log('then:', JSON.stringify(res.data, null, 4)))
  .catch(err => console.log('error', err.response.data));

// Output:
// then: {
//     "code": 409,
//     "description": "Conflict"
// }
```


Bottom line: It is all sorted now, this can be close again. Thanks. 🙂
