### ISSUE TITLE
Effects do not catch the actions when `fork` inside `all` after `1.0.0-beta.3`

### ISSUE THREAD

**Issue by purepennons** [redux-saga/redux-saga#1733]
#### Description of the bug/issue
See the example. I run a saga by `fork` inside `all`. The effects (only tried `takeEvery` and `takeLatest`) do not catch the action and run the sagas after `1.0.0-beta.3` version.

#### Steps to reproduce the bug/issue
1.  click inc/dec button to increment/decrement the state.

#### Example
All examples are same except the `redux-saga` version.

- `1.0.0-rc.0`: [https://codesandbox.io/s/nwlmw448np](https://codesandbox.io/s/nwlmw448np)
- `1.0.0-beta.3`: [https://codesandbox.io/s/1454688p7l](https://codesandbox.io/s/1454688p7l)
- `1.0.0-beta.2 `: [https://codesandbox.io/s/yx2m3no4z](https://codesandbox.io/s/yx2m3no4z)
- `1.0.0-beta.1`: [https://codesandbox.io/s/31zx718r16](https://codesandbox.io/s/31zx718r16)
- `0.16.2`: [https://codesandbox.io/s/yvmqz37j31](https://codesandbox.io/s/yvmqz37j31)

### Actual results
- Buttons of `1.0.0-rc.0` and `1.0.0-beta.3` have no responses. 
- `1.0.0-beta.2 ` and `0.16.2` take all actions and increment/decrement the state correctly.

### The Expected results
All version should take all actions and increment/decrement the state correctly.

### Environment information

- redux-sage `1.0.0-rc.0`, `1.0.0-beta.3`, `1.0.0-beta.2 `, `1.0.0-beta.1`, `0.16.2`

**Comment by shinima** [comment]
After changing...

```javascript
export function* process() {
  yield all([
    fork(takeEvery, Types.DO_INC, increment),
    fork(takeEvery, Types.DO_DEC, decrement)
  ]);
}
```

to

```javascript
export function* process() {
  yield all([
    takeEvery(Types.DO_INC, increment),
    takeEvery(Types.DO_DEC, decrement)
  ]);
}
```

... then everything works as expected.

Because `takeEvery` is already a wrapper of `fork`, `fork(takeEvery, ...)` is unneccessary. Just use `takeEvery(...)` 😸

**Comment by purepennons** [comment]
I know, but that is a breaking change.

**Comment by Andarist** [comment]
Yes, we know - that's why it is listed in https://github.com/redux-saga/redux-saga/releases/tag/v1.0.0-beta.3 "Fixed" section.

**Comment by GuillaumeCisco** [comment]
I have the exact same issue from version >= 1.0.0.
I use this pattern for loading my sagas:
```javascript
import {fork} from 'redux-saga/effects';
import my_saga from './my_saga';

export default function* root() {
    yield fork(my_saga);
}
```
The `my_saga.js` file looks like:
```javascript
import {takeLatest} from 'redux-saga/effects';

function* myGenerator(request) {
    // do stuff, yield stuff
}

export default function* () {
    yield all([
        takeLatest(MY_ACTION_TYPE, myGenerator),
    ]);
}
```

The `myGenerator` function is never called :/

**Comment by Andarist** [comment]
could you prepare a codesandbox.io showcasing the problem?

**Comment by GuillaumeCisco** [comment]
@Andarist Simply using the beginner tutorial.
Following: https://redux-saga.js.org/docs/introduction/BeginnerTutorial.html
github repo : https://github.com/redux-saga/redux-saga-beginner-tutorial
Clone it, go inside the `sagas` branch, modify the `package.json` for having `"redux-saga": "1.0.1"`.
Then, `yarn install`, `yarn run`.

Go to the webpage, it does not work on my computer.

yarn : 1.13.0
node : v11.10.0

If someone can confirm it.

codesandbox is here: https://codesandbox.io/s/nwj4jrm1n0
Thank you,

**Comment by shinima** [comment]
@GuillaumeCisco You should use `yield all([...])` instead of `yield [...]` in the root saga, and this is why the code is not working in 1.0.1.  

Actually, if you view the logs in 0.16.x, there is a deprecation warning which tells you to update the code.

**Comment by GuillaumeCisco** [comment]
@shinima I took the code from the official tutorial as you can see.
I succeeded to make the tutorial work by adding the `yield all([...])` and replacing the `yield call(delay, 1000)` by `yield delay(1000)` with an `import { all, put, takeEvery, delay } from "redux-saga/effects";`

The tutorial is not up to date.

Unfortunately, it changed nothing in my own project, effects are not called...

**Comment by GuillaumeCisco** [comment]
Ok I just found out my issue.
I use `redux-sagas-injector` https://github.com/GuillaumeCisco/redux-sagas-injector.
I'm the maintainer of this lib.
Issue is `redux-sagas-injector` use a old version of `redux-saga` and is in charge to create the `sagaMiddleware`: `const sagaMiddleware = createSagaMiddleware();`

When mixing old and new versions of `redux-sagas` with dependencies, effects are not called.
I'm thinking how to make the code compatible for both versions without breaking changes...

**Comment by Andarist** [comment]
From what I see the @GuillaumeCisco has handled the problem on his side (inside redux-saga-injector) and originally reported issue actually works as expected - therefore Im closing this issue as resolved, feel free to open new issues though if needed

**Comment by GuillaumeCisco** [comment]
Thanks @Andarist.
However, I think the beginner tutorial should be updated ;)

**Comment by Andarist** [comment]
I think it's already updated - if you can please check it in the git repository, not on the website. I'm planning to redeploy docs website after doing a patch release which I'm sort of preparing right now.
