### ISSUE TITLE
runSaga example link is a bad link in v1 document, can you please provide an example please

### ISSUE THREAD

**Issue by sOm2y** [redux-saga/redux-saga#1738]
I was trying to test a whole saga with runSaga, and doesn't work, then checking the v1 documentation, and found that the runSaga example link is a bad link - https://github.com/redux-saga/redux-saga/blob/v1.0.0/docs/UsingRunSaga.md

Can you please provide a good example of how to use runSaga with chanel and dispatch, or fix the link please? Still not sure how to config chanel in runSaga...

**Comment by Andarist** [comment]
Thanks for the report - I've fixed this link, this section is available under https://github.com/redux-saga/redux-saga/blob/v1.0.0/docs/advanced/UsingRunSaga.md
