### ISSUE TITLE
TS typedefs: take(array) does not work with heterogenous redux-action actions

### ISSUE THREAD

**Issue by slorber** [redux-saga/redux-saga#1740]
Was on 0.16 and tried the 1.0.0, and I'm getting this TS error when trying to mix redux-action actions with distinct payload types:

![image](https://user-images.githubusercontent.com/749374/51612828-87405480-1f22-11e9-9b5e-bc31b9245092.png)

It works fine if the payload has same type:

![image](https://user-images.githubusercontent.com/749374/51612902-a6d77d00-1f22-11e9-8940-12407ca6eeaf.png)

It used to work fine on 0.16

Didn't try but afaik a workaround is using toString:

![image](https://user-images.githubusercontent.com/749374/51612948-c40c4b80-1f22-11e9-9da4-fe2f1717607a.png)

Not sure how to fix this, but  `StringableActionCreator<any>` does work in `ActionSubPattern`

**Comment by restrry** [comment]
@aikoven would you mind to have look?

**Comment by aikoven** [comment]
Try to specify the type parameter:

```ts
takeLatest<Action1 | Action2>([...], ...)
```

Don't know yet how we could make it inferred. We need to have
```ts
[StringableActionCreator<Action1>, StringableActionCreator<Action2>]
``` 
inferred to 
```ts
ActionPattern<Action1 | Action2>
```

**Comment by Andarist** [comment]
Could we maybe use conditional types and do some fancy stuff like:
```js
type Unpack<T extends ActionTypes> = T extends Array<StringableActionCreator<infer A>> ? ActionPattern<A> : T
```
Note that actual type names are probably different, I'm not using saga together with TS and I dont have correct type named remembered by heart.

**Comment by slorber** [comment]
Actually in my app I have an array with like 10 actions if I could avoid
maintaining that list it would be better :p

**Comment by aikoven** [comment]
Pretty busy right now, but this issue is on my list.

**Comment by aikoven** [comment]
@slorber Could you please check if https://github.com/redux-saga/redux-saga/pull/1769 fixes your case?

**Comment by slorber** [comment]
Hi @aikoven and thanks for your update

migrating to 1.0 is not in my priority anymore and don't have much time, so let's consider it's working and if I don't reopen later or someone else, then it's fine ;)

**Comment by mattvperry** [comment]
@aikoven Looks like #1769 only fixed this issue for `takeLatest` and other similar helpers. What about simply `take`?

**Comment by aikoven** [comment]
@mattvperry You're right. Here's the fix: https://github.com/redux-saga/redux-saga/pull/1795
