### ISSUE TITLE
Strange typings and docs information about eventChanel

### ISSUE THREAD

**Issue by retyui** [redux-saga/redux-saga#1746]
### Description
I really don't understand.

What the `matcher` argument do in docs and typings?

[`eventChannel(subscribe, [buffer], [matcher])`](https://github.com/redux-saga/redux-saga/tree/master/docs/api#eventchannelsubscribe-buffer-matcher)

Because in code this argument not supported 
https://github.com/redux-saga/redux-saga/blob/2aecdb310db8760ddd2c2513bf1cce7174c289d9/packages/core/src/internal/channel.js#L110-L113

**Comment by shinima** [comment]
This should be a mistake in doc. Would you like make a PR to fix this?

**Comment by retyui** [comment]
And [types](https://unpkg.com/@redux-saga/core@1.0.0/index.d.ts)
```js
export function eventChannel<T>(subscribe: Subscribe<T>, buffer?: Buffer<T>, matcher?: Predicate<T>): EventChannel<T>
```

**Comment by retyui** [comment]
@shinima No. I wouldn't
