### ISSUE TITLE
Failing saga test in 1.0.0

### ISSUE THREAD

**Issue by rybon** [redux-saga/redux-saga#1749]
# Fixed, see comments below
### Steps to reproduce
I've prepared 2 CodeSandboxes. One with a passing 0.16.2 test and an identical one with just a version bump to 1.0.0 where the same test fails.

#### Description of the bug/issue
Forked task in which the effect returns a `Promise.reject` value no longer returns error data.

#### Steps to reproduce the bug/issue
Run the CodeSandboxes.

#### Example
0.16.2 https://codesandbox.io/s/ym9218w601
1.0.0    https://codesandbox.io/s/kx10q3vwzo

### Actual results
Failing test. Only the redux-saga version number has changed.

### The Expected results
Passing test after upgrading from 0.16.2 to 1.0.0

### Environment information
Passing: 0.16.2
Failing: 1.0.0

**Comment by Andarist** [comment]
As to the showcased problem - instead of using `.done` getter you have to call `.toPromise()` method.

**Comment by rybon** [comment]
Yes, that fixed it, thanks! I've updated the 1.0.0 CodeSandbox to reflect this.

I'll continue to investigate the browser freezing problem. Perhaps the same cure does the trick there as well.

**Comment by rybon** [comment]
The browser freezing problem is still there. I'll close this ticket and open another one.
