### ISSUE TITLE
Browser freezes in 1.0.0

### ISSUE THREAD

**Issue by rybon** [redux-saga/redux-saga#1750]
### Steps to reproduce
Needs to be investigated.

#### Description of the bug/issue
After upgrading from 0.16.2 to 1.0.0 and running the app, the browser (Chrome) gets stuck in what seems like a `while` loop and ceases to respond. Other than changes to the imports of `delay` from `redux-saga` to `redux-saga/effects` and `task.done` to `task.toPromise()`, no code changes were done. Reverting back to 0.16.2 resolves the issue.

#### Steps to reproduce the bug/issue
Needs to be investigated.

#### Example
Needs to be created.

### Actual results
The browser becomes unresponsive.

### The Expected results
A responsive browser.

### Environment information
1.0.0

**Comment by rybon** [comment]
OK I will, thanks for the tip!

**Comment by rybon** [comment]
https://github.com/redux-saga/redux-saga/blob/master/packages/core/src/internal/proc.js#L165

This function gets called in what seems like an infinite loop. Both arguments are `undefined`. This is what caused the freeze. Any ideas?

**Comment by rybon** [comment]
OK I found the issue.

When you call `Promise.resolve()` or `Promise.reject()` the resulting value is `undefined`. This triggers the infinite loop. Changing the value to anything else resolves the issue.

**Comment by shinima** [comment]
Thanks for report, I've confirmed this issue and I'll create a PR to fix it.
