### ISSUE TITLE
Redux Saga Monitor Log release plans

### ISSUE THREAD

**Issue by mike1808** [redux-saga/redux-saga#1752]
Hi!

Can you say, do you plan to release your saga monitor which logs sagas into the console to npm? 

I published the package under `redux-saga-monitor-log`, however, I didn't setup rollup or any other build system and I assume that files from `node_modules` will be compiled on the client which is a bad assumption.

So, if you are going to release it, I can transfer ownership of the package to you, if no, I'll setup a build system.

**Comment by szb512** [comment]
Well, it would be a big improvement to redux-saga, but there would be one issue with npm, and the issue is that it might not recognize the sagas, and result in errors, which would make users edit npm so it accepts sagas.

**Comment by restrry** [comment]
@Andarist let's release it. related discussion https://github.com/redux-saga/redux-saga/pull/1718#discussion_r250313519

**Comment by ashirley** [comment]
This is done now isn't it?

https://www.npmjs.com/package/@redux-saga/simple-saga-monitor

**Comment by Andarist** [comment]
Right, thanks for pointing out.
