### ISSUE TITLE
How to use takeLatest with putResolve?

### ISSUE THREAD

**Issue by idandagan1** [redux-saga/redux-saga#1763]
Hi,
`takeLatest` don't work for me.
I'm using `redux-saga` with [`feathers-redux`](https://github.com/feathers-plus/feathers-redux).

Example of my code:
```
// saga.js
import { putResolve, takeLatest } from 'redux-saga/effects';
import { services } from './services';

function* handleFindUsers(action) {
    const query = { /* some query */ };
    const usersAction = services.users.find({ query });

    yield putResolve(usersAction);
}

function* mySaga() {    
    yield takeLatest('FIND_USERS', handleFindUsers);
}
```
**services.users.find** will result with an action like this:
```
{
   type: 'SERVICES_USERS_FIND',
   payload: { promise: <promise> }
};
```

package.json:
```
dependencies: {
    ....
    "redux-saga": "^1.0.0",
    "feathers-redux": "^3.0.0",
    ...
}
```

But the `takeLatest` won't cancel the last result.
What i'm doing wrong?
Thanks.

p.s
love this project :)

**Comment by GabrielFerrarini** [comment]
When you call

```
const action = services.users.find({ query });
```

you probably want to use a call effect.

```
const user = yield call(services.users.find, { query });
```

Also, make sure you are not crating a variable with the same name of your argument. Your receiving action and declaring another action inside your function.

**Comment by idandagan1** [comment]
Thanks @GabrielFerrarini but this is only an example (there is no variable issue in the real code).

In addition, I've also tried using a call effect. 
but getting the same result.

**Comment by Andarist** [comment]
`putResolve` will wait for actions which result in a promise being returned from dispatch, not for promises embedded within action object

**Comment by idandagan1** [comment]
@Andarist can you provide an example for usage of `putResolve`?

**Comment by Andarist** [comment]
https://github.com/redux-saga/redux-saga/blob/50efcd293414d6c73db93d09faebaadb47b06387/packages/core/__tests__/interpreter/put.js#L67-L72

**Comment by mihaisavezi** [comment]
This as an example in the README or in the APIReference would be killer.
