### ISSUE TITLE
Fumbling with takeLatest/takeLeading HelperWorkerParameters type

### ISSUE THREAD

**Issue by flushentitypacket** [redux-saga/redux-saga#1766]
I often inject dependencies into the saga like this:

```
const dependencies = {foo: 'bar'}
takeLatest(ACTION_TYPE, workerFn, dependencies)
```

But `dependencies` type errors with:

> Argument of type '[{ foo: string; }]' is not assignable to parameter of type 'never'

I dug into it and found that the ACTION_TYPE type is passed into HelperWorkerParameters like:

```
type HelperWorkerParameters<ActionType, Fn extends (...args: any[]) => any> = Last<Parameters<Fn>> extends ActionType
  ? AllButLast<Parameters<Fn>>
  : never
```

Which I'm having trouble understanding / make work. Does this mean that ActionType needs to be the last parameter in the additional arguments? That doesn't seem to make much sense to me--I'm a bit lost.

Thanks!

**Comment by flushentitypacket** [comment]
Also somewhat troubling is that I can't just escape-hatch it with

```
takeLatest(ACTION_TYPE, workerFn, dependencies as any)
```

Since it conflicts with the `never` type.

**Comment by flushentitypacket** [comment]
Ah, okay, I've found the issue.

```
type Dependencies = {foo: string}
const workerFn = (dependencies: Dependencies) => {}
takeLatest(ACTION_TYPE, workerFn, {foo: 'bar'})
```

Does NOT compile because `workerFn` does not include a second arg for the `action` being passed in.

```
const workerFn = (dependencies: Dependencies, action: ActionType) => {}
```

This works.

**Comment by flushentitypacket** [comment]
Add the Typescript error here in case it helps anyone searching for this problem:

Argument of type '[FooType]' is not assignable to parameter of type 'never'.

**Comment by Burize** [comment]
Nevertheless,  if I need a dependencies, but don't need an action in the workerFn(saga), then there is unused argument, that i must provide and type ...
