### ISSUE TITLE
saga logging breaks the app

### ISSUE THREAD

**Issue by stropho** [redux-saga/redux-saga#1776]
#### Description of the bug/issue
Development logging cant handle all values

#### Steps to reproduce the bug/issue
Run the following saga
```
const mySaga = function * (): Saga<void> {
	const data = Object.create(null)
	yield call(console.log, data)
}
```
or just
```String(Object.create(null))```
which is actually beeing evaluated in https://github.com/redux-saga/redux-saga/blob/65034cc8b08ab5a6ff1e7441f3062960615f368d/packages/core/src/internal/io.js#L146 

### Actual results
The logging  that should help the developers breaks the app.
Before this issue I thought that you can put just anything into `String()` or `Boolean()`. But that is not true.

### The Expected results
A working app should not break because of dev logs

### Thoughts toward the solution

1. Fix our app, so that redux-saga works with normal objects. It is the first thing that I did. However, it really took me a while to see where the problem emerged after upgrading to redux-saga@1 - very frustrating. Additionally `Object.create(null)` was sent via action in a library, redux middleware, that we use, so I couldnt actually remove it, just create a workaround for it. The irony is that the app works fine in production but fails in development because of a log that is not actually being logged
2. create a helper function , e.g. `tryString`, with a try-catch clause that would be used to convert values to string.

### Environment information

- redux-saga version 1.0.1

**Comment by shinima** [comment]
Thanks for reporting. In my option, I think we may simply avoid stringifying `args[0]`. Replacing the code to `instead of writing yield call(delay, ...) where delay from ...` should fix the issue. How you think?

**Comment by stropho** [comment]
Thx. Without `args[0]`, the warning still notifies how to (not) call delay effect. So it is totally fine by me.
