### ISSUE TITLE
cancel saga on one of two events from store

### ISSUE THREAD

**Issue by eyale** [redux-saga/redux-saga#1779]
Need to cancel saga depends on one of two events from redux.
```
export function* watcherDownloadSaga() {
  while (yield take(downloadRequest().type)) {

    const _downloadSaga = yield fork(downloadSaga);

    yield take(togglePauseDownload().type), 
    or       
   yield take(networkStatusChanged().type),
    ]);
    yield cancel(_downloadSaga);
  }
}
```

**Comment by jasonhendry** [comment]
I've used the race pattern in the [Sagas documentation](https://redux-saga.js.org/docs/advanced/RacingEffects.html) to good effect.

You should be able to adapt that to your example.

**Comment by shinima** [comment]
Take with an array of types should work.

```javascript
yield take([ togglePauseDownload().type, networkStatusChanged().type])
```

More detail can be found at [doc](https://redux-saga.js.org/docs/api/#takepattern).

**Comment by eyale** [comment]
Thank you @shinima and @jasonhendry both variants are working properly, now the problem with rn-fetch-blob.
