### ISSUE TITLE
[PROPOSAL]: `defer` effect (PR willing)

### ISSUE THREAD

**Issue by bradennapier** [redux-saga/redux-saga#1781]
So I just ran into a bit of a surprising situation, I do understand the reasoning for it but it leads to the consideration that a `defer` action may be required.

I had assumed `fork` and `spawn` actually defer so that I can do the following

```javascript
      console.log('LISTENING FOR NEXT');
      const { type, payload } = yield take(chan);
      console.log('PROCESS: ', type, payload);
       yield spawn(onClick, ...args);
...
```

and expect that `LISTENING FOR NEXT` would execute before `onClick` is even called.  This is not the case and actually appears only possible by forking a task and putting a mini delay in that forked task then calling it independently.  

I'm a little confused as I swear this is how it worked at some point but alas, I am probably crazy :).  I can imagine the idea is to call the `likely` async function and simply not wait for it to resolve - so since it calls the function immediately in this case we run into the issue and would need to put a small `await` call in the `onClick` (which is an async function).

> In my case, the `onClick` is also potentially calling the chan and the effect must be processed.

So I would suggest something more along the lines of having `spawnDeferred` and `forkDeferred` to accomplish this requirement.  The fork or spawned would be called on `nextTick` (which on web atm i believe would translate to `Promise.resolve().then(...)` although i havent kept up with things).

So in my case it roughly translates to:

```javascript
yield spawn(() => Promise.resolve().then(() => onClick(...args)));
```

which, of course, fixes my problem.  

```javascript
yield spawnDeferred(onClick, ...args)
```

just so much simpler and ofc has other benefits since the former would need to handle things differently if i wanted to make sure it was called as a saga and such.

---

I guess the saga version would just be something simple like the following without consideration for how saga currently handles stateful situations like this:

```javascript
let nextTickProm;

function* deferredExecute(fn, args) {
  if (!nextTickProm) {
    nextTickProm = Promise.resolve();
  }
  yield call(() => nextTickProm);
  nextTickProm = undefined;
  return yield call(fn, ...args);
}

function* spawnDeferred(fn, ...args) {
  return yield spawn(deferredExecute, fn, args);
}

function* forkDeferred(fn, ...args) {
  return yield fork(deferredExecute, fn, args);
}
```

> Note that this also has the minor optimization benefit that it does also require a new promise for every defer required since it will reuse the same promise for each tick.

**Comment by bradennapier** [comment]
I can also put a PR together to implement this if its agreed that it would be something we want to add.  Initially looking at this I am thinking of this as a rough idea:

```javascript
export function defer(deferredEffect, fnDescriptor, ...args) {
  if (process.env.NODE_ENV !== 'production') {
    check(deferredEffect, is.effect, 'defer(effect, fn, ...args): argument effect is not a redux-saga effect')
    check(deferredEffect, () => deferredEffect !== defer, 'defer(defer, ...): argument effect may not be defer')
    validateFnDescriptor('defer', fnDescriptor)
  }
  return deferredEffect(nextTickPromise, call(fnDescriptor, ...args))
}
```

* Would need to validate its a `fnDescriptor` effect
* Not 100% positive this is the right general api but it seems like a good idea

Idea would be to add a general `defer` effect

```javascript
yield defer(effect, fnDescriptor, ...args)
// -->
yield defer(fork, fnDescriptor, ...args)
yield defer(spawn, fnDescriptor, ...args)
// and potentially (but with more consideration) things like
yield defer(cancel, tasks)
// ...
```

Then `helpers` could be provided just to basically sugar that but potentially not required at that point.

**Comment by Andarist** [comment]
> (which on web atm i believe would translate to `Promise.resolve().then(...)` although i havent kept up with things).

This is a nice point of reference for this problem~:
https://github.com/jamiebuilds/tickedoff/blob/99129560b3b788188c575f907488a3922b17e604/index.js

As to your proposal - I'm not against adding things to the core, but as a rule of thumb I would like to add only things that makes sense and which cannot be implemented in userland OR which benefits greatly from being in the core.

Seems like the whole proposal is simply about executing things ASAP but not in the same stack trace and this seems like a simple saga composition. What would be the argument in your eyes behind implementing this in the library itself?

**Comment by bradennapier** [comment]
It’s not about ASAP it’s about ensuring that your take is captured before the forked code runs. 

In my case I was running into cases where it was missing some events since a fork was called which put again to be handled by the same loop, which ofc could be dangerous but in this case it was critical.  

I think in general there are many times one would do things where they’d want to make sure their main saga is reset and ready before actually calling the code.  

So it’s actually opposite, instead of wanting to run things ASAP it ensures your function continues after any request is made and that the action won’t occur until AFTER the event loop is then opened again.

**Comment by bradennapier** [comment]
@Andarist I would also point this out https://github.com/whatwg/html/issues/512 which is the upcoming `queueMicroTask` that implements this in browser nicely without the boilerplate.

**Comment by shinima** [comment]
> My reasoning for this being a core piece of the API is that the event loops in general can be a bit confusing and this calls it out to show actually what behavior with and without the `defer` can be expected ......

Actually in both cases the action `{ type: 'TWO' }` will NOT be ignored, @bradennapier you can check it in [this codesandbox](https://codesandbox.io/s/3yzrz7m86m?expanddevtools=1&fontsize=14).

---

From your implementation of `defer`, I guess that it is sufficient to add `yield Promise.resolve()` before what you want to defer. For example (following your examples)...

```javascript
function* sagaOne() { // --> 4
  // explicitly defer `put({ type: 'TWO' })`
  //   so we can make sure the action can be taken by parentSaga
  yield Promise.resolve()

  yield put({ // --> 5
    type: 'TWO',
  });
}

// other code omitted...
```

**Comment by bradennapier** [comment]
Well my simplification may simply be not capturing it correctly as the `yield` may make this work as desired although it still happens when not using yield in a similar case as shown with the console logging here when `fork` executes immediately so in my case highlighted via the `gist` and other cases where i likely ended up not using `yield` it absolutely ends up causing conflict.

https://codesandbox.io/s/xjp7nnr744?fontsize=14

**Comment by bradennapier** [comment]
I would also point out [this isnt the only time this has come up](https://github.com/redux-saga/redux-saga/issues/277).  I actually am positive I've seen quite a few issues all related to users not being aware of the execution flow that will occur based on the effects they use.  

Again, `defer` provides a documented method which makes this flow more clear to users and provides a simple tool to try when they run into weird race-conditions like these.

**Comment by bradennapier** [comment]
@shinima took a sec to put together this specific case where you end up potentially running into a potential issue.   I can outline more cases by digging into my other projects to find where these things came up and I am sure I could find more issues that highlight users having confusion around this topic if needed.

https://codesandbox.io/s/moq877oqx9

**Comment by neurosnap** [comment]
Thanks everyone for posting and suggesting a feature improvement.  Since it’s been years since the last post, I’m going to reluctantly close this issue.  If we still think this feature is important we should prioritize getting a working PR up for review.  Thanks!
