### ISSUE TITLE
npm fails to install redux-saga because it exits with error exit status 0

### ISSUE THREAD

**Issue by szb512** [redux-saga/redux-saga#1787]
Npm fails to install redux-saga because it exits with multiple errors and an error exit status 0, any hints?

**Comment by Andarist** [comment]
You would have to share some logs to get help

**Comment by szb512** [comment]
I am unable to get logs. All I know is that it exits with all errors.

**Comment by saboya** [comment]
There endless possibilities for an error, most of which have nothing to do with redux-saga.

**Comment by szb512** [comment]
The issue is with npm.

**Comment by szb512** [comment]
I will edit npm later.

**Comment by szb512** [comment]
This is actually becoming a problem.
