### ISSUE TITLE
How setContext is supposed to work

### ISSUE THREAD

**Issue by insonifi** [redux-saga/redux-saga#1798]
At first, I was fascinated by ability to store some saga related data, e.g. I need to keep web socket subscription. After tinkering with context for couple of day, I must say, I give up. I don't get how it is supposed to work.

- Should context be persistent between saga executions?
- Can forked saga change context of parent?
- What is use case for context in general?

Here is a use case I tried to implement:
https://codesandbox.io/s/p3043owkz7

Please help! :)

**Comment by Andarist** [comment]
> * Should context be persistent between saga executions?

Yes - if you dont change it.

> * Can forked saga change context of parent?

No. Only in mutable manner.

> * What is use case for context in general?

Storing top level stuff, often not simple data that can be stored in state and having it accessible within whole saga subtree (thanks to context). It helps to avoid passing same arguments everywhere.

**Comment by shinima** [comment]
There are some points that may help you understand context:

* Every task has its own context. When a new task is created, a new context object is created for this task.
* Task can only change its own context by yielding `setContext` effects.
* When saga middleware gets a `getContext('foo')`, it will first check whether `'foo'` in the **task** context. If it is there, then returns it; else it will check whether `'foo'` is in the context of the **task's parent**. If not, then check **parent's parent's** context... The check will be executed until to the root task.  If the root task's context does not has `'foo'`, then `getContext('foo')` return `undefined`.

The last point is simply implemented by using [`Object.create()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create), which is alwayed referred as [prototype chain](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain). You can find the source code where we call `Object.create` in redux-saga [here](https://github.com/redux-saga/redux-saga/blob/14aaf609b3d5dfdd57e64303599b10b014a1e958/packages/core/src/internal/newTask.js#L17).

**Comment by shinima** [comment]
I'm cloing this issue. If you have any further questions, just ask.

**Comment by abettadapur** [comment]
I think it would be really helpful to add a doc section on this, or beef up the `get/setContext` api reference, because these gotchas aren't exactly clear
