### ISSUE TITLE
unable to make API call using map of items with yield all [ ]

### ISSUE THREAD

**Issue by NikhilDevop** [redux-saga/redux-saga#1800]
I have an array of items where I make API call for each item in array. I am using react native debugger for debugging ([https://github.com/jhen0409/react-native-debugger][1]), the problem is when I place debugger statement in the function where I make API call (i.e., inside callAPI function) the debugger doesn't stop there and is not even entering into callAPI function,

But when I remove the '[ ]' symbol in the yield call([ ]) the debugger stops in the callAPI function and an error " Objects are not valid as a React child ( found Error: Request failed with status code 400). If you meant to render a collection of children, use an array instead) "  is thrown. The following is the syntax with which I am facing problem.

    const callAPI = async ( client: ServiceRootClient, move: moveReq): Promise<any> => {

            debugger;

            const results = await client

                .forOne(singletons => singletons.find(singleton => 

                 singleton.$Name === "Item"))

                .forOperation(ops => ops.find(op => op.$Name === "Move"))

                .withParameters((params, parameterSet) => {

                    params.map(param => {

                        if (param.$Name === "Data") {

                            parameterSet.add(param, movement);

                        }

                    });

                })

                .execute();
        
        return results;
    };
    
  

     export function* applyItemMovements(action: itemManagement.Action) {

      try {
    
    	const result = yield all([

                    ItemMoveRequests.map(ItemMoveRequest=>

                        call(callAPI, action.metadata.client, moveReq);

                    )

                ]);

          } catch(error) {

                //print error

          }

    }

I am using '[ ]' inside yield all to make API calls for all array items so that if one API call fails that doesn't stop the other items in the array calling the API.

Also, I am not sure whether this is the way to make API call so that remaining items call API even if one item in array fails or should I do any modifications in the yield. How to make a call to  callAPI function? and can I also pass a label to each call of item ?

  [1]: https://github.com/jhen0409/react-native-debugger

**Comment by shinima** [comment]
What you need may be...

```javascript

export function* applyItemMovements(action) {
  try {
    // create an array of promises
    const promises = ItemMoveRequests.map(ItemMoveRequest => callAPI(action.metadata.client, moveReq))
    // pass `promises` to all
    const result = yield all(promises)
  } catch (error) {
    //print error
  }
}
```

---

> ...remaining items call API even if one item in array fails...

You can use `Promise#catch` to avoid errors in one API-call propogating to `all` effect.

```javascript
const promises = ItemMoveRequests.map(ItemMoveRequest => {
  const promise = callAPI(action.metadata.client, moveReq)
  return promise
    .then(result => ({ label: 'some label', ok: true, result })
    .catch(err => ({ label: 'xxx', ok: false, err })),
  )
})
const result = yield all(promises)
```

**Comment by NikhilDevop** [comment]
@shinima if I used yield call (callAPI, action.metadata.client, moveReq) how to handle then?

**Comment by shinima** [comment]
Yes, you can. Then the code will look like 
```javascript
yield all(
  ItemMoveRequests.map(moveReq =>
    call(callAPI, action.metadata.client, moveReq)
  )
)
```

Note that you don't need write the square brackets `[ ]` manually.

**Comment by NikhilDevop** [comment]
but [  https://stackoverflow.com/questions/54193476/how-to-use-yield-inside-map-for-react-native](url) says ) to wrap the map into [ ] that's what I am confused whether to use it or not .

**Comment by Andarist** [comment]
Using `[]` directly was supported in the past - it got deprecated long time ago and removed in v1

**Comment by NikhilDevop** [comment]
@shinima as you suggested the code using call 

```
yield all(
  ItemMoveRequests.map(moveReq =>
    call(callAPI, action.metadata.client, moveReq)
  )
)
```
in this how ( and where)  the errors can be handled( if any)  as even if one request fails remaining items will be able to make API request such.

**Comment by Andarist** [comment]
You'd have to implement this yourself, something like:
```
const allSettled = effects => all(effects.map(effect => fork(function* settle() {
    try {
        return { error: false, result: yield effect }
    } catch(err) {
        return { error: true, result: error }
    }
})))
```

**Comment by NikhilDevop** [comment]
Thanks for your answer @Andarist ...but what i was asking is if I can also use fork() in place of call in the following code : 
```
yield all(
  ItemMoveRequests.map(moveReq =>
    call(callAPI, action.metadata.client, moveReq)  // --> fork(callAPI, action.metadata.client, moveReq)
  )
)
```

The reason I am asking as call() is a blocking effect and if one item of the array calls the API then that call blocks the other items in the array to further call the API and I don't want that to happen. That's the reason I asked if fork() can be used instead of call().

**Comment by Shahriar-Shakil** [comment]
`
const response = yield all(
      selectedDaaks.map((item) => {
        var {id, dak_type} = item;
        return call(fetchDaakForward, {id, dak_type, ...payload});
      })
    );
`
I got response as array . I need to individual response item . if i loop over the response array the put method not working

**Comment by gadiGuesty** [comment]
> You'd have to implement this yourself, something like:
> 
> ```js
> const allSettled = effects => all(effects.map(effect => fork(function* settle() {
>     try {
>         return { error: false, result: yield effect }
>     } catch(err) {
>         return { error: true, result: error }
>     }
> })))
> ```

@Andarist shouldn't be `call` instead of `fork`?

**Comment by Andarist** [comment]
Yes, probably it should - with call it would block on those tasks.

**Comment by goodwin64** [comment]
Is there a plan to include the `allSettled` into the redux-saga API the way it's done in the `Promise` API?

**Comment by goodwin64** [comment]
Here's a workaround for promise-based array, not for array of generators:

```ts
const [a, b, c, d]: [
  PromiseSettledResult<A>,
  PromiseSettledResult<B>,
  PromiseSettledResult<C>,
  PromiseSettledResult<D>,
] = yield Promise.allSettled([
  Api.getA(paramsForA),
  Api.getB(paramsForB),
  Api.getC(paramsForC),
  Api.getD(paramsForD),
]);
```

But having a built-in `allSettled` effect is preferable imo.

**Comment by Andarist** [comment]
@goodwin64 I could accept a PR for a builtin `allSettled`
