### ISSUE TITLE
How to get data from response header?

### ISSUE THREAD

**Issue by daniel-pietryga** [redux-saga/redux-saga#1807]
### Description
Hi, 
I have some saga requests. In response I got header 'Last-Modified' with date of last modification, I need to store this data in reducer to add it to later requests to check if there are some modifications. But after fetch I receive a Promise object, and i can only resolve it by response.json() which return me just body data. Is there any method to receive in saga method, after call, also headers data to put it into redicer?

**Comment by shinima** [comment]
You can just call `response.headers.get(headerName)` to retrieve the header that you're interested in.

```javascript
function* saga() {
  const response = yield call(fetch, someUrl)
  const header = response.headers.get('Last-Modified')
  const body = yield call([response, response.json])
  yield put({
    type: 'save-body-with-header',
    header: header,
    body,
  })
}
```
