### ISSUE TITLE
Take latest with race

### ISSUE THREAD

**Issue by maciejsikora** [redux-saga/redux-saga#1808]
Hi,
I need to watch if one of **n** actions is called, I would say I need something like **takeLatestRace**, so I want to call the worker if one of provided actions is dispatched, but until worker is not finished I don't want to proceed with others. Lets say:

`yield takeLatestRace([action1, action2], handler)`

So if **action1** is sent then **action2** is skipped until worker is done. 
Was trying some race with takeLatest, but cannot have it working as I want.  How can I do smth like that? Tnx in advance.

**Comment by mchyb** [comment]
IMO there is no need for extending an already complex API. ;) You can achieve the described functionality using `actionChannel` with `buffers.sliding`  and [blocking](https://redux-saga.js.org/docs/api/#blocking--non-blocking) `call` effect.  I hope I understood you correctly.

```js
function*() {
  const channel = yield actionChannel(
    ['action1', 'action2'],
    buffers.sliding(1)
  );

  while (true) {
    const action = yield take(channel);

    yield call(actionHandler, action);
  }
};
```
