### ISSUE TITLE
Common fetch worker [proposal]

### ISSUE THREAD

**Issue by shapkarin** [redux-saga/redux-saga#1819]
Hello. After some time using redux-saga I found out that I repeat the same pattern to describe mostly any fetch worker. I'm not sure that it would be flexible and idiologically right to include that feature to the project. I want to know what author and community think about that.

Here is an example:

```es6
import { put, call, fork } from 'redux-saga/effects';

import { fetchSomeInfo } from './someApi';
import {
    loadSomeInfoStart,
    loadSomeInfoSucces,
    loadSomeInfoError
} from './actions';

function* fetch ({ action, method, start, succes, error }){
    try {
        yield put(start());
        const { data } = yield call(method, action);
        yield put(succes(data));
    } catch (err) {
        yield put(error(err));
    }
}

function* fetchWorkerExample (action){
    yield fork(fetch, {
        action,
        method: fetchSomeInfo,
        start: loadSomeInfoStart,
        succes: loadSomeInfoSucces,
        error: loadSomeInfoError
    });
}
```

**Comment by shapkarin** [comment]
https://www.npmjs.com/package/saga-fetch

**Comment by shapkarin** [comment]
https://www.npmjs.com/package/saga-fetch

**Comment by Andarist** [comment]
Hi! Sorry that I haven't found time before to answer. 

I believe this kind of abstraction is too project-specific and thus a shared helper in the codebase or an external library seems like the most appropriate place for it if you want to deduplicate this logic

**Comment by shapkarin** [comment]
OK
