### ISSUE TITLE
[...effects] has been deprecated in favor of all([...effects]), please update your code

### ISSUE THREAD

**Issue by lucasharada** [redux-saga/redux-saga#1826]
I've been following #1090 to create a map with a yield operator and made it work. The issue now is that I've been getting the `[...effects] has been deprecated in favor of all([...effects]), please update your code` warning.

I checked several issues related to this warning and all comments, but couldn't manage to fix. The code that is triggering the warning is `const resources = yield all(lists.map(el => call(getResourcesFromList, el)));`, where `getResourcesFromList` is generator function. I commented all the lines from `getResourcesFromList`, but to ensure the problem was on the `all` call.

**Comment by saransh-malik** [comment]
@lucasharada Did you get a solution for this?

**Comment by lucasharada** [comment]
@saransh-malik Actually, I kept the same code, but the warning is gone.
