### ISSUE TITLE
Saga call is taking extremely long 

### ISSUE THREAD

**Issue by ThinkSalat** [redux-saga/redux-saga#1829]
I have an api call in my sagas like this:

    console.time('saga call')
    const response = yield call(api.route, accessToken, args, moreArgs) 
    console.timeEnd('saga call')
and surround it I have a console.time and console.timeEnd

I also have console.times surrounding the api.route call like so

    export const route = (accessToken, args, moreArgs) => {
      console.time('api call');
      let res =  fetch(fetchParams (not included here) );
      console.timeEnd('api call')
      return res
    };

The api.route call is taking ~3ms

The yield call(..) is taking 3000-11000ms

How can I debug this? I'm logging any actions sent to the saga middleware and nothing is running after the initial call. I'd like to find out how I can break into the call function and see what's taking so long.

BTW, I'm on version 0.14.7 if that helps. Upgrading to the latest version hasn't really helped. At first, the calls take ~1 second, but quickly go back up to 3-5 seconds.

**Comment by zhaoyingdu** [comment]
isn't fetch a promise? and your saga is waiting for your fetch promise to resolve?
try to console.log(res) before the return res call, see if it prints a function or the response object

**Comment by ThinkSalat** [comment]
> isn't fetch a promise? and your saga is waiting for your fetch promise to resolve?
> try to console.log(res) before the return res call, see if it prints a function or the response object

Yeah the res is a promise. That's how all our apis return.

**Comment by zhaoyingdu** [comment]
``` javascript
let res=  fetch(fetchParams (not included here) ).then(response=>{
   console.timeEnd('api call') //this is the actual time when you get response from your fetch() call 
   return response
}
```

**Comment by ThinkSalat** [comment]
Thanks! I'll give that a look. As an update, firing off the api call was taking only 6ms, but I put a console.timeEnd in the `.then` statement and it ended up being the culprit!

**Comment by ThinkSalat** [comment]
I figured it out. For some reason, the latency was being caused by React Native Debugger. When I turned off React Native Debugger the time went down to about 2-3 seconds. Before, it was taking 20 seconds or so to update.
