### ISSUE TITLE
npm ERR! Unexpected end of JSON input while parsing near

### ISSUE THREAD

**Issue by biplabdatta** [redux-saga/redux-saga#1839]
### Steps to reproduce
Trying to install redux-saga using " npm install --save redux-saga"
#### Description of the bug/issue
getting error while tryiing to install redux-saga
#### Steps to reproduce the bug/issue
My npm veriosn - 6.4.1
node version - v10.15.3
"react": "^16.8.4"

#### Example
PLease find the error log file in below url
https://github.com/biplabdatta/burgerapp/blob/master/2019-04-30T02_57_52_950Z-debug.log

**Comment by zhaoyingdu** [comment]
try npm cache clean and try again see if the error still persist?

**Comment by shinima** [comment]
Has a try with `npm cache clean --force`?   This problem seems to be unrelated with redux-saga.
