### ISSUE TITLE
Race condition between multiple sagas listening to same action

### ISSUE THREAD

**Issue by whitfier** [redux-saga/redux-saga#1841]
### Description
I have 2 sagas listening to the same action using `takeLatest`. When that action is dispatched, I expect both sagas to be run concurrently. Both sagas write to the same variable in Redux, causing a race condition (I know this is bad - I have removed the race condition, but I am trying to understand it better). I expect that the saga who finishes last will have their value persisted in Redux.

I have a CodeSandbox to demonstrate this scenario https://codesandbox.io/s/ywjlkown5v. This is using redux-saga 0.16.0.

In the demo, when I have
```
const saga = function*() {
  yield takeLatest("ADD_MESSAGE", appendSaga);
  yield takeLatest("ADD_MESSAGE", noopSaga);
};
```
the appendSaga "wins" by finishing last, and I see "foofoofoo" after clicking the button a few times. Then, when I change it to
```
const saga = function*() {
  yield takeLatest("ADD_MESSAGE", noopSaga);
  yield takeLatest("ADD_MESSAGE", appendSaga);
};
```
the appendSaga still "wins" and I see "foofoofoo".

What's interesting is when I upgrade redux-saga to 1.0.2, the behavior changes. Here is the same sandbox with 1.0.2 https://codesandbox.io/s/moon9kw43x

Now the order of my `takeLatest` calls matters. When I have
```
const saga = function*() {
  yield takeLatest("ADD_MESSAGE", appendSaga);
  yield takeLatest("ADD_MESSAGE", noopSaga);
};
```
the noopSaga "wins" by finishing last, and I see "" after clicking the button a few times. And when I change it to
```
const saga = function*() {
  yield takeLatest("ADD_MESSAGE", noopSaga);
  yield takeLatest("ADD_MESSAGE", appendSaga);
};
```
the appendSaga "wins" and I see "foofoofoo".

Why did this behavior change in 1.0? Is this expected? I searched the release notes but failed to find the relevant change.

**Comment by amr** [comment]
If I understand correctly, your problem can be rephrased in that the sagas used to run in parallel in 0.16 but in 1.0 they will run in sequence? If so, as a newcomer to redux-saga I think the new behavior makes a lot more sense, and if you want your sagas to execute in parallel then wrap them in [all()](https://redux-saga.js.org/docs/api/#alleffects---parallel-effects).

Hope this helps and I just didn't completely miss the point :)

**Comment by Andarist** [comment]
This is side-effect of this change:
> internal stdChannel got reworked to be a singleton object (it is wrapped multicastChannel's instance'), also it is an exported API to support new runSaga's signature - this should also result in being a small perf boost

Previously when we had 1 stdChannel per saga our scheduler was "released" (semaphore was decremented) after each put on such channel and in this particular situation it lead to a flush of the queued actions because it managed to go to 0.

The same thing happens in v1 (releasing, flushing etc) but we release only after "full pass" - after an action has a chance to reach each existing task, so in this particular situation - there is only a single release in comparison to 2 releases of our internal semaphore in previous versions of the saga.
