### ISSUE TITLE
runSaga.toPromise never resolves when having takeLatest in the saga

### ISSUE THREAD

**Issue by ickata** [redux-saga/redux-saga#1845]
#### Description of the bug/issue

Having a `takeLatest` yielded in the saga, and running the saga via `runSaga` and converting to a promise, promise never resolves:

```js
function* takeSaga() {
   
}

function* saga() {
   yield takeLatest('foo', takeSaga);
}

runSaga({
   dispatch: () => null,
   getState: () => {},
}, saga).toPromise() // this never resolves!!!
```

#### Steps to reproduce the bug/issue

Just run the code above, or better check example below:

#### Example
https://codepen.io/anon/pen/QRWGEP?editors=0011

### Actual results

The returned promise never resolves.

### The Expected results

The returned promise should resolve at the end of the root saga, after forking takeLatest, and w/o waiting for takeLatest to execute.

### Environment information
- redux-saga version: 1.0.2
- babel / typescript setup:
```
		"babel-loader": "^7.1.1",
		"babel-plugin-transform-class-properties": "^6.9.1",
		"babel-plugin-transform-es2015-classes": "^6.24.1",
		"babel-plugin-transform-es2015-modules-commonjs": "^6.26.0",
		"babel-plugin-transform-object-rest-spread": "^6.8.0",
		"babel-plugin-webpack-alias": "^2.1.2",
		"babel-preset-react": "^6.24.1",
		"babel-register": "^6.24.1",
```

**Comment by zhaoyingdu** [comment]
Forked child is attached to the parent task.  Perhaps `yield spawn` a wrapper function explicitly should not block the root for completion   

Quote from saga doc, [redux-saga's fork model](https://redux-saga.js.org/docs/advanced/ForkModel.html)
> **Attached forks (using fork)**
>Attached forks remain attached to their parent by the following rules
>**Completion**
>A Saga terminates only after
>It terminates its own body of instructions
>All attached forks are themselves terminated

**Comment by ickata** [comment]
Hey there,

`spawn` works like a charm. Thanks for that, I'm pretty new in sagas, should have known that.

Closing.
