### ISSUE TITLE
My mac is lagging when i import TakeEvery module from ‘redux-saga/effects’

### ISSUE THREAD

**Issue by ChenYCL** [redux-saga/redux-saga#1857]
### Description
IDE is webstorm 2019.1，maybe it's IDE‘s problem ,😄

**Comment by hilkeheremans** [comment]
Yes, it might be. The latest RC for 2019.1.3 has a fixed issue relating to `redux-saga`, try that.

See also https://confluence.jetbrains.com/display/WI/WebStorm+191.7479.11+Release+Notes

**Comment by ChenYCL** [comment]
Yes, not lagging now after update the version.
