### ISSUE TITLE
Breaking change to yield map (without all)

### ISSUE THREAD

**Issue by psiservices-rcocks** [redux-saga/redux-saga#1861]
Hi,

We have discovered what appears to be an undocumented breaking change between 0.16.2 and 1.0.0.

Example code : https://gist.github.com/psiservices-rcocks/7c8c2f540aa1b3744f2ac1e36efa681f

Comparison of outputs: https://gist.github.com/psiservices-rcocks/5e1a8c0c1692e42d26d94c97b10804bf

The above executes differently in 0.16.2 and 1.0.2. (Taking note to fix the delay import between the versions)

In 0.16.2, code such as `yield items.map(x => fork(fn, x))` would execute in the saga, but in 1.0.2 they do not.

I can understand why, the map maps to an array of effects and yields this instead of an effect, but arrays of effects used to be processed but they no longer are without calling the `all` effect.

Was this an intentional breaking change? There is mention of breaking changes related to fork, but this appears to be different and also affects `call`.

**Comment by Andarist** [comment]
This is listed as breaking change in this bullet point:
> removed some deprecated APIs - takeEvery, takeLatest, throttle from the redux-saga entry point (they are and were importable from redux-saga/effects), takem, put.sync and **executing array of effects, there is explicit API for this for already some time - all effect**

**Comment by psiservices-rcocks** [comment]
Thank you for your prompt response pointing out my error, I hadn't realised this was a previously deprecated API and should have read the notes more carefully.

**Comment by Andarist** [comment]
Hm, that's slightly weird - it got deprecated in [v0.15.0](https://github.com/redux-saga/redux-saga/releases/tag/v0.15.0 ) and it had a deprecation warning right from the start:
https://github.com/redux-saga/redux-saga/blob/f29fdc5d7f508512169f52bebeb983ec017fa25d/src/internal/proc.js#L151
