### ISSUE TITLE
Is it necessary to register all ragas in root ?

### ISSUE THREAD

**Issue by TNChalise** [redux-saga/redux-saga#1862]
I know its a rookie question, but unable to find the right way of doing it.

lets say I have two containers ``login.container.js`` and  ``profile.container.js``.  And two seperate sagas for each containers ``login.saga.js`` and ``profile.saga.js``. 

So, I forked all sagas in root saga as:
```
function* rootSaga() {
    yield all([
        fork(LoginSagas),
        fork(ProfileSagas)
    ]);
} 
```

When I dispatch events from, lets say profile.container.js, the actions being dispatched to both sagas. 

<img width="529" alt="Screen Shot 2019-06-02 at 10 49 42 am" src="https://user-images.githubusercontent.com/4486063/58755303-2c4be900-8524-11e9-98dc-bb679696f325.png">

From this screen shot, I can clearly see that, the action PROFILE_UPDATE being dispatched from profile.container.js is caught into both two sagas and share the both profile and login states. 

The way I am registering dispacher actions in my container is something like:
```
const mapStateToProps = state => {
    return {
        isLoading: state.profile.isLoading
    }
};

const mapDispatchToProps = (dispatch, state) => {
    return {
        actions: {
            profile: bindActionCreators(profileActions, dispatch)
        }
    }
};

export default connect(mapStateToProps, mapDispatchToProps)(ProfileContainer);
```
Even though I unregister both sagas from rootSaga.js, the action is passed through both sagas. 
Is this expected behaviour or I am doing something wrong ?

**login.action.js**

- LOGIN, LOGIN_SUCCESS, LOGIN_FAILURE
switch to these actions only.

**profile.action.js**
 - UPDATE_PROFILE, UPDATE_PROFILE_SUCCESS, UPDATE_PROFILE_FAILURE
switch case to these actions only.

And help will be appreciated. 

Thanks in advance.

**Comment by Andarist** [comment]
Well - it's the same case as with reducers. Actions are being dispatched to "all" reducers (technically there is only a single reducer though), and all reducers have the opportunity to update state based on ANY action. Same with sagas. If you want to prevent that you'd have to introduce some scoping mechanisms.

**Comment by TNChalise** [comment]
@Andarist Thanks for clarifying. If this is the expected behaviour, then its okay. I am confused as all sagas are listening to actions to happen and modify state; then I am observing all actions that will happen in my application. Will this slow down application performance ?

**Comment by Andarist** [comment]
It shouldnt slow down much, unless you dispatch really many actions per second

**Comment by TNChalise** [comment]
Thanks alot.
