### ISSUE TITLE
`npm install` isn't working; possibly something to do with yarn or lerna

### ISSUE THREAD

**Issue by clintonblackmore** [redux-saga/redux-saga#1864]
### Summary

In trying to build the samples as per the instructions, the process errors out in the `npm install` step. The error message makes me wonder if it has something to do with yarn or lerna.

### Steps to reproduce

I've tried this with two versions of `npm` using `nvm`; latest (12.4.0) and 8.12.0.

The [instructions for running the sample programs](https://redux-saga.js.org/#building-examples-from-sources) say
```
   Building examples from sources

   $ git clone https://github.com/redux-saga/redux-saga.git
   $ cd redux-saga
   $ npm install
   $ npm test (edited) 
```

When I do the `npm install` step, I get an error message. [installation_output.txt](https://github.com/redux-saga/redux-saga/files/3254466/installation_output.txt)
Here is the full log: [2019-06-04T20_47_40_940Z-debug.log.zip](https://github.com/redux-saga/redux-saga/files/3254472/2019-06-04T20_47_40_940Z-debug.log.zip)

#### Description of the bug/issue

The key error seems to be:

```
> undefined postinstall /Users/fepc-f110/Projects/Learning/ReduxSaga/redux-saga
> lerna run --parallel --scope redux-saga --scope @redux-saga/* build

lerna notice cli v3.14.1
lerna info filter [ 'redux-saga', '@redux-saga/*' ]
lerna info Executing command in 8 packages: "yarn run build"
lerna ERR! yarn run build exited 2 in '@redux-saga/core'
lerna ERR! yarn run build exited 2 in '@redux-saga/core'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! undefined postinstall: `lerna run --parallel --scope redux-saga --scope @redux-saga/* build`
npm ERR! Exit status 2
```

### Actual results

Building the samples fails.

### The Expected results

Building the samples should succeed.

### Environment information

I'm afraid I'm fairly new to the node world. The logs above were generated using node-v12.4.0. I think my environment is fairly clean.

I asked for a list of globally installed modules and got:

➜ npm list -g --depth 0
/Users/fepc-f110/.config/nvm/12.4.0/lib
└── npm@6.9.0

**Comment by Andarist** [comment]
Instead of running `npm install` you should run `yarn`. I've published correct instructions in the docs right now.

**Comment by clintonblackmore** [comment]
Excellent. That works nicely.
