### ISSUE TITLE
Error: fork: argument fn is undefined or null

### ISSUE THREAD

**Issue by sahlouls** [redux-saga/redux-saga#1867]
**Current Behavior**
When running test with `Jest`, despite all tests are successful, I still have a console error 

```
 console.error node_modules/@redux-saga/core/dist/chunk-774a4f38.js:104
      Error: fork: argument fn is undefined or null
          at check (/home/dsdsd/repos/ggg-gui/node_modules/@redux-saga/core/dist/chunk-774a4f38.js:26:11)
          at validateFnDescriptor (/home/dsdsd/repos/ggg-gui/node_modules/@redux-saga/core/dist/chunk-774a4f38.js:446:3)
          at fork (/home/dsdsd/repos/ggg-gui/node_modules/@redux-saga/core/dist/chunk-774a4f38.js:546:5)
```

my root saga
```
export default function* rootSaga(): SagaIterator {
  yield all([
    fork(mySaga1),
    fork(mySaga2),
    fork(mySaga3),
  ]);
}
```

The issue appear only when I added the `mySaga3`.

All is working perfectly, just this console error. 

Any idea where this error is coming from ? how to fix it ?

**Comment by Andarist** [comment]
Either `mySaga3` is undefined/null or `mySaga3` uses a fork in its implementation with undefined/null argument

**Comment by sahlouls** [comment]
- `mySaga3` does not use any fork
- mySaga3 is well defined

The only workaround I found yet is to import the store where I run sagas.

**Comment by Andarist** [comment]
Without seeing (and running) your exact code I can't advise much more.

**Comment by sahlouls** [comment]
Solved my self, need to import the saga under test

**Comment by onepiece998** [comment]
> SagaIterator

can you show the sample code, i am facing the same issue but I am unable to understand "need to import the saga under test"
this sentence
