### ISSUE TITLE
`yield call` will not proceed if calling generator with a fork that contains takeLatest

### ISSUE THREAD

**Issue by rhysbrettbowen** [redux-saga/redux-saga#1874]
### Steps to reproduce

https://codesandbox.io/s/basic-redux-saga-n4qb4?fontsize=14

click first button - second console.log will not run
click second button, it will

### Actual results

"gets here" in console

### The Expected results

"gets here" and "not here" in console

**Comment by Andarist** [comment]
That's expected (according to the uses forking model - https://redux-saga.js.org/docs/advanced/ForkModel.html ). A task won't return until all attached tasks end.
