### ISSUE TITLE
I am trying to make yield call method  inside a for loop . I am want to catch an error (network error : Type error inside) inside a try catch block . But I couldn't succeed and I am not able to manage to catch the error. Is there any way to solve this?

### ISSUE THREAD

**Issue by anoopileaf** [redux-saga/redux-saga#1876]
### Description
Please provide some context about the problem and some code examples if relevant.
The best way to provide an example is repository or use [Code Sandbox](https://codesandbox.io/)(there is a [prepared template](https://codesandbox.io/s/0q9yzno0zv?module=%2Fsrc%2Fsagas%2Findex.js) for Code Sandbox)

**Comment by anoopileaf** [comment]
` for (let index = 0; index < action.data.length; index++) {
            const item = action.data[index];
            const newAddress = action.address || item.asssetAdress;
                const response = yield call(Api, ApiConstants.MAINTENANCE_SAVE, item.mainteinenceData, 'POST', action.token);
                if (response.result === "success") {
                    const id = response.maintenanceTaskID;
                    yield put(saveHistoryAction.saveHistory(newAddress,item.mainteinenceData,item.imagesData,item.riskRegisterData,action.completeArray,action.inspectionAsset));
                    yield call(imagesSave, id, item.imagesData, action.token);
                    if(item.locationData){
                        yield call( updateLocation , item.locationData, id, action.token);
                    }
                    if ((item.id && item.id !== '') || item.id === 0) {
                        yield put(storeOfflineAction.removeSingleOffline(item.id));
                    }
                }else{
                    Alert.alert("Issue In Submitting");
                }
                yield put(loginActions.disableLoader());
                yield call(navigationActions.navigateToSection, 'Sections');
        }`

**Comment by Andarist** [comment]
Please provide a **well-formatted** issue with a link to the codesandbox which has your problem reproduced.
