### ISSUE TITLE
Please provide an unminified version of the browser ESM build

### ISSUE THREAD

**Issue by zero298** [redux-saga/redux-saga#1878]
### Description

I'm very appreciative of the ES-browsers build from #1716 however, do you think that you could provide an unminified version as well?  I see that you provide both minified and unminified version of the UMD bundle on [unpkg](https://unpkg.com/redux-saga@1.0.3/dist/):

- `redux-saga.umd.js`
- `redux-saga.umd.min.js`

but only the minified version of the ES browsers build for core and effects:

- `redux-saga-core.esmodules-browsers.js`
- `redux-saga-effects.esmodules-browsers.js`

For my use case, I just have a static server serving `node_modules` and letting the browser's ESM implementation do all the work.  This is working well for other libraries that provide unminified versions of the ES module like [Vue](https://unpkg.com/vue@2.6.10/dist/) (`vue.esm.browser.js`) but debugging is currently for redux-saga is currently difficult.

**Comment by Andarist** [comment]
Released in 1.0.4
