### ISSUE TITLE
saga monitor reports @@redux-saga/TERMINATE without any exceptions being thrown

### ISSUE THREAD

**Issue by kimgysen** [redux-saga/redux-saga#1881]
I applied the saga monitor, and seen in my logs that a terminate action has been invoked: 

```
const watchEffectEnd = (effectId, res) => {
    console.log('watch effect id', effectId);
    console.log('watch effect', res);
};

const sagaMiddleware = createSagaMiddleware({
    sagaMonitor: {
        rootSagaStarted: (id, e) => {
            console.log('event rootSaga started', id);
        },
        effectCancelled: () => {
            console.log('cancelled');
        },
        effectRejected: (e) => {
            console.log('rejected', e);
        },
        effectResolved: watchEffectEnd,
        effectTriggered: (event) => {
            console.log('*** effect tiggered ***', event);
        }
    }
});

```

> watch effect @@redux-saga/TERMINATE

What is troublesome is that I don't have a clue why this error is thrown and I'm afraid that I won't get out of this one on my own.  
In my current local implementation I have added try / catch blocks in my root saga, as well as the watcher sagas. Neither the monitor, nor the try / catch blocks throw any error.  

I have added the question to StackOverflow here: **https://stackoverflow.com/questions/56828752/redux-saga-terminate-action-triggered-for-unknown-reason**
This SO post provides some more detail, and a link to the Github repo where I have uploaded my codebase.  

Thanks for help.

**Comment by Andarist** [comment]
Could u prepare a codesandbox which would showcase your problem?

**Comment by kimgysen** [comment]
Hello, unfortunately this will be difficult as I am dealing with a sort of specific issue related to my current setup that involves webpack compilation and server side rendering.  

Could you kindly download the following github repo and have a look there: https://github.com/kimgysen/zwoop-website  
The only thing required is to: 

```
npm install
npm run start:iso:dev 
```

This will automatically spin up everything required and auto-compile / refresh the browser on any code changes. It may just fail the first time because of a race condition that I need to look into, but it should work perfectly otherwise once it's up.  The code is pretty standard isomorphic setup.   
Please let me know if you have an issue, but I don't think you will have.  

When I load the page for the first time, the watcher saga is executed as expected.   
On subsequent requests (manual browser refresh), the saga is terminated (basically nothing happens).  
On the client it works as expected.

**Comment by Andarist** [comment]
This happens because you dispatch `END` - https://github.com/kimgysen/zwoop-website/blob/dea8cbc82d2082d2e4bbd9b2db90286f74e89723/src/server/redux/store.js#L48

I wouldn't be worried about this - this is just a special symbol which gets propagated through saga to know that it should end all its child and so on when you dispatch another special action (END).

**Comment by kimgysen** [comment]
We can close this issue. I didn't find the solution in the end but solved the problem in another way. Thanks for looking into it anyhow.
