### ISSUE TITLE
takeLatest$1 requires a saga parameter

### ISSUE THREAD

**Issue by hopewise** [redux-saga/redux-saga#1882]
I am trying to use `throttle` to prevent duplicate calls to REST service, how ever I get an error.

Here is my implementation:

```
export default function* syncMobileToken(action) {
  yield throttle(1000, 'SYNC_MOBILE_TOKEN', syncMobileTokenNow, [action])
}

function* syncMobileTokenNow(action) {
  yield put(NotificationsActions.syncMobileTokenLoading())
  try {
    const response = yield call(notificationsService.syncMobileToken, action.data)

    let data = response.ok ? response.data : null
    if (data) {
      yield put(NotificationsActions.syncMobileTokenSuccess(action.data))
    } else {
      yield put(
        NotificationsActions.syncMobileTokenFailure({
          status: response.status,
          error: response.data.error ? response.data.error : response.data.errors,
        })
      )
    }
  } catch (error) {
    console.log(`syncMobileToken error: ${error}`)
  }
}
```

I am using the same working function I used before using `throttle` but I just added renamed it to `syncMobileTokenNow`

I got this error:

```
takeLatest$1 requires a saga parameter
```

here is how I connect it:

```
const mapDispatchToProps = (dispatch) => ({
  fetchInitData: () => dispatch(StoreActions.fetchData()),
  syncMobileToken: (token) => dispatch(NotificationsActions.syncMobileToken({ token })),
})
```

any idea? what does that error mean?

**Comment by mean2me** [comment]
Sorry for my stupid question but... where did you call `takeLatest` ?

**Comment by hopewise** [comment]
I did not call `takeLatest `, I just used `throttle` 🤒

**Comment by Andarist** [comment]
This error has to come from some takeLatest invocation, check out your error stack.

**Comment by hopewise** [comment]
oh, its not stupid question, I've found that `syncMobileToken ` is already used with `takeLatest` in the Sagas index as:
```
export default function* root() {
  yield all([
    .
    .
    .
    takeLatest(NotificationsTypes.SYNC_MOBILE_TOKEN, NotificationsSaga.syncMobileToken),
    ])
 ```

now, I understand that I need to use throttle in there, as `root` generator function will boot all the effects.

but if I tried to as:
```
export default function* root() {
  yield all([
    .
    .
    .
    throttle(1000, NotificationsTypes.SYNC_MOBILE_TOKEN, NotificationsSaga.syncMobileToken),
    ])
 ```
and reverted `syncMobileToken` as it was before ( just generator function that has yields, call, put, no throttle)
I get this error:

    throttle requires a saga parameter

How would I solve this issue ?

**Comment by Andarist** [comment]
You'd really have to share your code (preferably on codesandbox). Looks good, so can't know what's wrong without having the issue reproduced.

**Comment by hopewise** [comment]
I have solved it! I just did:

    import { syncMobileToken } from './NotificationsSaga'
    .
    .
    throttle(1000, 'SYNC_MOBILE_TOKEN', syncMobileToken),
instead of

    throttle(1000, 'SYNC_MOBILE_TOKEN', NotificationsSaga.syncMobileToken),

and I changed the way I export the function, I removed `default` so it looks like:

    export function* syncMobileToken(action) {

and it worked! but why?

**Comment by mean2me** [comment]
@hopewise , I'd like to tell you why :)

Could you post a small working example reproducing your issue? I'd like to investigate too.

**Comment by hopewise** [comment]
this is a similar case: https://stackoverflow.com/questions/56043247/takelatest1-requires-a-saga-parameters with minimum code..

my repo is very big, and hard to extract things.. thanks

**Comment by Andarist** [comment]
@hopewise Please understand that we are trying to help you solve your problem and we do that in our spare time. How you can expect us to help you blindly (which takes WAY more time than when having repro case) when you don't want to take time to prepare a small working example of a problem?

**Comment by hopewise** [comment]
@Andarist I appreciate your support for sure, I tried to create a sample here: https://codesandbox.io/embed/modest-mountain-862bl , I put every thing, but I got stuck with boilerplate, I wish there is a ready boilerplate that users Saga so that I can use..

**Comment by Andarist** [comment]
You can fork one of those - https://codesandbox.io/search?refinementList%5Bnpm_dependencies.dependency%5D%5B0%5D=redux-saga&page=1&configure%5BhitsPerPage%5D=12

**Comment by hopewise** [comment]
Thanks will report it once I can reproduce it in sandbox
