### ISSUE TITLE
Argument of type '"USER_LOGIN_REQUEST"' is not assignable to parameter of type 'TakeableChannel<unknown>' in yeild takeLatest

### ISSUE THREAD

**Issue by nirajhi** [redux-saga/redux-saga#1883]
### Description
I am trying to write redux-saga for simple login application with typescript. When creating my watch function, 

```
export default function* watchUserAuthentication() {
     yield takeLatest(types.USER_LOGIN_REQUEST, authenticateUser);
}
```
I get the following typescript error _Argument of type '"USER_LOGIN_REQUEST"' is not assignable to parameter of type 'TakeableChannel<unknown>'.ts(2345)_
Is there any way to remove this error?

<img width="885" alt="Screen Shot 2019-07-05 at 5 45 25 PM" src="https://user-images.githubusercontent.com/2114194/60721123-b1278980-9f4c-11e9-9cce-5e8ab03e4307.png">

**Comment by Andarist** [comment]
Please share a repository with the issue reproduced.

**Comment by chenghw** [comment]
In the `authenticateUser` generator, you are currently declaring the action as `{ payload: ICredential }` without a `type`. If you declare the `type`, I think you will get rid of that error...so something like this...`{ type: typeof types.USER_LOGIN_REQUEST; payload: ICredential; }`

Side note and cool feature of `redux-saga` is that you can pass the actions creators to the `take` functions as long as the action creators have a `toString` method on them that return the type. (Here are the docs)[https://redux-saga.js.org/docs/api/#takepattern] Two libraries that do this for you are `redux-actions` and `typesafe-actions`.

This would allow you to stop importing the types and use only the action creators everywhere instead.

```typescript
export function* authenticateUser({ payload }: ReturnType<typeof loginRequest>) {
  ...
}

export default function* watchUserAuthentication() {
  yield takeLatest(loginRequest, authenticateUser);
}
```

**Comment by nirajhi** [comment]
Thank you @chenghw . You are right. I should have added the type parameter. Also, I will look into the feature, you mentioned.

**Comment by rufatZZ** [comment]
@chenghw Thank you man. :)

**Comment by jvvolkart** [comment]
@chenghw I added the type as a second parameter but now typescript shows an error that it is not being used, what do I do in this case?

**Comment by thelimarenan** [comment]
@chenghw, thank you!!!

**Comment by masonyeh** [comment]
@chenghw thank you man 👍

**Comment by JasonXiaoSpace** [comment]
so how to resolve it ? i can't understand it

**Comment by MaximPravenkiy** [comment]
@chenghw Thank you very much, dude!

**Comment by zhyd1997** [comment]
@chenghw thanks a lot!

**Comment by ch-hassansaeed** [comment]
instead of 

    export function* getListEventsByUserSaga(action: { payload: any; }) {
    ...
    //logic
    ...
    }

use this 

    export function* getListEventsByUserSaga(action: any) {
    ...
    //logic
    ...
    }

**it works for me**
