### ISSUE TITLE
Duplicating service calls in Saga on Mounting Component for Embedded pagelet

### ISSUE THREAD

**Issue by AnirbanHub** [redux-saga/redux-saga#1884]
### Steps to reproduce
We have a ComponentDidMount() which initializes fetchingInitialData function and the fetchInitialData function is called in the Sagas 
In Sagas , the function gets called like below :

export function* fetchItem2() {
  const correlationId = yield select(selectors.retrieveCorrelation);
  const Item2 = yield call(ItemAPI.fetchItem2, correlationId);
  yield put(saveItem2(Item2));
}

export function* fetchItem1() {
  const correlationId = yield select(selectors.retrieveCorrelation);
  const Item1 = yield call(ItemAPI.fetchItem1, correlationId);

  yield put(saveSystemItemCount(Item.systemItemCount));
  yield put(saveItem1(Item.miscellaneousItems));
  yield call(fetchItem3, Item.Item3);
}

export function* fetchInitialData() {
  try {
    yield all([
      call(fetchItems1),
      call(fetchItems2)
    ]);

    yield put(setPageStatus(PAGE_STATUS.MAIN));
  } catch (error) {
    yield put(setPageStatus(PAGE_STATUS.ERROR));
  }
}

export function* watchFetchItem2() {
  yield takeLatest(actionTypes.FETCH_ACTIVITY_DEFINITIONS, fetchItem2);
}

export function* watchFetchitem1() {
  yield takeLatest(actionTypes.FETCH_ACTIVITIES, fetchItem1);
}

export function* watchFetchInitialData() {
  yield takeLatest(actionTypes.FETCH_INITIAL_DATA, fetchInitialData);
}

export default function* root() {
  yield fork(watchFetchInitialData);
  yield fork(watchFetchItem2);
  yield fork(watchFetchItem1);
...
...
...
}

#### Description of the bug/issue
On doing a Console.log after the export function* the fetchItem1 and fetchItem2 calls are made twice after every reload(or navigating back to the pagelet without loging out of the app). As a consequence I am getting duplicate service calls being made which is visible in the Network tab of browser. These calls seem to be compounding 1x,2x,3x and so on everytime I navigate back to the pagelet.
This is happening for redux-saga version 1.0.2 as a dependency. In addition we have another shared repository in our application's package.json that also has redux-saga 1.0.2.  However on downgrading the version to 0.16.0 the issue disappears. I have been trying to find for similar issues on the web but did not come across something similar.

#### Steps to reproduce the bug/issue

My container looks like below 

class ItemContainer extends Component {
  /* istanbul ignore next */
  componentDidMount() {
    const { fetchInitialData } = this.props;

    fetchInitialData();
  }
render ()
.....
return (
<ItemPage
...... 
/>

const mapStateToProps = (state, _ownProps) => ({ // eslint-disable-line no-unused-vars
  ...
});

/* istanbul ignore next */
const mapDispatchToProps = dispatch => ({
  setPageStatus: (status) => { dispatch({ type: actionTypes.SET_PAGE_STATUS, status }); },
  fetchInitialData: (items) => { dispatch({ type: actionTypes.FETCH_INITIAL_DATA, items }); },
});

export default connect(mapStateToProps, mapDispatchToProps)(injectIntl(ItemContainer));

#### Example
To help us to identify a problem faster, please provide repository with an example or use [Code Sandbox](https://codesandbox.io/)
(there is a [prepared template](https://codesandbox.io/s/0q9yzno0zv?module=%2Fsrc%2Fsagas%2Findex.js) for Code Sandbox)

### Actual results
Multiplying service calls on page reload (or navigating back to the pagelet from another pagelet)
### The Expected results
Should be one service call everytime navigate back to the pagelet.

**Comment by Andarist** [comment]
Please provide a well formed issue with a link to a repository with the issue reproduced, without this we won't be able to help you.

**Comment by AnirbanHub** [comment]
@Andarist  - Here is a link to the sandbox where I have tried to write the stub code. https://codesandbox.io/s/new-dc76z .  So when I do a console.log, right after line 31 of sagas.js file, it gives me 2 logs instead of one which is the issue here. When I downgrade the redux-saga on the package json and on the shared repo to version 0.16.2 the console log outputs only one log. So something is trigerring that saga call twice which only happens on this redux-saga version(1.0.2). In fact I have tested on version 1.0.0 and I get the error with that version as well. Please let me know if that helps.
