### ISSUE TITLE
How to make multiple API requests in a loop and get the failed ones at the end of the saga ?

### ISSUE THREAD

**Issue by thidasapankaja** [redux-saga/redux-saga#1885]
How can I yield inside forEach or map ?

I have a scenario which is quite unique. I followed [this](https://github.com/redux-saga/redux-saga/issues/306) answer but it doesn't serve my purpose. What I need is I need to run multiple api requests to same endpoint and catch if there's any error and continue. And at the end pass the error object.

```
function* createGroups(data) {
  const task = yield fork(Api.createGroupUrl,, data);

 // How can I catch the particular error and continue ?
}

yield payload.rateGroups.map(group =>
    call(createGroups, { ...requestData, groupId: group.id }),
  );
```

Above code is the one I implemented following the mentioned answer.
What I need is make all the requests and catch whether each of it's success or not.
 
Let's say I have array of 4 objects. And 2nd and 4th ones fail.  I need to run 3rd one even the 2nd one fails and at the end return the failed groupIds.

How can I do it ? Any help would be greatly appreciated.

Thanks

**Comment by Andarist** [comment]
Example solution:
```js
function zip(arrayA, arrayB) {
  return arrayA.map((elementA, index) => [elementA, arrayB[index]]);
}

const settle = (fn, ...args) =>
  call(function*() {
    try {
      return { status: "fulfilled", value: yield call(fn, ...args) };
    } catch (err) {
      return { status: "rejected", reason: err };
    }
  });

function* worker() {
  const results = yield all(
    payload.rateGroups.map(group =>
      settle(createGroups, { ...requestData, groupId: group.id })
    )
  );

  const zipped = zip(results, payload.rateGroups);
  const failedGroups = zipped
    .filter(([settled]) => settled.status === "rejected")
    .map(([settled, group]) => group.id);
  
  // ...
}

```

**Comment by thidasapankaja** [comment]
Thank you @Andarist I'll try this and let know

**Comment by thidasapankaja** [comment]
@Andarist This worked perfectly for my scenario, Thank you !

**Comment by sachinkotwal** [comment]
@Andarist  I implemented above mentioned solution to call multiple graphql endpoints. But when there is an error in api .it is not getting caught inside the catch block, even I added additional try catch block inside the worker function but even it didn't get caught there too and directly displayed on the screen  like "Unhandled Rejection (Error): GraphQL error:" Not sure What I am missing here
