### ISSUE TITLE
When is saga scheduler queue flushed?

### ISSUE THREAD

**Issue by 3kgoldie** [redux-saga/redux-saga#1891]
When is the saga scheduler queue flushed? I see that yielding put in a saga causes a dispatch task to be added to the queue and then the queue is flushed, but is that the only time? Is there a way for the queue to end up in a suspended state and has to wait for another asap/immediately call before executing the rest of the tasks?

If I yield put in my saga, since put is non-blocking, my saga will resume immediately, but how soon can I expect the action to reach the reducers?

**Comment by Andarist** [comment]
It should always be delivered to your reducers within the current JS microtask (so the same call stack). Do you need extra info? In general would be better not to rely on internal scheduling semantics, so not sure if I'd like to spoil more for you 😉

**Comment by 3kgoldie** [comment]
Yes, I would like extra info, thank you. I just want to make sure I understand what is happening

**Comment by Andarist** [comment]
We flush after:
- [when executing `put`](https://github.com/redux-saga/redux-saga/blob/edd8f77b7886c858199ff2c23af571cec6477f8c/packages/core/src/internal/effectRunnerMap.js#L68)
- [receiving external action from redux](https://github.com/redux-saga/redux-saga/blob/edd8f77b7886c858199ff2c23af571cec6477f8c/packages/core/src/internal/channel.js#L241)
- [after starting root saga](https://github.com/redux-saga/redux-saga/blob/edd8f77b7886c858199ff2c23af571cec6477f8c/packages/core/src/internal/runSaga.js#L81)
- [after forking](https://github.com/redux-saga/redux-saga/blob/edd8f77b7886c858199ff2c23af571cec6477f8c/packages/core/src/internal/effectRunnerMap.js#L157)

**Comment by 3kgoldie** [comment]
Thanks!
