### ISSUE TITLE
How do I pause a generator until a promise resolves then yield the value?

### ISSUE THREAD

**Issue by baharev** [redux-saga/redux-saga#1893]
I am pretty sure I am missing something basic. Code:

```javascript
const { createStore, applyMiddleware } = require('redux')
const createSagaMiddleware = require('redux-saga').default
const { call } = require('redux-saga/effects')

function* fetchData() {
    // Fake task, "fetching" the number 1 from a remote server
    yield new Promise(resolve => setTimeout(() => resolve(1), 1000))
}

function* genFunc() {
    const data = yield call(fetchData)
    console.log('data:', data)
    yield 2
}

function* mainLoop() {
    for (const value of genFunc()) {
        console.log('In loop:', value)
    }
}

function* rootSaga() {
    yield call(mainLoop)
}

const sagaMiddleware = createSagaMiddleware()

const store = createStore(
    (state, action) => state, 
    { },
    applyMiddleware(sagaMiddleware)
)

sagaMiddleware.run(rootSaga)
```

When I run the code it prints:

    $ node index.js 
    In loop: { '@@redux-saga/IO': true,
      combinator: false,
      type: 'CALL',
      payload:
       { context: null, fn: [GeneratorFunction: fetchData], args: [] } }
    data: undefined
    In loop: 2

However, I want it to print (after a pause of 1 second):

    data: 1
    In loop: 2

That's what I expected to happen based on the [documentation](https://redux-saga.js.org/docs/api/#callfn-args):

> `call(fn, ...args)`  
> [...] The parent Generator will be suspended until
> the child Generator terminates normally, in which case the parent
> Generator is resumed with the value returned by the child Generator.

What am I missing?

How do I pause a generator until a promise resolves then yield the value?

Many thanks in advance!

**Comment by Andarist** [comment]
In this case with by doing `genFunc()` you are basically just creating an iterator - which is just an object with `.next`/`.return`/`.throw` methods. You pass this directly to a for-of loop which uses iteration protocol so it exhausts that iterator and thus you are receiving raw yielded values (they were receiving by the iterating loop as return values of its internal next calls).

For things to get resolved by redux-saga you have to pass it to redux-saga's runtime by yielding to it. How to do that? It depends on what you are trying to achieve with this for-loop. 

In general, most commonly u want to "await" the final result of the called child worker, and you could do that with:
```js
yield call(genFunc)
```
But that wouldn't give you access to an intermediate value of the fetchData's result, it would give you only the returned `2`.

If you really need access to those intermediate values you could achieve this with combination of fork and channel, but this seems like beyond the scope of this question. If not - please ask me to explain this in more detail and I will provide an example of this.

**Comment by baharev** [comment]
@Andarist Thank you for the response. That `for` loop is important for the real application. I am only showing you a simplified code here which of course does not make much sense due to the simplifications...

I don't want to see the intermediate result `1` in the loop. That is what I would like to see after a 1 second pause:

    data: 1
    In loop: 2

(Note: there isn't `In loop: 1` in the desired output.)

In the real application `genFunc()` yields chunks of a blob. The blob would not fit into memory, but the chunks do. We do not know the number of chunks ahead of time, that's why I am iterating over `genFunc()` in mainLoop. The `mainLoop()` applies transformations to the chunks (deflates them), then accumulates them. The compressed chunks should fit into memory.

I have already found a workaround in the real application, nevertheless, I would like to understand how to do it with generators and redux-saga.

Thank you for the help in advance.

**Comment by Andarist** [comment]
The for-of loop needs to know somehow when the iteration stops and you need here to yield chunks (intermediate results) to the iterating process, this means that if u want to use for-of loop you'd have to do something quirky like this:
```js
function* getLazyChunks() {
    while (true) {
        // yield functions which should be called by the mainLoop
        yield () => getChunk().then((chunk) => {
            // assign done based on appropriate condition
            return chunk
        }))

        if (done) {
            return
        }
    }
}

function* mainLoop() {
    const accumulator = []
    const it = getLazyChunks()

    for (const getNextChunk of it) {
        const chunk = yield call(getNextChunk)
        accumulator.push(deflate(chunk))
    }

    // process accumulator
}
```

With channels you could establish 2 way explicit communication like this:
```js
function* getLazyChunks(in, out) {
    while (true) {
        yield take(in)
        const chunk = yield call(getNextChunk)
        if (/* some condition */) {
            out.close()
            return
        }
        yield put(out, chunk)
    }
}

function* mainLoop() {
    const in = channel()
    const out = channel()
    const accumulator = []

    yield fork(getLazyChunk, in, out)

    while (true) {
        yield put(in, true)
        const chunk = yield take(out)
        
        if (chunk === END) {
            break
        }

        accumulator.push(deflate(chunk))
    }

    // process accumulator
}
```

**Comment by baharev** [comment]
@Andarist Thank you for the example snippets. As far as I am concerned, we can close this issue. I really appreciate your help!
