### ISSUE TITLE
redux-saga does not do anything: not listening the dispatches (or is not running the saga function)

### ISSUE THREAD

**Issue by marcosroot** [redux-saga/redux-saga#1896]
I have a saga to handle login, which will listen for LOGIN_REQUEST (state/auth/saga.js):

```
function* handleLogin(action) {
    // ...

    console.log("handleLogin saga OK")

    try {
        // ...

    } catch (e) {
        // ...
    }
}

function* loginSaga() {
    console.log("loginsaga ok")
    yield takeLatest(LOGIN_REQUEST, handleLogin)
}

export {
    loginSaga,
}
```

a point here: the login.log of loginSaga is executed when the app is rendered, but the console.log of the handleLogin function is not executed when the action is dispatched, which shows that the saga seems to be configured correctly but not running function after dispatch

Now, I import this into a root file (state/rootSaga.js):

```
import {
    loginSaga
} from './modules/auth/saga';

function* rootSaga() {
    yield all(
        [
            loginSaga(),
        ]
    )
}

export default rootSaga;
```

After that, I do the same thing doc says, but using reduxdevtools (state/configureStore.js):

```
// saga imports
import createSagaMiddleware from 'redux-saga';
import rootSaga from './rootSaga';

const configureStore = () => {
    const persistedState = loadState()
    const sagaMiddleware = createSagaMiddleware();

    // all middleares with redux dev tools
    const middlewares = [
        sagaMiddleware,
    ]

    const composeEnhancers = composeWithDevTools(
        applyMiddleware(
            ...middlewares
        )
    )

    const store = createStore(
        rootReducer,
        persistedState,
        composeEnhancers
    );

    sagaMiddleware.run(rootSaga)
    return store
};

export default configureStore;
```

I can not seem to figure out where I'm going wrong, I know only that the dispatch seems to be not being heard by the middleware, or the loginSaga is not running the function.

source code: https://github.com/marcosroot/webstation.dev-client/tree/master/src/state

**Comment by jayeshanandani** [comment]
I am running into the same issues. None of the dispatches are being heard. It seems to be related to  #1887

**Comment by marcosroot** [comment]
this started to work magically, then I dispatched the same action into useEffect, into another component (the original is dispatched when submitting a form)

**Comment by lindboe** [comment]
FWIW I ran into an issue like this and moving where I was calling `sagaMiddleware.run` made it work. From https://github.com/redux-saga/redux-saga/issues/1120 I surmise that the action that I cared about was being dispatched before the sagas were being run.

**Comment by pulpfree** [comment]
I have the same problem with versions >= 1.0.0. If I downgrade to <= 0.16.2 it works ok.

**Comment by GreenRidingHood** [comment]
thanks @pulpfree , i didnt understand rearranging solution from @lindboe -looks like better approach but my luck of knowledge  i guess, that works after so many hours

**Comment by dotslashbin** [comment]
hmm this didn't really do it for me. @pulpfree , did you have to downgrade something else besides redux-saga?

**Comment by pulpfree** [comment]
@dotslashbin ensure that your root is setup as below, the `yield all` was the key.
```
function* rootSaga() {
    yield all(
        [
            loginSaga(),
        ]
    )
}
```

**Comment by dotslashbin** [comment]
Thank you very much! I finally got it. There was also an issue with the "connect" function on my component. So, the problem wasn't actually this.

**Comment by lenindelarosa** [comment]
> @dotslashbin ensure that your root is setup as below, the `yield all` was the key.
> 
> ```
> function* rootSaga() {
>     yield all(
>         [
>             loginSaga(),
>         ]
>     )
> }
> ```

Thanks man! After viewing this I put a comma at the end of the last saga in the array, and it worked! I proceeded with removing the comma cause it just does not make sense, and it continued to work... What kind of bug is this!? I lost a full day of coding because of this :(

**Comment by dotslashbin** [comment]
I'm glad you go through with it man! yeah, sometimes you need 1 day to
solve something really simple. It's important that you have your linters in
check.

Anyway, now I am using redux-toolkit.You should give it a try too. It has a
lot of advantages which I think is great for large scale projects.
