### ISSUE TITLE
How do I cancel a setTimeout within a saga?

### ISSUE THREAD

**Issue by orpheus** [redux-saga/redux-saga#1897]
How do you cancel a setTimeout function initiated by a saga? For instance, on `takeLatest`, it's supposed to cancel the saga that was fired for the previous action, but if that saga initiated a timeout the timeout still runs even though `takeLatest` cancelled the saga.

I've tried to assign the setTimeout to a variable and do cancelTimeout on the finally block catch as shown [here in the very last example](https://redux-saga.js.org/docs/advanced/NonBlockingCalls.html) but to no avail. I don't quite understand the timing of everything that is happening. But here's my code:

```
const delay = ms => new Promise(resolve => {
  setTimeout(() => {
    // here is where I want to specify my timeout logic
    console.log('timed-out')
    resolve()
  }, ms)
})

export function * setActionTimeout () {
  yield put(setActionTimestamp(Date.now()))
  yield delay(3000)
  console.log('post delay')
}

export function * actionHandler () {
  yield takeLatest(TAKE_IN_ACTION, setActionTimeout)
}
```

What happens is that let's say 15 actions go off. It takes in all 15 actions, then in about 3 seconds I get 15 logs of: `timed-out` and then right after 1 log of: `post delay` 

So I see that the sagas are getting cancelled because otherwise I would have expected 15 logs of: `post delay`. But I cannot figure out how to cancel the timer. 

I've also tried: 

```
const delay = ms => new Promise(resolve => {
  resolve(setTimeout(() => {
    console.log('timed-out')
  }, ms))
})

export function * setActionTimeout () {
  yield put(setActionTimestamp(Date.now()))
  let timeout
  try {
    timeout = yield delay(3000)
  } finally {
    if (yield cancelled()) {
      clearTimeout(timeout)
    }
  }
  yield delay(3000)
  console.log('post delay')
}
```

But here this happens: `timeout` is undefined in the `finally` block and so `timed-out` gets logged 15 times. 

How can I create a saga that takes the latest action, starts a timeout, and cancels the previous timeout?

**Comment by Andarist** [comment]
Don't reimplement delay on your own - it's a builtin effect and the builtin one already support cancellation and it's implemented like this:
https://github.com/redux-saga/redux-saga/blob/374fde6e70945e0d20b2e4c221b74f643e26bd2b/packages/delay-p/src/index.js#L9

**Comment by orpheus** [comment]
Fantastic, I overlooked that api effect. Thank you
