### ISSUE TITLE
EventChannel for SignalR events isn't emitting

### ISSUE THREAD

**Issue by TAGC** [redux-saga/redux-saga#1903]
I'm trying to set up a saga that handles information transmitted over SignalR from an ASP.NET Core application. I've followed the documentation [here](https://redux-saga.js.org/docs/advanced/Channels.html) and written code that successfully establishes a connection and receives data through the socket. However, the saga I wrote to retrieve items emitted on the event channel blocks indefinitely, even after data is emitted into it. I noticed #1502 describes a pretty similar issue.

The snippet below illustrates what I've attempted so far, and as far as I can tell it should work. In the browser console pane, I see logs showing the connection getting established and I see "Emitting" appear too, meaning that `overwriteBranchStateHandler` got invoked. I also see "Got here 1?" but not "Got here 2?" in the pane, showing that the saga is blocking at `const update = yield take(socketChannel);`.

```typescript
import { HubConnection, HubConnectionBuilder } from '@aspnet/signalr';
import { eventChannel, EventChannel } from 'redux-saga';
import { all, apply, call, put, take } from 'redux-saga/effects';
import { overwriteBranchState } from './actions';
import { ProductConsultant } from './types';

function createSocket(rootUrl: string): HubConnection {
  const connection = new HubConnectionBuilder().withUrl(`${rootUrl}/branchHub`).build();
  return connection;
}

interface IBranchState {
  productConsultants: ProductConsultant[];
}

function subscribeToUpdates(connection: HubConnection): EventChannel<IBranchState> {
  return eventChannel(emit => {
    function overwriteBranchStateHandler(branchState: IBranchState) {
      console.log('Emitting');
      emit(branchState);
    }

    function unsubscribe() {
      connection.off('OverwriteBranchState');
    }

    connection.on('OverwriteBranchState', overwriteBranchStateHandler);

    return unsubscribe;
  });
}

export function* watchOnUpdates() {
  const socket = yield call(createSocket, 'https://localhost:5001');
  const socketChannel = yield call(subscribeToUpdates, socket);
  yield apply(socket, HubConnection.prototype.start, []);
  yield apply(socket, HubConnection.prototype.invoke, ['QueryBranchState']);

  try {
    while (true) {
      yield call(console.log, 'Got here 1?');
      const update = yield take(socketChannel);
      yield call(console.log, 'Got here 2?');
      yield put(overwriteBranchState(update.productConsultants));
    }
  } finally {
    yield apply(socket, HubConnection.prototype.stop, []);
  }
}

export default function* rootSaga() {
  yield all([watchOnUpdates()]);
}
```

### Environment information

- redux-saga version: 1.0.5

#### TypeScript setup

Using version 3.5.3

##### tsconfig

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "downlevelIteration": true
  },
  "include": [
    "src"
  ]
}
```

**Comment by TAGC** [comment]
Hi. any update on this?

**Comment by Andarist** [comment]
In what order 'Emitting' and 'Got here 1?' are shown in the console?

**Comment by TAGC** [comment]
'Emitting' first, and then 'Got here 1?'.

**Comment by Andarist** [comment]
`eventChannel` is not buffered by default, so if you emit when there is no listener (pending take) on it then the message gets dropped. You can change used buffer type though, so you can create your `eventChannel` like this:
```js
eventChannel(subscribe, buffers.expanding())
```

**Comment by TAGC** [comment]
That worked. Thanks for your help. 👍
