### ISSUE TITLE
Is there an effect for post-processing a set of events in sequence?

### ISSUE THREAD

**Issue by davidrpiper** [redux-saga/redux-saga#1904]
Hey folks,

First of all thank you for your work on redux-saga and for being so active in the community. I have a question about how to implement a particular kind of `take` behaviour.

It feels like a combination of `takeLeading` and `takeLatest`.

On receiving any of actions A, B or C, I would like to execute a saga, and prevent parallel invocations of the same saga if more actions come in. This can be achieved with the `takeLeading` effect.

However, if more actions do come in, I would like the saga to execute again immediately after the first invocation of the saga completes. This is not quite the same as `takeLeading` because it does not continue to listen to events while the saga is running.

(If A, B or C could not be fired while the saga is executing, then `takeLeading` would be sufficient, but I cannot guarantee that sadly).

Essentially there should only ever be a single saga invocation running at any stage, with the constraint that an executing saga should not be cancelled when a new event comes in, but that event should be tracked in some way so that the saga can fire again after it completes.

Is there a built-in effect (or a combination of effects) that could do this?

**Comment by davidrpiper** [comment]
Hm I may have been a bit fast in asking the question - I think I've found something that works? Can I confirm with someone that this isn't crazy?

```
const channel = yield actionChannel([A, B, C], buffers.sliding(1));
while (true) {
    yield take(channel);
    yield myFunc();
}
```

**Comment by Andarist** [comment]
That’s a good solution and in fact out builtin throttle is implemented similarly

**Comment by davidrpiper** [comment]
Thanks! It's the first time I'd needed something beyond the built-in effects so it felt a little strange.
