### ISSUE TITLE
delay methods get suspended on iPad and iPhone

### ISSUE THREAD

**Issue by jpgorman** [redux-saga/redux-saga#1905]
### Steps to reproduce

```js
function* myDelayedLogoutSaga(){
  yield put(action.logout())
}

function*() {
  const FIVE_MINUTES = (1000 * 60) * 5
  yield delay(FIVE_MINUTES)
  yield myDelayedLogoutSaga()
}
```

#### Description of the bug/issue
The delayed saga is suspended by the OS when the device is locked. When the device is unlocked the delay will continue from where it left off.

#### Steps to reproduce the bug/issue

As above
...

### Actual results
Delays can run for as long as a device is locked.

### The Expected results
The delay should run for as long as is specified in the code

**Comment by Andarist** [comment]
This really seems like something out of the scope of the saga. Under the hood we use plain `setTimeout` and if that's how it works - then its behavior shouldn't be altered by redux-saga.

**Comment by jpgorman** [comment]
I guess then, it would mean that any time critical operations would have to be hand rolled by the given developer. A good example would be triggering an action to lock an app after a given timeout. 

This can be achieved by using a polling timer. 

Maybe a better solution would be to add a method that allows for a delay that uses polling?

**Comment by Andarist** [comment]
This seems like a more special need - more often a developer doesn't have to worry about it as it doesn't affect their app that much. 

This can be implemented in userland very easily though (just create your own `delay` version in few lines of code). Keep in mind that polled version might also have some drawbacks - browsers really don't guarantee that timers will get fired at their scheduled deadlines. You might encounter this problem i.e. on desktop browsers when you switch tabs, go idle or whatever - even `setTimeout(fn, 1000)` might fire after several seconds, 2 minutes or probably even after a longer period of time.

**Comment by jpgorman** [comment]
The advantage of the polling approach though is that it would negate the hibernation state, regardless of it's precision.

You're right though. Looking at the existing code base `delay` is peppered throughout so this issue would crop up when using `debounce`, `retry` and a few others no doubt. 

These can be fixed in userland though as you say. It's just add more overhead to using sagas.

**Comment by Andarist** [comment]
IMHO it doesn't add any overhead to using sagas - it just doesn't lift that responsibility from your shoulders.
