### ISSUE TITLE
can redux saga dispatch return result immediately instead of returning action

### ISSUE THREAD

**Issue by alanhg** [redux-saga/redux-saga#1907]
maybe like this

```javascript
 async componentDidMount() {
        const userInfo = await this.props.fetchUserAction();
    }
```

```javascript
function* fetchUserEffects() {
    console.log('fetchUserEffects');
    const user = (yield call(getUserInfo));
    return user;
    // yield put({type: 'USER_FETCH_SUCCEEDED', user: user.data});
}

function* mySaga() {
    yield takeEvery('USER_FETCH', fetchUserEffects);
    yield takeEvery('TEST_SAGA', testSagaEffects);
}

export default mySaga;
```

```javascript
export const fetchUserAction = () => ({
    type: 'USER_FETCH'
});
```

## benefit
I can use the effect's result directly, don't need to put action and save data to redux store.

## dva.js
According to my understanding, dva.js is based on the framework of redux-saga and other technologies. When we dispatch the action in this framework and execute saga-effects, we can get the result directly. I think this is a very good feature.

## about the question
https://stackoverflow.com/questions/52214499/can-redux-saga-dispatch-return-api-result-immediately-instead-of-returning-actio

**Comment by aybb** [comment]
You don't call saga directly, you actually calling `store.dispatch(action)`.

**Comment by alanhg** [comment]
> You don't call saga directly, you actually call `store.dispatch(action)`.

I know it.

**Comment by aybb** [comment]
> > You don't call saga directly, you actually call `store.dispatch(action)`.
> 
> I know it.

Then what is your question about ? You can use something like https://github.com/Chion82/redux-wait-for-action this in order to achieve this behavior but you should not build your app in that way.

**Comment by kutlugsahin** [comment]
Hey @alanhg 

I needed the same behavior once so I wrote my own helper functions to do that. It also enables waiting for the result of dispatched actions in saga. Take a look at [redux-saga-callback](https://github.com/kutlugsahin/redux-saga-callback).

**Comment by alanhg** [comment]
@kutlugsahin I will try.

**Comment by nilu1991** [comment]
Hello @alanhg ,

Did you got any solution for this, if yes Can you please update?

**Comment by alanhg** [comment]
@nilu1991 I found a solution,@adobe/redux-saga-promise

and I create demo, you can read my commit 
https://github.com/alanhg/react-demo/commit/52f7ef7a287a51407d00d89cc04f2cdf09ea8df8
