### ISSUE TITLE
No saga response when using version >= 1.0.0

### ISSUE THREAD

**Issue by pulpfree** [redux-saga/redux-saga#1908]
After upgrading my app to the latest version of saga I get no response from my sagas. If I downgrade to <= 0.16.2 it works ok.

I downloaded the redux-saga-beginner-tutorial repo, upgraded to 1.0.2 and same problem, nothing works.

Is there something in the store setup for versions >= 1.0.0 that is not listed in your docs?

Regards,
Ron Dyck

**Comment by danielweck** [comment]
Exact same problem. Sticking to `0.16.2` for now.

**Comment by Andarist** [comment]
Are you by any chance using saga in React Native?

**Comment by pulpfree** [comment]
No, just react@latest

**Comment by Andarist** [comment]
Are there no errors logged in the console? `redux-saga` is well-tested and v1 is only a small iteration over v0.16, so whatever that has to be some environmental/setup problem.

I got reports from React Native users that it's hard for them to notice misusage errors - caused mainly by using `yield call(delay, 100)` over `yield delay(100)` (where latter is v1 version of the same thing)

**Comment by danielweck** [comment]
Same here, just React.

**Comment by danielweck** [comment]
In my case, I did make sure to update the `delay` code to the new effect API.

**Comment by danielweck** [comment]
No console error messages, the app just hangs "doing nothing" :)
(the Redux Saga pipeline does not seem to kick-in)

In my case, note that WebPack is used to bundle the TypeScript code into ES5 Javascript bundles (main and renderer processes in Electron).

**Comment by Andarist** [comment]
Could you try to distill down your setup so I could debug it? Or put a bunch of console logs at the startup of your root saga to see if it runs at all. Next step would be to check if reducers receive actions and later put a console log in here - https://github.com/redux-saga/redux-saga/blob/374fde6e70945e0d20b2e4c221b74f643e26bd2b/packages/core/src/internal/middleware.js#L28 and maybe debug that .put call to see if it does anything.

**Comment by danielweck** [comment]
I would love to be able to contribute a minimal repro test case, but I am afraid I am running short of dev time at the moment. Thank you for pin-pointing where the problem potentially comes from though, and for providing general guidance on how to troubleshoot the "stalled" Saga pipeline :)

**Comment by pulpfree** [comment]
Probably the simplest would be to clone (or maybe fork) the https://github.com/redux-saga/redux-saga-beginner-tutorial repo and upgrade redux-saga to the latest version.
For example in the repo file: sagas.js, I have the following:
```
export function* incrementAsync() {
  console.log('fire incrementAsync')
  yield call(delay, 1000)
  yield put({type: 'INCREMENT'})
}
```
The console.log statement prints in the original repo version of 0.15.0, but when upgraded to the latest, nothing logs out.

I did notice in the repo examples: https://github.com/redux-saga/redux-saga/blob/master/examples/async/src/main.js that the store is created somewhat differently than other examples so that runSaga is started after the store is configured:
```
const store = configureStore()
store.runSaga(rootSaga)
```
I'd be willing to try this approach (a little later today/tomorrow) and report back with my findings.

**Comment by danielweck** [comment]
Electron main process:
```
import { applyMiddleware, createStore } from "redux";
import { composeWithDevTools } from "redux-devtools-extension";
import createSagaMiddleware from "redux-saga";

    const sagaMiddleware = createSagaMiddleware();
    const store = createStore(
        MY_ROOT_REDUCER,
        composeWithDevTools(
            applyMiddleware(sagaMiddleware),
        ),
    );
    sagaMiddleware.run(MY_ROOT_SAGA);
```

Electron renderer process:
```
import { applyMiddleware, createStore } from "redux";
import { composeWithDevTools } from "redux-devtools-extension";
import createSagaMiddleware from "redux-saga";

import { routerMiddleware } from "connected-react-router";

    const sagaMiddleware = createSagaMiddleware();
    const store = createStore(
        MY_ROOT_REDUCER(MY_HASH_HISTORY),
        composeWithDevTools(
            applyMiddleware(
                routerMiddleware(MY_HASH_HISTORY),
                sagaMiddleware,
            ),
        ),
    );
    sagaMiddleware.run(MY_ROOT_SAGA);
```

**Comment by Andarist** [comment]
@pulpfree I've [fixed that tutorial](https://github.com/redux-saga/redux-saga-beginner-tutorial/commit/e5e6f404d877267a4a662d32999cc93e36f10084) - main issue was that plain array was yielded [here](https://github.com/redux-saga/redux-saga-beginner-tutorial/blob/4e09911253aee603bcf93e215e5cb0bd5bc0852a/sagas.js#L19-L22) (instead of that array wrapped in `all` effect). That pattern was deprecated [since 29 Apr 2017](https://github.com/redux-saga/redux-saga/releases/tag/v0.15.0) (and there were deprecation warnings in the console since then)

**Comment by pulpfree** [comment]
@Andarist yes, the `all` effect did the job. Seems to me I did get some warnings for not using it at some point (can't recall what version etc). Thanks for all your help!

**Comment by danielweck** [comment]
That fixed it for me too (`all()` + individual `call()` for each array item). Thanks! :)

**Comment by lucasfeijo** [comment]
The issue of not using `all` in the root saga did it for me, thanks! You should add this to the release logs in version 1.0.0 as a breaking change! Because it is.

**Comment by Andarist** [comment]
@lucasfeijo it’s literally there - https://github.com/redux-saga/redux-saga/releases/tag/v1.0.0 :
> removed some deprecated APIs - takeEvery, takeLatest, throttle from the redux-saga entry point (they are and were importable from redux-saga/effects), takem, put.sync and executing array of effects, there is explicit API for this for already some time - all effect
