### ISSUE TITLE
Codemod to rewrite imports from 'redux-saga' to 'redux-saga/effects'

### ISSUE THREAD

**Issue by CoryDanielson** [redux-saga/redux-saga#1918]
I've written a code mod that rewrites imports from 'redux-saga' to 'redux-saga/effects'. It was useful while upgrading a large codebase between different versions of redux-saga.

Is this something that could potentially be included into this repo? If so, how would you like it to be stored and organized?

**Comment by Andarist** [comment]
Hi! Yes - this could certainly be included in this repository. Do you have examples with how different projects keep those?

**Comment by evidens** [comment]
It seems like a lot of projects have a separate repo for codemods:
- https://github.com/reactjs/react-codemod
- https://github.com/babel/babel-upgrade
- https://github.com/skovhus/jest-codemods

But I've also kept them under a `/transforms/` directory at the root of the project.

If you haven't already written tests for the codemods, it's pretty easy with `__testfixtures__` I can point out examples if needed.

**Comment by CoryDanielson** [comment]
How would someone use the `/transforms/` if they were included into this repo?

Tests are really the last thing that I need to add for the codemod - I was just modifying a test file locally and updating it as I developed the codemod.

**Comment by CoryDanielson** [comment]
How would someone use the `/transforms/` if they were included into this repo?

---

Tests are really the last thing that I need to add for the codemod - I was just modifying a test file locally and updating it as I developed the codemod.

**Comment by Andarist** [comment]
@CoryDanielson I was thinking of just publishing them so people could install them and run with jscodeshift easily
