### ISSUE TITLE
Update API documentation for put

### ISSUE THREAD

**Issue by superburrito** [redux-saga/redux-saga#1921]
Not sure if anyone else had the same experience, but I was thrown off a little bit by 
https://redux-saga.js.org/docs/api/#putaction

> Creates an Effect description that instructs the middleware to dispatch an action to the Store. This effect is non-blocking and any errors that are thrown downstream (e.g. in a reducer) will not bubble back into the saga. 

The term `non-blocking` somehow led me to expect `put` to behave like some kind of "asynchronous `dispatch`".  This intuition is of course, incorrect, as we can expect the store to immediately receive the action from `put()` unless we have some kind of asynchronous middleware that delays/prevents the action from reaching the store.

I do wonder if this is a valid concern? If it seems like a reasonable mistake to make, I'd be glad to submit a PR to suggest tweaks to the wording.

**Comment by Andarist** [comment]
I agree that non-blocking here might be misleading - it would be better to just describe it as synchronous. In addition to that, the last part of what you have pasted in is incorrect - errors thrown in reducers are no longer swallowed - https://codesandbox.io/s/redux-saga-example-goc5o . That has changed in v1.

Would you like to prepare a documentation PR improving both things?

**Comment by superburrito** [comment]
Sure, I'd be happy to

**Comment by alanhg** [comment]
@superburrito 
> unless we have some kind of asynchronous middleware that delays/prevents the action from reaching the store
can you give an example?
