### ISSUE TITLE
How to get output of `all` effect?

### ISSUE THREAD

**Issue by hopewise** [redux-saga/redux-saga#1923]
I am trying to use saga outside the context of redux, simply experimenting with effects and generators.

I need to retrieve all key values from `Storage` in parallel, here is my implementation:

```
export function* getHeaders() {
  let calls = []
  APIClient.instance().keys.forEach((key) => calls.push(call(Storage.get, key)))
  yield all(calls)  
}
```

where each `Storage.get` returns a promise.

I do call the function as:

```
let values = getHeaders().next().value
console.log(values)
```

I already have 5 keys in storage, I expected to get their values, but instead I got:

![Screen Shot 2019-09-01 at 11 57 53 AM](https://user-images.githubusercontent.com/1061157/64076216-a0845d00-ccca-11e9-84de-a85fb3466658.png)

Any idea?
as seen above, `uid` is the first key in `APIClient.instance().keys`

**Comment by Andarist** [comment]
You are not supposed to call `.next` manually in your application code. Instead of that, you should pass your root saga to the middleware and call/fork the rest.

**Comment by hopewise** [comment]
Can I use the above example without using Redux? I just want to make use of the goodness of `call`

**Comment by Andarist** [comment]
https://redux-saga.js.org/docs/advanced/UsingRunSaga.html

**Comment by hopewise** [comment]
Thanks
