### ISSUE TITLE
bundling failed: Error: Unable to resolve module `./chunk-2fd513a6.js`

### ISSUE THREAD

**Issue by kishansbs** [redux-saga/redux-saga#1934]
error: bundling failed: Error: Unable to resolve module `./chunk-2fd513a6.js` from `/Users/machd/Desktop/RN_Projects/App/app/node_modules/@redux-saga/core/dist/redux-saga-core.prod.cjs.js`

"react": "16.8.6",
    "react-native": "0.60.4",
 "redux-saga": "^1.0.5"

**Comment by Andarist** [comment]
Please reinstall your node_modules, clean cache etc. That file is published as you can confirm here - https://unpkg.com/@redux-saga/core@1.0.3/dist/chunk-2fd513a6.js

**Comment by kishansbs** [comment]
@Andarist 

thanks, clear cache work for me.

**Comment by phungnlg** [comment]
> Please reinstall your node_modules, clean cache etc. That file is published as you can confirm here - https://unpkg.com/@redux-saga/core@1.0.3/dist/chunk-2fd513a6.js

I did all these steps but got no luck. Here's my console output

Started by user Phung Nguyen
Running as Phung Nguyen
Building remotely on vps-ubuntu-adslave in workspace /home/adslave/jenkins/workspace/RN_Template/rct_android_mss
using credential 839a5065-92d6-49e7-902a-fea784547ab2
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://phungbss@bitbucket.org/phungbss/mss_upgrade.git # timeout=10
Fetching upstream changes from https://phungbss@bitbucket.org/phungbss/mss_upgrade.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://phungbss@bitbucket.org/phungbss/mss_upgrade.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision d2cc653a97c9096ffe2c810a262ceb8726bcd98a (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d2cc653a97c9096ffe2c810a262ceb8726bcd98a
Commit message: "1.0.3"
 > git rev-list --no-walk d2cc653a97c9096ffe2c810a262ceb8726bcd98a # timeout=10
[rct_android_mss] $ /bin/sh -e /tmp/env-rct_android_mss884610863321598628.sh
[environment-script] Adding variable 'HOCKEY_APP_ID' with value '8b87e776b6484903bedef80a14384561'
[environment-script] Adding variable 'PACKAGE_VERSION' with value '1.0.3'
[environment-script] Adding variable 'PROJECT_NAME' with value 'RN_Template'
[rct_android_mss] $ /bin/sh -xe /tmp/jenkins6033509677696638119.sh
+ INIT_BUILD_NUMBER=0
+ expr 0 + 12
+ BUILD_NUMBER=12
+ npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
+ npm cache verify
Cache verified and compressed (~/.npm/_cacache):
Content verified: 0 (0 bytes)
Index entries: 0
Finished in 0.021s
+ npm config set prefix /home/adslave/jenkins/workspace/RN_Template/rct_android_mss
+ npm install --force --unsafe-perm
npm WARN using --force I sure hope you know what you are doing.

> MSS@1.0.3 postinstall /home/adslave/jenkins/workspace/RN_Template/rct_android_mss
> node ./Script/src/android-release-gradle-fix.js && node ./Script/src/android-gradle-fix.js

Already fixed.
Fix Start
Fix Done
npm WARN @emotion/provider@0.11.2 requires a peer of @emotion/core@0.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-treebeard@3.1.0 requires a peer of @emotion/styled@^0.10.6 but none is installed. You must install peer dependencies yourself.

audited 940604 packages in 20.539s
found 13 vulnerabilities (12 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
+ mkdir -p android/app/src/main/assets
+ rm -rf android/app/build
+ react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
Loading dependency graph, done.
error Unable to resolve module `./chunk-2fd513a6.js` from `/home/adslave/jenkins/workspace/RN_Template/rct_android_mss/node_modules/@redux-saga/core/dist/redux-saga-core.prod.cjs.js`: The module `./chunk-2fd513a6.js` could not be found from `/home/adslave/jenkins/workspace/RN_Template/rct_android_mss/node_modules/@redux-saga/core/dist/redux-saga-core.prod.cjs.js`. Indeed, none of these files exist:
  * `/home/adslave/jenkins/workspace/RN_Template/rct_android_mss/node_modules/@redux-saga/core/dist/chunk-2fd513a6.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/home/adslave/jenkins/workspace/RN_Template/rct_android_mss/node_modules/@redux-saga/core/dist/chunk-2fd513a6.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`. Run CLI with --verbose flag for more details.
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by Andarist** [comment]
You'd have to share complete, runnable, repository with the issue reproduced - without that I don't have enough information to know what can be wrong.

**Comment by Zabi-Progton** [comment]
Still the same error. Any fixes? Did cache clean and reinstalled node_modules, doesn't work

**Comment by Andarist** [comment]
> You'd have to share complete, runnable, repository with the issue reproduced - without that I don't have enough information to know what can be wrong.

**Comment by Tommoore96** [comment]
I've just done an npm update from 1.0.3 to the latest version and this has happened:

![Screenshot 2019-10-10 at 12 31 08](https://user-images.githubusercontent.com/27972790/66565317-1695a280-eb5a-11e9-94bd-2c67f589c1ec.png)

I've tried cleaning cache, removing `node_modules/`, reinstalling, even reverting to the old version to no avail.

**Comment by Andarist** [comment]
could u pack contents of your `node_mdoules/@redux-saga/core` and share it with me?

**Comment by senthilbalajiganesan** [comment]
for some reason it works only when u uninstall redux-saga only and reinstall redux-saga only again, it works.

**Comment by Mayaela** [comment]
Hey. I'm having the same problem and clearing cache, removing node_modules and upgrading saga didn't work...

**Comment by thanhluantl2304** [comment]
Restart IDE (VS Code) works for me!

**Comment by joncardasis** [comment]
I had this issue upgrading from 1.0.5 to 1.1.1.

Clearing cache (`rm -rf $TMPDIR/react-*; rm -rf $TMPDIR/haste-*; rm -rf $TMPDIR/metro-*; watchman watch-del-all`), removing node_modules, and then restarting metro worked for me.

**Comment by komelabbbas** [comment]
below steps are use for me [expo]
-> copy project folder and paste in new folder
-> in those new folder , node modules reinstall
-> start expo using "expo r -c"
-> Run on iOS simulator .
