### ISSUE TITLE
No exported member SagaIterator

### ISSUE THREAD

**Issue by codeinabox** [redux-saga/redux-saga#1939]
### Steps to reproduce
In a TypeScript project have the following import

`import { SagaIterator } from "redux-saga";`

Then build the project with `tsc --noEmit`

#### Description of the bug/issue
Module '".../node_modules/redux-saga/index"' has no exported member 'SagaIterator'.

### Environment information
- redux-saga version 1.1.1

**Comment by prwelber** [comment]
@codeinabox I am importing this as `import { SagaIterator } from "redux-saga/core"` and that seems to work, though in my setup I have to quiet ts and eslint because they complain about not being able to find the module 🤷‍♂

**Comment by Andarist** [comment]
@codeinabox please prepare a runnable repro case so I can take a look

**Comment by codeinabox** [comment]
I got to the bottom of it. The project package.json had a TypeScript dev dependency version of 3.0.1, upgrading this to 3.5.3 fixed the issue
