### ISSUE TITLE
put or putResolve no difference?

### ISSUE THREAD

**Issue by alanhg** [redux-saga/redux-saga#1940]
thunks

```javascript
export const fetchUser = (user) => (dispatch) => {
    getAddress()
        .then((res) => {
            dispatch(setUserInfo(user));
        })
        .catch((error) => {
            console.log(error);
        });
};

```

effects

```javascript
function* fetchUserEffects() {
    const user = (yield call(getUserInfo)).data;
    yield put(fetchUser(user)); // put or putResolve
    console.log('Class: fetchUserEffects, Function: fetchUserEffects, Line 8 yield select(): ', yield select(state => state.user));
}
```

## result
when I use put or putResolve, it always prints effects log first.

## should be?
when I use putResolve, it should print async action log

I am puzzled with putResolve and no-blocking concept.

![image](https://user-images.githubusercontent.com/9245110/65388522-2a31c280-dd7f-11e9-9945-4af95b0811c0.png)

**Comment by Andarist** [comment]
Please take a look at this example - https://codesandbox.io/s/redux-saga-example-x77jb

**Comment by alanhg** [comment]
OK，I got it but in my case.
when I use put or putResolve, it always prints effects log first.
it's why. I used saga and thunk.

**Comment by alanhg** [comment]
@Andarist 
I understand, thank you very much.
But I still have a question, my example above, if I remove the catch, the difference between put and putResolve can be reflected, just like your example. But if you add a catch, it won't work. I want to know why.

### Error segment
```javascript
.catch((error) => {
            console.log(error);
        });
```

**Comment by Andarist** [comment]
I can't help you further unless you provide a runnable code that I could inspect - without such I don't have enough information to answer your question.

**Comment by pengw00** [comment]
so at the end of the day，putResole is blocking with more lantency？

**Comment by Andarist** [comment]
No - `putResolve` just works with thunk actions that return promises, so it can block until that promise resolves. It has no effect on regular actions.
