### ISSUE TITLE
Errors on invalid effects in fork

### ISSUE THREAD

**Issue by vansosnin** [redux-saga/redux-saga#1941]
### Description

Hello! First of all, thank you for this awesome library.

In your [v1 release](https://github.com/redux-saga/redux-saga/releases/tag/v1.0.0) you have stopper interpreting effects returned from `fork`.

![image](https://user-images.githubusercontent.com/8207551/65412258-504f7500-de08-11e9-8918-01b8b37fc706.png)

Though there is written that "_this shouldn't affect any real-life code_", it affected my project :) But it doesn't matter much.

**The question is**: is it possible to throw errors in such situations? This code had just stopped working silently and we couldn't see the problem in errors monitor.

**Comment by vansosnin** [comment]
Why only dev-mode error? If you have error monitoring only in production, and forgot to test this in dev mode, it still can blow up silently.

**Comment by Andarist** [comment]
> Why only dev-mode error? If you have error monitoring only in production, and forgot to test this in dev mode, it still can blow up silently.

Well - if you forget to test in dev mode you are probably in bigger problems than this one 😉I believe that adding a production error for this could be a breaking change and we can't do that without bumping a major version.

**Comment by vansosnin** [comment]
Ofcourse there are some problems) And still it doesn't mean that throwing error is incorrect. It is one of ways to receive feedback and detect problem.
Well, breaking change is an argument. Maybe, you can add this feature to some kind of backlog for version 2?

**Comment by Andarist** [comment]
> Well, breaking change is an argument. Maybe, you can add this feature to some kind of backlog for version 2?

Could be done, but there are no plans right now to work on v2 - the API is stable and I have no ideas what I would refactor that would need breaking changes (only an idea or two for new, but compatible, APIs which can be released as part of the v1 line).
