### ISSUE TITLE
How to access the context inside a component ?

### ISSUE THREAD

**Issue by abdelmagied94** [redux-saga/redux-saga#1942]
I used the saga context api to share my API client instance between sagas. After the user login successfully, I persist the user authentication token using `redux-persist` library. To check if there's a token or not when the app opens, I created a Loading component and connect it to the store. Now, I want to access the context to set the token if found to the API instance. How would I do that?

**Comment by Andarist** [comment]
Dispatch an action, listen to it in your saga and setContext appropriately.

**Comment by abdelmagied94** [comment]
@Andarist Thanks for quick response. I really appreciate that. Isn't it possible to consume the saga context like we can do with the React context?

**Comment by Andarist** [comment]
Saga's context is shared withing Saga's tree - just like React's one, which is shared inside React's tree (you can't access it easily from outside).

**Comment by abdelmagied94** [comment]
@Andarist So is there any alternatives to achieve the same task plus additionally give the components access to it? Sorry if I cause any annoying to you.

**Comment by Andarist** [comment]
You need to establish some way of communication or data sharing between saga and your component if you need it. Can't give you a recipe for this, because there are multiple ways to do it and you need to figure out what works best for you and your problem space.

**Comment by abdelmagied94** [comment]
Ok. Thank you very much! I really appreciate your help.
