### ISSUE TITLE
How to use web workers inside sagas? 

### ISSUE THREAD

**Issue by rssfrncsrenishaw** [redux-saga/redux-saga#1945]
Are there any examples of using web workers inside sagas?

Bonus points if it uses comlink!

**Comment by rssfrncsrenishaw** [comment]
Turns out that it just works 👍

**Comment by armw4** [comment]
Nice that sagas has native support for web workers. I’m slowly learning on the fly here! Great 👍

**Comment by rssfrncsrenishaw** [comment]
@Andarist  I was surprised that my google search came up empty for "redux saga + web worker".

**Comment by Andarist** [comment]
Web workers are not that widely used - so I guess it's because of that.

**Comment by rssfrncsrenishaw** [comment]
Yes unfortunately it is probably that.
