### ISSUE TITLE
takeLatest task cancelling based on some arguments of action payload

### ISSUE THREAD

**Issue by sadq10** [redux-saga/redux-saga#1949]
Hi guys,

I've an action (ACTION) with payload format as {a: …, b: …} and following is the takeLatest code.

yield takeLatest(ACTION, task);

Now, any previous task is cancelled if ACTION is fired again, however is there a way to have this task cancellation based on arguments?

For eg. something like below

yield takeLatest(ACTION, task, (action1, action2) => (action1.a === action2.a))

Now, any previous task is cancelled only if the value of 'a' key is same.

A simple scenario:

ACTION with payload {a: 1, b: 1} - Task 1 starts running

ACTION with payload {a: 2, b: 1} - Task 2 starts running and Task 1 isn't cancelled as the value of key 'a' doesn't match.

ACTION with payload {a: 1, b: 3} - Now, the Task1 is cancelled (if it's running) as the key 'a' matches with the first one.

Also, on a related note, is there a way to perform clean up code if the task is cancelled as part of takeLatest?

**Comment by Andarist** [comment]
You can check out `takeLatestPerKey` here - https://codesandbox.io/s/kwr75ynq7v 

```js
function takeLatestPerKey(patternOrChannel, worker, keySelector, ...args) {
  return fork(function*() {
    const tasks = {};

    while (true) {
      const action = yield take(patternOrChannel);
      const key = yield call(keySelector, action);

      if (tasks[key]) {
        yield cancel(tasks[key]);
      }

      tasks[key] = yield fork(worker, ...args, action);
    }
  });
}
```

**Comment by sadq10** [comment]
Thank you very much @Andarist. It's working great. I will read more about these effects to understand it's working.

**Comment by sadq10** [comment]
Shouldn't it be:

```
if (tasks[key].isRunning()) {
        yield cancel(tasks[key]);
      }
```
instead of

```
if (tasks[key]) {
        yield cancel(tasks[key]);
      }
```
.

**Comment by Andarist** [comment]
Yeah - it could be. I think (not 100% sure) that canceling a canceled or done task is a noop, so it shouldn't matter though.

**Comment by vincerubinetti** [comment]
Disclaimer, I'm brand new to `redux-saga`.

Great solution @Andarist. Is there any merit to building this into the library? I guess judging by the "me to" :+1:'s on this post, it's not that common a need. But still, doesn't this solution feel like reimplementing something the library is already supposed to do: cancel/override concurrent actions?

Perhaps for `take(pattern)`, the `pattern()` function could be provided with more information than just the `action` to somehow allow key matching, so a whole new set of functions (`takeLatestPerKey`, `takeEveryPerKey`) isn't needed... wracking my brain to think of how that could work though.

**Comment by Andarist** [comment]
I don't think there is much need to build this into redux-saga itself. People have very different needs and we provide composable primitives (effects) that can be used to build higher-level stuff like this. A separate library with saga-helpers could be built by the community, but it's not something that we'd like to provide as part of the core.

**Comment by vincerubinetti** [comment]
I understand. Perhaps if this issue had like 100+ :+1:'s it might be a different story, but I guess people don't need it as much as I do. FWIW, this might defeat the purpose of using `redux-saga` for me, as I'm trying it out to replace and simplify my custom `takeLatest`-equivalent code, and having to do this solution will be almost as long.

Just throwing this out there. `takeLatest` (or `pattern`, more generally) could work something like this instead:

```javascript
yield takeLatest((action) => {
    // return boolean
    return action.payload.someKey === 'DESIRED_KEY';
    // OR return function
    return (otherAction) => otherAction.payload.key === action.payload.key;
  }, fetchSomeStuff);
```
The benefit would be, as I mentioned above, not having to add all these new duplicate `takeLatestPerKey` functions to the API. But I understand that this would add complexity to the API and possibly a lot of performance overhead having to run that compare function against every other action. 

But I figured I'd throw it out there as an idea, possibly for someone from the community looking to implement some kind of add-on as you said.

**Comment by Andarist** [comment]
> Just throwing this out there. takeLatest (or pattern, more generally) could work something like this instead:

It couldnt. `pattern` can already be a function. Your proposed change would change current semantics.

> FWIW, this might defeat the purpose of using redux-saga for me, as I'm trying it out to replace and simplify my custom takeLatest-equivalent code, and having to do this solution will be almost as long.

As show-cased such helper can be built and reused across the application, so if you are already a redux-saga user then this is a viable solution. If you only want to handle a single flow through redux-saga then it might be an overkill for your app. It starts to shine when you start to use it more heavily.

**Comment by vincerubinetti** [comment]
> It couldnt. `pattern` can already be a function. Your proposed change would change current semantics.

I'm not sure if you understood my suggestion. `pattern` could be a function that returns another function which then returns a boolean. So it'd basically split [bullet 2 here](https://redux-saga.js.org/docs/api/#takepattern) into two sub-bullets, one for returning a `bool` and one for returning a `func`. 

So theoretically, maybe your code could be modified to type check the return value from the `pattern` function, and if it's a `bool`, behave as it normally behaves right now, not breaking anything for existing users. But if it's a `func`, then add this new functionality.

But regardless, I still agree with you that it seems pointless to make the change in the core library.
