### ISSUE TITLE
Ignore actions

### ISSUE THREAD

**Issue by jaulz** [redux-saga/redux-saga#1951]
### Description
Is it possible to ignore certain actions? In my case I would like to sync actions across multiple tabs but I don't want them to be picked up by `redux-saga`, i.e. only the reducers should be executed.

**Comment by Andarist** [comment]
The easiest for this could be just to make separate types for those syncing actions and make reducers handle them with the same logic as original ones.

**Comment by fyodore82** [comment]
Redux-saga will take only actions which match `pattern` argument of `take`, `takeEvery`, `taleLatest`, etc, effects. So to not process some actions by redux-saga just not use `take` effect for this type of actions. Such actions will be still processed by redux reducers.

```
function* watchAction1() {
  yield takeEvery('ACTION1', function* () { 
    //process ACTION1 by saga 
  })

function reducer (state, action) {
  switch (action.type) {
    case 'ACTION1': 
    // ACION1 is also processed by reducer in addition to redux-saga
      return {
        ...state
      }
    case 'ACTION2':
    // ACTION2 processed only by reducer. Redux saga will ignore it
      return { ...state }
  }
}
```
