### ISSUE TITLE
License section missing in ReadMe documentation

### ISSUE THREAD

**Issue by MrNoddyInfy** [redux-saga/redux-saga#1958]
I see Licence section is missing at the end of ReadMe documentation. I have seen other project which have license section, should it be there for this also?

**Comment by Andarist** [comment]
PRs are welcomed.

**Comment by MrNoddyInfy** [comment]
Ok. will work on this.

**Comment by Andarist** [comment]
Closed by https://github.com/redux-saga/redux-saga/pull/1959
