### ISSUE TITLE
big fat problem with saga, miss all dispatch after the first time in ssr

### ISSUE THREAD

**Issue by lucabro81** [redux-saga/redux-saga#1963]
### Steps to reproduce
Install the project linked below, and try to reload the page twice, saga will serve data from the api only the first time, then all dispatched actions are missing. There're several log to know what's happening.
The saga is in `store/test/sagas.js`.
I've also tried to implement `takeLatest` like in the documentation [(here)](https://redux-saga.js.org/docs/api/#takelatestpattern-saga-args) without success

#### Example
[example](https://github.com/lucabro81/saga-miss-dispatch-after-the-first)

### The Expected results
well... I suppose that has to work every time, right?

### Environment information
this is the package.json content of the example

    {
        "name": "test-next-app",
        "version": "0.1.0",
        "private": true,
        "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start"
        },
        "dependencies": {
            "axios": "^0.19.0",
            "next": "9.1.1",
            "next-redux-saga": "4.0.2",
            "next-redux-wrapper": "4.0.1",
            "react": "16.10.2",
            "react-dom": "16.10.2",
            "react-redux": "7.1.1",
            "redux": "4.0.4",
            "redux-devtools-extension": "^2.13.8",
            "redux-saga": "1.1.1"
        }
    }

**Comment by Andarist** [comment]
You need to create saga middleware PER store's instance, you can't just hoist it to the top level and share it between your stores. Just move this to your `makeStore` function. Hope this helps.

**Comment by lucabro81** [comment]
It works perfectly now
