### ISSUE TITLE
[Question] Is it possible to install a specific commit from Git URL of this project, while waiting for a new release?

### ISSUE THREAD

**Issue by rszalski** [redux-saga/redux-saga#1965]
Hey, thanks for all the hard work done for `redux-saga` I use it in multiple projects and ❤️  it!

I'm, currently testing TypeScript 3.7-beta and there is 1 issue with `redux-saga@v1.1.1`:

```
$ tsc --project . --pretty
node_modules/@redux-saga/core/types/ts3.6/index.d.ts:2:33 - error TS2440: Import declaration conflicts with local declaration of 'END'.

2 import { Saga, Buffer, Channel, END, Predicate, SagaIterator, Task } from '@redux-saga/types'
                                  ~~~


Found 1 error.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The reason the above is broken is that TS 3.7 now correctly identifies clashing import conflicts, see https://github.com/microsoft/TypeScript/pull/31231.

I believe this has been fixed in https://github.com/redux-saga/redux-saga/commit/8fb79a68acad1d4f7ece36fb01bb0ce2caaff0b4#diff-b592703726a731d7374c673b13f5be31L3 with an import alias. However, I'm having trouble with installing this version of `react-redux` (probably due to this being a monorepo):

```
$ yarn add https://github.com/redux-saga/redux-saga.git#8fb79a68acad1d4f7ece36fb01bb0ce2caaff0b4                                                                                                                                      ✘
yarn add v1.19.1
[1/4] 🔍  Resolving packages...
error Can't add undefined: invalid package version undefined.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Would it be possible to release a patch version with this fix? ~Or find a workaround to actually install this commit and see if it fixes the issue first.~

EDIT: My workaround was to use https://github.com/ds300/patch-package. I tested the change locally and created a patch for `postinstall` step.

For reference, here's the patch:

```diff
diff --git a/node_modules/@redux-saga/core/types/ts3.6/index.d.ts b/node_modules/@redux-saga/core/types/ts3.6/index.d.ts
index 67657b2..51dfed5 100644
--- a/node_modules/@redux-saga/core/types/ts3.6/index.d.ts
+++ b/node_modules/@redux-saga/core/types/ts3.6/index.d.ts
@@ -1,5 +1,5 @@
 import { Action, Middleware } from 'redux'
-import { Saga, Buffer, Channel, END, Predicate, SagaIterator, Task } from '@redux-saga/types'
+import { Saga, Buffer, Channel, END as EndType, Predicate, SagaIterator, Task } from '@redux-saga/types'
 import { ForkEffect } from './effects'

 export { Saga, SagaIterator, Buffer, Channel, Task }
@@ -240,8 +240,8 @@ export interface RunSagaOptions<A, S> {
 }

 export const CANCEL: string
-export const END: END
-export type END = END
+export const END: EndType
+export type END = EndType

 export interface TakeableChannel<T> {
   take(cb: (message: T | END) => void): void
```

**Comment by Andarist** [comment]
I'll try to remember to release a new patch this week - thanks for raising this up.

**Comment by Andarist** [comment]
I was not aware that TS@3.7 is going to be released so soon - if I'd knew I would release this sooner. Anyway - I've just published a new patch version, so enjoy redux-saga@1.1.2 🚀

**Comment by ilias-t** [comment]
Seems v1.1.2 and v1.1.3 haven't been published to npm, likely due to this error in the release job: https://github.com/redux-saga/redux-saga/runs/290076134

![image](https://user-images.githubusercontent.com/4505008/68259738-87ac6680-ffef-11e9-82a0-cdf24db9d925.png)

**Comment by Andarist** [comment]
@ilias-t both were successfully published, which can be verified here https://www.npmjs.com/package/redux-saga

The failure you are seeing is from changesets which I plan to use in the future to automate releases, but it's not working correctly right now because of our docs generation tool (gitbook) depending on npm package and this causing problem. For the time being, I'm still doing releases manually with Lerna and this failure has no impact on that.

**Comment by ilias-t** [comment]
👍 sorry for the false alarm, can confirm it now appears to be published fine. Thanks for again for the quick response to this!
