### ISSUE TITLE
Cannot import CreateSagaMiddleware

### ISSUE THREAD

**Issue by lorenzorivosecchi** [redux-saga/redux-saga#1967]
### Steps to reproduce
1. `create-react-app myapp`
2. Add   `"resolutions": {  "**/**/fsevents": "1.2.9"  }` to package.json to solve this [issue](https://github.com/yarnpkg/yarn/issues/5962#issuecomment-491934806).
2. `yarn add redux-saga`

[Here](https://github.com/lorenzorivosecchi/colliderchat-client) is my repository

#### Description of the bug/issue
Cannot create middleware because function `createSagaMiddleware` cannot be imported.

#### Steps to reproduce the bug/issue
```javascript
import { applyMiddleware, createStore } from 'redux'
import { composeWithDevTools } from 'redux-devtools-extension'
import { rootReducer } from './reducers/rootReducer'
import rootSaga from './sagas/rootSaga';
import createSagaMiddleware from 'redux-saga'

export default function configureStore(preloadedState) {

    const sagaMiddleware = createSagaMiddleware();
    const middlewareEnhancer = applyMiddleware(sagaMiddleware);

    const enhancers = [middlewareEnhancer];
    const composedEnhancers = composeWithDevTools(...enhancers);

    const store = createStore(rootReducer, preloadedState, composedEnhancers);

    store.sagaTask = sagaMiddleware.run(rootSaga);

    return store
}
```

### Actual results
SagaMiddleware is null because function createSagaMiddleware doesn't exist;
My IDE alerts me that _imported module doesn't have a default export declared_.

### Environment information
**macOS** 10.15.1
**node** v12.8.0
**yarn** 1.17.3
**create-react-app** 3.1.1
**redux-saga** 1.1.1

**Comment by Andarist** [comment]
After installing your repository and adding:
```js
import createSagaMiddleware from 'redux-saga'
console.log({ createSagaMiddleware })
```
I can see:
<img width="538" alt="Screenshot 2019-11-01 at 23 18 02" src="https://user-images.githubusercontent.com/9800850/68059731-e5923300-fcfd-11e9-9620-54e311ef1451.png">

**Comment by lorenzorivosecchi** [comment]
**UPDATE**
I've managed to make the program work on my machine with the following configuration.

**nvm** 0.35.0
**node** v12.13.0
**yarn** 1.19.1

Closing the issue
