### ISSUE TITLE
Error not defined when debugging catch block in the saga

### ISSUE THREAD

**Issue by jbojcic1** [redux-saga/redux-saga#1972]
When debugging inside the saga catch block I am not able to see the error. Screenshot:

![Screen Shot 2019-11-06 at 11 29 52 AM](https://user-images.githubusercontent.com/10374826/68290806-e2de6780-0088-11ea-93aa-62270460ba91.png)

however, when I pass that error to another function, I can see it:

![Screen Shot 2019-11-06 at 11 31 23 AM](https://user-images.githubusercontent.com/10374826/68290870-fbe71880-0088-11ea-85a3-b9dca60a6184.png)

Codesandbox where you can reproduce:

https://7t2j8.csb.app/

To reproduce just open the link, open debugger and click the only button on the page.

Not sure if this is a known issue but I couldn't find it documented anywhere.

**Comment by Andarist** [comment]
It's because you are looking at the source code (using source maps), but the right pane with Scope tab is actually seeing transpiled stuff (what actually gets executed in the browser). Most probably it's somewhere in that Context object.
