### ISSUE TITLE
Error: Unable to resolve module `./io-d4ec1d36.js`

### ISSUE THREAD

**Issue by samitha9125** [redux-saga/redux-saga#1973]
### Steps to reproduce

1. Install Redux-saga 1.1.3 or any version after 1.1.1 as it seems.
2. Import redux-saga and use some effects.
2. Try to build the app.

#### Description of the bug/issue

Error occurs on build time, 

bundling failed: Error: Unable to resolve module `./io-d4ec1d36.js` from `node_modules/@redux-saga/core/dist/redux-saga-core.prod.cjs.js`: 

#### Steps to reproduce the bug/issue

1. Try to build the app.

### Actual results

Error occurs saying Unable to resolve module `./io-d4ec1d36.js` from `node_modules/@redux-saga/core/dist/redux-saga-core.prod.cjs.js`.

### Already Tried
1. Deleted package-lock.json , node_modules and reinstalled
2. Downgraded version redux version 1.1.3 to 1.1.1.

Even though I downgraded, as it seems, redux-sage require `@redux-saga/core` 1.1.1 or higher than that.

    "requires": {
        "@redux-saga/core": "^1.1.1"
    }

So automatically it updates core version to 1.1.3.

### The Expected results

Build without any issue.

### Environment information
redux-saga version 1.1.3
react-native 0.61.2

**Comment by Andarist** [comment]
This is a caching problem. I'm not sure why & how but it seems like Metro bundler used by RN is just really aggressive about some caching. You have to cleanup your caches and do a fresh install.

**Comment by AlejoSalvo95** [comment]
Im having the same issue and cleaning cache does not solve it

**Comment by Andarist** [comment]
This has been reported in https://github.com/redux-saga/redux-saga/issues/1934 and various attempts at clearing caches & restarting metro resolved this issue. Please read that issue and suggestions there. You could also try to report this to Metro bundler because this seems like a thing that shouldn't have happened in the first place.

**Comment by samitha9125** [comment]
@Andarist  Before opening this issue I went through that one and tried solutions mentioned in there as well. But nothing worked fine. Only thing worked for me was, manually editing the `node module -> redux-saga -> package.json`. I had to downgrade `redux-saga/core` version to 1.0.3 and remove the carrot symbol. 

So as it seems, this is an issue with redux-saga 1.1.3

**Comment by Andarist** [comment]
I have no idea what can be recommended to fix this on your side besides clearing caches and reinstalling. This is **not** a redux-saga issue.

The error mentions that:
> Error: Unable to resolve module ./io-d4ec1d36.js from node_modules/@redux-saga/core/dist/redux-saga-core.prod.cjs.js

So let's take a look at the content of that file - https://unpkg.com/@redux-saga/core@1.1.3/dist/redux-saga-core.prod.cjs.js . The only interesting part for us are require calls at the top:
```js
var symbols = require('@redux-saga/symbols');
var _extends = _interopDefault(require('@babel/runtime/helpers/extends'));
var _objectWithoutPropertiesLoose = _interopDefault(require('@babel/runtime/helpers/objectWithoutPropertiesLoose'));
var is = require('@redux-saga/is');
var io = require('./io-d7550be2.js');
var redux = require('redux');
var deferred = _interopDefault(require('@redux-saga/deferred'));
require('@redux-saga/delay-p');
```

As we can see here there is no reference for `require('./io-d4ec1d36.js')` in here - it's a clear indication that the bundler has some outdated info cached and it didn't even check new content of `./dist/redux-saga-core.prod.cjs.js` which references **other** file - `'./io-d7550be2.js'`

**Comment by AlejoSalvo95** [comment]
I stopped using the computer that had this issue and bought a new one. I no longer have this problem, thanks!

**Comment by Andarist** [comment]
Whatever works for you 😝

**Comment by vipullimbachiya** [comment]
Remove node modules and try installing packages using yarn instead of npm, that worked for me.

**Comment by AgustinJimenez** [comment]
> Remove node modules and try installing packages using yarn instead of npm, that worked for me.

Works for me, npm broke.

**Comment by foubei** [comment]
react-native start --reset-cache solves my issue

**Comment by vikramAfi** [comment]
installing the packages using yarn worked for me
