### ISSUE TITLE
TS typings for v1.1.1 and typescript 3.7.2

### ISSUE THREAD

**Issue by yzzhuo** [redux-saga/redux-saga#1976]
### Description of the bug/issue
After upgrading typescript from 3.6.3 to 3.7.2,  typescript show `yield select()` return type is undefined.
``` typescript
// with typescript 3.6.3, state's type is any
const state = yield select();

// in order to make the type as expectation, we do something like this
// AppState is return type of store.getState() here
const state:AppState = yield select(); 
validateIsValidUser(state.user);
```
```typescript
// while with typescript 3.7.2, state's type is undefined. If we something way like 
const state:AppState  = yield select(); 
// compile error. Type 'undefined' is not assignable to type AppState
```

### The Expected results
`yield select()` return any is acceptable. `yield select((state: AppState) => state.user)` can return the type of state.user is better, any is acceptable, but undefined is not cool.

### Environment information

- redux-saga 1.1.1
- typescript  3.7.2

**Comment by Andarist** [comment]
Could you prepare a runnable repro case for this?

**Comment by yzzhuo** [comment]
Oh, sorry it is my mistake
```
function* asyncIncrement(): IterableIterator<Effect> {
	const state:AppState = yield select(); // type error, say yield select return undefined.
	yield put(counter.actions.update('count', state.counter.count + 1));
}
```
after remove `IterableIterator<Effect>` of asyncIncrement, it is ok to return any of yield select().

**Comment by carneiror** [comment]
> after remove `IterableIterator<Effect>` of asyncIncrement, it is ok to return any of yield select().

Unfortunately I can't use this approach since this solution will break a couple of eslint rules on my project.

The only solution I found:

```ts
function* asyncIncrement(): IterableIterator<Effect> {
	const state: unknown = yield select();
	yield put(counter.actions.update('count', (state as AppState).counter.count + 1));
}
```

Which is far from perfect.

**Comment by Andarist** [comment]
We hope to address TS types in a more holistic way in the future, see discussion in https://github.com/redux-saga/redux-saga/issues/1932

**Comment by egorovsa** [comment]
You can use SagaIterator insted of IterableIterator<Effect>
```
import { SagaIterator } from '@redux-saga/core';

function* saveListOfEventTemplates(): SagaIterator {
    try {
        const eventTemplatesList: ProjectApi.EventTemplate[] = 
            yield select(ProjectSelectors.getEventTemplateList);
...
```

**Comment by TeoTN** [comment]
I think that with the latest version of TypeScript (3.8.0) one still cannot safely declare types for `yield` expressions in sagas.

What was provided is:
```
interface Generator<T = unknown, TReturn = any, TNext = unknown>
        extends Iterator<T, TReturn, TNext> {
    next(...args: [] | [TNext]): IteratorResult<T, TReturn>;
    return(value: TReturn): IteratorResult<T, TReturn>;
    throw(e: any): IteratorResult<T, TReturn>;
    [Symbol.iterator](): Generator<T, TReturn, TNext>;
}
```

And at best I think we can use that to say that an effect will be passed to a saga but `TNext` doesn't seem to allow the order in which values of various types will be passed to `.next` (resulting in `yield` expression evaluation to that value).

**Comment by Andarist** [comment]
Yes, that's right - there is a plan to introduce a workaround for this using `yield*`, but I couldn't yet find the time to push this idea forward. If you are interested in helping - please reach out to me on Twitter so we could discuss this in more detail.
