### ISSUE TITLE
Calling redux saga inside a function es6

### ISSUE THREAD

**Issue by jothreddy** [redux-saga/redux-saga#1981]
Here is the link for

https://codesandbox.io/s/react-redux-saga-example-fhr31?from-embed

In App.js file there is a button component. I am calling hi function onclick event. In this event, I want to use redux saga to call sayHello();

Say Hello!

const hi = () => {
console.log("hiiiiiiiiiiiiii");
sayHello();
};

if I using sayHello directly on button click event, code works fine. But my requirement is call it in an other function. Below is the entire file for reference.Appreciate your help.

import React, { Component } from "react";
import { connect } from "react-redux";
import * as actions from "./actions";

class App extends Component {
  render() {
    const { hello, sayHello, exampleTask } = this.props;
    return (
      <div className="App">
        <h1>Hello {hello}</h1>
        <h2>Redux-saga demo. Start editing to see some magic happen!</h2>
        <button onClick={hi}>Say Hello!</button>
        <button onClick={exampleTask}>Example Task</button>
      </div>
    );
  }
}

const hi = () => {
  console.log("hiiiiiiiiiiiiii");
  sayHello();
};

const mapStateToProps = state => ({
  hello: state.hello
});

const mapDispatchToProps = {
  sayHello: actions.sayHello,
  exampleTask: actions.exampleTask
};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(App);

**Comment by shinima** [comment]
You need to format your code before we can dig into your problem.
