### ISSUE TITLE
Redux (persistent logic)

### ISSUE THREAD

**Issue by ameyzulkanthiwar** [redux-saga/redux-saga#1987]
### NOTE: But I can not use the "persistent" logic in the code for resolving this issue.

I resolved this issue using persistent logic code. But I am not allowed to use this approach.

**Comment by khaliu** [comment]
Hi there!,
I think it does't have anything to do with Redux Sagas by the way, but could you explain why you can't use persistence in your app? Commonly the redux state is stored in localStorage, sessionStorage, Cookies, etc, and then re-hydrated. There are libraries like Redux Persist for that.

**Comment by ameyzulkanthiwar** [comment]
The size of the data is too big that's why I am not allowed to use this approach.

**Comment by ameyzulkanthiwar** [comment]
```
...
...
import { loadState, saveState }from './stores/persistent';
import { defaultEntities }from './reducers/entities';

const store = stores.initStore(loadState());
store.subscribe(() => {
  const state = store.getState();
  saveState({
    entities: {
      ...defaultEntities,
      ...state.entities, // <<--- if I add this line of code here it is resolving the issue but Not allowed to use this approch
      auth: state.entities.auth
    },
    dashboardsRecentViewed: state.dashboardsRecentViewed,
    auth: state.auth,
    ui: state.ui
  })
});

...
...
...
```

**Comment by khaliu** [comment]
In redux persist you can choose which parts of your store will be saved, even you can select nested parts of your store. Maybe that could help you. I would only save the most important parts of it, the ones that have to do with the app current state, and leave out of it the ones that can be refetched, also you can save references to that data and fetch the heavy content later.

**Comment by ameyzulkanthiwar** [comment]
I tried to go with that approach too but did not help me, but I will try again.

**Comment by ameyzulkanthiwar** [comment]
I did find a way to fix this issue by storing the data when we are in a particular component. As soon as we leave the component we are removing the content from the local storage. 

I think it is a kind of hacky way to do it but it worked for me.

Thank you for help guys.
