### ISSUE TITLE
[Server Side] my first saga fetch is not waited, but all the next ones yes

### ISSUE THREAD

**Issue by tomtom94** [redux-saga/redux-saga#1989]
I can't make a proper server side.

When I start my server and make a fetch for example `http://localhost:3000/last-movie-releases`

**The first fetch is not waited** by `toPromise()`. But ***all the other ones I do next*** are good, server side is then alright.

Just a snippet my code below. I dispatch my redux action in the class constructor. (like everybody does)
```
  store
    .runSaga(rootSaga)
    .toPromise()
    .then(() => {
      console.log('sagas complete');
      const html = ReactDOMServer.renderToString(jsx);
      const css = sheets.toString();
      res.send(
        renderFullPage(html, css, serialize(store.getState()))
      );
    })
    .catch(e => {
      console.log(e.message);
      res.status(500).send(e.message);
    });

  ReactDOMServer.renderToString(jsx);

  store.close();
```

***Is it a normal behavior ?***

PS : My saga making the fetch I am talking about starts with a `fork`, then a `fork` again, and a `call`. Exactly like in the [real-word repo](https://github.com/redux-saga/redux-saga/tree/master/examples/real-world)

I am wondering if I missed a return somewhere.

**Comment by tomtom94** [comment]
I have also opened the exact same issue (on stackoverflow)[https://stackoverflow.com/questions/59146837/redux-saga-my-first-fetch-is-not-waited-but-all-the-next-ones-yes/59147319?noredirect=1#comment104521173_59147319]

**Comment by tomtom94** [comment]
I am reporting a bug issue

Check this https://stackoverflow.com/a/59179039/10294022

**Comment by tomtom94** [comment]
Issue is now open on [loadable-component here](https://github.com/smooth-code/loadable-components/issues/473)

**Comment by theKashey** [comment]
Aaaannd it's closed as irrelevant and incorrect.
If you want to fix your case please provide more code, better just all, so it would be more clear what `jsx` is, and who (where?) triggers the saga.
