### ISSUE TITLE
takeEvery发起异步请求，会无限请求接口

### ISSUE THREAD

**Issue by nuonuonuonuoyan** [redux-saga/redux-saga#1990]
### Description
Please provide some context about the problem and some code examples if relevant.
The best way to provide an example is repository or use [Code Sandbox](https://codesandbox.io/)(there is a [prepared template](https://codesandbox.io/s/0q9yzno0zv?module=%2Fsrc%2Fsagas%2Findex.js) for Code Sandbox)

**Comment by shinima** [comment]
你需要描述地具体一些，最好可以附上相关地代码，这样我们才知道发生了什么

You need to describe your question in detail, so we can known what's going on.
