### ISSUE TITLE
Typescript error when using .next() in Jest

### ISSUE THREAD

**Issue by CosmaTrix** [redux-saga/redux-saga#1993]
Hi there,

I've been having an issue testing TS sagas with Jest. The tests behave as expected, but TS isn't happy when I pass arguments to the `.next()` functions

I have this simple redux implementation. Nothing crazy there, just a few action creators to load data from an API service.
```typescript
// reducer.ts
interface AppState {
  loading: boolean;
  data: string[];
  error?: Error;
}

// Selectors
const selectLoading = (state: AppState): boolean => state.loading;

// Action creators
const fetchDataLoading = () => ({
  type: "FETCH_DATA_LOADING"
});

const fetchDataSuccess = (payload: string[]) => ({
  type: "FETCH_DATA_SUCCESS",
  payload
});

const fetchDataError = (error: Error) => ({
  type: "FETCH_DATA_ERROR",
  error
});
```

And a simple saga to handle the API request
```typescript
// sagas.ts
const fetchDataAPI = (): Promise<string[]> => fetch("/api").then(r => r.json());

function* sagaToTest() {
  try {
    const isLoading: boolean = yield select(selectLoading);

    if (isLoading) {
      return;
    }

    yield put(fetchDataLoading());

    const data: string[] = yield call(fetchDataAPI);

    yield put(fetchDataSuccess(data));
  } catch (e) {
    yield put(fetchDataError(e));
  }
}
```

Now let's say I want to test that the saga stops when `loading` is true
```typescript
it("should stop when loading is true", () => {
  const gen = sagaToTest();

  // select loading state
  expect(gen.next().value).toEqual(select(selectLoading));
  
  // loading is true, stop here
  expect(gen.next(true).done).toBe(true);
});
```
The test passes, but I get a TS error when I pass `true` (or `fsalse`) to the `.next` function
```typescript
gen.next(true);
// TS2345: Argument of type '[boolean]' is not assignable to parameter of type '[] | [string[]]'.   Type '[boolean]' is not assignable to type '[string[]]'.
```
However, TS is fine when I pass an array of strings (which is the shape of `data` in my reducer)
```typescript
gen.next(['value 1', 'value 2']);
// All good here
```

TS tells me that this is the shape of my saga
![image](https://user-images.githubusercontent.com/3206387/70700941-d83c7100-1ccb-11ea-8704-0aa040fdf1fc.png)
So far so good, but for the last parameter, which seems to be only the return type of the `call` effect. But no trace of the `select` and the `put` ones.

I could assert the type of the generator in my test
```typescript
const gen = sagaToTest() as Generator<any, void, string[] | boolean>;
```
but that doesn't sound like a good solution. Or is it?
 
Any thoughts?

**Comment by evpozdniakov** [comment]
Same here:
![image](https://user-images.githubusercontent.com/1109345/75423913-b38c8880-590d-11ea-9d80-e067aeeb042e.png)

**Comment by kyleffoo** [comment]
@evpozdniakov have you found a solution?

**Comment by crcass** [comment]
I don't know if this is the right way to solve the problem, but here how I do it in my projects: 
```sh
// sagas.ts

const fetchDataAPI = (): Promise<string[]> => fetch('/api').then(r => r.json());

export function* sagaToTest() {
  try {
    const isLoading: boolean | undefined = yield select(selectLoading);

    if (isLoading) {
      return;
    }

    yield put(fetchDataLoading());

    const data: string[] | undefined = yield call(fetchDataAPI);
    if (data) {
      yield put(fetchDataSuccess(data));
    }
  } catch (e) {
    yield put(fetchDataError(e));
  }
}
```

```sh
// sagas.test.ts

import { cloneableGenerator } from '@redux-saga/testing-utils';
import { select } from 'redux-saga/effects';
import { sagaToTest, selectLoading } from '../sagas';

it('should stop when loading is true', () => {
  const gen = cloneableGenerator(sagaToTest)();

  // select loading state
  expect(gen.next().value).toEqual(select(selectLoading));

  // loading is true, stop here
  expect(gen.next(true).done).toBe(true);
});
```

If someone knows of a better way, I'm open to ideas.

**Comment by dimkajasons** [comment]
there is a problem here `const_ data: string[] = yield call(fetchDataAPI);`
just remove `string[]`

**Comment by neurosnap** [comment]
Closing because it looks like there’s a resolution.  Thanks!
