### ISSUE TITLE
How does redux-saga return a promise

### ISSUE THREAD

**Issue by lgf196** [redux-saga/redux-saga#1994]
saga：
    *setPagaTion({data}){
      yield put({type:'paga',data});
    }
component:
 this.props.dispatch({type: SAGA_GET_PAGATION,data});
I now want to change the dispatch to something like this:
 this.props.dispatch({type: SAGA_GET_PAGATION,data}).then(()=>{})
How do you do that???

**Comment by Andarist** [comment]
You'd have to put resolve/reject pair into the action object and call them from within your saga. This is an anti-pattern though. With saga your components should sync to the store using stat (mapStateToProps) and not through direct communication like you are proposing.

**Comment by LitileXueZha** [comment]
Some other way? i just want to use promise otherwise callback

**Comment by singleseeker** [comment]
Any update?
