### ISSUE TITLE
Whether can provide a API like race, but just waiting for success response

### ISSUE THREAD

**Issue by hurrine** [redux-saga/redux-saga#1996]
### Description
Please provide some context about the problem and some code examples if relevant.
The best way to provide an example is repository or use [Code Sandbox](https://codesandbox.io/)(there is a [prepared template](https://codesandbox.io/s/0q9yzno0zv?module=%2Fsrc%2Fsagas%2Findex.js) for Code Sandbox)

Saga provide APIs like race to send multi requests, once get one response, no matter it's resolved or rejected, will abort others. Whether can provide a similar API to realize:  when get one resolved response, then abort other requests?

**Comment by Andarist** [comment]
You can easily build this yourself using existing primitives:
```js
const raceSuccess = tasks =>
  call(function*() {
    const taskCount = Object.keys(tasks).length;
    const errorCount = 0;

    const taskHandler = task =>
      call(function*() {
        try {
          return yield task;
        } catch (err) {
          errorCount++;
          // you can implement different error handling strategy
          if (errorCount === taskCount) {
            throw err;
          }
        }
      });

    const wrappedTasks = Array.isArray(tasks)
      ? race(tasks.map(taskHandler))
      : race(
          Object.keys(tasks).reduce((acc, key) => {
            acc[key] = taskHandler(tasks[key]);
            return acc;
          }, {})
        );

    return yield wrappedTasks;
  });

```
