### ISSUE TITLE
Could getContext typing be adapted to setContext typing?

### ISSUE THREAD

**Issue by FaresAbu-Khiarah** [redux-saga/redux-saga#2000]
Hi,
I was wondering if it would be possible to change getContext's typing to be typed in the same generic way as setContext's typing is.
See: https://github.com/redux-saga/redux-saga/blob/master/packages/core/types/effects.d.ts#L1010
```typescript
export function getContext<C extends object>(prop: string): GetContextEffect<C>

export type GetContextEffect<C extends object> = SimpleEffect<'GET_CONTEXT', GetContextEffectDescriptor<C>>

export type GetContextEffectDescriptor<C extends object> = string
```

**Comment by Andarist** [comment]
What benefits would it yield?

**Comment by FaresAbu-Khiarah** [comment]
Well I forgot an important detail for it to make sense :) `prop` needs to be typed with `keyOf C` instead of plain `string`.

```typescript
export function getContext<C extends object>(prop: keyOf C): GetContextEffect<C>
```

Then you'd get the benefit of typed function argument
