### ISSUE TITLE
Two 'take' handlers for one channel

### ISSUE THREAD

**Issue by bboyair** [redux-saga/redux-saga#2003]
I tried the following code:
```
takeEvery('runTest', function*() {
                    let getChan = () => eventChannel((emitter) => {
                        setTimeout(() => emitter({ type: 'testAction' }), 4000);
                        setTimeout(() => emitter({ type: 'testAction' }), 7000);
                        return () => {}
                    });
                    let chan = yield call(getChan);
                    yield takeEvery(chan, function* () {
                        yield call(console.log.bind(console), 'handle 1');
                    });
                    yield takeEvery(chan, function* () {
                        yield call(console.log.bind(console), 'handle 2');
                    });
});
```
and expected output is
```
handle1
handle2
handle1
handle2
```
but i got
```
handle1
handle2
```
is this a bug? or am i do something wrong? (i want to get both handlers working on any action)

**Comment by auriiolym** [comment]
I've encountered the same issue (and it cost me half a week to find a solution). From the source code it seems the event channel only uses one taker for every event. Not sure whether this is an intended design choice.
I'd also prefer being able to have multiple takers per event channel, if only to signal the event channel closing to the secondary taker.

**Comment by Andarist** [comment]
>  From the source code it seems the event channel only uses one taker for every event. Not sure whether this is an intended design choice.

Yes, this is the intended design choice. While this might not work for your use case it's a perfect match for other use cases.

> I'd also prefer being able to have multiple takers per event channel,

You can do that by using `multicastChannel`.

**Comment by bboyair** [comment]
oh.. ok, tnx!
