### ISSUE TITLE
Yield delegate effect proxies for TypeScript

### ISSUE THREAD

**Issue by gilbsgilbs** [redux-saga/redux-saga#2008]
Following up the discussion we had with @Andarist [here](https://github.com/agiledigital/typed-redux-saga/pull/10#issuecomment-578075239), I'd be interested in integrating yield delegate effect proxies to this monorepo so that we could officially benefit from strong return types for sagas. Once this is done, we could start working on #1286.

I'd like to hear from you @Andarist and maybe also you @aikoven and @danielnixon on how you think it should be done. I'm a bit clueless for now. As it was already stated, we definitely want to keep the default behavior unchanged. Here are the possibilities I have considered so far:

- Just copy typed-redux-saga in this monorepo. We would then use the same shotgun technique I used in typed-redux-saga, that is to say copy-paste any change to the effects type definition and change return types to what effects actually return. This carries the same issue typed-redux-saga has: a high risk of lagging behind upstream changes or even just miss some changes. But maybe we're just happy with that, we'll just be vigilant and current type definitions don't require that much maintenance at the moment so why do we even care?
- Fork redux-saga, port every effects to yield delegate and backport changes as they come. But it's pretty clear that it would be even worse in terms of maintenance cost, and we probably wouldn't be able to stand this in the long run;
- So considering my main issue here is that I don't really want to have 3 copies of `effects.d.ts` in this repo (one for TS<3.6, one for 3.6<=TS, and one for 3.6<=TS with yield delegate), could we consider dropping one of them, namely drop support for TS<3.6? I don't think this would be that much of an issue for users given that TS3.6+ types have been around for a while now, given that the migration from one TypeScript version to another is generally not that hard, and given all the benefits new types bring? And users of a legacy version of TS could just remain on a legacy version of redux-saga, that's not a big deal to me.
- Could we consider going even further and at some point just deprecate all typings of non-yield-delegate effects? I might be wrong, but I feel like no sane TypeScript user would ever want to use raw yield effects once their delegate counterparts are properly implemented and typed. If there are any performance-related issues, it's quite easy to provide a babel plugin and a babel macro (as [already shown possible](https://github.com/agiledigital/typed-redux-saga/pull/14) in typed-redux-saga). Legacy typings for `redux-saga/effects` (and `@redux-saga/core/effects`) could still be maintained in `DefinitelyTyped` if there's any urge for it or as I already said, users could just keep their legacy apps in a legacy version redux-saga, it's not too bad.

What are your thoughts on this? Do you see any smarter or alternative approach? The solution I like the most at the moment is the 3rd, and gently but firmly moving towards 4th. WDYT?

**Comment by henrikra** [comment]
This awesome idea!

**Comment by Andarist** [comment]
> a high risk of lagging behind upstream changes or even just miss some changes. But maybe we're just happy with that, we'll just be vigilant and **current type definitions don't require that much maintenance at the moment so why do we even care**?

Exactly this - `redux-saga` seems quite complete right now. There is no real active development of it, nor there are plans of major refactors (at least on my side - I always welcome community contributions). So I don't believe this is an issue - copy-pasting is fine.

> Could we consider going even further and at some point just deprecate all typings of non-yield-delegate effects?

I'm not sure if this is something that we should ever do, especially that I'd like to keep runtime support for non-yield-delegates because they should be slightly more performant, both time & memory-wise. We can promote using typed variant though with optional babel plugin/macros for optimization purposes. Given more time my stance might of course change, but right now I don't see much need for deprecating the current ways.

---

As to the whole thing - I'm totally on board with that and I've expressed interest in it in some other issue, I just don't have time to drive this effort myself. I literally wanted to respond back to you immediately and was thinking about doing so every time, but I only have managed to actually take time to do it just now - which is 8 days later. I might be able to take some time to implement babel-related stuff as I'm pretty proficient in that area, but if you can do it as well - I would appreciate any help with that too (I assume that you would like to help with migrating `yield*` support to this repo, right?).

**Comment by Andarist** [comment]
@gilbsgilbs let me know if you would like to work on this. No pressure, I would just want to know what's the current status of this.

**Comment by gilbsgilbs** [comment]
I don't think I'll make it in the very near future because typed-redux-saga works for me right now and most importantly the time I can allocate to open-source while preserving my mental health is pretty low at the moment. It's in my plans though (if nobody picks this up before I do).

**Comment by Andarist** [comment]
Ok, no problem - I have very limited time for OSS right now as well, so I totally understand. Thanks for letting me know.

**Comment by henrikra** [comment]
@gilbsgilbs So do you recommend `typed-redux-saga` for production? I am thinking to give it a chance 🤔

**Comment by gilbsgilbs** [comment]
> So do you recommend typed-redux-saga for production? I am thinking to give it a chance thinking

I've been using it in production since https://github.com/agiledigital/typed-redux-saga/pull/10. I can only talk for my experience, but I would definitely recommend it since it really improved types safety,  quality and readability of the code base. I even caught some bugs and code-smells during the migration thanks to it.

Also, the migration was painless (a bunch of search/replace regexps and macros did 99% of the job). The code of the library itself is fairly simple since it's only made of dummy proxies, so I wouldn't worry much about bugs. I don't think the overhead of these proxies is a good argument against using typed-redux-saga as handling side-effects in global event-driven state management framework is already inherently slower by an order of magnitude. (And if the [babel-macro](https://github.com/agiledigital/typed-redux-saga/pull/14) makes it, this will be even less of an argument.)

Finally, given the discussion we just had in this issue, it is very likely that when the yield-delegate effects land in `redux-saga`'s monorepo, the migration will just consist in changing imports from `typed-redux-saga` to `redux-saga/effects/typed` (or something like this). So basically, migrating to typed-redux-saga now doesn't mean you'll have to migrate twice. Which is fortunate.

**Comment by parkerault** [comment]
@henrikra FWIW I used typed-redux-saga in two production apps at Whole Foods and it worked flawlessly. There are a few things that require a different approach (passing an action creator to `select` instead of a string, for example), but for the most part it's just a matter of replacing `yield` with `*yield`.

**Comment by SantoJambit** [comment]
I started work on this. Maybe someone can help fill in some of the missing pieces?

**Comment by neurosnap** [comment]
I investigated using this idea inside my [cofx](https://github.com/neurosnap/cofx) library and found one major snag with adopting this paradigm: testing.  How does testing work with yield delegates?  If we cannot build tests like we used to with normal generators then this solution feels untenable to me.

**Comment by neurosnap** [comment]
Closing since the resolution is to use `typed-redux-saga` instead of making changes to `redux-saga` itself.  There is also a possibility that typescript will better support our use case so I anticipate we will take that path for better typing: https://github.com/microsoft/TypeScript/issues/43632
