### ISSUE TITLE
redux saga calling function twice on single dispatch

### ISSUE THREAD

**Issue by satp8** [redux-saga/redux-saga#2016]
#### Steps to reproduce the bug/issue

1.
2.
...

#### Example
To help us to identify a problem faster, please provide repository with an example or use [Code Sandbox](https://codesandbox.io/)
(there is a [prepared template](https://codesandbox.io/s/0q9yzno0zv?module=%2Fsrc%2Fsagas%2Findex.js) for Code Sandbox)

**Comment by Andarist** [comment]
Literally no specifics about the issue were given, I have to close this.
