### ISSUE TITLE
Call effect and other generator function with typescript 3.7.2

### ISSUE THREAD

**Issue by sldone** [redux-saga/redux-saga#2018]
Hello! I have an issue with `call` effect and generator function. 
How to fix this type error? Google and stackoverflow didn't help.

### Steps to reproduce
```typescript
function* searchItemHandler(entity: SearchEntity, queryString: string): SagaIterator<void> {
  yield put(setLoading(true))
  const result: APIResponse<Product[]> = yield call(api.request.get, apiRoutes.search, {
    params: {entityType: 'PRODUCT', name: queryString},
  })
  yield put(setProducts(result.data.content))
  yield put(setLoading(false))
}

function* locationChangeHandler({payload}: LocationChangeAction): SagaIterator<void> {
  const path = payload.location.pathname
  const searchString = parseSearch(payload.location.search)
  if (!matchPath(path, {path: ROUTES.SEARCH})) return

  const searchEntity = last(path.split('/'))
  const queryString = get(searchString, 'q', '')

  if (payload.isFirstRendering) {
    yield put(setQueryString(queryString))
  }

  // string with error
  yield call(searchItemHandler, searchEntity, queryString)
}
```

### Error
```
Error:(36, 14) TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '(entity: SearchEntity, queryString: string) => SagaIterator<void>' is not assignable to parameter of type '{ context: unknown; fn: (this: unknown, ...args: any[]) => any; }'.
      Type '(entity: SearchEntity, queryString: string) => SagaIterator<void>' is missing the following properties from type '{ context: unknown; fn: (this: unknown, ...args: any[]) => any; }': context, fn
```

### Environment information

- redux-saga 1.1.3

- typescript 3.7.2

**Comment by Andarist** [comment]
This is not a complete repro case - you would have to share the issue reproduced on something like CodeSandbox so somebody could take a look at it.

**Comment by sldone** [comment]
OK, I'll add a link to codesandbox

**Comment by gilbsgilbs** [comment]
`searchEntity` in `locationChangeHandler` has type `string | undefined`, which is incompatible with type `SearchEntity` expected by `searchItemHandler`. The fact that the error is not explicit is related to how TypeScript handles the multiple function signatures for `call`. I don't think we can do much about it. You can force the generic you expect to use when calling `call` to improve the error message: `yield call<typeof searchItemHandler>(searchItemHandler, searchEntity, queryString)`.

When my sagas have parameters, I kind of prefer exposing them as effects as it usually simplifies typings:

```ts
function searchItemEffectHandler(entity: SearchEntity, queryString: string): CallEffect<void> {
  return call(function*(): SagaIterator<void> {
    // […] 
  });
}

function* locationChangeHandler({payload}: LocationChangeAction): CallEffect<void> {
  return call(function*(): SagaIterator<void> {
    […]
    yield searchItemHandler(searchEntity, queryString);
  });
}
```

The only problem with that approach is that it makes forking the saga cumbersome:

```ts
yield fork(function*(): SagaIterator<void> { yield locationChangeHandler(…); });
```

Hope this helps.

**Comment by sldone** [comment]
> `searchEntity` in `locationChangeHandler` has type `string | undefined`, which is incompatible with type `SearchEntity` expected by `searchItemHandler`. The fact that the error is not explicit is related to how TypeScript handles the multiple function signatures for `call`. I don't think we can do much about it. You can force the generic you expect to use when calling `call` to improve the error message: `yield call<typeof searchItemHandler>(searchItemHandler, searchEntity, queryString)`.
> 
> When my sagas have parameters, I kind of prefer exposing them as effects as it usually simplifies typings:
> 
> ```ts
> function searchItemEffectHandler(entity: SearchEntity, queryString: string): CallEffect<void> {
>   return call(function*(): SagaIterator<void> {
>     // […] 
>   });
> }
> 
> function* locationChangeHandler({payload}: LocationChangeAction): CallEffect<void> {
>   return call(function*(): SagaIterator<void> {
>     […]
>     yield searchItemHandler(searchEntity, queryString);
>   });
> }
> ```
> 
> The only problem with that approach is that it makes forking the saga cumbersome:
> 
> ```ts
> yield fork(function*(): SagaIterator<void> { yield locationChangeHandler(…); });
> ```
> 
> Hope this helps.

Oh, thank you! I didn't see type error related to `SearchEntity` and `string | undefined`.
And thanks for your approach.
