### ISSUE TITLE
Error: call: argument fn is undefined or null

### ISSUE THREAD

**Issue by wasif-shehzad** [redux-saga/redux-saga#2035]
```
Error: call: argument fn is undefined or null
    at check (io-1d6eccda.js:37)
    at validateFnDescriptor (io-1d6eccda.js:459)
    at call (io-1d6eccda.js:528)
    at _callee$ (common.js:146)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at next (redux-saga-core.dev.cjs.js:1161)
    at currCb (redux-saga-core.dev.cjs.js:1255)
    at redux-saga-core.dev.cjs.js:485
```
After updating the ReactNative I am getting this error.
My package.json file

{
  "dependencies": {
    "add": "^2.0.6",
    "apisauce": "^1.1.1",
    "moment": "^2.24.0",
    "native-base": "^2.13.8",
    "prop-types": "^15.7.2",
    "react": "16.13.0",
    "react-native": "0.61.5",
    "react-native-action-button": "^2.8.5",
    "react-native-animatable": "^1.3.3",
    "react-native-device-info": "^5.5.3",
    "react-native-dropdownalert": "^4.2.1",
    "react-native-facebook-account-kit": "^2.1.0",
    "react-native-fbsdk": "^1.1.2",
    "react-native-fcm": "^16.2.4",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-google-places": "^3.1.2",
    "react-native-image-picker": "^2.3.0",
    "react-native-image-progress": "^1.1.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "0.26.1",
    "react-native-maps-directions": "^1.7.3",
    "react-native-modal": "^11.5.4",
    "react-native-permissions": "^2.0.9",
    "react-native-progress": "^4.0.3",
    "react-native-reanimated": "^1.7.0",
    "react-native-screens": "^2.0.0-beta.13",
    "react-native-spinkit": "^1.5.0",
    "react-native-star-rating": "^1.1.0",
    "react-native-step-indicator": "^0.0.11",
    "react-native-swiper": "^1.6.0-nightly.5",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.11.1",
    "react-navigation-redux-helpers": "^1.0.6",
    "react-redux": "^7.2.0",
    "react-timer-mixin": "^0.13.4",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3",
    "redux-thunk": "^2.3.0",
    "socket.io-client": "^2.3.0",
    "yarn": "^1.22.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-proposal-decorators": "^7.8.3",
    "@babel/plugin-transform-flow-strip-types": "^7.8.3",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^25.1.0",
    "eslint": "^6.5.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.13.0"
  },
}

**Comment by achillesoo7** [comment]
Hey @wasif-shehzad 

This is happening because you have passed an undefined function in call(<Undefined Function>), can you please cross check it or share a code snippet.

**Comment by wasif-shehzad** [comment]
Hi, @achillesoo7  Thanks for your reply. I figured it out myself
I was using
 `call(delay, timeout )` 
but it should be like
 **`call( delay(timeout))`** .

**Comment by manudeli** [comment]
Hey @wasif-shehzad 
Did you export delay? I met this problem and found solution for that
but it's just my mistake because of not exporting from sagas.js

I think you need to test like below code as official instruction of saga
```javascript
call(delay, timeout)
```
and you just need to export delay function in sagas.js, I think

**Comment by EricWong1994** [comment]
> Hey @wasif-shehzad Did you export delay? I met this problem and found solution for that but it's just my mistake because of not exporting from sagas.js
> 
> I think you need to test like below code as official instruction of saga
> 
> ```js
> call(delay, timeout)
> ```
> 
> and you just need to export delay function in sagas.js, I think

me too~

**Comment by khanhnt2911** [comment]
yeah
