### ISSUE TITLE
Merge redux-saga-observer functionality into Redux?

### ISSUE THREAD

**Issue by rickwebiii** [redux-saga/redux-saga#2047]
At Tableau, we've gotten quite a bit of value out of redux-saga (especially using redux-saga-test plan for testing). However, we found that managing syncronicity and concurrency between sagas to be challenging.

To solve this, I wrote a library called [redux-saga-observer](https://github.com/tableau/redux-saga-observer) that allows you to use and compose the observer pattern in sagas and was wondering if it would be worthwhile to merge these back into the redux-saga project. They sit completely on top of vanilla call, take, and select effects so you could put them in another top-level folder called observers.

Syntactically, they're a bit different more complex than simple effects, using the builder pattern to create complex interactions. For example (in Typescript):
```
function* saveList(payload: SaveAction) {
   yield runWhile<State>()
        .saga(function* () {
            yield call(
                fetch,
                {
                    method: 'POST',
                    path: '/api/list',
                    data: JSON.stringify({
                        name: payload.name,
                        lines: payload.lines
                    })
                }
            );

            const res1 = yield call(someAsyncThing);
            const res2 = yield call(someOtherAsyncThing, res1);
            yield put({ type: 'SOME_ACTION', result: res2 });

        })
        .invariant('NAME_UNCHANGED', s => s.name === payload.name)
        .invariant('LINES_UNCHANGED', s => s.lines === payload.lines)
        .onViolation(function* (state, violations) {
            // If we need to dispatch some sagas, actions, or whatever for cleanup, do it here.
        })
        .run()
}
```
Here, the builder pattern sets up a saga that only runs while the underlying state's name and lines Redux items are the same as that in the passed payload. When an invariant is no longer true, the saga stops processing effects and your onViolation callback gets called so you can clean up depending on which invariants are no longer true about your redux state.

This is great for aborting a saga that's been obviated by a user action. Maybe the user deleted an item you were validating in a saga and so the saga should stop running, or maybe the document changed and the validation is not longer necessary.

You can also us this library to dispatch sagas when the Redux store changes in an interesting way (rather than take a bunch of actions, the set of which may change over time).

Another use case for this library is saga A can yield put an action that will trigger saga B. Then saga A can observerWhile until saga B's Redux store changes appear and then continue.

Right now we're publishing redux-saga-observer, as a separate MIT licensed npm package, but was wondering if it would make sense to merge this functionality into redux-saga. Let me know what you think.

**Comment by TeoTN** [comment]
Isn't that too loosely related to sagas? And isn't this a mixup of two patterns one with sagas another with observers? It seems to address very specific problems that can already be solved within sagas, for example

Dispatching on state change:
```
function* mySaga(hasStateChangedFn) {
  yield takeEvery('*', function() {
    const state = yield select();
    if (hasStateChangedFn(state)) {
      yield put(stateChanged());
    }
  });
}
```

**Comment by neurosnap** [comment]
Thank you very much for proposing this idea.

I created a new discussion asking people to submit their ideas to improve redux-saga.  If you are still interested, please go there and submit this.

https://github.com/redux-saga/redux-saga/discussions/2264

Closing this issue for now.  Thanks!
