### ISSUE TITLE
Update global context.

### ISSUE THREAD

**Issue by rumeshwick** [redux-saga/redux-saga#2050]
Is there a way to update global context using setContext and see the updated context in all the sagas. I tried doing this and i can see the updated context only in the updated saga. When getting the context in other sagas using the getContext, i cannot see the updated context. Please help.

This is related to #1426

**Comment by juzerzarif** [comment]
Don't know if this still helps but I landed here from google and ended up figuring this out after a fair bit of snooping through the issues so figured it might help someone else:

The task descriptor returned from the [`middleware.run`](https://redux-saga.js.org/docs/api/#middlewarerunsaga-args) function has a `setContext` function on it that can be called to update the context for the task. If you're using a root saga pattern mentioned [here](https://redux-saga.js.org/docs/advanced/RootSaga.html) setting the context for that task will make the context available for all child sagas.
```javascript
const sagaMiddleware = createSagaMiddleware();
// setup the redux store
// ...
const task = sagaMiddleware.run(rootSaga);

...

task.setContext({ api: {...} });
```

**Comment by neurosnap** [comment]
Closing as it looks like there was a resolution.  Thanks!
