### ISSUE TITLE
Test Saga containing while(true) loop

### ISSUE THREAD

**Issue by maxnathaniel** [redux-saga/redux-saga#2051]
### Description
Hi,

I was trying to implement full saga testing instead of step-by-step saga testing with the example provided (https://redux-saga.js.org/docs/advanced/Testing.html).

However, the `runSaga` function doesn't terminate in cases where we have infinite loops, seen in cases where a generator function contains a `while(true)` loop. And since it doesn't terminate, Jest times out with this error `Timout - Async callback was not invoked within the 5000ms specified by jest.setTimeout`.

Is anyone able to provide an example of how we can test such a generator function ?

Thank you.

**Comment by CoreyAR** [comment]
Could you move true to a variable that is reset after the completion of the loop during testing? That would prevent timeout and allow for your to test the steps of the loop
This is psuedo code but I am thinking  something like the following might work

```
let loop = true
while(loop) {
...
    if (process.env.NODE_ENV === 'testing') {
        loop = false
    }
}
```

**Comment by maxnathaniel** [comment]
Looks like a feasible solution! Thanks. I'll give it a try.
