### ISSUE TITLE
Broken links in documentation site, "Troubleshooting" section

### ISSUE THREAD

**Issue by jagretz** [redux-saga/redux-saga#2055]
#### Description of the bug/issue

Just a few broken links I found while reading through the documentation.

I found 3 broken links in documentation for `babel-plugin-redux-saga`. 

From page [6. Troubleshooting](https://redux-saga.js.org/docs/Troubleshooting.html#error-stack-for-errors-bubbling-to-root-saga-is-unreadable), click on the link text 

1. "Docs are available here" 
  - Navigates to an [empty page](https://redux-saga.js.org/packages/babel-plugin-redux-saga/). 
  - It is probably supposed to the [github project page](https://github.com/redux-saga/redux-saga/tree/master/packages/babel-plugin-redux-saga) (unless there is a "docs" site or it that I don't know about).
2. "check this example".
  - Navigates to an [empty page](https://redux-saga.js.org/examples/error-demo)
  - It probably is supposed to link to example on the [github project page](https://github.com/redux-saga/redux-saga/tree/master/packages/babel-plugin-redux-saga#example)
3. "Note: It works for testing as well"
  - Navigates to an [empty page](https://redux-saga.js.org/examples/error-demo/test/sagas.js)
  - Probably supposed to go to the error stack [demo](https://redux-saga.js.org/examples/error-demo/test/sagas.js). It should probably be [this](https://github.com/redux-saga/redux-saga/tree/master/examples/error-demo)
Visit [](), click on the link text "".

**Comment by neurosnap** [comment]
Closing as it looks like there was a resolution.  Thanks!
