### ISSUE TITLE
Possible race-condition with fork-and-watch approach

### ISSUE THREAD

**Issue by molefrog** [redux-saga/redux-saga#2059]
### Description
Hi! First of all, many thanks for the work on Redux Saga. 

I'm working on a small utility that allows to run sagas only on specific routes of the app. While the implementation was pretty straightforward I have some feelings that the code might result in some
undefined behavior, because of the order async effects are applied.

Assuming I have the following code:

```js
function* saga() {
  yield take('ONE');

  yield fork(function* () {
    // will it always receive the second action?
    yield take('TWO');
  });
}

// component
dispatch({ type: 'ONE' });
dispatch({ type: 'TWO' });
```

Can it be possible, in theory, that by the time the saga is forked and starts listening for actions, the action `TWO` is already fired and we missed it?

**Comment by ogyr** [comment]
Hi, I would think it prudent to assume that there exists indeed a race condition. 

Even if you could deduce from the current implementation that you would always either receive or miss the effect, wouldn't that be an implementation detail?

**Comment by molefrog** [comment]
Hi @ogyr and thanks for your answer. I think it's safe to close this issue, since it's been a while and I agree with you on that we could consider this an implementation detail. If I recall correctly, I did test this behaviour locally and I couldn't find any signs of a race condition.
