### ISSUE TITLE
Getting null is not a constructor when using call.

### ISSUE THREAD

**Issue by jean182** [redux-saga/redux-saga#2060]
# Description

I'm using redux saga with a library called sweet alert to display alert messages, I have a pretty basic saga that performs a request to an API after that I display an alert either with success or error messages, but I cannot use the call method with swetalert method.

My current code looks like this:

```js
function* createUserSaga(action) {
  const { user, swal } = action.payload;
  try {
    const response = yield call(createUserRequest, user);
    yield put(createUserSuccess(response));
    swal.fire("Listo!", "Creado exitosamente", "success");
  } catch (error) {
    yield put(createUserFail(error.message));
    swal.fire("Oops...", error.message, "error");
  }
}
```

I would like to use the call effect in order to perform the swal.fire but I'm receiving null is not a constructor, when I try to do it

```js
function* createUserSaga(action) {
  const { user, swal } = action.payload;
  try {
    const response = yield call(createUserRequest, user);
    yield put(createUserSuccess(response));
    yield call(swal.fire, "Listo!", "Creado exitosamente", "success");
  } catch (error) {
    yield put(createUserFail(error.message));
    yield call(swal.fire, "Listo!", "Editado exitosamente", "success");
  }
}
```

I'm pretty sure the call instruction is being sent correctly but I'm wondering why this does not work here's a screenshot using the debugger before the error happens:
<img width="206" alt="Screen Shot 2020-05-07 at 20 34 22" src="https://user-images.githubusercontent.com/7577652/81364170-4847fb00-90a2-11ea-8751-2b720235b1af.png">

And here's what it happens with the working code:
<img width="224" alt="Screen Shot 2020-05-07 at 20 33 56" src="https://user-images.githubusercontent.com/7577652/81364185-5269f980-90a2-11ea-9cb3-2090a40da5af.png">

I don't know if redux saga is the one causing the error, but I would like to know why wrapping it inside a call is not working. I would like to wrap it inside the call because it can be tested.

EDIT
I believe I solved it by calling it like this:
`yield call([swal, swal.fire], "Listo!", "Editado exitosamente", "success");`
but anyways I was wondering why I need to use that syntax, I don't have to use it when I do the first call, which triggers the request:
`const response = yield call(createUserRequest, user);`

**Comment by Andarist** [comment]
This is the basic `this` problem in JavaScript - `swal.fire` depends on `this` and thus you need to pass it to make it work, it's similar to:
```js
var c = { a: 'foo', fn() { console.log(this.a) } }
var test = c.fn
test() // oops, doesn't work
```

**Comment by jean182** [comment]
Thank you, understood, thanks for the clarification, it was super helpful
