### ISSUE TITLE
Saga not running with version 1.0(p.s. I am using minified js file through CDN)

### ISSUE THREAD

**Issue by Komal1223** [redux-saga/redux-saga#2064]
I am using minified js file for redux-saga(https://cdnjs.cloudflare.com/ajax/libs/redux-saga/1.0.0/redux-saga.umd.min.js)

**store.js**

import { Redux, ReduxSaga } from './lib/export-libs';

import sagas from './sagas';
import App from './app/index';
import APO from './app/apo/index';

const { createStore, combineReducers, applyMiddleware, compose } = Redux;

const reducers = combineReducers({
  app: App.AppReducer,
  apo: APO.APOReducer,
});
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

const sagaMiddleware = ReduxSaga.default();

const middleware = composeEnhancers(applyMiddleware(sagaMiddleware));
const store = createStore(reducers, middleware);

sagaMiddleware.run(sagas);

export default store;

**sagas.js**
import APO from './app/apo/index';

export default function* sagas() {
  yield [
    ...APO.APOSaga,
  ];
}

**apo/index.js**
import { APOSaga } from './apo-sagas';
import APOReducer from './apo-reducer';

export default {
  APOSaga,
  APOReducer,
};

**apo-sagas.js**

export function* getBusinessCriteria(action) {
try {
const response = yield call(getBusinessCriteriaApi, action.payload.snapshotId, action.payload.filterHealthFactor);

yield put({ type: constants.GET_BUSINESS_CRITERIA_SUCCESS, payload: response });
} catch (error) {
yield put({ type: constants.GET_BUSINESS_CRITERIA_ERROR, payload: error });
}
}

export function* watchGetBusinessCriteria() {
yield takeLatest(constants.GET_BUSINESS_CRITERIA_ACTION, getBusinessCriteria);
}

export const APOSaga = [
fork(watchGetBusinessCriteria),
],

With saga 1.0 version, the debugger never goes inside getBusinessCriteria function. But If I am using Redux-Saga 0.16 it works though with 0.16  version my API calls are hitting twice for a single action i.e an another issue

**Comment by Andarist** [comment]
An honest question - would you be able to give anyone help based on shared information (assuming you would be proficient in a given subject)? 

Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given. And no exact steps are given here - just random (and not even formatted!) code. There is also no clear information about what is not working.

**Comment by Komal1223** [comment]
> An honest question - would you be able to give anyone help based on shared information (assuming you would be proficient in a given subject)?
> 
> Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given. And no exact steps are given here - just random (and not even formatted!) code. There is also no clear information about what is not working.

I won't be able to share repro case in runnable form as my project is bit complex but I have explained the issue briefly.

**Comment by Andarist** [comment]
> I won't be able to share repro case in runnable form as my project is bit complex

How do you expect others to dedicate time to help you if you can't dedicate time to provide as much information as you can?

This doesn't work in v1 and has been deprecated for a long time before v1 has been released.
```js
export default function* sagas() {
  yield [
    ...APO.APOSaga,
  ];
}
```
The correct way of running multiple sagas is this:
```js
export default function* sagas() {
  yield all([
    ...APO.APOSaga,
  ]);
}
```

**Comment by Komal1223** [comment]
> > I won't be able to share repro case in runnable form as my project is bit complex
> 
> How do you expect others to dedicate time to help you if you can't dedicate time to provide as much information as you can?
> 
> This doesn't work in v1 and has been deprecated for a long time before v1 has been released.
> 
> ```js
> export default function* sagas() {
>   yield [
>     ...APO.APOSaga,
>   ];
> }
> ```
> 
> The correct way of running multiple sagas is this:
> 
> ```js
> export default function* sagas() {
>   yield all([
>     ...APO.APOSaga,
>   ]);
> }
> ```

Thanks that works. But still my API URL are hitting twice. Any suggestion?

**Comment by Andarist** [comment]
Can't give any recommendations on that one - it has to be a bug in your application logic.

**Comment by Komal1223** [comment]
Okay. Closing this issue 👍
