### ISSUE TITLE
[Example Request] More elegant way to toggle spinner state in saga

### ISSUE THREAD

**Issue by fix777** [redux-saga/redux-saga#2071]
I want to show a spinner only a request costs more than 250ms, currently, I'm using something like this:
```jsx
function* someWorker() {
  const task = yield fork(someService);

  yield delay(250);
  let loading;
  if (task.isRunning()) {
    loading = true;
    yield put(startLoading());
  }

  const response = yield task.toPromise();

  if (loading) {
    yield put(stopLoading());
  }

  if (response) {
    // ...
  }
}
```
But it's not satisfying enough. An official example would be appreciated. ❤️

**Comment by Andarist** [comment]
```js
function* someWorker() {
  const task = yield fork(someService);

  let { loading, response } = yield race({
    loading: delay(250),
    response: join(task)
  })

  if (loading) {
    yield put(startLoading());
    response = yield join(task)
    yield put(stopLoading()) // this should be avoidable as handling response should dismiss the loader anyway
  }

  // handle response
}
```

**Comment by fix777** [comment]
> ```js
> function* someWorker() {
>   const task = yield fork(someService);
> 
>   let { loading, response } = yield race({
>     loading: delay(250),
>     response: join(task)
>   })
> 
>   if (loading) {
>     yield put(startLoading());
>     response = yield join(task)
>     yield put(stopLoading()) // this should be avoidable as handling response should dismiss the loader anyway
>   }
> 
>   // handle response
> }
> ```

Thank you @Andarist 😄
