### ISSUE TITLE
How to prevent Promise rejection from reaching reducer?

### ISSUE THREAD

**Issue by janoist1** [redux-saga/redux-saga#2072]
I'm experimenting with an idea of async actions.

There's an action that has a `promise` with exposed `resolve` & `reject` in `meta`:
```js
// actions.js

export const anAction = () => {
  const deferred = {}

  deferred.promise = new Promise((resolve, reject) => {
    deferred.resolve = resolve
    deferred.reject = reject
  })

  return {
    type: 'AN_ACTION',
    meta: deferred,
  }
}
```

I've got a special version of `bindActionCreators` too:

```js
import { bindActionCreators } from 'redux'

export default (createAction, dispatch) => {
  const d = (...args) => {
    const result = dispatch(...args) || {}
    const action = args[0]

    if (action.meta?.promise) {
      result.promise = action.meta.promise
    }

    return result
  }

  return bindActionCreators(createAction, d)
}
```

In a saga:
```js
function* aSaga({ meta }) {
  const { resolve, reject } = meta
  
  if(condition) {
    resolve()
  } else {
    reject('an error')
  }
}

takeEvery('AN_ACTION', aSaga)
```

Somewhere, in a component:
```js
const { anAction } = bindActionCreators(actions, dispatch)

anAction().promise.then(() => {
  // this works when resolve is called in saga
}).catch(error => {
  // error reaching this but bubbling over and resulting an unhandled error
})
```

Question is, why does calling `reject` in saga result an unhandled error?

**Comment by khaliu** [comment]
And how is it related to ReduxSaga?

**Comment by janoist1** [comment]
@khaliu Accidentally sent question without finishing it. Have a look now.

**Comment by Andarist** [comment]
It shouldn't result in an uncaught rejection error - the problem has to be how you have written your code, saga can't interfere with this anyhow. To get more concrete help you would have to share a **runnable** repro case of your problem.

**Comment by janoist1** [comment]
The isolated example does work. However I'm experiencing the issue in a React-Native project.

**Comment by Andarist** [comment]
Well, you will have to figure it out on your own then if you are not able to create a runnable repro case.

**Comment by janoist1** [comment]
Obviously! :D 
I'll try if no luck then create a RN runnable repo for you.

Besides, what do you think about the idea of placing a promise in the meta and let the saga to handle it?

**Comment by janoist1** [comment]
I've found the issue! I was watching actions in a saga that have promise in their `meta`, chain on them without catching. It took me 3 minutes now with a fresh mind.

**Comment by Andarist** [comment]
> Besides, what do you think about the idea of placing a promise in the meta and let the saga handle it?

Conceptually it's bad - but it solves some problems with less ceremony. I've used this approach myself in the past as well 😉

**Comment by janoist1** [comment]
Cool! Rules are meant to be broken! 😅

I'm getting deep into the rabbit hole and now hiding ugly parts for instance with a custom `takeLatestAsync`:
```js

const takeLatestAsync = (patternOrChannel, saga, ...args) => fork(function* () {
  let task

  while (true) {
    const action = yield take(patternOrChannel)
    const { resolve, reject } = action.meta

    if (task) {
      yield cancel(task) // cancel is no-op if the task has already terminated
      reject(Error('Saga cancelled'))
    }

    function* wrap(fn, ...args) {
      try {
        const result = yield call(fn, ...args)
  
        console.log('WRAP result', result)
        resolve(result)
      } catch (error) {
        console.log('WRAP error', error)
        reject(error)
      }
    }

    task = yield fork(wrap, saga, ...args.concat(action))
  }
})
```
