### ISSUE TITLE
problem with redux or node modules???

### ISSUE THREAD

**Issue by F067** [redux-saga/redux-saga#2073]
i'll be insane...why do i have this error???
i cant open my app this message appeared directly after the login:

Unhandled Rejection (Error): Given action "changeLang", reducer "selectedLang" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.

please heeelp...

[reducer.pdf](https://github.com/redux-saga/redux-saga/files/4665259/reducer.pdf)

[screensource.pdf](https://github.com/redux-saga/redux-saga/files/4665260/screensource.pdf)

**Comment by Andarist** [comment]
It has nothing to do with redux-saga - your problem lies in your reducer.
