### ISSUE TITLE
Effect to avoid having duplicates saga for the same action payloads when using takeEvery

### ISSUE THREAD

**Issue by MattAgn** [redux-saga/redux-saga#2075]
Hello, here's a problem I had to solve recently in my project:

### Description
We use the following watcher pattern to fire sagas:

```typescript
function* randomSaga() {
  // do stuff...
}

function* randomWatcher() {
  yield takeEvery("SOME_ACTION", randomSaga)
  );
}
```

- Constraint 1: if two `SOME_ACTION` actions are dispatched at about the same time but with a different payload, I want to fire 2 differents sagas
- Constraint 2: if two `SOME_ACTION` actions are dispatched at about the same time but with the same payload, I want to fire only one saga. (ie. use the behaviour of `takeLeading` if the action types and payloads are the same). More precisely, I don't want to fire 2 sagas for the same action payload in a row.

I needed something in between a `takeEvery` and a `takeLeading` in a way, some kind of `takeEveryUnique`. I tried to find something like that in the redux saga effects but to no avail. Thus I made my own basic `takeEveryUnique` and wondered if it would be helpful for others. Is it the kind of helper effect that could be added to the redux-saga repo? If so, I can try to make a PR to add it.

### Possible solution
Here's the solution I work with so far:
```typescript
import { takeEvery } from 'redux-saga/effects';
import _ from 'lodash';

export function* takeEveryUnique<Fn extends (...args: any[]) => any>(actionType: string, saga: Fn) {
  let previousPayload: unknown;
  const actionMatcher = (incomingAction: { type: string; payload?: unknown }) => {
    if (
      incomingAction.type === actionType &&
      (!incomingAction.payload || !_.isEqual(previousPayload, incomingAction.payload))
    ) {
      previousPayload = incomingAction.payload;
      return true;
    }
    return false;
  };
  yield takeEvery(actionMatcher, saga);
}
```

This function could be improved by getting closer to the `takeLeading` behavior by setting the previousPayload back to null once the saga has finished running. As it is now, it won't fire a second saga for the same action payload even when the first saga has finished running.

**Comment by Andarist** [comment]
Goal of redux-saga is to moatlt provide low-level, composable effects from which you can build your own, more sophisticated, helpers. I dont really want to include things like this in the core - im really glad though that u have been able to build such high level helper on your own by using what is provided by the core 👍

**Comment by MattAgn** [comment]
Sure I understand :) Thanks for the quick reply!
