### ISSUE TITLE
How to use call effect with window.location.assign in IE11?

### ISSUE THREAD

**Issue by krutoo** [redux-saga/redux-saga#2076]
Hi. Please tell me, how can i use `call` effect with `window.location.assign` in IE11?

I was trying to use it like this:

```js
yield call([window.location, 'assign'], 'somestring');
```

But in IE11 i have error `Invalid calling object`:

![image](https://user-images.githubusercontent.com/13140130/83485160-e1aad700-a4bf-11ea-97a7-a8e0231dae59.png)

**Comment by Andarist** [comment]
This should work:
```js
yield call([window.location, window.location.assign], 'somestring');
```

**Comment by krutoo** [comment]
@Andarist No, this code produces same error. 
Looks like that problem is because in IE11 calling `window.location.assign[bind/call]` is not allowed

**Comment by Andarist** [comment]
Then it looks like you should do this:
```js
yield call((...args) => window.location.assign(...args)], 'somestring');
```

**Comment by krutoo** [comment]
Yeah, it my current solution too.

> Then it looks like you should do this:
> 
> ```js
> yield call((...args) => window.location.assign(...args), 'somestring');
> ```

Yeah, its my current solution too. Just wanted to know about more elegant solutions, well...
