### ISSUE TITLE
High version "react native", After packaging, "yield call" cannot be used, but "call" can be used, "yield put" can also be used. no problem in the test environment

### ISSUE THREAD

**Issue by showtan001** [redux-saga/redux-saga#2080]
### Steps to reproduce
After packaging, "yield call" cannot be used, but "call" can be used, "yield put" can also be used. no problem in the test environment(debug environment). 
However, everything is normal when react native@0.58.6 or lower (including after packaging the apk).
Is this a react-native reason or does redux-saga need to adapt to the higher version of react-native (0.62.2)?
### Environment information

        "dva": "^2.6.0-beta.20",（"redux-saga": "^0.16.2"）
        "react": "^16.8.4",
        "react-dom": "^16.8.4",
        "react-native": "0.62.2",

**Comment by showtan001** [comment]
![image](https://user-images.githubusercontent.com/32892347/84340260-dbf57580-abd2-11ea-9ffe-6b0213fb0d16.png)

**Comment by Andarist** [comment]
I'm afraid this is a problem with your environment, I'm not a React Native user and I can't help you much.

**Comment by showtan001** [comment]
@Andarist ok, thanks!
