### ISSUE TITLE
How to make context work for a subset of sagas?

### ISSUE THREAD

**Issue by hbarcelos** [redux-saga/redux-saga#2082]
### Description

I have the following use case:
- Users in my app can choose different providers to which they will connect in order to retrieve data.
- Users can switch the provider anytime they want.

These providers are set in a React-centric API that returns a bunch of things. I'm interested in a prop called `library` which is a non-serializable object that I can access this way:

```js
const { library } = useGetProvider();
```

Whenever the user changes the provider, `library` becomes a new instance. I setup the following hook in an `<Initializer/>` component:

```js
React.useEffect(() => {
  dispatch(changeLibrary(library));
}, [library]);
```

This makes the dispatched `changeLibrary` non-serializable, but since it's not processed by any reducer, it's fine.

I need `library` instances in different slices of my application, because that's where I'll get my data from.

I was hoping to be able to use the `setContext`/`getContext` effects like this:

```js
// sliceA.js
function* changeLibrarySaga(action) {
  const library = action.payload;
  yield setContext({ libraryForSliceA: library });
}

function* watchChangeLibrary() {
  yield takeEvery('CHANGE_LIBRARY', changeLibrarySaga);
}

// Using this in other sagas

function* getDataSaga(action) {
  const library = yield getContext('libraryForSliceA');
  library.getMyData(action.payload.something);
}

function watchGetData() {
  yield takeEvery('GET_DATA', getDataSaga);
}
```

I'd have a `changeLibrarySaga` in different slices of my application.

However, I educated myself a bit about context and the snipped above won't work because context only work for parent/children relationships between sagas. Since the sagas above are independent and forked only by the root saga, I'm out of luck.

The alternatives I see currently:
1. Put `library` in the payload of the dispatched actions, but that will make most of my actions non-serializable.
2. Store a global reference to `library` and inject it as the  `context` option of the `sagaMiddlewere`; whenever `library` changes, I mutate the global reference. This is bad because the update could happen in the middle of a running saga, which would cause inconsistent behavior.

Is there any other way I could rewire a given set of sagas whenever `library` is changed? 

I was thinking in the possibility of creating a higher order saga that would react to that change, cancel all pending tasks bound to the current `library` and then register the new sagas bound to the new context. However, I'm having a hard time translating this into code.

**Comment by hbarcelos** [comment]
So after a lot of struggle, I've put this together:

```js
export function runSagasWithContext(sagas, { createContext = ({ library }) => ({ library }) } = {}) {
  return function* watchChangeLibrary() {
    let tasks = [];

    try {
      while (true) {
        const action = yield take(`${changeLibrary}`);
        const { library } = action.payload;

        if (tasks) {
          yield cancel(tasks);
        }

        // If there's no library, don't re-spawn the tasks
        if (!library) {
          tasks = [];
          continue;
        }

        const context = yield call(createContext, { library });
        yield setContext(context);

        tasks = yield all(
          sagas.map(saga =>
            spawn(function* sagaWrapper(...args) {
              let isCancelled = false;

              while (!isCancelled) {
                try {
                  yield call(saga, ...args);
                } catch (err) {
                  console.warn('Error in saga:', err);
                } finally {
                  if (yield cancelled()) {
                    console.info('Cancelling saga:', saga.name);
                    isCancelled = true;
                  }
                }
              }
            })
          )
        );
      }
    } finally {
      if (yield cancelled()) {
        /**
         * We need to perform this cleanup because `tasks` array was `spawn`ed,
         * not `fork`ed, so we need to cancel them explicitly.
         *
         * @see { https://redux-saga.js.org/docs/advanced/ForkModel.html#detached-forks-using-spawn }
         */
        yield cancel(tasks);
      }
    }
  };
}
```

This apparently works, but I'm willing to get some feedback.

**Comment by Andarist** [comment]
`getContext` is not reactive as it cannot be. Saga is a state machine that is always paused in a particular state (represented by `yield`), so if you are pass `yield getContext()` we can't really magically go back and restart things automatically - this is just impossible.

So your intuition to listen for an action that represents a change is good. Looking briefly at your code snippet it overall looks good, I just have 3 generals remarks about it:
- I don't think that you need to separate `runSagasWithContext` and `watchChangeLibrary`, seems like both could be collapsed to a single generator
- not sure why you are using `spawn` over `fork` if you want to cancel those `tasks` anyway if your watcher gets canceled
- there is no point in accepting and forwarding `args` in your `spawn` as you don't pass any extra arguments there anyway

**Comment by hbarcelos** [comment]
Hi @Andarist , thanks a lot for the feedback.
I've used basic sagas in the past, but now I'm stumbling upon more complex use cases for them, so I'm struggling a little bit.

> - I don't think that you need to separate `runSagasWithContext` and `watchChangeLibrary`, seems like both could be collapsed to a single generator

If I don't have a wrapper function, I'm not sure how I would be able to create multiple context-aware sagas. Currently I have this in my slice file:

```js
// features/tokens/tokensSlice.js
export const sagas = {
  tokensMainSaga: runSagasWithContext([debounceCheckAllowanceSaga, watchApproveSaga], {
    createContext: ({ library }) => ({
      tokenApi: createTokenApi({ library }),
    }),
  }),
};
```
The pattern above is repeated in other places.

Then I import them in the root saga roughly like:
```js
// store/rootSaga.js
import { sagas as tokensSagas } from '~/features/tokens/tokensSlice';
import { sagas as transactionsSagas } from '~/features/tokens/transactionsSlice';

export default function* rootSaga() {
    const sagas = [
        ...Object.values(tokensSagas),
        ...Object.values(transactionsSagas)
    ];

    yield all(sagas.map(saga => fork(saga));
}
```
Do you have any suggestions?

> - not sure why you are using spawn over fork if you want to cancel those tasks anyway if your watcher gets canceled
> - there is no point in accepting and forwarding args in your spawn as you don't pass any extra arguments there anyway

Yeah, I got confused about the errors bubbling up in `fork`s, but I'm already handling them in the wrapper saga, so there's no need to use `spawn`.
About the `args`, you're right. Also there should be no need for args in any of the `sagas` I pass down to this because they are usually watchers, so they don't take arguments anyway.

**Comment by Andarist** [comment]
> If I don't have a wrapper function, I'm not sure how I would be able to create multiple context-aware sagas.

You don't have to create a factory function to capture those arguments, you can just encapsulate this into an effect:

```js
export const sagas = {
  tokensMainSaga: call(runSagasWithContext, [debounceCheckAllowanceSaga, watchApproveSaga], {
    createContext: ({ library }) => ({
      tokenApi: createTokenApi({ library }),
    }),
  }),
};
```

That would require a change in how you later start them though, so maybe it doesn't suit your use case right now. It's possible though. If you want to keep forking those at a higher level then your solution is OK.

**Comment by hbarcelos** [comment]
Well, that looks like dark sorcery to me :rofl:

What would I need to do to start that later?

**Comment by Andarist** [comment]
Just `yield` that.
```js
yield sagas.tokensMainSaga
// or
yield all([sagas.tokensMainSaga, /* more /*])
```

Effects in `redux-saga` are not magic anyhow, they are just objects that encode what kind of thing you would like to do, but if you do not yield them immediately they are still objects and you can pass them around to yield at a later point in time.

**Comment by hbarcelos** [comment]
That's awesome... Thank's a lot @Andarist
