### ISSUE TITLE
npm test failed with fresh checkout

### ISSUE THREAD

**Issue by bayareabear** [redux-saga/redux-saga#2083]
#1782 # Steps to reproduce

Checkout master
run yarn
run npm test
failed with:
shopping-cart-example: internal/modules/cjs/loader.js:327
shopping-cart-example:       throw err;
shopping-cart-example:       ^
shopping-cart-example: Error: Cannot find module '/Users/xzhang3/Documents/git/redux-saga/node_modules/redux-saga/dist/redux-saga-effects-npm-proxy.cjs.js'. Please verify that the package.json has a valid "main" entry
shopping-cart-example:     at tryPackage (internal/modules/cjs/loader.js:319:19)
shopping-cart-example:     at Function.Module._findPath (internal/modules/cjs/loader.js:703:18)
shopping-cart-example:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
shopping-cart-example:     at Function.Module._load (internal/modules/cjs/loader.js:862:27)
shopping-cart-example:     at Module.require (internal/modules/cjs/loader.js:1042:19)
shopping-cart-example:     at require (internal/modules/cjs/helpers.js:77:18)
shopping-cart-example:     at Object.<anonymous> (/Users/xzhang3/Documents/git/redux-saga/examples/shopping-cart/test/sagas.js:3:1)
shopping-cart-example:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
shopping-cart-example:     at Module._compile (/Users/xzhang3/Documents/git/redux-saga/node_modules/pirates/lib/index.js:99:24)
shopping-cart-example:     at Module._extensions..js (internal/modules/cjs/loader.js:1176:10) {
shopping-cart-example:   code: 'MODULE_NOT_FOUND',
shopping-cart-example:   path: '/Users/xzhang3/Documents/git/redux-saga/node_modules/redux-saga/effects/package.json',
shopping-cart-example:   requestPath: 'redux-saga/effects'

**Comment by Andarist** [comment]
You need to `npm run build` before running the whole suite of tests.

**Comment by bayareabear** [comment]
I tried npm run build first then run test, it failed:
   ✕ should be compatible with es2015 preset regenerator (26ms)
    ✕ should be compatible with env preset regenerator (125ms)
    ✓ should handle passed sourcemaps (23ms)
    ✓ should build absolute path if useAbsolutePath option = true (5ms)
  babel7
    ✓ attach source to declaration (24ms)
    ✓ attach source to export declaration (7ms)
    ✓ attach source to export declaration when processed with regenerator (234ms)
    ✓ should wrap yielded call expression (no name check) (8ms)
    ✓ should wrap method call (6ms)
    ✓ shouldn't wrap delegate (3ms)
    ✓ should handle nested structures (12ms)
    ✓ should handle function expression (5ms)
    ✓ should handle simplest expression (6ms)
    ✓ should handle expressions in object properties (6ms)
    ✓ should be compatible with es2015 preset regenerator (22ms)
    ✓ should be compatible with env preset regenerator (54ms)
    ✓ should handle passed sourcemaps (15ms)
    ✓ should build absolute path if useAbsolutePath option = true (4ms)

  ● babel6 › attach source to export declaration when processed with regenerator

    expect(received).toBe(expected) // Object.is equality

    Expected: "\"use strict\";

    var _marked =
    /*#__PURE__*/
    regeneratorRuntime.mark(test1),
        _marked2 =
    /*#__PURE__*/
    regeneratorRuntime.mark(test2);

    function test1() {
      return regeneratorRuntime.wrap(function test1$(_context) {
        while (1) {
          switch (_context.prev = _context.next) {
            case 0:
              _context.next = 2;
              return Object.defineProperty(foo(1, 2, 3), \"@@redux-saga/LOCATION\", {
                value: {
                  fileName: \"test/fixtures/declaration-regenerator/source.js\

**Comment by bayareabear** [comment]
Any help is appreciated

**Comment by Andarist** [comment]
Hm, not sure what's wrong - I have run tests successfully just now 🤔 Could you list your environment info (node, OS, npm, whatever you can think of, versions)?

**Comment by bayareabear** [comment]
I updated all those versions. now it is failing:
lerna ERR! yarn run test stderr:
Error: /Users/xzhang3/Documents/git/redux-saga/packages/core/types/ts3.6/effects.test.ts:289:1
ERROR: 289:1  expect  TypeScript@next: Expected an error on this line, but found none.

    at /Users/xzhang3/Documents/git/redux-saga/node_modules/dtslint/bin/index.js:190:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xzhang3/Documents/git/redux-saga/node_modules/dtslint/bin/index.js:5:58)
error Command failed with exit code 1.
error Command failed with exit code 1.

**Comment by Andarist** [comment]
> ERROR: 289:1 expect TypeScript@next: Expected an error on this line, but found none.

This might be a problem in our tests - new TS version might behave different from the older ones. I'm afraid that I won't have time to investigate this any time soon, any help would be much appreciated.

**Comment by bayareabear** [comment]
I am glad to help but I am new to react. I spent a few hours but could not figure out how to fix it

**Comment by bayareabear** [comment]
Is there a way to fix the TS version so that I can get around the problem for now?

**Comment by Andarist** [comment]
Maybe by using `localTs` option with dtslint, but I'm not sure:
https://github.com/microsoft/dtslint/blob/8847473ceb7fffd4e065e99929e2b16ea071b619/src/index.ts#L99
