### ISSUE TITLE
Type definition is old or missing -  import using 'redux-saga/effects', showing Module '"redux-saga/effects"' has no exported member 'all'.

### ISSUE THREAD

**Issue by nithincvpoyyil** [redux-saga/redux-saga#2084]
Hi Team,

Trying to import `'all'` from **'redux-saga/effects'** and it showing no exported member.   However, **'@redux-saga/core/effects'** is working. I did not install any type definitions seperately, it is installed along with **redux-saga**. In documentation, code examples are using imports from **'redux-saga/effects'**. 

![redux  saga import issue image](http://nithincv.in/redux-issue.png)

**My Observations:**

-  `redux-saga/effects` is referring to **@types/redux-saga/effects.d.ts** , which has`  type definitions for redux-saga 0.9.1`.

- In **node_modules/redux-saga/effects.d.ts**, it has the correct type definitions
  `export * from '@redux-saga/core/effects'`

 **Environment information :**
 - VSCode Editor
-  Packages Info:
```
        "redux": "^4.0.5",
        "redux-saga": "^1.1.3",
        "typescript": "^3.6.2"

info Direct dependencies
└─ redux-saga@1.1.3
info All dependencies
├─ @redux-saga/core@1.1.3
├─ @redux-saga/deferred@1.1.2
├─ @redux-saga/delay-p@1.1.2
├─ @redux-saga/is@1.1.2
├─ redux-saga@1.1.3
├─ typescript-compare@0.0.2
├─ typescript-logic@0.0.0
└─ typescript-tuple@2.2.1
```

**Comment by Andarist** [comment]
You should not be using `@types/redux-saga` at all - this probably confuses your IDE.

**Comment by nithincvpoyyil** [comment]
I guess, that might be the issue @Andarist , I have deleted all the node modules & yarn lock file and reinstalled again. Now it is showing definitions from '`~/redux-saga/effects.d.ts`'

**Comment by joegasewicz** [comment]
@Andarist solution worked for me, thanks.

**Comment by Scorpovi4** [comment]
@types/redux-saga is 8 y.o and deperecated, watch package before integrate it.
