### ISSUE TITLE
How to change the amount of forked tasks waiting for channels dinamically?

### ISSUE THREAD

**Issue by hemavidal** [redux-saga/redux-saga#2089]
What the documentation says is that we can have a queue implemented easily with Channels:
```javascript
import { channel } from 'redux-saga'
import { take, fork, ... } from 'redux-saga/effects'

function* watchRequests() {
  // create a channel to queue incoming requests
  const chan = yield call(channel)

  // create 3 worker 'threads'
  for (var i = 0; i < 3; i++) {
    yield fork(handleRequest, chan)
  }

  while (true) {
    const {payload} = yield take('REQUEST')
    yield put(chan, payload)
  }
}

function* handleRequest(chan) {
  while (true) {
    const payload = yield take(chan)
    // process the request
  }
}
```
I noticed that we can determine the number of concurrent tasks and in the sample it was 3 multiple tasks running in parallel:
```javascript
for (var i = 0; i < 3; i++) {
    yield fork(handleRequest, chan)
  }
```
However,

How can I change the number 3 to another number dynamically without cancel the tasks running in the fork?

If I want to increase the 3 to 5 it's easy, it's just add other forks whenever I want, but what about to decrease this number without lost the running tasks?

**Comment by Andarist** [comment]
You would have to implement a more sophisticated logic:
1. have a saga responsible for managing worker pool
2. create a channel for it
3. pass this channel to each forked saga
4. notify the manager saga about worker state changes (`processing: boolean`)
5. knowing about processing status of your workers you could quite easily implement logic in which you would "wait" for a worker to complete before shutting it down

**Comment by hemavidal** [comment]
Great, thanks.
I will check if I can get a solution for it.

**Comment by hemavidal** [comment]
Alright, I got a solution:

- Firstly I've given an id for each fork task because I haven't found a way to retrieve the fork id in the current task:
```javascript
let taskCounter = 0
const forks = {}
...
const chan = yield call(channel)
for (let i = 0; i < queueSize; i += 1) {
      taskCounter += 1
      const taskID = taskCounter
      forks[taskID] = {
        isRunning: true,
        fork: yield fork(doSomething, { chan, taskID }),
      }
    }
```
- After that I've created a saga to watch the REMOVE_CHANNEL_TASK action:
The action:
```javascript
export const REMOVE_CHANNEL_FORK = 'REMOVE_CHANNEL_FORK'

export const removeChannelFork = ({ taskID }) => ({
  type: REMOVE_CHANNEL_FORK,
  taskID,
})
```
The saga:
```javascript
function* watchFinishFork() {
  while (true) {
    const { taskID } = yield take(REMOVE_CHANNEL_FORK)
    forks[taskID].isRunning = false
  }
}
```
- And finally I implemented the main saga to watch the actions conditioned to the isRunning:
```javascript
function* doSomething({ chan, taskID }) {
  while (true) {
    const payload = yield take(chan)
    yield executeTheSomething(chan, payload)
    if (!forks[taskID].isRunning) {
      delete forks[taskID]
      break //this means that the fork will finish its execution
    }
  }
}
```
So thank you for the guidance @Andarist 👏
