### ISSUE TITLE
What do you think about peerDependencies

### ISSUE THREAD

**Issue by shapkarin** [redux-saga/redux-saga#2092]
Hello. Maybe this repo had this before in codebase but I didn't [find](https://github.com/redux-saga/redux-saga/issues?q=is%3Aissue+peerDependencies) any issue except one about babel. 
What do you think about to move redux to the [peerDependencies](https://docs.npmjs.com/files/package.json#peerdependencies)?

**Comment by Andarist** [comment]
It's not a good fit for us - we don't actually treat Redux as a peer dep. All you need is a conforming interface (which Redux provides) - you can integrate `redux-saga` with non-Redux systems just fine. We only use `redux` as a dependency for its `compose` function. We could just copy-paste it here and remove that dependency altogether, but I don't see much value in that as while we don't require Redux for anything else, it is a usual companion to `redux-saga`. So being able to share `compose` implementation allows us to save few bytes for most of our consumers.

**Comment by shapkarin** [comment]
@Andarist redux has a nice code and also compose function. Not sure that it will save a lot of bundle size.
