### ISSUE TITLE
Not Found - GET https://registry.npmjs.org/@redux-saga%2fcore - Not found

### ISSUE THREAD

**Issue by rk2609** [redux-saga/redux-saga#2102]
### Description
Please provide some context about the problem and some code examples if relevant.
The best way to provide an example is repository or use [Code Sandbox](https://codesandbox.io/)(there is a [prepared template](https://codesandbox.io/s/0q9yzno0zv?module=%2Fsrc%2Fsagas%2Findex.js) for Code Sandbox)

**Comment by ArTo1s** [comment]
The same problem while installing through yarn.
`error An unexpected error occurred: "https://registry.yarnpkg.com/@redux-saga/core/-/core-1.1.3.tgz: Request failed \"404 Not Found\"".`

**Comment by Andarist** [comment]
Must be a registry issue, this module has been published over 9 months ago: https://www.npmjs.com/package/@redux-saga/core?activeTab=versions
