### ISSUE TITLE
Cancelling async iterators

### ISSUE THREAD

**Issue by Mr-Wallet** [redux-saga/redux-saga#2104]
Since redux-saga doesn't directly support async iterators, I was wondering how we can deal with third-party dependencies that provide an async iterator as their interface, and specifically how we may cancel iteration before the iterator is exhausted.

The standard way to do stop an asyncIterator is to simply `break` out of the `for await (... of ...)` loop that's consuming it. However the standard way to cancel tasks in redux-saga is to give it a `cancel(task)` effect, which will run the `return` method on the saga generator. This would mean that in each iteration of the `for await` loop, we'd need to have a `yield` that allows redux-saga to intercede with the cancellation. However, as previously noted, redux-saga doesn't support `async function*`, so there's no obvious way to feed that cancellation into the loop.

I was wondering if there was any recommended best practice for dealing with this cancellation problem - preferably one that doesn't involve a convoluted dance with a global state-management system. Please note that in my use case, it is imperative that the iterator stop execution; it's not sufficient to leave the loop detached and continue to iterate while redux-saga ignores it.

**Comment by neurosnap** [comment]
Thanks for posting this issue!  I’d love to read thoughts from others on this issue.  I have not specifically had this issue but if I’m reading this correctly, I think it is something redux-saga should address.

**Comment by neurosnap** [comment]
Circling back to this issue.  I'd like to dive deeper into the problem.  Could you share some code that illustrates the issue with async iterators?

**Comment by Mr-Wallet** [comment]
[Octokit](https://octokit.github.io/rest.js/v19#pagination) has async iterators available for pagination. This gives us a super clean pattern:
```js
const getAllPages = async (octokit, request) => {
  let results = [];

  for await (const response of octokit.paginate.iterator(request)) {
    results = results.concat(response.body);
  }

  return results;
};
```
OK, so, that's a good start, though it would be nice to stream pages one at a time into redux... but, let's say the next priority for this is to get it into redux-saga, and to make it cancellable. If the user backs out of this view, we might fetch a _bunch_ of pages the user doesn't care about. But the question is, what's the best way to make it as simple as `yield cancel(paginateTask)` or closing a channel? It's definitely not enough to leave it running as a detached task; that's bandwidth, and API rate limit, that the user will not appreciate wasting.

Ideally I could just plug the function provided by Octokit into redux-saga, and use `cancel` to just terminate the async iterator instantly, but I can't `yield call(asyncGeneratorFn)` to get a task because that's unsupported. I could... make an eventChannel and have `emitter(END)` act as a substitute for `cancel(task)`? But then I need to figure out how to make `getAllPages` shut down the moment something comes into the channel (and, as an async function, it cannot be turned into a redux-saga-compatible generator). I can use Redux to... set an abort flag that gets checked every loop? But it seems weird to use global state, if I happen to be in a situation where the caller can pass around a Task and not have to involve Redux at all, if only I had a Task to cancel.

Oh, and it would be even more ideal to abort the generator instantly in case I want to use a `finally` block, and not wait for the current request to complete or fail, just so I don't have to worry about race conditions with my cleanup code... so even having `getAllPages` be in charge of when it checks for its own abort signal is not ideal, and if I want to solve that, things start getting even... weirder.

So what would be considered the best saga-fu here?

**Comment by Andarist** [comment]
As far as I know, there is no way to impact the async iterator while it is "in flight". The item has to resolve first before you can do anything about it. For that reason, I wouldn't recommend iterating through it using `for-await-of` loop but rather doing something like that:
```ts
function* getAllPages(octokit, request) {
  let results = [];

  for (const responseP of octokit.paginate.iterator(request)) {
    const { value, done } = yield responseP
    if (done) {
      break;
    }
    results = results.concat(value.body);
  }

  return results;
};
```

Note that I don't have any practical experience with async iterators and I could be wrong about this.

**Comment by Mr-Wallet** [comment]
Neither do I, which is why I missed such an obvious solution 🤦 

I am too accustomed to having redux-saga solve everything for me in this project. Yes, that gives a very clean and abortable saga. 👍
