### ISSUE TITLE
add support for native es modules in Node

### ISSUE THREAD

**Issue by rifler** [redux-saga/redux-saga#2105]
### Description
Native ES modules were landed in [node@12.7.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#2019-07-23-version-1270-current-targos) (see [proposal-pkg-exports](https://github.com/jkrems/proposal-pkg-exports/)).

I created [small repo](https://github.com/rifler/node-esm-example/) with interested for me packages like express, lodash, redux, redux-saga, etc - and try to run app in esm mode.

By default, there are many errors, but they easily fixed by `npm run patch`.

Some packages need to fix their source, but redux-saga packages need to fix only package.json. You can see example of fixes here - https://github.com/rifler/node-esm-example/blob/master/patches/packageJsonConfigs.js

**Comment by rifler** [comment]
Also, it would be nice to create dual commonjs/es module - https://nodejs.org/dist/latest-v12.x/docs/api/esm.html#esm_dual_commonjs_es_module_packages

but here we should rename all `*.cjs.js` files to `*.cjs`, otherwise node throws error

**Comment by Andarist** [comment]
ESM is a dangerous thing that often cannot be shipped within the current major version of a library. Each library is different though so this should be carefully evaluated here - maybe there is a way to make CJS and ESM entrypoints coexist here but from my experience, there probably isn't. 

In a way, I would probably put this aside until React ships its ESM - cause this might be a final push for the React community to drop CJS and bump major versions everywhere.

**Comment by neurosnap** [comment]
Hard to argue with that and I like the general approach: wait for `react` to adopt ESM before we try to do it inside `redux-saga`.

**Comment by neurosnap** [comment]
Closing this issue because it's unclear when we plan to support ESM because we want to maintain backwards compatibility.
