### ISSUE TITLE
Correct Flow type for generator returning all effect?

### ISSUE THREAD

**Issue by AndrzejSala** [redux-saga/redux-saga#2109]
Because in console I have seen warning about using `all` with arrays of effect, I have transformed this one:

```
export default function* mappingSagas(): Generator<any, any, any> {
  yield [
    watchFetchCategoryTargeting(),
    watchFetchDevices(),
    watchFetchMarketStates(),
  ];
}
```
To this one:

```
export default function* mappingSagas(): Saga<void> {
  yield all([
    watchFetchCategoryTargeting(),
    watchFetchDevices(),
    watchFetchMarketStates(),
  ]);
}
```
Unfortunatelly Flow is highlighting the content of all effect with errors like:
`Cannot call `all` with array literal bound to `effects` because in array element: Either property `@@redux-saga/IO` is missing in  `Generator` [1] but exists in  `TakeEffect` `

What is a proper flow typing for function which return all effect? `: Saga<void>` works fine with other effects, but with `all` there is something wrong.

**Comment by Andarist** [comment]
I'm afraid that we do not maintain Flow types for Redux-Saga, they are community-driven and live outside of this repository.
