### ISSUE TITLE
How to create a package with rollup using redux-saga

### ISSUE THREAD

**Issue by jacqueswho** [redux-saga/redux-saga#2113]
I am trying to create a package that exports a redux saga generator function, when I test via npm link, all seems great. However when I publish the package and import from the package I get an error. It can't seem to find my generator functions. Using rollup to package the code. Is there something wrong that I am doing to export the code? I have tried numerous settings with rollup? Please could you guide or tell me what I am doing wrong

below is some of the code from my [package](https://github.com/trixtateam/trixtaJS) I am trying to create.

## `setupTrixtaSaga.js`
```JS
import 'regenerator-runtime/runtime';
import { put, fork, all, takeLatest, takeEvery } from 'redux-saga/effects'
import {
  REACTION_RESPONSE,
  SUBMIT_ACTION_RESPONSE_SUCCESS,
  CHANNEL_JOINED_FIELDS,
  SUBMIT_ACTION_RESPONSE,
  UPDATE_TRIXTA_ROLES,
  SUBMIT_REACTION_RESPONSE,
  SUBMIT_ACTION_RESPONSE_FAILURE,
  SUBMIT_REACTION_RESPONSE_FAILURE,
  SUBMIT_REACTION_RESPONSE_SUCCESS,
} from '../constants';
import {
  updateAction,
  updateReaction,
  updateTrixtaError,
  updateReactionResponse,
  updateActionResponse,
  updateLoadingErrorStatus,
} from '../reduxActions';
import { getChannelName, isNullOrEmpty } from '../../utils';

/**
 * Check the roles returned for the user, join channels for these roles
 *
 * @param {Object} params
 * @param {Object} params.data
 * @param {Array} params.data.roles
 * @returns {IterableIterator<*>}
 */
export const checkTrixtaRolesSaga = function* checkTrixtaRolesSaga({ data }) {
  const roles = get(data, 'roles', []);
  try {
    if (!isNullOrEmpty(roles)) {
      yield all(
        roles.map((role) =>
          fork(checkLoggedInRoleSaga, {
            role,
          })
        )
      );
    }
  } catch (error) {
    yield put(updateTrixtaError({ error: error.toString() }));
  }
};


/**
 * Attempts to connect to roleChannel
 * @param role
 * @returns {IterableIterator<*>}
 */
export const checkLoggedInRoleSaga = function* checkLoggedInRoleSaga({ role }) {
  if (role) {
    const channelTopic = getChannelName({ role });
    yield put(getPhoenixChannel({ channelTopic }));
  }
};

export const setupTrixtaSaga = function* setupTrixtaSaga() {
  yield takeLatest(UPDATE_TRIXTA_ROLES, checkTrixtaRolesSaga);

}
```

## import from package in another project
```JS
import { setupTrixtaSaga, updateTrixtaRoles } from '@trixta/trixtajs';

export default function* defaultSaga() {
yield all([setupTrixtaSaga()]);
}


```

**Comment by Andarist** [comment]
For starters - you can't export things like this: https://github.com/trixtateam/trixtaJS/blob/370dce190f6d60392edbf10ac8dff239e71a8f55/src/index.js#L8 . You just shouldn't mix ESM and CJS module formats like this, it won't work in multiple scenarios. Please refactor this to named exports and check things then.

**Comment by jacqueswho** [comment]
@Andarist thank you for the suggestion. Will try that

**Comment by jacqueswho** [comment]
@Andarist 

I had look at your amazing [article](https://developers.livechat.com/updates/how-to-create-javascript-libraries-in-2018-part-2) and took some ideas on the rollup config. Your package is really a must have in all redux applications. I really want to thank you for your amazing work. I made the suggestions you did, [changes](https://github.com/trixtateam/trixtaJS/blob/master/src/index.js) .  [rollup changes](https://github.com/trixtateam/trixtaJS/blob/master/rollup.config.js) . Seems to be working now, but I am not sure what I did that made it work. Do you mind seeing if I am doing something wrong regarding the packaging?

Maybe you should as part of your examples you already have include build examples with webpack, rollup and so forth.

**Comment by Andarist** [comment]
You should write it like this:
```js
export { trixtaReducer, setupTrixtaSaga, trixtaActionTypes };
export const utils = { getChannelName, getMessageFromError, isNullOrEmpty };
```

`module.exports` is a CJS construct, if you author your modules in ESM then you should stick to ESM syntax. Rollup doesn't even understand natively CJS so it thinks `module.exports` is just some random global thing - it doesn't touch it unless your use its CJS plugin, but it should only be used to process external modules (the ones in `node_modules`) and not the code you have authored.

**Comment by jacqueswho** [comment]
> You should write it like this:
> 
> ```js
> export { trixtaReducer, setupTrixtaSaga, trixtaActionTypes };
> export const utils = { getChannelName, getMessageFromError, isNullOrEmpty };
> ```
> 
> `module.exports` is a CJS construct, if you author your modules in ESM then you should stick to ESM syntax. Rollup doesn't even understand natively CJS so it thinks `module.exports` is just some random global thing - it doesn't touch it unless your use its CJS plugin, but it should only be used to process external modules (the ones in `node_modules`) and not the code you have authored.

@Andarist Can you also write it like this
```JS
export * from './React/constants';
```

I see I am using the commonjs as well
```JS
import commonjs from '@rollup/plugin-commonjs';

const createConfig = ({ input, output, external, env }) => ({
  input,
  output: {
    sourcemap: true,
    name: OUTPUT_NAME,
    globals: GLOBALS,
    ...output,
  },
  external: makeExternalPredicate(external === 'peers' ? peerDeps : deps.concat(peerDeps)),
  plugins: [
    env === 'production' && terser(),
    json({
      // All JSON files will be parsed by default,
      // but you can also specifically include/exclude files
      exclude: ['node_modules/**'],

      // for tree-shaking, properties will be declared as
      // variables, using either `var` or `const`
      preferConst: true, // Default: false

      // specify indentation for the generated default export —
      // defaults to '\t'
      indent: '  ',

      // ignores indent and generates the smallest code
      compact: true, // Default: false

      // generate a named export for every property of the JSON object
      namedExports: true, // Default: true
    }),
    commonjs(),
    filesize(),
    nodeResolve({
      jsnext: true,
    }),
    babel({
      exclude: 'node_modules/**',
      babelHelpers: 'runtime',
    }),
    env &&
      replace({
        'process.env.NODE_ENV': JSON.stringify(env),
      }),
  ],
  onwarn(warning, warn) {
    if (warning.code === 'UNUSED_EXTERNAL_IMPORT') {
      return;
    }
    warn(warning);
  },
});
```

**Comment by Andarist** [comment]
> @Andarist Can you also write it like this

If it would result in the same structure to be exported, then yeah - sure. I haven't tracked your imports/exports to know if it would, but this should be possible.

> I see I am using the commonjs as well

Yes, but as mentioned - it really should only be responsible for handling your node_modules that might contain some CJS-only modules. And it's also only useful if you plan on bundling some dependencies into your bundle. So it's somewhat useless for you right now as you only create cjs & bundles but with all of your dependencies listed as externals (as you should - when bundling a library code). It's useful when bundling for UMD target - which usually contains the code of your dependencies in it. UMDs are sort-of relicts of the past, I would not create them - unless you know that you need them for some reason (like allowing your consumers to load them using <script> tag from a CDN). Or when bundling an application code when you want to pull all of your dependencies into the bundle because you need them at runtime. When bundling library code you want to leave your dependencies out of your bundles so they can be resolved by your consumers and their code can be shared if your consumer happens to depend on a specific package multiple times (like for example if they depend on `lodash` and your package, and your package depends on `lodash` as well - you want a single `lodash` to be resolved and shared at runtime and not duplicated because you have bundled it into your code).
