### ISSUE TITLE
Handling local state update after sage completion.

### ISSUE THREAD

**Issue by anish01stha** [redux-saga/redux-saga#2114]
What is the best way to do something in the component such as updating the local state or redirecting to other routes after dispatching an action? As an example, my component has a local state for the visibility of a modal.

const [ isVisible, setVisible ] = useState(false);
const hideModal = () => {setVisible(false)}

What is the proper way to implement something like:

```
dispatch(postArticleAction(articleData)).then(() => hideModal());
dispatch(postArticleAction(articleData)).then(() => redirectTo("/some_other_route"));

```

with sagas like:
```
function* postArticleWorker ({articleData}) {
  try {
    const response = yield call(articlePostEndpoint, articleData);
    const data = yield call(response.json);
    yield put('ARTICLE_REQUEST_SUCCESS', data);
  } catch (err) {
    yield put('ARTICLE_REQUEST_FAILED');
  }
}

function* saga () {
  yield fork(takeEvery, 'REQUEST_ARTICLE', postArticleWorker);
}
```
I have referenced issue #697 and want to confirm if the solution present there is still the best ones and if https://github.com/Chion82/redux-wait-for-action is recommended, which I do not want to use because reintroducing callbacks and promises after using redux-saga beats its purpose.

Looking through StackOverflow, redirecting in the saga itself is best and it does solve for that use case. However, something like updating the local state after a saga is executed successfully, what would be the best way to do it in saga except moving my entire local state like isVisible into redux which is absurd. 

So what would be the best way?

**Comment by acodesmith** [comment]
You could have a `status` in redux which saga updates

```
yield put('ARTICLE_REQUEST_SUCCESS', data);
```

The reducer:

```
case ARTICLE_REQUEST_SUCCESS:
  return {
  ...state,
  status: STATUS_ENUM.SUCESS // i.e. 'success'
 }
```

In the component:

```
const { status } = useSelector(getArticle);

useEffect(() => {
  if(status === STATUS_ENUM.SUCCESS){
    hideModal();
    redirect('/some-other-route');
  }
}, [status])
```

**Comment by neurosnap** [comment]
Closing as it looks like there was a resolution
