### ISSUE TITLE
Typescript yield select() with root type

### ISSUE THREAD

**Issue by mfoncho** [redux-saga/redux-saga#2117]
### Description
Are there any options for augmenting the yielded result of  ```select()```
without casting each time like ``` (yield select()) as RootState``` 
but  more cleaner like
```js
/*
 *    interface IRootState { 
 *        sliceOne: ISliceOne;
 *        sliceTwo: ISliceTwo;
 *    }
 */
function * root({type, payload}){
    // Slice in this case both
    // slices would already have
    // their slices type inferred like
    // was declared as
    // select(): Iterator<IRootState> 
    const { sliceOne, sliceTwo } = yield select();
}

**Comment by neurosnap** [comment]
Hi!  No, this is a limitation with typescript.  See issue here: https://github.com/microsoft/TypeScript/issues/43632

Closing for now.  I’m going to create a single GH issue and pin it specifically for this problem because there has been a little bit of traction on it in TS.
