### ISSUE TITLE
How do i implement a loop of API Call ? It must be sequential

### ISSUE THREAD

**Issue by LouisJS** [redux-saga/redux-saga#2119]
### Description

I'd like to implement a list of POST call **sequentially**, not in parallels with redux-saga

Currently i'm doing :

```
/** Update Single Property */
function* sagaUpdateProperty(accountId, property) {
  try {
    const response = yield call(
      MyApi.updateProperty,
      accountId,
      property,
    );
   const { stuff, anotherStuff } = response;
    yield put(updateProperty({ stuff, anotherStuff }));
  } catch (error) {
     // handle Error
  }
}

/** Update Several Properties  */
function* sagaUpdateProperties(action) {
  try {
    const { accountId, properties } = action.payload;
    const effects = properties.map((property) =>
      call(sagaUpdateProperty, accountId, property),
    );
    yield all(effects);
  } catch (error) {
  // handles error
    );
  }
}
```

But i have noticed that the calls were executed in parallels which troubles my API.
So i need to :
 - Execute one API Call
 - Dispatch the changes
 - ... repeat ...

What should i replace the ```yield all(effects);``` with ?

**Comment by khaliu** [comment]
Hi, `all` is for executing the effects in parallel, https://redux-saga.js.org/docs/api/#alleffects---parallel-effects

what you want to do, you can achieve it by simple iterating over the properties. with `for` or `forof`

like

```
for (const property of properties) {
  yield call(sagaUpdateProperty, accountId, property)
}
```

you can do a put inside the for, for each result, or you can store the results and do the same put as the `Single Property` example that you provided.

**Comment by LouisJS** [comment]
Thank you.

I've tried map, forEach. It didn't work. `For of` does the job.
I have no idea why 😂

Thank you very much 🥇

**Comment by khaliu** [comment]
That's because you are executing the `yields` outside the generator function, `map, foreach` have a function as callback not a generator.
