### ISSUE TITLE
Please declare a license

### ISSUE THREAD

**Issue by hcldan** [redux-saga/redux-saga#2122]

**Comment by akuji1993** [comment]
There is a license right in the top level folder. It's MIT.

**Comment by r3nya** [comment]
https://github.com/redux-saga/redux-saga/blob/master/LICENSE

**Comment by hcldan** [comment]
Thank you
 
----- Original message ----- From: "Andrew M." <notifications@github.com> To: redux-saga/redux-saga <redux-saga@noreply.github.com> Cc: Dan Dumont <ddumont@pnp-hcl.com>, Author <author@noreply.github.com> Subject: Re: [redux-saga/redux-saga] Please declare a license (#2122)Date: Mon, Sep 28, 2020 12:18 PM 
 
https://github.com/redux-saga/redux-saga/blob/master/LICENSE

**Comment by r3nya** [comment]
Btw, @hcldan please close this issue if everything is ok now. 😉
