### ISSUE TITLE
yield call in map sequentially

### ISSUE THREAD

**Issue by klimnikova** [redux-saga/redux-saga#2126]
### Description
Hi! I want to use yield call in map and I saw examples how do it  such as:
`export function* normalizeFileData(files) {
  return yield all(files.map(file => call(loop(file.id))));
}`

But calls will be in parallel, but I want to do calls sequentially, how can I resolve this problem?

**Comment by Andarist** [comment]
Assuming that your given code works and the only problem is to make those calls sequential then this should work:
```js
export function* normalizeFileData(files) {
    const results = []
    for (let file of files) {
        results.push(yield call(loop(file.id)))
    }
    return results
}
```

**Comment by klimnikova** [comment]
Thanks a lot!
