### ISSUE TITLE
Dispatch action from saga immediately

### ISSUE THREAD

**Issue by Avizura** [redux-saga/redux-saga#2127]
Hi, is it possible to dispatch action from saga immediately? 
Currently `runPutEffect` "schedules the put in case another saga is holding a lock"

**Comment by Andarist** [comment]
No, you shouldn't have to think about scheduling. What's your use case for wanting this to happen "immediately"?

**Comment by Avizura** [comment]
Sorry for late response @Andarist . My case is that I am handling fetching data for each page (url) in redux-saga.

Let's assume user clicks on a button -> click handler dispatches SOME_ACTION -> redux-saga watcher in its turn dispatches CALL_HISTORY_METHOD action from some react-router-redux library

How it works now:
```
1. clickHandler() { dispatch({ type: SOME_ACTION })  }
2. REDUX_SAGA_WATCHERS[SOME_ACTION] {  yield put({ type: CALL_HISTORY_METHOD })  }
3. inside redux-saga: exec(put({ type: CALL_HISTORY_METHOD })) task
4. reactRouterReduxMiddleware() { 
      if (action.type === CALL_HISTORY_METHOD) {
        history[action.payload.method](action.payload.args) 
      }
    }
5. history.listen((location, action) => dispatch({ type: LOCATION_CHANGE }))
6. **for some reason put({ type: CALL_HISTORY_METHOD }) task hasn't finished yet, so put({ type: LOCATION_CHANGE }) task is added to the queue**
7. rendering new page
8. put({ type: CALL_HISTORY_METHOD }) task is finished -> exec(put({ type: LOCATION_CHANGE })) task
9. REDUX_SAGA_WATCHERS[LOCATION_CHANGE] { yield fetchDataForNewUrl() }
```

 How I want it to be:
I want fetchDataForNewUrl() to be called before rendering the new page

My original question was wrong. The question now is why exec(put({ type: CALL_HISTORY_METHOD })) doesn't run synchronously (there are no redux-saga watchers for this action)
