### ISSUE TITLE
Configuration of the store when using Redux Toolkit

### ISSUE THREAD

**Issue by EdmundsEcho** [redux-saga/redux-saga#2128]
Hello --

I've been using sagas for a few years now.  All great.  I recently updated my redux capacity using the Redux Toolkit.  I'm getting Errors... My only questions are as follows: 

1. Is is bad practice to have sagas mutate state?  
2. If I want to "hide" what sagas is doing from the Redux Toolkit, is there a way to do so in the store/toolkit configuration?  
3. Sagas is the last item in my middleware array.  Should that still be the case when using the redux toolkit?

Thanks to anyone with experience here.

\- E

**Comment by Andarist** [comment]
> Is is bad practice to have sagas mutate state?

Yes. But the same can be said about Redux itself, so this leads me to a belief that maybe there is some missing context here, for this question?

> If I want to "hide" what sagas is doing from the Redux Toolkit, is there a way to do so in the store/toolkit configuration?

Sorry, I'm not familiar with the Toolkit - I'm not sure what you would like to hide and from where.

> Sagas is the last item in my middleware array. Should that still be the case when using the redux toolkit?

That would be probably best, although Saga should work at any position in the middleware chain - the only difference is at what stage actions are passed to it which might matter in some specific setups.

**Comment by EdmundsEcho** [comment]
The toolkit tracks state mutation between dispatches... Here is the link: https://redux-toolkit.js.org/introduction/quick-start

The saga that I'm working on now uses `select`; something I generally try to avoid.  I chose to keep it this way because the saga schedules  an async error report using a large portion of the store's state. Small changes in state lead to a large scan of the state.  

So, did I somehow mutate state while selecting some portion of state required to generate the report?  ... something I'm figuring out now.  That would be bad.

What I do know: I dispatch an event with the report upon success... that would not be an issue.  

\- E

**Comment by EdmundsEcho** [comment]
I still have not resolved the issue.  I have confirmed that when I toggle on/off the saga's capacity to `take` an offending `action`, the immutability error goes away. 
```js
/**
 * Configuration that controls when to add error validations
 * to the queue.
 */
const errorCheckSchedulingActions = [
  TYPES.UPDATE_FILEFIELD, // <<< e.g., comment this out, and this action works fine
  TYPES.UPDATE_IMPLIED_MVALUE,
  TYPES.UPDATE_WIDE_TO_LONG_FILES,
  TYPES.TOGGLEFILE,
  TYPES.GET_FILEMETA_SUCCESS,
];

function* _report() {
  const state = yield select();
  try {
    const report = yield call(reportHvsErrorsP, state);  // <<< state read-only 
    return report;
  } catch (error) {
    yield put(reportHvsTimedout(error));
  }
}

function* _scheduleValidation(action) {  // <<<
  console.log('%cfiles.sagas received an action', debug.color.orange);
  console.dir(action);

  const [report, timedout, nextRequest] = yield race([
    call(_report),
    take(TYPES.REPORT_HVS_TIMEDOUT),
    take(errorCheckSchedulingActions),
  ]);

  if (typeof report !== 'undefined') {
    yield put(reportHvsErrorsActionCreator(report));
  } else if (typeof timedout !== 'undefined') {
    /* just cancel others in the race */
  } else if (typeof nextRequest !== 'undefined') {
    yield call(_scheduleValidation);
  }
}

// Watchers which are exported and combined in sagas.
// **NOTE** anything exported from this file will be executed by src/initSagas
export function* watchForFilesFetch() {
  yield takeLatest(TYPES.GET_READDIR_START, _fetchDirectory);
}

export function* watchForMetaFetch() {
  yield takeEvery(TYPES.TOGGLEFILE, _toggleFile);
}

export function* watchForUpdateField() {  // <<<<
  yield takeEvery(errorCheckSchedulingActions, _scheduleValidation);
}
```

The redux error claims I have mutated "inside a dispatch".  
```
Uncaught Error: Invariant failed: A state mutation was detected inside a dispatch, in the path: files.headerViews./Users/edmund/Desktop/data/s_vSmall.csv.fields.0.levels. Take a look at the reducer(s) handling the action {"type":"files/UPDATE_FILEFIELD","filename":"/Users/edmund/Desktop/data/s_vSmall.csv","fieldIdx":3,"key":"null-value","value":"xyzchange"}. (https://redux.js.org/troubleshooting#never-mutate-reducer-arguments)
```

My understanding is that it's ok for sagas to read state to augment the payload of an action.  Redux uses the state from which the saga read from, to then update it with the payload per the spec in the relevant reducer (in this case, files.reducer).

Any ideas?

\- E

**Comment by EdmundsEcho** [comment]
## Solved

In my reducer I sent a partially cloned object to a function that mutates that object
`inputA -> updated inputA`.  The object was referencing state.  Once I completely cloned the object... I was "good to go".

This all said, where I position sagas in the middlewares chain: given I use sagas to re-start backend tasks following a rehydrate from my persist reducer, how should I think about sequence?

\- E
