### ISSUE TITLE
redux-saga function stuck at yield call

### ISSUE THREAD

**Issue by mkd63** [redux-saga/redux-saga#2129]
### Description

I have the following redux-saga function.

```
function* getStockPrices({ payload: ticker }) {
  try {
    console.log("price running", ticker);
    const response = yield call(fetchStockPrice, ticker);
    console.log(response, "stock saga");
    if (response.status >= 200 && response.status < 300) {
      yield put(stockPriceSuccess(response.data, response.status));
    } else {
      throw response;
    }
  } catch (error) {
    console.log(error);
  }
}
```

The 1st console log works and prints. Then, yield call calls then following function

```
async function fetchStockPrice(ticker) {
  const response = await axios.get("/api/stock-extra/stock-price-data", {
    params: { ticker: ticker },
  });
  console.log(response);
  return response;
}
```

Response is logged from above function. But, after this, the console.log with stock saga is not printed.

So, the function is stuck at yield call.

Please help with this problem.

**Comment by cheersmas** [comment]
have you tried removing the async and using it as a regular function?

**Comment by UniKylin** [comment]
1. `fetchStockPrice ` is a asynchronous method, response time is uncertain.
2. `call` effect is blocking calls.

**Comment by mkd63** [comment]
> have you tried removing the async and using it as a regular function?

yes i have but without async, I dwas getting just an unresolved promise in the log statement. after adding async, I was atleast getting the data in log.

**Comment by mkd63** [comment]
> 1. `fetchStockPrice ` is a asynchronous method, response time is uncertain.
> 2. `call` effect is blocking calls.

@UniKylin so how to stop call from bloacking it ?

**Comment by cheersmas** [comment]
your syntax looks fine to me, maybe I am missing something.
let me know if I am wrong or if it works for you. But can you try this?

```
function* getStockPrices({ payload: ticker }) {
  try {
    console.log("price running", ticker);
    let response = yield apply(axios, axios.get, ["/api/stock-extra/stock-price-data", {
       params: { ticker: ticker },
    }]);
    response = response.json();
    if (response.status >= 200 && response.status < 300) {
      yield put(stockPriceSuccess(response.data, response.status));
    } else {
      throw response;
    }
  } catch (error) {
    console.log(error);
  }
}
```

**Comment by UniKylin** [comment]
> > 1. `fetchStockPrice ` is a asynchronous method, response time is uncertain.
> > 2. `call` effect is blocking calls.
> 
> @UniKylin so how to stop call from bloacking it ?
To invoke [`cancel`](https://redux-saga.js.org/docs/advanced/TaskCancellation) method to stop it. have a try
