### ISSUE TITLE
How to deal with async generators?

### ISSUE THREAD

**Issue by hbarcelos** [redux-saga/redux-saga#2130]
Hey guys, I have a more of a conceptual problem I've been struggling with in the past couple of days.

I have to subscribe to N infinite event streams and react to the events occurring in them. Those are standard Node-like event-emitters.
I also have a facade API which should merge those N event streams together into a single one.
My initial thought was to convert the subscription into an async generator:

```js
  async function* subscribe({ fromBlock = 0, toBlock = 'latest', filter = {} } = {}) {
    let res;
    let rej;
    let promise = new Promise((resolve, reject) => {
      res = resolve;
      rej = reject;
    });

    const subscription = linguo.events.allEvents({ fromBlock, toBlock, filter });
    subscription
      .on('data', event => {
        res(event);

        promise = new Promise((resolve, reject) => {
          res = resolve;
          rej = reject;
        });
      })
      .on('error', err => {
        rej(err);
        promise = new Promise((resolve, reject) => {
          res = resolve;
          rej = reject;
        });
      });

    while (true) {
      try {
        const event = await promise;
        yield event;
      } catch (err) {
        console.warn(`Canceling event subscription for contract ${linguo.options.address}`, err);
        break;
      }
    }

    subscription.unsubscribe();
  }
```

Then to combine the multiple `subscribe()` calls, I've found this [merge](https://repeater.js.org/docs/repeater#repeatermerge) operator from the `repeatable` library:

```js
// Proxy handler for the `subscribe` method:
  const subscribeHandler = {
    apply: (target, thisArg, args) => {
      const apiInstances = Object.values(apiInstancesByAddress);

      return Repeater.merge(apiInstances.map(instance => instance.subscribe.apply(instance, args)));
    },
  };
```

Then I happily wrote my saga:

```js
export async function* subscribeSaga(action) {
  const { fromBlock, toBlock, filter } = action.payload ?? {};

  const linguoApi = yield getContext('linguoApi');
  const subscription = yield call([linguoApi, 'subscribe'], { fromBlock, toBlock, filter });
  for await (const evt of subscription) {
    console.log('>>>', evt);
  }
}
```

Only to find out then that `redux-saga` does not  support async generators :/

I thought of maybe using `eventChannel`, but it plays well with callback-based APIs, couldn't figure out a way to consume async generators (not sure if it's even possible).

The "easy" route here would be to expose the N event emitters and wrap them in a channel, but this is exposing internals which the API facade should take care of.

Any ideas?

**Comment by Andarist** [comment]
I might be missing something but looking at the implementation of the `subscribe` - it doesn't look right. What I mean is that it doesn't include any buffering, nor it clears the promise after consuming it - wouldn't this very often lead to duplicated items being consumed?

**Comment by hbarcelos** [comment]
Yeah, I created just a rough draft of what I wanted to do, it's not even near ready to be used in the wild.
I was just trying to validate this idea I had.

Is there an easy way to consume async generators in `redux-saga`? If not, I'll probably abandon this approach.

**Comment by Andarist** [comment]
> Is there an easy way to consume async generators in redux-saga? If not, I'll probably abandon this approach.

Ofc there is! 😉 Take a look here:
https://codesandbox.io/s/focused-waterfall-iwwsu?file=/src/index.js

I'm not sure why do u want to use async generators though - unless it's an API that you don't control. If you control it then you would probably be better without them.

**Comment by hbarcelos** [comment]
Awesome, thank's a lot.

> I'm not sure why do u want to use async generators though - unless it's an API that you don't control. If you control it then you would probably be better without them.

I guess you're right, I ended up creating an event channel directly from the event emitters for this specific use case, but it's good to know I can consume async generators if I need it some day.

Thank you very much.
