### ISSUE TITLE
How Can I Create Multiple Calls Side Effects

### ISSUE THREAD

**Issue by BuangHosen** [redux-saga/redux-saga#2131]
#### Objective
I want to display snackbar status for each request.

#### Sample code
```
function* uploadSnackbar(status) {
  if (status) {
    yield put(
      snackBar({
        message: "Successfully update documents",
        variant: SNACKBAR.SUCCESS
      })
    );
  } else {
    yield put(
      snackBar({
        message: "One or more documents is failed to upload ",
        variant: SNACKBAR.ERROR
      })
    );
  }
}

export function* updateSupplierDocuments(api, { payload }) {
  const response = yield all(
    payload.map(document =>
      call(api.updateSupplierDocuments, document)
    )
  );

  yield uploadSnackbar(
    response.every(({ ok }) => ok === true)
  );

  return response;
}
```

**Comment by Andarist** [comment]
You have not asked any question here that I could answer...

**Comment by BuangHosen** [comment]
My apology Mr @Andarist , 

What I mean is currently my implementation was render the **SUCCESS** snackbar if all response is true, otherwise return false. But is there any possibility to render all the message snackbar depends on the response? For an example, I have 3 array, which return 2 true and 1 false, then the snackbar should display 2 **SUCCESS** and 1 **FAILED**

**Comment by Andarist** [comment]
1. should a snackbar be displayed right away after a single response comes in? or should all requests be awaited and then multiple snackbars should pop up?
2. should snackbard be grouped? as in - with "2 SUCCESS and 1 FAILED" do u want to display 2 or 3 snackbars?

**Comment by BuangHosen** [comment]
Thanks for your response,

For the first question, the snackbar will automatically display once we got a response back.
Second question, for that case perhaps we can render 3 snackbar in sequence.

 Indeed I have tried various ways but didnt solve the problem. Again thanks for your help.

**Comment by Andarist** [comment]
Then just move your actions to a saga responsible for a single call:
```js
function* updateSupplierDocument(document) {
    const response = yield call(api.updateSupplierDocuments, document)

    if (response.ok) {
        yield put(
            snackBar({
                message: "Successfully updated document",
                variant: SNACKBAR.SUCCESS
            })
        );
    } else {
        yield put(
            snackBar({
                message: "Document has failed to upload",
                variant: SNACKBAR.ERROR
            })
        );
    }

    retrun response
}

export function* updateSupplierDocuments(api, { payload }) {
  const response = yield all(
    payload.map(document =>
      call(updateSupplierDocument, document)
    )
  );

  return response;
}
```

**Comment by BuangHosen** [comment]
Great! I got your idea, thanks very much sir. I really appreciated it.
