### ISSUE TITLE
How Tasks get cleaned?

### ISSUE THREAD

**Issue by TeoTN** [redux-saga/redux-saga#2133]
### Description
I wasn't able to find any documentation on how tasks are cleaned - let's say I have fork over generator that runs infinite loop, if I don't cancel the fork task, does it ever get cleaned? Is there any cleanup phase for the saga middleware, when this would get cancelled?

```
function* neverEndingStory() {
  while (true) {
    ...
  }
}

function* mySaga() {
  const task = yield fork(neverEndingStory); // When store / middleware is destroyed, does the task leak?
}
```

**Comment by Andarist** [comment]
This should answer your question: https://redux-saga.js.org/docs/advanced/ForkModel.html#cancellation

The whole subtree gets cleaned when you cancel a particular task - this includes canceling a "root" task. So you need to cancel the task returned from `const task = middleware.run(saga)`

**Comment by TeoTN** [comment]
Does the cancellation have to be in another saga though? I wonder if I could clean up the root saga when a root component gets unmounted

**Comment by Andarist** [comment]
What happens under the hood is that we call the `iterator.return()`. So even if it's blocked on some step it will be terminated - each saga is canceled on its own. If you need to clean up some resources manually then you need to use the `cancelled()` effect in the `finally` block.

As to the rest - I would kinda need to know how you set up things and how do u want to handle this to advise more.
