### ISSUE TITLE
setTimeout doesn't work in android background 

### ISSUE THREAD

**Issue by MaxToyberman** [redux-saga/redux-saga#2137]
### Steps to reproduce
1. create a task that will run in background.
2. add delay (uses setTimeout under the hood)
3. saga will hang

#### Description of the bug/issue
saga delay hangs when used in background,  

#### Solution 
use `BackgroundTimer.setTimeout` instead of default timeout

### Environment information

- redux-saga 1.1.3
- react-native
- android

**Comment by Andarist** [comment]
`BackgroundTimer.setTimeout` this is not available in all supported environments. You should be able to wrap this API very easily into a saga-compatible one. As this is an issue with React Native rather than with `redux-saga` I'm going to close this issue
