### ISSUE TITLE
Get all currently running forks from running saga

### ISSUE THREAD

**Issue by mikabytes** [redux-saga/redux-saga#2141]
### Description
Hi! This has been bugging me out for a while and I'm thinking there must be some reasonable way to deal with it. Thanks for helping out!

Let's say I have this:

```
function* main() {
   yield* multiple()

  yield take("someCondition")
  return "somevalue"
}

function* multiple() {
   yield fork(someOtherLongRunningFunction)
   yield fork(someThirdEverLastingFunction)
}
```

When "someCondition" type has been submitted the "somevalue" should be returned. For this to happen the forks first need to be cancelled. Is there some way I can query ReduxSaga for a list of currently running forks?

The example is trivial, and I'm aware I could wrap the whole thing in a fork and then cancel that single fork. However, my real-world case is much more complex. There are multiple running forks, started in multiple places, and keeping track of all the forks is getting messy. 

Note: I only want to cancel all subforks, not the currently running saga itself (because that would also cancel the parent which is waiting for the result to be returned).

**Comment by Andarist** [comment]
Why not doing this?
```js
function* main() {
  const task = yield fork(multiple)

  yield take("someCondition")
  yield cancel(task)
  return "somevalue"
}

function* multiple() {
   yield fork(someOtherLongRunningFunction)
   yield fork(someThirdEverLastingFunction)
}
```

**Comment by mikabytes** [comment]
Good question. I don't see why not anymore. I even hinted the answer in my own question _I could wrap the whole thing in a fork and then cancel that single fork_.

Thanks for pointing out the obvious :)  I'll go with this approach, and get back to you if I figure out why that didn't seem like an option before.

**Comment by mikabytes** [comment]
Wanted to share this for those who need a saga that returns a value _without_ waiting for forks.

```javascript
export function* cancelForks(actor) {
  let res, rej
  const promise = new Promise((r, j) => {
    res = r
    rej = j
  })

  yield fork(function* () {
    try {
      let ret
      yield call(function* () {
        ret = yield* actor()
      })
      res(ret)
    } catch (e) {
      rej(e)
    } finally {
      yield cancel()
    }
  })

  return yield promise
}
```

Usage:
```javascript
function* multiple() {
  yield cancelForks(function*() {
    yield fork(someOtherLongRunningFunction)
    yield fork(someThirdEverLastingFunction)

    return `somevalue`
  })
}

console.log(yield work()) // "somevalue" (without delay), the fork is cancelled when function returned
```

A few notes here:
- We cannot use `join` because that would cancel the caller as well. The promise handles the communication to parent.
- We have to use the extra `call()` because `yield*` bypasses the try/catch otherwise.
