### ISSUE TITLE
Delay too short in React Native

### ISSUE THREAD

**Issue by JaapWeijland** [redux-saga/redux-saga#2142]
#### Description of the bug/issue
I expect a `delay(5000)` to wait for 5 seconds. Instead, it waits only 500 milliseconds (estimated). 

#### Steps to reproduce the bug/issue
Implement the following:

```
// rootSaga.ts

export default function* rootSaga() {
    ...
    yield all([
        takeEvery(REHYDRATE, function* initSaga() {
            yield all([
                ...
                fork(reachabilitySagas),
                ...
            ])
       })
    ])
}
```

```
// reachabilitySagas.ts

export default function* reachabilitySagas() {
    console.log('Ping cycle initiated');
    while (true) {
        console.log('Ping cycle instance');
        // Ping every 5 seconds
        yield delay(5000);
    }
}
```

### Actual results
`Ping cycle instance` being printed 2 times a second.

### The Expected results
`Ping cycle instance` being printed once per 5 seconds.

### Environment information
```
"react": "16.13.1",
"react-native": "0.63.3",
"redux": "^4.0.5",
"redux-saga": "^1.1.3",
"@babel/core": "^7.8.4",
"typescript": "^3.8.3"
```

### Closing thoughts
Does this have to do something with the way I fork my reachabilitySaga? Or does this have something to do with the "ticker" of React Native?

**Comment by Andarist** [comment]
We literally use `setTimeout` under the hood - so if this gets resolved sooner than it is supposed to then it has to be an issue related to React Native itself.

**Comment by JaapWeijland** [comment]
This indeed appears to be a react-native issue with the debugger, in which time goes almost 5x as fast.

**Comment by JaapWeijland** [comment]
For people experiencing the same issue, this issue was causing it:

https://github.com/facebook/react-native/issues/27008
