### ISSUE TITLE
Saga redux duplicate call api

### ISSUE THREAD

**Issue by tomnyson** [redux-saga/redux-saga#2144]
### Steps to reproduce
saga call duplicate api with build react. it work well with dev version without build

#### Description of the bug/issue
this picture with dev
![image](https://user-images.githubusercontent.com/10257765/101304472-e2f3fc80-3872-11eb-8a1f-76f74ac3246e.png)
this picure with prod
![image](https://user-images.githubusercontent.com/10257765/101304533-03bc5200-3873-11eb-9d77-727cd5cca868.png)

#### Steps to reproduce the bug/issue
yarn build 
serve -s build -l 4000
...

#### Example
To help us to identify a problem faster, please provide repository with an example or use [Code Sandbox](https://codesandbox.io/)
(there is a [prepared template](https://codesandbox.io/s/0q9yzno0zv?module=%2Fsrc%2Fsagas%2Findex.js) for Code Sandbox)

### Environment information

 "redux-saga": "^1.1.3",

**Comment by neurosnap** [comment]
I don’t see any code in this issue description.  Please provide us with some code or a code sandbox so we can properly debug this issue.  Closing for now but feel free to reply here and I can reopen.
