### ISSUE TITLE
Where to find the `asEffect` function that used to be in redux-saga/utils?

### ISSUE THREAD

**Issue by willemodendaal** [redux-saga/redux-saga#2145]
### Description

The `redux-saga-test-plan` documentation says that redux-saga provices an `asEffect` function that I can use to enhance my tests. See 'Inspect Specific Properties' section [in their documentation](http://redux-saga-test-plan.jeremyfairbank.com/integration-testing/exposed-effects.html).

Is this function still available somewhere? I can't seem to track it down. Apparently it was [moved somewhere else](https://github.com/clarketm/saga-monitor/issues/3#issuecomment-461837832), but I don't know where to.

I see there is an npm library called [redux-saga-utils](https://www.npmjs.com/package/redux-saga-utils), but that doesn't look like the right thing.

Does anyone know if the `asEffect` function is still somewhere I can use?

**Comment by Andarist** [comment]
`asEffect` was just "unpacking" the description object - I don't think you should really rely on this but right now you can pretty much get the same effect by inspecting `.payload` property on the returned effect. If you want to ensure if the effect is of a particular type then just inspect the `.type` property.

**Comment by neurosnap** [comment]
Closing as it looks like a PR was recently opened in `redux-saga-test-plan` updating the documentation.  Thanks for submitting this issue!
