### ISSUE TITLE
Trace saga put origins for debugging purposes - saga function name and line number

### ISSUE THREAD

**Issue by springjazzy** [redux-saga/redux-saga#2147]
Currently I have a big amount of redux actions in my project. When debugging it would be convenient to inspect origins (component methods, redux-saga functions) that dispatched actions. 

For pure redux I can write middleware:

```ts
const logMiddleware = () => next => action => {
  const fakeError = new Error();
  const stack = fakeError.stack;
  const logAction = {...action, stack };
  return next(logAction);
};
```

But it doesn't show origins of `redux saga` for `put` effects. I understand that they are just effects and real work is done in middleware, but it would be really cool to see trace info - where did that action came from (function name and line number).

**Comment by aybb** [comment]
You can try to wrap `put` effect with function:

```
const betterPut = (...args) => {
   // log here
   return put(...args)
}
```

And use it in you saga:
```
yield betterPut()
```

It's super easy to create your own modified effects since effects it's just a plain objects

**Comment by springjazzy** [comment]
Thanks for the idea. 
The only downside is that I need to import that wrapped `put` method and use it.

Are there any means to change original saga put effect to decorated one somewhere in application entry point?

If I write something like this:

```js
saga.put = betterPut
```

I'm getting `Cannot set property put of [object Object] which has only a getter` error.

**Comment by tareqdayya** [comment]
@springjazzy sorry, I haven't tried this so i'm not sure it would work, but did you try using `Object.defineProperty` to work around the getter only thing?

**Comment by springjazzy** [comment]
@tareqdayya `put` is not `configurable` property. So i'm getting `Uncaught TypeError: Cannot redefine property: put`

**Comment by springjazzy** [comment]
I've ended up with following solution:

```ts
function put(action) {
  const fakeError = new Error();
  const stack = fakeError.stack;
  return saga.put({ ...action, stack });
}

const handler = {
  get: function (target, prop) {
    if (prop === 'put') {
      return put;
    }
    return target[prop];
  },
};
const proxy = process.env.NODE_ENV !== 'development' ? saga : new Proxy(saga, handler);
export default proxy;
```
