### ISSUE TITLE
Cannot assign to read only property 'joiners' of object '#<Object>'

### ISSUE THREAD

**Issue by lakeshadow0** [redux-saga/redux-saga#2149]
### Description

I am running into this error when trying to cancel a previously detached task (via `spawn`). The setup works like this:

1. A detached task is spawned which has a loop for an event emitter
2. The returning task from the spawn effect is then stored into a Redux state which uses ImmerJS
3. When a certain action is performed, the task is pulled from the state and then cancelled

On step #3, I get that specific error.

```
webpack-internal:///./node_modules/@redux-saga/core/dist/io-6de156f3.js:178 TypeError: Cannot assign to read only property 'joiners' of object '#<Object>'
    at end (webpack-internal:///./node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1040)
    at Object.cancel (webpack-internal:///./node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:999)
    at cancelSingleTask (webpack-internal:///./node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:667)
    at runCancelEffect (webpack-internal:///./node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:679)
    at runEffect (webpack-internal:///./node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1228)
    at digestEffect (webpack-internal:///./node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1295)
```

Quick snippet example

```js
function myEventChannel(){
    return eventChannel(emitter => {
       ...
    });
}
function* eventEmitterHandler(){
   const channel = yield call(myEventChannel);
   
   while(true){
      const event = yield take(channel);
      ...
   } finally{
      ...
   }
}

function* spawnHandler(){
    const task = yield spawn(eventEmitterHandler);
    yield put(updateTaskAction(task));
}

function* cancelHandler(){
   const task = yield select(taskSelector);
   yield cancel(task);
}
```

I attempted to re-create the issue from a base Redux-Saga project but I could not. Cancel worked as expected, and after looking through the runtime code I cannot find anything. I'm hoping someone here would have insight into what the problem is.

**Comment by lakeshadow0** [comment]
Just had a hunch to throw in ImmerJS into the Repl and now I can consistently reproduce the error. 

https://codesandbox.io/s/redux-saga-issue-template-forked-yojsc

Click "start counter" and then "stop counter", the error I am receiving should show in the console.

**Comment by lakeshadow0** [comment]
The solution I found is to wrap the task within a class to prevent Immer from freezing it. If anyone has found another solution please share! I'll be closing this but hopefully it helps someone else in the future.

**Comment by Bartel-C8** [comment]
Thanks @lakeshadow0 for your solution, got the same problem here. And your solution worked fine!
When a `fork` is used instead of `spawn` a slightly different error message is thrown, so for future references:

Cannot assign to read only property 'cont' of object '#<Object>'
