### ISSUE TITLE
The future of redux-saga

### ISSUE THREAD

**Issue by 3plusalpha** [redux-saga/redux-saga#2151]
As a fan of process managers (well, redux-saga is not a saga, but that's a different story) and as a fan of control flow not spread into React components, I wonder what the future of redux-saga is like.

There wasn't any further development in 2020 as far as I can see it from github insights (https://github.com/redux-saga/redux-saga/graphs/contributors?from=2020-01-01&to=2020-12-28&type=c).

Have the redux-saga maintainers given up the project?

**Comment by Andarist** [comment]
My interests have certainly shifted towards other projects but I'm still around for bug fixing, reviewing PRs etc. 

`redux-saga` is a perfectly working piece of software and, honestly, there are no real feature requests from the community. IMHO it's more a sign of maturity and stability than it is a sign of staleness or giving up on a project.

**Comment by 3plusalpha** [comment]
@Andarist I remember you are working quite a lot on [xstate](https://github.com/davidkpiano/xstate).
Kudos for contributing so much to both libraries!

My concern is that redux is less and less the first choice when it comes to state management, and hence the pattern (process manager) will not be available to the JS community anymore with the descent of redux. In the end you only really need the event part of redux, which could be anything (even just custom JS events). 

So I wonder if it's possible to decouple redux-saga from redux.

**Comment by Andarist** [comment]
It's actually already completely decoupled 😅 We expose `runSaga` API that can be used with anything that satisfies the `{dispatch, getState}` interface - the actual redux middleware just binds Redux to that. See https://redux-saga.js.org/docs/advanced/UsingRunSaga.html

**Comment by dcbrwn** [comment]
There is still a big room for DX improvement like readable stacktraces and better typing. But currently the project [looks](https://github.com/redux-saga/redux-saga/graphs/contributors?from=2019-12-26&to=2021-01-17&type=c) pretty much like it's abandoned. I think it makes sense to put big bold "looking for maintainers" in the top of README.md.

**Comment by foglerek** [comment]
I second what @dcbrwn just mentioned — I'd happily give improving stack traces a stab (the groundwork is there with sagaStack via the onError handler, but would be neat if we could read/generate the saga stack during saga execution as caught and handled errors are still largely illegible).

Are you accepting PRs @Andarist?

**Comment by Andarist** [comment]
> I'm also concerned about sagaError being module-scoped as opposed to being instantiated per-process — isn't there a risk with leaking error state between requests in node?

I don't think so as we catch the error, forward it synchronously through saga layers and report it if it stays uncaught. I could be wrong - it has been quite some time since I've looked at that code.

> I'd love to know if you're still accepting PRs @Andarist and if this is something you'd be open to before digging in!

PRs are always welcome. I would appreciate RFC write-up about current problems and the proposed solution to settle what actually should/could be done.

**Comment by dcbrwn** [comment]
As for types: this PR still needs some love https://github.com/redux-saga/redux-saga/pull/2053

**Comment by Andarist** [comment]
Yes - I'm aware, I plan to get to this PR but I just have a ton of OSS work to do and this gets constantly shifted in my priorities 😢

**Comment by neurosnap** [comment]
I love this GH issue and thanks for posting it.  `redux-saga` is alive and well and I use it for virtually all of my work and personal web apps.  I’m going to close this issue for now and kindly redirect everyone to a recent GH discussion that I created discussing the future of this library.

https://github.com/redux-saga/redux-saga/discussions/2264
