### ISSUE TITLE
Can't import with extensions

### ISSUE THREAD

**Issue by daveisfera** [redux-saga/redux-saga#2152]
### Steps to reproduce
Run [`eslint` with `import/extensions`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md) set to "always" and `ignorePackages` set to `false`

#### Description of the bug/issue
`eslint` wants the extensions but when it's specified, the `import` doesn't work since there's not actually a file there and it's just some "magic" in a `package.json` file

### Environment information
- redux-saga version: 1.1.3
- babel / typescript setup: 7.11.0

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by neurosnap** [comment]
Closing issue for now.  Please feel free to reply with more information so we can help debug.  Thanks!
