### ISSUE TITLE
I am using react saga, it's rendering twice once called in development environment.

### ISSUE THREAD

**Issue by gursewak11** [redux-saga/redux-saga#2153]

**Comment by shivaylamba** [comment]
It is happening to me as well, we are working on the same project @gursewak11 should we ask Billy

**Comment by neurosnap** [comment]
Thanks for submitting this issue.  We are going to need more information in order to help triage this issue.  I’m going to close this for now but please feel free to reply and I can re-open and help debug.  Thanks!
