### ISSUE TITLE
批量任务的取消操作

### ISSUE THREAD

**Issue by olabala** [redux-saga/redux-saga#2154]
有一个批量异步任务，支持单独取消其中某一个任务，也支持不断接收新的任务进来。

所以分析起来像是 takeEvery与cancel的结合，
https://codesandbox.io/s/takeeveryperkey-example-forked-8hjyf?file=/sagas/cancel.js

参照takelatestperkey 实现了一个takeEveryperke，但发现存在一些问题：
1. 如果某个任务已经被取消了，能否提前对tasks做些改动？
2. 由于是takeEvery，所以cancel的action也是N次被捕获，感觉有些浪费

不知道还有没有其他更好的实现 @shinima

**Comment by shinima** [comment]
@olabala    没有完全看明白你想要做什么，不过根据你的代码优化了一个版本，具体直接看代码吧

https://codesandbox.io/s/takeeveryperkey-example-forked-h2hdj?file=/sagas/cancel.js

**Comment by shinima** [comment]
没什么问题的话我就把 issue 关闭了
