### ISSUE TITLE
When using takeEvery to replace while loop and take, the error handling stops working

### ISSUE THREAD

**Issue by stevemao** [redux-saga/redux-saga#2155]
The examples in https://redux-saga.js.org/docs/advanced/Channels.html uses `while (true)` loop with `yield take(channel)`

```
  while (true) {
    try {
      // An error from socketChannel will cause the saga jump to the catch block
      const payload = yield take(socketChannel)
      yield put({ type: INCOMING_PONG_PAYLOAD, payload })
      yield fork(pong, socket)
    } catch(err) {
      console.error('socket error:', err)
      // socketChannel is still open in catch block
      // if we want end the socketChannel, we need close it explicitly
      // socketChannel.close()
    }
  }
```

We want to use higher level API `takeEvery(channel, saga, ...args)` to replace this

```
try {
  takeEvery(socketChannel, function* (payload) {
      // An error from socketChannel will cause the saga jump to the catch block
      const payload = yield take(socketChannel)
      yield put({ type: INCOMING_PONG_PAYLOAD, payload })
      yield fork(pong, socket)
  })
} catch (err) {
     console.error('socket error:', err)
      // socketChannel is still open in catch block
      // if we want end the socketChannel, we need close it explicitly
      // socketChannel.close()
}
```

However, the error handling doesn't work anymore if `socketChannel` emits an error.

Expected behaviour: The error handling works the same way as `while (true)` loop with `yield take(channel)`

**Comment by Andarist** [comment]
`takeEvery` is not a blocking effect - the forking saga has continued its execution and thus going past your try/catch block. Its suspension point is just at a different point than you expect it to - it's just how JS works.

You should be able to add a blocking effect within your try/catch block to make it work, smth like:
```js
yield new Promise(() => {})
```
This probably ain't the best solution though. I would recommend not relying on errors for your application flow and convert them to explicit events.

**Comment by stevemao** [comment]
Thanks for taking the time explaining this.

I don't understand this part:

> You should be able to add a blocking effect within your try/catch block to make it work, smth like:
yield new Promise(() => {})

Could you elaborate this or link me somewhere? Thanks a lot!

**Comment by Andarist** [comment]
Consider how this works under the hood:
```js
function runEffect(effect) {
  switch (effect) {
    case "takeEvery":
      return "task_" + Math.random().toString(36).substring(2);
  }
}

function* saga() {
  try {
    const task = yield "takeEvery";
  } catch (err) {
    console.log("caught", err);
  }
  console.log("we are already here");
}

const it = saga();
// kick off
const yielded = it.next();

const result = runEffect(yielded);

it.next(result);
```

Note that in the real `redux-saga` the `it.next()` is not always called immediately - if you block by yielding something that we need to await (such as a promise that never resolves) then we won't call it immediately and your saga will be able to still catch the error if we call `it.throw()` (because you will still be suspended within try/catch block(.

**Comment by neurosnap** [comment]
Closing as it looks like there was a resolution to this issue.
