### ISSUE TITLE
sagaMiddleware.run() can't add second arg using Typescript

### ISSUE THREAD

**Issue by Singtah** [redux-saga/redux-saga#2162]
### Steps to reproduce
Add an extraArg to .run() : 
`const configureStore = () => {
  const extraData = "extraData"
  const store = createStore(rootReducer, applyMiddleware(sagaMiddleware));
  sagaMiddleware.run(rootSaga, [extraArg]);
  return store;
};`
#### Description of the bug/issue
Should be possible to add extra arguments. 
https://redux-saga.js.org/docs/api/#middlewarerunsaga-args
#### Steps to reproduce the bug/issue

1. Add extra argument to run
2. Typescript throws error : Expected 1 argument but got 2
...

#### Example
https://codesandbox.io/s/redux-saga-typescript-example-rz8bg?file=/src/core/store/configureStore.ts:244-443

### Environment information
- "redux-saga": "^1.1.3",
- "typescript": "~3.8.2"

Solving this would allow me to inject dependencies down to my sagas. Not sure if its a recommended way though, i am open for other solutions.

**Comment by Andarist** [comment]
Extra args are passed using positional arguments, so you can do this:
```js
sagaMiddleware.run(rootSaga, 'test');
```

Note that your `rootSaga` has to accept parameters for this to work:
```ts
export default function* rootSaga(a: string) {
  yield all([fork(LyricsSaga)]);
}
```

See the adjusted codesandbox: https://codesandbox.io/s/redux-saga-typescript-example-forked-8h2ky?file=/src/core/store/configureStore.ts:352-389

**Comment by Singtah** [comment]
@Andarist Thank you for your reply. 
I was just missing the the definition in rootSaga, where the extraArgs def are needed.

Also I was wondering if using the extra args was the common way for passing dependencies into sagas. Any thoughts on this ?

**Comment by Andarist** [comment]
> Also I was wondering if using the extra args was the common way for passing dependencies into sagas. Any thoughts on this ?

It's OK - if you want to have your top-level sagas parametrized then this is the way to go.
