### ISSUE TITLE
Access class instance inside Sagas

### ISSUE THREAD

**Issue by Singtah** [redux-saga/redux-saga#2164]
### Description
I am trying to inject dependencies into the top `rootSaga`. Seems like whenever i try to access an attribute of an instance inside a Saga, it is undefined and it can't access `this.myClassProp`

1. create an instance of `HttpImageFetchingGateway ` : 

```
export class HttpImageFetchingGateway implements ImageFetcherGateway {

    private readonly pictureName: string;

    constructor() {
        this.pictureName = "fakeHttpIamge"
    }

    fetch() {
        //Can't log or access attributes of the instance :
        console.log(this.pictureName)   //TypeError: Cannot read property 'pictureName' of null
        console.log("pictureHere");     //logs fine
        return Promise.resolve(this.pictureName) --> This will fail
    }
}

---------------------------------------------------------------------------------------------------------

export const dependencies: Dependencies = {
    imageFetchingGateway: new HttpImageFetchingGateway()
}
```

Create store, inject middleware with dependency : 

```
export function createReduxStore(dependencies: Dependencies): Store<AppState> {
    const sagaMiddleware = createSagaMiddleware();
    let store = createStore(reducers, applyMiddleware(sagaMiddleware));
    sagaMiddleware.run(rootSaga, dependencies);
    return store;
}
```

rootSaga and Saga : 

```
export function* localImageFecher(dependencies: Dependencies) {
    const imageRequested= yield call(dependencies.imageFetchingGateway.fetch);
    yield put(image_fetched(imageRequested));
}

export default function* rootSaga(dependencies: Dependencies) {
    yield takeEvery(fetch, localImageFecher, dependencies)
}
```

I am not sure why i can't access ```this``` inside Saga ? Thanks for the help

**Comment by Andarist** [comment]
> I am not sure why i can't access this inside Saga ? Thanks for the help

Well, you should read online how `this` works in JavaScript - I'm afraid I don't have time right now to explain its oddities.

You can work around this by doing this:
```js
```

**Comment by Singtah** [comment]
Thank you for your quick answer @Andarist.
So i am losing context by using `call` effect. I would rather try to keep `call` for test purposes...

Is your solution equivalent to creating a function with context binding like so : 
`const imageRequested = yield call(dependencies.imageFetchingGateway.fetch.bind(dependencies.imageFetchingGateway));`

**Comment by Andarist** [comment]
Yes, this is somewhat equivalent - my version just does this internally:
```js
dependencies.imageFetchingGateway.fetch.call(dependencies.imageFetchingGateway)
```

**Comment by DadouBordeaux** [comment]
A little bit of explanation :

```call(myClass.aMethod, param);

function call(aMethod, param) {
  // Doing some stuffs then
  aMethod(param); // we have a reference of the method without the context.
}
```

Correct me if I'm wrong :).

I suggest for this link [](https://redux-saga.js.org/docs/api#callcontext-fn-args)

That it could be usefull to change `This is useful to invoke object methods.`  with `This is useful to invoke object / class methods.`

**Comment by Jameskmonger** [comment]
@Singtah does using an arrow function for `fetch` solve your issue?

```ts
fetch = () => {
    /* ... */
}
```

**Comment by neurosnap** [comment]
Closing as it looks like there was a resolution to this question
