### ISSUE TITLE
real-world example can not run correctly. window is not defined

### ISSUE THREAD

**Issue by Facefall** [redux-saga/redux-saga#2167]
### Steps to reproduce

1. `cd /examples/real-world`
2. `npm i`
3. `npm start`

#### Description of the bug/issue
real-world example can not run correctly
it says 

> ReferenceError: window is not defined
    at new Dock 
    at processChild
    at ReactDOMServerRenderer.render
    at ReactDOMServerRenderer.read
    at renderToString
    at /path/.../redux-saga-master/examples/real-world/**server.js:72:7**
line 72: renderToString(rootComp)

#### Steps to reproduce the bug/issue

1. `cd /examples/real-world`
2. `npm i`
3. `npm start`

**Comment by neurosnap** [comment]
Thank you for posting this issue.  Would you be interested in submitting a PR to fix it?

**Comment by irfanabliz** [comment]
For me it's working fine, depending on how you started your server I guess, for me it's
1. `npm run build`
2. `yarn --cwd examples/real-world start` or `cd /examples/real-world && npm start`

**Comment by neurosnap** [comment]
Thanks @irfanabliz !

I'm going to mark this issue as resolved for now.  If anyone else has issues starting the real world example, please feel free to open a new issue or comment here and we will address it.

Thanks everyone!
