### ISSUE TITLE
Cancelled effect type error in typescript 4.2

### ISSUE THREAD

**Issue by androBermudez** [redux-saga/redux-saga#2177]
#### Description of the bug/issue

After update to typescript 4.2 my build process fails with this error:

> 'yield' expression implicitly results in an 'any' type because its containing generator lacks a return-type annotation.

This happens only yielding cancelled effect. 

It seems that this is due a breaking change in typescript. I am wondering if there is a workaround.

See [TS](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-2.html#noimplicitany-errors-apply-to-loose-yield-expressions)

#### Example

```
function* mySaga() {
  try {

  } catch (error) {
    
  } finally {
    if (yield cancelled()) {
      yield call(abort)
    }
  }
}
```

### Environment information

- redux-saga version: 1.1.3
- typescript version: 4.2.4

**Comment by TristanHessellHyper** [comment]
@androBermudez You'll need to add a return type to the `mySaga` generator function.

Something like:

```ts
function* mySaga() : any {
  try {

  } catch (error) {
    
  } finally {
    if (yield cancelled()) {
      yield call(abort)
    }
  }
}
```

**Comment by panmau** [comment]
You can also use the `SagaIterator` type as the return type for your function. 

So for example this will work:
```
function* mySaga(): SagaIterator {
  try {
  } catch (error) {
  } finally {
    if (yield cancelled()) {
      yield call(() => {});
    }
  }
}
```

The documentation of the type says the following:
```
/**
 * Annotate return type of generators with `SagaIterator` to get strict
 * type-checking of yielded effects.
 */
``` [source file](https://github.com/redux-saga/redux-saga/blob/24e9a68d621fd2a57a29b3b80e4b54ecb22fa593/packages/types/types/index.d.ts)
