### ISSUE TITLE
"takeImportant", combining takeLatest with takeLeading, worth including in the core?

### ISSUE THREAD

**Issue by SinusPi** [redux-saga/redux-saga#2179]
After a bit of experimenting, I whipped up a custom taker, combining takeLatest with takeLeading, by giving the saga control over whether it wants to be restartable or not. Dropping it here, perhaps it's worth implementing at the core level, or maybe someone finds it interesting.

Use: `yield takeImportant(action, saga, true|false)`

Define saga as: `function* saga(setImportant, action, ...args)`

Call `setImportant(true|false)` in the saga to switch between interruptability or not.

```
const takeImportant = (patternOrChannel, saga, startImportant = false, ...args) => fork(function* () {
    let important = startImportant;
    let lastTask;
    const setImportant = (isit) => (important = isit);
    while (true) {
      const action = yield take(patternOrChannel);
      if (lastTask) {
        if (important) continue;
        yield cancel(lastTask);
      }
      lastTask = yield fork(saga, setImportant, action, ...args);
    }
});
```

**Comment by AuthorProxy** [comment]
I don't see any reasonable usecase. For example, I have `takeLatestOrEvery` which read data from the passed action payload (meta), so I can control directly from UI when I want single `latest` or multiple `every` requests, in case I have multiple entities of the same type but with different ids.

**Comment by neurosnap** [comment]
Thanks @AuthorProxy 

Closing this issue for now.  If you want to continue discussing other patterns, please feel free to open a GH discussion.
