### ISSUE TITLE
How to cancel saga task from useEffect

### ISSUE THREAD

**Issue by jakub-chatrny** [redux-saga/redux-saga#2186]
### Description
I have `useSaga` hook which runs saga task on component mount and should cancel it on unmount. However `yield canceled()` is never triggered. Here is code:
```
const createRunSagaAfterAppInit = (
   moduleSaga: SagaWithReturnType<[Record<string, unknown>]>,
): SagaWithReturnType<[Record<string, unknown>]> => {
   return function* initLoadingSaga(...params) {
      // Mock is used to avoid import from core/loading core/init packages
      try {
         ... 
         yield fork(moduleSaga, ...params);
      } finally {
        console.log('initLoadingSaga finally'); // saga is not blocked this log is executed
         if (yield cancelled()) {
            console.log('initLoadingSaga cancelled'); // <-- never happen
         }
      }
   };
};

export const useSaga = (
   saga: SagaWithReturnType<[Record<string, unknown>]>,
) => {
   const store: SagaStore = useStore();
   const { isFallback, query }: NextRouter = useRouter();

   useEffect(() => {
      if (!isFallback) {
         // Run independent saga. Note this saga is not canceled on main saga cancellation.
         const sagaTask = store.sagaMiddleware?.run(
            createRunSagaAfterAppInit(saga),
            query,
         );

         return () => {
            console.log('useSaga isRunning', sagaTask.isRunning()); // true
            sagaTask.cancel();
            console.log('useSaga isCancelled', sagaTask.isCancelled()); // true
         };
      }
      return null;
   }, []);
};
```
### Context
I'm using redux-saga with nextjs. For now we run sagaTask on each page in `useEffect` and cancel it on unmount, and also run main saga independently (handling some general redux state tasks). I understand it's not best practice, it would be much better cancel saga from main saga and this approach worked for us in past. I hope we will be able work around nextjs router to allow it in future.

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by martinkadlec0** [comment]
@jakub-chatrny I think the problem is that the `cancelled` effect is only really useful with blocking effects or infinite cycles inside the `try` block. With non-blocking effects such as takeEvery the code execution will reach the finally block before the task is cancelled and that is why the condition doesn't work. 

While probably not the ideal solution, you should be able to get around your problem by adding any blocking effect at the end of the try block e.g.:


```javascript
const pageASaga = function* () {
  try {
    yield takeEvery("SOME_ACTION", function* () {
      console.log("SOME_ACTION triggered in pageASaga");
    });
    yield take('__never__') // saga will remain blocked here until cancelled
  } finally {
    if (yield cancelled()) {
      console.log("pageASaga: canceled");
    }
  }
};
```

Other option would be to rewrite the `takeEvery` into a while with `take` effect. Hope this helps a bit O:)

**Comment by jakub-chatrny** [comment]
Yes thanks for reply! Didn't realized, that generator might reach the end and at same time saga task be still active. 

In meantime we used explicit clean up saga. I'll put it here as alternative to what you suggested.

```
export const useSaga = (
   saga: SagaWithReturnType<[Record<string, unknown>]>,
   cleanUpSaga?: SagaWithReturnType,
) => {
   const store: SagaStore = useStore();
   const { isFallback }: NextRouter = useRouter();
   const query = useUrlQuery();

   useEffect(() => {
      if (!isFallback) {
         // Run independent saga. Note this saga is not canceled on main saga cancellation.
         const sagaTask = store.sagaMiddleware?.run(
            createRunSagaAfterAppInit(saga),
            query,
         );

         return () => {
            // as workaround run cleanup saga separately
            if (cleanUpSaga) {
               store.sagaMiddleware?.run(cleanUpSaga);
            }
         };
      }
      return null;
   }, []);
};
```

**Comment by neurosnap** [comment]
Closing this issue since it looks like there was a resolution.
