### ISSUE TITLE
Can I use effects inside array.reduce() callback?

### ISSUE THREAD

**Issue by rus-yurchenko** [redux-saga/redux-saga#2188]
I'm new to redux-saga and faced an issue with loops. I'm refactoring my code from thunks to sagas with `.reduce` methods. I'm remapping input data into another shape using conditions inside a callback to skip some iterations or to return the accumulator. I need to get the redux data by using a selector inside my callback. For this action, I think I should use a `selector` effect.

I saw the advice about how to loop over sagas with `.map()`, but this isn't my case.

Can you, please, elaborate on how can I use `yield select()` inside `array.reduce() to get the data from a redux store`? I like this method a lot because it's declarative and I'd rather not use a plain `for` loop in my project.

Thanks in advance.

**Comment by stropho** [comment]
As far as I know you cannot `yield` anything from the callbacks provided in `.map()` or `reduce()` - these callbacks are not generators.
The only way I can think to avoid writing simple loops over and over again is to create your own helper-saga that will include it (just in one place)

**Comment by martinkadlec0** [comment]
@rus-yurchenko How about getting the state before running your reducer?

```javascript
function*someSaga() {
  const state = yield select()
  someArray.reduce((agg, item) => {
    const data = someSelector(state)
    // ...
  }, {})
}
```
I am selecting the whole state there but you could even have some special selector that would prepare the data for your reducer (e.g. some map or something) so you wouldn't need the other selector inside of the reducer.

**Comment by neurosnap** [comment]
I’m closing this issue for now due to inactivity.  Please feel free to continue to ask questions if needed.  Thanks!
