### ISSUE TITLE
How to use EventSource in redux-saga , is it possible to consume it , i did a extensive search over the internet but couldn’t find article doing it.

### ISSUE THREAD

**Issue by dineshnagrani** [redux-saga/redux-saga#2196]
### Description
Please provide some context about the problem and some code examples if relevant.
The best way to provide an example is repository or use [Code Sandbox](https://codesandbox.io/)(there is a [prepared template](https://codesandbox.io/s/0q9yzno0zv?module=%2Fsrc%2Fsagas%2Findex.js) for Code Sandbox)

**Comment by Andarist** [comment]
This should work - you only need to adjust this according to your needs.
```js
function createSse() {
  const chan = eventChannel((emit) => {
    const sse = new EventSource("/api/v1/sse");
    sse.addEventListener("message", (ev) => emit(ev.data));
    return () => sse.close();
  });
  return;
}

function* saga() {
  const chan = yield call(createSse);
  while (true) {
    const data = yield take(chan);
    // do smth here
  }
}
```
