### ISSUE TITLE
Add Travis-CI again (or remove button in README)

### ISSUE THREAD

**Issue by erikvold** [redux-saga/redux-saga#2200]
GH Actions Node CI logs expire much sooner that Travis-CI for one thing, and we seem to be having trouble with CI atm, so it would be nice to have those logs.

GH Node CI log for first failed commit: https://github.com/redux-saga/redux-saga/runs/267504349

^ not there

Travis CI logs from before switch to GH Actions CI: https://travis-ci.org/github/redux-saga/redux-saga/builds

^ still there

There is no reason not to have both running afaict.

**Comment by neurosnap** [comment]
Thanks for submitting this issue.  We have resolved the CI issues and don't intent on using travis anymore.
