### ISSUE TITLE
Hanged call effect when nested spawn effect throws error in finally block

### ISSUE THREAD

**Issue by chbdetta** [redux-saga/redux-saga#2202]
### Steps to reproduce
See the codesandbox

#### Description of the bug/issue
Some error happens in the spawn effect's `finally` block, instead of aborting the root saga with error or logging the error on console, the root saga never resolves or rejects.

#### Example
https://codesandbox.io/s/saga-spawn-silent-error-2xbsg?file=/src/index.js

### Actual results
The root saga task never resolve or reject nor does any error show in the console

### The Expected results
The root saga reject or an error show in the console

### Environment information

- redux-saga version: 1.1.3
- babel / typescript setup: babel7 + webpack5

**Comment by neurosnap** [comment]
Greetings!  Sorry for the late response.  You're using `spawn` and trying to have the parent task catch the error.  This doesn't work the way you think it does by *design*.  If you switch `spawn` to `fork` it works as expected.

From the docs:

https://redux-saga.js.org/docs/advanced/ForkModel#detached-forks-using-spawn

> Uncaught errors from spawned tasks are not bubbled up to the parent. And cancelling a parent doesn't automatically cancel detached forks (you need to cancel them explicitly).

I'd be happy to continue chatting about this, but closing the issue for now.
