### ISSUE TITLE
How to catch error in saga.take effect?

### ISSUE THREAD

**Issue by springjazzy** [redux-saga/redux-saga#2203]
Suppose, I have some business logic that deals with:

1. Show dialog load panel for time consuming operation
2. Do something with record
3. Save it via sending request (saga.put) to saga that actually saves record
4. Subscribe to save result and do somthing according to save result
5. Hide load panel

In pseudo-code it would look like this:
```js
function* handlePayment(payment){
  try {
  // 1. Show some sialog with LOAD PANEL
  yield saga.put({type: 'SHOW_LOAD_PANEL'}); 

  // 2. Do something with record
  payment.N_Amount = 1000;

 //3. Save it via sending request (saga.put) to saga that actually saves record
 yield saga.put({type: 'SAVE', payment });

 // 4. Subscribe to save result 
yield saga.take(act => {
  if (act.type === 'SAVE_RESULT') {
    const success = act.success;
    // EXCEPTION MAY BE RAISED HERE DUE TO SOME BL
    return true;
  }
})

// and do somthing according to save result 
...
 } finally {
  // 5. HIDE LOAD PANEL
   yield saga.put({type: 'HIDE_LOAD_PANEL'});
 }
}
```

Now what if some error is raised in `take`  effect handler? In that case finally is not called and load panel doesn't hide.

I have found somehow similar [question](https://github.com/redux-saga/redux-saga/issues/2155) but it's related to `takeEvery` which is not blocking. In contrast `take` is blocking and still try-finally context is dissapeared which is very unfortunate and not convenient. Should I wrap all logic in `take` effect into its own try-finally?

I've prepared [codesandbox](https://codesandbox.io/s/cocky-leaf-8fuo9?file=/src/testSaga.ts) for testing `take` error handling. Try click any button and you will see that error is not handled - finally code is not called.

Is it a bug or feature?

**Comment by springjazzy** [comment]
Several thoughts on the matter (all IMHO)
1. It seems natural that `try-catch-finally` block would actually do its job - catch and finalize.
2. Possible semantic conflict - `call` effect propagates error to calling Generator but `take` effect doesn't do it.
3. In C#, for example, if exceptions are thrown while `await` `Task` then it would be real exception that propagates to code that awaits so it is possible to wrap whole code with `try-catch-finally`.

**Comment by neurosnap** [comment]
Closing this issue for now.  If you would still like to chat I'd be more than happy to reopen and continue the discussion.  Thanks!
