### ISSUE TITLE
createMockTask does not properly mock task

### ISSUE THREAD

**Issue by nategraf** [redux-saga/redux-saga#2205]
### Steps to reproduce

Testing a function that uses the `join` operation, create a test that uses `createMockTask` to mock the return of a call to fork.

#### Description of the bug/issue

`join` on mocked tasks that are not complete will result in an exception.

In order to work around this issue, I added `isAborted` and `joiners` to the mock task.

#### Example

https://github.com/celo-org/wallet/pull/508/files#diff-0d5091378c9a747cc2c61efd98db534427cc6a0a649978ace1ea6c471bfcad10R37-R53

### Actual results

Exception with either `isAborted` not being a function, or `Cannot read property 'push' of undefined` (when `joiners` is not included on the mock)

### The Expected results

`createMockTask` returns an object that can be used in place of a Task in tests.

**Comment by Andarist** [comment]
If you prepare a PR with a test and the fix - I would be happy to merge it.

**Comment by lourd** [comment]
Also just ran into this issue myself. Made a more narrow repro in a code sandbox here https://codesandbox.io/s/jest-test-forked-9ubf8?file=/index.test.js.

Related issue on redux-saga-test-plan https://github.com/jfairbank/redux-saga-test-plan/issues/97

Any suggestions on the design of a solution @Andarist? How complex would this be?
