### ISSUE TITLE
TypeScript error with TakeEvery: TakeableChannel<unknown>

### ISSUE THREAD

**Issue by gmunumel** [redux-saga/redux-saga#2216]
Hello, 

I have a simple redux saga. 

```javascript

import { api } from '../api';
import * as screen from './slice';
import { fetchScreenSuccess } from './slice';

interface fetchScreenPayload {
  screenName: string;
}

interface fetchScreenAction {
  type: string;
  payload: fetchScreenPayload;
}

function* fetchScreen(api: any, action: fetchScreenAction) {
  ...
}

export default function* watchDataSource() {
  yield takeEvery(screen.fetchScreen, fetchScreen, api);
                  ^^^^^^^^^^^^^^^^^^
   Argument of type 'ActionCreatorWithoutPayload<string>' is not assignable to parameter of type 'TakeableChannel<unknown>'.
  Property 'take' is missing in type 'ActionCreatorWithoutPayload<string>' but required in type 'TakeableChannel<unknown>'.
}

```

The slice is: 

```javascript
export const screenSlice = createSlice({
  name: 'screen',
  // `createSlice` will infer the state type from the `initialState` argument
  initialState,
  reducers: {
    fetchScreen(state): any {
      state.screen = initialState.screen;
      state.isLoading = true;
    },
  },
});
```

Any idea of how to remove the typescript error?

**Comment by brykov** [comment]
Having the same issue.

**Comment by on3iro** [comment]
you could use the `.type` or `.toString()` properties of the action creator created by redux-toolkit

**Comment by neurosnap** [comment]
I agree with @on3iro on this one.  Because `redux-toolkit` overrides the `toString()` to provide the `action.type` it's hard for `redux-saga` to figure that out on its own and I don't think we want to bake this assumption into `takeEvery` typings.

I'm going to close this issue for now, please feel free to ask any follow up questions and I'll be more than happy to answer!  Thanks!

**Comment by challet** [comment]
Having the same problem here, it wasn't resolved with using the `type` property or `toString()` method, leading to 
> Argument of type 'string' is not assignable to parameter of type 'TakeableChannel<unknown>

The strange thing I noticed is that there is no issue with no extra `args` (`api` in the original report). 

Trying to decipher the typescript [signatures for](https://github.com/redux-saga/redux-saga/blob/main/packages/core/types/ts3.6/effects.d.ts#L180-L211) for this method, the solution is probably in them. Any pointer would be appreciated.

**Comment by vandercijr** [comment]
If you are using redux-toolkit this probably will work for takeEvery
example: 

```
function* actionGen(action: PayloadAction<any>): any {
   const payload = action.payload
    ...
}

export function* anySaga() {
   yield takeEvery("ACTION", actionGen)
}
```
