### ISSUE TITLE
Can debounce provide maxWaitTime param

### ISSUE THREAD

**Issue by shunmian** [redux-saga/redux-saga#2218]
### Description

Can [debounce](https://redux-saga.js.org/docs/api/#debouncems-pattern-saga-args) provide a `maxWait` param which will execute after wait more than `maxWait` ms, like the [loadsh debounce](https://lodash.com/docs/4.17.15#debounce)?

**Comment by neurosnap** [comment]
I'm going to close this issue for now.  If you still have follow up questions, please feel free to reply here or in another issue.  Thanks!
