### ISSUE TITLE
Design bug in the navbar

### ISSUE THREAD

**Issue by SpandanNepal** [redux-saga/redux-saga#2227]
### Steps to reproduce
- Navigate to this [link](https://redux-saga.js.org/docs/introduction/GettingStarted).
- At around 990px-1085px, a horizontal scroll bar seems to appear at the bottom. I guess this is because the main wrapper's width is greater than that of the browser.
- If you scroll the horizontal scrollbar, keep an eye on the navbar. It seems the navbar's width is not set to 100% w.r.t the browser, which makes the navbar look a bit off. 
- Please see the image shown below. This can be a design bug.

#### Description of the bug/issue
![Screenshot from 2021-10-17 21-44-55](https://user-images.githubusercontent.com/65861498/137635426-46d08164-da45-4b3f-82f4-75104dab6624.png)
![Screenshot from 2021-10-17 21-44-36](https://user-images.githubusercontent.com/65861498/137635430-f0ed7f17-64fd-4e34-9c78-f2f4c6042e3f.png)
![Screenshot from 2021-10-17 21-53-26](https://user-images.githubusercontent.com/65861498/137635548-c05af8ea-06ef-4dff-a1f6-f6dcbe6748ac.png)

#### Video

https://user-images.githubusercontent.com/65861498/137729867-84cdc519-bb19-4a00-a19f-2f1d03e66807.mp4

#### Steps to reproduce the bug/issue
This is already stated above.

### Actual results
The navbar seems to not showing properly while scrolling.

### The Expected results
A full width (100%) navbar should be shown even while scrolling.

**Comment by Andarist** [comment]
@acdvs would you know if that is the issue with the styles here or maybe an issue with docusaurus itself?

**Comment by SpandanNepal** [comment]
Hi @acdvs, I've added a video on the description of this issue. It shows the issue to which I am referring. It is on the official site of redux-saga.
