### ISSUE TITLE
eventChannel graphql subscription

### ISSUE THREAD

**Issue by humarkx** [redux-saga/redux-saga#2229]
### Steps to reproduce
```
export function* SUBSCRIBE_TO_NOTIFICATIONS() {
	try {
		const channel = eventChannel(emitter => {
			const listener = onNotificationByUserId('234234234', data => emitter(data))
			return () => listener
		})
		while (true) {
			const notification = yield take(channel)
			console.log('NOTIFICATION RECEIVED', notification)
		}
	} catch (error) {
		console.warn(error)
	}
}
```
#### Description of the bug/issue
App closes after some time, or when coming back from background mode
![image](https://user-images.githubusercontent.com/13049940/142514565-1216ed37-d535-44d8-8cb9-f9fe4d393f4c.png)

**Comment by neurosnap** [comment]
I think we are going to need some more information to be able to adequately help here.  Could you provide a little more context into the issue and the corresponding error you are seeing?

**Comment by neurosnap** [comment]
I'm going to close this issue for now.  If you are still having issues, please provide more information so we can better help.  Thanks!
