### ISSUE TITLE
Logo in repo readme is broken

### ISSUE THREAD

**Issue by heytulsiprasad** [redux-saga/redux-saga#2232]
### Description of the bug/issue
The link to official logo of Redux saga is broken in the repo's readme, probably happened due to page has been moved.

### Steps to reproduce the bug/issue

1. Go to this repo's [readme](https://github.com/redux-saga/redux-saga)
2. Check the readme

### Actual results
<img src='https://redux-saga.js.org/logo/0800/Redux-Saga-Logo-Landscape.png' alt='Redux Logo Landscape' width='800px'>

### The Expected results
<img src='https://redux-saga.js.org/img/Redux-Saga-Logo-Landscape.png' alt='Redux Logo Landscape' width='800px'>

**Comment by heytulsiprasad** [comment]
Can help with this if needed.

**Comment by Andarist** [comment]
@heytulsiprasad help would be much appreciated

**Comment by heytulsiprasad** [comment]
> @heytulsiprasad help would be much appreciated

@Andarist made a PR to fix existing broken image links. Reviews are welcome.
