### ISSUE TITLE
Unit tests for Retry redux-saga

### ISSUE THREAD

**Issue by js-jegan** [redux-saga/redux-saga#2235]
### Description
Trying to write unit tests for the retry api here, https://redux-saga.js.org/docs/api/#retrymaxtries-delay-fn-args 
basically trying to simulate the retries to exhaust.

**Comment by neurosnap** [comment]
Greetings!  Sorry for the late response.  Do you still need help with writing tests?  I'd be happy to help.

**Comment by js-jegan** [comment]
no prob. yes please. it will be great to have some help for this.

**Comment by neurosnap** [comment]
Okay, to make this the most relevant to you, do you use any libraries to test generators?  I'll use that in my example to send you.

**Comment by js-jegan** [comment]
we use `jest & enzyme`.

**Comment by neurosnap** [comment]
Closing for now.  Please feel free to follow up and I can reopen.
