### ISSUE TITLE
Can I check the saga status to have just one instance of running saga middleware?  

### ISSUE THREAD

**Issue by fpichlou** [redux-saga/redux-saga#2236]
I'm working on a micro front-end project based on ReactJS, I'm passing the scope of store from the sub-modules or internal projects.
I'm running the saga middleware at the same time as I'm injecting module in the store configuration of the main module.
You can see the configuring steps in the following code:
```

.
.
.
  const startSaga = (key, saga) => {
    const runnableSaga = function* main() {
      const sagaTask = yield fork(saga);
      const { payload } = yield take(STOP_SAGA);

      if (payload === key) {
        yield cancel(sagaTask);
      }
    };

    sagaMiddleware.run(runnableSaga);
  };
  const stopSaga = (key) => {
    store.dispatch({
      payload: key,
      type: STOP_SAGA,
    });
  };

  const useInjectModule = (key, reducer, saga) => {
    store.injectReducer(key, reducer);
    useEffect(() => {
      startSaga(key, saga);
      return () => {
        stopSaga(key);
      };
    }, []);
  };
  store.injectModule = useInjectModule;
.
.
.
```

Also I'm injecting the scope such as this in the sub-module:

```
  store.injectModule(SCOPE, rootReducer, rootSaga);

```

Based on code, when I use the `store.injectModule`, the `sagaMiddleware.run` will be run.
I have two providers in the one module which are using ` store.injectModule` for accessing the store object. How can I check the status of saga to have just one instance of that in the main module which are running saga middleware by updating injectModule property?

**Comment by Andarist** [comment]
I don't really understand your issue in full - it would be best if you could create a repro case for this that I could inspect. That being said - the middleware returns a `Task` and those have such methods:
https://github.com/redux-saga/redux-saga/blob/f6e5fde90443b196a12d85a06d323b5c9dff5593/packages/types/types/index.d.ts#L142-L174

**Comment by neurosnap** [comment]
I'm closing this issue for now.  @fpichlou if you still have some questions relating to this issue, please feel free to reply here and I'll reopen.  Thanks!
