### ISSUE TITLE
Is Redux-Saga still maintained?

### ISSUE THREAD

**Issue by tboulis** [redux-saga/redux-saga#2243]
Hello all, 
I really love `redux-saga` and I just saw that it hasn't been updated for 2 years. Is this because they work flawlessly or lack of support? 
I haven't noticed any security vulnerabilities or bugs to be honest, but it's a little bit weird that nothing has changed in the last 2 years. 

Thanks is advance!

**Comment by Andarist** [comment]
> I haven't noticed any security vulnerabilities or bugs to be honest

That’s why there was no release for so long 😉

**Comment by tboulis** [comment]
Makes sense! :)
