### ISSUE TITLE
Specify the file name for beginners in the doc `beginner tutorial`

### ISSUE THREAD

**Issue by genzyy** [redux-saga/redux-saga#2248]
### Description
In the beginner tutorial of redux-saga documentation [here](https://redux-saga.js.org/docs/introduction/BeginnerTutorial#making-asynchronous-calls), I feel like we should specify the file name here which is `Counter.js` for the developers who are just getting started.

I will create a pull request for this if approved.

**Comment by Andarist** [comment]
PRs are welcome 👍
