### ISSUE TITLE
Update CI to modern nodejs versions

### ISSUE THREAD

**Issue by neurosnap** [redux-saga/redux-saga#2260]
Right now our CI runs for [3 node versions](https://github.com/redux-saga/redux-saga/blob/master/.github/workflows/nodejs.yml#L11): 8, 10, and 12.

These are pretty old nodejs versions.  [v12 is EoL this April.](https://nodejs.org/en/about/releases/)  Furthermore we aren't testing the latest LTS versions (14, 16, 17).  My hunch is that support for 8, 10, and 12 aren't particularly useful.

I think we should just support 14, 16, 17 and reflect that in our CI.

**Comment by PreetSangha** [comment]
@neurosnap 
Hi there,  can I have a go at trying this, please?

Preet

**Comment by neurosnap** [comment]
@PreetSangha So sorry!  I have already started working on it.  FYI my plan is to go through all the GH issues and start triaging this repo.  I'm also going to add more cleanup GH issues like this one so keep a look out to help!

**Comment by PreetSangha** [comment]
No worries @neurosnap, feel free to tag me and I'll try and help if I can.
