### ISSUE TITLE
Expose reading context from saga middleware task

### ISSUE THREAD

**Issue by rushil-patel** [redux-saga/redux-saga#2267]
### Description

This is my use case:
I want to be able to globally cancel all spawned tasks. The way I was hoping to achieve this is wrap the `spawn` effect such that all spawned tasks are stored in saga context. Then from code external to the saga middleware be able to cancel each task stored in saga context, however it doesn't seem possible at the moment to read saga context outside of a generator.

Something like:
```js
     const mainTask = sagaMiddleware.run(rootSaga);
     mainTask.getContext('spawnEffects') // get tasks to cancel


// Spawn Wrapper

    export function* spawn(...args: Parameters<typeof sagaSpawn>) {
        const spawnEffects = yield getContext('spawnEffects');
    
        const spawnTask = yield sagaSpawn(...args);
        setContext({
            spawnEffects: [...spawnEffects, spawnTask]
        });
    }
```

**Comment by Andarist** [comment]
Can't you already achieve this using code similar to this?
```js
const spawnCtx = new Set()
const mainTask = sagaMiddleware.run(rootSaga, spawnCtx);

// use spawnCtx when needed

function* rootSaga(spawnCtx) {
  yield setContext('spawnEffects')
  // ...
}

function* spawn(...args) {
  const spawnEffects = yield getContext('spawnEffects')
  const spawnTask = yield spawn(...args);
  spawnEffects.add(spawnTask)
  return spawnTask
}
```

**Comment by rushil-patel** [comment]
Yes, something like this would work for me. Thanks for the quick suggestion
