### ISSUE TITLE
Dispatching action created by createAsyncThunk

### ISSUE THREAD

**Issue by eiire** [redux-saga/redux-saga#2271]
#### Description of the bug/issue
Typescript error when dispatching action created by createAsyncThunk.

#### Steps to reproduce the bug/issue

1. Using the _createAsyncThunk_ from Redux Toolkit, create thunk action creator
2. Use this thunk action creator in _put_ from saga effects

**Error**: Argument of type 'AsyncThunkAction < T > ' is not assignable to parameter of type 'Action < any > '. 

_Solution_: 
```
declare module "redux-saga/effects" {
  export * from "@redux-saga/core/effects";
  export function put<A extends ThunkAction>(action: A): PutEffect<A>;
}
```

**But** it's better to define _ThunkAction_ type in [effects.d.ts](https://github.com/redux-saga/redux-saga/blob/24e9a68d621fd2a57a29b3b80e4b54ecb22fa593/packages/core/types/effects.d.ts#L367)

**Comment by Andarist** [comment]
> But it's better to define ThunkAction type in [effects.d.ts](https://github.com/redux-saga/redux-saga/blob/24e9a68d621fd2a57a29b3b80e4b54ecb22fa593/packages/core/types/effects.d.ts#L367)

I'm not sure about that. We can't just assume that a thunk action is valid - it's not always the case because you need specific middleware in your store to handle such dispatched items.
