### ISSUE TITLE
I suppose it's better use .toEqual instead of assert.deepEqual

### ISSUE THREAD

**Issue by Andrii256** [redux-saga/redux-saga#2276]
This is not in code, this is documentation. So I removed template comments.
Here is link https://redux-saga.js.org/docs/introduction/BeginnerTutorial

There are code example where you use 
```js
test('incrementAsync Saga test', (assert) => {
// ...
assert.deepEqual(/* ... */)
// ...
```

I spend a while to google what `assert` is (I'm browser js engineer, not node.js engineer, so no: waht is `assert` was not obvious for me)

I think it's better replace by `.toEqual()` jest matcher.
May be it will not so beautifull, but it will be more clear for people who read.

Thanks

**Comment by neurosnap** [comment]
Thanks for submitting this GH issue.  I understand the potential confusion since most people use `jest`, but rewriting the docs is time consuming and if we do rewrite them, it will be a holistic rewrite.
