### ISSUE TITLE
Can we still pass store's dispatch function to the generator function?

### ISSUE THREAD

**Issue by mattchannn** [redux-saga/redux-saga#2278]
Hi all,

According to the [documentation](https://redux-saga.js.org/docs/basics/DispatchingActions)
> **We could pass the Store's dispatch function to the Generator. Then the Generator could invoke it after receiving the fetch response**

Is that still true?

Assuming I dispatch an action called `counter/asyncIncrement` somewhere and I have the following watcherSaga function

```js
function* watchAsyncIncrement() {
  yield takeEvery("counter/asyncIncrement", incrementAsync);
}
```

The workerSaga generator function could accept the action prop I know that, but what about the dispatch prop? Without the dispatch prop we could still declare side effect by using `put` which is built in redux saga. Can someone help?

**Comment by neurosnap** [comment]
See here: https://redux-saga.js.org/docs/api#takeeverypattern-saga-args

You can pass arguments to the end of `takeEvery` and they will get sent to `incrementAsync`.

```ts
function* incrementAsync(dispatch, action) {}

function* watchAsyncIncrement(dispatch) {
  yield takeEvery("counter/asyncIncrement", incrementAsync, dispatch)
}
```

**Comment by neurosnap** [comment]
You got half-way there.  There is no code within redux-saga that passes `dispatch`, this is considered an anti-pattern.  You should just use `put` to dispatch actions inside a generator.

Having said that, to get your example to work, you must pass `store.dispatch` into the `sagaMiddleware.run` function.  Then you must pass it to the `rootSaga` and then your watch function.  I've forked your codesandbox and got it working: https://codesandbox.io/s/affectionate-surf-hyeqcv
