### ISSUE TITLE
Continue execution of saga after task cancellation

### ISSUE THREAD

**Issue by james-filtness** [redux-saga/redux-saga#2283]
I have the following code:

```
while (true) {
   const action = yield take(START_POLLING);
   yield race([
     call(poll(), action),
     take(STOP_POLLING),
   ]);
}

poll() {
  // hit some poll endpoint on the server
  const data = callServer();
  // if the response is some status call some function to handle the response
  if (data.status === 'SUCCESS') {
      yield put(STOP_POLLING);
      // do something with the response here
     doSomething();
  }
}
```

When the `STOP_POLLING` action is dispatched in the `poll` function, the execution of the `poll` function is stopped because Redux Saga cancels the losing effect in the race (https://redux-saga.js.org/docs/advanced/TaskCancellation).

Is there any way around this? I need to be able to cancel the polling but still have the `doSomething` function in the example above run. It's important in this case that the polling is stopped before the `doSomething` function is executed.

### Environment
redux-saga: 1.1.3

**Comment by neurosnap** [comment]
Greetings!  Hmm, I might need to understand the business logic a little better here.  When `poll` gets cancelled, does `callServer` get cancelled as well or does it finish the HTTP request/response?  If you know it will always finish, regardless of the task getting cancelled, then in the link you cited it demonstrates what you can do.  You wrap the code inside `poll` with a `try {} finally {}` and check for the `yield cancelled` or if it always needs to be called you can skip it entirely.

Can you try this to see if it works?

```js

poll() {
  let data = null;
  try {
    // hit some poll endpoint on the server
    data = callServer();
  } finally {
     // if the response is some status call some function to handle the response
    if (data.status === 'SUCCESS') {
        yield put(STOP_POLLING);
        // do something with the response here
       doSomething();
    }
  }
}
```

**Comment by james-filtness** [comment]
Hi, thanks for you reply. So I had tried to use the finally block but yield cancelled was never true when I expected it to be. Your response made me realise I don't need to check for cancelled anyway. I've now moved the code in to the finally block and it works as I need it to: The Polling is halted but my `doSomething` function is still called.

Thanks for your help!
