### ISSUE TITLE
takeLatest is not accepting args

### ISSUE THREAD

**Issue by Deivbid** [redux-saga/redux-saga#2284]
### Description
Hello! I'm migrating from `redux-saga@0.16` to `v1.1.3` (the latest one) and I found that using `takeLatest` is giving me this error: `Expected 2 arguments, but got 3` ... this is one of the lines with that error  

```
function* watchCurrentContextItem(featureId: string) {
    yield takeLatest(ContextTypeKeys.SET_CURRENT_QTI_CONTEXT_ITEM, setDetailsPanelContextValue, [ featureId ]);
}

// AdDed [ featureId ] as an array because of the `args` param of takeLatest but was inly `featureId` without the array before  
```

The [docs](https://redux-saga.js.org/docs/advanced/Concurrency/) says clearly that I can pass an array of args after the saga, so I don't understand what I'm I doing wrong ??? 

BTW I'm importing the takeLatest from `import { takeLatest } from 'redux-saga/effects';`

**Comment by Andarist** [comment]
Could you prepare a TS playground with the problem depicted there?
