### ISSUE TITLE
redux-saga delay effect max milliseconds

### ISSUE THREAD

**Issue by joerndyherrn** [redux-saga/redux-saga#2289]
#### Description of the bug/issue
The delay redux-saga/effects wont delay when the time in milliseconds is greater than a specific number it wont delay without any warning/error or similar.

#### Example
```
function* logoutAfterTokenExpiration(userToken) {
    const timeTillExpiration = Token.getTimeTillExpiration(userToken);

    yield delay(timeTillExpiration);
    yield put(AuthActions.logout());
}
```

In our case the timeTillExpiration was 63071998615 milliseconds - so mistakenly about 729 days.

https://codesandbox.io/s/redux-saga-issue-template-forked-80qczq?file=/src/sagas/index.js

### Actual results
The process is not delayed and following actions are performed instantly.

### The Expected results
Even nobody would set such a high delay there should be an error, delaying the maximum possible amount of milliseconds or similar instead of skipping the delay.

### Environment information
├── @fortawesome/fontawesome-free@5.15.3
├── bootstrap@5.0.2
├── chartist-plugin-legend@0.6.2
├── chartist@0.11.4
├── del@6.0.0
├── eslint-config-airbnb-base@14.2.1
├── eslint-plugin-import@2.23.4
├── eslint@7.30.0
├── gulp-add-src@1.0.0
├── gulp-clean-css@4.3.0
├── gulp-clean@0.4.0
├── gulp-concat@2.6.1
├── gulp-expect-file@2.0.0
├── gulp-favicons@3.0.0
├── gulp-less@5.0.0
├── gulp-livereload@4.0.2
├── gulp-minify@3.1.0
├── gulp-plumber@1.2.1
├── gulp-remove-empty-lines@0.1.0
├── gulp-replace@1.1.3
├── gulp-strip-css-comments@2.0.0
├── gulp-watch@5.0.1
├── gulp-zip@5.1.0
├── gulp@4.0.2
├── jquery@3.6.0
├── lightbox2@2.11.3
├── moment@2.29.1
├── natives@1.1.6
├── nodemailer@6.6.2
├── run-sequence@2.2.1
├── stylelint-config-standard@22.0.0
├── stylelint@13.13.1
└── yargs@17.0.1

**Comment by neurosnap** [comment]
Thanks for submitting this issue!  [Under the hood, we use `setTimeout` for the delay effect.]

> [Maximum delay value](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#maximum_delay_value)
> Browsers including Internet Explorer, Chrome, Safari, and Firefox store the delay as a 32-bit signed integer internally. This causes an integer overflow when using delays larger than 2,147,483,647 ms (about 24.8 days), resulting in the timeout being executed immediately.

Maybe we could check the time in development and log an error if the value is greater than the max?

**Comment by joerndyherrn** [comment]
@neurosnap Yeah I'd appreciate a development error log

And would it be nice to decrease the timeout to the maximum possible value (2,147,483,647 ms) if it's set higher?

**Comment by Andarist** [comment]
I don't think that decreasing the timeout is something that we should do. While maybe closer to the "intended" timeout it could potentially obscure the problem and hide it from the user, whereas this problem should always be fixed on the user's side.

**Comment by s4nju** [comment]
Hi, If you allow, I would love to work on this issue🙏, if yes can you please guide what should be the expected behavior? 😅 Thanks a lot in advance.

**Comment by sbaechler** [comment]
I just ran into the same issue.

A check and a warning (or even an error) would be nice.
