### ISSUE TITLE
is this library still being maintained?

### ISSUE THREAD

**Issue by ekacahya21** [redux-saga/redux-saga#2298]
I'm really helpful with this library at the first time i use 4 years ago. But when i want to start new project with this, I've seen that latest update is 3 years ago.

**Comment by neurosnap** [comment]
Yep!  Is there anything we can help you with?

**Comment by ekacahya21** [comment]
Just checking out if it's still reliable to use 😉. Thank tou @neurosnap

**Comment by neurosnap** [comment]
No worries!

**Comment by Helpico** [comment]
The saga library will go on working fine, being maintained. Well, it's a great  news! Redux-Saga is a masterpiece!
