### ISSUE TITLE
Babel version requirement

### ISSUE THREAD

**Issue by KevinBurton** [redux-saga/redux-saga#2305]
I try to run this (npm start) tutorial (redux-saga-beginner-tutorial) and I get an error:

Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

I am not sure how to get the correct or expected Babel version?

### Description
Please provide some context about the problem and some code examples if relevant.
The best way to provide an example is repository or use [Code Sandbox](https://codesandbox.io/)(there is a [prepared template](https://codesandbox.io/s/0q9yzno0zv?module=%2Fsrc%2Fsagas%2Findex.js) for Code Sandbox)

**Comment by neurosnap** [comment]
So I just ran the beginner tutorial without issues.  What version of node are you running?

**Comment by neurosnap** [comment]
Closing this issue for now since it appears to be working as expected.  I'd be more than happy to reopen to continue the discussion.
