### ISSUE TITLE
Effect or code pattern like `all` that fires effects consecutively rather than concurrently?

### ISSUE THREAD

**Issue by Slapbox** [redux-saga/redux-saga#2311]
Note: I assume that technically `yield all` does run consecutively in a sense, I'm not sure how to phrase the title more clearly, but hopefully the issue text will make the problem clear.

----

Perhaps this isn't necessary and I'm overlooking something simple. The only ways I can think to handle this currently require extensive and verbose code.

The rationale for this in our case is that we need to fire an effect for every item in an array, but we also want to run a `progressUpdater` function after each call.

The problem is that, because `progressUpdater` is a callback in the `doThing` function, all the `progressUpdater` functions fire after all the core logic of `doThing`, rather than being able to call the `progressUpdater` before the next item is mapped over.

**For example:**
```js
function* progressUpdater() {
  // ... logic
  yield put(actions.setTransient, nextVal)
}

function* doThing(item, progressUpdater) {
  yield all([
    put(someAction(item)),
    take('someAction'),
  ]);
  yield call(progressUpdater)
}
// ...
yield all(
  items.map(item => call(doThing, item, progressUpdater))
)
```

**So given an array of 5 `items` the runs look like this:**

> doThing
> doThing
> doThing
> doThing
> doThing
> progressUpdater
> progressUpdater
> progressUpdater
> progressUpdater
> progressUpdater

**Is there any simple way to have it run like below instead?**

> doThing
> progressUpdater
> doThing
> progressUpdater
> doThing
> progressUpdater
> doThing
> progressUpdater
> doThing
> progressUpdater

Note that `progressUpdater` doesn't _need_ to be a callback necessarily, it just needs to run between before the next call to `doThing`

----

Code like this produces a list of effects with `delay` between each `call`, but it still all fires at once as far as I can tell, rather than instituting a delay between each `call`

The `effects` array looks like this:

> call
> delay
> call
> delay
> call
> delay
> call
> delay
> call
> delay

```js
const effects = items.flatMap(n => [
  call(doThing, item, progressUpdater),
  delay(5000),
]);
yield all(effects);
```

**Comment by Slapbox** [comment]
Gotta love rubber ducking.

This code _almost_ works. The only issue is that suddenly the `yield all` inside of `doThing` gets stuck waiting for a `take` that never fires (but this worked fine 


```
const effects = items.flatMap(n => [
  call(doThing, item, progressUpdater),
  delay(5000),
]);

// yield all(effects); // progressUpdater doesn't run as intended, but `take` works

// Below method makes progressUpdater fire as expected, but breaks `take`
for (const effect of effects) {
  yield effect;
}
```

**Comment by Slapbox** [comment]
I think this works?

```js
const effects = items.flatMap(n => [
  spawn(doThing, item, progressUpdater),
  delay(5000),
]);

for (const effect of effects) {
  yield effect;
}
```

I'm not sure that I understand why using `call` blocks execution though. I know it's blocking, but I'm not sure how it actually blocks the downstream `take` here.

**Comment by neurosnap** [comment]
My recommendation is to not use `all` for something that needs to be consecutive. What about something like this?

```ts
function* progressUpdater() {
  // ... logic
  yield put(actions.setTransient, nextVal)
}

function* doThing(item, progressUpdater) {
  yield all([
    put(someAction(item)),
    take('someAction'),
  ]);
  yield call(progressUpdater)
}

for (let i = 0; i < items.length; i += 1) {
  yield call(doThing, item, progressUpdater);
}
```
