### ISSUE TITLE
cancel effect does not stop takeLeading

### ISSUE THREAD

**Issue by willyamdev** [redux-saga/redux-saga#2313]
I have an application that uses a takeLeading effect and it works well at the first action call, but sometimes I need to cancel the takeLeading effect based in some validations, at this point all works well, but when I try to run my action call again it not trigger the takeLeading effect, it seems to be blocked, it's like cancel effect didn't canceled the takeLeading effect.

**Comment by willyamdev** [comment]
Yep, 

so basically this is my rootSaga:

```js 
export default function* rootSaga() {
yield all([
   takeLeading(VisitActionTypes.RELEASE_GATE_VISIT_REQUEST, releaseGateVisit),
 ]
}
```

this is my saga file and the releaseGateVisit function
```js 

export function* releaseGateVisit(action: AnyAction) {
     const {
        visit: {
          containers,
          identification: { quantity },
        },
        ocrContainer: { selectedOCRContainers },
      }: ApplicationState = yield select(getGlobalState);

      try {
        //validations
        yield all([
          call(checkContainerTare, containers),
          call(checkMGW, containers),
          call(checkWeighings, containers, quantity),
          call(checkSeals, containers),
          call(checkContainerIso, containers),
          call(checkTruckBodyAndPosition, containers),
          call(
            checkFullContainersSelectedOCRContainers,
            selectedOCRContainers,
            containers
          ),
        ]);
      } catch (error: any) {
        yield all([
          put(
            createWarningModal({
              isErrorModal: false,
              title: "Error",
              message: error.message,
            })
          ),
          put(openVisitError()),
          cancel(), <------ cancel effect
        ]);
      }
}
```

this is one example of one of the validations functions that I call


```js 
export const checkSeals = (containers: Container[]) => {
  const attachments = containers.flatMap((d) => d.attachments);

  if (containers.some((d) => d.seals.length === 0 && !d.noSeals))
    throw new Error(
      `All unmarked containers that do not contain seals need to inform seals!`
    );

  if (!attachments.some((d) => d.type === "Lacre"))
    throw new Error(`There must be at least one seal-type photo attached!`);
};
```

**Comment by neurosnap** [comment]
What happens if you remove the `cancel` call?  I'd also add some log statements to make sure code you're expecting to get called actually does get called.

**Comment by willyamdev** [comment]
I have been debuging my application with cancel effect and without it, and if I remove the cancel effect it continues the saga function, no problems about that. With cancel effect it stops the saga but as I said, I can not call this saga again. All seems to work well, but if I call cancel effect it never let me call the saga again.

**Comment by willyamdev** [comment]
Great, I will take a look on it, I will try to make my root saga more fault tolerant with it.

 Thank you!
