### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by alphakex2** [redux-saga/redux-saga#2314]
Hello, I'm trying out redux-saga for the first time and I've ran into an issue where the api gets called infinitely. I get data, but infinitely. What I'm I doing wrong?

```
export const getUsersRequest = createAction(Action.GET_USERS)

const addressSlice = createSlice({
  name: "address",
  initialState,
  reducers: {
    getUsers: (state, action: PayloadAction<User[]>) => {
      state.users = action.payload
    }
  },
})
```

Here is the saga

```
function* getUsersWorker(): SagaIterator {

  try {
    const {data} = yield call(getUsersApi)
    
    yield put(getUsers(data.data))
    
  } catch (error) {
    console.log(error)
  }
}

 function* watchGetUsersRequest() {
  yield takeEvery(getUsersRequest.toString(), getUsersWorker)
 }
```

if I use take in a combined worker and watcher it works perfectly:

```
function* getUsersWorker(): SagaIterator {

  try {

    yield take(getUsersRequest.type)
    const {data} = yield call(getUsersApi)
    
    yield put(getUsers(data.data))
    
  } catch (error) {
    console.log(error)
  }
}
```

**Comment by alphakex2** [comment]
Greetings Neurosnap....I'm calling it on component load

const Address: React.FC<AddressProps> = () => {
  const dispatch = useAppDispatch()
  useEffect(() => {
    dispatch(getUsersRequest())
  }, [dispatch])
  return (
    <div className="flex justify-center my-40">
      <List />
    </div>
  )
}

export default Address

**Comment by neurosnap** [comment]
I would remove the dispatch dependency from your useEffect.

Can you show me how your root saga is setup?

**Comment by alphakex2** [comment]
Thanks for the response neurosnap. I'm still getting the loop without the useEffect. I tried using a button <button onClick={() => getUsersRequest()}>  </button> but Immediately click event is fired i get the loop. 

export default function* rootSaga() {
  yield all([...usersSagas])
}
my store configuration
const saga = createSagaMiddleware()

export const store = configureStore({
  reducer: {
    counter: counterReducer,
    address: addressReducer,
  },
  middleware: [saga],
})
saga.run(rootSaga)

**Comment by neurosnap** [comment]
```
yield all([...usersSagas])
```

Can you should me what `usersSagas` looks like?

**Comment by alphakex2** [comment]
Hello neurosnap, here is the repo https://github.com/alphakex2/react-redux-saga...if you build and run it, you'll it making unlimited API requests

**Comment by alphakex2** [comment]
That was one nasty bug on my part, thanks for all your help bro... cheers!!!
