### ISSUE TITLE
take(channel) occur error in typescript, how to fix it? 

### ISSUE THREAD

**Issue by anjunlee** [redux-saga/redux-saga#2329]
```
import { actionChannel, put, take } from "redux-saga/effects";

function* watchResponse() {
    type resp = { type: string, payload: any }
    const responseChan: resp = yield actionChannel('ORDER_BOOK');
    while (true) {
      const { payload } = yield take(responseChan)
    }
}

export default watchResponse
```

> No overload matches this call.
  Overload 1 of 3, '(pattern?: ActionPattern<Action<any>> | undefined): TakeEffect', gave the following error.
    Argument of type 'resp' is not assignable to parameter of type 'ActionPattern<Action<any>> | undefined'.
  Overload 2 of 3, '(pattern?: ActionPattern<Action<any>> | undefined): TakeEffect', gave the following error.
    Argument of type 'resp' is not assignable to parameter of type 'ActionPattern<Action<any>> | undefined'.
  Overload 3 of 3, '(channel: TakeableChannel<unknown>, multicastPattern?: Pattern<unknown> | undefined): ChannelTakeEffect<unknown>', gave the following error.
    Argument of type 'resp' is not assignable to parameter of type 'TakeableChannel<unknown>'.
      Property 'take' is missing in type 'resp' but required in type 'TakeableChannel<unknown>'.ts(2769)
index.d.ts(247, 3): 'take' is declared here.

**Comment by Andarist** [comment]
Your type annotation is wrong, it should be:
```ts
const responseChan: Channel<resp> = yield actionChannel('ORDER_BOOK');
```

**Comment by anjunlee** [comment]
> Your type annotation is wrong, it should be:
> 
> ```ts
> const responseChan: Channel<resp> = yield actionChannel('ORDER_BOOK');
> ```

thanks, it's working
