### ISSUE TITLE
How to know when the task queue is empty

### ISSUE THREAD

**Issue by madcapnmckay** [redux-saga/redux-saga#2335]
I am attempting to write some dev tools for redux-saga that use the `SagaMonitor` interface.  I have helpers for tracking what effects are currently pending/resolved/rejected etc. 

One thing I am struggling with is how to know when all queued effects have been processed. Is there a signal or piece of state I can read to know this?

For example, say we are running the below saga
```
function * myTask() {
    while(true) {
        const action = yield take('SOME_ACTION');
        if (action.payload.value === 1) {
            yield put({ type: 'SOME_OTHER_ACTION' });
        }
    }
}
```

At some point, all effects have been triggered and/or resolved and we are in a steady state waiting for the next action. The queue is empty so to speak (this may not be the correct nomenclature).

How do I know when I'm in that state, would the next tick be the correct point to mark this assertion?

**Comment by neurosnap** [comment]
Hi!  Do you want to buffer these actions?  If so I would look into an [`actionChannel`](https://redux-saga.js.org/docs/advanced/Channels) which will help with that.  This will help you build an actual queue.

To further help, I'd like to better understand your use case, why do you want to know if your "queue" is empty?

**Comment by neurosnap** [comment]
Closing issue for now.  Please feel free to follow up with any feedback and I'll reopen.
