### ISSUE TITLE
Argument of type 'string' is not assignable to parameter of type 'TakeableChannel<unknown>'

### ISSUE THREAD

**Issue by Mohammed-Mounir** [redux-saga/redux-saga#2336]
### Description
dispatching action with payload, produces this typescript error: Argument of type 'string' is not assignable to parameter of type 'TakeableChannel'.
.

export default function* watchAuth() {
yield* takeLatest(startAuth.toString(), handleAuthUser); // Argument of type 'string' is not assignable to parameter of type 'TakeableChannel'.
}

using:
"@reduxjs/toolkit": "^1.8.5",
"typed-redux-saga": "^1.5.0",

**Comment by parnekov** [comment]
add **type: string** near payload type
function* sagaFunction({ payload: { params, onSuccess, onError } }: {payload: Payload, type: string}): Generator{}

**Comment by challet** [comment]
Or as the second argument of the typed action creator : 

```ts
createSlice({
  reducers: {
    actionName: (state, action: PayloadAction<PayloadType, string>) => …
  }
})
```

**Comment by challet** [comment]
As soon as an extra param is added the problem gets back : 

```
yied takeLeading(action, subSaga, extraParam);
…
function* subSaga(extraParam, {payload}: PayloadAction<PayloadType, string>): Generator
```

To fix it, I had to explicitly name the type : 

```
yied takeLeading(action, subSaga, extraParam);
…
function* subSaga(extraParam, {payload}: PayloadAction<PayloadType, "slice/actionName">): Generator
```

**Comment by thomasuster** [comment]
This worked for a codebase that didn't have toolkit.

//before
```ts
function* someSaga({something}) {
	...
}
```

//after
```ts
function* someSaga({something}:ReturnType<typeof actions.someAction>) {
	...
}
```
