### ISSUE TITLE
yield and takeLatest not working with jest 

### ISSUE THREAD

**Issue by komalharmale** [redux-saga/redux-saga#2366]
Env version Details
  "react": "18.1.0",
    "react-native": "0.70.6",
    "react-redux": "^8.0.5",
    "redux": "^4.2.1",
    "redux-saga": "^1.2.2"

when i run the app normally redux-sagas methods execute properly but when i test same with jest it's not executing the methods
//////saga.js

import {takeLatest,put,delay,call }from 'redux-saga/effects';
import {INCREASE_BURGER,DECREASE_BURGER} from '../Burger/burgerActionTypes';

function* increaseAsync(){
  console.log("function call")
  console.log("saga-begin")
  yield delay(4000);
    yield put({
    type:"INCREASE_BURGER_UP",
    payload:5
})
}

export default function* watchCounterIncrease(){

    yield takeLatest(INCREASE_BURGER,increaseAsync);
}

**Comment by neurosnap** [comment]
Hi!

Could you please share your jest test? Thanks!

**Comment by komalharmale** [comment]
import  watchCounterIncrease from '../MyAssets/Redux/saga/saga';

describe('App  Screen', () => {
  const result=watchCounterIncrease();
  console.log(result.next().value);
  console.log(result.next());
})

**Comment by komalharmale** [comment]
Any suggestion?

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by komalharmale** [comment]
https://codesandbox.io/s/redux-saga-counter-example-forked-32wp08?file=/index-test.js

**Comment by komalharmale** [comment]
Thank you for your support, but my concern is if we try to console this value then it is returning as undefined.
`iter.next().value` as well as `delay(1000)` is returning as undefined that is the reason the test cases are passing because the both value having undefined as result but in actual it's not giving as expected output.

**Comment by komalharmale** [comment]
closing as issue is not related to the this library
