### ISSUE TITLE
Why not use the await and async instead of the generator and yield?

### ISSUE THREAD

**Issue by hongNianYS** [redux-saga/redux-saga#2384]
### Description
Please provide some context about the problem and some code examples if relevant.
The best way to provide an example is repository or use [Code Sandbox](https://codesandbox.io/)(there is a [prepared template](https://codesandbox.io/s/0q9yzno0zv?module=%2Fsrc%2Fsagas%2Findex.js) for Code Sandbox)

**Comment by Andarist** [comment]
https://github.com/redux-saga/redux-saga/tree/9c2af0c453898bd4c9eef42b364f9f6f212adb2e#redux-saga-chooses-generators-over-asyncawait
