### ISSUE TITLE
Update peer dependencies to include `redux@5` (currently beta)

### ISSUE THREAD

**Issue by markerikson** [redux-saga/redux-saga#2401]
We're hoping to release the full wave of Redux package major versions by the first week of December.  That includes RTK 2.0, and Redux core 5.0.

I see that `@redux-saga/core` currently includes `"redux": "^4.0.4"` as an actual dependency.  Got a couple questions / requests:

- Could you put out a beta of some kind that ups the dep to `"redux": "^5.0.0-beta.0"`, and test things on your end?
- Does it make sense for Redux to be a _peer_ dependency rather than a full dependency?

**Comment by Andarist** [comment]
> Could you put out a beta of some kind that ups the dep to "redux": "^5.0.0-beta.0", and test things on your end?

We could do that but it might be an overkill here. It would probably be just fine to release a new version with updated ranges. OTOH, we might not be able to do that right now since `redux` is the dependency here and not a peer dependency.

> Does it make sense for Redux to be a peer dependency rather than a full dependency?

That would make sense but it could be seen as a breaking change. I think that we should:
- inline `compose` (since that's the only actual runtime "dependency" that we have on `redux`)
- inline types that we import from `redux` (structural typing in TS FTW)
- move redux from a dependency to an optional peer dep

I think all of that combined would allow us to avoid all of the breaking change concerns

**Comment by Methuselah96** [comment]
Unfortunately I don't think the redux@4 `Middleware` type and redux@5 `Middleware` type are assignable to each other, so that might not work unless we can common with a type that is assignable to either.

**Comment by neurosnap** [comment]
@Andarist and I are working through the type issues, hopefully we will be able to figure some common middle-ground.  Will update when we have more time to investigate.

**Comment by Methuselah96** [comment]
Redux 5 [just dropped](https://github.com/reduxjs/redux/releases/tag/v5.0.0). Any updates?

**Comment by Andarist** [comment]
I'll try to prioritize this to get something out of the doors soon-ish

**Comment by Andarist** [comment]
@Methuselah96 I fixed this Middleware problem by annotating `next` as `(action: never) => unknown`. It's not 100% correct... but I think it should be OK for most practical purposes. The middleware is not something the user is meant to interact with and `applyMiddleware` accepts it so that's the important part.

**Comment by ribeaud** [comment]
So guys, do you plan an update/release soonish here?

**Comment by jorgevds** [comment]
> @Methuselah96 I fixed this Middleware problem by annotating `next` as `(action: never) => unknown`. It's not 100% correct... but I think it should be OK for most practical purposes. The middleware is not something the user is meant to interact with and `applyMiddleware` accepts it so that's the important part.

We recently tried updating our store config to use RTK's configureStore instead, but the types of Middleware seem to be incompatible. Concatenating createSagaMiddleware (inside an array ofc) to RTK's getDefaultMiddleware does not work. Is there any alternative to casting createSagaMiddleware to any in this context?

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by jorgevds** [comment]
> Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

I'm unable to reproduce this: [codesandbox](https://codesandbox.io/p/sandbox/lively-glitter-xmwj59?file=%2Fsrc%2Findex.ts%3A8%2C19&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsiu2oa200063b6du79m6pmp%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsiu2oa200023b6dirkei2od%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsiu2oa200033b6dggnibmmh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsiu2oa200053b6dkc80nkyv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B90%252C10%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsiu2oa200023b6dirkei2od%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsiu2oa200013b6dvgoxwsmn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsiu8ve8003q3b6dui3afdkz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsiuf1ti00023b6f92kud4pz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A19%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A19%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clsiu2oa200023b6dirkei2od%2522%252C%2522activeTabId%2522%253A%2522clsiuf1ti00023b6f92kud4pz%2522%257D%252C%2522clsiu2oa200053b6dkc80nkyv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsiu2oa200043b6dfaimtxr3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsiu2oa200053b6dkc80nkyv%2522%252C%2522activeTabId%2522%253A%2522clsiu2oa200043b6dfaimtxr3%2522%257D%252C%2522clsiu2oa200033b6dggnibmmh%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsiu2oa200033b6dggnibmmh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Seems to work just fine out of the box, so we're probably doing something wrong on our end.

**Comment by Yemisrach15** [comment]
> > Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.
> 
> I'm unable to reproduce this: [codesandbox](https://codesandbox.io/p/sandbox/lively-glitter-xmwj59?file=%2Fsrc%2Findex.ts%3A8%2C19&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsiu2oa200063b6du79m6pmp%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsiu2oa200023b6dirkei2od%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsiu2oa200033b6dggnibmmh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsiu2oa200053b6dkc80nkyv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B90%252C10%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsiu2oa200023b6dirkei2od%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsiu2oa200013b6dvgoxwsmn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsiu8ve8003q3b6dui3afdkz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsiuf1ti00023b6f92kud4pz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A19%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A19%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clsiu2oa200023b6dirkei2od%2522%252C%2522activeTabId%2522%253A%2522clsiuf1ti00023b6f92kud4pz%2522%257D%252C%2522clsiu2oa200053b6dkc80nkyv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsiu2oa200043b6dfaimtxr3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsiu2oa200053b6dkc80nkyv%2522%252C%2522activeTabId%2522%253A%2522clsiu2oa200043b6dfaimtxr3%2522%257D%252C%2522clsiu2oa200033b6dggnibmmh%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsiu2oa200033b6dggnibmmh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
> 
> Seems to work just fine out of the box, so we're probably doing something wrong on our end.

Have you gotten any solution? I'm also getting a typescript error when applying saga as middleware with redux toolkit's `configureStore`. 

```
const store = configureStore({
   ......
    middleware: getDefaultMiddleware => [
      ...getDefaultMiddleware(),
      sagaMiddleware,
    ],
   ......
});
```

**Comment by jorgevds** [comment]
> > > Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.
> > 
> > 
> > I'm unable to reproduce this: [codesandbox](https://codesandbox.io/p/sandbox/lively-glitter-xmwj59?file=%2Fsrc%2Findex.ts%3A8%2C19&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsiu2oa200063b6du79m6pmp%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsiu2oa200023b6dirkei2od%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsiu2oa200033b6dggnibmmh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsiu2oa200053b6dkc80nkyv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B90%252C10%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsiu2oa200023b6dirkei2od%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsiu2oa200013b6dvgoxwsmn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsiu8ve8003q3b6dui3afdkz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsiuf1ti00023b6f92kud4pz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A19%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A19%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clsiu2oa200023b6dirkei2od%2522%252C%2522activeTabId%2522%253A%2522clsiuf1ti00023b6f92kud4pz%2522%257D%252C%2522clsiu2oa200053b6dkc80nkyv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsiu2oa200043b6dfaimtxr3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsiu2oa200053b6dkc80nkyv%2522%252C%2522activeTabId%2522%253A%2522clsiu2oa200043b6dfaimtxr3%2522%257D%252C%2522clsiu2oa200033b6dggnibmmh%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsiu2oa200033b6dggnibmmh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
> > Seems to work just fine out of the box, so we're probably doing something wrong on our end.
> 
> Have you gotten any solution? I'm also getting a typescript error when applying saga as middleware with redux toolkit's `configureStore`.
> 
> ```
> const store = configureStore({
>    ......
>     middleware: getDefaultMiddleware => [
>       ...getDefaultMiddleware(),
>       sagaMiddleware,
>     ],
>    ......
> });
> ```

We upgraded RTK from version 1.9.7 to ^2.2.0 and that seemed to do the trick. Peer dependencies got upgraded when bumping as well: Redux (5.0.1), Immer (10.0.3), Redux-thunk (3.1.0), and Reselect (5.1.0). Hope that helps.

**Comment by markerikson** [comment]
@Yemisrach15 Don't use the spread operator with `getDefaultMiddleware()`. TS loses type information. Instead, use `getDefaultMiddleware().concat(sagaMiddleware)`.
