### ISSUE TITLE
feature request: interface for integration with other frameworks (like Vue)

### ISSUE THREAD

**Issue by yannvr** [redux-saga/redux-saga#2404]
### Description
The only good thing about React is redux-saga as it decouples user flows from the UI. Surprisingly, I've not seen any other frameworks with any application side-effect solutions. Is it possible to decouple redux-saga from React so it becomes agnostic? Maybe by providing an interface that allows for the integration with other frameworks like Vue?

**Comment by Andarist** [comment]
It's already decoupled. `runSaga` API exists exactly for this reason: https://redux-saga.js.org/docs/advanced/UsingRunSaga

**Comment by yannvr** [comment]
Great, thanks for pointing this out!
