### ISSUE TITLE
flow-type definitions

### ISSUE THREAD

**Issue by ryyppy** [redux-saga/redux-saga#358]
Hi!

I was wondering if there are any flow-type definitions for redux-saga out there?
If not, I would then probably start writing them, but I need a helping hand of verifying the output, so we don't publish anything incompatible :-)

**Comment by tomauty** [comment]
Haven't seen any in the wild. There are TypeScript definitions here though, so it shouldn't be too hard to convert. I'm interested as well.

**Comment by ryyppy** [comment]
I linked the related flow-typed issue and will hopefully start working on it soon!
The thing is, TypeScript definitions actually look very similar, but they sadly behave differently in very subtle ways, which makes them hard to convert... we will see how far I get :-)

**Comment by Beingbook** [comment]
Is this in progress?

**Comment by ryyppy** [comment]
Yeah. Progress is tracked in the linked flow-typed issue, but right now I am quite busy with other stuff :-/ ... not sure when I can create a first working PR

**Comment by tomauty** [comment]
Do you have a branch open? I deal w/ redux-saga + flow "errors" daily and would be happy to start adding basic definitions.

**Comment by ryyppy** [comment]
Sure, will do this as soon as possible... the thing is that flow cannot deal with these super generic interfaces (like strongly typed call() and such) ... and I only have a very raw scaffold

**Comment by tomauty** [comment]
Any update on this?

**Comment by ryyppy** [comment]
Man I am so sorry,... right now I have so many other tasks that I can't work on it properly.
I was also waiting for some syntax enhancements of `flow`, since they also introduced named exports and other stuff lately.

https://gist.github.com/ryyppy/23db18faba8e5e031b1f81adfc050eb9

This is what I wrote so far, but I already completely lost the track and would also probably pull in the newest progress of redux-saga as well.

**Comment by ryyppy** [comment]
Also a good thing about newest `flow` releases is that they completely reimplemented the union-evaluation, which will be very useful for this lib as well.

**Comment by pgherveou** [comment]
@ryyppy 
Do you think there is a way to define return type of yield statement in this typical redux-saga code? 

```js
/* @flow */

declare var getFoo: () => Promise<string>
declare var call: (fn: () => Promise<any>) => any

function * mySaga(): Generator<*, *, *> {
  // I am expecting a string 
  // but yield type can't really be type checked, and are always maybe type 
  const foo: ?string = yield call(getFoo)

  // only workaround that works for me for now is to force cast and add all this extra parentheses
  const foo: string = ((yield call(getFoo)): any)
}

```

**Comment by ryyppy** [comment]
Hm, yeah generic `Next` values are problematic. 
To get the full type-safetiness, you have to do some type refinement:

```
function *mySaga(): Generator<*, *, *> {
  // I am expecting a string
  // but yield type can't really be type checked, since they are dynamic
  // other issue are that return type of yield are maybe type
  const foo = yield call('something');

  // In the corresponding branches, flow
  // will recognize the different types
  // of foo 
  switch(typeof foo) {
    case 'string':
      console.log(foo.length);
      break;
    case 'number':
      console.log(foo.toFixed(2));
      break;
    default:
      console.log('meh');
  }

  // Of course, also with if()
  if (typeof foo === 'string') {
    console.log(foo.length);
  }
}

const iter = mySaga();

iter.next('asdf');
iter.next(1);
```

**Comment by ryyppy** [comment]
Here is a sound explanation of samgoldman why this is designed like this: https://github.com/facebook/flow/issues/2080

**Comment by pgherveou** [comment]
thks for the explanations @ryyppy

**Comment by tychota** [comment]
@ryyppy can I help you ?

**Comment by ryyppy** [comment]
@tychota : if you are able to get something going, I can definitely do the review and testing for it :-) ... a few posts above is my gist to what I started... right now I build so much vim infrastructure for flow and I barely can find time for that right now

**Comment by ryyppy** [comment]
Short update: I feel confident now that I can publish the redux-saga libdefs latest in the end of this week. 

Short teaser: https://twitter.com/ryyppy/status/767470833472311297

**Comment by stratospark** [comment]
@ryyppy 

I'm trying to use the latest redux-saga defs, and I'm running into a bit of trouble getting `takeLatest` to typecheck.

Here's an example that I'm trying to figure out:
```
function* saga0(): Generator<IOEffect, string, string> {
  let foo = yield fork((): Promise<number> => Promise.resolve(1));
  return '';
}

export function* saga() : Generator<IOEffect, *, *> {
  takeLatest('FOO', saga0);
  yield fork(takeLatest, 'FOO', saga0);
}
```

When takeLatest is called directly, it type checks, but when I declaratively fork takeLatest, I'm getting some lengthy type check errors.

I'm pretty new to both redux-saga and flowtype, so perhaps I'm not using takeLatest correctly. I decided to fork takeLatest for easier testing of the generator.

Any insights? Everything else redux-saga related is type checking and I'm really looking forward to increasing my type coverage. Thanks!

**Comment by ryyppy** [comment]
Hmm, this is because the `takeLatest` requires a `Generator` type, but gets my own backed simulation of a `Generator`...

I did this to my definitions and the tests run through:
```
  declare interface TakeXRet extends Generator<*,*,*> {
    name: string,
  }
```

Not sure if I should patch this... probably yes :-)

**Comment by ryyppy** [comment]
@stratospark Could I ask you to open an issue on flow-typed?

**Comment by Andarist** [comment]
Thanks to the great work by @Alxandr, `flow-typed` has now updated [`redux-saga` typings](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/redux-saga_v0.16.x/flow_v0.56.0-/redux-saga_v0.16.x.js). Closing the issue now, if there are any problems with new typings, please report them here by creating a new issue or fix them in `flow-typed` repository.

If you have any suggestions on what is the best way to incorporate typings directly into `redux-saga` repository - please let me know. From what I understand the biggest problem is that typings are targeting specified range of flow versions and having them directly in the repository kinda locks them down to that range and might cause problems for people using versions from outside the range.
