### ISSUE TITLE
Code snippets illegible in night mode on the docs website.

### ISSUE THREAD

**Issue by priteshgupta** [redux-saga/redux-saga#477]
The text under `.token.operator` class becomes illegible when 'Night' mode is activated on the docs website

![screen shot 2016-08-08 at 3 53 31 pm](https://cloud.githubusercontent.com/assets/848636/17499120/5bcffc26-5d80-11e6-8573-cf58ae8b9779.png)

**Comment by baldwmic** [comment]
Looks like we just need to disable the `background` property for `token.operator` selector

![screen shot 2017-04-19 at 1 08 08 am](https://cloud.githubusercontent.com/assets/10538297/25164111/df3d1330-249c-11e7-8236-af592f978f0d.png).

Looks like the CSS is coming from Prism.

@Andarist it seems we need to also include the dark-theme css, as there is an [override here](https://github.com/PrismJS/prism/blob/1f699e7cf2d5cde00cc2eae12c6de1a2c6fa8c76/themes/prism-dark.css#L94) that seems to fix the issue.

**Comment by Andarist** [comment]
@baldwmic would u like to provide some help in fixing this? hadnt time to take care of this yet and probably wont have in the near future

**Comment by baldwmic** [comment]
@Andarist yes i can do it, but can you point me to where this css is being added? i don't see it in the docs folder

**Comment by Andarist** [comment]
i think its all defined in `book.json`, you can check how `redux` fixed this issue - by adding there a custom css which fixes this, but i think this could have been done with `prism` upgrade or something, but that would have to be investigated - i didnt play with gitbook much
