### ISSUE TITLE
CreateMockTask should be documented

### ISSUE THREAD

**Issue by countoren** [redux-saga/redux-saga#495]
I had to look in the source code in order to find that it is possible to mock a task and how to do it.
It will be really helpful if it can be added to documention

**Comment by yelouafi** [comment]
done http://yelouafi.github.io/redux-saga/docs/api/index.html#createmocktask

**Comment by bstro** [comment]
Did this get removed? I don't see any mention of `createMockTask` anywhere currently.

**Comment by kopax** [comment]
@yelouafi , Where did the doc go ?

**Comment by henrikra** [comment]
I really want this function to be documented too :/

**Comment by kopax** [comment]
@henrikra 

```javascript
    import { createMockTask } from 'redux-saga/lib/utils';
...
  it('should take LOCATION_CHANGE', () => {
    const watcher = createMockTask();
    const takeDescriptor = twitterFeedDataSaga.next(watcher).value;
    expect(takeDescriptor).toEqual(take(LOCATION_CHANGE));
  });
```

**Comment by henrikra** [comment]
I have made PR on this https://github.com/yelouafi/redux-saga/pull/681 If someone can check it I would appreciate that :)

**Comment by Andarist** [comment]
@henrikra 
I've just noticed that its not documented in the API reference section. Would you be willing also to provide some short description with a link to the section you have created in #681 ?

Would be greatly appreciated!

**Comment by cellog** [comment]
the import is not documented:

```javascript
import { createMockTask } from 'redux-saga/lib/utils';
```

**Comment by henrikra** [comment]
@cellog Please make Pr about it :) And correct if I have other mistakes

**Comment by cellog** [comment]
Pr is unnecessary. Just copy and paste the 1 line import statement into the code example in the docs for task cancelation

**Comment by Andarist** [comment]
just a note - you can import any util from `redux-saga/utils`
