### ISSUE TITLE
Rendering three times problem (universal saga)

### ISSUE THREAD

**Issue by aight8** [redux-saga/redux-saga#537]
I use react router and redux saga with react. The data is fetched in the componentWillMount method of the page Components. When the user is not logged in then just the public page is rendered instead of the original destination. This is the problem:
The first render cycle dispatches all required sagas in componentWillMount to get the data. Because on the first render cycle the END destination component is never rendered, so it dispatches only the "fetch current user" saga.
I tried to understand how startup sagas work, but it not works how I wanted. I have now 2. root sagas. The first one is the one with all the takeLatest forks. The second one is a startup root saga for which I wait to complete BEFORE I continue to the first render cycle.

``` JS
export function* startupSaga(args) {
  // Startup sags
  yield [
    fork(fetchCurrentUser, { payload: {} }, {}, args),
  ];
}
```

server.js:

``` JS
        const statupTasks = sagaMiddleware.run(startupSaga, { node: { req, res } });
        store.dispatch(END);

        statupTasks.done.then(() => {
```

The problem is that statupTasks.done never resolves.
1. Is this really the right way to solve that?
2. Why the statupTasks is never resolved?

Thanks!

**Comment by kencckw** [comment]
Same problem. Please help.

**Comment by Andarist** [comment]
Hey, sorry I've somehow missed your issue. Did you overcome the troubles somehow?

Could be the problem of `statupTasks` not resolving be connected to the problem mentioned [here](https://github.com/yelouafi/redux-saga/issues/707)?

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
