### ISSUE TITLE
Logging could be made better

### ISSUE THREAD

**Issue by michaelgilley** [redux-saga/redux-saga#580]
Logging could be a little smarter to handle different objects like Error, plain objects, or strings depending on what's thrown.

It'd also be helpful if stack traces could be dynamically created for development envs to produce "long stack traces".

Either way, calls to `log` should be used consistently throughout. E.g.:

https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L272
https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L293
https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L353

**Comment by Andarist** [comment]
Thanks for pointing out, will try to unify this soon

**Comment by rclai** [comment]
Yes, currently all the errors incurred are completely unhelpful, not even the exception stack object is helpful on the try/catch.

**Comment by michaelgilley** [comment]
Not sure if this applies but I've been a fan of Bluebird's longStackTraces. It'd be great if we could create something similar for debugging. Even so, perhaps some kind of error formatting that logs out a human-readable error would be nice.

**Comment by wafisher** [comment]
One other comment which may apply: the stack trace when running in JSC in iOS doesn't include the actual error, only the stack trace (without the top line). But when debugging in Chrome via React Native's remote debugging the error is logged. Happy to provide more details but it makes it almost impossible to debug without debugging remotely.

**Comment by tvedtorama** [comment]
It would also be  incredible cool if we could find a way to export saga **and effect** history to [remote-redux-devtools](https://github.com/zalmoxisus/remote-redux-devtools) - or some other log format.  Some kind of activity graph would be awesome, especially when something breaks somewhere inside something spawned.

**Comment by Andarist** [comment]
I've standardized error logs a little bit in latest release. Gonna close this issue - but if you feel there is any more room to improvement (beside implementing babel plugin for better stack traces like mentioned [here](https://github.com/redux-saga/redux-saga/issues/1199)) please create a new issue so we can discuss this further.
