### ISSUE TITLE
TypeScript CallEffect signature

### ISSUE THREAD

**Issue by tvedtorama** [redux-saga/redux-saga#619]
Hi, 

the current typescript definition for the call effect comes with max 4 arguments, and a fallback for any argument count.  

When I am working with this, the fallback is preventing type checking on arguments - and I had to remove it for it to actually use the T1,T2, etc types of the more specific signatures.  I was otherwise not stopped from passing the wrong argument list.

Can we get rid of the fallback signature and provide a five-argument version?

From this:
```
interface CallEffectFactory<R> {
  (fn: CallEffectArg<CallFunc0>): R;
  <T1>(fn: CallEffectArg<CallFunc1<T1>>,
       arg1: T1): R;
  <T1, T2>(fn: CallEffectArg<CallFunc2<T1, T2>>,
           arg1: T1, arg2: T2): R;
  <T1, T2, T3>(fn: CallEffectArg<CallFunc3<T1, T2, T3>>,
               arg1: T1, arg2: T2, arg3: T3): R;
  <T1, T2, T3, T4>(fn: CallEffectArg<CallFunc4<T1, T2, T3, T4>>,
                   arg1: T1, arg2: T2, arg3: T3, arg4: T4): R;
  (fn: CallEffectArg<CallFuncRest>, ...args: any[]): R;
}
```

To this:
```
interface CallEffectFactory<R> {
  (fn: CallEffectArg<CallFunc0>): R;
  <T1>(fn: CallEffectArg<CallFunc1<T1>>,
       arg1: T1): R;
  <T1, T2>(fn: CallEffectArg<CallFunc2<T1, T2>>,
           arg1: T1, arg2: T2): R;
  <T1, T2, T3>(fn: CallEffectArg<CallFunc3<T1, T2, T3>>,
               arg1: T1, arg2: T2, arg3: T3): R;
  <T1, T2, T3, T4>(fn: CallEffectArg<CallFunc4<T1, T2, T3, T4>>,
                   arg1: T1, arg2: T2, arg3: T3, arg4: T4): R;
  <T1, T2, T3, T4, T5>(fn: CallEffectArg<CallFunc5<T1, T2, T3, T4, T5>>,
                   arg1: T1, arg2: T2, arg3: T3, arg4: T4, arg5: T5): R;
}

```

?

**Comment by aikoven** [comment]
What if you had to pass six arguments?
Actually the right way would be to have something like this:
```ts
(fn: CallEffectArg<CallFuncRest>, 
 arg1: any, arg2: any, arg3: any, arg4: any, arg5: any, 
 ...args: any[]): R;
```
This way the last signature would be selected only for 5+ arguments functions.

**Comment by tvedtorama** [comment]
I believe you are right, haven't tested it though.

**Comment by aikoven** [comment]
@tvedtorama Can you please submit a PR? I don't have enough time for it right now. 

There are tests for TS definitions, you can add this case there. There are also other effect typings that should be fixed as well. 

If you're not up to contributing, I will fix it once I have time.

**Comment by tvedtorama** [comment]
I might be able to do a PR, I'll let you know.  Thank you.

**Comment by Andarist** [comment]
@aikoven Would you be willing to provide a PR for this?

**Comment by aikoven** [comment]
@Andarist Yes, actually I'm in the middle of reworking the typings to make them more strict, support new APIs and add tests. Will make a PR in a few days.

**Comment by aikoven** [comment]
Covered by https://github.com/redux-saga/redux-saga/pull/740.

**Comment by Andarist** [comment]
Gonna close it, as its already included in the PR that will get merged soo.
