### ISSUE TITLE
Saga for initial render?

### ISSUE THREAD

**Issue by 0xsven** [redux-saga/redux-saga#661]
In my application I am doing a few impure activities right after the initial render, like checking if there is an auth-cookie or requesting some data from an API etc.

I would love to create a saga that runs after (or even before) the initial render. How would I set this up with redux-saga?

Does it even make sense to use saga here? i feels like something I should do in a saga. I haven't thought it through and would like to have your insight on that.

**Comment by Andarist** [comment]
it really depends on what you are trying to achieve, but conventionally I think its easiest to set up some `loading` state flag and just render conditionally null if it is `loading`

and ofc you can lift `loading` state from your saga by dispatching an action from your saga (`yield put(action)`) and process the action in reducers

**Comment by ms88privat** [comment]
I used to fire an action "APP_STARTED" in the componentDidMount of my RootComponent.

**Comment by granmoe** [comment]
Is it really coupled to the render? I have a few apps where I grab some bootstrapped data from the server and process it (among others things) immediately after I create my store in my main js entry point (not even in a component yet). Just make it so you conditionally render something "pre-load" / before the tasks you mentioned (like show a spinner or something).

**Comment by samsch** [comment]
From a technical standpoint, you can run any saga you want from `sagaMiddleware.run()`. So when you call that from your main.js (or whatever bootstrap file), the saga can do whatever you want.

**Comment by Andarist** [comment]
Going to close this, if you have any further questions - please just ask :)
