### ISSUE TITLE
Preventing container rendering until data is resolved

### ISSUE THREAD

**Issue by mmahalwy** [redux-saga/redux-saga#663]
Please excuse me if this has been previously answered. How can I prevent react-router from rendering a container until sagas for that container (data fetching) is resolved? And what does that look like? Any examples? 

Thanks

**Comment by tobyl** [comment]
When your data is fetched, you can pass it to a container/component as props:

```
if (!this.props.data) {
    return <LoadingSpinner />;
} else {
    return <Component />;
}
```

Not really a redux-saga thing, more of a component thing.

**Comment by Andarist** [comment]
With server side rendering you need to dispatch actions (lets call them - fetch commands) so they can be catched in your sagas. Make the saga tree block on every `call` etc and dispatch special action `END` which is exposed by the library. It will cause your sagas which are being blocked `take`s to resolve and your root task will be able to resolve in that way
```javascript
const task = sagaMiddleware.run(rootSaga)
task.then(() => ...)
```
and then in your callback upon task completion send the server side rendered stuff back to your client.

There are several issues spread up on issues with examples, you can browser around and dig them up. Its certainly something that could be explained better in the docs though.

Going to close this, if you have any further questions - please just ask :)
