### ISSUE TITLE
generator is already running

### ISSUE THREAD

**Issue by kopax** [redux-saga/redux-saga#703]
Dear @yelouafi.

I have an error thrown in my console since weeks, and I cannot describe if it's an error or not.

It does what I expect it to do, it's just generating an error.

I have asked on [stackoverflow](http://stackoverflow.com/questions/40861641/redux-sagas-cancelwatcher-throw-error-uncaught-at-getlogin-generator-is-al?noredirect=1#comment68946864_40861641)  and [here](http://stackoverflow.com/questions/41143919/redux-saga-cancel-effect-trigger-error-is-already-running-while-it-does-cancel) and created on issue on [mxstbr/react-boilerplate](https://github.com/mxstbr/react-boilerplate/issues/1281) but I haven't got any answers.

According to a certain Yassine Elouafi (maybe you)

> what's the execution env (versin of chrome?, node?). I asked because it could be likely a V8 bug. see [github.com/Microsoft/TypeScript/issues/9372](https://github.com/Microsoft/TypeScript/issues/9372) or [github.com/Microsoft/TypeScript/issues/9372](https://github.com/Microsoft/TypeScript/issues/9372)

The problem come from the `cancel` effect. If I cancel it I have this error `pageLogin generator is already running`.

- Do you have any information regarding this issue ? 
- Is there a way to mask the error in the console ?
- Is there a workaround ?

**Comment by Andarist** [comment]
Could you reproduce it on something like webpackbin? Would be really helpful to play around with full working example.

Or you could public your repo and prepare it for testing.

**Comment by Andarist** [comment]
It seems that it is caught here for you - https://github.com/yelouafi/redux-saga/blob/fb4c69e7a9fe7e588a878b898ce6f342a1e9428a/src/internal/proc.js#L343-L347 . Thats probably why it has not impact on your code, beside the nasty warning.

It seems though that it might be related to some bug on our side, replicated example would help a lot.

**Comment by yelouafi** [comment]
@kopax As a temporary workaround You can filter out that error by passing a custom logger to the middleware

```js
function myLogger(level, message, error = '') {
 // ignore error
  if(error === 'Generator is already running' ) return

  /*eslint-disable no-console*/
  if(typeof window === 'undefined') {
    console.log(`redux-saga ${level}: ${message}\n${(error && error.stack) || error}`)
  } else {
    console[level](message, error)
  }
}

// in your middleware setup code
const sagaMiddleware = createSagaMiddleware({ logger: myLogger })
```


@Andarist 

I was able to get the same error executing the following code in Chrome's console 

```js
var g

function* gen() { 
  yield 1 
  console.log(g) // print the status of the generator
  doSomeCrazyStuff()
  yield 2
}

function doSomeCrazyStuff() {
  g.next()
}

g = gen()
g.next()
g.next()
```
you'll see the status of the generator is `running`: the code tries to call `next` while there is already a `next` in progress. 
 
It could be some subtle race conditions (it could be also a V8  bug [like this one](https://bugs.chromium.org/p/v8/issues/detail?id=3096)

**Comment by kopax** [comment]
@Andarist if you still need a gist example after the example of @yelouafi I will create one.

@yelouafi thanks for the temporary workaround, se we just disable the error and keep this open until we have more information ?

**Comment by Andarist** [comment]
@kopax 
Ye, it would still be cool to see a gist of saga example, as @yelouafi's code probably shows what I would expect to happen. Within saga environment that shouldnt happen.

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.

**Comment by martinkadlec0** [comment]
@Andarist I am still running into this even with redux-saga v1.

I managed to reduce the code from our application to this: https://codesandbox.io/embed/generator-is-already-running-k3ywc

It is somehow the combination of navigation + delay + takeLatest (or cancel).

**Comment by gary1410** [comment]
> @Andarist I am still running into this even with redux-saga v1.
> 
> I managed to reduce the code from our application to this: https://codesandbox.io/embed/generator-is-already-running-k3ywc
> 
> Try clicking on "go to bar" and you should get the error in console.
> 
> It is somehow the combination of navigation + delay + takeLatest (or cancel actually I assume).
> 
> **Edit**: Andarist helped me to figure this one over twitter. The problem is that history.push causes synchronous imperative dispatch which the saga scheduler can't properly handle. Solution is to use the call effect instead of calling history.push directly.

Can you give an example in code of how you handled this using the call effect?  I just came across this issue.  Thanks,  Gary

**Comment by levenleven** [comment]
@martinkadlec0 @Andarist Thank you, I had similar issue and it was fixed by using `call` effect. Maybe we could put this into https://redux-saga.js.org/docs/Troubleshooting.html? Though I'm not sure how to word the issue correctly

**Comment by Andarist** [comment]
@martinkadlec0's issue was about synchronous cancellation attempt (from what I remember) on an already executing generator.

It looked smth like this:
```js
yield takeLatest('FOO', function* inner() {
  if (someCondition) store.dispatch('FOO')
})
```

When you enter that `inner` generator you can't imperatively call `dispatch`, when you are still executing that generator, that would lead to that generator being called from outside with `next`/`return`/`throw` (and that happens in here because `FOO` leads to cancellation of currently running generator put into takeLatest).

I admit that this is hard to put into words, I'd appreciate if anyone could explain this in simple words and would gladly accept a documentation PR describing this.
