### ISSUE TITLE
Similar lib for a non-redux use?

### ISSUE THREAD

**Issue by DarrylD** [redux-saga/redux-saga#705]
Really got use to this saga patten. Want to something similar for node, any similar libs?

**Comment by Andarist** [comment]
You can connect other data sources via - http://yelouafi.github.io/redux-saga/docs/api/index.html#runsagaiterator-options . It would be technically possible to use in node, but without requirements, I cannot recommend any specific.

Also look at this project - https://github.com/koajs/koa

**Comment by akinnee** [comment]
Here's a newer non-redux specific library which is quite similar to redux-saga. It uses the same `call()` wrapper to yield instructions instead of yielding promises.
https://github.com/neurosnap/cofx
