### ISSUE TITLE
feature request: takeBetween effect

### ISSUE THREAD

**Issue by nktssh** [redux-saga/redux-saga#706]
I've encountered with situation when I need saga to be executed between two action (e.g. need to get entity status from server only on particular view)

My initial attempt was like this:
```
import {
  take,
  fork,
} from 'redux-saga/effects';

export default function* takeBetween(startAction, stopAction, saga, ...args) {
  const forkedTask = yield fork(function* takeBetweenFork() {
    while (true) {
      yield take(startAction);
      const task = yield fork(saga, ...args.concat(startAction));
      yield take(stopAction);
      task.cancel();
    }
  });

  return forkedTask;
}
```

Will it be useful to add such kind of functionality into core API, alongside with `takeLatest` and `takeEvery` ?

If so, I can make a pull request with tests for this functionality.
But probably I'll need help with integration with core.

@yelouafi what do you think?

**Comment by Andarist** [comment]
Imho `takeBetween` is kinda misleading name for this one, smth like `runBetween` or `forkBetween` would be much more appropriate.

Also instead of `task.cancel()` the more idiomatic way to do this is `yield cancel(task)`

I aint sure if this one should be added to the core, but overally is quite cool. I would love to see some `redux-saga-utils` package with more of such helpers. Without tree-shaking it might not be worth to add it for everybody.

**Comment by nktssh** [comment]
@Andarist thanks for the feedback!
Agree, naming is open question 🤔. I was inspired by `takeLatest/takeEvery`.
If `redux-saga-utils` package will be planned/created - just ping me, I'll make a pull request with pleasure!

**Comment by Andarist** [comment]
just saying I have just run into the issue when I in fact needed `takeBetween` ;) but a little bit different than you have proposed (which I would call `runBetween`), would be smth like
```javascript
export default function* takeBetween(
	pattern,
	startPattern,
	stopPattern,
	saga,
	...args
) {
  const forkedTask = yield fork(function* takeBetweenWorker() {
    while (true) {
      yield take(startPattern);
      const task = yield takeEvery(pattern, ...args);
      yield take(stopAction);
      yield cancel(task);
    }
  });

  return forkedTask;
}
```

**Comment by nktssh** [comment]
@Andarist maybe, `takeBetweenEvery` will clarify this code better, what do you think? 
I know, this function is cover your particular case, but still - maybe, provide a way to customize behaviour (`takeLatest/takeEvery`) with some defaults?

**Comment by Andarist** [comment]
But such defaults would need to be customizable afterwards, hard to think of the easy API to do it. And also there are just too many things people would like to customize with each helper that it is hard to make those generic.

However I'm still thinking how to organize the whole package, so the `utils` could grow with more specialized helpers (now we have only 3).

**Comment by Andarist** [comment]
Ive marked this as `utils`, so it can be easily found in the future. Gonna close for now as such utils package needs to be rethought and organised. Not much time for that now. Its certainly something I would like to have done in some form after we release v1.

Ill keep tabs on various ideas which could have been added to such a package. If you have some free time (or anybody else for that matter) it would be super helpful if you browse our issues and gather a list of things that people have proposed or maybe even gave examples of in the comments. Separate issue could be crated for this.

Going to close this for now. If you have any further insight - Im all ears :)
