### ISSUE TITLE
Why is there different behaviors with END.

### ISSUE THREAD

**Issue by awaw00** [redux-saga/redux-saga#707]
I've written a simple saga demo [here](http://www.webpackbin.com/4ykwZgJNG)

In `main.js`, I run the root saga, when root saga is resolved, will log text 'DONE'.

After this, I dispatch an action 'START', then close saga use store.close():

```javascript
// main.js
import 'babel-polyfill';
import createStore from './createStore';
import sagas from './sagas';

const store = createStore();
const d = type => store.dispatch({type});
store.runSaga(sagas).done.then(() => bin.log('DONE'));

d('START');

store.close();
```

```javascript
// sagas.js
import { take, put, call, fork, takem } from 'redux-saga/effects';
import { delay } from 'redux-saga';

function *subTask () {
  let times = 0;
  while (times++ < 6) {
    bin.log(yield take('NEXT'));
    yield call(delay, 1000);
    bin.log('next');
  }
}
export default function *() {
  while (true) {
    yield take('START');
    bin.log('start');
    yield call(delay, 1000);
    bin.log('delayed');
    yield fork(subTask);
    bin.log('end');
  }
}
```

Check the Log tab and we can see output like:

**"start"
"delayed"
"end"**

It seems like saga hasn't been resolved yet.

I think this is the correct result because in #255 , @yelouafi said:

> The only way to escape from END will be inside forked tasks and within race effects.

But, if we remove two lines in sagas.js:

```diff
yield take('START');
bin.log('start');
--- yield call(delay, 1000);
--- bin.log('delayed');
yield fork(subTask);
bin.log('end');
```

The log output is:

**"start"
"end"
"DONE"**

-- Saga has been resolved, why?

**Comment by awaw00** [comment]
@Andarist thanks for your reply.

**Comment by Andarist** [comment]
@awaw00 

I've wanted to let you know that I'm working on the `stdChannel` so it can become a singleton, and im pretty much done, but have 1 case to work out, before its ready. Hopefully it wont take me forever ;) It also will help on some perf issues when one have really many tasks in his app.

**Comment by yelouafi** [comment]
@Andarist Perhaps we should decouple `stdChannel` totally from `channel` as they seem to be completely different things: 

- one is unbuffered, multicast (dispatch to all subscribers), event pubsub (ie with matchers)
- while the other can be buffered, unicast (dispatch to one taker using FIFO rule), and matchers just doesn't make sense (as we encountered in a previous issue IIRC).

It seems like continuing the 'OOP' way (treating stdChannel as an extension to channel) is going to impose superfluous complications to the channel interface.

**Comment by Andarist** [comment]
You might be right, although Ive started implementing this and added smth like `putAll` to the interface, which could be possibly made later as an effect too. It might be useful for people to multicast to the channel, so each pending subscriber gets the notification. 

They do not seem too coupled and that this unification between them impose complications (yet at least). Ofc they for sure need to share the common interface. Implementation could be split, but aint sure how much of a gain would that give us, and for sure some duplication (which is not always the worst thing in the world). 

Anyway - established semantics/API would be great. If we split the implementation then multicast primitive could be exported for external usage too and `stdChannel` just being made on top of it + `put` wouldnt need its twin method `putAll`, but just the behaviour would differ - depending on the channel type - multicast vs unicast

**Comment by Andarist** [comment]
Im working on releasing v1. Part of that is [rewritten internal stdChannel](https://github.com/redux-saga/redux-saga/pull/824), so it becomes a multicast. It solves this bug and some others. I've written [failing test](https://github.com/redux-saga/redux-saga/pull/824/commits/37599b2ed668d851f79baf44c7196e6650510a4d) for the bug described in this issue and merged it into the mentioned stdChannel PR to confirm that. Therefore I'm closing this issue now, you can watch progress on v1 [here](https://github.com/redux-saga/redux-saga/milestone/1). I don't have much time to work on this, so however slow the progress is it is steady at the moment, so I hope you won't have to wait too long for the release.
