### ISSUE TITLE
using actionChannel to accumulate many API calls in X time

### ISSUE THREAD

**Issue by anthonychung14** [redux-saga/redux-saga#718]
Overview:
I have an action creator dispatching two actions like so

dispatch(action1(payload1)) => sagaForAction1 (POST)
dispatch(action2(payload2)) => sagaForAction2 (PUT)

sagaForAction2 does not catch the dispatched action2

I have another action creator that properly utilizes sagaForAction2 using action2 alone

As a workaround, I have considered yield put'ing action2 from within sagaForAction1, but I do not understand why sagaForAction2 doesn't detect action2

Reference code:

```
export default function* listensForAction2(action) {
    yield takeEvery(action2, sagaForAction2);
}

export default function* listensForAction1(action) {
    yield [
       takeEvery(action1, sagaForAction1),
       takeEvery(actionFoo, sagaForActionFoo)
   ]
}

export default function* rootSaga() {
    yield [
        fork(listensForAction1),
        fork(listensForAction2),
    ];
}
```

**Comment by anthonychung14** [comment]
#50 seems to address my issue, namely this quote 

> The problem is that the then callback will not execute right away, instead the underlying promise runtime will schedule the goAndFetchNextTakeEffect in a microtask queue. It simply means, the then will wait for the current flow (for example the current event handler, or componentDidMount or whatever fired the action) to terminate and then execute goAndFetchNextTakeEffect. Meantime your code continues and executes dispatch(action2). But at this time, the Saga hasn't yet fetched the next effect (e.g. take or fork) so it is not ready yet to take the action.

However, since this issue was closed, I'm not sure what the resolution was if there was a fix implemented to allow this use-case

**Comment by Andarist** [comment]
Could you specify the redux-saga version you are using? Also the code
snippet of the moment dispatching those actions wold be helpful

**Comment by anthonychung14** [comment]
version ^0.13.0

I didn't think it would add much, but here is the simplified version
`
export const createOrUpdateNode = (payload) => (dispatch, getState) => {

       dispatch(addContent(...args);
       dispatch(updateNode(...args);
};
`

**Comment by Andarist** [comment]
I've created a [webpackbin](http://www.webpackbin.com/V163Uq5Vz) with your snippets in it and it seems that both actions are logged to the bin's console. 

Could you reproduce the issue there? Your original code is way more complex than this simple demo and without the reproduced issue its really difficult to help. You can just edit the code and git Save - it will generate the new URL with your changes included.

**Comment by anthonychung14** [comment]
@Andarist I was mistaken while debugging. My second dispatched action was using an actionChannel to process requests serially (which was not working). 

Desired specs I'm trying to meet:
1. Process queued actions serially through actionChannel (yield call api )
2. When all actions are processed through channel, dispatch final action (dispatch FinalAction)
3. FinalAction merges all previous api calls into one map as a payload

I've attached the code below. 

My use of takeEvery is incorrect since each dispatched action effectively forks a new channel. Derp. Here's my original code + my second attempt at writing a watcher for the actionChannel

```
function* transactionChannel(action) {
    const buffer = buffers.expanding(5);
    const channel = yield actionChannel('UPDATE_COMPONENT_CONTENT', buffer);

    let transactionsPending = true;

    while (transactionsPending) {
        const { payload } = yield take(channel);
        let accumulator = {}

        try {
            yield call(delay, 200);
            const { results } = yield call(putResource, options = {});
            accumulator = results.reduce(reducingFunction, accumulator);

            if (buffer.isEmpty()) {
                yield put({ type: 'COMPLETE_TRANSACTIONS', payload: accumulator });
                transactionsPending = false;
            }
        } catch (e) {
            yield put({ type: 'PUT_FAILED', payload: e, error: true });
        }
    }
}

const actionUpdatesComponentContent = (action => action.type === 'UPDATE')

// Is this causing X number of channels to be forked rather than taking from one?
export default function* componentContentSaga(action) {
    yield takeEvery(actionUpdatesComponentContent, transactionChannel);
}

// My second attempt at filtering actions so only UPDATE enters the channel
export default function* componentContentSaga(action) {
    while (yield take(actionUpdatesComponentContent)) {
        yield fork(transactionChannel(action))
    }
}

// Third idea. More simple 
export default function* componentContentSaga(action){
    while (true) {
        const finalResult  = yield take(actionUpdatesComponentContent)
        // dispatch action to store with accumulated result
    }
}

```

**Comment by Andarist** [comment]
```javascript
export default function* componentContentSaga(action) {
    const buffer = buffers.expanding()
    const actionChan = yield actionChannel('UPDATE_COMPONENT_CONTENT', buffer)
    const resChan = channel(buffers.expanding())
    
    while (true) {
        const { payload } = yield take(actionChan)
        
        try {
            const res = yield call(someAPI, payload)
            yield put(resChan, res)

            if (!buffer.isEmpty()) {
                continue
            }

            const results = yield flush(resChan)
            yield put({ 
                type: 'COMPLETE_TRANSACTIONS',
                payload: results.reduce(reducingFunction, {})
            });
        } catch (err) {
            yield put({ type: 'PUT_FAILED', payload: err, error: true });
            // also there should probably be something done about
            // resChan, actionChan and failed call
            // but hard to tell what without knowing the requirements
        }
    }
}
```
aint sure if this meets your needs, but should be easily tweakable

**Comment by anthonychung14** [comment]
got it working pretty well. channels are schweet
