### ISSUE TITLE
documentation link is broken

### ISSUE THREAD

**Issue by activedecay** [redux-saga/redux-saga#719]
https://yelouafi.github.io/redux-saga/docs/ExternalResources.html

can't reach this. seems to be an empty repo https://github.com/yelouafi/yelouafi.github.io

**Comment by Andarist** [comment]
The reposity was just today transferred to the organization's account so from now on the correct URL path for all docs is https://redux-saga.github.io/redux-saga/docs/

I've corrected just now all links I've had found and gonna ping @yelouafi to publish the docs asap. 

Thanks for noticing and reporting the issue!
