### ISSUE TITLE
Typescript - Saga 0.14 - Mismatch between console warning & definition files

### ISSUE THREAD

**Issue by mcrawshaw** [redux-saga/redux-saga#720]
With version 0.14 there is a new console warning:
```
import takeEvery from 'redux-saga' has been deprecated in favor of import takeEvery from 'redux-saga/effects'.
The latter will not work with yield*, as helper effects are wrapped automatically for you in fork effect.
Therefore yield takeEvery will return task descriptor to your saga and execute next lines of code. 
```
If using Typescript, changing the import to `redux-saga/effects` is not supported by included Typescript definition files.

Should we move the helpers across from index.d.ts to effects.d.ts, or copy it until the deprecation is enforced?

Happy to provide PR or assist.

Mark.

**Comment by Andarist** [comment]
Hey,
all typings (both TS and flow) are community-driven and not written by core maintainers, so there is a high possibility for a mismatch between just released version of the library and the respective typings files.

I will be happy to merge your PR with updated typings, which (like you said) should be copied from from index.d.ts to effects.d.ts , just please remember that original helpers were generators and effects are just plain objects. The accepted types should stay the same but the returned type for the effects should be different - in this case the same thing what `fork` would return. For reference see [this](https://github.com/redux-saga/redux-saga/blob/0833e843a2dadf7fac50cd470784ee2af420aab0/src/internal/io.js#L157)

**Comment by mcrawshaw** [comment]
PR awaiting review, same return type as fork.
