### ISSUE TITLE
Who uses Redux-Saga?

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#722]
If your company is using Redux-Saga in production, please let us know who are you so we can mention you in the README. Linking logos would be appreciated too.

**Comment by anthonychung14** [comment]
We are hoping to use Redux-Saga in production. I've got a PR pending with our company, but still some final bugs to squash!

![Brandcast](http://2016.sfdesignweek.org/wp-content/uploads/2016/05/Brandcast_logo.png)

**Comment by gabrielhpugliese** [comment]
We are using in production: https://www.shore.com/de/ (not this page, only on the real webapp)

![https://cdn2.hubspot.net/hubfs/498216/02_Icons/shore_logo.svg?t=1481792698323](https://cdn2.hubspot.net/hubfs/498216/02_Icons/shore_logo.svg?t=1481792698323)

**Comment by slorber** [comment]
stample.co https://stample.co/assets/homepage/img/stample_atom.png

**Comment by eloytoro** [comment]
We do at [mozio](http://www.mozio.com/)


![logo](https://cloud.githubusercontent.com/assets/3936773/21569352/b1fdc098-ce81-11e6-83ac-8682bc7aa4e7.png)

**Comment by kuy** [comment]
We're heavily using Redux Saga in [entrepedia](https://entrepedia.jp/pages/venture_maps).

![screen shot 0028-12-31 at 2 32 30](https://cloud.githubusercontent.com/assets/151614/21569588/752ebe08-cf01-11e6-99c1-28e6e1667f4b.png)

**Comment by cheersjosh** [comment]
We use Redux Saga throughout our entire application at [Pozible](https://pozible.com) - Australia's largest crowdfunding platform.

![logo](https://cloud.githubusercontent.com/assets/7821982/21599332/12cb2268-d1bf-11e6-8b18-13a378cf5820.png)

**Comment by eliseumds** [comment]
We do at [ProductReview.com.au](https://www.productreview.com.au), Australia's first and most comprehensive consumer opinion site. We'll be releasing the new version of our public-facing app in a few months.

Some of our use cases:

* Analytics
* Authentication
* A very flexible form builder to create specifications for our listings (ex: product model, color, weight, engine size). Great work from @danialk
* User activity tracking
* Files uploader ([see GIF](https://cloud.githubusercontent.com/assets/640840/22722980/cdafea26-ee0e-11e6-93c7-8405efb8c4e5.gif))
* A NodeJS WebSocket server built upon sagas, as well as its client
* Notifications
* Recently viewed items and searched terms
* Form state persistency (local storage + redux-form)
* And so on...

We'll release both user user tracking utils and the files uploader as open source soon :)

Apart from simple autocomplete components and read queries (we use `redux-thunk` for them), all of our side-effects were moved into sagas.

// Cheers, @cheersjosh :)

![logo-2](https://cloud.githubusercontent.com/assets/640840/22723091/aa316074-ee0f-11e6-9ea7-0837a749fdbe.jpg)

**Comment by mltucker** [comment]
Hey.  We use redux-saga in [Wonderling](http://wonderlingapp.com).  It's a questions app for iPhone and Android (for getting closer to friends, family, and S.O.) built with react-native.  So happy with redux-saga -- thank you!

Logos [here](http://wonderlingapp.com/press), e.g. this one: ![Wonderling Log](http://s3-us-west-2.amazonaws.com/wonderling/press/WonderlingLogo.png).

**Comment by Poirette** [comment]
I do at [Global Jet luxembourg](http://www.globaljetconcept.com/) but for internal backend app. It works well, even if it pretty basic (crud api operation async call, with some race / cancellation for UI).

I like the fact that actions are just plain objects, even for async operations.

**Comment by neurosnap** [comment]
[http://notion.ai](url) We built the desktop and web email app using redux-saga.

![section-icon-envelope 3x](https://cloud.githubusercontent.com/assets/1940365/24293036/339d6ccc-1066-11e7-9144-bddf5b483b69.png)

**Comment by baldwmic** [comment]
@Andarist would you like a PR for these in the README ?

**Comment by Andarist** [comment]
oh, ye - sure :) always wanted to get this done eventually

**Comment by baldwmic** [comment]
@Andarist here's a start: https://github.com/baldwmic/redux-saga/tree/whoUsesReduxSaga

Do we have any design ideas? Ideally, it'd be nice to have logos all be the same width/height dimensions

**Comment by RoyLiou** [comment]
[Kdan Mobile](https://www.kdanmobile.com)
![Kdan Logo](https://www.kdanmobile.com/zh-tw/images/menu/kdanlogo_02.svg)
Hi, everyone
We use Redux-saga in our [shop page](https://creativestore.kdanmobile.com)

**Comment by wub** [comment]
We use RS here at StarNow.

![StarNow](https://staticsn.com/images/logo-dark.svg)

**Comment by baldwmic** [comment]
@wub I'm not currently working on #944 right now, but you can add yourself there. Should be pretty simple

**Comment by Rohithzr** [comment]
We use it in production on [CXIHUB](https://www.cxihub.com)
![Logo of Cxihub](https://www.cxihub.com/wp-content/uploads/fav_icons.png)
