### ISSUE TITLE
Redux-Saga logo

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#723]
As `redux-saga` has been migrated to the organization account I feel like it deserves a logo! However my poor graphical skills are not enough to create one, so the help from you guys - the community - would be much appreciated.

**Comment by karland** [comment]
@Andarist I have played around a little and thought I'll make an attempt. How do you like this one? Feel free to make any suggestions....


![redux-saga-logo-v1](https://cloud.githubusercontent.com/assets/4803370/22478097/df8619f4-e7e8-11e6-897f-c7791e6fc5de.png)

**Comment by granmoe** [comment]
This looks awesome!

**Comment by granmoe** [comment]
After looking at it for longer, the green lines kind of looks like a smiley face. Should we care? Maybe do something different with the upper green line? I'm horrible at design, just throwing ideas out there :-)

**Comment by granmoe** [comment]
@karland I dig it! Great work :-)

**Comment by Andarist** [comment]
@karland gr8 work! Would prefer to keep it open for a while, maybe you'll face some competition :P but anyway I like it and if nothing new pops up, I would like to make this official with your permission ofc :)

cc @yelouafi

**Comment by karland** [comment]
@Andarist Glad you like it. Feel free to use it, whenever and however you please. It would be CC0 of course.

**Comment by Nihaux** [comment]
was looking for a logo for a presentation 👍

**Comment by yelouafi** [comment]
I like it! 
thanks @karland

**Comment by eliseumds** [comment]
So... do we have a winner? It would be lovely to use the project's logo on a presentation I'll do on Monday :)

**Comment by Andarist** [comment]
Yeah, i think we have. Use it on ur presentation freely. Ill update Readme and other stuff with it, hopefully 2morrow

**Comment by Andarist** [comment]
@karland 
could you provide a version with transparent background? Also a version with "redux-saga" text to the right of the logo would be appreciated.
