### ISSUE TITLE
Problem testing function as argument of call

### ISSUE THREAD

**Issue by nicmesan** [redux-saga/redux-saga#730]
Hello, I am trying to test a call effect that has a function as argument:

`function * gen () {
     yield call(setSessionTimeOut, function (){return 1})
 }`

but when I try to test it, I get an assertion error:

```
var genFunc = gen();

expect(
	genFunc.next().value
	).to.deep.equal(
	call(setSessionTimeOut, function (){return 1})
	);
```

This is what I am getting in the console, which isn't to much help:

>  AssertionError: expected { Object (@@redux-saga/IO, CALL) } to deeply equal { Object (@@redux-saga/IO, CALL) }

Thanks in advance!

**Comment by Andarist** [comment]
Well, functions cannot be tested against equality in other way than by reference, so deep equality check wont do you any good.

You would have to test it differently, maybe expose this function from the module so it can be imported in your tests? or just check if this is a `call` effect (so just check its type and check if it contains a function (not the function) in its stored arguments?

**Comment by nicmesan** [comment]
You are right, I didn't though about that. Since I need to pass some arguments to this function, I will follow the type-check path. 

Thanks!
