### ISSUE TITLE
take() should work with action creators with a custom `.toString` property

### ISSUE THREAD

**Issue by thezanke** [redux-saga/redux-saga#732]
`take()` should respect action creators that use `.toString()` to output their type—from libraries like *redux-actions* and *redux-act*—so we don't need to maintain a list of constants.

For anyone who hasn't seen it, `redux-actions` sets a `.toString()` method on it's action creators, thus eliminating the need for action type constants. With these libraries, you just use the action creator as a computed property key for an object and it automatically calls `.toString` and finds the type of the action on it's own. This reduces a lot of boilerplate code and makes for a cleaner-looking codebase (there's much less `SNAKE_CASED_CAPITALIZED_CONSTANTS` sprinkled around the code).

`take()` (or really, the `matcher` method in proc.js) should automatically call `.toString()` on these action creators. If this was implemented we could completely drop action type constant files (since we already don't need them for reducers with these action helper libraries).

I know that simply doing this for ALL patterns that are functions would break the predicate matcher. One way we could get around this is to see if the pattern being passed to `take()` has a "toString" property of it's own (not from prototype). This could be tested with `is.func(pattern) && pattern.hasOwnProperty('toString')` (or we could define a new helper to test for it). Action creators from these utility libraries pass this test while standard functions wouldn't.

IMO, nobody using these libraries wants to have to write a wrapper for `take()` and add _Yet Another Import™_ to the top of their files just to have this functionality. I also personally don't want to have to type `.toString()` after every action when I use `take()`.

I could make a PR to update the definition(s) of `matcher()` and/or `matchers()` from _src/internal/proc.js_ to have it support this.

**Comment by Andarist** [comment]
I think this might be a good idea and could be included in the core.

Should be tested before `is.func`, puting it before `is.array` would be rather confusing (or not?).

Updating the docs appropriately in your PR would be also greatly appreciated.

**Comment by nktssh** [comment]
we also have no constants and all action creators has custom `.toString`, and we invented following workaround:
```
yield takeLatest(`${someActionCreator}`, someSaga);
```

but, yeah, it will be nice to see stringable action creators

**Comment by Andarist** [comment]
it would also work with `yield takeLatest(String(someActionCreator), someSaga);` which is quite clearer what it does

**Comment by Andarist** [comment]
thinking out loud - the concept could be leveraged to get rid of [this](https://github.com/redux-saga/redux-saga/blob/23f1e0f6e226d3e05897f2709705c0c65cfd3eb1/src/internal/io.js#L5-L16)

cc @yelouafi

**Comment by Andarist** [comment]
@thezanke @nktssh the feature got released, you can check it out [here](https://github.com/redux-saga/redux-saga/releases/tag/v0.14.3)
