### ISSUE TITLE
put.resolve not blocking

### ISSUE THREAD

**Issue by clouddra** [redux-saga/redux-saga#744]
I have having some problems trying to initiating a blocking `put`. Basically I am trying to ensure a second request is fired only after the first request completes.

The code (pseudocode) looks something like this:

```javascript
function* firstAsync(payload){
  try {
    const response = yield call(API.post, payload);
    yield put(finishFirst(response));
  } catch (error) {}
}


export function* first() {
  while(true) {
    const actionPayload = yield take(START_FIRST);
    yield call(firstAsync, action)
  }
}

function* secondAsync(payload){
  try {
    const response = yield call(API.post, payload);
    yield put(finishSecond(response));
  } catch (error) {}
}

function *firstThenSecond(payload) {
  // startfirst() is the action creator for const START_FIRST
  yield put.resolve(startFirst(payload));
  yield call(secondAsync, payload);
}

export function* someSaga() {
  yield takeLatest(FIRST_THEN_SECOND, firstThenSecond);
}
```

The behavior should be `someSaga -> firstThenSecond -> first -> firstAsync -> secondAsync` but `secondAsync` is finishes before `firstAsync`. 

Would appreciate if anyone can help point me in the right direction.

**Comment by Andarist** [comment]
For this use case I think you kinda overcomplicated things, IF YOU DO NOT need ability to start those requests independently from `FIRST_THEN_SECOND` action (by dispatching 'chunk' actions like `START_FIRST`), you simply could do it like this:
```javascript
function *firstThenSecond(action) {
  const payload = yield call(firstAsync, action)
  yield call(secondAsync, payload)
}

export function* someSaga() {
  yield takeLatest(FIRST_THEN_SECOND, firstThenSecond);
}
```
I think you could misunderstood `put.resolve` it has no way to control your sagas completion. It quite simply uses `dispatch` under the hood. The whole `resolve` part means that if your `dispatch` returns a promise (for example from your custom middleware) it will wait for that promise to resolve and only then resume your saga.

**Comment by clouddra** [comment]
@Anahkiasen thanks for the clarification. `*first()` actually does a lot more things (forking and cancelling other sagas) but I have omitted them to keep the discussion simple. 

So am I right to say that there is no way to synchronously dispatch an action and wait for the completion of the saga chain before transiting to the next state? I thought that such a use case would be pretty common.

**Comment by Andarist** [comment]
It is completely possible, just do this:
```javascript
function *firstThenSecond(payload) {
  yield put(startFirst(payload));
  const payload = yield take(FINISH_FIRST)
  yield call(secondAsync, payload);
}
```
or
```javascript
function* firstAsync(payload){
  try {
    const response = yield call(API.post, payload);
    yield put(finishFirst(response));
    return response
  } catch (error) {}
}

function *firstThenSecond(action) {
  const firstTask = yield fork(firstAsync, action)
  const payload = yield join(firstTask)
  yield call(secondAsync, payload);
}
```

**Comment by clouddra** [comment]
Cool. Totally forgot about matching on `FINISH_FIRST`.

Just to point out that the fork example does not work if we have something like this:
```javascript
function* first() {
  yield takeLatest('START_FIRST', firstAsync)
}
```
`fork(firstAsync, action)` will bypass `takeLatest`.

Thanks for the help.

**Comment by Andarist** [comment]
Yeah, sure `forkedTask` must block until a result is retrieved AND return it, so it can be returned by a saga as `join(forkedTask)` result. 

`takeLatest` is returning a task descriptor immediately. However I wouldnt ever use nesting `takeLatest` within `takeLatest` call itself. It might work, as parent `takeLatest` would cancel inner `takeLatest` on each trigger but probably if you need such construct it can be organized better in the code than using nested `takeLatest`s

**Comment by clouddra** [comment]
Yup using nested `takeLatest` is definitely not a good idea. Just wanted to use it to point out that it might not work for the `fork` case if we want `takeLatest` semantics.

In my case I did organized things manually (complex saga dependencies) in my code.

**Comment by Andarist** [comment]
Aint sure what you mean, as its sometimes hard to discuss without seeing the code ;)

If you want to use `takeLatest` semantics though (not nested ones, just single `takeLatest`) its still applicable easily in the posted example code.
```javascript
function* firstAsync(payload){
  try {
    const response = yield call(API.post, payload);
    // you could have here even more complex async logic
    // just it had to be made ina blocking manner
    // so the mentioned requirements are met
    yield put(finishFirst(response));
    return response
  } catch (error) {}
}

function* secondAsync(payload){
  try {
    const response = yield call(API.post, payload);
    yield put(finishSecond(response));
  } catch (error) {}
}

function *firstThenSecond(action) {
  const firstTask = yield fork(firstAsync, action)
  const payload = yield join(firstTask)
  yield call(secondAsync, payload);
}

export function* someSaga() {
  yield takeLatest(FIRST_THEN_SECOND, firstThenSecond);
}
```

**Comment by clouddra** [comment]
yup single ones work fine.

The actual code looks something like (with variable names changed to keep things simple):
```javascript
function* first() {
  let firstRunning;
  let anotherSaga = yield fork(someOtherSaga);

  while (true) { // eslint-disable-line no-constant-condition
    const actionPayload = yield take(START_FIRST);
    if (firstRunning) {
      yield cancel(firstRunning);
    }
    yield cancel(anotherSaga);
    anotherSaga = yield fork(someOtherSaga, action);
    firstRunning = yield call(firstAsync, actionPayload);
  }
}
```

It is similar to a `takelatest` with additional logic inside. I always want to run `someOtherSaga` and `firstAsync` with the newest `actionPayload`. 

- `someOtherSaga`has it own logic which matches other actions.
- `FIRST` and `FIRST_THEN_SECOND` can be triggered independent of each other.

In this case, `yield take(FINISH_FIRST)` would work fine but I think it can be difficult to make `fork(firstAsync, action)` work (I could be wrong though...).
