### ISSUE TITLE
return promise within saga?

### ISSUE THREAD

**Issue by L-Jovi** [redux-saga/redux-saga#745]
thanks for smart redux-saga lib, it help me a lot :)

and now I'm confused that using promise within saga's generator.

I notice that from common es6 generator I can get promise from call like below simple code,

```
f = () => {
  return new Promise(( resolve ) => { resolve('hello '); })
    .then(( res ) => { return res + 'world!' });
}

gen = function* () {
  yield f();
}

gen().next().value  // get promise here
```

but within saga I could directly get value `hello world!` from `yield f()` result,

maybe I'm not understand clearly, is saga handle the result for me?  and how could I get promise from `yield f()`?

thanks for your time,

regards.

**Comment by Andarist** [comment]
You are right about the part that saga handles the result for you. In its
basics its the interpreter of the yielded values.

So when you yield smth redux-saga looks at what you have passed to it and
handles it appropriately. In case of the yielded promise it chains it with
then, retrieve the result from its callback and injects it back to your
generator. It looks roughly like this:

if (is.promise(yieldedValue))
yieldedValue.then(res => gen.next(res))
}

You must understand that left value and right value of the assignment
involving yield are completely different things.

The created iterator from the generator is under control from the outside
world. It wont be run until .next(). And you can pass values from the
outside by supplying an argument to the next call.

Its completely valid to create a generator which would receive entirely
different thing than it has yielded.

Imagine that

function* gen() {
const three = yield 2
console.log(three) // 'three'
}

const it = gen()
it.next() // {value: 2, done: false}
it.next('three') // {value: undefined, done: true}

**Comment by L-Jovi** [comment]
@Andarist  thanks for your patient reply :)
