### ISSUE TITLE
watch for any action being dispatched

### ISSUE THREAD

**Issue by m1m6** [redux-saga/redux-saga#747]
Hi all, i'm new to Saga :), I have an issue, when i'm trying to watch all action being dispatched, and depending on some action types i called a saga for that,
here's my code:

```
 export function* watchAnyAction(){
  yield* takeEvery('*', function* logger(action){
    const state = yield select()
    switch (action.type) {
      case 'LOGIN_FORM_SUBMIT':
        yield* takeLatest('LOGIN_FORM_SUBMIT', loginForm);
      }
    }
  )
}
```
So when submit the login form, the action is dispatched and the code enters the case 'LOGIN_FORM_SUBMIT', but the '**loginForm**' won't be executed for the first click, but if click once again, it will proceed and the function '**loginForm**' will be executed!!

**Comment by Andarist** [comment]
First of all such usage of `takeLatest` will end up badly for you really quick. It forks a new *endless* watcher (`loginForm`) on every `LOGIN_FORM_SUBMIT` taken by this `takeEvery('*')`

I do not recommend you to use such construct as nesteds `takeEvery`/`takeLatest`/`throttle`. They intended use is only for 1 level deep.

Also with new version of the redux-saga you can import those from the `redux-saga/effects` and use them with regular `yield` (no `yield*`) and they will yield back to your saga a task descriptor (just like `fork` and `spawn`) back to your saga so you can control their life aferwards. Its easy to just `yield cancel(taskDescriptor)` to terminate the task.

You must be aware that using `takeLatest(pattern)` will start to listen on this pattern just from the moment of creating the task, so its natural that you 'miss' first action which has just created this task as it happened before creating it, right?

Im not sure what you are trying to achieve, but the more natural feels to me to handle it this way:
```javascript
 export function* watchAnyAction(){
  yield takeEvery('*', function* logger(action){
    console.log(action)
  })
  yield takeLatest('LOGIN_FORM_SUBMIT', loginForm);
}
```
