### ISSUE TITLE
Testing issue [Symbol.iterator] is not a function while trying to inject an array as select result in a saga

### ISSUE THREAD

**Issue by CyrilQuandalle** [redux-saga/redux-saga#757]
I'm using redux saga 0.13.0 and I'm trying to test a saga which executes as expected :

    export function* mygen(id) {
      let selectedItems = yield select(myselector) //return an array of integer
      for(let item of selectedItems) {
        const {response, error} = yield call(asynFunc, id, item)
        if (response) {
          yield put({type: ACTION_SUCCESS, data: response.data})
        }
        else {
         yield put({type: ACTION_FAILURE, error: error.response.data.error})
        }
      }
    }
Here is my test :

    it("myTest", () => {
        const gen = mygen()
        expect(gen.next().value).to.deep.equal(select(myselector))

        expect(gen.next({selectedItems: [1], item:1, id:1})).to.deep.equal(call(asynFunc, 1, 1))
    })

 I'm having this error :

     TypeError: selectedItems[Symbol.iterator] is not a function
which is weird because selectedItems is an array

and when I console log selected Item I have  { selectedItems: [ 1 ], item: 1, id: 1 } which should be [1]

do you have any idea of how to test it ?
thanks in advance

**Comment by Andarist** [comment]
Frow what I see you are injecting `{selectedItems: [1], item:1, id:1}` as `const selectedItems` and its an object, not an array. 

You might have wanted to write `let { selectedItems } = yield select(myselector)`, but then you wont be able to reference those `id` and `item` in your `yield call(asynFunc, id, item)`.

You must restructure your looping and this injected/selected structure.

**Comment by CyrilQuandalle** [comment]
Thank you for your quick answer, I'll restructure my loop and let you know when I  have an acceptable structure

**Comment by Andarist** [comment]
Im closing the issue for now, if you have any questions regarding the issuse (or any other) just answer here Im gonna receive email notification and reply. Cheers!
