### ISSUE TITLE
Better way to deal with API Middleware and redux?

### ISSUE THREAD

**Issue by SpencerCDixon** [redux-saga/redux-saga#758]
This is just a general question and may belong on SO but figured someone here might be able to help... feel free to close if this is wrong medium.

**Question**: Let's say I inherited a redux app that has API middleware like the one Dan Abramov shows in real world example.  It takes some action with CALL_API and then dispatches the success/failure cases.  Is there a way I can integrate those 'middleware actions' better with redux-saga?  Code is worth a thousand words:

Example API Middleware action creator:
```
 export const deleteEntity = (id) => ({
  [CALL_IAM]: {
    types: [DELETE, DELETE_SUCCESS, DELETE_FAIL],
    endpoint: `/entity/${id}`,
  },
});
```

My sagas end up being something like this:
```
export function* deleteEntitySaga(id) {
  yield put(actions.deleteEntity(id));
  const { success } = yield race({
    success: take(at.DELETE_SUCCESS),
    fail: take(at.DELTE_FAIL),
  });
  return !!success;
}
```
Is using `race` appropriate here?  Is there a better way to approach this integration that I'm missing?  If not, totally fine, just curious.

Cheers

**Comment by Andarist** [comment]
yeah, using `race` is pretty reasonable here, im only wondering whats the point of this integration here? is `success` utilized somewhere else?

**Comment by SpencerCDixon** [comment]
Yeah so essentially I might have other sagas that use this one and they need to wait until the entity is deleted either successfully or fails to delete and respond accordingly.  For example, if deleted successfully then pop an alert saying everything went well or if failed ask user if they want to retry, etc.

Glad that race is being used properly was skeptical since none of the examples I saw used it this way
