### ISSUE TITLE
[RFC] yield restart(task) / task.restart()

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#762]
So I was discussing with @granmoe about the idea of introducing a `restart` effect, which basically would just call a `restart` method on the task descriptor. I feel exposing this on the `task` itself is also needed so it is possible to restart a `sagaMiddleware.run` / `runSaga` result (which is a task) from the outside, which is important in the context of code-splitting and dynamically run sagas on routes for example.

This would require a small rewrite of `proc` function as it accepts iterators now, so in the moment of creating a `task` it is not possible to store on it originating generator and its arguments. However this is just an implementation detail not exposed as the public API I dont see any cons of doing that.

Semantics needs to be established:
- I see `restart` as a combo of `cancel` + `fork`.
- I think the status of the task (running/cancelled/aborted) shouldnt matter here, restarting would be possible on each one of them.
- It also seems reasonable to me that `.restart()` should return new instance of the task, a copied one, otherwise it could lead to some unexpected behaviours (if not how we would handle `task.done` once initial promise in initialized by a getter?)

On top of that `redux-saga` or people in the userland could implement higher-order sagas for auto restarting. However it is not really that hard even now as shown [here](https://github.com/redux-saga/redux-saga/pull/644#issuecomment-266454875). (cc @aikoven )

What should be considered:
- should we track sync errors and expose that information to the user? may be possible by wrapping - `result = iterator.next(arg)` in `proc`'s `next` with `try`/`catch` block. Such meta property could be useful for people trying to restart aborted task to determine if its worth restarting.

Once implemented `takeLatest` could be rewritten using this.

cc
@yelouafi
@slorber (thinking it might be interesting in perspective of your thread/issue about actor systems)

**Comment by slorber** [comment]
Hi,

I don't have much feedback to provide here as I don't really need to restart sagas imperatively, in my usecase I just need root sagas to be kept alive for the whole app lifespan.

One important thing I noticed in my app is that it can be very annoying if we restart sagas without a backoff policy. It can lead to infinite execution loops that may lock the main thread and the whole browser very badly. In my app I'm currently adding a delay between restarts, as a workaroud to let some space to the thread to execute some code.

Here's my current code:

```javascript

import {
  runSaga,
  delay,
} from "redux-saga";

import {
  spawn,
  call,
} from "redux-saga/effects";


import mainContentSaga from "widgets/mainContent/common/sagas/mainContentSaga";
import folderSelectionDefaultTargetUpdaterSaga from "sagas/folderSelectionDefaultTargetUpdaterSaga";
import stampleWillUpdateSaga from "sagas/stampleWillUpdateSaga";
import navBarSaga from "widgets/navBar/navBarSaga";
import toastSaga from "widgets/toast/toastSaga";
import subscriptionBannerSaga from "widgets/subscriptionBanner/subscriptionBannerSaga";
import stampleFullScreenSaga from "widgets/stampleFullScreen/stampleFullScreenSaga";


// See https://github.com/redux-saga/redux-saga/issues/570
const makeRestartable = (saga) => {
  return function* () {
    yield spawn(function* () {
      while (true) {
        try {
          yield call(saga);
          console.error("unexpected root saga termination. The root sagas are supposed to be sagas that live during the whole app lifetime!",saga);
        } catch (e) {
          console.error("Saga error, the saga will be restarted",e);
        }
        yield delay(1000); // Avoid infinite failures blocking app TODO use backoff retry policy...
      }
    })
  };
};


const rootSagas = [
  mainContentSaga,
  toastSaga,
  navBarSaga,
  subscriptionBannerSaga,
  stampleFullScreenSaga,
  folderSelectionDefaultTargetUpdaterSaga,
  stampleWillUpdateSaga,
].map(makeRestartable);


// Adapter to make Redux-saga work on top of legacy atom-react framework
const makeIO = (atomReactContext) => ({
  dispatch: events => atomReactContext.publishEvents(events),
  subscribe: listener => {
    const callback = event => {
      listener({...event, type: event.name})
    };
    atomReactContext.addEventListener(callback);
    return () => atomReactContext.removeEventListener(callback);
  },
  getState: () => atomReactContext.getState(),
});


export const startSagas = (atomReactContext) => {
  const IO = makeIO(atomReactContext);
  rootSagas.forEach(saga =>
    runSaga(saga(),IO)
  );
};
```

**Comment by Andarist** [comment]
That I was something I was going after with:
> should we track sync errors and expose that information to the user?

Then it would allow user to decide if he wants to `restart` and when.

**Comment by granmoe** [comment]
I think this should be a higher order saga with a signature like 

```
yield autorestart(saga, { restartHandler, abortHandler })
```

Where `restartHandler` will be called in the `catch` of the HO saga and receive `(error, saga)` as arguments, and `abortHandler` will be called when the saga is aborted (due to throwing synchronously) and also receive `(error, saga)` as arguments. This would allow users to easily hook into error monitoring services / analytics at a top level (a common need).

**Comment by martin-svk** [comment]
any development on this?

**Comment by Andarist** [comment]
Not rly, it was an idea I had and wanted some feedback from the community, so I've started this discussion here, but hadnt time to get to it.

**Comment by Andarist** [comment]
After a thought I've decided this idea is not worth implementing in the code.

I think @ajwhite presents some really cool API for similar problems [here](https://github.com/redux-saga/redux-saga/pull/644#issuecomment-334968776).

This `retry` could still get implemented, but I'd rather like to find a good API for custom effects and have it implemented in user land (as some addon or something) on top the custom effects. However there is no development at the moment considering this feature, I invite all the community to start a discussion about this, proposing the API and even implementing this feature.
