### ISSUE TITLE
[RFC] cancel propagation

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#763]
I thought a lot about error handling in the sagas in general. Gonna write up some post (hopefully soon) about the matter. But came to some conclusions I would like to share with you.

It's good to distinguish your independent tasks by using `spawn` and `fork` appropriately. I would argue that `spawn` should be used mostly when starting the independent task, so error from a sibling or sibling's child tree wont cancel your `spawn`ed independent task by accident.

In other cases I feel `fork` should be favoured as cancel propagation is a superb feature and in most cases this is what one is looking for.

So I would recommend using them both like that as a rule of thumb, especially for beginners. This means `spawn` is more likely to pop up in your rootSaga than in its childs.

In recent times however code-splitting is getting more and more traction (as it should), so people are naturally starting to split their sagas too, so they all dont start to run at the startup, but also on some routes etc. This means that they are run dynamically and possibly canceled at later point of time when they are no longer needed for the app. 

In such scenario of code-splitting I feel like it is crucial to re-think cancel propagation strategies. At first glance it seems reasonable that top-level task started by `sagaMiddleware.run` / `runSaga` should be treated in a different way to ease cancelation of the whole group of sagas started within the same top-level task.

Otherwise it's extremely cumbersome to isolate independent tasks by using `spawn` and at the same time cancel whole task tree (along with `spawn`ed ones!) while code-splitting, as it would require user to expose to himself references to each `spawn` task.

WDYT? Im curious what other ideas could be used for this problem.

cc @yelouafi @slorber @granmoe @chaintng @jshumakerpruitt @neurosnap

**Comment by slorber** [comment]
Hi,

Currently in my app I don't do code-splitting so I can't provide real feedback on that.

One interesting approach is [react-redux-saga](https://github.com/threepointone/react-redux-saga) (cc @threepointone) which will probably help people who want a saga to live only for a given route (like react-router), so it should work fine with code splitting as long as it's already setup for JSX components.

However I'm not really advocating JSX-based routing, and this approach won't work with [redux-tower](https://github.com/kuy/redux-tower) of @kuy 



It may be opiniated, but I think root sagas are special. In my app, they generally tend to live from begin to end, or at least from the whole route lifespan. Maybe it could be useful to have a saga HOC that permit to cancel both forked and spawned tasks on failure, and be the default for any task started with runSaga?

**Comment by Andarist** [comment]
I really like your idea of higher order saga with different behaviour that today that could be used by default as root sagas or even somewhere down the task tree if somebody wishes to. It also would allow preserving the current behaviour if somebody wants it.

Not sure about API though, but I guess something neat could be figured out.

**Comment by neurosnap** [comment]
It sounds like the primary issue is that we are suggesting people use `spawn` for all sagas that are run by `runSaga` that way when one saga fails the entire app doesn't fail, but at the same time we need a way for people to dynamically cancel an entire tree of sagas even when they use `spawn`.

All of this is in an effort to be able to split saga trees up based on application logic or code splitting.

In this scenario it sounds like we need to come up with an API that will allow us to create a `rootSaga` beyond simply the `runSaga` implementation.

In my large redux application we simply pool all of our disparate sagas together into the `runSaga`.  Is there a way currently to pool together multiple root sagas?

**Comment by Andarist** [comment]
> In my large redux application we simply pool all of our disparate sagas together into the runSaga. Is there a way currently to pool together multiple root sagas?

Could you post a shortened snippet of your code? I aint sure what exactly do you mean.

**Comment by granmoe** [comment]
Can't we just make every invocation of runSaga kill the existing root saga before it starts the new one? Then each split module can run rootSaga again. Or do the already running sagas need to keep their current state? I'm lacking a huge amount of context here, so apologies if this is way too simplistic. In our production app, we just import all of our sagas in the index duck and spread them into one array that we start in the root saga. You could conditionally build the sagas array by page.

```
import { sagas as paymentSagas } from 'ducks/payment'
import { sagas as fulfillmentSagas } from 'ducks/fulfillment'

export function* rootSaga () {
  // check the route or whatever and then combine sagas accordingly
  let sagas
  if (paymentPage) {
    sagas = [...paymentSagas, ...someOtherSagas]
  }
  yield sagas.map(spawn) // or however you prefer to start your sagas
}
```

Just my initial reactions to what's been said here so far.

**Comment by Andarist** [comment]
I dont think that would play well for us. Its rather easy for me to imagine a case where the saga needs to keep its state. Think for example about websocket connection. This one is a saga id like to keep alive no matter what - global for my app. But there are also route-specific trees

**Comment by granmoe** [comment]
That makes sense. So what's needed is something more like `loadMoreSagas` and `killSomeSagas`

**Comment by yelouafi** [comment]
Like @slorber I dont have experience with code-splitting so mostly astronaute thoughts :)

One way to view spawn vs fork is like manual/automatic memory management (or any other 'system' resource). for each manual start, there should be also a corresponding cancel, and that means also the burden of manually propagating cancellation down.

regarding splitting, If  a task attached to a route/container (using `sagaMiddleware.run`), then the task should be cancelled also manually.

for example in React, starting in `componentWillmount` and cancelling in `componentWillUnmount` would ensure cancellation is propagated automatically through React lifecycle hooks (assuming splitting is based on routes/containers). for the rest (sagas started withing this route, IMO only `fork` should be used here unless exceptional situation).

One thing that perhaps surprise about fork is the error propagation behavior, but this could be simply handled by wrapping the forked task in a HO task which `call`s the original task in a try/catch block (could even use an effect helper for that)

**Comment by Andarist** [comment]
Hm, it kinda boils down to proper error handling all over the place, the problem is that the language is not enforcing it in anyway and people tend to get a little bit paranoid. And as redux-saga (but also react!) is the interpreter, our code is ran by a 3rd party machinery which all is done often in the same call stack etc, so any uncaught error just destroy our app entirely.

Would be probably cool if we could create some guidelines about using fork, spawn in context of code-splitting, but also without it. The community (and me too) get often really confused about this.

Im also wondering if there is legitimate use case for a `spawn` inside a route based saga, and probably there is for non-watchers, when somebody would like to persist the task even if the route changes, but then it cannot be a watcher as those probably are unwanted and there is no easy to kill it outside of the saga, which I think is kinda dangerous, but maybe unavoidable.

However i feel like we should provide a way to do this. After all `spawn`ed tasks are root tasks, just like those originated from `sagaMiddleware.run`, but the references for those are hidden.

**Comment by yelouafi** [comment]
>Hm, it kinda boils down to proper error handling all over the place, the problem is that the language is not enforcing it in anyway and people tend to get a little bit paranoid. And as redux-saga (but also react!) is the interpreter, our code is ran by a 3rd party machinery which all is done often in the same call stack etc, so any uncaught error just destroy our app entirely.

I agree this is confusing. Perhaps, as a convenience, we should give the global `onError` handler a chance to intercept the error before deciding to kill the entire tree.

**Comment by Andarist** [comment]
But even with that presence of `fork`/`spawn` will still confuse ppl 📦 

Thinking about cancelling `spawn` tasks - I think it is possible in `finally` blocks within `if (yield cancelled())` right? Although I've always found this effect to be not elegant.
