### ISSUE TITLE
Infinite loop with multiple puts

### ISSUE THREAD

**Issue by bassbump** [redux-saga/redux-saga#766]
Why does this code create an infinite loop? 
```
export function* watchFetchBookRequest() {
  yield takeLatest(FETCH_BOOK_REQUEST, handleFetchBookRequest)
}

export function* handleFetchBookRequest(action) {
  try {
    const response = yield call(axios.get, "http://myapicall.com")
    yield put({type: LOADING_START})
    yield put({type: FETCH_BOOK_SUCCESS, payload: response.data})
    yield put({type: LOADING_STOP})
  } catch (error) {
    yield put({type: FETCH_BOOK_FAILURE})
  }
}
```

If I remove `yield put({type: LOADING_START})` it doesn't loop and works fine.

I use an almost exact replica of real-world example with server side rendering and prefetching. I dispatch FETCH_BOOK_REQUEST on a componentWillMount()

**Comment by bassbump** [comment]
Perhaps some extra info, I'm using an almost identical example of real-world example, so server-side rendering. I dispatch FETCH_BOOK_REQUEST on a componentWillMount().

**Comment by bassbump** [comment]
I think I may have figured out what the problem was. I have a parent component that was displaying a <Loader /> element if the state.isLoader was true, else it would render the component that dispatches FETCH_BOOK_REQUEST on componentWillMount().

So on dispatch of FETCH_BOOK_REQUEST, the loader is set to true, FETCH_BOOK_SUCCESS will be called and the loader is set to false. By doing so it triggers again componentWillMount(), ...

So is the best way to implement a <Loader /> component per container? Or is there a better way to have a HOC with a Loader that can listen to a LoaderReducer? Or is this ill-advised?

**Comment by Andarist** [comment]
Well, you need to figure out the best way to do it in your application. I aint sure about your requirements, but its possible to have a `loaded` flag which you would pass to your child component and based on that it will dispatch (or not) a `FETCH_BOOK_REQUEST`. Therefore you wont find you in this endless loop situation.

**Comment by bassbump** [comment]
Makes sense, thank you
