### ISSUE TITLE
[RFC] error reporting

### ISSUE THREAD

**Issue by Andarist** [redux-saga/redux-saga#767]
Basically error reporting is not standardized through the library and also could possibly be made more descriptive and useful for the user. Because `redux-saga` is an interpreter of your generators and the pull nature of this process, some stack tracing etc must be done manually to be user-friendly.

I would like you to point out the use cases and scenarios where there is a room for improvement.

Pain points:
- [try/catch vs uncaught](https://github.com/redux-saga/redux-saga/issues/389#issuecomment-272674316)

**Comment by markspolakovs** [comment]
Context: in React Native, if there's an exception inside the saga, the error log it spits out is completely useless and makes me wade through lines after lines of redux-saga internals.

![image](https://cloud.githubusercontent.com/assets/2904440/22861264/3b5fb372-f115-11e6-8732-80143554c6b3.png)

**Comment by simlmx** [comment]
Sounds like a first step would be to log the `error.message` here
https://github.com/redux-saga/redux-saga/blob/v0.14.3/src/internal/proc.js#L437
Because of the `||`s, it only logs `error.stack`.

**Comment by richardszalay** [comment]
> if there's an exception inside the saga

Worse, because yielding `put` calling the reducers, errors throws in any _reducers_ also get the message-less RedScreen.

**Comment by Andarist** [comment]
Would adding `error.message` to the log (as suggested bt @simlmx) would help a little?

**Comment by richardszalay** [comment]
Absolutely, though coming from React Native it would be nice if the error was formatted the same. 

In fact, is there any reason the error object itself can't be logged? That would allow the platform to handle its display in the console.

**Comment by karl-freeman** [comment]
The `error.stack` property is implemented inconsistently across browsers. Most notably, it includes the error message in Chrome, but not in Firefox. This makes debugging in Firefox a tad harder.

Since the `stack` property is non-standard, I would be in favour of dropping it completely, but as a quick fix, I would also welcome adding the `error.message` to the log, even if this would duplicate it in Chrome.

**Comment by danstepanov** [comment]
@Andarist @richardszalay What is blocking merging that simple change (adding `error.message` to the log)?

**Comment by Andarist** [comment]
I've standardized error logs a little bit in latest release. Gonna close this issue - but if you feel there is any more room to improvement (beside implementing babel plugin for better stack traces like mentioned [here](https://github.com/redux-saga/redux-saga/issues/1199)) please create a new issue so we can discuss this further.
