### ISSUE TITLE
flow-type: type-checking the return values of yielded effects

### ISSUE THREAD

**Issue by matttti** [redux-saga/redux-saga#773]
Correct me if I'm wrong, but as far as I understood the conversation in #358 there are two approaches to detect the correct return-type of the `yield` calls. 
We could either limit ourselves to only one type with `function * mySaga() : Generator<*, *, Y>`, or add the type explicitly: `const foo: Foo = yield select(getFoo)`. However, with both approaches we'll loose flow's type-inference power, making them rather useless.

Now, I thought about another approach: What I tried is to wrap the effects into generators themselves which are called via the `yield*` statement (which simply hand over control to another generator). Here's a simplified example:

```javascript
// redux-saga/effect-generators.js

import * as Effects from './effects'

export function select * (fn, ...args) {
  return yield Effects.select(fn, ...args)
}
```

```javascript
// flow-typed/redux-saga.xx.js

declare module 'redux-saga/effect-generators' {
  // Ensure Generator returns the same type as fn. No call parameters integration yet
  declare var select :  (<R, Fn: ((state: any) => R)>(fn: Fn) => Generator<*, R, *>)
  ...
}
```

```javascript
// mySagaFile.js

import {select} from 'redux-saga/effect-generators'

function * MySaga () : Generator<*, *, *> {
   const user = yield* select(getUser)
}
```

So the only difference for the user would be to add a `*` to each yield statement, and to import the effect functions from a different location. I made some experiments and it seems very promising. 

Of course, it's totally debatable if such an enhancement should be part of `redux-saga` itself. For me, a full grown flow support is quite important.

I'm looking forward to hear your opinions.

**Comment by Andarist** [comment]
Well, as flow and TS typings are completely community driven in the project, I wouldnt like to include this as recommended way of doing things, as the sole purpose of this are the typings.

Unfortunately Im not a good flower so Im not capable of fully helping you here, but I hope the flow community will step up and give some insight on this in the comments. 

From what I understand you try to leverage the type inference here, right? Is it possible to connect each effect's result to the yielded effect itself (which is just an object)? Could you give more examples? `select` seems like one of the easier ones. 

Wondering if the support for this type of thing couldnt be added to the flow itself as generators are comming somewhat more mainstream.

**Comment by matttti** [comment]
Thanks for your reply. Yes, leveraging type inference by extracting the return type is my intention. I think this is what makes type systems so powerful in detecting the hidden bugs. I'll try to give more explanation, also to make some thoughts clear for myself. 

And it would be really really great if ppl from the flow community could help here.

The problem with generator typing in general, is the fact that it is completely up to the application (here: `redux-saga` middleware) what data and type to pass back in `iterator.next(...)` calls.

Or in other words: the decision what type the LHS of a yield statement has, is determined by the caller of the generator, and not solely the RHS. Only the latter can be easily inferred by a type system.

So the only reasonable and safe return type here is `any`. Flow allows, however, to specify a global yield return type `Y` in `Generator<*, *, Y>`. No idea where this could be of any use...

I don't think it is possible to "connect" effect's objects to yield atm. One speculative way I could imagine would be to allow a RHS->LHS mapping dictionary in the place of `Y`. Or to give each effect a second annotation how it should behave when situated in a yield context. But my gut feeling is pessimistic that these are realistic approaches for flow.

Regarding your questions for other examples besides `select`. The pattern should stay the same for all kind of effects. All return types change from `Object` to `Generator<*, R, *>`. Maybe it could be generalized like this:

```javascript
function * IOEffectGenerator(effect, ...args) {
  return yield effect(...args)
}

export select = IOEffectGenerator.bind(IOEffects.select)
export call = IOEffectGenerator.bind(IOEffects.call)
```

However, I'm no expert of the Saga-API, and don't know all possible contexts.

**Comment by Andarist** [comment]
Sorry, didnt yet time to read thoroughly your response, but I've ended somehow in [this thread](https://github.com/facebook/flow/issues/2445#issuecomment-246534411) and Im wondering if that helps you anyhow (it might not ofc).

Also [this thread](https://github.com/facebook/flow/issues/2613) seems to be connected with your issue, but no responses there yet.

**Comment by matttti** [comment]
Thanks @Andarist for finding the two threads. Especially the second one deals with the same problem.

I created [a gist containing implementations](https://gist.github.com/matttti/ae0d65bf534cb84a0dbe4ddd3b0f759c) of the effects I need (`call`, `fork`, `cps`, `cancelled`, `select`). Works quite reliable for me. Hope this will be helpful for someone out there.

However, the `take`effect family still gives me a headache, and I would be glad to get some input from the community here. I thought about using "action prototypes" instead of "actiontype constants" as first paramter, but I'm not very convinced.

**Comment by Andarist** [comment]
I wouldnt like to include some special constructs into the library just for sake's of typings. Is your issue still unresolved? Should I leave this issue opened? Please let me know.

**Comment by matttti** [comment]
I'm using the solution described above. It's not complete, but I'm happy for now.

**Comment by Andarist** [comment]
Ok, going to close issue for now. If you have any further questions, please just ask :)
