### ISSUE TITLE
[Need Help] Error Handling

### ISSUE THREAD

**Issue by rvlewerissa** [redux-saga/redux-saga#777]
Hi, 

I got a little problem here. I don't really understand how redux saga internally works, so this question probably will clear my heads up.

So,
 I have a worker saga as follows:
```
export function* productSaga({key}) {
  let commodity = {
    SeedProducts: ['bibit', 'SEED'],
    FertilizerProducts: ['pupuk', 'FERTILIZER'],
    PesticideProducts: ['pestisida', 'PESTICIDE'],
  };
  commodity = commodity[key];
  try {
    let [res0, res1, res2] = yield [
      call(allProductHighlight, commodity[0]),
      call(allPopularProduct, commodity[0]),
      call(allNewProduct, commodity[0]),
    ];
    let payload = yield call(constructPayload, res0.message, res1.message, res2.message);
    yield put({
      type: `FETCH_${commodity[1]}_SUCCESSFUL`,
      payload,
    });
  } catch (err) {
    console.log('ERROR', err);
    yield put({type: `FETCH_${commodity[1]}_FAILED`, message: err});
  }
}
```

It calls API which looks like this:
```
async allPopularProduct(category) {
    let res = await fetchJSON(`/allproductpopulerinfo?category_id=${category}`);
    if (res.error) {
      throw new Error(`Fetching ${category} from server failed`);
    } else if (res.message) {
      return res;
    } else {
      throw new Error(`No ${category} data from server`);
    }
  }
```

The `fetchJSON()` returns a promise.

What I'm confused about is, how does the worker saga (`productSaga`) able to throw an error? I mean, there are certain occasion where it would catch errors.

My current understanding is that `call` only returns an instruction to redux-saga which will be called internally, so how does it pass the throw to the worker saga?

Sorry guys I'm still new :)

**Comment by Andarist** [comment]
> My current understanding is that call only returns an instruction to redux-saga which will be called internally

Your understanding is correct 👍 

> so how does it pass the throw to the worker saga?

Your generators are returning iterators (objects with `next`, `throw`, `return` methods). `redux-saga` is calling `next` on those to retrieve instructions (as you have described it) and it handles those instructions for you, so if that throws somehow - for example in the `catch` method of the promise you have yielded (or created by running a `call` effect) - it simply inject that error back to your iterator by calling `it.throw(err)`. That can be seen [here](https://github.com/redux-saga/redux-saga/blob/0635ccc629556d88ee8f93e3747488f7cafb0b2c/src/internal/proc.js#L229)

**Comment by rvlewerissa** [comment]
@Andarist OMG, thanks so much dude. Really clear this up!! I'll close this ya.. Thanks again!

**Comment by Andarist** [comment]
No problem. Glad it helped :)
