### ISSUE TITLE
Important: Which effects are asynchronous?

### ISSUE THREAD

**Issue by vjancik** [redux-saga/redux-saga#779]
Since the `redux-saga` middleware can resolve Promises, meaning, it behaves similarly to the `async` / `await` pattern of using generators, it's unclear which yields (with *effects*) are synchronous and which are asynchronous.

To clarify, I'm asking, which *effects* use a Promise / setTimeout / callback function (that could be called asynchronously), inside the middleware.

Obviously all the **blocking** effects are going to be asynchronous, but what about the non-blocking? Is there a guarantee that the `yield` to a non-blocking effect will return to the *yielding* generator in the same event loop cycle (without a context switch)?

If this is ambiguous, could we add it into documentation for each effect?

### Why this is important

Every context switch could cause a potential race condition. I need to be able to know when a context switch can happen, to be able to reason about potential order of instruction execution.

The most vulnerable place where this can happen is the *rootSaga* where you register a lot of listeners (e.g. with `takeEvery`). Does each `yield takeEvery` cause a context switch?

**Comment by slorber** [comment]
You can easily figure this out:


```javascript
const log = setTimeout(() => console.debug("timeout"),0);

function* root() { 
  log(); 
  yield fork(saga1);
  log(); 
  yield spawn(saga2)
  log(); 
  yield put(event);
  log(); 
}
```

Didn't run but IMHO all 3 effects are non blocking and will execute before any log statement.

For put effect doc also mentions a blocking `put.resolve(action)`.
Don't know the subtilities of all the effects but IMHO non blocking ones do not involve any context-switch.

**Comment by Andarist** [comment]
Basically all effects are handled synchronously until async thing happens so there is no much context switching there. That means that only things like promises and `take` (as it set up the one time listener for action) will block and be handled async.

**Comment by Andarist** [comment]
@vjancik 
Do you feel that should be expressed better in the docs? would you be willing to provide a small docs PR with it?

**Comment by Andarist** [comment]
Going to close this, if you have any further questions - please just ask :)

**Comment by ustun** [comment]
I think it would be helpful to list which calls are blocking and which are not. 

I was initially confused why `takeLatest` examples in the docs did not require using `all`, then discovered that it does not wait. 

See the last example here https://redux-saga.js.org/docs/basics/UsingSagaHelpers.html and compare the rest of the document suggesting using `all` or similar means to manage the root saga: https://redux-saga.js.org/docs/advanced/RootSaga.html

Glossary page defines blocking and non-blocking calls, but does not list which ones are what: https://redux-saga.js.org/docs/Glossary.html

The API reference should also ideally list which function is blocking and which is not. It is using the  word `wait`, but it would help if it tagged the blocking ones explicitly: https://redux-saga.js.org/docs/api/

Also, I believe at the library level, the names could be changed in the next major version to make this less confusing. Compare Clojure's core.async which provides blocking and non-blocking calls, differing with a `!` at the end of the name: https://clojuredocs.org/clojure.core.async/%3E!! and https://clojuredocs.org/clojure.core.async/%3E!

Happy to provide a PR for the doc changes or enhancements if this makes sense. Just wanted to outline my experience as a beginner with saga.

Changing the function names probably would require more discussion.

**Comment by Andarist** [comment]
Such list is available here: https://github.com/redux-saga/redux-saga/blob/9949c91d7293e0e216e4c7785360e928625a5757/docs/api/README.md#blocking--non-blocking
