### ISSUE TITLE
put.resolve isn't blocking when invoked via an action

### ISSUE THREAD

**Issue by epikhighs** [redux-saga/redux-saga#780]
I have a saga that has 3 put.resolve(), but it seems put.resolve does not block for my intended use case.

```
// inits different part of the state tree with some initial data
export function* initSaga (action) {
    yield put.resolve(INIT1, 1)); 
    yield put.resolve(INIT2, 2));
    yield put.resolve(INIT3, 3));
}

```

if i invoke this initSaga with a call(), then each put.resolve seems to block.  However, if I try to invoke initSaga via an action that was dispatched, then the put.resolves don't seem to block.

yield call(initSaga) // is blocking
yield takeEvery(INIT, initSaga) // is not blocking
yield takeEverySync(INIT, initSaga) // is not blocking

I sort of understand why takeEvery wouldn't block since it uses fork internally, but I dont' understand why my implementation of takeEverySync does not block.

```
function* takeEverySync(pattern, saga, ...args) {
    const requestChan = yield actionChannel(pattern);
    while (true) {
        const action = yield take(requestChan);
        yield call(saga, ...args.concat(action));
    }
}
```

Is there a way to write takeEvery in a synchronous fashion to make the put.resolve()'s synchronous?

**Comment by slorber** [comment]
Aren't you confusing takeEvery and takeLatest?
Are you sure your initSaga  isn't run multiple times concurrently?
Instead of takeEverySync why not using take directly?

**Comment by epikhighs** [comment]
@slorber hi, could you clarify - how I might be confusing takeEvery and takeLatest?
initSaga is only run once so far in my project, but in the future there could be a use case where it might run multiple times.

my implementation of takeEverySync basically uses take directly. I could change it so that it doesn't use the actionChannel, but I still have the same problem where the put.resolve() is not blocking so that code that relies on the state to be updated from the put.resolve breaks.

```
export function* initSaga (action) {
    while (true) {
        yield take(INIT_SAGA);
        yield put.resolve(INIT1, 1)); 
        yield put.resolve(INIT2, 2));
        yield put.resolve(INIT3, 3));
    }
}
```

**Comment by slorber** [comment]
I never used put.resolve yet so I don't know maybe there's a bug somewhere...

Are you sure you aren't calling multiple times initSaga?

Sorry but I'm not really sure to understand what you are trying to dispatch with `yield put.resolve(INIT1, 1));` there's an extra bracket and put effect does not take 2 arguments. How can you be so sure that this effect is not blocking? Does dispatching it directly through reduxStore.dispatch(action) block? Have you setup some kind of batching redux middleware?

**Comment by epikhighs** [comment]
@slorber you are correct that put.resolve only takes one argument.  I was copy pasting from my project code and forgot that I was using helper functions in my project.  Anyways, this is a more complete code sample of what I'm doing. 

```
export function* initSaga (action) {
    yield put.resolve({type: 'INIT1', payload: 1,});
    yield put.resolve({type: 'INIT2', payload: 2,});
    yield put.resolve({type: 'INIT3', payload: 3,});
}

function* takeEverySync(pattern, saga, ...args) {
    const requestChan = yield actionChannel(pattern);
    while (true) {
        const action = yield take(requestChan);
        yield call(saga, ...args.concat(action));
    }
}

export default function* rootSaga () {
    yield takeEverySync('INIT', initSaga);
}

// in some other saga in response to URL change
yield put.resolve({type: 'INIT'});
// at this point state should have been initialized but it isn't 
const state = (yield select());


// if i use call instead, then the initSaga and all the put.resolves execute synchronously
yield call(initSaga);
// at this point state is initialized successfully
const state = (yield select());

```

**Comment by Andarist** [comment]
what middlewares do you have installed into your store? which one is returning a promise?

**Comment by epikhighs** [comment]
This is how I'm creating the store @Andarist 
```
        rootStore = createStore(rootReducer, rootState, compose(
            applyMiddleware(thunk),
            applyMiddleware(sagaMiddleware),
            ReduxTool.instrument()
        ));
        if (module.hot) {
            module.hot.accept('src/main/rootReducer', () =>
                rootStore.replaceReducer(require('src/main/rootReducer')/*.default if you use Babel 6+ */)
            );
        }

```

**Comment by Andarist** [comment]
So when you dispatch this - `yield put.resolve({type: 'INIT'});` it is geting handled by `redux-thunk` somehow, right? And returning a promise which will resolve when some INIT data get finally to the store?

Would be great if you create a short webpackbin example of the behaviour. Looking at the source code and everything looks fine from what I see, but with the bin we could be sure and the possible bug could be fixed (in redux-saga or in your code, Im happy to help in both situations :))

**Comment by epikhighs** [comment]
@Andarist the INIT action that gets dispatched isn't handled by a thunk.  It just simply goes to the reducer.  I have redux-thunk as a middleware b/c of older code that started off using it, but we've been migrating most new code to sagas exclusively.

I tried removing the redux-thunk middleware and it does not change the behavior.

Should I be using redux-thunk to handle the INIT action?

**Comment by Andarist** [comment]
No, you dont have to handle this with thunk, but the `put.resolve` got into the library for better integrations with things like thunks. Why do you use `put.resolve` then instead of regular `put`? however that shouldnt affect the behaviour from what I understand.

If you dont do anything async in your middleware chain then your reducers should be run first and code point after the `put` should be in the moment of already updated state, so updated values could be retrieved via `select`

What about the webpackbin - would you be willing to prepare one?

**Comment by epikhighs** [comment]
@Andarist I can prepare a webpackbin.  I haven't used it before, however. I'm not sure how to include redux saga and other middleware. Webpackbin only seems to have redux support out of the box.

**Comment by Andarist** [comment]
Its rly easy. You click somewhere on the top in the menu and type in the popup dialog what packages you would like have it to install. After a few secs they are gonna be ready for ur usage

**Comment by epikhighs** [comment]
Hmm. I'm going to http://www.webpackbin.com/ and it has a boilerplates dropdown, but the list of options seems to be fixed.  I can't type in there to add other libs.  I only see redux in there.

**Comment by Andarist** [comment]
Click `Configure` instead of `Boilerplates` and there you will have input to type under `Add NPM package`

**Comment by epikhighs** [comment]
Ohhh, i didn't see that option b/c my browser window width was too small!  I see it now. I'll try to setup something.  Thanks.

**Comment by epikhighs** [comment]
Im getting a "regeneratorRuntime is not defined" error when I try to include a generator function.  I tried including 'babel-polyfill', but webpackbin is throwing errors when trying to download that package.  Do you have a webpackbin that already has this boilerplate setup?

**Comment by epikhighs** [comment]
http://www.webpackbin.com/VJoneYkwz

A bare bones project with only 1 generator function.  Can't seem to get it to work.

**Comment by granmoe** [comment]
@epikhighs Here's one I have saved to use for sharing saga examples.

http://www.webpackbin.com/N1vffI2WM

You have to import babel-polyfill before anything else

**Comment by epikhighs** [comment]
@granmoe thanks for the boilerplate. 

@Andarist http://www.webpackbin.com/Eyni351Dz  refer to the saga.js comments I put in to test the two use cases.

My example dispatches the URL_CHANGE action twice to verify that there is a race condition and that put.resolve does not work as I thought it should.

Thanks for all your help guys.

**Comment by Andarist** [comment]
First of all - `put.resolve` is used with no benefit - `put` would be exactly the same here.

About your other problem - it is connected to internal scheduler of nested dispatches. We must guarantee that no dispatch is run until the one which caused it finishes. So it is intended that after `INIT` action you can `select` DIRECTLY after this action is handled by your reducers (and they are not handling it, cause they are handling only `INIT_1` and `INIT_2`).

If you have any further questions please ask them, I would clarify this as much as I can.

**Comment by epikhighs** [comment]
so is there another way to make the INIT action dispatch either synchronous or have it wait until the state tree is updated and then the rest of the onUrlChange saga executes?

The only way to update state is through PUTs and if PUTs are always async, then I'm not sure how I can sequence the kind of logic I'm trying to do in the onUrlChange saga.

**Comment by Andarist** [comment]
you are facing a scheduling problem because the flow of executions is:
`dispatch(INIT)`
`some code after put(INIT)`
`dispatch(INIT_1)`
`some code after put(INIT_1)`
`dispatch(INIT_2)`
`some code after put(INIT_2)`

and you thought it is smth like
`dispatch(INIT)`
`dispatch(INIT_1)`
`dispatch(INIT_2)`
`some code after put(INIT)`
`some code after put(INIT_1)`
`some code after put(INIT_2)`

as to the solution you should use - I'll think about it some time later and present you some suitable (hopefully) solution for this problem

**Comment by epikhighs** [comment]
Thanks @Andarist. 

In general, my sagas always have PUT as the very last line.  So I never ran into this issue. But when trying to sequence this initialization logic, I'm running into this issue.  I also anticipate the more my saga flows start to interleave and depend on each other, I'll have more situations like this.

**Comment by Andarist** [comment]
So is it requirement for you to buffer `INIT` actions? If an `INIT` action happens when handling of one is happening already, should it be handled too/could it be ignored/cant happen?

1. if it should be handled too
```javascript
export function *onUrlChange () {
  yield put({type: 'INIT'})

  yield call(initSaga);
  /*
  OR
  yield take('INITIATED')
  where yield put('INITIATED') happens at the end of your `initSaga`
  */
  const state = (yield select());
  bin.log(state);
}
```

2. if it could be ignored - basically what I've done in 1. but skip `takeEverySync` and just do smth like `takeAndBlock`

```javascript
function* takeAndBlock(pattern, saga, ...args) {
  const task = yield fork(function* () {
    while (true) {
      const action = yield take(pattern)
      yield call(saga, ...args, action)
    }
  })
  return task
}
```

3. if cant happen - nothing to worry about, just use `takeAndBlock` as precaution

**Comment by epikhighs** [comment]
@Andarist thank you so much! Such a simple solution :) 

And thank you to everyone else at the redux saga team.

Btw, is there an example of how to use put.resolve correctly with thunks?

**Comment by epikhighs** [comment]
An updated example of the solution: http://www.webpackbin.com/VygyT4Mwf

**Comment by Andarist** [comment]
@epikhighs 
There is not I think, but maybe you could provide a docs for it?

Its all about setting some middleware like this (this is not real thunk! ive made it up now):
```javascript
const thunkMiddleware = ({ dispatch }) => (next) => (action) => {
	if (!(action instanceof Promise)) {
		return next(action)
	}
	return action
}

export default thunkMiddleware
```
as you can see if an action is not a promise we pass it down the middleware chain with `next` but if it is a promise we simple return it, so its returned to the `dispatch` caller (redux-saga in our example) and it can be treated by `put.resolve` in a special way - so it waits for the promise resolution

**Comment by Andarist** [comment]
Going to close this, if you have any further questions - please just ask :)
