### ISSUE TITLE
redux saga confused

### ISSUE THREAD

**Issue by alanwei0** [redux-saga/redux-saga#783]
as we know

> The mental model is that a saga is like a separate thread in your application that's solely responsible for side effects.

```javascript
function* handleActionA() {
  yield call(delay, 1000);
  yield put({ type: 'ACTION_B' });
}

function* watch() {
  yield takeLatest('ACTION_A', handleActionA);
}

function reducer(state, action) {
  switch (action.type) {
    case 'ACTION_A':
       console.log('ACTION_A');
       // change state
       return newState;
    case 'ACTION_B': 
       console.log('ACTION_B');
       // change state
       return newState;
  }
}
```

if i trigger 'ACTION_A'  10 times, because saga not intercept the action, so it will print 'ACTION_B' 10 times, and render ui 10 times, that's not what i want.

so, i want to ask, is saga's watcher mode a good structure? i think redux-thunk's interception mode is more simple and reasonable.

**Comment by Andarist** [comment]
You can always split your action types - if you want 'interception' just dispatch something you do not handle in the reducers and later put from the saga something you do.

There is no 'better' here, just 2 different approaches. I bet somebody going from saga to the thunks would probably have other opinion than you right now, but it all boils down to our habits only and what we are accustomed to.

**Comment by alanwei0** [comment]
thanks for your answer. 
we have discussed your approach some days ago, but i may be confused to me about what does "action" mean. if actions are interfaces exposed by reducer, then is an action without a reducer still an action? On the other, if an action has no reducer, then saga is not just handling effects but changes to a controller like thunk.

**Comment by Andarist** [comment]
well, if you want to categorize like that i would say that action is a contract - it is defined how based on them (that they have `type`) system can interact with its parts

**Comment by alanwei0** [comment]
so, you mean that action is not defined by reducer, and reducer just handle action. am i right?

**Comment by slorber** [comment]
@alanwei0 like the DOM fire events that you may choose to handle or not, you can do the same with Redux. It's not a bad practice to decouple action producing from action handling in more complex apps, and any action can be handled by 0 - * reducer

Maybe reading this would help: https://www.confluent.io/blog/turning-the-database-inside-out-with-apache-samza/

**Comment by alanwei0** [comment]
@slorber i think action has some different with events. if an action be handled by more than one reducer, then the program procedure may be confused，because i don't know how many reducer will handle this action. so in my team, we have a rule that "an action can only be handled by an reducer, if the action is complex, we trigger actions flow in saga or thunk". 

In addition, we split store into parts(ex: domain data, ui data).  reducers that handle domain data are just like model in MVC in my mind and the actions are more like the methods of model.

**Comment by slorber** [comment]
@alanwei0 it depends on your conventions, but the saga pattern implemented originally in this library comes from event-sourced backend systems where we consider that every state change is triggered by an event and the saga can handle those events.

Also note that Redux is also inspired by such systems in the first place.

IMHO it has been a wrong theorical decision for the Flux team to create the name "action", but it certainly helpex Flux to gain adoption because the event-sourced theory is less idiomatic for newcomers

So I'd say you can use the lib the way you want in the end, but have to know that it takes origin from a world where the term "action" does not exist, in favor of "commands" and "events"

**Comment by alanwei0** [comment]
@slorber thank you so much

**Comment by Andarist** [comment]
Also if you have a convention of 1 action - 1 reducer I think it may lead to so called 'setter actions' which are rather an anti-pattern. What @slorber said about them (actions) being events is a good naming I think. They should be named kinda like events - describing what happened and potentionally carrying some payload with them and every part of the system can react (no pun intended :P) to it how it fits. Personally I dont see "1 action many reducers" as anti-pattern and do that quite often.

**Comment by alanwei0** [comment]
@Andarist i'm more confused now.............

**Comment by Andarist** [comment]
You need to be more specific, what have confused you?

**Comment by alanwei0** [comment]
i map the redux architecture to traditional MVC arch to help me understand the actions/reducers/saga/components in react/redux. in my deep mind, i regard saga/thunk as controller, so when i trigger an action, i can be find all process flow in saga/thunk. i think it makes the program more understandable and readable. if an action has many reducers, i must to find all reducers in different files. 
that's all.

**Comment by alanwei0** [comment]
@slorber your answer in stackoverflow is so helpful for me

**Comment by Andarist** [comment]
Well, if that works for you its totally ok. However as @slorber have mentioned `redux` didnt originated exactly from MVC and it rather tries to present different approach in regards to the architecture. Such mapping as yours can probably be made in most of the architectures on some level, but I would encourage you to try to look on things in a broader spectrum.

At least for me it was liberating, trying to use apply MVC mental model on the redux might end up with fighting against it instead of leveraging its potential.

**Comment by alanwei0** [comment]
ok，i will keep learning

**Comment by alanwei0** [comment]
still has two question
1. why you say that `1 action - 1 reducer` is an anti-pattern
2. if `1 action - >1 reducer`, how to make the action flow clearly and readable?

**Comment by Andarist** [comment]
Im not saying that there shouldnt be such actions that have just 1 reducer corresponding to it, but making a rule of thumb of this is an anti-pattern in my opinion. I find it really convenient for more than 1 reducer to respond on some action.

About the flow - most people keep their constants in separate file and use those as keys to the reducers switch (or some custom reducer creator like createReducer), so if you need to check what reducers respond to what action type it really comes down to global search on your project and seeing what files contains reference to the one you are looking for

**Comment by alanwei0** [comment]
i understand

**Comment by Andarist** [comment]
If you have any new questions, please ask them here or open a new issue. Gonna close this one for now.
