### ISSUE TITLE
Dynamic Import via Saga

### ISSUE THREAD

**Issue by bradennapier** [redux-saga/redux-saga#788]
So I wanted to do some code splitting in my [redux-saga-processes](https://github.com/Dash-OS/redux-saga-process).  I just wanted to make sure my thinking is sound here (it does appear to work well).  Not sure if there is another way that I could call import directly without the extra promise?

import() returns a promise and webpack 2 will code split this way within the server-side rendered app I am building.  I cant run ```yield call(import, './path')``` as that seems to fail likely due to the parser just being confused.  So my solution was just to wrap it in another promise, anything I am not thinking about with doing this?

```javascript
/*
  Wraps import in a promise that can be resolved by sagas since
  call(import, './path') would cause an error.
*/
function* sagaImport(path) {
  const importPromise = new Promise(resolve =>
    import(`./${path}`).then(module => resolve(module))
  )
  const awaitPromise = () => Promise.resolve(importPromise)
  return ( yield call(awaitPromise) )
}
```

This way, my process looks like this to import dynamically and load the modules code only once needed:

```javascript
import Process from 'redux-saga-process'

export default class FirebaseGeneralProcess extends Process {
  
  static config = { ssr: false };

  firebase = undefined
 
  // Await AUTH_SUCCESS and fork this.authenticated
  static actionRoutes = {
    authSuccess: 'authenticated'
  };
  
  // Create a categorized task to import our firebase module asynchronously
  * authenticated(action) {
    console.log('User Authenticated!')
    yield* this.task.create('importer', 'firebase', this.importer, 'firebase/app')
  }
  
  * importer(path) {
    this.firebase = yield call(sagaImport, 'importFirebase.js')
  }
  
}

```

**Comment by Andarist** [comment]
> I cant run yield call(import, './path') as that seems to fail likely due to the parser just being confused.

Im not sure if thats the case, but proposed `import` is not a function (you can read more about it [here](http://www.2ality.com/2017/01/import-operator.html)), although it looks like one. So maybe it cant be passed by a reference to the saga, but aint sure 100% about this, just a thought.

And if thats the case, your wrapping method is fine (rule of thumb - if it works for you, it is fine :P). Is it code-splitting for you like you expect it to?

**Comment by Andarist** [comment]
Going to close this, if you have any further questions - please just ask :)

**Comment by Odinsama** [comment]
@bradennapier this did not work for me :( the path variable does not work in runtime because by that time everything is just in bundle.js and the path means nothing, the only way I could make it work is to hard code a path and take no arguments, that way it got transpiled properly by webpack. Anybody else had this issue and/or know a way around it?

**Comment by michelemendel** [comment]
1. I had the same problem with the path, but have no solution
2. The solution above doesn't work for me. The page just hangs. I think the promise is not fulfilled. There is no error.

**Comment by rebolyte** [comment]
Thanks @bradennapier! Your snippet pointed me in the right direction. Note that it can be simplified:
```js
this.firebase = yield call(() => import('./importFirebase.js'))
```
