### ISSUE TITLE
take does not catch PUT from child saga

### ISSUE THREAD

**Issue by anthonychung14** [redux-saga/redux-saga#789]
Multiple actions can be dispatched in a small time-window. Our solution involves batching our calls so that there can only be one outgoing api call at a time.

Any subsequently queued server requests will be condensed into one and await return before dispatching.

This is done by adding a blocking 'yield take' to pause taking from a requestChannel until the server call resolves

Simplified code as follows

```
function* transactionSaga() {
    const requestBuffer = buffers.dropping(1);
    const requestChannel = yield actionChannel(actionIsCreate, requestBuffer);

    yield [
        takeLatest(actionIsRequested, putToChannel),
        fork(watchRequest, requestChannel, requestBuffer, contentBuffer)
    ];
}

function* putToChannel({ payload, meta }) {
    yield call(delay, 200);
    yield put({ type: workingData.transactions.CREATE, payload });
}

function* watchRequest(requestChan, buffer) {
    while (true) {
        const action = yield take(requestChan);
        
        if (reqBuffer.isEmpty()) {
            yield handleRequest(action);
        }            
        
        // blocked here.    
        yield take('DONE');
    }
}

function* handleRequest(action) {
    try {
        yield call(api, packet)
        yield put({ type: 'DONE' })

    } catch (e) {
        yield put({ type: 'err' })
    }
}

```
referring to this https://github.com/redux-saga/redux-saga/issues/598, but I don't think it's relevant given the complexity of the OP's code.

**Comment by Andarist** [comment]
well, you are doing this `yield handleRequest(action);` so it will BLOCK here until `hanleRequest` is done - you have yielded an iterator which is a blocking call

if you want to make this non blocking, just do this instead - `yield fork(handleRequest, action);`

**Comment by anthonychung14** [comment]
I will try it out. Just to clarify:

I want handleRequest to BLOCK until the call completes, then and only then take another request from the channel.

Once handleRequest puts "DONE", the watchRequest Saga does not continue.
Redux dev tools shows that DONE was logged, but watch request does not continue.

I would expect that upon receiving 'DONE', watchRequest would take another item from the channel

-----------

Thus what I'm learning from what you said, yielding an iterator does not allow watchRequest to continue (even if handleRequest completes)

**Comment by anthonychung14** [comment]
yup! you are right. 🎊  we're saga-official now

**Comment by Andarist** [comment]
> Thus what I'm learning from what you said, yielding an iterator does not allow watchRequest to continue (even if handleRequest completes)

Not at all, yielding iterator will block your saga to the moment of its completion. Your problem was that you have yielded an iterator (`handleRequest`) IN WHICH you make `put(DONE)` while `watchRequest` is still blocked on `handleRequest` and when it resumes its geting blocked on `take(DONE)` but it wont resume cause it has already happened.

**Comment by anthonychung14** [comment]
Thank you for the clarification! I think I follow now.

Bad
watchRequest -> handleRequest -> yield put(DONE)  -> watchRequest on take(DONE)

w/fork
watchRequest, fork(handleRequest) -> watchRequest on take(DONE), handleRequest forked and running.

been a lot of fun learning this library. closing!
