### ISSUE TITLE
IE 8 and lower compatibility

### ISSUE THREAD

**Issue by kelsonic** [redux-saga/redux-saga#792]
Since Redux-Saga uses generators, is it compatible with all browsers?

**Comment by slorber** [comment]
@kelsonic since React itself is not supporting IE8 anymore I'd rather not expect tooling created around React ecosystem to be compatible with older IE browsers.

https://facebook.github.io/react/blog/2016/01/12/discontinuing-ie8-support.html

**Comment by kelsonic** [comment]
@slorber Great, thanks! :)
