### ISSUE TITLE
redux-saga take latest action in auto complete compoent ?

### ISSUE THREAD

**Issue by m1m6** [redux-saga/redux-saga#793]
Hi, i have an autocomplete component, when a user start typing, an request sent to the server with the value of input, But i'have a problem with this approach, ex:

when a user type for example : a ==> an request sent to the server with this value, if he continuing writing, for each individual new character a new request sent to the server, but in this way i will overhead my server with too many request, As i use redux-saga takeLatest, the latest request only will be useful for the users, 

`export function* watchForDestinationLocationSearch(){
  yield* takeLatest(types.START_LOCATION_SEARCH+"_destination",getAddresses);
}
`

So how can i prevent/cancel requests to the server, and only execute the last one?

**Comment by Andarist** [comment]
It depends how your `getAddresses` looks. Could you share it with us?

**Comment by m1m6** [comment]
@Andarist 

`


function* getAddresses(action){

  let url = ADDRESSES_ENDPOINT ;
  try {
      const response = yield call(API.fetchAddress,url);
      let options= [];
        response.data.map(function (option) {
          options.push(option);
        });


      let data = {
        options: options
      };

      yield put({type:types.FINISH_LOCATION_SEARCH,payload:response.data});

    } catch (err) {
      yield put({
        type: types.LOCATION_SEARCH_FAILURE,
        payload: {
          _error: err.message
        }
      });
    }
}`

**Comment by anthonychung14** [comment]
I've seen autocomplete with observables, so very interested in a "pull-based" system with generators/sagas. (it will be an upcoming feature for us as well)

**Comment by Andarist** [comment]
well, first of all - you can debounce calls by simply putting a `yield call(delay, 300)` at the beginning of your `getAddresses`, so if `types.START_LOCATION_SEARCH+"_destination"` happens quickly one after the another the task will be restarted and restarted all over again until user really stops typing so you can proceed with your autocomplete request

secondly - if you would like to cancel a request that has already started but you dont care about it anymore you need to attach a cancellation function as `CANCEL` to your request, in a similar way like [here](https://github.com/redux-saga/redux-saga/issues/651#issuecomment-262375964) (keep in mind - it is not possible to cancel a request made with built-in `fetch` API)

**Comment by rezadhah** [comment]
how about you handle it in input onChange? so if the length of input is match with your desire, you dispatch the action to saga?

**Comment by Andarist** [comment]
Going to close this, if you have any further questions - please just ask :)
