### ISSUE TITLE
implementing `either` logic with `race`?

### ISSUE THREAD

**Issue by MoeSattler** [redux-saga/redux-saga#795]
I have a scenario, where I give a user two options, and I want to know which one he choose.
I tried this:

```
const { isAccepted , isDeclined } = yield race({
  isAccepted: take(ACCEPT),
  isDeclined: take(DECLINE),
 })

if (isAccepted) { /* ... */}
else if (isDeclined) {/* ... */}
```

While this works, it's not very elegant. Is there a more idiomatic way to do this with sagas?

**Comment by Andarist** [comment]
It shoukd work exactly as in your edited version. Are u sure that you are using it like that?

**Comment by MoeSattler** [comment]
@Andarist yes, in the end it did work (see the edited text). Though it's seems a bit hacky. I was wondering if there was a better way to do it.

**Comment by Andarist** [comment]
Why do you feel it is hacky? You just need to compare returned key against how you have named your effects

**Comment by MoeSattler** [comment]
@Andarist not if I use IO that is not redux. Then I get whatever that trigger delivers.

**Comment by Andarist** [comment]
Still what you get will be injected in under the key you have described in
the race effect

**Comment by MoeSattler** [comment]
Fair enough. It will work for my use case. 

Just out of curiosity: what if the effect returns `undefined`? (I know, quite edge-case-y)

**Comment by Andarist** [comment]
Well, you will just have undefined under the specified key. So if thats ur
concern you need to make smth like:

const result = yield race({ ... })

if ('isDeclined' in result) {
...
} else {
...
}

**Comment by MoeSattler** [comment]
The underlying problem is, that it is not easy to immediately understand the mechanism, especially for someone who is new to Sagas. We strive to keep our code easy. We also prefer to code our documentation instead of documenting our code. 
And while Saga helps a lot with that, we are just not 100% happy with `race` for our use case. It does do the job though, and a comment will explain.

**Comment by Andarist** [comment]
If you have any better idea how to solve this branching of logic I would be
glad to hear you out. Was also thinking quite a lot about this in a past
but never thought about anything more elegant.

**Comment by MoeSattler** [comment]
I am not sure, tbh. Sorry for the rather unconstructive critique. 😞 
I am relatively new to sagas and try to get all the concepts myself first.

**Comment by Andarist** [comment]
Not a problem, if you have any problems just ping me. Ill try to explain
any of your concerns or answer any of your questions
