### ISSUE TITLE
Recipes wrong import of throttle 

### ISSUE THREAD

**Issue by eks1985** [redux-saga/redux-saga#797]
Inside documentation - recipes - throttling is using import of throttle like this

```
import { throttle } from 'redux-saga'
```

Which caused a warning 

> import throttle from 'redux-saga' has been deprecated in favor of import throttle from 'redux-saga/effects'.
> The latter will not work with yield*, as helper effects are wrapped automatically for you in fork effect.
> Therefore yield throttle will return task descriptor to your saga and execute next lines of code

Need to update documentation page

```
import { throttle } from 'redux-saga/effects'
```

**Comment by Andarist** [comment]
Hey, thanks for noticing. Could you be willing to update the recipes and create a PR with it?

**Comment by eks1985** [comment]
Yes, i try
