### ISSUE TITLE
Access custom component's methods from sagas

### ISSUE THREAD

**Issue by nda2221** [redux-saga/redux-saga#802]
Hi.
How to access to a component's method from saga? For example, I have [this](https://github.com/devBrian/react-native-dropdownalert) DropdownAlert component in my MainComponent. The DropdownAlert is referenced by it's ref. In one of my saga's I do some async fetching, and onError I want to do DropdownAlert.alertWithType('error', 'Error', err).
I was thinking to put a ref to a redux store. But it is not serializable.

**Comment by Andarist** [comment]
You should communicate this with state changes. So the preferred way is to
put action from saga, handle it in your reducers so the state changes and
your component gets notified about it and rerenders or call smth in your
lifecycle hooks

**Comment by nda2221** [comment]
Thanks, buddy!
Can you elaborate more how my component gets notified and rerenders or call smth in your
lifecycle hooks? Shall it happen in shouldComponentUpdate(), or I check a prop in the render() and depending on the state - exec ref.callFunc?

**Comment by Andarist** [comment]
Your render should be pure - so generally only return the react elements, no side effects.

Im not sure what exactly you are using, but im assuming that you use `react-redux`, so your component would get notified about the state change and in your `mapStateToProps` you could set some props based on this state, so the props can be checked in some lifecycle hook - like `componentDidUpdate` and based on that run some callback.

**Comment by nda2221** [comment]
Thanks again.
It works now. I was struggling where to initiate async actions with DOM. componentDidUpdate is the right place.
