### ISSUE TITLE
`yield cancelled()` never returns the value if it's used in a nested generator run by `yield*` and the task is actually cancelled

### ISSUE THREAD

**Issue by roman-g** [redux-saga/redux-saga#803]
Hi,

Most likely I just missed something simple about differences between `yield` and `yield*`, but today I got a strange behavior related to them.

I tried to check if the saga was cancelled, but `yield cancelled()` didn't return the value and just stopped execution if the task was actually cancelled. 
This part of code is located in a separate function because I'd like to make it reusable. So, I ran it using `yield*`, because I read that it's an idiomatic way to compose sagas.

Then I tried to do the same using `yield` and it worked as expected.

Here is the working sample: http://www.webpackbin.com/N1nss1cwf

Code:

```javascript
export default function* root() {
    bin.log("root > enter");   
    const task1 = yield fork(nestedSaga1);       
    bin.log("root > cancel nested saga");   
    yield cancel(task1);  
    bin.log("root > exit");
}

const nestedSaga1 = function*(){
    bin.log("nestedSaga1 > enter");
    //if there is 'yield*', 'cancellation status' log never happens in 'nestedSaga2'
    //if there is 'yield', it works as expected
    yield* nestedSaga2();
    bin.log("nestedSaga1 > exit");
}

const nestedSaga2 = function*(){
    try {
        bin.log("nestedSaga2 > enter");
        yield take("NOT_EXISTING_ACTION"); //a long blocking action...
        bin.log("nestedSaga2 > exit");
    } finally {
        //this log is always written correctly:
        bin.log("nestedSaga2 > finally");      
        const isCancelled = yield cancelled();
        //this is never executed if 'yield*' is used in 'nestedSaga1':
        bin.log("nestedSaga2 > cancellation status: " + isCancelled); 
    }
}

/*
Logs in case of `yield*`:
"root > enter"
"nestedSaga1 > enter"
"nestedSaga2 > cancellation status: false"
"nestedSaga2 > enter"
"root > cancel nested saga"
"nestedSaga2 > finally"
"root > exit"

Logs in case of `yield`:
"root > enter"
"nestedSaga1 > enter"
"nestedSaga2 > enter"
"root > cancel nested saga"
"nestedSaga2 > finally"
"nestedSaga2 > cancellation status: true"
"root > exit"
*/
```

**Comment by r-zzi** [comment]
PS. I understand that `yield*` 'embeds' the nested generator into the parent, and `yield` actually just returns the generator which actually will be executed by redux-saga somehow, but it doesn't explain that behavior to me :)

**Comment by Andarist** [comment]
That's a really interesting case - a possible bug even. In this case your effect is not handled at all and thats why its not returning anything to you, as its geting skipped. Gonna investigate this and return to you when I have some findings.

**Comment by Andarist** [comment]
So it seems its the `regenerator`'s bug. You can read more about it [here](https://github.com/facebook/regenerator/issues/275) (I've filled an issue there)

**Comment by granmoe** [comment]
This is worrying. Does this still happen if we use `yield call(foo)` instead of `yield* foo()`?

**Comment by Andarist** [comment]
`call` is fine fortunately ;)

**Comment by Andarist** [comment]
So it seems that it got fixed in the regenerator itself, but I guess it still need to get into the next version of Babel.
