### ISSUE TITLE
takeLatest + race misses actions

### ISSUE THREAD

**Issue by anthonychung14** [redux-saga/redux-saga#805]
Inside my takeLatest func, I have a task that needs to be repeated until we get a certain server response.

Conversely, I want to cancel the task if we receive a 'LOGOUT' action. I have structured the problem like so

```
function* saga() {
    yield takeLatest(startProcessAction, task)
}

function* task({ payload }) {
    while(true) {
        const { a, b } = yield race({
            response: call(api, payload),
            close: take(tabClosed)
        })

        if (close) { 
            return
        }
        if (response.success) {
            yield put({ type: success, payload: result })
        }
        yield call(delay, 5000)
    }
} 
```

I've confirmed that the actions are being dispatched to the store for "tabClosed", but the saga doesn't pick it up.

I'm guessing it has something to do with takeLatest receiving an action, but not sure where the saga is blocked and not listening to dispatched actions.

**Comment by Andarist** [comment]
Could you provide a timeline 'stream' of your actions? What actions happen and in what order + what you expect to happen in your sagas on each of them.

**Comment by anthonychung14** [comment]
1. Only one polling job exists at a time
2. User opens tab (takeLatest starts task)
3. Polling begins (while loop is in first iteration)

.....5 seconds elapse (while loop is in second iteration. race starts again)

4. User switches tabs
5. New polling job begins (yay takeLatest)

6. User closes all tabs (the event that is being missed by race)
7. Polling stops

**Comment by Andarist** [comment]
could you post exact actions which happens in your project?

**Comment by anthonychung14** [comment]
I replaced the api call with a delay and found that race is working as expected

My api call is a simple fetch.

Should I call a worker with a try/catch block?

**Comment by anthonychung14** [comment]
being blocked on yield call delay makes sense
I'm going to extract the api call into another worker so it goes

try {
yield call(api)
} catch {
} finally {
yield call(delay)

**Comment by anthonychung14** [comment]
THAT WAS IT.

Thank you @Andarist 

I embedded my delay in my api call and it correctly takes now
