### ISSUE TITLE
parallel call returns an object rather than makes a call

### ISSUE THREAD

**Issue by anthonychung14** [redux-saga/redux-saga#806]
This issue is not working as I would have expected. I am receiving the saga's CALL object rather than the results of each POST following this pattern:

`const results = yield postOptionsCollection.map(option => call(parallelPost, option))`

I expected results to be an array of API responses.

I ended up being able to complete parallel calls using this pattern:

```
    for (let i = 0; i < postOptionCollection.size; ++i) {
                    tasks[i] = yield fork(parallelPost, postOptionCollection.get(i));
                }

     for (let i = 0; i < tasks.length; ++i) {
                    yield join(tasks[i]);
                }

```

parallelPost code
```
function* parallelPost(options) {
    try {
        const { results } = yield call(postResource, options);
        yield put({ type: workingData.UPDATE, payload: results });
        yield put({ type: 'WAIT_BASTARD' });

    } catch (e) {
        yield put({ type: 'POST_FAIL' });
    }
}

```
https://github.com/redux-saga/redux-saga/issues/134

**Comment by anthonychung14** [comment]
Seems as though this is expected via here

http://stackoverflow.com/questions/40043644/redux-saga-how-to-create-multiple-calls-side-effects-programmatically-for-yield

thus, how can we take that array of effects and actually instruct middleware to execute?

**Comment by Andarist** [comment]
working as expected - http://www.webpackbin.com/N1hnEHTPM

are you sure you didnt forget to `yield` your array?

**Comment by anthonychung14** [comment]
`const results = yield postOptionsCollection.map(option => call(parallelPost, option))`

that was my code copy pasted. The for-loop + fork + join is working for me, so I'll try it again next time the opportunity arises. if the above pattern is correct, I can conclude it must be my parallelPost call that was wrong.

**Comment by anthonychung14** [comment]
code below
deleteResource returns a promise

I would expect packet.length requests to be made in parallel and instead, nothing happens
```
yield splitNodes.map(packet => call(deleteResource, {
            firstId: packet.getIn([0, 'id']),
            nodes: packet,
            resource: 'content'
        }));
```

**Comment by Andarist** [comment]
Should be ok, can u post a reproduced issue on smth like codesandbox?

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
