### ISSUE TITLE
SagaHelpers: throttleHelper's arguments

### ISSUE THREAD

**Issue by chrisHchen** [redux-saga/redux-saga#807]
I was reading the source code of master branch to try to understand saga a little more. But I got a little confused.
The line I have doubt is here: [argument about throttleHelper](https://github.com/redux-saga/redux-saga/blob/master/src/internal/sagaHelpers.js#L85). The effect creator **take**  has two arguments, is the second one **pattern** really necessary?

**Comment by Andarist** [comment]
I think its obsolete. Thanks for noticing. Would you like to provide a PR with removing it?

**Comment by chrisHchen** [comment]
ok~
