### ISSUE TITLE
Please update index.d.ts

### ISSUE THREAD

**Issue by und3fined** [redux-saga/redux-saga#813]
Hi,

Please update `sagaMiddlewareFactory` interface.
I realize it is not updated to a newer version.

params *emitter* is *require*. Why?
In *[API Reference](https://redux-saga.github.io/redux-saga/docs/api/index.html#createsagamiddlewareoptions)* it was not mentioned as require.

Please update index.d.ts

Thanks.

**Comment by Andarist** [comment]
cc @aikoven

**Comment by aikoven** [comment]
This will be covered by https://github.com/redux-saga/redux-saga/pull/740.

For now, if you're not using `strictNullChecks`, you can set `emitter: null`. Otherwise, you can try this:
```ts
const sagaMiddleware = sagaMiddlewareFactory({...options} as any)
```

**Comment by und3fined** [comment]
@aikoven: Thank for your solution.

Currently, I'm using override code with:

```
/**
 * Redux Saga
 * redux-saga-d.ts
 */
import {SagaMiddleware, Monitor, Emit} from "redux-saga";

declare module 'redux-saga' {
    export default function sagaMiddlewareFactory<T>(options?: {
        sagaMonitor?: Monitor;
        emitter?: (emit: Emit<T>) => Emit<T>;
    }): SagaMiddleware;
}
```

**Comment by Andarist** [comment]
Going to close it for now as issue seems to be resolved. If you have any further issues please reopen.
