### ISSUE TITLE
yield call doesn't run when app is backgrounded?

### ISSUE THREAD

**Issue by EdmundMai** [redux-saga/redux-saga#816]
My redux action will potentially run in the background

```
BackgroundGeolocation.onGeofence(geofence => {
  this.props.prepareOrder();
});
```

Saga:
```

function* prepareOrder(action) {
  // ************* I get the notification **************
  PushNotification.localNotification({
    message: "Your order is now being prepared.",
    soundName: 'default',
  });
  ...
  

  // ************* but this doesn't get called until I foreground the app *********
  try {
    yield call(helpers.saveOrderToOMS, formattedOrder); // <---- runs successfully when my app is  #foregrounded
    yield put({ type: actions.ORDER.FULFILL });
  } catch (e) {
    console.log("Error with request to OMS: ", e);
  }
}

export default function* watchOrderStatus() {
  yield takeEvery(actions.ORDER.PREPARE, prepareOrder);
}

```

When my app is foregrounded it works. I am looking at my server log to see when the `helpers.saveOrderToOMS` request is made, and it doesn't happen until I foreground my app.

Is there a way to make `yield` run even when my app is backgrounded?

**Comment by restrry** [comment]
it should work. probably the problem is in gelococation plugin itself. for example https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/267

**Comment by EdmundMai** [comment]
It seems to be working again... I'll close this issue and reopen it if I notice it happening again.
