### ISSUE TITLE
Saga Middleware Documentation Improvement Suggestions

### ISSUE THREAD

**Issue by Judahmeek** [redux-saga/redux-saga#817]
Apologies in advance for some unrefined stream brainstorming. I've been experimenting with React/Redux/etc (and Webpack and Yarn and ... @.@) for a couple months now and am in the process of switching from thunk to saga: https://github.com/Judahmeek/Teropa-React-on-Rails

I've ran into a few speed-bumps along the way. The two greatest issues I recall are:

1. Figuring out how to give a saga an action as a parameter (since the fact that the triggering action is provided as the first parameter to the saga is never explicitly stated in the documentation), and 

2. Dealing with infinite loops because the fact that `yield put` triggers the middleware again is also not explicitly stated in the documentation. Small detail and probably only something that will be ran into by students like myself (because most real world examples that I've seen seem to split from requestSagaAction to successOrFailureActions), but pretty frustrating to troubleshoot.

   * Also, I was surprised to discover that [the Middleware pushes actions to the reducer before filtering them through running sagas.](https://github.com/redux-saga/redux-saga/blob/master/src/internal/middleware.js#L78-L79) I get the reasons for it, but as far as I know, this also isn't documented except through issues and source code. Something like this should be especially documented since it runs contrary to the concept that ["[Redux Middleware] provides a third-party extension point between dispatching an action, and the moment it reaches the reducer."](http://redux.js.org/docs/advanced/Middleware.html).

This isn't just a flame post. I'll be more than happy to submit a Doc PR eventually, but thought that it would be best to post my thoughts for discussion and correction first. Thanks for your time and feedback. 🎉

**Comment by Andarist** [comment]
Hey, I've read your issue before, but didnt have time yet to respond.

I think you've raised legitimate concerns about that some things could be explained better in the docs. Such discussions are always welcome on our board. We strive for better!

**Comment by Judahmeek** [comment]
@Andarist: Much appreciated. Once things settle down, I'll review this issue again. Coming from `redux-thunk`, my biggest obstacles (other than a minimal understanding of how redux middleware works) was:
1. That there is no documentation that sagas receive `action` implicitly from `takeEvery`, and
2. That there was no warning that `yield put` triggers all the middleware again, creating the possibility for infinite loops.

In my case, I naively tried replacing `dispatch` with `yield put` and resolving the resulting infinite loops required asking questions on [Reactiflux's discord server](https://www.reactiflux.com/) and examining Redux documentation regarding middleware and `store.dispatch` vs `next`.

Granted, these are things any redux dev should know, but I would love to see pointers to them in `redux-saga` documentation. In fact, since it's likely? that many of the devs adopting `redux-saga` are porting over from `redux-thunk`, ya'll might want to consider a section listing common obstacles and concepts (not in detail, but with links) specific to a redux-thunk migration.

**Comment by Andarist** [comment]
Would you maybe be willing to create such docs section and send a PR as you have just experienced the problems and know from the first hand what troubled you the most? Would appreciate this greatly, dont have much time for improving the docs lately :/

**Comment by Judahmeek** [comment]
I'm certainly willing to explore the idea. Here's hoping it doesn't take me forever and a day to get around to it.
