### ISSUE TITLE
Can't dispatch ( put ) from catch clause

### ISSUE THREAD

**Issue by reharik** [redux-saga/redux-saga#819]
Hi I have an fetch saga that performs a fetch and if it fails get's caught in the try catch, much like all the examples.  I land in the the catch clause no problem but the put never dispatches my action. The code looks like this.
`function* request(action) {
  let response;
  let payload;
  try {
    response = yield call(fetch, action.url, action.params);
    payload = yield response.json();

    if (!response.ok) {
      throw new Error(response);
    }
    if(payload && payload.result && !payload.result.success){
      throw new Error('Server was unable to complete the request');
    }
    yield put({type: action.states.SUCCESS, action, response:payload});
    } catch (err) {
    yield put({type: action.states.FAILURE, action,  err});
   }
}`
( sorry can't get the formatting )
the success path works fine, the catch path gets hit, and console logs show up but the action never shows in the browser logs.

**Comment by Andarist** [comment]
There should be no problem with that. Could you provide a reproduced example of the failing behaviour on something like webpackbin?

**Comment by reharik** [comment]
Indeed, I'm very sorry, massive case of user error.  
Thanks for a great plug in.
r
