### ISSUE TITLE
disable logger in production builds

### ISSUE THREAD

**Issue by anthonychung14** [redux-saga/redux-saga#835]
production builds have logging still happening from the utils file

https://github.com/redux-saga/redux-saga/issues/343

there is no documentation (that I could find) indicating how to accomplish this other than stating that there is a  "logger" option in the createSagaMiddleware

mainly all the console.infos that inform me when a task is cancelled

**Comment by Andarist** [comment]
According to the [source code](https://github.com/redux-saga/redux-saga/blob/3b90d33d27cb1a5aa99e8672b47cf8e496d686f6/src/internal/proc.js#L277-L279) this log should happen only in dev builds. Are you sure you have correctly configured your build?

**Comment by anthonychung14** [comment]
You are correct. I did not read the source code/issue correctly in the above issue
