### ISSUE TITLE
Race for the latest

### ISSUE THREAD

**Issue by sospedra** [redux-saga/redux-saga#840]
Is there something like `race` but for the latest instead of the first?

Suppose I've got two forked tasks. And I want to `put` an action when the last one is done. How would I do that?

Thanks 🥇

**Comment by sospedra** [comment]
I resolve it with `join`. Dunno if super correct.

**Comment by Andarist** [comment]
`join` is good, especially as you now can join on multiple tasks with single effect, this works if your tasks run in parallel, if they need to be called in a waterfall manner it might be good to implement a helper for this.
