### ISSUE TITLE
How to define function that calls yield?

### ISSUE THREAD

**Issue by EdmundMai** [redux-saga/redux-saga#841]
I am using WebRTC with redux sagas. One requirement is that I have to define `peerConnection.onicecandidate`:

```
let peerConnection;

function* createPeerConnection(action) {
  ...
  peerConnection = new RTCPeerConnection(servers);

  peerConnection.onicecandidate = (event) => {
    if (event.candidate) {
      yield put({ type: videoSessionActions.SEND_LOCAL_CANDIDATE, payload: event.candidate });
    }
  }
}
```

However, yield put is not working in this method. How would I change this so that it works with sagas?

**Comment by granmoe** [comment]
@EdmundMai It would be nice if you could get the result of peerConnection like

`const event = yield call(peerConnectionPromiseMethod)`

But I'm not sure if you have a way to force this into something that returns a promise. This is easiest, but it looks like it probably won't work for your case here. So I think you might end up needing to use the event channel described here to connect these external events to redux-saga:

https://redux-saga.github.io/redux-saga/docs/api/index.html#external-api

**Comment by Andarist** [comment]
as mentioned `eventChannel` is probably a way to go :)
