### ISSUE TITLE
logout action not working on browser refresh

### ISSUE THREAD

**Issue by prudhvisays** [redux-saga/redux-saga#842]
logout is working If I didn't refresh the browser.After refeshing the browser logout not working. Is there any solution for it?
Below is the saga code that I had written for the logout action

```
//...function

    export function* logout() {
          yield put({ type: 'SENDING_REQUEST', sending: true });

          try {
            let response = yield call(auth.logout);
            yield put({ type: 'SENDING_REQUEST', sending: false });
          } catch (error) {
            yield put({ type: 'REQUEST_ERROR', error: error.message });
          }
        }

        export function* logoutFlow() {
          while (true) {
            yield take('LOGOUT');
            yield put({ type: 'SET_AUTH', newAuthState: false });
            yield call(logout);
            forwardTo('/login');
          }
        }

        export function* logoutRoot() {
          yield fork(logoutFlow);
        }

        export function* watcherRoot() {
          const watcher2 = yield fork(logoutRoot);
        }

        export default [
          mainRoot,
          watcherRoot,
        ];
```

**Comment by Andarist** [comment]
Should work just fine, can you create a reproduced issue on something like webpackbin?

**Comment by prudhvisays** [comment]
https://github.com/prudhvisays/newsb/blob/master/app/containers/AuthPage/sagas.js
use the above link to go through code 👍

**Comment by Andarist** [comment]
Yeah, but seeing the code is not exactly the same as reproduced issue - I mean that I cant debug it ;) Reproduced example in the wild would be really helpful for tracking this down.

**Comment by prudhvisays** [comment]
I am a beginner . I dont know how to use webpackbin. Is there any other way that you can help out?
btw using react-boilerplate
