### ISSUE TITLE
Queue system

### ISSUE THREAD

**Issue by mike623** [redux-saga/redux-saga#844]
Here is the usecase: 
1. I have multiple task
2. Each task need upload multiple files
3. The queue of each task is dynamic (I can keep add file when uploading)
4. only `put` once all files upload

Something like
````
{
  task1: [uploadSaga1, uploadSaga2],
  task2: [uploadSaga1, uploadSaga2],
}
````
what I have
================
- upload saga(i.e. able to `put`/`call` anything after upload success)

what I need
===================
- how to `queue` sagas to let the task keep running util uploaded all files?

**Comment by Andarist** [comment]
Aint sure if I got your problem correctly, but you should be able to do this easily with `actionChannel`:
```javascript
const buf = buffers.expanding()
const chan = yield actionChannel(UPLOAD_FILE, buf)

while (true) {
	const file = yield take(chan)

	yield call(upload, file)

	if (buf.isEmpty()) {
		yield put(UPLOAD_SUCCESSFUL)
	}
}
```
