### ISSUE TITLE
select() is not syncronous

### ISSUE THREAD

**Issue by TrevorHinesley** [redux-saga/redux-saga#845]
In the below code, customer is empty when it's stringified. Upon checking its value, it's not empty (and stringifying it works properly). It's like it hasn't finished selecting the state before it gets assigned to options.

```
/**
 * Create customer
 */
export function* createCustomer() {
  // Select customer info from store
  const customer = yield select(makeSelectCustomer())
  const subscription = yield select(makeSelectSubscription())
  const requestURL = `${process.env.API_URL}/customers`

  try {
    const options = {
      body: JSON.stringify({
        data: {
          type: 'customers',
          attributes: customer,
          relationships: {
            subscriptions: {
              data: [
                {
                  type: 'subscriptions',
                  attributes: subscription
                }
              ]
            }
          }
        }
      })
    }

    // RIGHT HERE - if i put a debugger, customer is a full 
    // object, but if i check options, it's missing the attributes key (aka no customer). 
    // Sometimes this works, sometimes it doesn't. It's like 
    // customer isn't being yielded yet before it's being 
    // assigned to the above body parameter (sometimes).

    // Call our post helper (see 'utils/request')
    const response = yield call(post, requestURL, options)
    yield put(destroy('registration'))
    const customer = response.data
    const session = response.included[0]
    yield put(customerCreateSuccess(customer, session))
  } catch (err) {
    yield put(customerCreateError(err))
  }
}
```

**Comment by TrevorHinesley** [comment]
Confirmed. I tried doing `attributes: customer.toJS()` (because it's an ImmutableJS Map), and it's undefined. But again, if I put a debugger after options has been defined, customer is a full object by the time the debugger has triggered.

**Comment by Andarist** [comment]
`select` effect is completely synchronous. Is wrong options object geting passed into your `yield call(post, requestURL, options)` ?

**Comment by TrevorHinesley** [comment]
As the code above shows, the issue is visible before that call you referred to ever happens.

**Comment by Andarist** [comment]
If you use `regenerator-runtime` it might twist your code a little bit, ive already once got onto this when I was really surprised that some of my `console.log`'s were displayed out of order. 

That's why im asking if the wrong value is geting into the call a line below.

**Comment by TrevorHinesley** [comment]
I'm not sure what regenerator-runtime is but I'm not using it. This saga is dispatched via another saga that is watching for an action. The action is dispatched after a redux-form is submitted, but all of that is fairly irrelevant since this seems to just be some sort of sync issue.

**Comment by Andarist** [comment]
`regenerator-runtime` transpiles your generators thanks to babel, if you use `babel-polyfill` you probably use this

Could u create a reproduced issue on something like webpackbin?

**Comment by TrevorHinesley** [comment]
Ahh I gotcha. I'll see if I can! Thanks again for the help.

**Comment by TrevorHinesley** [comment]
I actually think this was a bizarre race condition where the form was submitting twice before the first saga execution completed. I'm not entirely sure, but adjusting some triggers fixed this (I believe). Sorry for the headache!
