### ISSUE TITLE
Will memory gets consumed more when running all sagas combined together

### ISSUE THREAD

**Issue by RajeshSivanesan** [redux-saga/redux-saga#846]
We have been using redux-sagas for a while, during initialization of saga-middleware, we do run all sagas together in one shot.

Consider all my sagas are running on infinite loop, listening for a certain type of action. Since these all sagas are running together (infinitely too) will it consume more memory.

If we are using this with React Native, will there be any performance impact ?

**Comment by anthonychung14** [comment]
There will undoubtedly be a performance impact.

The question is: do the benefits conferred by such a library outweigh the memory needed for your sagas?

IMO until you come across evidence of a memory leak or experience decreased performance, it seems like a hard question to answer

**Comment by Andarist** [comment]
How much memory can really sagas take? You shouldnt be overconcerned about such issues prematurely - only when you meet some memory leaks and even then it could be investigated in the library itself so it could become more performant for every user.
