### ISSUE TITLE
saga carousel?!

### ISSUE THREAD

**Issue by anthonychung14** [redux-saga/redux-saga#848]
I am trying out sagas with carousel jobs. Namely, when a button is pressed, it starts a backgroundTask that will alter the ordering of images on a data node after a delay.

There can be many of these tasks forked in the background and running

I have a basic implementation going with the following approach

1. switchWorker saga that maintains a hashMap of jobs. If there is no job, create one. If you receive action for same job, cancel it (meaning they toggled the option off)

2. race between cancel event and delay + switch pictures worker

-------------

Questions:

1. How would you handle component deletion? (if client deletes the carousel, I do not cancel the subroutine)
2. If a user has many carousels running, will these subroutines take up MORE memory than doing a setInterval on each component? 
3. How would you handle initialization? Say that upon entering a new state, they have some carousels already toggled on

**Comment by Andarist** [comment]
Could u post some shortened (or full) code examples? I always find myself reasoning about the code better

@memory
Well, ofc a subroutine will take more memory (shouldnt be too much though) than interval as its way more complex structure

**Comment by anthonychung14** [comment]
I ended up solving it with liberal use of 'meta' tags to identify tasks in a map (similar to how you showed me with takeLatestByProp helper)

Code here
```
export default function* switchWorkersByProp(propsOrSelector, pattern, worker, taskMap) {
    // eslint-disable-next-line no-constant-condition
    while (true) {
        const action = yield take(pattern);
        const propsVal = typeof propsOrSelector === 'function' ?
            propsOrSelector(action) : action[propsOrSelector];

        if (!taskMap[propsVal]) {
            taskMap[propsVal] = yield fork(worker, action, taskMap);

        } else {
            taskMap[propsVal].cancel();
            taskMap[propsVal] = false;
        }
    }
}

export default function* componentContent() {
    const taskMap = {};
    yield [
        switchWorkersByProp('meta', activateBgCycle, bgCycleWatcher, taskMap),
    ];
}

const cancelMeta = (action, meta) =>
    action.type === CANCEL &&
    action.meta === meta;

function* bgCycleWatcher(action, taskMap) {
    const { meta } = action;
    yield race({
        worker: call(bgCycleWorker, action, taskMap),
        cancel: call(bgCycleCancel, action, taskMap),
        end: take(act => cancelMeta(act, meta))
    });
}

function* bgCycleCancel(action, taskMap) {
    const { meta } = action;

    while (true) {
        // check if any delete operation matches the meta
        const deleteAction = yield take(DELETE);
        const shouldStopBgCycle = deleteAction.payload.some(node => node.get('id') === meta);
        // if yes, cancel the job
        if (shouldStopBgCycle) {
            yield put({ type: CANCEL, meta });
        }
    }
}

function* bgCycleWorker(action, taskMap) {
    const { meta } = action;

    while (true) {
        yield call(delay, delayTime * 1000);

        yield put({
            type: actionTypes.workingData.node.bgCycle.SWITCH,
            payload: meta
        });
    }
}
```

interested on how you'd approach it. was a fun problem to solve with sagas

**Comment by eliseumds** [comment]
@anthonychung14 if you're interested, this are sagas for timers components (multiples ones may be instantiated): https://gist.github.com/eliseumds/bdefeb7a7bfc4275ba90298791740511

**Comment by anthonychung14** [comment]
oh nice! this is an interesting approach. I saved this since I imagine us using more eventChannels in the near future. thank you

**Comment by eliseumds** [comment]
@anthonychung14 ye, I had to move to channels because of clock sync issues. At first, I was using this naive approach:

```js
while (true) {
  yield delay(1000);
  yield put(incrementTimer(id));
}
```

But, since it takes a few milliseconds to go the coordinator and get back (~2-3ms), after a while, instead of showing 50min, for example, my clock was showing 49min. Channel solved it because it runs independently.

I'm also using channels in a file uploader workflow to [keep track of the request progress](https://gist.github.com/eliseumds/3f4d5c1b0d81f02121af79c224f5db8d).
