### ISSUE TITLE
more saga v. observable chatter

### ISSUE THREAD

**Issue by anthonychung14** [redux-saga/redux-saga#850]
at a certain fork (lol) in my learning, I was choosing between RxJS and sagas, chose sagas because Redux Observable wasn't as well-supported at the time.

that being said, I have two questions:

1. flexibility vs. observables: rx is prolific library for streams. what use cases can it handle that saga patterns will have trouble dealing with?

- a. I saw an observable pattern PR in the backlog, if they are implemented via generator/saga pattern, will you capture most of the use-cases that observables handle?

2. memory usage vs. observables: observables (to my understanding) are the pipes that you setup beforehand to direct different streams of data. in my mind, this translates to less memory used, which then means better performance. this seems different than the imperative-style of

- a. take from this channel, then do this
- b. wait for X action, when X, do Y

as our saga codebase grows, I'm trying to be proactive about tech decisions we might have to make down the road.

MobX is lightweight and a possible alternative
Relay is powerful, but not sure yet if its worth it to setup yet

**Comment by Andarist** [comment]
Mentioned PR is just for ease of converting streams for channels, nothing more. 

About concept differences you can read [here](https://github.com/redux-saga/redux-saga/issues/105#issuecomment-182831804). 

I think for new comers saga is more flexible, you dont have to get your head wrapped about all of those operators which are used by observables libraries. Also in general modeling complex scenarios is easier with saga (at least for me), however stream solutions feel more elegant in the end.

It all boils down to personal preference really.

@performance
You shouldnt worry too much about this, both should handle very wide range of scenarios just fine without troubles.

**Comment by anthonychung14** [comment]
ahh yes yelouafi's explanation was extremely insightful around push/pull data sources.

thank you!
