### ISSUE TITLE
call versus apply argument assumptions

### ISSUE THREAD

**Issue by blueish** [redux-saga/redux-saga#851]
Is there a reason why the `call` effect automatically structures the rest of its parameters into an array, while the `apply` effect expects the third argument to be an array of arguments?

It seems inconsistent to have this be the way to use a call:
```javascript
const data = yield call([myContext, myApiFunction], arg1, arg2);
```
whereas for apply you must explicitly structure the arguments into an array:
```javascript
// This doesn't work:
const data = yield apply(myContext, myApiFunction, arg1, arg2]);
// this does:
const data = yield apply(myContext, myApiFunction, [arg1, arg2]);
```

Relevant context: https://github.com/redux-saga/redux-saga/blob/283cc6c168e5773854e44dce66cda70bb1a1d0a9/src/internal/io.js#L78
The difference is the `call` function using the rest parameter syntax to collect the remaining arguments into an array, while the `apply` function is assuming they will be inputted as an array.

**Comment by Andarist** [comment]
its straightforward analogy to javascript's [`Function.prototype.apply`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply) and [`Function.prototype.call`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call)

**Comment by blueish** [comment]
Makes sense that it's based on the function prototypes. Thanks!
