### ISSUE TITLE
Better redux saga debugging tools for the console

### ISSUE THREAD

**Issue by aight8** [redux-saga/redux-saga#852]
I often came to the situation I required a structural representation of my root saga to understand how the current state looks like. There is an example code which achive that but it's very verbose, and there is an working in progress saga dev tools however it's only for the browser anyway.

It were nice to provide a simple function for development which can output a compact tree like structure of the current root saga to the console. Even better if it supports colors.

This would help a lot that people understand how the current redux-saga "state" look like.

Compared to debug just a simple variable, debugging the complex state of redux-saga is much more difficult to understand the situation.

**Comment by anthonychung14** [comment]
Were you referring to SagaMonitor? It provides an expanded tree, but you can compact it yourself.

I imagine there's something within the monitor source code that defaults to an expanded view as well.

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
