### ISSUE TITLE
Feature Request: call([ context:Object, fn:String ], args...) syntax

### ISSUE THREAD

**Issue by ThisIsMissEm** [redux-saga/redux-saga#855]
Given this existing in scope:

```
function MyClass() {
  this.foo = "foo";
}

MyClass.prototype.useFoo = function useFoo(bar) {
  console.log('useFoo', this.foo, bar)
}

var MyInstance = new MyClass()
```

If I use `call(fn, args...)` then I expect to get an error:

```
yield call(MyInstance.useFoo, 'bar')
```

This is fails, as we know, because `useFoo` will be called in the context of `null` instead of `MyInstance`. Hence, I have to use the syntax of: `call([ context, fn ], args...)`

```
yield call([ MyInstance, MyInstance.useFoo ], 'bar')
```

Which will now succeed, logging `'useFoo', 'foo', 'bar'` to the console.

This is great, and works as expected, however, it is a little bit verbose, as such I'd like to propose a secondary syntax; Currently we can annotate `call` as:

- `call(fn:Function, ...args)`
- `call([ context:Any, fn:Function ], ...args)`

I'd like to propose the signature of:

- `call([ context:Object, fn:String ], args...)`

This would enable the above to be written as:

```
yield call([ MyInstance, 'useFoo' ], 'bar')`
```

Note: Object = anything that derives from Object, so Functions, Constructor Instances, Classes, Class Instances, etc.

---

Granted the side-effect of this is that you wouldn't receive flowtype/typescript type checking to assert that `fn` exists on `context`, where as using `call([ context:Any, fn:Function ], ...args)` does give you type checking that the fn is callable (still doesn't give support for type checking arguments though.

**Comment by Andarist** [comment]
Actually I've already implemented it, but its hanging on PRs (https://github.com/redux-saga/redux-saga/pull/826). I hope to move things a little bit faster soon, but for now I didnt have time to finish such things as this which ive started and wanted to release under v0.15

**Comment by Andarist** [comment]
It got released yesterday :)
