### ISSUE TITLE
Testing endless loops

### ISSUE THREAD

**Issue by codepunkt** [redux-saga/redux-saga#862]
I've been doing a lot of work with both `redux-observable` and `redux-saga` and so far i like the testability of sagas a lot!

What i don't get is the testing of endless loops/watchers. e.g.

```javascript
import { call, take } from 'redux-saga/effects'

import logout from './logout'
import LOGOUT from '../constants'

export function* logoutWatcher () {
  while (true) {
    yield take(LOGOUT)
    yield call(logout)
  }
}
```

so far i'm testing this (with `jest`) using something along the lines of

```javascript
import { call, take } from 'redux-saga/effects'

import logout from '../logout'
import LOGOUT from '../../constants'
import logoutWatcher from '../logoutWatcher'

describe('logoutWatcher', () => {
  const generator = logoutWatcher()

  test('takes a LOGOUT action', () => {
    expect(generator.next().value).toEqual(take(LOGOUT))
  })

  test('takes a LOGOUT action', () => {
    expect(generator.next().value).toEqual(call(logout))
  })
})
```

This verifies that the logoutWatcher watches for and takes `LOGOUT` actions and calls the `logout` method afterwards. This does not verify that this is actually running in an endless loop.

_How do i verify that the watcher is running in an endless loop?_

**Comment by beldur** [comment]
In your specific case you could use the `redux-saga` helper `takeEvery` (See [Docs](https://redux-saga.github.io/redux-saga/docs/basics/UsingSagaHelpers.html)).
The code would look like this:

```js
import { takeEvery } from 'redux-saga/effects'

import logout from './logout'
import LOGOUT from '../constants'

export function* logoutWatcher () {
  yield takeEvery(LOGOUT, logout)
}
```

This way you leave the responsibility of running the loop to `redux-saga`.

`takeEvery`'s loop is tested here with a simple `for` loop: [/test/sagaHelpers/takeEvery.js](https://github.com/redux-saga/redux-saga/blob/master/test/sagaHelpers/takeEvery.js#L30)

**Comment by codepunkt** [comment]
That doesn't verify the endless loop, though. It only verifies the first x runs - which is probably enough ;-)

**Comment by aikoven** [comment]
Isn't it the same as trying to solve the Halting problem?

**Comment by codepunkt** [comment]
@aikoven Most likely is.

Do you

- test the loop x times?
- test the loop once?

If you test it more than once - how large is your x?

**Comment by aikoven** [comment]
I think it's enough to test all the states where the process can possibly be, and that it then comes back to the first state.

**Comment by codepunkt** [comment]
Thanks for everyone's opinions! I'm going to close this.

If anyone manages this in a different way, feel free to continue the discussion 👍
