### ISSUE TITLE
How to use Flowtype with redux-saga?

### ISSUE THREAD

**Issue by gajus** [redux-saga/redux-saga#864]
I saw this issue, https://github.com/redux-saga/redux-saga/issues/358

But I am still not clear how to write basic type annotations for `redux-saga` code. Suppose this example:

```js
const selectSuggestion = function *() {
  yield takeLatest('LOCATION_FORM_SELECT_SUGGESTION', function *(action) {
    yield put(changeStatus('not-in-use'));
    yield put(setCurrentAddress(action.payload.description));
  });
};
```

What is supposed to be the type of `selectSuggestion`?

**Comment by mhink** [comment]
Go take a look at the [`flow-typed`](https://github.com/flowtype/flow-typed/tree/master/definitions/npm/redux-saga_v0.13.x) definitions- they should help. Unfortunately, I think they're a bit out of date just at the moment, so you might have a bit of trouble getting them to work perfectly.

That being said, I've always found Flow's type inference to work rather well for this purpose. Try this:

```
const selectSuggestion: * = function* () {
  /*...*/
}
```

**Comment by neurosnap** [comment]
I'm running into a lot of issues with the flow-typed definitions as well, primarily with using the effects.

```js
yield fork(processThreadResponses, {
    responses: responses.filter((r) => r),
    replace,
    replaceFolder,
});
```

Flow error: function call Function cannot be called on any member of intersection type intersection

This error in particular has plagued my codebase with seemingly no solution.  I would love any feedback on how to get rid if of this nefarious error.

**Comment by anthonychung14** [comment]
any updates or tips on these?
should we look into adding Task descriptors?

**Comment by Andarist** [comment]
I would love to incorporate some solution for you guys, but unfortunately I have no flow (or TS) experience and I need the community to provide a solution for this.

**Comment by mimshwright** [comment]
@Andarist In short, flow expects you to define a type for yield, return, and next. https://flow.org/blog/2015/11/09/Generators/

**Comment by Andruschenko** [comment]
@neurosnap Did you find any solution to your problem so far?

**Comment by fengerzh** [comment]
@gajus I think you need to define a `Iterable<any>` in your functions as below:

```
export function getActivities(api: any) {
  function * worker(): Iterable<any> {
    const response = yield call(api.getActivities);

    if (typeof response === 'undefined') {
      throw new Error('`response` should be an object.');
    }
    if (response.ok) {
      const activities = path(['data'], response);
      yield put(Actions.activitiesSuccess(activities));
    } else {
      yield put(Actions.activitiesFailure());
    }
  }

  function * watcher(): Iterable<any> {
    while (true) {
      yield take(Types.ACTIVITIES_REQUEST);
      yield call(worker);
    }
  }

  return {
    watcher,
    worker
  };
};
```

**Comment by gajus** [comment]
> @gajus I think you need to define a Iterable<any> in your functions as below:

Thats a bad idea. A better option is `Iterable<*, *, *>`.

**Comment by Andarist** [comment]
Thanks to the great work by @Alxandr, `flow-typed` has now updated [`redux-saga` typings](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/redux-saga_v0.16.x/flow_v0.56.0-/redux-saga_v0.16.x.js). Closing the issue now, if there are any problems with new typings, please report them here by creating a new issue or fix them in `flow-typed` repository.

If you have any suggestions on what is the best way to incorporate typings directly into `redux-saga` repository - please let me know. From what I understand the biggest problem is that typings are targeting specified range of flow versions and having them directly in the repository kinda locks them down to that range and might cause problems for people using versions from outside the range.

**Comment by mackbrowne** [comment]
@Andarist  any working examples of this?  I'm using Iterable<Effect> for my watcher, but I can't figure out how to properly type my worker?  Using 'any' right now, which i'd like to avoid.

@gajus you seem to know what your talking about, any advice?

**Comment by Andarist** [comment]
Unfortunately not, I'm not using any typings with redux-saga at the moment. The typings were provided by @Alxandr, maybe he could give some examples.

**Comment by yfr** [comment]
Have the same issue. Update to the newest typing (Thanks @Alxandr!) but I dont't get it to work properly. An example would be great!

**Comment by Alxandr** [comment]
There is a `Saga<T>` type. If I understand you question correctly. Example:

```js
function* mySaga(): Saga</* return type */ void> {
  yield put(myEffectCreator());
}
```

**Comment by Andarist** [comment]
What about `call` usage? Can LHS be typed nicely in relation to RHS?

**Comment by mackbrowne** [comment]
@Alxandr thanks so much for the quick reply.  You were correct and helped me remove the only 'any' from my typings.

Here's what I have now 

```
export function* initializeAsyncStateWorker(action: Action): Saga<void> {
  try {
    yield put(initAppSuccess());
  } catch (err) {
    yield put(initAppError(err));
  }
}

// Watcher
export function* initWatcher(): Iterable<Effect> {
  yield takeEvery(INIT, initializeAsyncStateWorker);
}
```

I'm using Saga<void> for the worker.  However is Iterable<Effect> anywhere close to what I should be using for the watcher?  I kinda figured it out by trial and error, I have no idea if it's correct

**Comment by Alxandr** [comment]
@mackbrowne just use `Saga<...>` for both. Some examples:

```js
function* loginSaga(username: string, password: string): Saga<User | null> {
  const result = yield call(doTheActualLogin, username, password));
  if (result.success) {
    return result.user;
  } else {
    return null; // or error
  }
}

function* handleLoginSaga(action: LoginAction): Saga<void> {
  const user = yield call(loginSaga, action.payload.username, action.payload.password);
  if (user !== null) {
    yield put(setUser(user.id));
  } else {
    yield put(setLoginFormError('Wrong username or password'));
  }
}

function* rootSaga(): Saga<void> {
  yield takeEvery(LOGIN, handleLoginSaga);
}
```

**Comment by Andarist** [comment]
@Alxandr is `result`'s type in your `loginSaga` inferable from `doTheActualLogin`?

**Comment by mackbrowne** [comment]
@Alxandr wow i feel dumb now!  Thanks so much dude!

**Comment by Alxandr** [comment]
@Andarist I'm not entirely sure. It might be. But, it is **strongly recommended** that you always type sagas as being type `Saga<....>`. It's very possible that `Saga<*>` would work just fine, I haven't tried that. But if you do not type the saga, flow has a tendency to do weird things with generators.

**Comment by rolandhordos** [comment]
I like how this cues you to shape the output of your generators / sagas.

i.e. `User | null` is a discrete contract, versus the variety of effects that might be emitted otherwise.

**Comment by rolandhordos** [comment]
I like how this cues you to shape the output of your generators (i.e. `User | null` is a discrete contract).

**Comment by EugeneZ** [comment]
@Andarist 
> @Alxandr is `result`'s type in your `loginSaga` inferable from `doTheActualLogin`?

No, unfortunately. It's type `any`, which you can see by using `flow type-at-pos` or simply by changing `result. success` in the next line to something that would obviously cause an NPE like `result.sucess.garbage.that.causes.exceptions` and flow won't utter a peep.

The easiest way to get around this is to explicitly type the LHS:

```const result: ActualLoginRV = yield call(doTheActualLogin, username, password));```

Since it's `any` already, flow won't complain that you are narrowing it. However, if you make a mistake doing this (like, say, `doTheActualLogin` is later changed to return a different type), flow will not complain.

If you want more soundness and are willing to go through the effort, you can create use-specific generators and use `yield *` to "proxy" them, which preserves the type information:

```function* callPromise<Args: Array<*>, T>(
  fn: (...args: Args) => Promise<T>,
  ...args: Args
): Saga<?T> {
    return yield call(fn, ...args);
}

function* loginSaga(username: string, password: string): Saga<User | null> {
  const result = yield* callPromise(doTheActualLogin, username, password));
  if (result.success) {
    return result.user;
  } else {
    return null; // or error
  }
}
```

Now, since you are splaying the effects, and `callPromise` is explicitly describing the mechanism that `redux-saga` uses to resolve `Promise`s, `flow` will actually strictly enforce the LHS/RHS relationship. But fi you mess with `callPromise` you can introduce silent errors again. And if you forget to use it. And this only works for `Promise`s so you have to make custom versions of these for anything else you want that `redux-saga` handles.

I would love to figure out a better way of doing it. Maybe the key is in adding another generic type to `Saga<...>` that relates the third arg (`Next`) with the effect.

**Comment by Alxandr** [comment]
I see now that I misread this question initially. Unfortunately, anything to the left of `yield` will be typed as `any`. No good way around it for now (unless you want to only yield 1 thing in the saga).

**Comment by retyui** [comment]
Here a small but useful example:
https://gist.github.com/retyui/533cc4e13949a70a64aa7959d95da22d
