### ISSUE TITLE
Application-level pub/sub messaging with eventChannel

### ISSUE THREAD

**Issue by codyrushing** [redux-saga/redux-saga#866]
I've been exploring using `eventChannel` to set up a simple pub/sub system for my redux app, but despite reading the docs I'm having trouble setting this up.  Ideally, here are the two functions I would like to expose in my app:

* __`on(eventName, callback)`__ - allows a listeners to register callback for events by name.
* __`trigger(eventName, payload)`__ - allows emitters to emit events with a name and a payload.

I don't really want to use the store for this, as events are more "fire and forget" and should not persist.  There are pub/sub libraries that I could use, but I'm already using `redux-saga` and see that it supports event channels, I just can't quite wrap my head how to architect it.  My guess is that it would involve building an event channel responsible for emitting events, while also running a saga that watches for those events and sends their payloads to the appropriate callbacks, but I'm still not sure how to bring it all together with simple __`on`__ and __`trigger`__ methods.  Is this easy to set up with `redux-saga` or should I go with a pub/sub library.  Thanks!

**Comment by Andarist** [comment]
I aint sure how you would like to leverage eventChannel for ur use case. Its intended as wrapper around external event sources so the things such source emit can be consumed by takers in ur sagas.

Excellent example for this is a websocket connection - you just wrap ur logic in a channels callback where it exposes u an emit function and whatever you emit from inside will get put into the channel so you can take(channel) from it.

Is this behavior of any value to u? Does it satisfies ur requirements somehow?

For an event bus solution i would go with developit/mitt - its super easy and super straightforward. Aint sure what communication do u need with ur sagas though. Maybe ur event bus should be wrapped by an eventChannel so its events could be consumed by saga? Anyhow - would need more info to advice properly

**Comment by codyrushing** [comment]
@Andarist I think you clarified it for me.  `eventChannel` is for direct communication between sagas.  What I'm looking for is a general-purpose event bus, which is not the use case for `eventChannel`.  Thanks for the recommendation on mitt.

**Comment by Andarist** [comment]
Channels are in general for inter saga communications, eventChannel is kinda their special case - it can feed sagas from external data sources.

So this one is for listening to the outside world. Its one way communication to the saga from there
