### ISSUE TITLE
How to integrate Server Sent Events in eventChannel

### ISSUE THREAD

**Issue by BingxingXu** [redux-saga/redux-saga#868]
Here is my code:
```js
 export function subSSE(url) {
 // should I put const eventSrc outside here?
  const subs =  emitter => {
    const eventSrc = new EventSource(url);
     eventSrc.onmessage = (msg) => {
       return emmitter(msg);
     };
     eventSrc.onerror = () => {
       return emitter(END);
     };
    return eventSrc.close
  };
  return eventChannel(subs);
}

export function* sseSagas() {
  const token = yield select(makeSelectToken());
  const url = `${config.apiUrl}/messages/change-stream?access_token=${token}`;
  const chan = yield call(subSSE, url);
  while (true) {
    const msg = yield take(chan);
    console.log(msg);
  }
  // yield put('something to actions');
}

export function* homeSaga() {
  yield fork(sseSagas)
}

export default [
  homeSaga,
];
```
I got the errors like these
```
uncaught at homeSaga 
 at sseSagas 
 TypeError: __webpack_require__.i(...) is not a function
    at subSSE (eval at ./app/containers/Home/sagas.js
```
which is useless to debug.

I am pretty sure, there must be something wrong in my `eventChannel`. But I can't find out why. And all the eventChannel examples I can find are about `websocket` not `server sent event`.
Please help!!

**Comment by baldwmic** [comment]
@BingxingXu when it comes to using an [eventChannel](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/Channels.md#using-the-eventchannel-factory-to-connect-to-external-events), i'm using a pattern like so:

```
const createChannel = (externalEventSource) =>
  eventChannel(emitter) => {
    externalEventSource.eventHandler = (event) => {
      emitter({ event });
    });
    return () => {
      // cleanup
    });
  });

export function* subscribeChannel() {
  const externalEventSource = new ExternalEventSource(options);
  const channel = yield call(createChannel, externalEventSource);
  while (true) {
    const event = yield take(channel);
    // do something with event
  }
}
```
where `ExternalEventSource` is some instance that has event handlers that we can listen on and then emit events to our `subscribeChannel` saga. Good examples of this are [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) or [Notification](https://developer.mozilla.org/en-US/docs/Web/API/notification), but you can surely use [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) too.

**Comment by baldwmic** [comment]
looking at your provided code, and using the above paradigm, something like this might work:

``` 
export function subSSE(eventSrc) {
  const subs = emitter => {
     eventSrc.onmessage = (msg) => {
       emitter(msg);
     };
     eventSrc.onerror = () => {
       emitter(END);
     };
    return () => {
      eventSrc.close();
    }
  };
  return eventChannel(subs);
}

export function* sseSagas() {
  ...
  const eventSrc = new EventSource(url);
  const chan = yield call(subSSE, eventSrc);
  while (true) {
    const msg = yield take(chan);
    console.log(msg);
  }
}
```

you may have already solved this, as you seemed to be onto the solution. the key thing is to pass in an already instantiated instance of the `EventSource` class to the event channel creator (`subSSE`). Then, inside of the eventChannel, you can attach functions to event handlers (like `onmessage`, which will emit some event to the subscriber saga (`sseSagas`). It's at this point that the `take` sees an event emitted and should log it.

**Comment by Andarist** [comment]
This issue got a little bit stale, therefore Im closing it. Feel free to respond when you get to it.
