### ISSUE TITLE
Testing emitter from Channel

### ISSUE THREAD

**Issue by andresmijares** [redux-saga/redux-saga#880]
I'm trying to find a way to proper test this, I've been reading the docs and a lot of people seems to have a similar issue.

```javascript

function emitterFn (instance) {
  return eventChannel(emit => {
    const listener = instance.changes()
     .on('change', info => {
      emit(info)
    })
    return () => listener.cancel()
  })
}

function* something () {
 const emitter = yield call(emitterFn)
   try {
    while (true) {
       let payload = yield take(emitter)
       /* code omitted */
      }
   }
}

```

What is the proper way to get the pattern/channel for that emitter?

```
   let output = saga.next({}).value
   let expected = take({})
```

I doesn't read the proper channel, I've also tried to instanciate the channel and pass it as an argument and it didn't work

```javascript
     let channel = myChannelFunction()
     let output = saga.next(channel).value
     let expected = take(channel)
```

Any ideas?

**Comment by Andarist** [comment]
this should pretty much work
```javascript
const saga = something()
let actual = saga.next()
let expected = call(emitterFn)

const chan = channel()

actual = saga.next(chan).value
expected = take(chan)
```

**Comment by andresmijares** [comment]
@Andarist almost, the expectation is working good, however, for some reason the `emitter` here is undefined

``` javascript
function* something () {
 const emitter = yield call(emitterFn)
   try {
    while (true) {
       let payload = yield take(emitter) // this emitter is undefined on tests
       /* code omitted */
      }
   }
}
```

The code is fine and working perfectly, when I run it, it has a value.

Any idea?

**Comment by andresmijares** [comment]
@Andarist Almost, It still throws the take channelOrPattern is not valid, I checked a little and notice the emitter is undefined when running the tests, however, it works fine one the code:

```
function* something () {
 const emitter = yield call(emitterFn)
   try {
    while (true) {
       let payload = yield take(emitter) // <--- this is undefined
       /* code omitted */
      }
   }
}
```

That is causing the error when testing I guess, so I tried adding the emitter to the previous next() to make it available, but I guess the same result.

If it helps, my event channel is the same as [#631](https://github.com/redux-saga/redux-saga/issues/631)

**Comment by lourd** [comment]
You're trying to test the `emitterFn` function in your example, correct? If that is the case, you should do that outside of a saga. You'll need to fake the `instance` that you pass into `emitterFn`, something like [this `FakeEmitter` class](https://gist.github.com/lourd/005f957bb42db50d686ef068ed564cd2#file-emitterchannel-test-js-L39) that allows you to control when events are emitted and the `emit` function from the `eventChannel` is called. Looks like you're mock instance might be slightly more involved with properly mocking the behavior of the `changes` method, but pretty similar. 

When you go to test the channel's closing behavior, create a spy on the `cancel` method of the `instance` you passed it, and assert that its called. i.e.

```js
const cancel = jest.spyOn(emitter, 'cancel')
channel.close()
expect(cancel).toHaveBeenCalledWith(/*whatever arguments it should have been called with*/)
```

When you go to write a test for a saga that uses the channel creator function, you don't need to mess with channels, you just call `next` on the iterator with whatever you need. When you need to pass in a fake channel, you can do it with a couple of simple no-op functions.

Here's [an example](https://gist.github.com/lourd/15d7c9bcf859b4cafb53dccae02e03c6) from one of my project's tests (using [`redux-saga-test-plan` ](https://github.com/jfairbank/redux-saga-test-plan), which I heartily recommend)
