### ISSUE TITLE
Implementing Notification system: Interrupt/Resume/Dismiss

### ISSUE THREAD

**Issue by danscotton** [redux-saga/redux-saga#881]
I've been using `redux-saga` on my project for the last 6+ months or so and it's been fantastic. I can't for the life of me however get my head around a new feature I'm implementing: a simple notification system.

The feature is fairly standard:
- certain tasks within the app will show a success-like notification message to the user to inform them that their actions have been successful: *User 'Dan' was created successfully*, *Profile changes have been saved*, etc.
- the notifications should automatically hide after X seconds
  - unless the user hovers their mouse over the notification to interrupt the timeout
  - the timeout of X seconds is restarted once they move their mouse off the notification
- alternatively, the user can dismiss the notification manually by clicking the ✘
- or by clicking an action within the notification, e.g. *User 'Dan' was created successfully [View Profile]* which should also dismiss the notification
- many notifications can be displayed at once

I've got the following redux actions:

```es6
export const show = createAction(SHOW, p => ({ ...p, id: generateId() }));
export const hide = createAction(HIDE);
export const interrupt = createAction(INTERRUPT);
export const resume = createAction(RESUME);
export const dismiss = createAction(DISMISS);
```

where a notification is created with:

```es6
dispatch(show({ message: 'Profile changes have been saved' }));
```

and all of the other actions are invoked with the `id` of the notification (passed down to my react component and wired up):

```es6
const renderNotification = ({ id, message }) =>
    <Notification id={ id } message={ message}
        onInterrupt={ () => dispatch(interrupt(id)) }
        onResume={ () => dispatch(resume(id)) }
        onDismiss={ () => dispatch(dismiss(id)) } />
```

the reducer doesn't do much other than stick the message in a list on `SHOW`, and `omit` it from the list on `HIDE`.

---

I start off with a simple watcher and saga combo to hide the notification after X seconds:

```es6
export function* watchShow () {
    yield takeEvery(SHOW, showNotification);
}

function* showNotification ({ payload }) {
    yield call(delay, X);
    yield put(hide(payload));
}
```

This works great, and caters for multiple notifications just fine. However, I can't seem to get my head around the next bit of `INTERRUPT`/`RESUME` actions.

I've tried `fork`ing the `delay`/`put` actions so they don't block and then `cancel` the task following a `take(INTERRUPT)`:

```es6
function* showNotification ({ payload }) {
    const hideTask = yield fork(function* () {
        yield call(delay, X);
        yield put(hide(payload));
    });

    yield take(INTERRUPT);
    yield cancel(hideTask);
}
```

but as you might guess, all notifications are cancelled on a single `INTERRUPT`.

Following this, the code got messy real quick checking if `id`s were equal to other `id`s and I couldn't quite get it to all line up.

So, has anybody come across something like this before and have an idea on how to get it working?

Thanks in advance.

**Comment by Andarist** [comment]
smth like this should work 
```javascript
export function* watchShow () {
    yield takeEvery(SHOW, showNotification);
}

function* showNotification({ payload: { id: notificationId } }) {
    while (true) {
        const { hide, interrupted } = yield race({
            hide: call(delay, 5000),
            interrupted: take(ac => String(ac.type) === String(interrupt) && ac.payload.id === notificationId)
        })

        if (hide) {
            yield put(hide({ id: notificationId }))
            return
        }

        const { dismissed } = yield race({
            dismissed: take(ac => String(ac.type) === String(dismiss) && ac.payload.id === notificationId),
            resumed: take(ac => String(ac.type) === String(resume) && ac.payload.id === notificationId)
        })

        if (dismissed) {
            yield put(hide({ id: notificationId }))
            return
        }
    }
}
```

**Comment by danscotton** [comment]
Thanks @Andarist, that worked perfectly!

I ended up importing `_.isEqual` from `lodash/fp` to refactor the `take`s to be:

```es6
const { dismissed } = yield race({
    dismissed: take(isEqual(dismiss({ id }))),
    resumed: take(isEqual(resume({ id }))),
});
```

Appreciate the help 👍

**Comment by Andarist** [comment]
No problem, if you have any further questions, just ask.

**Comment by tuanhung9293** [comment]
What is resume function?
