### ISSUE TITLE
miss action

### ISSUE THREAD

**Issue by eruca** [redux-saga/redux-saga#882]
```javascript
function* watchRequest() {
    const chan = yield call(channel);
    for (let i = 0; i < 3; i++) {
        yield fork(handleRequest, chan);
    }

    while(true) {
        const { payload } = yield take(REQUEST);
        console.debug("watchRequest", payload); // will be mention soon
        yield put(chan, payload);
    }
}

function* handleRequest(chan) {
    while(true) {
        const payload = yield take(chan);
        console.debug("payload >>>>", payload);
        websocket.send(JSON.stringify(payload));
    }
}
```

one of my pageComponent's constructor
```javascript
props.dispatch(request(FETCH_CREATED_USERS, {account: props.account}))
props.dispatch(request(FETCH_DEPARTMENTS, {}))

function request(type, payload) {
    return {type:REQUEST, payload}
}
```

when the Page is Created, will diaptch action pull server information,
but in one case, the <code>props.dispatch(request(FETCH_DEPARTMENTS, {}))</code> will not success,
the debug("watchRequest",payload) not log the action,
I wander "take" will  take everyAction like takeEvery, but it cann't use it here.

```shell
saga.js:28 watchRequest Object {type: "LOGIN", payload: Object}
saga.js:28 watchRequest Object {type: "FETCH_CREATED_USERS", payload: Object}
saga.js:28 watchRequest Object {type: "FETCH_DEPARTMENTS", payload: Object}
saga.js:28 watchRequest Object {type: "AUTHREGISTER", payload: Object}
saga.js:28 watchRequest Object {type: "FETCH_CREATED_USERS", payload: Object}
```

**Comment by Andarist** [comment]
Could u rephrase the scenario? I cannot quite understand what is the exact problem.

**Comment by eruca** [comment]
```javascript
class Admin extend Component {
    constructor(props){
          ...
         props.dispatch(request(FETCH_CREATED_USERS, {account: props.account}))
         props.dispatch(request(FETCH_DEPARTMENTS, {}))
    }
}
```
the react-router from "/" to "/admin"

```shell
// console will print
saga.js:28 watchRequest Object {type: "FETCH_CREATED_USERS", payload: Object}
saga.js:28 watchRequest Object {type: "FETCH_DEPARTMENTS", payload: Object}
```

if the router from "/admin/register/1" to "/admin"
the Admin instance will construct, and should dispatch both actions.
but log will only receive the first action, the second is missed;

I have swap the position of the actions, first will receive and second not;

**Comment by visweshs** [comment]
The constructor isn't the right place to do [this.](https://facebook.github.io/react/docs/react-component.html#componentdidmount).

This is what I believe is happening:

1) Constructor starts constructing Admin with state S
2) Constructor dispatches action A
3) Reducer computes new state S1
4) Saga MW starts action A
5) S1 triggers rerender of Admin

Try dispatching the actions in componentDidMount().

**Comment by Andarist** [comment]
I believe that your constructor cannot just bail out and it needs to synchronously run till completion.

From my tests on the basically similar code that you have posted it works just fine. Are you sure you have posted complete snippet that is needed for reproduction?

Which version of the redux-saga are u using?

**Comment by eruca** [comment]
my version is 0.14.3, my code above I think is all about, I'm sorry not trace the issue anymore, I change my code to One dispatch not two, and it works well.

**Comment by Andarist** [comment]
Hm, if so then Im gonna close this. If you have any problems in the future, please just ask :)

**Comment by eruca** [comment]
thanks a lot
