### ISSUE TITLE
yielding takeEvery doesn't run multiple tasks in parallel

### ISSUE THREAD

**Issue by allenylzhou** [redux-saga/redux-saga#885]
from https://redux-saga.github.io/redux-saga/docs/basics/UsingSagaHelpers.html
`// use them in parallel
export default function* rootSaga() {
  yield takeEvery('FETCH_USERS', fetchUsers)
  yield takeEvery('CREATE_USER', createUser)
}`

This doesn't actually use them in parallel, it will never take the CREATE_USER action. Am I incorrect or is the documentation wrong?

**Comment by Andarist** [comment]
What version of redux-saga do u use?

**Comment by allenylzhou** [comment]
^0.11.0

**Comment by Andarist** [comment]
The change allowing this was introduced in `v0.12`. Please read the [release note](https://github.com/redux-saga/redux-saga/releases/tag/v0.12.0)
