### ISSUE TITLE
`Max call stack exceeded` / `Out of stack space` when using lots of sagas

### ISSUE THREAD

**Issue by wilsaj** [redux-saga/redux-saga#888]
We have an app that is making heavy use of sagas. With versions `0.13.0` and up we sometimes run into max call stack errors due to the recursive scheduler and having too many things on the queue. The exact error depends on the browser and circumstance (for example: "Maximum call stack size exceeded" or "Out of stack space") . There is a PR to fix this and a lot of relevant discussion in that PR: https://github.com/redux-saga/redux-saga/pull/790

Our workaround so far has been to revert and pin to `redux-saga@0.12.1`

Opening this as a separate issue here because:
- It will be easier to find when searching for the error. I happened to stumble upon the PR via google search after not finding any GH issues about it.
- This issue can be a place for discussion about things like workarounds that are unrelated to that PR itself
- If for some reason that PR doesn't work out then the issue is still valid

**Comment by Andarist** [comment]
[This](https://github.com/redux-saga/redux-saga/pull/790#issuecomment-287302932) is PR attempting to solve this issue, however author abandoned it due to lack of time. Would you be willing to give it a shot? Not much there to finish the work. Would be happy to merge it in asap when its finished.

**Comment by wilsaj** [comment]
Hi @Andarist - I've got some time to work on this now. Logistically, how should that work - open a new PR?

**Comment by Andarist** [comment]
@wilsaj I think the best way is to:
```sh
git remote add pbadenski https://github.com/pbadenski/redux-saga.git
git fetch pbadenski
git checkout pbadenski/master
git checkout -b BRANCH_NAME
```
and start from there

**Comment by hendywijaya** [comment]
Hi Guys,

I'm still getting this issue at `0.15.6`

When utilizing a lot of Sagas, in high traffic / concurrency, my app will break:

```
redux-saga error: uncaught at fetchCategoryAPI
RangeError: Maximum call stack size exceeded
    at /var/ruparupa/frontend/node_modules/redux-saga/lib/internal/middleware.js:68:23
    at /var/ruparupa/frontend/node_modules/redux-saga/lib/internal/middleware.js:72:22
```

It doesn't always break at the same Sagas 

Should I increase my OS limit on the stack size ? I doubt that will answer the issue.

it seems to point to this part of the redux-saga code

```
return function (next) {
      return function (action) {
        if (sagaMonitor && sagaMonitor.actionDispatched) {
          sagaMonitor.actionDispatched(action);
        }
        var result = next(action); // hit reducers --> recursion on line 72
        sagaEmitter.emit(action);
        return result;
      };
    };
```
Could this be another issue on the recursion ? @wilsaj @Andarist 

Many thanks in advanced for the responses
