### ISSUE TITLE
does the middleware offers any buffer?

### ISSUE THREAD

**Issue by tugorez** [redux-saga/redux-saga#891]
```javascript
function* taker() {
    for (;;) {
        const { payload } = yield take('SOME_RANDOM_TYPE');
        yield call(delay, 5000);
        console.log('receiceved: ', payload);
    }
}

function* sender() {
    const action = { type: 'SOME_RANDOM_TYPE', payload: 'some_random_payload' };
    yield put(action);
    yield put(action);
    yield put(action);
    yield put(action);
    yield put(action);
}
```
in this case the pending actions (appended by the sender) will be dropped? or does "take" implements some buffer in which case "taker" is guaranteed to execute all actions.

**Comment by visweshs** [comment]
I think you're looking for [takeLatest](https://redux-saga.github.io/redux-saga/docs/api/index.html#takelatestpattern-saga-args).

```
function* taker(action) {
   try { 
       const response =  yield call(API.makeCall, action.payload)
       yield put(actions.result(response))
   } catch (e) { 
       yield put(actions.error(e))
   }
}

function *sender() {
    yield takeLatest('SOME_RANDOM_TYPE', taker)
}
```

**Comment by Andarist** [comment]
@tugorez this has no buffer internally, but internally we have a scheduler implemented for even more complex scenarios and it is guaranteed that all of those will fire. The only problem which sometimes appear is the order and timing of those, but I would say its really marginal - you have to have complex sagas implemented and rely on timing (which can be avoided with proper code planning).

**Comment by tugorez** [comment]
Hi guys, thank you very much for your responses. 
I'm currently developing a chat app and I need to be very carefully for api calls because the order of creation matters. 

what do you think about this approach
```javascript
import uuid from 'uuid/v4'; 

function* sender1() {
   for (;;) {
       yield take('SENDER');
       const pid = uuid();
       yield put({ type: 'RECEIVER',  payload: {...payload, pid } });
       yield take(pid);
       //... do something else
   }
}

function* sender2() {
   for (;;) {
       yield take('SENDER');
       const pid = uuid();
       yield put({ type: 'RECEIVER',  payload: {...payload, pid } });
       yield take(pid);
       //... do something else
   }
}

function* receiver() {
   for (;;) {
      const { payload } = take('RECEIVER');
      const { pid } = payload;
      try {
          const result = yield call(api.login, payload);
          yield put({ type: pid, payload: { result  } });
       } catch(error) {
          yield put({ type: pid, payload: { error } });
       }
    }
}

export default function*() {
  yield [call(receiver), call(sender1), call(sender2)];
}
```

**Comment by Andarist** [comment]
By `  yield [call(receiver), call(sender1), call(sender2)];` you start them in parallel. If `SENDER1` and `SENDER2` happen close to each other then your `receiver` might be blocked on `const result = yield call(api.login, payload);` so the second one will get lost and stuck forever.

You can do something like:
```javascript
const chan = yield actionChannel('RECEIVER', buffers.expanding())
for (;;) {
      const { payload } = take(chan);
      // ...
}
```
in that way no request will get lost

**Comment by tugorez** [comment]
Thank you for your response Andarist.
What you mean by happen to close each other? 
receiver1 and receiver2 are supposed to wait for an action, do something and then wait for the same action again

**Comment by Andarist** [comment]
Yes, but they both do `yield put({ type: 'RECEIVER' })` which is consumed by the same `receiver` at this point `const { payload } = take('RECEIVER');`. So if senders both put `RECEIVER` there is only 1 `receiver` to handle it and it might not be listening at the moment for new action.

Alternatively you could wrap it with `takeEvery`, so it becomes:
```javascript
function* receiver({ payload }) {
    const { payload } = take('RECEIVER');
    const { pid } = payload;
    try {
        const result = yield call(api.login, payload);
        yield put({ type: pid, payload: { result  } });
     } catch(error) {
        yield put({ type: pid, payload: { error } });
     }
}
```

and use it like this:
`yield [takeEvery(receiver), call(sender1), call(sender2)];`

**Comment by tugorez** [comment]
Excellent answer Andarist :) , I think I will use the actionChannel in order to warranty the order creation in the server.

**Comment by tugorez** [comment]
@Andarist is there any difference between
```javascript
const chan = yield actionChannel('RECEIVER', buffers.expanding());
```
and 

```javascript
const chan = yield actionChannel('RECEIVER');
```

**Comment by Andarist** [comment]
latter is using the [default buffer](https://github.com/redux-saga/redux-saga/blob/43d515cacefc5361d44140de356c9a9c8b3b5801/src/internal/proc.js#L622)
