### ISSUE TITLE
does the middleware pause tasks for nextAnimationFrame?

### ISSUE THREAD

**Issue by visweshs** [redux-saga/redux-saga#893]
I apologize if I am not following conventions here - new to the community.
I ran into this github [repository](https://github.com/corbt/next-frame), and I am thinking of using it in the following manner:

```
function* main() {
  while (yield take(START_BACKGROUND_SYNC) ) {
    const bgSyncTask = yield fork(bgSync)
    yield race({
      nextFrame: call(nextFrame),
      cancel: take(CANCEL_TASK)
    })  
  }
}
```
Is this necessary in react-native for 'true' non-blocking async workflows? 
Or is there something already present in the middleware that handles this?

**Comment by Andarist** [comment]
It really depends on what kind of stuff you are trying to achieve, but this should generally work. It depends though what you would like to happen for `nextFrame` and `cancel` cases.

**Comment by visweshs** [comment]
I would like to pause all currently running sagas whenever a next animation frame is requested, and resume all sagas after the frame is delivered.

**Comment by Andarist** [comment]
`JSON.stringify` has literally nothing to do with DOM. 

Anyway - `redux-saga` is an asynchronous tool and it shouldn't block your main thread too much. It is not literally possible to 'pause' sagas when 'next animation frame is requested' in JavaScript, this is not how the language works. If you do too much work in your code and your UI starts lagging, you need to figure out how to chunk ur work in some async way. It has nothing to do with redux-saga per se, but is a general problem when programming in JavaScript.

This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
