### ISSUE TITLE
Webpack bundles both redux-saga/es and redux-saga/lib

### ISSUE THREAD

**Issue by Ephys** [redux-saga/redux-saga#894]
The current way of accessing redux-saga's effects is by importing `redux-saga/effects.js`, but that file uses `redux-saga/lib`. This causes webpack to bundle both `redux-saga/lib` and `redux-saga/es`.

I didn't see anything in the documentation mentioning this, so I'm assuming it's a bug?

My current workaround is to add the following to my webpack configuration, but it feels unstable

```javascript
{
  resolve: {
    alias: {
      'redux-saga/effects.js': 'redux-saga/es/effects.js'
      'redux-saga/util.js': 'redux-saga/es/util.js'
    }
  }
}
```

Thank you for your help :)

**Comment by Andarist** [comment]
Whats the undesired effect of the current situation? Duplicated dependencies in the dist file?

From what I understand your alias fix is allowing webpack2 to perform tree shaking and all by using es modules, right?

**Comment by Ephys** [comment]
If by current situation you mean without the alias fix, the undesired effect is having two versions of redux-saga in the same bundle (the contents of `/lib` and `/es`).

Here's the contents of my bundle without the alias:
![screen shot 2017-04-05 at 14 06 00](https://cloud.githubusercontent.com/assets/1280915/24704705/110e11b4-1a09-11e7-8231-090f00dc6326.png)

And wWith the alias:
![screen shot 2017-04-05 at 14 07 37](https://cloud.githubusercontent.com/assets/1280915/24704761/403aef16-1a09-11e7-8edb-2ea644602064.png)

So while the fix does indeed allow webpack2 to perform tree shaking, the bigger benefit is not having two different redux-sagas.

**Comment by Andarist** [comment]
Would you like to collaborate on straightening things? Im not too proficient with bundler configurations, would be cool to work on this with somebody more experienced on the matter. We could schedule some gitter/reactiflux/other_channel time

**Comment by Ephys** [comment]
Actually if you want I can just make a PR with a fix that should make rollup/webpack2 always bundle /es and node/browserify/others always use /lib :)

It's a really minor change https://github.com/Ephys/redux-saga/commit/1ab5bb537279bfb3f1c4e3ecdd065f770d21bccc

Don't worry it doesn't break anything :)

<img width="491" alt="screen shot 2017-04-05 at 17 11 20" src="https://cloud.githubusercontent.com/assets/1280915/24712366/f7b9ee6c-1a22-11e7-80ed-8918fac2c9c7.png">

**Comment by Andarist** [comment]
LOL! I was searching and asking around for quite some time how to point `/utils` and `/effects` to the right directories for both types of builds

Had no idea (and could find this info) that such simple `package.json`s fixes this....

Happy to accept a PR from you. Apart from this I'm strongly considering switching the bundler to rollup, but that might be another PR or I can make it later, just dont know when.

Bless you!

**Comment by aikoven** [comment]
This is a really cool trick, thanks for sharing it, @Ephys!
