### ISSUE TITLE
how to abort request which is sending a big file

### ISSUE THREAD

**Issue by budarin** [redux-saga/redux-saga#897]
Imagine we have an interface for uploading to a server some files
we should create saga which is monitoring action with file in payload and send a file with the xhr request.
sending file is a simple task, but aborting any of sending request become a problem

how to abort any particular request which is sending a file to a server in saga?

**Comment by Andarist** [comment]
How do you make your requests? Cause the answer depends on that :)

**Comment by budarin** [comment]
I'm talking not about canceling a fetch task but about abort real http request

**Comment by Andarist** [comment]
As I said - it depends on how do u do your requests. What kind of API/library are u using?

**Comment by baldwmic** [comment]
@budarin if you're using [`XMLHttpRequest`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest), you could use an [eventChannel](https://github.com/redux-saga/redux-saga/blob/master/docs/advanced/Channels.md#using-the-eventchannel-factory-to-connect-to-external-events) and [abort](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort) the XHR from there if the large file upload is taking too long.

Like @Andarist said though, it really depends on how you are implementing the file upload. If you are not using [Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) or [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest), can you explain what you mean by a "real" HTTP request? After all, any implementation of the protocol HTTP will send a request

**Comment by Andarist** [comment]
Its also worth mentioning that `fetch`s are non-cancellable

**Comment by budarin** [comment]
Hi !

I use to superagent as HTTP request library
So, as I've understood, I have to save the instance returned by call superagent instance and than manually call abort/cancel method on it?

**Comment by Andarist** [comment]
from what I understand its API you can make some wrapper and use it like this
```
function* callAPI(url) {
	const req = request.get(url)
	req[CANCEL] = () => req.abort()
	const result = yield req
	return result
}

function* saga() {
	const requestTask = yield fork(callAPI, 'http://...')

	// ... 

	yield cancel(requestTask)
}
```

**Comment by budarin** [comment]
Thanks for the sample.

But I need to cancel running request not from within the same saga - it must be another saga which look for an action { CANCEL_UPLOADING_FILE, id }

so I need to store result of the request in a store by id ?

**Comment by Andarist** [comment]
Just pass the reference to the request task there so it could be canceled, storing in the store is preventing u from serialization of the store

You could have also use `setContext`/`getContext` effects.

**Comment by florimm** [comment]
How does this work with auto cancel when used with takeLatest (or how should i do it)?

**Comment by Andarist** [comment]
if you use [such solution](https://github.com/redux-saga/redux-saga/issues/897#issuecomment-301132742) as above the cancelation process will know how to cancel the forked (internally by takeLatest) task

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
