### ISSUE TITLE
Commit d3139ef now getting error

### ISSUE THREAD

**Issue by realseanp** [redux-saga/redux-saga#898]
Regarding d3139ef

I saw package.json was updated 3 hours ago and I just started getting the error:

`Uncaught TypeError: (0 , _reduxSaga2.default) is not a function`

I am using webpack. 

```
import createSagaMiddleware from 'redux-saga';
const sagaMiddleware = createSagaMiddleware();
```

**Comment by Andarist** [comment]
Thats weird, ive tested it myself. Could u link to the project which
results in error? Which webpack do u use?

**Comment by realseanp** [comment]
@Andarist just confirmed that the latest version of webpack fixes the issue. I am working on a branch that is using webpack 2.1.0-beta.25. Seems like it doesn't play nicely together.

**Comment by Andarist** [comment]
Thanks for quick reply, you get me scared for a moment! ;)

**Comment by gabrielhpugliese** [comment]
I am having this issue too. I upgraded from 0.14.3 to 0.14.6 today.
Using webpack@2.2.1

**Comment by gabrielhpugliese** [comment]
Just tried to update webpack (2.3.3) but got the problem. Any ideas how to debug this?

**Comment by Andarist** [comment]
Could u share reproduced situation on some repository ready for download and debug?

**Comment by gabrielhpugliese** [comment]
Sorry, I am using the beta indirectly via this package: https://github.com/JeffreyWay/laravel-elixir-webpack-official
And webpack was also in the package.json so I was confused.

**Comment by gabrielhpugliese** [comment]
Forgot to say: that package is also using webpack beta. When getting out of beta it works.
