### ISSUE TITLE
How to test take effect by pattern function

### ISSUE THREAD

**Issue by mysticmana** [redux-saga/redux-saga#901]
I have this function watch fetch request by function
```
export function* watchFetchRequest() {
  while(true) {
    const action = yield take(action =>  /^FETCH_/.test(action.type))
    console.log('watchFetchRequest ', action)
  }
}
```
How can I unit test it? Below is my test with ava, but it will throw error
```
test('watchFetchRequest', t => {
  const generator = watchFetchRequest();
  t.deepEqual(
    generator.next().value,
    take(action =>  /^FETCH_/.test(action.type))
  );
})
```

**Comment by Andarist** [comment]
Well, each instance of the function holds different reference, you cannot compare even the simplest functions by any form of equality, unless they are truly the same (same reference). That's how it works in javascript and many other languages.

You need to extract this predicate function so your test can import it

**Comment by mysticmana** [comment]
OK, based from @Andarist comment, I can extract the predicate function to `matchFetch`, then use it in both saga and test code. Thanks @Andarist 
```
export function matchFetch(action) {
  return /^FETCH_/.test(action.type);
}

export function* watchFetchRequest() {
  while(true) {
    const action = yield take(matchFetch)
    console.log('watchFetchRequest ', action)
  }
}
```
Test code
```
import { watchFetchRequest, matchFetch } from '../saga/api';
test('watchFetchRequest', t => {
  const generator = watchFetchRequest();
  t.deepEqual(
    generator.next().value,
    take(matchFetch)
  );
})
```
