### ISSUE TITLE
takeEvery with TypeScript: type must have a '[Symbol.iterator]()' method that returns an iterator

### ISSUE THREAD

**Issue by tamethecomplex** [redux-saga/redux-saga#902]
Hi all,

I have been using Redux Saga with ES6 for a while and am looking to switch to TypeScript.  I get the below error in bold when trying to use the takeEvery effect.  I see that typescript expects the return value from watchSendMessageToSnackbar() to be IterableIterator<any>.  Any ideas on how to fix this?

```

import { put, fork, takeEvery } from 'redux-saga/effects'
import { OPEN_SNACKBAR, CLOSE_SNACKBAR, SEND_MESSAGE_TO_SNACKBAR } from '../constants/ActionTypes'
import { sleep } from './effect_utils/sleep'

function* writeToSnackbar (action) {
  yield put({ type: OPEN_SNACKBAR, payload: { snackbarMessage: action.payload.message } })
  yield sleep(action.payload.msDelay)
  yield put({ type: CLOSE_SNACKBAR })
}

function* watchSendMessageToSnackbar () {
  yield * takeEvery(SEND_MESSAGE_TO_SNACKBAR, writeToSnackbar)  **//Results in TS error "Type must have a '[Symbol.iterator]()' method that returns an iterator**
}

export default function* root () {
  yield [
    fork(watchSendMessageToSnackbar)
  ]
}
```

**Comment by Andarist** [comment]
Im not a TS guy, but have you tried using `yield takeEvery(SEND_MESSAGE_TO_SNACKBAR, writeToSnackbar)` instead of `yield*` there?

**Comment by tamethecomplex** [comment]
Thanks @Andarist, this did in fact resolve the compilation error.  I'm running into other issues related to the fact that Webpack won't compile generators down to es5, and of course to use Redux Saga I need generators.  But regardless, I'm going to close this issue for now given it appears to have solved the types problem.  Thanks!

**Comment by Andarist** [comment]
Webpack per se is not for compilation/transpilation, you need to plug in
babel with appropriate transforms (regenerator-runtime in this situation)
and that will transpile ur generators just fine. Hope it helps

**Comment by tamethecomplex** [comment]
Sorry meant to say that typescript (version 2.2 in my case) won't transpile generators down to ES5... it throws an error and forces you to change your target to ES6.  But I have seen cases where people put typescript in a chain before babel, which takes the ES6 output down to ES5 finally.  I might give that a try.
