### ISSUE TITLE
Question: batching api calls in chunks

### ISSUE THREAD

**Issue by SpencerCDixon** [redux-saga/redux-saga#906]
Scenario:

Let's say I have to make 100 API calls to update some resources.  I'd like to do them 5-10 at a time and once the first chunk finishes I then start the next chunk.  I feel like this is a great use case for channels but I'm not entirely sure how to do it properly.  Anyone have any thoughts on the most 'idiomatic' way to achieve this goal with redux saga?

Some psuedo code:
```js
function* doLotsOfCallsSaga() {
  const entities = yield select(getEntities);

  // take first 5 entities and make API calls in parallel
  // once all 5 are done, take the next 5, etc.
}

function* rootWatcher() {
  yield fork(takeEvery, COMMIT_EXPENSIVE_API_CALLS, doLotsOfCallsSaga);
}
```

**Comment by Andarist** [comment]
nothing easier for the redux-saga!
```javascript
function* rootWatcher() {
	const buffer = buffers.expanding(100)
	const chan = yield actionChannel(API_CALL, buffer)

	while (true) {
		const actions = []

		for (let i = 0; i < 5; i++) {
			const action = yield take(chan)
			actions.push(action)

			if (buffer.isEmpty()) {
				break
			}
		}

		yield actions.map(action => call(api, action))
	}
}
```

Ive changed the code (requirements?) a little bit to show the idea and how I would try to tackle the problem first. In the code you have posted I would just slice entities to get 5, yield them mapped to calls and continue until I do them all. But another `COMMIT_EXPENSIVE_API_CALLS` could come in during the process and I dont know how ur state changes so I cannot predict if thats a problem or not

**Comment by SpencerCDixon** [comment]
Excellent, thank you for the direction!  I will tackle this tomorrow and see how it goes :-) 👍
