### ISSUE TITLE
Error on NPM Install

### ISSUE THREAD

**Issue by schraj** [redux-saga/redux-saga#908]
[2017-04-14T15_22_21_333Z-debug.txt](https://github.com/redux-saga/redux-saga/files/922398/2017-04-14T15_22_21_333Z-debug.txt)
I'm getting the following error when running npm install after the initial fork and clone of the repo. 
I'm on: (windows 10, node: v7.8, npm: v4.5)

Based on the following warning, it looks like it is trying the "Prepublish" process as well as the npm package install and this is causing the failure.  However, the latest version of npm is 4.5 so, this message is confusing.  I'm not able to find a beta version of npm@5 to see if that resolves the issue. 
`npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)`

Error:
PS C:\gitOpenSource\redux-saga> npm install
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> redux-saga@0.14.3 prepublish C:\gitOpenSource\redux-saga
> npm run check && npm run compile && npm run build

> redux-saga@0.14.3 check C:\gitOpenSource\redux-saga
> npm run lint && npm run test

> redux-saga@0.14.3 lint C:\gitOpenSource\redux-saga
> eslint src

npm ERR!     cross-env BABEL_ENV=cjs babel-node test/index.js | tap-spec
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux-saga
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\gitOpenSource\redux-saga\npm-debug.log

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\gitOpenSource\\redux-saga\\node_modules\\npm\\bin\\npm-cli.js" "ru
n" "check"
npm ERR! node v7.8.0
npm ERR! npm  v2.14.8
npm ERR! code ELIFECYCLE
npm ERR! redux-saga@0.14.3 check: `npm run lint && npm run test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-saga@0.14.3 check script 'npm run lint && npm run test'.
npm ERR! This is most likely a problem with the redux-saga package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && npm run test
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux-saga
npm ERR! There is likely additional logging output above.

npm ERR!     cross-env BABEL_ENV=cjs babel-node test/index.js | tap-spec
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux-saga
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\gitOpenSource\redux-saga\npm-debug.log

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\gitOpenSource\\redux-saga\\node_modules\\npm\\bin\\npm-cli.js" "ru
n" "check"
npm ERR! node v7.8.0
npm ERR! npm  v2.14.8
npm ERR! code ELIFECYCLE
npm ERR! redux-saga@0.14.3 check: `npm run lint && npm run test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-saga@0.14.3 check script 'npm run lint && npm run test'.
npm ERR! This is most likely a problem with the redux-saga package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run lint && npm run test
npm ERR! You can get their info via:
npm ERR!     npm owner ls redux-saga
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\gitOpenSource\redux-saga\npm-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"}
(current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redux-saga@0.14.3 prepublish: `npm run check && npm run compile && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-saga@0.14.3 prepublish script 'npm run check && npm run compile && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-saga package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run check && npm run compile && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-saga
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-saga
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jeremy Schrader\AppData\Roaming\npm-cache\_logs\2017-04-14T15_22_21_333Z-debug.log

**Comment by Andarist** [comment]
I've just checked how it is behaving on the node + npm versions you have and everything is fine, although I've checked in on Mac. I've noticed though that in the `npm-debug.log` which you have posted it says `npm ERR! npm v2.14.8`, could u verify what version of npm is running the install process?

`prepublish` is run with each `install`, but only after it completes, so there should be no conflict in the ordering of those. Could u verify that you have `node_modules` created with packages in it despite the error? If yes then the next step would be to verify which task is having the trouble - try to run manually `npm run lint` and `npm run test`. 

Thanks for the report, cannot reproduce so far, but I hope we'll get together to the bottom of this.

**Comment by schraj** [comment]
Thanks for the quick response.

When doing the following:
1) a clean clone of the repo
2) then running NPM Install
3) the node-modules directory is created and appears to be complete
4) the "npm" package for "npm" itself is installed in the local node-modules directory and its version is 2.14.8.
   a)  the following warning appears in the install process as the node modules are being installed
`npm WARN prefer global npm@2.14.8 should be installed with -g`
   b) this local "npm" module is being required by "gitbook-cli" 

I tried upgrading that local version to the current version but I still get the same failure(Below).

C:\gitOpenSource\redux-saga\test\middleware.js:5
var _tape2 = babelHelpers.interopRequireDefault(_tape);
             ^
ReferenceError: babelHelpers is not defined
    at Object.<anonymous> (C:\gitOpenSource\redux-saga\test\middleware.js:5:14)
    at Module._compile (module.js:571:32)
    at loader (C:\gitOpenSource\redux-saga\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\gitOpenSource\redux-saga\node_modules\babel-regis
ter\lib\node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/gitOpenSource/redux-saga/test/index.js:2:1)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\gitOpenSource\\redux-saga\\node_modules\\npm\\bin\\npm-cli.
js" "run" "test"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redux-saga@0.14.3 test: `cross-env BABEL_ENV=cjs babel-node test/index.js | tap-spec`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-saga@0.14.3 test script 'cross-env BABEL_ENV=cjs babel-node test/index.js | tap-spec'.

Running lint alone is is successful:
`npm run lint` 

Running test alone is not and gives the error above as well:
`npm run test`

**Comment by Andarist** [comment]
Could u try editing the `test/index.js` and add there in the topline such a line - `import 'babel/external-helpers'` ?

**Comment by schraj** [comment]
That did it.  Thanks for taking the time to help with this!

**Comment by ahmed3eraqi** [comment]
![image](https://user-images.githubusercontent.com/9159804/29766483-2b18f860-8bdf-11e7-84a7-2637dfe0dd25.png)

**Comment by Andarist** [comment]
@ahmed3eraqi we need more information about ur configuration and what step of the installation has failed, etc

**Comment by ahmed3eraqi** [comment]
when i instal  angular new project

ng new appname
