### ISSUE TITLE
Redux saga waiting fork effect until it's done

### ISSUE THREAD

**Issue by guswnsxodlf** [redux-saga/redux-saga#912]
I'm reading react-saga doc (https://redux-saga.github.io/redux-saga/docs/advanced/ForkModel.html), and **have some question.**
In the middle of the doc, they say **"Say for example, the delay of 1000 milliseconds elapsed and the 2 tasks hasn't yet finished, then fetchAll will still wait for all forked tasks to finish before terminating the whole task."**. But how can 'fetchAll' detects whether the tasks end?

**Comment by Andarist** [comment]
In this particular scenario `fetchAll` yields an array - that is a parallel effect. So the redux-saga runtime knows that it should immediately start all those 3 effects in the array in parallel and it will only continue to run `fetchAll` once each of them completes.

Under the hood it just stores counter of completed effects and increment it with each completion. Once it equals `arr.length` it can resume the `fetchAll`. You can see it [here](https://github.com/redux-saga/redux-saga/blob/83ee6d821e41c34748efe4d6c4562589babe9080/src/internal/proc.js#L535-L540) in the code

**Comment by guswnsxodlf** [comment]
Thanks :)
Is it same process on the 'fork fork delay(call)' example, not only [call, call, call]?

**Comment by Andarist** [comment]
Could u post exact code in question? Wouldnt like to misinform u because of
wrong misinterpretation or smth.

**Comment by guswnsxodlf** [comment]
Ok Thanks!

```
import { delay } from 'redux-saga'
import { fork, call, put } from 'redux-saga/effects'
import api from './somewhere/api' // app specific
import { receiveData } from './somewhere/actions' // app specific

function* fetchAll() {
  const task1 = yield fork(fetchResource, 'users')
  const task2 = yield fork(fetchResource, 'comments')
  yield call(delay, 1000)
}

function* fetchResource(resource) {
  const {data} = yield call(api.fetch, resource)
  yield put(receiveData(data))
}

function* main() {
  yield call(fetchAll)
}
```

I'm curious about how 'fetchAll' can detects whether the tasks end..

**Comment by neurosnap** [comment]
`main` will wait for the `call(delay, 1000)` before finishing.

**Comment by guswnsxodlf** [comment]
But fetchAll didn't yield before 2 tasks end even if delay ends.

**Comment by Andarist** [comment]
`fetchAll` will:
- start a `fetchResource, 'users'` task
- start a `fetchResource, 'comments'` task
- wait 1000 due to `call(delay, 1000)` ofc

But even after the mentioned delay it may not resolve right away after it finishes. All forked tasks need to get resolved as well. It's realised internally by a [`forkQueue`](https://github.com/redux-saga/redux-saga/blob/83ee6d821e41c34748efe4d6c4562589babe9080/src/internal/proc.js#L29-L43) - each forked task is geting attached to its parent.

**Comment by guswnsxodlf** [comment]
Ahha! Thank you so much :)

**Comment by Andarist** [comment]
Gonna close this, if you have any further questions - dont hesitate and ask :)
