### ISSUE TITLE
General saga library

### ISSUE THREAD

**Issue by ksjun** [redux-saga/redux-saga#913]
I think Redux-Saga's generator functions and middleware for async are much better than ES7 async-await.

My non-react app ( MPEG-DASH library like dash.js ) has many long-run ES7 await functions. To cancel them, a promise must be passed as a parameter, and Promise.race() is used everywhere to check canceling. And custom message queues are used for communication between async functions. 

But If saga part is separated from Redux-Saga, it will be used many places
like web services and game loops.

**Comment by Andarist** [comment]
**redux-saga** stays quite agnostic from the use case. We provide the external API for integrations other than `redux` - https://redux-saga.github.io/redux-saga/docs/api/index.html#external-api .

Is this what you were looking for? Or you would like to see even bigger seperation/modularization?

**Comment by baldwmic** [comment]
@ksjun is the [`runSaga`](https://github.com/redux-saga/redux-saga/tree/master/docs/api#runsagaiterator-options) enough to run sagas outside of Redux for your app? did you have something else in mind?

**Comment by blocka** [comment]
I'm successfully using redux-saga in a vue + vuex app.

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
