### ISSUE TITLE
How to test the END action

### ISSUE THREAD

**Issue by schuma7** [redux-saga/redux-saga#914]
I am looking for a way to test the following watcher:

```
function* watchTest() {
  let action = yield take(TEST_ACTION);
  while (action !== END) {
    yield fork(test);
    action = yield take(TEST_ACTION);
  }
}
```

I'd like to verify that TEST_ACTION keeps getting processed and the 'test' generator is forked until END is dispatched. Is there currently a way to do this?

**Comment by Andarist** [comment]
U wont be able to receive END when using take, for that u need to use take.maybe .

But anyway redux-saga is going to end ur generator when END is dispatched if its blocked on regular take. There is no need to test this behaviour on application level. Its geting tested on library level already.

**Comment by schuma7** [comment]
Ok, that answers my question, thank you!
