### ISSUE TITLE
takeLatest not triggering under specific condition

### ISSUE THREAD

**Issue by forgo** [redux-saga/redux-saga#915]
I have a root saga function that looks like this:

```javascript
export default function * StarterSagas() {
    yield [
        takeLatest(BreadcrumbActions.ADD_BREADCRUMB, switchView),
        // ...
    ]]
}
```
There are various places in the app which could trigger the ADD_BREADCRUMB action, and those seem to work, in general, with the exception of when I am triggering that action from a map marker.

I am using [Leaflet](http://leafletjs.com/) with GeoJSON markers. I have created markers and trigger click events like this:

``` javascript
const geoJSON = L.geoJSON(geoJSONData, {
    onEachFeature: (feature, layer) => {
        layer.on({
            click: (e) => {
                if(feature.properties.name === "Event") {
                    return addBreadcrumb("Event "+feature.properties.id, BreadcrumbConstants.views.eventDetail, clickEventDetail, [feature.properties.id]);
                }
                else if(feature.properties.name === "Picture") {
                    return addBreadcrumb("Picture "+feature.properties.id, BreadcrumbConstants.views.pictureDetail, clickPictureDetail, [feature.properties.id]);
                }
            }
        });
    }
}).addTo(this.map);
```

As you can see, I am calling the "addBreadcrumb" action creator which I know is successfully triggering the ADD_BREADCRUMB action in my react/redux app.

So if the ADD_BREADCRUMB and corresponding reducer switch are being executed, is there any reason why the saga would NOT?

The only difference is that the action is triggered in a nested callback.

If I can confirm the ADD_BREADCRUMB action is being executed, why would redux-saga's "takeLatest" ignore this action in this particular case of clicking on a map and not elsewhere?

I have also tried to use "takeEvery", but that has no effect on the outcome.

Any help is greatly appreciated!

**Comment by forgo** [comment]
Something interesting to note that I just discovered:

If I simply do *nothing* in my reducer by a `return state`, the saga gets executed. If I modify the state in the reducer action switch and return that state, then the sage no longer gets executed...

Any ideas why that would happen?

**Comment by forgo** [comment]
I found a workaround, but I'm still not sure why it wasn't working to begin with (hopefully somebody out there might have an idea).

What I ended up doing was, instead of passing the "addBreadcrumb" action down from a higher level parent component (e.g. - <Parent action={addBreadcrumbs}> <Map action={addBreadcrumb} /> </Parent>), I connected the lowest level <Map> component to a *NEW* action (via mapDispatchToProps) called "addBreadcrumbFromMap".

From that new action reducer for "addBreadcrumbFromMap", I intermediately stored the breadcrumb the map should be adding in my reducer's state -- as opposed to re-using the same "switchView" saga to unpack the "last" breadcrumb on my stack (which I thought should always correspond to the last pushed breadcrumb item (apparently not?).

So now I have a new saga "switchViewFromMap" triggered by the new action which deconstructs my breadcrumb, applies the action the same way as "switchView" stored in the breadcrumb, except now I am additionally calling `yield put` at the end to trigger the "addBreadcrumb" action and, consequently, the normal "switchView" saga.

To me, there seems to be an unnecessary duplication of logic here...

If anybody has insight into how I can reduce this into a single saga and action again, I'm all ears.

**Comment by Andarist** [comment]
hey, the missing piece to understand the whole picture for me is how in this `onEachFeature` from the first post `addBreadcrumb` is geting dispatched, cause it isnt used in the mentioned code. Also your middleware chain setup might be crucial here.

Would be great if you could reproduce your issue one something like webpackbin.

**Comment by baldwmic** [comment]
looking at the root saga, i haven't seen this syntax before:

```
export default function * StarterSagas() {
    yield [
        takeLatest(BreadcrumbActions.ADD_BREADCRUMB, switchView),
        // Question: what other code is here? another "takeLatest"?
    ]] // Question: why is there a second closing bracket here with no matching one above?
}
```
@forgo why are you yielding to an array of helpers? Based off the [docs](https://github.com/redux-saga/redux-saga/tree/master/docs/api#takelatestpattern-saga-args), I've really only seen the syntax: `yield takeLatest(ADD_BREADCRUMB, switchView)` and so I'm wondering if that could be an issue.

But as said before, it's difficult to know exactly where things could be going wrong without sharing the code on something like webpackbin.

**Comment by Andarist** [comment]
yielding array is fine, its instructing the saga to run each item in parallel and resolve once all of them compelted - pretty similar to `Promise.all`

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
