### ISSUE TITLE
Testing that a saga was called

### ISSUE THREAD

**Issue by richierob62** [redux-saga/redux-saga#916]
Is there a not-too-complex way of testing that a saga was called for a given action?

I'm not speaking of the testing of the saga itself, but having a way of ensuring that I did respond to a given action and not overlook it.

**Comment by eirslett** [comment]
You could unit test the root saga, where you use `takeEvery` and delegate actions to the saga, at least that's what I do.

**Comment by baldwmic** [comment]
Taking a simple example from the [docs](https://github.com/redux-saga/redux-saga/blob/master/docs/basics/DeclarativeEffects.md#declarative-effects):

```
function* watchFetchProducts() {
  yield takeEvery('PRODUCTS_REQUESTED', fetchProducts)
}

function* fetchProducts() {
  const products = yield Api.fetch('/products')
  console.log(products)
}
```

@richierob62 are you asking how you can easily test whether the `fetchProducts` generator was called when the `PRODUCTS_REQUESTED` action is dispatched?

If so, you can spy on the `fetchProducts` generator using [sinonjs](https://github.com/sinonjs/sinon) and then test that when `PRODUCTS_REQUESTED` action is dispatched, the spied saga gets called. something like:

```
var spy = sinon.spy(fetchProducts);
store.dispatch({ type: 'PRODUCTS_REQUESTED' });
assert(spy.called)
```

@eirslett do you have an example in code of how you would test the above example? curious to see how you would approach it.

**Comment by eirslett** [comment]
```javascript
function* rootSaga () {
  yield fork(takeEvery, 'PRODUCTS_REQUESTED', fetchProducts);
}
```

```javascript
it('The root saga should react to actions', () => {
  const generator = rootSaga();
  expect(generator.next().value).to.eql(fork(takeEvery, 'PRODUCTS_REQUESTED', fetchProducts));
  expect(generator.next().done).to.eql(true);
});
```

Tests like this one end up looking a lot like the implementation. That's fine. I like to think of it as double-entry bookkeeping.
If you want black-box testing of side effects, I think they are better written as integration tests - using sinon everywhere can be cumbersome.

**Comment by baldwmic** [comment]
thanks @eirslett, it's helpful to see in code how others are doing things.

yes, i agree that using sinon to test things can get tricky; the idea is very neat, but the implementation gets hairy.

your approach reminds me of how my colleague is looking at testing sagas: https://github.com/jimbol/generator-test-runner. that tool makes testing feel more declarative, but under the hood it's really doing something very similar to what you have.

and as to white-box vs black-box tests, i know there's a big discussion here #518 ;)

**Comment by richierob62** [comment]
Thanks @eirslett and @baldwmic

> _Re: @richierob62 are you asking how you can easily test whether the fetchProducts generator was called when the PRODUCTS_REQUESTED action is dispatched?_
Yes, I was speaking of that.

Learned a lot from the mini discussion.
