### ISSUE TITLE
http://redux-saga.js.org/ seems to be down.

### ISSUE THREAD

**Issue by jinalskothari** [redux-saga/redux-saga#921]
It's not just me according to http://downforeveryoneorjustme.com/http://redux-saga.js.org/

**Comment by Andarist** [comment]
how did u even find this link? :D I mean - is it public anywhere? we have just today asked for it to become available for us and the request is still pending - https://github.com/js-org/dns.js.org/pull/1193

**Comment by jinalskothari** [comment]
https://redux-saga.github.io/redux-saga/ redirects there!

**Comment by baldwmic** [comment]
@Andarist must be because we merged in #920 before js-org approved us! That was my mistake for not catching that final step 😭

**Comment by Andarist** [comment]
Reverted the change, I think it should be fine now. Sorry for the mess. Didnt realise it will cause this

**Comment by indus** [comment]
Sorry for the mess. When I wrote the 4 steps for a subdomain request GiHub pages didn´t made an automatic redirect after adding a CNAME. Now I also accept requests withou a CNAME and add them to JS.ORGs zonefile; but merge the request after the CNAME is setup by the owner... Nevertheless it is on it way but you may face DNS caching if you tied to open the URL before.

**Comment by baldwmic** [comment]
@Andarist should we add back the CNAME since the redux-saga.js.org subdomain has been added?

**Comment by Andarist** [comment]
@baldwmic done, i hope it will go all good this time

@indus no worries :)

**Comment by baldwmic** [comment]
it's working! 🎈 

@Andarist we should update the website link for the [repo](https://github.com/redux-saga/redux-saga)

currently it's this: https://redux-saga.github.io/redux-saga/
should go to this: https://redux-saga.js.org/

it re-directs right now, but just to make the complete switch

**Comment by Andarist** [comment]
@baldwmic done, i think ive found every occurance
