### ISSUE TITLE
OAUTH2 Authentication and token management with redux-saga

### ISSUE THREAD

**Issue by dispix** [redux-saga/redux-saga#924]
Hi everyone,

I have been working with redux-saga for a couple of months now, and would like to share with you an OAUTH2 workflow that I wrote for a project at work. The full saga workflow is available here: https://gist.github.com/dispix/5a9c990bd6eea4b7f9a93fe93722baa8

What the worklow does is:
1. When the application starts, listens for the start of the authentication process (either through login/password or existing tokens saved in localStorage).
2. Once the authentication process succeeds, it listens for a logout action from the user.

While the user is authenticated, another saga watches for a special `app/FETCH` event that is used for every request in the application. The action looks like this:
```js
{
  type: 'app/FETCH',
  payload: {
    url: '/users',
    // Eventually, some other stuff like additional headers, request method, etc.
    onSuccess: (response) => doSomething(response), // Will be called when the request succeeds
    onError: (error) => doSomethingElse(error), // Will be called if the request fails
  },
  meta: { /* Some metas if needed */ }
}
```

The saga then adds the authentication header (using the access token) and handles the request process:
- if all is well, wait for the response and then call the `onSuccess` or `onError` method;
- if the access token is expired, call the `refreshTokens` method and wait for its completion. If the tokens refreshed successfully, the request will then be sent to the API. This allows the application to delay the request when needed.
- if multiple requests are sent at the same time, only the first request will actually trigger a refresh request but all the requests will wait for the completion of that call before proceeding.

I was posting here to share that knowledge, and eventually gather some remarks to improve these workflows. As I am not fully competent yet with redux-saga, there may be some way to write these workflows in a more concise and simple way.

Thanks for reading. I hope this will get some attention and, eventually, some comments :)

**Comment by baldwmic** [comment]
@dispix this looks very well thought out and it's awesome you shared with the rest of us! I haven't worked on Oauth2 personally, but as I understand, there are plenty of pitfalls to avoid so I'm sure this will be useful to others.

One musing, have you wondered whether something like this might make a good middleware that others using redux and redux-saga could install and use without needing to re-implement the difficult aspects of Oauth2 you already solved?

**Comment by dispix** [comment]
I don't think this code can be used as a middleware in its current state. The `app/FETCH` action payload contains two mandatory callback `onSuccess` and `onError`, in my opinion calling them upon receiving a response is not the role of a middleware doesn't has much to do with redux. Plus my code is very implementation-specific (see the specific 50x error handling for example) and I fear it may be really hard to find an OAUTH2 workflow that can be abstracted enough to be put into a middleware.

But maybe I'm totally wrong about that, would love your opinion on that matter :)

**Comment by baldwmic** [comment]
I haven't had the time to look at your code specifically, but you can see that there is an auth library for redux [like this](https://github.com/jerelmiller/redux-simple-auth) that is middleware. perhaps you could explore it as an idea.

**Comment by alvelig** [comment]
Hi, I made something similar which consists of 2 libs:

https://github.com/alvelig/redux-saga-auth

https://github.com/alvelig/redux-saga-api-call-routines

It makes use of `redux-saga-routines` for compatibility with redux-form. Any comments are appreciated.

**Comment by dispix** [comment]
Nice @alvelig ! Will try to look at them cause they seem pretty interesting libs and I may give you a hand if you plan on maintaining them :)

**Comment by alvelig** [comment]
@dispix thank you for your interest. Though these are rather early versions, but I plan using this libs in production heavily, so I will be maintaining them anyway if this approach is suitable.

Some help is required more on defining input and output data for the libs, as I don't have this part clear to be able to cover most production cases.

**Comment by Andarist** [comment]
This is not an issue and the thread got a little bit stale, if you want to discuss more you can always:
- respond under this thread - every participant will get notified
- join gitter or discord (reactiflux) channels

You can also always send PRs to the addons list to share your awesome work with the community.
