### ISSUE TITLE
Actions are being push to store multiple times from saga in an app with react-router

### ISSUE THREAD

**Issue by kfrajtak** [redux-saga/redux-saga#926]
Hi,

I have ran into a problem in my application. I have a page that displays data from a backend data store, the data is loaded when the page is loaded or when the user clicks Refresh button. When I stay on the page, everything works perfect - one click, one action pushed to redux store, one server roundtrip.

The sequence is as follows

* take NODES_LOAD
* put NODES_LOADING true
* fetch data
* put NODES_LOADED

But when I navigate away to another page using the react-router `Link` and go back to the same page, the sagas start to act weird. After a specific action is taken, the following action is put multiple times (or as many times I navigate away from this page and back again).

And then the sequence of action is 

* take NODES_LOAD
* put NODES_LOADING true
* put NODES_LOADING true
* put NODES_LOADING true
* fetch data
* fetch data
* fetch data
* put NODES_LOADED
* put NODES_LOADED
* put NODES_LOADED

To be sure that the sagas are not singletons (as I originally thought), I have added a dumb hashcode to the saga:

```let i = 0;

function* watchLoadNodesSaga() {
  i++;
  while (true) {
    try {  
      yield take(constants.NODES_LOAD);
      console.info(i);
      ...
```
which writes the so-called hashcode to the console multiple times (as described earlier). The value of variable `i` is advanced whenever I land on the nodes page. The sagas are introduced into the system in the routeing mechanism in `injectAsyncSagas` method in [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate/blob/fd77388ec716f9c853a2464ac4b03dfb646a3887/app/utils/asyncInjectors.js#L51) calling `sagas.map(store.runSaga);`. So everytime the route is matched, the sagas are injected and ran using the `store.runSaga` method.

The issue can be reproduced when you run the sample react-boilerplate project and replace the content of sagas.js file with 

```import { take, call, put, select, cancel, takeLatest } from 'redux-saga/effects';
import { LOCATION_CHANGE } from 'react-router-redux';
import { LOAD_REPOS } from 'containers/App/constants';
import { reposLoaded, repoLoadingError } from 'containers/App/actions';

import request from 'utils/request';
import { makeSelectUsername } from 'containers/HomePage/selectors';

function* watchGithubData() {
    while (true) {
        try {
            yield take(LOAD_REPOS);
            // Select username from store
            const username = yield select(makeSelectUsername());
            const requestURL = `https://api.github.com/users/${username}/repos?type=all&sort=updated`;

            // Call our request helper (see 'utils/request')
            const repos = yield call(request, requestURL);
            yield put(reposLoaded(repos, username));

        } catch (err) {
            yield put(repoLoadingError(err));
        }
    }
}

export default [
    watchGithubData
];
```

You'll notice multiple `boilerplate/App/LOAD_REPOS_ERROR` actions being pushed to the store.

Has anyone experienced the same problem? Am I doing something wrong?

Thanks,
Karel

PS: I have created the issue in the react-boilerplate code.

**Comment by Andarist** [comment]
Please look at this issue - https://github.com/redux-saga/redux-saga/issues/917#issuecomment-295425909

**Comment by kfrajtak** [comment]
It does not work for me. 


This is my saga 

```
export function* loadNodesSaga() {
    const watcher = yield takeLatest(constants.NODES_LOAD, getNodes);
    yield take(LOCATION_CHANGE);
    yield put({type: 'location changed'});
    yield cancel(watcher);
    yield put({type: 'canceled'});
}
```
and the `put` method is not invoked ...

**Comment by baldwmic** [comment]
@kfrajtak can you post a [webpackbin](https://www.webpackbin.com/) of your code? it's difficult to debug (at least for me) without knowing what else could be going on

**Comment by kfrajtak** [comment]
My app is quite large. However, I am experiencing the same issue with react-boilerplate sample application (when saga is using `while` cycle).

I have also noticed that you are importing `takeLatest` from `redux-saga/effects`. In my project I have to reference it from `redux-saga`, otherwise, the `takeLatest` function is undefined (it is not export in `effects.js` file). I have version 0.14.3 installed.

**Comment by Andarist** [comment]
> and the put method is not invoked ...

that would mean `LOCATION_CHANGE` is not dispatched. Could u confirm it? Could u maybe also confirm that the line after `const watcher = yield takeLatest(constants.NODES_LOAD, getNodes);` is reached?

> I have also noticed that you are importing takeLatest from redux-saga/effects. In my project I have to reference it from redux-saga, otherwise, the takeLatest function is undefined (it is not export in effects.js file). I have version 0.14.3 installed.

That is rather weird, they are part of `effects` since `v0.14`.

**Comment by trevorharwell** [comment]
I just ran into this exact issue.  It appears that react-boilerplate is blinding calling `store.runSaga` every time you load a dynamic page https://github.com/react-boilerplate/react-boilerplate/blob/master/app/routes.js#L34.  I, like @kfrajtak, assumed that the default saga would be loaded once on first page load, and then never again.  It appears this assumption is incorrect.  I will be submitting a PR to the react-boilerplate to fix this issue as soon as a get a chance.

**Comment by trevorharwell** [comment]
Here is my PR that allows loaded components to not get re-processed and thus cause this issue.
https://github.com/react-boilerplate/react-boilerplate/pull/1734

**Comment by baldwmic** [comment]
Awesome work, thank you @trevorharwell ! 😄

**Comment by Andarist** [comment]
This issue got a little bit stale and also seems to be resolved, therefore Im closing it.
