### ISSUE TITLE
tracking and retrying parallelTasks[index]

### ISSUE THREAD

**Issue by anthonychung14** [redux-saga/redux-saga#928]
docs indicate that in order to run parallel tasks, we do something like this

```
const [ a, b, c, ] = yield [ forkA, forkB, forkC ] 
```

what strategies would you suggest for handling the status of each of these tasks? 

for example:

a/c are successful, do X action
b is not successful, do y action

I thought about utilizing actionChannels along the lines of

```
const tasksStarted = yield actionChannel(start_task);
const tasksCompleted = yield actionChannel(end_task);
```
Each completed task can then be placed in their corresponding bucket (X/Y)

However, I'm not sure if this is over-engineered and wanted a sanity check if anyone else has solved similar issues.

To give a sense of scale, the upper bound of this array of tasks can be up to 20.

I also posted this in StackOverflow, but since the community here is extremely knowledgable, I thought it'd be worth it in try both *ahem* channels.

**Comment by Andarist** [comment]
Could post some more thorough usage of this? Would be easier to help if you provide a complete problem to solve.

**Comment by anthonychung14** [comment]
it's a lengthy piece of code. I did end up figuring it out using the aforementioned strategy

**Comment by Andarist** [comment]
You could maybe leverage `join` for this use case if you want a single result from each of those parallel tasks and you can stop your saga to wait for each completion. But again - cant advise more without more exact use case description.
