### ISSUE TITLE
Can i make a repository for translated docs?

### ISSUE THREAD

**Issue by mskims** [redux-saga/redux-saga#931]
Hello guys, I'm studying redux libraries now and I'm very interested in `redux-saga`.

As a native Korean speaker, I've tried to find saga docs written in Korean, but what I have found is just one readme paper translation at [this](https://github.com/redux-saga/redux-saga/blob/master/README_ko.md)

if you guys don't mind, I want to write a Korean translation docs like [Chinese did!](https://github.com/superRaytin/redux-saga-in-chinese)

Thank you for contributing your awesome repository!

**Comment by baldwmic** [comment]
@mskims that would be amazing! I'm sure other Korean speakers would be most grateful to you if you did. I'm not on the redux-saga team, but I'm sure @Andarist would approve as there's already some other translations

**Comment by Andarist** [comment]
Yeah, sure - I can merge in. However not a big fan of those as they tend to become outdated quite fast.
