### ISSUE TITLE
Not enumerable Error property sagaStack

### ISSUE THREAD

**Issue by morulus** [redux-saga/redux-saga#934]
Dear Saga creators, I found myself in a terrible situation with creating snapshots with store state, which contains errors.
Normal javascript error has not enumerable properties. So JSON.stringify(new Error()); equals `{}`. And it is normal.
But Saga adds `sagaStack` to the errors (provided by effects) as enumerable property. So JSON become  `{sagaStack: '...'}`. I'm comparing state snapshots with Jest. Since each machine generates own error text, my tests became fail.
This problem solved for me with preparing each error with Object.defineProperty{e, 'sagaStack', { writable: true, enumerable: false, configurable: true, value: '' }. But it is the dirty way. 

Why not make `sagaStack` unenumerable as such as all others properties of Error?

**Comment by Andarist** [comment]
What's ur use case of keeping errors in the state?

If u need this, I'm open for a PR which would fix this issue for u. Quite the only place to change is [here](https://github.com/redux-saga/redux-saga/blob/d0aa83d782b241799264879e139db4d03438ae28/src/internal/proc.js#L286) and possibly a test for this would be needed
