### ISSUE TITLE
[Question] Way to implement a throttle that allows early execution.

### ISSUE THREAD

**Issue by lxcid** [redux-saga/redux-saga#938]
Hey Andarist, we chatted on reactiflux and here's the follow issue on the topic.

Here's our chatlog:
```
Andarist: @lxcid aint sure what do u mean by force flush
Andarist: and it depends on what kind of debounce would u like to implement
Andarist: leading, trailing or both?
lxcid: @Andarist hey thanks for replying! I meant forcing the debounce to execute early though
lxcid: In lodash, to achieve that, you will call flush on the denounced method.
Andarist: @lxcid  please make an issue on the github repo, that way i wont forget to reply to u 2morrow
Andarist: Cant do this from mobile now
```

I going to switch to asking about throttle instead of debounce here, as my research was mostly focus on throttle before I asked the question. (Sorry for the confusion!)

So in lodash, I can achieve this with the following code.
```javascript
import throttle from 'lodash/throttle';

const log = throttle((msg) => console.log(msg), 250);
log('hello');
log.flush(); // console should print hello immediately here…
```
In [the API document under notes](https://github.com/redux-saga/redux-saga/tree/master/docs/api#throttlems-pattern-saga-args), you provides the sample implementation for throttle in saga…

```javascript
function* throttle(ms, pattern, task, ...args) {
  const throttleChannel = yield actionChannel(pattern, buffers.sliding(1))

  while (true) {
    const action = yield take(throttleChannel)
    yield fork(task, ...args, action)
    yield call(delay, ms)
  }
}
```

This is a nice implementation but one issue with this is that it blocked on `call(delay, ms)`, thus wouldn't allow us to force it to execute early or implement the `flush()` behaviour in lodash.

Do you have a good alternative to this requirement?

**Comment by Andarist** [comment]
The simplest would be this:
```javascript
function* throttle(ms, throttleChannel, task, ...args) {
  while (true) {
    const action = yield take(throttleChannel)
    yield fork(task, ...args, action)
    yield call(delay, ms)
  }
}

function* flushPending(channel, buffer) {
	if (buffer.isEmpty()) {
		return
	}

	const action = yield take(channel)
	yield call(callAPI, action)
}

function* saga() {
	const buffer = buffers.sliding(1)
	const channel = yield actionChannel(pattern, buffer)

	yield fork(throttle, 300, channel, callAPI)

	// ...
	yield call(flushPending, channel, buffer)
}
```

some duplication involved, maybe you could abstract this somehow more nicely, but ive wanted to show the idea how this could have been approached

other idea is maybe simpler:
```javascript
function* flushableThrottle(ms, pattern, task, ...args) {
  const throttleChannel = yield actionChannel(pattern, buffers.sliding(1))

  while (true) {
    const action = yield take(throttleChannel)
    yield fork(task, ...args, action)
    yield race({
    	flush: take('FLUSH_THROTTLE')
    	wait: call(delay, ms)	
    })
  }
}
```

**Comment by lxcid** [comment]
Thanks @Andarist! Both example are awesome! I couldn't have asked for more!

**Comment by shinima** [comment]
@Slapbox In `redux-Saga@1.0.0-beta.1`, if you import `delay` from `'redux-saga/utils'`, then `delay` is an async function which returns a Promise when called.  If you import `delay` from `'redux-saga/effects'`, then `delay` is an effect creator which returns a call-effect when called, and that means you should always call `delay` directly.

I find these two `delay` very confusing since they have the same name but with different behavior.

**Comment by Slapbox** [comment]
Great explanation. Thanks very much @shinima. If you have any ideas about this related question on flushable buffers in throttling (with the addition of canceling tasks) I could really use some guidance on what I'm misunderstanding here: https://github.com/redux-saga/redux-saga/issues/1511

Thanks again for your explanation of `delay`. Makes perfect sense, though the existence of the two methods in the first place makes less sense.

**Comment by Andarist** [comment]
> Thanks again for your explanation of delay. Makes perfect sense, though the existence of the two methods in the first place makes less sense.

Agreed, we probably should hide the second one to make it less confusing. We should only expose it somehow for more advanced users. Maybe through a separate package?
