### ISSUE TITLE
Writing sagas based on context services instead of singletons

### ISSUE THREAD

**Issue by VictorQueiroz** [redux-saga/redux-saga#939]
I used to write singletons of api clients to easy execute requests anywhere of the application. But turns out that I need to get rid of them. I need to instantiate them somewhere else for some application particular purposes, also testing is easier this way. So how can I work with that? Instead of having a global object like `ApiUtil.get('/users/200')` access it using context like `this.apiClient.get('/users/200')` or something related. How can I create sagas that support saga function context by default?

**Comment by aikoven** [comment]
The Context feature is what you're looking for, see https://github.com/redux-saga/redux-saga/pull/735

**Comment by VictorQueiroz** [comment]
Solved my problem. Nice feature, thank you
