### ISSUE TITLE
What do you think about this "actor's concurrency model" 

### ISSUE THREAD

**Issue by tugorez** [redux-saga/redux-saga#941]
```javascript
function* pong({ payload: { pid, ...args } }) {
   const payload = `Hello ${pid}`;
   put({ type: pid, payload });
}

function* ping() {
  const self = uuid(); // some random string
  const payload = { pid: self };
  yield put({ type: 'PONG', payload  });
  const { payload: message } = yield take(pid);
  console.log(payload);
}
```
The interesting part here is the ability to coordinate 2 sagas with just passing actions;

**Comment by tugorez** [comment]
perhaps related to https://github.com/redux-saga/redux-saga/issues/886 and https://github.com/redux-saga/redux-saga/issues/891

**Comment by Andarist** [comment]
If the pattern solves your problem then its fine :) Dont have anything against it. Its just leveraging the redux protocol (actions) to coordinate various parts of the system, its exactly where `redux` shines.

**Comment by tugorez** [comment]
@Andarist Thank you very much for your feedback ;)
