### ISSUE TITLE
Update release notes

### ISSUE THREAD

**Issue by jfairbank** [redux-saga/redux-saga#942]
Hello!

I noticed that the last few releases haven't had release notes when I've visited the "Releases" tab. I figured that the patch versions for v0.14 were just minor bug fixes, so I wasn't too concerned. However, Greenkeeper just alerted me to v0.15, so I visited the releases to find no release notes.

Are release notes kept anywhere else that I'm missing? I depend on release notes to ensure that [redux-saga-test-plan](https://github.com/jfairbank/redux-saga-test-plan) supports all of redux-saga's features. I haven't kept up with all the issues and commits in this repo to properly glean all the changes made to redux-saga for v0.15.0.

Would you be able to update the release notes for v0.15 please? I'd be happy to help in the future if you need help keeping track of changes. Thanks as always for redux-saga!

**Comment by Andarist** [comment]
Ive seen ur issue just while I was writing new release notes ;) They are available in the regular place, aint publishing anywhere else, so dont worry. Just did a release first and have started to write the new one, wasnt fast enough for you though :)

**Comment by jfairbank** [comment]
Haha, no worries. Sorry for opening the issue so quickly! I should have waited. I just happened to be on GitHub when Greenkeeper alerted me. Thanks again!

**Comment by Andarist** [comment]
No worries, there were quite some changes. Hopefully didnt screw anyone's project by releasing this.
