### ISSUE TITLE
Documentation: Running Tasks in Parallel

### ISSUE THREAD

**Issue by SmileSydney** [redux-saga/redux-saga#946]
I have two actions to run in parallel. The sample code in the documentation section below suggests using the `yield all` syntax. I'm getting an error on `all` ("all is not defined").

Do I need to import `all` from a library?

From https://redux-saga.js.org/docs/advanced/RunningTasksInParallel.html:
```
const [users, repos]  = yield all([
  call(fetch, '/users'),
  call(fetch, '/repos')
])
```

**Comment by Andarist** [comment]
What version of the redux-saga do u have? All was introduced in v0.15, but its functionality was achieved in previous versions by yielding arrays of effects.

**Comment by SmileSydney** [comment]
Thanks @Andarist - that was it! Updated to 0.15 and now works like a charm.

**Comment by vivekdwivedi** [comment]
Upgraded to 0.15.3 and still getting the same error. Is there something specific to watch out here? Just uninstalled redux-saga and installed again to get the latest package.

**Comment by Andarist** [comment]
@vivekdwivedi do you `import { all } from 'redux-saga/effects'` first?

**Comment by vivekdwivedi** [comment]
No. I guess it wasn't mentioned anywhere in the tutorials. I tried that in previous version thinking I needed to import it, but all wasn't available then. Importing all fixes things. Thanks!

**Comment by Andarist** [comment]
If its missing somewhere in the docs, please report the issue or send the PR with a fix. Thanks in advance ;)
