### ISSUE TITLE
[Feature] fork.try() - unblocking and uncatching effect

### ISSUE THREAD

**Issue by DiMoNTD** [redux-saga/redux-saga#952]
I have many situations, when send data to server, but responses to those requests is optional. So I use `fork` effect that make request and don't block the thread. But if server unavailable or something go wrong, it's throw an error, that I need to wrap with try/catch (or catch in Promise). So from laconic code
```
yield fork(doRequest);
```
need to write like that
```
yield fork(async () => {
  try {
    await doRequest();
  } catch (e) {
    // do nothing;
  }
})
```
 So would be cool to make `fork` effect, that don't throw error up to stack

Finally
```
yield fork.try(doRequest)
```

What do you think about it?

**Comment by Andarist** [comment]
cant u just make a 'safe' wrapper which could be used to wrap `doRequest`? something like
```javascript
const safe = async (worker, ...args) => {
  try {
    await worker(...args);
  } catch (e) {
    // do nothing;
  }
}
```
and then use it like this:
`yield fork.try(safe(doRequest))`

Aint sure completely about the code as Im not using async functions in my project, but that way or another it should be doable I think

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
