### ISSUE TITLE
Incorrect warning message for takeLatest for 0.15.1

### ISSUE THREAD

**Issue by ismay** [redux-saga/redux-saga#959]
I've upgraded to 0.15.1 and got this warning:

```
import takeLatest from 'redux-saga' has been deprecated in favor of import takeLatest from 'redux-saga/effects'.
The latter will not work with yield*, as helper effects are wrapped automatically for you in fork effect.
Therefore yield takeLatest will return task descriptor to your saga and execute next lines of code. 
```

It instructs you to use: `import takeLatest from 'redux-saga/effects'`, whereas I believe it should be `import { takeLatest } from 'redux-saga/effects'`

**Comment by Andarist** [comment]
Warning is ok. You should upgrade ur code so those are imported from effects

**Comment by ismay** [comment]
I understand, but what I mean is that the warning-message example is missing the brackets, which implicates that it is a default export.

So not:

```
import takeLatest from 'redux-saga'
```

But

```
import { takeLatest } from 'redux-saga'
```

**Comment by Andarist** [comment]
Ah, didnt notice this. Gonna update it tonight. Thanks

**Comment by Andarist** [comment]
Fixed, but gonna release later

**Comment by pak11273** [comment]
I'm getting this warning too.
