### ISSUE TITLE
[...effects] has been deprecated in favor of all([...effects]), please update your code 

### ISSUE THREAD

**Issue by hurrtz** [redux-saga/redux-saga#960]
I have updated redux-saga to its current version and now I am getting these warnings. I am unsure as to how I should update my code to resolve the issue.

Nowhere in my code am using [...effects] as a pattern yet I am using sagas heavily which makes debugging a bit tedious if I don't know where to look.

Can you point to some kind of documentation where I can read this issue and see why you have chosen to trigger this warning?

**Comment by ryankask** [comment]
Check out the [release notes for v0.15.0](https://github.com/redux-saga/redux-saga/releases/tag/v0.15.0). It mentions the new `all` effect. See also 7078c204a22.

If you're not yielding an array in your code, are you possibly using a third party package that is?

**Comment by hurrtz** [comment]
You where very much correct, thank you. Your answer pointed me in the right direction:
https://github.com/redux-saga/redux-saga/tree/master/docs/api#alleffects---parallel-effects

**Comment by Andarist** [comment]
We should probably make this warning less excessive as it might spam your console quite a bit. Will take care of it today.

**Comment by imamatory** [comment]
So `all([...effects])` is deprecated? Maybe it should be in docs?

**Comment by Andarist** [comment]
No it's not deprecated - in fact its the favored one and is in the docs - https://redux-saga.js.org/docs/api/#alleffects---parallel-effects

`yield [...effects]` got deprecated

**Comment by oliversisson** [comment]
For me, I only used it on the rootsaga:
```
export default function* rootSaga() {
  yield all([
```

(import all: `import {all} from 'redux-saga/effects';`)

**Comment by crazy4groovy** [comment]
I do the same as @oliversisson. Just updated to v0.15.3, updated code accordingly, but I still see the deprecation warning. Why?

If I put a debug break in `runAllEffect` (which runs right after the deprecation msg logged), the `effects` is an empty array. This all seems odd to me...

**Comment by Andarist** [comment]
@crazy4groovy

Maybe you have used something like yield results.map(res => put(someAction(res))) and missed that when upgrading?

**Comment by msageryd** [comment]
Thank you @Andarist 

**yield someArray.map** bit me. I had used it in many places and it was not an easy thing to search for. I had to search for all of my "yield" and manually locate the places to update.

It would be great if the deprecation warning could pin point the place in the code that is bad. Is that hard to fix?

I'm good for now, but I suspect more will be biten by this.

**Comment by jasondonnette** [comment]
Same, although in Atom doing a regex search for `yield .+.map` found them for me pretty easily

**Comment by Andarist** [comment]
I'll try to check if it's easy to pin point the root causing deprecation warnings

**Comment by DominicTobias** [comment]
So in summary how do I convert this to use `all`?

```js
export default function* rootSaga() {
  yield allSagas.map(saga => fork(saga));
}
```

**Comment by DominicTobias** [comment]
In summary am I doing this correctly? seems a bit verbose:

```js
export default function* rootSaga() {
  yield all(allSagas.map(saga => fork(saga)));
}
```

**Comment by Andarist** [comment]
@DominicTobias yes

**Comment by wSLecHayfIeNdock** [comment]
✍️ 🎉
```
export default function *rootSagas() {
-  yield [
-    fork(app),
-    fork(user),
-  ];
+  yield fork(app);
+  yield fork(user);
}
```

**Comment by iamdevlinph** [comment]
I still can't fix the deprecation warning on my side :( My situation is that I separate different sagas into different files and yield them all from the main sagas file.

**_sagas.js**
```
import { all } from 'redux-saga/effects';

import aboutSaga from './about/aboutSaga';

export default function* mySaga() {
  yield all([
    ...aboutSaga,
    // more sagas from different files
  ]);
}
```
**aboutSaga.js**
```
import { put, takeLatest, call } from 'redux-saga/effects';
import rsf from '../rsf';

import { types as aboutTypes } from './about';

function* aboutWillFetch() {
  try {
    const about = yield call(rsf.database.read, 'about');
    yield put({ type: aboutTypes.ABOUT_SUCCESS, about: yield about });
  } catch (e) {
    // console.log(e);
  }
}

const aboutSaga = [
  takeLatest(aboutTypes.ABOUT_REQUEST, aboutWillFetch),
];

export default aboutSaga;
```

I tried the following changes on my **_sagas.js** file with no success
### 1
```
import { all, fork } from 'redux-saga/effects';

import aboutSaga from './about/aboutSaga';

export default function* mySaga() {
  yield all(aboutSaga.map(saga => fork(saga)));
}
```
### 2
```
import { all, call } from 'redux-saga/effects';

import aboutSaga from './about/aboutSaga';

export default function* mySaga() {
  yield all([
    call(aboutSaga),
  ]);
}
```
### 3
```
import { all, fork } from 'redux-saga/effects';

import aboutSaga from './about/aboutSaga';

export default function* mySaga() {
  yield all(aboutSaga.map(fork));
}
```

My attempts are from what I found on google but I still doesn't help.

You can refer to [the file here](https://github.com/iamdevlinph/resume/blob/master/src/sagaDucks/_sagas.js)

**Comment by silarmani** [comment]
After hours of debugging my code I noticed something strange

If I use all + map + call, where the called function takes 1 parameter then no warning message is logged

`yield all(registerTdids.map((registerTdid, idx) => call(requestLookups, registerTdid)));`

however if I add on more parameter to the call then I get the warning

`yield all(registerTdids.map((registerTdid, idx) => call(requestLookups, registerTdid, idx > 0)));`

I even logged what is passed on to all()

- with 1 parameter

[ { '@@redux-saga/IO': true,
    CALL:
     { context: null,
       fn: [Function: requestLookups],
       args: [ '3.1.1.risk-register.da7ecd5e8ecc4c91ab3f5fa2a0686346' ] } },
  { '@@redux-saga/IO': true,
    CALL:
     { context: null,
       fn: [Function: requestLookups],
       args: [ '3.1.1.risk-register.ac408e95706e4235984d6587dbe8ee4d' ] } } ]

- with 2 parameters

', [ { '@@redux-saga/IO': true,
    CALL:
     { context: null,
       fn: [Function: requestLookups],
       args: [ '3.1.1.risk-register.da7ecd5e8ecc4c91ab3f5fa2a0686346', true ] } },
  { '@@redux-saga/IO': true,
    CALL:
     { context: null,
       fn: [Function: requestLookups],
       args: [ '3.1.1.risk-register.ac408e95706e4235984d6587dbe8ee4d', true ] } } ]

W ReactNativeJS: '[...effects] has been deprecated in favor of all([...effects]), please update your code', ''

Does anyone know why?

**Comment by Andarist** [comment]
That's weird, hard to say what's the reason without having the issue reproduced.

**Comment by phuongthuan** [comment]
```
export function* fetchAllReportsOfTeam(action) {
  try {
    yield delay(700);
    const members = yield call(callGetMembersOfTeam, action.teamName);
    const reports = yield members.map(function (member) {
      try {
        return call(callFetchAllReportsOfUser, member.id);
      } catch (error) {
        return put(fetchAllReportsOfUserFailed(error));
      }
    });
    const mergedReports = [].concat.apply([], reports);
    mergedReports.map(report => {
      const memberReport = members.filter(member => member.id === report.userId);
      if (memberReport && memberReport.length > 0) {
        report.userId = memberReport[0];
      }
      return null;
    });

    yield put(getAllReportsOfTeamSucceeded(mergedReports));
  } catch (error) {
    yield put(getAllReportsOfTeamFailed(error.message));
  }
}

export function* watchFetchAllReportsOfTeam() {
  yield takeLatest(GET_ALL_REPORTS_OF_TEAM, fetchAllReportsOfTeam);
}

export function* statisticSagaPage() {
  yield all([
    fork(watchFetchAllReportsOfTeam)
  ])
}
```

I write code like this. I don't know why I got the error.

**Comment by seantcanavan** [comment]
I did this for all the `yield all([fork(), fork()]);` calls in the code but still got the warning. 

I tried it for the `take` calls and got an error:

`const action = yield take(all([ACTION1, ACTION2]));`

Any ideas?

**Comment by Andarist** [comment]
`all` is handling parallel effects - you can't combine it with `take` like that. Not sure what results you are trying to achieve here, so not sure how can I help. If you provide a **runnable** repro case then I could take a look at it.

**Comment by seantcanavan** [comment]
No worries I appreciate the reply @Andarist. It's company code so I can't share it unfortunately. I'll keep learning `redux-saga` and hopefully I can knock out that warning on the initial page load.
