### ISSUE TITLE
Yielding a falsy value results in a saga that never continues

### ISSUE THREAD

**Issue by rjdestigter** [redux-saga/redux-saga#961]
Yielding `false`, `0`, or `""`, or any other falsy value will stop the saga from continuing.

```
function *proc1 () {
    yield call(delay, 1000)
    yield false
    console.info('Proc 1 delay is over')
  }

  function *main () {
    console.info('Started')
    yield call(proc1)
    console.info('Proc 1 is finished')
  }

  store.runSaga(main)
```

In the above example `console.info('Proc 1 delay is over')` is never reached.

Conversation in gitter:

https://gitter.im/yelouafi/redux-saga?at=590b4151bedc54b621c92e95
https://gitter.im/yelouafi/redux-saga?at=590b4151bedc54b621c92e95

Reply by @Andarist:
```
var createAsEffectType = function createAsEffectType(type) {
  return function (effect) {
    return effect && effect[IO] && effect[type];
  };
};
```

and first check if what you have yielded is a concrete effect
`: (is.notUndef(data = asEffect.take(effect))) ? runTakeEffect(data, currCb) (effect && effect[IO] && effect[type]) === false`
which ofc is.notUndef and your false (or any other falsy value) is trying to be resolved as take effect
```

**Comment by Andarist** [comment]
gonna release 2morrow morning, thanks for reporting!
