### ISSUE TITLE
takeLatest/actionChannel subscribed to the same action + actionChannel peek

### ISSUE THREAD

**Issue by anthonychung14** [redux-saga/redux-saga#962]
The general problem here is that there are two types of server calls, transactions and tasks.
All tasks accumulated must complete before a transaction starts

```
function* requestWatcher(requestChannel, taskChannel, taskBuffer) {
    while (true) {
        const { transaction, task } = yield race({
            transaction: take(requestChannel),
            task: take(taskChannel)
        });

        if (transaction) {
            yield put({ type: workingData.transactions.CREATE });
        }

        if (task) {
            // WAIT FOR ALL TASKS
            yield put({ type: 'TASK_IN_FLIGHT', payload: task });
            yield fork(flightAccumulator, flightChannel)
            yield take('ALL_TASKS_COMPLETE');
        }
    }
}
```

here, you can see that if a single task fires before a transaction, we want all tasks (and any subsequent tasks fired) to resolve before creating a transaction.

initially, I had a helperSaga monitor tasks with takeLatest
```
yield takeLatest('TASK_START', taskManager)

function* taskManager(taskBuffer, action) {
    console.log(action.type, action.meta, 'type in manager');
    const { payload, meta: { pid } } = yield take('TASK_COMPLETE');

        /*
            edge case: if A has fired while B resolved,
            the taskBuffer will actually be empty while we wait for it to resolve
            with takeLatest, we are guaranteed we are waiting to resolve most recent taskStart

            so while we're waiting, taskBuffer should be empty, so it's safe to put
        */
        // if most recent task complete does not match the first task that started,
        // wait for it to come back
    if (pid !== action.meta.pid) {
        yield take('TASK_COMPLETE');
    }

    yield put({ type: 'ALL_TASKS_COMPLETE', payload });
}
```
I noticed in Redux DevTools that in firing 3x TASKS in rapid succession, the first TASK_START was not recorded in devTools (even though it logged 3x TASK_COMPLETE

Questions:
1. Can takeLatest and actionChannel be subscribed to the same action?
2. Is there anyway to query an actionChannel for the number of items (or PEEK) at it without using yield take?

**Comment by Andarist** [comment]
> Can takeLatest and actionChannel be subscribed to the same action?

Yes, although probably not the best idea imho

> Is there anyway to query an actionChannel for the number of items (or PEEK) at it without using yield take?

no way to check numer of items, but its possible to check if there are any:
```javascript
const buf = buffers.expanding()
const chan = yield actionChannel(ACTION_TYPE, buf)

//...
if (buf.isEmpty()) {
  //...
}
```

**Comment by anthonychung14** [comment]
shucks. I settled copying data from the channel and maintaining a separate counter for the items that pass through the channel.

thank you for the quick reply!
