### ISSUE TITLE
storing actionChannels/buffers within Redux

### ISSUE THREAD

**Issue by anthonychung14** [redux-saga/redux-saga#963]
Is it a worthwhile pattern/architecture to store actionChannels/buffers within the Redux Store?

I ask because in complicated async scenarios, I need to share/maintain channels across sagas and would like to avoid the nuisance of passing down both args to determine whether or not a channel is empty, etc.

**Comment by Andarist** [comment]
Probably not the best idea as you lose serialization of the store. However check out recently added `setContext`/`getContext` effects. No docs yet but you can find the valuable informations linked in [the changelog](https://github.com/redux-saga/redux-saga/releases/tag/v0.15.0)

**Comment by anthonychung14** [comment]
makes sense. I took a look at the changelog and PR, but since it stemmed from someone asking about connect to non-Redux sources, it's not as apparent to me how I can apply these effects towards setting actionChannels/buffers as a type of context

could you give a really brief example of a use case for

1. make actionChannelContext
2. pass to child task?

**Comment by Andarist** [comment]
```javascript
function* saga() {
	const chan = yield getContext('chan')
}


function* saga() {
	const chan = yield actionChannel(SOME_ACTION)
	yield setContext('chan', chan)
	yield fork(child)
}
```
notice no argument passing, just context sharing

**Comment by anthonychung14** [comment]
WHOOOAOAOAOAOAO

super stoked to try this out

sidenote: verbiage around sagas seem very similar to Go. ⚡️  late to that realization but wanted to highlight it

**Comment by anthonychung14** [comment]
PS. once I get this working, more than happy to start on some docs for it

**Comment by Andarist** [comment]
hah, wanted to write go and saga comparison (especially about channels) but never have time to sit down and do it ;)
