### ISSUE TITLE
[SSR] - Actions not being caught by Saga

### ISSUE THREAD

**Issue by cpBurn** [redux-saga/redux-saga#969]
Hi there
I'm trying to implement SSR on [this boilerplate](https://github.com/apptension/react-boilerplate). Problem is that some actions seems to not being caught by Saga. I can see in the logs that `MAINTAINERS_FETCH` action is being called properly, but it doesn't seem to resolve (`MAINTAINERS_SUCCESS`). However it works fine on Frontend.

My Saga:

```
import { call, put, takeLatest, all } from 'redux-saga/effects';

import { get } from '../api/api.sagas';
import { MaintainersTypes, MaintainersActions } from './maintainers.redux';


export function* fetchMaintainersSaga({ language }) {
  console.log('fetchMaintainersSaga');
  try {
    const data = yield call(get, '/fixtures/maintainers.json', { language });

    yield put(MaintainersActions.fetchSuccess(data));
  } catch (e) {
    yield put(MaintainersActions.fetchError(e));
  }
}

export default function* maintainersSaga() {
  yield all([
    takeLatest(MaintainersTypes.FETCH, fetchMaintainersSaga),
  ]);
}
```
Relevant server code:

```
function renderAppToString(store, renderProps) {
  return renderToString(
    <Provider store={store}>
      <RouterContext {...renderProps} />
    </Provider>
  );
}

function renderAppToStringAtLocation(url, { webpackDllNames = [], assets, lang }, callback) {
  const memoryHistory = createMemoryHistory(url);
  const store = configureStore({}, memoryHistory);

  syncHistoryWithStore(memoryHistory, store, {
    selectLocationState: selectLocationState(),
  });

  match({ routes, location: url }, (error, redirectLocation, renderProps) => {
    if (error) {
      callback({ error });
    } else if (redirectLocation) {
      callback({ redirectLocation: redirectLocation.pathname + redirectLocation.search });
    } else if (renderProps) {
      store.rootSaga.done.then(() => {
        const state = store.getState().toJS();

        const appMarkup = renderAppToString(store, renderProps);

        const doc = renderToStaticMarkup(
          <HtmlDocument
            appMarkup={appMarkup}
            lang={state.locales.language}
            state={state}
            head={Helmet.rewind()}
            assets={assets}
            webpackDllNames={webpackDllNames}
          />
        );

        const html = `<!DOCTYPE html>\n${doc}`;
        callback({ html });
      }).catch((e) => {
        callback({ e });
      });

      renderAppToString(store, renderProps);
      store.close();
    } else {
      callback({ error: new Error('Unknown error') });
    }
  });
}
```  

Replaced the run saga and added close function from [original](https://github.com/apptension/react-boilerplate/blob/master/app/modules/store.js)

``` 
  store.rootSaga = sagaMiddleware.run(rootSaga);
  store.close = () => store.dispatch(END);
```

Also, first time I try to render, `renderToString` returns `<!--empty-react:1-->`.
Any hints?

**Comment by gajus** [comment]
> [..] but it doesn't seem to resolve (MAINTAINERS_SUCCESS) [..]

What do you mean by "resolve"?

You are stopping the saga after the first render:

```js
renderAppToString(store, renderProps);
store.close();
```

Assuming you have a routine that is taking `MAINTAINERS_SUCCESS`, the saga will be stopped by the time it is issued.

**Comment by gajus** [comment]
I've asked a related question http://stackoverflow.com/questions/43834756/how-to-handle-multiple-interdependent-sagas-when-rendering-server-side

**Comment by cpBurn** [comment]
@gajus thanks for your help. Maybe I did express myself wrong. What I mean is that I pass a function to `takeLatest`, but that function is never called. I need that function to be called and every subsequent action that `put` to be called as well. Does it make sense?

**Comment by gajus** [comment]
For the record, this is how I sorted the issue in my setup.

http://stackoverflow.com/a/43839772/368691

@Andarist can you please take a look at this solution and comment whether it makes sense?

**Comment by Andarist** [comment]
Truth to be told, but I'll try to help the best I can.

@cpBurn 
You would have to show when `MaintainersTypes.FETCH` is dispatched. `store.dispatch(END)` effectively ends all sagas which are stopped on a `take` and well... `takeLatest` is using `take` under the hood. So if you call `store.close()` before you dispatch `MaintainersTypes.FETCH` then your `takeLatest` wont be able to take it

@gajus 
From what I see your `watchNewSearchCriteria` is puting `GET_MOVIES` synchronously on each `[SET_GEOLOCATION, SET_DATE]` so `call(getMovies)` should run just fine as store wont be closed (yet). Am I missing something?

**Comment by cpBurn** [comment]
@Andarist `MaintainersTypes.FETCH` is dispatched in Home component (just a simple component) on
```
  componentWillMount() {
    this.props.fetchMaintainers(this.props.language);
  }
```  
Whole file [here](https://github.com/apptension/react-boilerplate/blob/master/app/routes/home/home.component.js).

**Comment by Andarist** [comment]
could u share ur whole setup as git repository so i can run it and debug the case?

**Comment by gajus** [comment]
> @gajus
From what I see your watchNewSearchCriteria is puting GET_MOVIES synchronously on each [SET_GEOLOCATION, SET_DATE] so call(getMovies) should run just fine as store wont be closed (yet). Am I missing something?

Clarified the description of the problem on the stackoverflow.

The flow is:

1. Component `componentWillMount` dispatches `GET_GEOLOCATION` and `GET_DATE`.
2. An asynchronous saga completes execution of `GET_GEOLOCATION|GET_DATE` and dispatches `SET_GEOLOCATION|SET_DATE`.

It is then that `GET_MOVIES` is dispatched and by this time the saga is stopped.

**Comment by cpBurn** [comment]
@Andarist sure. Here you are:
https://github.com/cpBurn/redux-saga-ssr

**Comment by Andarist** [comment]
Sorry for not responding any time sooner, frankly I missed your reply somehow. I guess you have worked around your issue by now, but if you have any more questions or your issue stays unresolved - please just write in this thread and I will for sure get back to you this time.
