### ISSUE TITLE
TS types for select effect results

### ISSUE THREAD

**Issue by subvertallchris** [redux-saga/redux-saga#970]
Hey everyone, thank you for getting the improved TS definitions in! I had become accustomed to being extra careful with my saga code but having the compiler help a bit more is very refreshing.

Out of curiosity, I see that data yielded from `select` are still identified as `any`, so there's nothing to check that what comes out of `select` is correct. The best I can do is something like this:

```
const stateData: { foo: string } = yield select((state: MyState) => ({ foo: state.foo }))
```

This at least lets code relying on `stateData` have a sense of what should be in there but it's on me to ensure that it matches what comes from that `select`. Is there a better way to do this?

**Comment by Andarist** [comment]
cc @aikoven @dcolthorp

**Comment by dcolthorp** [comment]
That's about as good as it gets, AFAIK. I'm pretty sure yield always returns `any`, as it's fundamentally dynamic and in the control of whoever's calling `next`. So you definitely need to explicitly type `stateData` to my knowledge.

You could get a little more help by wrapping `select` with something like 

```ts
export function selectState<T>(selector: (s:State) => T): SelectEffect {
  return select(selector);
}
```

to at least enforce that you're using a function that selects on the right thing. This also gives you the option of explicitly annotating the return type, such as:

```ts
const stateData: SubType = yield selectState<SubType>(getSubType);
```

This is a little repetitive, but is easy to visually verify that the variable type and expected return type are the same, and doing so will let TypeScript enforce that `getSubType` returns the right thing, aiding refactoring.

Granted, the type argument is optional – you could simply `yield selectState(getSubType)` and rely on tests or runtime exceptions to identify a return type incompatibility, as with `select`. In this case, the type system will at least verify that `getSubType` takes an argument compatible with `State`, even if you aren't constraining the return type for compatibility with the type of `stateData`.

**Comment by subvertallchris** [comment]
Ah! That is great. It hadn't occurred to me to wrap `select` like that. I don't mind the repetition at all, safety and consistency are way more important as far as I'm concerned. Gonna close the issue since it doesn't seem like we can do more than this. Thanks for the suggestion!

**Comment by jedrichards** [comment]
@dcolthorp @subvertallchris How about this. Use the return type of the selector itself:

```
const foo: ReturnType<typeof getFoo> = yield select(getFoo)
```

**Comment by G2Jose** [comment]
You could also get the correct typings for free using

```
const foo = getFoo(yield select())
```

From the [docs](https://redux-saga.js.org/docs/api/#selectselector-args), 
> If select is called without argument (i.e. yield select()) then the effect is resolved with the entire state (the same result of a getState() call).

**Comment by newswim** [comment]
Typing for generators has improved quite a bit:

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html

It would be great to see functions like `select` correctly infer the return type from a selector.

**Comment by gitstud** [comment]
> You could also get the correct typings for free using
> 
> ```
> const foo = getFoo(yield select())
> ```
> 
> From the [docs](https://redux-saga.js.org/docs/api/#selectselector-args),
> 
> > If select is called without argument (i.e. yield select()) then the effect is resolved with the entire state (the same result of a getState() call).

The default return of getState still comes back as unknown, I tend to use my sagas as logic controllers that might look at a couple different pieces of state such as which modals are open to determine what a generic onPress is supposed to do, for this reason I normally just select the whole state

**Comment by psqq** [comment]
```ts
function* _select<T>(fn: (state: RootState) => T) {
  const res: T = yield select(fn);
  return res;
}

const selectCounter = (state: RootState) => state.counter;

function* action() {
  const counter = yield* _select(selectCounter);
  // ...
}
```

**Comment by pierpo** [comment]
> You could also get the correct typings for free using
> 
> ```
> const foo = getFoo(yield select())
> ```
> 
> From the [docs](https://redux-saga.js.org/docs/api/#selectselector-args),
> 
> > If select is called without argument (i.e. yield select()) then the effect is resolved with the entire state (the same result of a getState() call).

Thank you, works perfectly.

Is there any drawback with using this method?

It feels like there isn't but it would be great to be sure.

**Comment by d65yan** [comment]
> > You could also get the correct typings for free using
> > ```
> > const foo = getFoo(yield select())
> > ```
> > 
> > 
> > From the [docs](https://redux-saga.js.org/docs/api/#selectselector-args),
> > > If select is called without argument (i.e. yield select()) then the effect is resolved with the entire state (the same result of a getState() call).
> 
> Thank you, works perfectly.
> 
> Can you think of any drawbacks with using this method?
> 
> It feels like there isn't but it would be great to be sure.

There is actually, testing becomes a problem as now you'll need to provide an entire state to your provider when testing the saga hence breaking the isolation as you'll now need to be aware of the selectors implementation details.

**Comment by gkielyellation** [comment]
@Andarist Are we able to re-open this issue based on the updates to Typescript 3.6?

**Comment by Andarist** [comment]
@gkielyellation will this be fixed/improved by https://github.com/redux-saga/redux-saga/pull/2053 ?

**Comment by VladosK0k0s** [comment]
Create custom select generator:

export function* appSelect<TSelected>(
  selector: (state: RootState) => TSelected,
): Generator<any, TSelected, TSelected> {
  return yield select(selector);
}

And then you can call it like here:

const {data} = yield* appSelect((state) => state.User);

**Comment by olegvilkovdaterok** [comment]
This is my way:
```javascript
const { currentUser }: RootState = yield select();
```
