### ISSUE TITLE
Determine origin of Error from a race

### ISSUE THREAD

**Issue by Lucretiel** [redux-saga/redux-saga#973]
Currently I have something like this:

    function* mySaga(work1, work2) {
        let result1, result2
        try {
            { result1, result2 } = yield race({
                result1: call(work1),
                result2: call(work2),
            })
        } catch(err) {
            // ???
            return
        }
        if result1 {
            // ...
        } else {
            // ...
        }
    }
My question is about the `catch` block, with the question marks. Is there any way to determine which of my two workers threw the error? Would it be worth adding an extension option to `race` to make it possible to do so? For instance, a throw/reject error could be wrapped in a single-key object, just like the return value from the race is.

**Comment by Andarist** [comment]
Interesting, we could extend `err` somehow, wouldnt like to wrap it in `{ result1: err }` though as people expect `err` to be an instance of `Error`.

Would u like to propose a semantics? The best I can think off now is to add a property to the error by throwing it in with something like
```javascript
err.originEffect = 'key'
```

**Comment by Lucretiel** [comment]
Ah, yes. My original idea was to replace the error with `{[key]: error}` or `{origin: key, error: error}`, but I can see why people would want to have the error be an `Error` type, especially if exceptions bubble out.

I like the idea of attaching a property to the error. I'll see if I can write up a proposed impl.

I wrote a simple wrapper that implements the same idea, but I'd *much* rather it be an extension to `race`, because of how heavy the wrapper implementation is. It requires wrapping all of your race Effects in a whole `call`, with a whole wrapping generator for each one:

```javascript
export const raceErrOrigin = racers => race(
	mapValues(racers, (racer, key) => call(function*() {
		try { return (yield racer) }
		catch (e) { e.raceOrigin = key; throw e }
	}))
)
```
