### ISSUE TITLE
Creating Saga middleware without using import syntax

### ISSUE THREAD

**Issue by septagram** [redux-saga/redux-saga#978]
I'm currently reviving an old project of mine. I'd like to migrate it to React+Redux, and to use Saga. Problem is, currently the project is not set up to use ES6 module syntax: no Webpack, no Babel, no System.js, nothing. Just a bunch of `<script />` tags to load dependencies. So I can't do this:

    import createSagaMiddleware from 'redux-saga'

I'm most likely going to work on my build system reasonably soon, but would really appreciate if I could get started with Saga before that. I looked at the ReduxSaga object that's exported to `window`, but can't find anything that would help me create middleware.

Anything I can do to create middleware with my current setup? Or a workaround?

**Comment by Andarist** [comment]
R u using umd build from the dist directory? Gonna look into that once i get home

**Comment by septagram** [comment]
Currently I'm using the build from [CDNJS](https://cdnjs.com/libraries/redux-saga). Version there seems to match your latest release tag.

**Comment by Andarist** [comment]
`ReduxSaga.default` is what u r looking for ;)

**Comment by septagram** [comment]
Yes, I tried that:

```
const sagaMiddleware = ReduxSaga.default()
...
window.store = Redux.createStore (
	rootReducer,
	Redux.applyMiddleware (sagaMiddleware)
)

sagaMiddleware.runSaga (rootSaga)
```

And I'm getting `TypeError: sagaMiddleware.runSaga is not a function` :(

**Comment by septagram** [comment]
I also tried to download `redux-saga.min.js` from the repo and use instead of CDN, nothing changed.

**Comment by septagram** [comment]
Ah, now it was something obvious. I was running `.runSaga()`, and it's just `.run()`.

Thanks a lot for the help, it works ^_^

Say, if I'll make a pull request with a small update to the docs regarding this use case, would you merge it?

**Comment by Andarist** [comment]
Yeah, sure. Propose a change, always happy to improve docs

**Comment by septagram** [comment]
Here you go )
