### ISSUE TITLE
multi-casting actionChannels

### ISSUE THREAD

**Issue by anthonychung14** [redux-saga/redux-saga#979]
I saw from here that discussions around multicasting were in the works.
https://github.com/redux-saga/redux-saga/issues/820

Having only one legitimate subscriber to an actionChannel is not consistent with having multiple sagas responding to a simple yield take(action). Got stuck on it for awhile before I realized that I was 'losing' events since one saga would greedily take the action and others would not respond.

I find myself building actionChannels for multiple subscribers and a lot of connecting, 'master' sagas that take and dispatch to each interested saga.

Has anyone else encountered/worked around this problem another way?

**Comment by Andarist** [comment]
`multicast` is on its way, although as a primitive, didnt yet consider how to tie this to the `actionChannel`s though. We'll try to put more work into it in the near future so I can finally release it.

**Comment by Andarist** [comment]
@anthonychung14 if you need a multicast here - why do u need `actionChannel`? Cant u just `take` those actions? `actionChannel`'s true power is in buffering which doesnt play nicely with multicasting (and wont be supported).

**Comment by anthonychung14** [comment]
@Andarist the pattern I'm looking for is in having multiple sagas respond to the same actionChannel item that is taken from the queue. I buffer the items since I need to enforce serial completion of multiple api calls

**Comment by Andarist** [comment]
Cant u redispatch (put) it with other type?

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.

**Comment by navneet-g** [comment]
Hi @Andarist,
Did multicast made to the API yet? I looked up in APIs but could not find a reference.
https://redux-saga.js.org/docs/api/
Thanks,

**Comment by Andarist** [comment]
@navneet-g it's available in redux-saga@beta
