### ISSUE TITLE
SSR and pending sagas

### ISSUE THREAD

**Issue by budarin** [redux-saga/redux-saga#982]
Hi!

I have a problem with pending sagas on server side
```
function* watchNavigate() {
    while (true) {
        const { payload: { url } } = yield take(START_NAVIGATE_TO);

        yield history.pushState(null, '', url);

        yield put({
            type: NAVIGATE_TO,
            payload: getLocationInfo(url),
        });
    }
}

export default function* rootSagas() {
    yield all([
        fork(watchNavigate),
    ]);
}
```
in server script I run this saga like this:
```
const rootTask = store.runSaga(rootSagas);
...
rootTask.done
    .then(... 2nd render app...)
    .then(() => store.dispatch(END));
```
but render never occurs - Promise never resolves. rootTask.done - still pending
But if rewrite watchNavigate function like this ( remove while loop ):
```
function* watchNavigate() {
    // while (true) {
        const { payload: { url } } = yield take(START_NAVIGATE_TO);

        yield history.pushState(null, '', url);

        yield put({
            type: NAVIGATE_TO,
            payload: getLocationInfo(url),
        });
    // }
}
```
Promise resolves but it doesn't meet business logic rules - it runs only once instead for every START_NAVIGATE_TO action

Help me please

**Comment by budarin** [comment]
any idea?

**Comment by budarin** [comment]
Here maybe the core of the problem:

```
const task = store.runSaga(dynamicSagas);
sagas.done.then(....).catch(...).finally(...);
```
I've change code from Promise.all to sagas.done.then.... and got the Error:
```
Error TypeError: sagas.done.then(...).catch(...).finally is not a function
```

**Comment by Andarist** [comment]
You shouldnt wait with dispatching `END`, however u need to dispatch it in the suitable moment for u which I cannot really predict - in general u should do it as soon as possible once you are sure ur sagas are created and fetching what u need.

So the flow should be more like this:
```javascript
store.dispatch(END)
saga.done.then(() => {
  // rerender ur app and send it to the client
})
```

**Comment by budarin** [comment]
but in real-world example https://github.com/redux-saga/redux-saga/blob/master/examples/real-world/server.js  store.runSaga(rootSaga).done.then resolves before dispatching END

```
store.runSaga(rootSaga).done.then(() => {
        console.log('sagas complete')
        res.status(200).send(
          layout(
            renderToString(rootComp),
            JSON.stringify(store.getState())
          )
        )
      }).catch((e) => {
        console.log(e.message)
        res.status(500).send(e.message)
      })

      renderToString(rootComp)
      store.close()

```

**Comment by Andarist** [comment]
> but in real-world example https://github.com/redux-saga/redux-saga/blob/master/examples/real-world/server.js store.runSaga(rootSaga).done.then resolves before dispatching END

Not rly, notice that `END` is dispatched [here](https://github.com/redux-saga/redux-saga/blob/2d8efbc7408d789132a28a21017eae4ea465772d/examples/real-world/server.js#L73). And it causes `done` promise to resolve. 

The idea is that `END` will cause all ur sagas which are hanging on `take`s to finish. You need to structure ur app in a way that all ur initial data gets fetched during setup and no delayed `take`s are needed during SSR.

Code-splitting doesnt change much in this matter. You just need to structure ur logic so it can be handled reasonably on the server side, it doesnt matter what code-splitted code will be ran if all of ur modules follow the same structure making saga SSR possible.

**Comment by budarin** [comment]
you are right!
I've missed it. Thanks a lot!

**Comment by Andarist** [comment]
Gonna close this then, if you have any further question - just ask :)
