### ISSUE TITLE
Event Channel not emitting on listener callback

### ISSUE THREAD

**Issue by wilcoxky** [redux-saga/redux-saga#983]
Hi, I am trying to use an eventChannel but seem to be encountering an error when trying to emit from a listener's callback.

```javascript
export default function createComChannel() {
  return eventChannel(function(emitter) {
    const handleIncomingData = (data) => {
      console.log('Running handle callback');
      const data2 = 'fake data';
      emitter({ payload: data });
    }
    // Will run and emit to yield take(channel)
    const iv = setInterval(handleIncomingData, 1000);

    // Will run callback but will not trigger yield take(channel)
    let mockListener = NativeAppEventEmitter.addListener('newFakeData', handleIncomingData);
    return () => { 
      clearInterval(iv);
      NativeAppEventEmiiter.removeListener(mockListener);
    }
  });
}
```
Any help wiould be greatly appreciated!

**Comment by Andarist** [comment]
Well, if this `const iv = setInterval(handleIncomingData, 1000);` works it cannot be a bug on our side. Please check if your `addListener` works correctly.

**Comment by wilcoxky** [comment]
`addListener` is correctly firing and logging when an event is fired. It seems the `emitter`. I have tried using different Event Emitters with no luck as well.

**Comment by Andarist** [comment]
You can quick check demo I've prepared for you - https://codesandbox.io/s/2kL8D2pYK

Everything is working like expected in my opinion, you can fork this demo and change it so it reflects ur use case more accurately so I can help you with locating the problem.

**Comment by wilcoxky** [comment]
Thanks for the help, I forked and ran the code and it seems to be working as intended. I believe the problem is occurring because react native seems to be ignoring emitted events from non-mounted components.

**Comment by wilcoxky** [comment]
I will keep you updated if that was the cause of the issue. Thank you for the help!
