### ISSUE TITLE
Calling redux sagas sequentially from within another saga

### ISSUE THREAD

**Issue by bhagatali** [redux-saga/redux-saga#984]
Saga noob here. I tried to find the right way of doing this but am unable to come up with anything that solves my problem. So I am hoping someone can help answer my question.

I have a saga that makes an API call to get a decision. Based on the decision, I may do a redirect or dispatch another action that triggers another saga flow.

```
export default function* applicationFlow(action) {
  let data = { productInfo: {} };
  try {
    yield put(appStatusSwitch('busy', 'Processing', 'app-status.text.verifying'));
    const res = yield call(api.call, data);
    const decision = res.decision ? res.decision.toLowerCase() : null;

    yield put(appDecision(decision));

    switch (decision) {
      case 'question':
          yield put (appQuestions (res.questions));
          // redirect to questions page
          redirectTo ('/question-page');
        break;
      case 'pass':
      case 'fail': 
        //dispatch an action that does another flow..yield takeLatest(APP_SUBMIT, processApplicationFlow)
        yield put (submit ());
        break;
      default:
        redirectTo('/technical-difficulty');
    }
  }
  catch(e) {
    redirectTo('/technical-difficulty');
  }
  finally {
      yield put(appStatusSwitch('free'));
  }
}
```

In the flow above, how do I make the saga wait for the `yield put (submit ())` to complete before the flow in this generator goes on to the finally block? Is this a use case where I use `yield*`? I tried using `yield*` but I am not sure I am doing it right.

**Comment by neurosnap** [comment]
Greetings!

If you have middleware that makes the `redux.dispatch` function return a promise then you can use [put.resolve](https://redux-saga.js.org/docs/api/)

On the project I'm working on we do not so what we do is we turn the `put(submit())` into another saga:

```js
// saga
function* onSubmit() {
  // do some async stuff here
}

function* applicationFlow(action) {
  // get to the point where put(submit()) is called
  yield call(onSubmit); // this blocks flow until onSubmit is done
}
```

Is there any reason in particular why you need to wait until `submit` is finished?  Are you doing async stuff inside that action creator or do you just want to make sure it has hit your reducer?

**Comment by bhagatali** [comment]
@neurosnap apologies for not getting back to you earlier. I didn't have access to my work laptop the past few days. The reason we need to wait until the `submit` is because we have async stuff inside that action. 

Let me see if I can use the same approach you have going, because I am unable to use the `put.resolve`.

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.

**Comment by omerdn1** [comment]
This is something I've been trying to tackle with some different approaches but I don't like any if them, anyone got an interesting solution?
