### ISSUE TITLE
all() effect combinator throw "TypeError: (0 , _effects.all) is not a function"

### ISSUE THREAD

**Issue by unam3** [redux-saga/redux-saga#985]
0.15.3. Good ol' yield [] works fine
```
      const allResult = yield [
        call(
          updateGTIN,
          {
            payload: updateGTINPayload
          }
        ),
        call(
          createUpdate,
          {
            payload: createUpdatePayload,
          }
        )
      ]
```

Both forms of all() don't. Snippets below throw "TypeError: (0 , _effects.all) is not a function".
```
      const allResult = yield all([
        call(
          updateGTIN,
          {
            payload: updateGTINPayload
          }
        ),
        call(
          createUpdate,
          {
            payload: createUpdatePayload,
          }
        )
      ])
```

```
      const allResult = yield all({
        updateGTINResult: call(
          updateGTIN,
          {
            payload: updateGTINPayload
          }
        ),
        createUpdateResult: call(
          createUpdate,
          {
            payload: createUpdatePayload,
          }
        )
      })
```

**Comment by Andarist** [comment]
Are u sure that u are using `0.15+`? Im using `all` just fine. How do you import it?

**Comment by unam3** [comment]
```
$ yarn info redux-saga|grep version:
version: '0.15.3',
```

`import { put, call, all } from 'redux-saga/effects'`

**Comment by Andarist** [comment]
That's weird, are u geting deprecation warnings while using `yield [...]` ? Could u share ur setup on something like codesandbox.io or a repository I could check out?

**Comment by unam3** [comment]
No warnings. I've renamed node_modules, run `yarn install` and diff node_modules/dist/redux-saga.js with old one — they're identical.
Tried `yarn install --force` after — same error.
About code sharing — I will try after run code with debugger.

**Comment by unam3** [comment]
hm.
grep -nr version node_modules/redux-saga/
node_modules/redux-saga/package.json:3:  "version": "0.14.3",

Seems like this isn't redux-saga problem. Close it.

**Comment by reidpd** [comment]
But if one WERE getting warnings.... how would one fix this?
