### ISSUE TITLE
How to cancel "all"?

### ISSUE THREAD

**Issue by gajus** [redux-saga/redux-saga#988]
I have the following construct:

```js
export default function *(): Generator<*, *, *> {
  while (yield take(SET_START)) {
    const allTasks = yield all([
      fork(createRequestRoutine(GET_MOVIES, getMoviesRemote, setMovies, setError)),
      fork(watchNewSearchCriteria)
    ]);

    yield take(SET_STOP);

    yield cancel(allTasks);
  }
}

```

Attempting to `yield cancel(allTasks)` produces an error:

> uncaught at rootSaga 
>  at effects 
> Error: cancel(task): argument [object Object],[object Object] is not a valid Task object 
> (HINT: if you are getting this errors in tests, consider using createMockTask from redux-saga/utils)

It is not clear from the documentation how to cancel tasks forked using `all`.

**Comment by Andarist** [comment]
Should work with `yield cancel(...allTasks)` or `yield all(allTasks.map(task => cancel(task)))`. We'll try to add some docs info later.

**Comment by gajus** [comment]
Thank you
