### ISSUE TITLE
Forked from root, sagas execute only once

### ISSUE THREAD

**Issue by insonifi** [redux-saga/redux-saga#989]
I can't figure it out and need some help.

```
export default function* root() {
  yield call(auth); // I want to block here, until I get valid authentication

/** these have HTTP polling loops, which I don't want to start asynchronously */
  yield fork(hosts);
  yield fork(dashboard);
  yield fork(feedback);
  yield fork(nodes);
  yield fork(tasks);
  yield fork(jobs);
  yield fork(backup);
  yield fork(update);
  yield fork(security);
}

```

What I get:
`call` executes and blocks here, then all `fork` are executed. And I see them starting (as in one loop iteration). But then it stops, and doesn't respond.

If I replace `call` with `fork` all is fine.

**Comment by Andarist** [comment]
You would have to show example code of what you are forking here.

`fork` means that the task will be started in background - it doesnt mean it will live forever.

**Comment by insonifi** [comment]
I do understand that. But it does, when I replace `call` with `fork`.

Here's what I `call`:

```
export default function* () {
  yield call(api.getStatusNoAuth); //which is Promise wrapped XHR call
}
```

And that's one of `fork`ed sagas

```
function* runSyncNodeAndHealth() {
  const syncNodesAndHealthSaga = yield fork(syncNodesAndHealth);
  yield take(actions.NODE_SYNC_STOP);
  yield cancel(syncNodesAndHealthSaga);
}
…
function* syncNodesAndHealth() {
  while (looping) {
    yield* getAllNodesHealth(); //calls fetch for each node

    yield call(delay, SYNC_INTERVAL);
  }
}
…
export default function* () {
  …
  yield fork(takeLatest, actions.HEALTH_REQUEST, getAllNodesHealth);
  yield fork(takeLatest, actions.NODE_SYNC_START, runSyncNodeAndHealth);
  …
}
```

**Comment by neurosnap** [comment]
A couple of comments.

I don't think having multiple `takeLatest` in one generator is going to work the way you are expecting.  Generally `take*` need to be inside their own generators in a 1:1 mapping.

`while (looping) {` it looks like you're missing a variable not in your snippet.

**Comment by insonifi** [comment]
> I don't think having multiple takeLatest in one generator is going to work the way you are expecting. Generally `take*` need to be inside their own generators in a 1:1 mapping.

I'm not sure I'm getting that. What do you mean by "own generators"? How I can achieve that?

Do I need to fork dedicated generator with single `takeLatest` like that?
```
function* subscribe() {
  yield fork(takeLatest, pattern, callback);
}

function* () {
  yield fork(subscribe);
}
```

It is `const looping = true;` all over the place.

**Comment by insonifi** [comment]
I figured what's wrong. According to documentation [Troubleshooting](https://redux-saga.js.org/docs/Troubleshooting.html), saga will miss any action when it's blocked (e.g. by `call`). It seems that what's happening because, if I trigger manual action sagas continue to work as expected.
