### ISSUE TITLE
eventChannel runs only one time

### ISSUE THREAD

**Issue by phuongpt** [redux-saga/redux-saga#992]
```
export function* watchFetchMessages() {
  while (true) {
    const {data} = yield take(Types.FETCH_MESSAGES_REQUEST)
    yield call(chatFetchMessages, data)
  }
}

function * fetchMessages(data) {
  try {
    const ref = firebase.database().ref(`messages/${data.channelId}`)

    const channel = eventChannel(emit => {
      ref.on('value', snapshot => {
        emit(snapshot.val());
      });
      return () => ref.off();
    });

// I need this code here to handle data when it be changed, but It makes fetchMessages can't be 
called multiple times (It runs normally when I put this in watchFetchMessages above)
    while (true) {
      const messages = yield take(channel);
      yield  put(Actions.fetchMessagesSuccess(messages))
    }
  } catch (e) {
  } 
}
```
please give me a solution for this one
Thanks in advance

**Comment by Andarist** [comment]
Could u describe ur requirements? I can prepare working snippet for u with explanation how is it done. From the posted snippet something is looking off to me and I cannot quite understand what the problem is and how it should be fixed - for instance `watchFetchMessages` and `fetchMessages` both have `channel` but its not the same one.

**Comment by phuongpt** [comment]
hi @Andarist, I've just updated snippet. `fetchMessages` of that code will run only one time.
but this code works well, but I can't use it because I need to raise `Actions.fetchMessagesSuccess` when date be changed
```
export function* watchFetchMessages() {
  while (true) {
    const {data} = yield take(Types.FETCH_MESSAGES_REQUEST)
    const channel = yield call(chatFetchMessages, data)
    const messages = yield take(channel);
    yield  put(Actions.fetchMessagesSuccess(messages))
  }
}

function * fetchMessages(data) {
  try {
    const ref = firebase.database().ref(`messages/${data.channelId}`)

    const channel = eventChannel(emit => {
      ref.on('value', snapshot => {
        emit(snapshot.val());
      });
      return () => ref.off();
    });
    return channel;
  } catch (e) {
  } 
}
```

**Comment by Andarist** [comment]
could u describe in words what flow are u trying to achieve? in the second snippet [here](https://github.com/redux-saga/redux-saga/issues/992#issuecomment-302090259) i still dont know how u pass the `channel` and if thats the same one or not

**Comment by phuongpt** [comment]
I think it's quite same this one https://github.com/redux-saga/redux-saga/issues/587 , 
I want to listen the changing in
```
ref.on('value', snapshot => {
        emit(snapshot.val());
});
```
to call `yield put(Actions.fetchMessagesSuccess(messages))`

**Comment by Andarist** [comment]
so what u have now described, could have been done like this:
```js
function createChannel() {
	const ref = firebase.database().ref(`messages/${data.channelId}`)

	const channel = eventChannel(emit => {
		ref.on('value', snapshot => {
			emit(snapshot.val());
		});
		return () => ref.off();
	})	

	return channel
}

function* observeSuccesses() {
	const channel = createChannel()

	while (true) {
		const messages = yield take(channel)
		yield put(Actions.fetchMessagesSuccess(messages))
	}
}
``
but I feel there are some other requirements than this, as this example is quite basic

**Comment by phuongpt** [comment]
@Andarist it works for watching the changes, but also causes the main issue is I can't open another channel, this means can't call `createChannel` twice.

**Comment by phuongpt** [comment]
well, let me conclude this one like this:
1. can watching the changes, but can't fire twice
```
function createChannel(data) {
  return eventChannel(emit => {
    setTimeout(()=>{
      emit('message' + data);
    })
    return () => {};
  });
}
function* observeSuccesses() {
  const {data} = yield take(Types.FETCH_MESSAGES_REQUEST)
  const channel = createChannel(data);
  while(true) {
    const message = yield take(channel);
    console.log(message);
  }
}

```
2. can fire multiple times, but can't watch the changes
```
function* observeSuccesses() {
  while(true) {
    const {data} = yield take(Types.FETCH_MESSAGES_REQUEST)
    const channel = createChannel(data);
    const message = yield take(channel);
    console.log(message);
  }
}
```

**Comment by Andarist** [comment]
why would u like to create the same channel multiple times? it doesnt feel right in most cases, maybe ur use case should be delt with some other effects? like

```js
function fetchMessages(data) {
	return new Promise(resolve => {
		const ref = firebase.database().ref(`messages/${data.channelId}`)
		const cb = snapshot => {
			ref.off('value', cb)
			resolve(snapshot.val())
		}
		ref.on('value', cb)
	})
}


function* observeSuccesses() {
  const chan = yield actionChannel(Types.FETCH_MESSAGES_REQUEST, buffers.expanding())
  
  while(true) {
    const {data} = yield take(chan)    
    const messages = yield call(fetchMessages, data);
    yield put(Actions.fetchMessagesSuccess(messages))
  }
}
```

if there are some requirements beside what ive included in this snippet - please add them so i provide more help ;)

**Comment by phuongpt** [comment]
thanks @Andarist. I just want to fetch messages from channelIds and watching them. 
Basically it should like your snippet, but this solution doesn't work for watching the changes, sorry.

**Comment by Andarist** [comment]
ok, so I think I know ur requirements now, you need something like this
```js
function createChannel(data) {
	const ref = firebase.database().ref(`messages/${data.channelId}`)

	const channel = eventChannel(emit => {
		ref.on('value', snapshot => {
			emit(snapshot.val());
		});
		return () => ref.off();
	})	

	return channel
}

function* observeSuccesses(channel) {
	while (true) {
		const messages = yield take(channel)
		yield put(Actions.fetchMessagesSuccess(messages))
	}
}

function* watchRequests() {
	// neccessary if u need to provide cancelation logic
	const subscriptions = {}

	while (true) {
		const { data } = yield take(Types.FETCH_MESSAGES_REQUEST)
		const channel = createChannel(data)
		const task = yield fork(observeSuccesses, channel)
		subscriptions[data.channelId] = [channel, task]
	}	
}
```

**Comment by phuongpt** [comment]
this is great, almost solved my problem! I deeply appreciate your thoughtfulness @Andarist.

**Comment by cosmosof** [comment]
I want user to get automated props change from redux, how I supposed to trigger `observeSuccesses()` ?  I didn't get this listener concept right? I did wrote a few saga functions and all triggered competent level triggers, like button, componentDidMount etc. 
I supposed to get database path changes, without any user effort, how can I do it? like user gets follow request on foregrounded app, it will pop up right there through saga listening channels. @Andarist

**Comment by cosmosof** [comment]
this my other sagas:

```
export default function * root () {
  yield [
    takeLatest(StartupTypes.STARTUP, startup),
    takeLatest(LoginTypes.LOGIN_REQUEST, login),
    takeLatest(SignupTypes.SIGNUP_REQUEST, signup),
    takeLatest(QuestionsTypes.SAVE_ANSWERS, answer),
    takeLatest(HomeScreenTypes.SAVE_TOKEN, savetoken),
    takeLatest(HomeScreenTypes.SAVE_REQUEST, savetokentodb),
  ]
}
```
all connected to an action. where does my new  event listener `function* observeSuccesses()` sagas goes. 

I understand listener saga is different than those above. 
[http://developingthoughts.co.uk/live-data-with-firebase-and-redux-saga/](url)

![fb2](https://user-images.githubusercontent.com/7368238/34590208-3080753a-f183-11e7-90ba-ac9f4a4008aa.png)

**Comment by Andarist** [comment]
You can just start a saga with a `fork` or `call` (one is non-blocking and one is blocking). You do not have an action trigger to start a saga. Hope it helps, but I'm a little bit unsure what the exact problem of yours is - could you describe it some more? You can always join our gitter channel to ask questions and have more direct chat - or you can always reach out to me on Twitter.

**Comment by cosmosof** [comment]
For the record, I am just adding my working code here.
The difficulty here was listener saga runs, before  this completed: `  const userId = firebase.auth().currentUser.uid;
`  So I have to make `updatedItemSaga` wait for userId. 

```
export default function * root () {
  yield [
    takeLatest(StartupTypes.STARTUP, startup),
    takeLatest(LoginTypes.LOGIN_REQUEST, login),
    takeLatest(SignupTypes.SIGNUP_REQUEST, signup),
    takeLatest(QuestionsTypes.SAVE_ANSWERS, answer),
    takeLatest(HomeScreenTypes.SAVE_TOKEN, savetoken),
    takeLatest(HomeScreenTypes.SAVE_REQUEST, savetokentodb),
    fork(updatedItemSaga)
  ]
}
```
```
function createChannel (userId) {
    const ref = firebase.database().ref(`/matchrequest/${userId}/`)
    const channel = eventChannel(emit => {
        ref.on('value', snapshot => {
          emit(Object.keys(snapshot.val())[0]);
        });
        return () => ref.off();
      })	
    return channel; 
  };
 
  export function * updatedItemSaga () {
    function connect() {
      return new Promise(resolve => {
        firebase.auth().onAuthStateChanged(function (user) {
          if (user) {
            resolve(user.uid)
          } else {
            reject(console.log)
          }
        })
      });
    }

    const userId = yield call(connect);

    const channel = createChannel(userId);
    while(true) {
      const item = yield take(channel);
      yield put(HomeScreenActions.invitationSuccessed(item));
    }        
  } 
```
