### ISSUE TITLE
Action loop never stop

### ISSUE THREAD

**Issue by synchr0n123r** [redux-saga/redux-saga#996]
I build "follow button" for social network. This button will be on sidebar, profile page, and other component. 

This work fine except i got infinite loop action after click follow button. I already working for few days to get problem solutions for this problem.

This seem happen because parent component changed every time state changed. Problem gone when i move click handler on parent component, but this will make me write same code for same function in many files. Due of size of project, it will be expensive to manage on development/production.

Is anyone have proper solutions for this? 

And this is "features" of redux or bugs?

![screen shot 2017-05-20 at 12 10 02 am](https://cloud.githubusercontent.com/assets/25856838/26259024/5e5286b6-3cf1-11e7-9bdd-65a542ac61f0.png)

```
handleClick() {
	
		this.props.dispatch({
			type: "MEMBER_FOLLOW_ACTION",
			payload: {userId}
		})
		
	}
export default function* rootModule () {
  yield [
  	takeEvery("MEMBERS_LATEST_REQUESTED", getMembersLatest),
  	takeEvery("MEMBER_FOLLOW_ACTION", doFollow),
  ]

export function* doFollow(action) {
	while (true) {
		try {
			const data = yield call(api.doFollow, action.payload);
			yield put({type: "MEMBER_FOLLOW_ACTION", ...data});
		} catch (e) {
			console.log('follow user error')
		}
	}
}
}
```

**Comment by synchr0n123r** [comment]
Didn't work, i tried it before...

**Comment by klaygomes** [comment]
And remove or change (...) put({type: "MEBER_FOLLOW_ACTION"}) (..) 
Because each time you yield this effect it will be caught by takeEvery again, causing an endless loop

**Comment by Andarist** [comment]
@synchr0n123r u need to distinguish ur actions - u cannot listen in saga for action of type A and in the same listener dispatch the same type A cause it will trigger ur listener once again and so on - infinitely

You need to name those 2 differently or use something like:
```js
yield takeEvery(ac => ac.type === "MEMBER_FOLLOW_ACTION" && Object.keys(ac).length === 1, doFollow)
```

**Comment by erikvold** [comment]
@Andarist I think this issue can be closed now.

**Comment by erikvold** [comment]
@synchr0n123r have you been able to resolve the issue?

**Comment by synchr0n123r** [comment]
solved....
Thank you all for your help
