### ISSUE TITLE
Data from api becomes undefined after yield put

### ISSUE THREAD

**Issue by BojiBote** [redux-saga/redux-saga#998]
I want to make a call to an API and put the data I receive inside the store.

The console logs the correct response, however, the action that modifies state in "put" returns undefined.

Here is my code in sagas.js (using axios for the get request):

```
export function* getLocationsFromAPI(action) {
  try {
    const response = yield call(axios.get, action.payload);
    console.log(response);
    yield put({ type: types.GET_LOCATION_SUCCESS, data: response.data });
  } catch (error) {
    console.log('Error', error);
  }
}

export function* rootSaga() {
  yield takeLatest(types.GET_LOCATIONS, getLocationsFromAPI);
}

export default rootSaga;
```
Image: [console.log(response)](https://i.stack.imgur.com/CeIPy.png)

Here are the relevant action creators:

```
export function getLocations(payload) {
  return { type: types.GET_LOCATIONS, payload };
}

export function setLocationsData(data) {
  return { type: types.GET_LOCATION_SUCCESS, data };
}
```
Here is a snippet of the relevant reducer (using immutability-helper to set state):
```
case types.GET_LOCATION_SUCCESS:
  return update(state, {
    data: { $set: action.data },
  });
```
I am using json-server to mock my data, if it helps.

Also, this works in my component:
```
const test = [1, 2, 3];
this.props.dispatch(setLocationsData(test)); 
console.log(this.props.locationData); // returns [1, 2, 3], initial state was []
```
This doesn't:
```
this.props.dispatch(getLocations('locations')); 
console.log(this.props.locationData)// returns undefined, , initial state was []
```
The dispatch is being sent from componentDidMount().

Am I missing something? Is it a config issue (dev environment is webpack react-hot-loader, react-redux, redux and router)? I even tried using fetch over axios and I still get the same result.

**Comment by Andarist** [comment]
Ur fetching via axios happens asynchronously, so u wont have ur state updates immediately and available in the next synchronous line after dispatching `getLocations`.

It should come though at some later point in time and ur saga will dispatch `GET_LOCATION_SUCCESS`, making the data available

**Comment by ed-zm** [comment]
You wont see data available with `console.log` because it is asynchronous. The function waits for the yield call and pass the result to the next yield. So, in other words your function runs the console.log before the `response` is ready

**Comment by Andarist** [comment]
This thread got a little bit stale, so I'm closing it. If you need to discuss this further, please just reply back here.
